/**
 * Listening dialogues, played in the Dialogues game (js/games/dialogues.js):
 * a short conversation between two people is read aloud (one higher voice,
 * one lower) with the script hidden, then the learner answers questions about it.
 *
 * Numbers in the lines are written in Hangul (세 시 반, 사천오백 원), so the
 * speech reads them the Korean way. The answer options use digits (3시 30분,
 * 4,500원): you have to map what you heard to the number.
 *
 * Fields: id, topic (a topic id), level (1–3), scene (an emoji for the place),
 *         title { ko, en },
 *         speakers { A, B: { name, en, emoji, voice: 'high' | 'low' } },
 *         lines [{ who: 'A' | 'B', ko, en }],
 *         words (2–4 vocabulary refs, 'topic:id': the dialogue unlocks once they're learned),
 *         questions [{ q { ko, en }, options (3 × { ko, en }), answer (index of the
 *                      right option; the game shuffles them), line (0-based index of
 *                      the line with the answer, or a list), why (shown after answering) }].
 */
Mallang.content.registerDialogues([
  // ---------- Level 1 ----------
  {
    id: 'cafe-order',
    topic: 'cafe',
    level: 1,
    scene: '☕',
    title: { ko: '카페에서 주문하기', en: 'Ordering at a café' },
    speakers: {
      A: { name: '직원', en: 'Barista', emoji: '🧑‍🍳', voice: 'low' },
      B: { name: '서연', en: 'Seoyeon', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 뭐 드릴까요?', en: 'Welcome! What can I get you?' },
      { who: 'B', ko: '라테 한 잔하고 쿠키 하나 주세요.', en: 'A latte and a cookie, please.' },
      { who: 'A', ko: '죄송합니다. 쿠키는 지금 없어요.', en: 'I’m sorry, we don’t have any cookies right now.' },
      { who: 'B', ko: '아, 그럼 케이크 하나 주세요.', en: 'Oh, then a slice of cake, please.' },
      { who: 'A', ko: '네, 라테 한 잔하고 케이크 하나요.', en: 'Sure: one latte and one slice of cake.' },
    ],
    words: ['cafe:latte', 'cafe:cookie', 'cafe:cake', 'cafe:please'],
    questions: [
      {
        q: { ko: '서연 씨는 뭘 마셔요?', en: 'What does Seoyeon drink?' },
        options: [
          { ko: '라테', en: 'a latte' },
          { ko: '녹차', en: 'a green tea' },
          { ko: '주스', en: 'a juice' },
        ],
        answer: 0,
        line: 1,
        why: 'Seoyeon says 라테 한 잔하고 쿠키 하나 주세요: “A latte and a cookie, please.”',
      },
      {
        q: { ko: '서연 씨는 뭘 먹어요?', en: 'What does Seoyeon eat?' },
        options: [
          { ko: '케이크', en: 'cake' },
          { ko: '쿠키', en: 'a cookie' },
          { ko: '샌드위치', en: 'a sandwich' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'The barista says 쿠키는 지금 없어요 (“we don’t have cookies right now”), so Seoyeon changes her order: 그럼 케이크 하나 주세요, “then a slice of cake, please”.',
      },
    ],
  },
  {
    id: 'day-now',
    topic: 'day',
    level: 1,
    scene: '📱',
    title: { ko: '지금 뭐 해요?', en: 'What are you up to?' },
    speakers: {
      A: { name: '지수', en: 'Jisu', emoji: '👩', voice: 'high' },
      B: { name: '민수', en: 'Minsu', emoji: '👨', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '민수 씨, 지금 뭐 해요?', en: 'Minsu, what are you doing right now?' },
      { who: 'B', ko: '집에서 밥 먹어요. 왜요?', en: 'I’m eating at home. Why?' },
      { who: 'A', ko: '저 지금 카페에 있어요. 같이 커피 마셔요!', en: 'I’m at a café right now. Let’s have a coffee together!' },
      { who: 'B', ko: '미안해요. 오늘은 좀 피곤해요. 내일 어때요?', en: 'Sorry, I’m a bit tired today. How about tomorrow?' },
      { who: 'A', ko: '좋아요. 그럼 내일 봐요!', en: 'OK. See you tomorrow, then!' },
    ],
    words: ['day:now', 'day:eat', 'day:today', 'day:tomorrow'],
    questions: [
      {
        q: { ko: '민수 씨는 지금 뭐 해요?', en: 'What is Minsu doing right now?' },
        options: [
          { ko: '밥을 먹어요', en: 'He’s having a meal' },
          { ko: '커피를 마셔요', en: 'He’s having a coffee' },
          { ko: '게임을 해요', en: 'He’s playing a game' },
        ],
        answer: 0,
        line: 1,
        why: 'Minsu says 집에서 밥 먹어요: he’s eating at home. The coffee is Jisu’s idea: she’s the one at the café.',
      },
      {
        q: { ko: '두 사람은 언제 만나요?', en: 'When will they meet?' },
        options: [
          { ko: '내일', en: 'tomorrow' },
          { ko: '오늘', en: 'today' },
          { ko: '지금', en: 'right now' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Minsu says 오늘은 좀 피곤해요. 내일 어때요?: he’s tired today, so he suggests tomorrow. Jisu agrees: 내일 봐요!',
      },
    ],
  },
  {
    id: 'numbers-movie',
    topic: 'numbers',
    level: 1,
    scene: '🎬',
    title: { ko: '영화 몇 시예요?', en: 'What time is the movie?' },
    speakers: {
      A: { name: '유나', en: 'Yuna', emoji: '👧', voice: 'high' },
      B: { name: '성민', en: 'Seongmin', emoji: '👦', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '성민 씨, 영화 몇 시예요?', en: 'Seongmin, what time is the movie?' },
      { who: 'B', ko: '네 시예요.', en: 'It’s at four.' },
      { who: 'A', ko: '세 시요?', en: 'At three?' },
      { who: 'B', ko: '아니요, 네 시요. 지금 두 시예요.', en: 'No, at four. It’s two o’clock now.' },
      { who: 'A', ko: '아, 그럼 밥 먼저 먹어요!', en: 'Oh, then let’s eat first!' },
    ],
    words: ['numbers:oclock', 'numbers:howmany', 'numbers:three', 'numbers:four'],
    questions: [
      {
        q: { ko: '영화는 몇 시예요?', en: 'What time is the movie?' },
        options: [
          { ko: '4시', en: '4:00' },
          { ko: '3시', en: '3:00' },
          { ko: '2시', en: '2:00' },
        ],
        answer: 0,
        line: [1, 3],
        why: 'Seongmin says 네 시예요: four o’clock (넷 becomes 네 before 시). Yuna hears 세 시 (three), so he says it again: 아니요, 네 시요.',
      },
      {
        q: { ko: '지금 몇 시예요?', en: 'What time is it now?' },
        options: [
          { ko: '2시', en: '2:00' },
          { ko: '4시', en: '4:00' },
          { ko: '3시', en: '3:00' },
        ],
        answer: 0,
        line: 3,
        why: 'Seongmin says 지금 두 시예요: it’s two o’clock now (둘 becomes 두 before 시), so they have time to eat first.',
      },
    ],
  },
  {
    id: 'directions-meet',
    topic: 'directions',
    level: 1,
    scene: '🚉',
    title: { ko: '어디에 있어요?', en: 'Where are you?' },
    speakers: {
      A: { name: '지아', en: 'Jia', emoji: '👩‍🦱', voice: 'high' },
      B: { name: '준호', en: 'Junho', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '준호 씨, 지금 어디에 있어요?', en: 'Junho, where are you right now?' },
      { who: 'B', ko: '역 앞에 있어요. 지아 씨는요?', en: 'I’m in front of the station. What about you?' },
      { who: 'A', ko: '저는 역 뒤 카페에 있어요.', en: 'I’m at the café behind the station.' },
      { who: 'B', ko: '아, 역 뒤요? 그럼 제가 거기로 갈게요.', en: 'Oh, behind the station? Then I’ll come over there.' },
      { who: 'A', ko: '네, 카페에서 기다릴게요.', en: 'OK, I’ll wait in the café.' },
    ],
    words: ['directions:where', 'directions:front', 'directions:behind', 'directions:station'],
    questions: [
      {
        q: { ko: '준호 씨는 지금 어디에 있어요?', en: 'Where is Junho right now?' },
        options: [
          { ko: '역 앞', en: 'in front of the station' },
          { ko: '역 뒤', en: 'behind the station' },
          { ko: '카페', en: 'at the café' },
        ],
        answer: 0,
        line: 1,
        why: 'Junho says 역 앞에 있어요: “I’m in front of the station.” Jia is the one behind it (역 뒤), at the café.',
      },
      {
        q: { ko: '두 사람은 어디에서 만나요?', en: 'Where do they meet?' },
        options: [
          { ko: '역 뒤 카페', en: 'at the café behind the station' },
          { ko: '역 앞', en: 'in front of the station' },
          { ko: '역 앞 카페', en: 'at a café in front of the station' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'Jia is at 역 뒤 카페 (the café behind the station), and Junho says 제가 거기로 갈게요: “I’ll come over there.”',
      },
    ],
  },
  {
    id: 'past-yesterday',
    topic: 'past',
    level: 1,
    scene: '🗓️',
    title: { ko: '어제 뭐 했어요?', en: 'What did you do yesterday?' },
    speakers: {
      A: { name: '은지', en: 'Eunji', emoji: '👱‍♀️', voice: 'high' },
      B: { name: '태민', en: 'Taemin', emoji: '👨‍🦱', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '태민 씨, 어제 뭐 했어요?', en: 'Taemin, what did you do yesterday?' },
      { who: 'B', ko: '친구하고 카페에 갔어요. 샌드위치도 먹었어요.', en: 'I went to a café with a friend. We had sandwiches, too.' },
      { who: 'A', ko: '와, 맛있었어요?', en: 'Oh, were they good?' },
      { who: 'B', ko: '네, 진짜 맛있었어요. 은지 씨는요?', en: 'Yes, really good. What about you?' },
      { who: 'A', ko: '저는 그냥 집에서 잤어요. 너무 피곤했어요.', en: 'I just slept at home. I was so tired.' },
    ],
    words: ['past:whatdid', 'past:went', 'past:ate'],
    questions: [
      {
        q: { ko: '태민 씨는 어제 어디에 갔어요?', en: 'Where did Taemin go yesterday?' },
        options: [
          { ko: '카페', en: 'to a café' },
          { ko: '친구 집', en: 'to a friend’s house' },
          { ko: '학교', en: 'to school' },
        ],
        answer: 0,
        line: 1,
        why: 'Taemin says 친구하고 카페에 갔어요: he went to a café with (하고) a friend, not to a friend’s house.',
      },
      {
        q: { ko: '은지 씨는 어제 뭐 했어요?', en: 'What did Eunji do yesterday?' },
        options: [
          { ko: '집에서 잤어요', en: 'She slept at home' },
          { ko: '카페에 갔어요', en: 'She went to a café' },
          { ko: '샌드위치를 먹었어요', en: 'She had a sandwich' },
        ],
        answer: 0,
        line: 4,
        why: 'Eunji says 저는 그냥 집에서 잤어요: she just slept at home, because she was so tired (너무 피곤했어요). The café and the sandwiches were Taemin’s day.',
      },
    ],
  },

  // ---------- Level 2 ----------
  {
    id: 'day-getup',
    topic: 'day',
    level: 2,
    scene: '⏰',
    title: { ko: '몇 시에 일어나요?', en: 'What time do you get up?' },
    speakers: {
      A: { name: '소연', en: 'Soyeon', emoji: '👩‍💼', voice: 'high' },
      B: { name: '지훈', en: 'Jihoon', emoji: '👨‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '지훈 씨는 매일 몇 시에 일어나요?', en: 'Jihoon, what time do you get up every day?' },
      { who: 'B', ko: '여섯 시에 일어나요.', en: 'I get up at six.' },
      { who: 'A', ko: '와, 일찍 일어나네요! 왜요?', en: 'Wow, that’s early! Why?' },
      { who: 'B', ko: '회사가 좀 멀어요. 지하철로 한 시간 걸려요.', en: 'My office is quite far. It takes an hour by subway.' },
      { who: 'A', ko: '그래요? 저는 회사가 가까워요. 그래서 여덟 시에 일어나요.', en: 'Really? My office is close, so I get up at eight.' },
      { who: 'B', ko: '와, 부러워요!', en: 'Wow, I’m jealous!' },
    ],
    words: ['day:getup', 'day:everyday', 'day:company'],
    questions: [
      {
        q: { ko: '지훈 씨는 몇 시에 일어나요?', en: 'What time does Jihoon get up?' },
        options: [
          { ko: '6시', en: '6:00' },
          { ko: '8시', en: '8:00' },
          { ko: '7시', en: '7:00' },
        ],
        answer: 0,
        line: 1,
        why: 'Jihoon says 여섯 시에 일어나요: he gets up at six (여섯 = 6).',
      },
      {
        q: { ko: '지훈 씨는 왜 일찍 일어나요?', en: 'Why does Jihoon get up early?' },
        options: [
          { ko: '회사가 멀어서', en: 'His office is far away' },
          { ko: '아침에 운동해서', en: 'He works out in the morning' },
          { ko: '일이 많아서', en: 'He has a lot of work' },
        ],
        answer: 0,
        line: 3,
        why: 'Jihoon says 회사가 좀 멀어요. 지하철로 한 시간 걸려요: his office is far, an hour away by subway.',
      },
      {
        q: { ko: '소연 씨는 몇 시에 일어나요?', en: 'What time does Soyeon get up?' },
        options: [
          { ko: '8시', en: '8:00' },
          { ko: '6시', en: '6:00' },
          { ko: '7시', en: '7:00' },
        ],
        answer: 0,
        line: 4,
        why: 'Soyeon’s office is close (회사가 가까워요), so she says 그래서 여덟 시에 일어나요: she gets up at eight (여덟 = 8).',
      },
    ],
  },
  {
    id: 'people-photo',
    topic: 'people',
    level: 2,
    scene: '📷',
    title: { ko: '가족 사진', en: 'A family photo' },
    speakers: {
      A: { name: '하나', en: 'Hana', emoji: '👩', voice: 'high' },
      B: { name: '현우', en: 'Hyunwoo', emoji: '👨', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '현우 씨, 이거 우리 가족 사진이에요.', en: 'Hyunwoo, this is a photo of my family.' },
      { who: 'B', ko: '와! 이 사람은 누구예요?', en: 'Wow! Who’s this?' },
      { who: 'A', ko: '우리 언니예요. 언니는 선생님이에요.', en: 'That’s my older sister. She’s a teacher.' },
      { who: 'B', ko: '이 남자는요? 오빠예요?', en: 'And this guy? Is he your older brother?' },
      { who: 'A', ko: '아니요, 남동생이에요. 아직 학생이에요.', en: 'No, he’s my younger brother. He’s still a student.' },
      { who: 'B', ko: '진짜요? 키가 정말 커요!', en: 'Really? He’s so tall!' },
    ],
    words: ['people:unni', 'people:oppa', 'people:sibling', 'people:teacher'],
    questions: [
      {
        q: { ko: '하나 씨 언니는 뭐 해요?', en: 'What does Hana’s older sister do?' },
        options: [
          { ko: '선생님이에요', en: 'She’s a teacher' },
          { ko: '학생이에요', en: 'She’s a student' },
          { ko: '의사예요', en: 'She’s a doctor' },
        ],
        answer: 0,
        line: 2,
        why: 'Hana says 우리 언니예요. 언니는 선생님이에요: it’s her older sister, and she’s a teacher.',
      },
      {
        q: { ko: '사진 속 남자는 누구예요?', en: 'Who is the man in the photo?' },
        options: [
          { ko: '남동생', en: 'her younger brother' },
          { ko: '오빠', en: 'her older brother' },
          { ko: '남자 친구', en: 'her boyfriend' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Hyunwoo guesses 오빠예요? (her older brother?), but Hana says 아니요, 남동생이에요: he’s her younger brother.',
      },
      {
        q: { ko: '하나 씨 남동생은 뭐 해요?', en: 'What does Hana’s younger brother do?' },
        options: [
          { ko: '학생이에요', en: 'He’s a student' },
          { ko: '선생님이에요', en: 'He’s a teacher' },
          { ko: '회사원이에요', en: 'He’s an office worker' },
        ],
        answer: 0,
        line: 4,
        why: 'Hana says 아직 학생이에요: her younger brother is still a student.',
      },
    ],
  },
  {
    id: 'numbers-booking',
    topic: 'numbers',
    level: 2,
    scene: '📞',
    title: { ko: '식당 예약', en: 'Booking a table' },
    speakers: {
      A: { name: '직원', en: 'Staff', emoji: '🙋‍♀️', voice: 'high' },
      B: { name: '민준', en: 'Minjun', emoji: '🧔', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '네, 한강식당입니다.', en: 'Hello, Hangang Restaurant.' },
      { who: 'B', ko: '안녕하세요. 토요일 저녁에 예약되나요?', en: 'Hello. Can I book a table for Saturday evening?' },
      { who: 'A', ko: '네. 몇 분이세요?', en: 'Yes, of course. For how many people?' },
      { who: 'B', ko: '네 명이요. 일곱 시에 돼요?', en: 'Four. Is seven o’clock OK?' },
      { who: 'A', ko: '죄송합니다. 일곱 시는 자리가 없어요. 일곱 시 반 괜찮으세요?', en: 'I’m sorry, we have no tables at seven. Would seven thirty be all right?' },
      { who: 'B', ko: '네, 좋아요. 그럼 일곱 시 반에 갈게요.', en: 'Yes, that’s fine. We’ll come at seven thirty, then.' },
    ],
    words: ['numbers:saturday', 'numbers:people', 'numbers:half', 'numbers:howmany'],
    questions: [
      {
        q: { ko: '무슨 요일에 가요?', en: 'What day are they going?' },
        options: [
          { ko: '토요일', en: 'Saturday' },
          { ko: '일요일', en: 'Sunday' },
          { ko: '월요일', en: 'Monday' },
        ],
        answer: 0,
        line: 1,
        why: 'Minjun asks 토요일 저녁에 예약되나요?: “Can I book for Saturday evening?”',
      },
      {
        q: { ko: '몇 명이 가요?', en: 'How many people are going?' },
        options: [
          { ko: '4명', en: '4 people' },
          { ko: '7명', en: '7 people' },
          { ko: '3명', en: '3 people' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'The staff asks 몇 분이세요? (the polite way to ask how many people), and Minjun says 네 명이요: four people (넷 becomes 네 before 명).',
      },
      {
        q: { ko: '몇 시에 가요?', en: 'What time are they going?' },
        options: [
          { ko: '7시 30분', en: '7:30' },
          { ko: '7시', en: '7:00' },
          { ko: '8시', en: '8:00' },
        ],
        answer: 0,
        line: [4, 5],
        why: 'Seven is full (일곱 시는 자리가 없어요), so the staff offers 일곱 시 반, and Minjun says 일곱 시 반에 갈게요: they’ll come at 7:30.',
      },
    ],
  },
  {
    id: 'shopping-gift',
    topic: 'shopping',
    level: 2,
    scene: '🎁',
    title: { ko: '친구 선물', en: 'A present for a friend' },
    speakers: {
      A: { name: '점원', en: 'Shop assistant', emoji: '👩‍💼', voice: 'high' },
      B: { name: '동현', en: 'Donghyun', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 뭐 찾으세요?', en: 'Welcome! What are you looking for?' },
      { who: 'B', ko: '친구 선물이요. 이 모자 얼마예요?', en: 'A present for a friend. How much is this hat?' },
      { who: 'A', ko: '그 모자는 팔천 원이에요.', en: 'That hat is 8,000 won.' },
      { who: 'B', ko: '그럼 이 티셔츠는요?', en: 'And this T-shirt?' },
      { who: 'A', ko: '티셔츠는 구천오백 원이에요.', en: 'The T-shirt is 9,500 won.' },
      { who: 'B', ko: '음, 친구 사이즈를 몰라요. 그냥 모자 살게요.', en: 'Hmm, I don’t know my friend’s size. I’ll just get the hat.' },
    ],
    words: ['shopping:hat', 'shopping:tshirt', 'shopping:gift', 'shopping:buy'],
    questions: [
      {
        q: { ko: '동현 씨는 뭘 사요?', en: 'What does Donghyun buy?' },
        options: [
          { ko: '모자', en: 'a hat' },
          { ko: '티셔츠', en: 'a T-shirt' },
          { ko: '가방', en: 'a bag' },
        ],
        answer: 0,
        line: 5,
        why: 'Donghyun says 그냥 모자 살게요: “I’ll just get the hat.”',
      },
      {
        q: { ko: '모자는 얼마예요?', en: 'How much is the hat?' },
        options: [
          { ko: '8,000원', en: '8,000 won' },
          { ko: '9,500원', en: '9,500 won' },
          { ko: '8,500원', en: '8,500 won' },
        ],
        answer: 0,
        line: 2,
        why: 'The assistant says 그 모자는 팔천 원이에요: 8,000 won. 구천오백 원 (9,500 won) is the T-shirt.',
      },
      {
        q: { ko: '동현 씨는 왜 티셔츠를 안 사요?', en: 'Why doesn’t Donghyun buy the T-shirt?' },
        options: [
          { ko: '친구 사이즈를 몰라서', en: 'He doesn’t know his friend’s size' },
          { ko: '티셔츠가 비싸서', en: 'The T-shirt is too expensive' },
          { ko: '색깔이 안 예뻐서', en: 'He doesn’t like the colour' },
        ],
        answer: 0,
        line: 5,
        why: 'Donghyun says 친구 사이즈를 몰라요: he doesn’t know his friend’s size, so he gets the hat instead.',
      },
    ],
  },
  {
    id: 'feelings-tired',
    topic: 'feelings',
    level: 2,
    scene: '😪',
    title: { ko: '화났어요?', en: 'Are you angry?' },
    speakers: {
      A: { name: '나연', en: 'Nayeon', emoji: '👩‍🦰', voice: 'high' },
      B: { name: '재민', en: 'Jaemin', emoji: '👨‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '재민 씨, 혹시 화났어요?', en: 'Jaemin, are you angry or something?' },
      { who: 'B', ko: '아니요, 화 안 났어요. 그냥 좀 피곤해요.', en: 'No, I’m not angry. I’m just a bit tired.' },
      { who: 'A', ko: '왜요? 어제 늦게 잤어요?', en: 'Why? Did you go to bed late last night?' },
      { who: 'B', ko: '네. 요즘 일이 많아서 너무 바빠요.', en: 'Yes. I have so much work these days, I’m really busy.' },
      { who: 'A', ko: '아, 힘내요! 제가 커피 살게요.', en: 'Oh, hang in there! I’ll buy you a coffee.' },
      { who: 'B', ko: '와, 고마워요. 기분이 좋아졌어요.', en: 'Aw, thanks. I feel better already.' },
    ],
    words: ['feelings:tired', 'feelings:angry', 'feelings:busy', 'feelings:mood'],
    questions: [
      {
        q: { ko: '재민 씨는 화났어요?', en: 'Is Jaemin angry?' },
        options: [
          { ko: '아니요, 피곤해요', en: 'No, he’s tired' },
          { ko: '네, 화났어요', en: 'Yes, he’s angry' },
          { ko: '아니요, 슬퍼요', en: 'No, he’s sad' },
        ],
        answer: 0,
        line: 1,
        why: 'Nayeon asks 혹시 화났어요? (are you angry?), but Jaemin says 아니요, 화 안 났어요. 그냥 좀 피곤해요: he’s not angry, just a bit tired.',
      },
      {
        q: { ko: '재민 씨는 왜 바빠요?', en: 'Why is Jaemin busy?' },
        options: [
          { ko: '일이 많아서', en: 'He has a lot of work' },
          { ko: '숙제가 많아서', en: 'He has a lot of homework' },
          { ko: '시험이 있어서', en: 'He has an exam' },
        ],
        answer: 0,
        line: 3,
        why: 'Jaemin says 요즘 일이 많아서 너무 바빠요: he has a lot of work these days, so he’s very busy.',
      },
    ],
  },
  {
    id: 'weather-rain',
    topic: 'weather',
    level: 2,
    scene: '🌦️',
    title: { ko: '내일은 비가 와요', en: 'Rain tomorrow' },
    speakers: {
      A: { name: '민지', en: 'Minji', emoji: '👧', voice: 'high' },
      B: { name: '우진', en: 'Woojin', emoji: '👦', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '우진 씨, 오늘 날씨 진짜 좋아요!', en: 'Woojin, the weather’s really nice today!' },
      { who: 'B', ko: '네, 맑고 따뜻해요. 그런데 내일은 비가 와요.', en: 'Yes, it’s clear and warm. But it’s going to rain tomorrow.' },
      { who: 'A', ko: '진짜요? 내일 친구하고 자전거 타요.', en: 'Really? I’m going cycling with a friend tomorrow.' },
      { who: 'B', ko: '비가 많이 와요. 그냥 오늘 타세요!', en: 'It’s going to rain a lot. Just go today!' },
      { who: 'A', ko: '좋아요. 지금 친구한테 전화할게요.', en: 'Good idea. I’ll call my friend now.' },
    ],
    words: ['weather:weather', 'weather:clear', 'weather:warm', 'weather:raining'],
    questions: [
      {
        q: { ko: '내일 날씨는 어때요?', en: 'What will the weather be like tomorrow?' },
        options: [
          { ko: '비가 와요', en: 'It’s going to rain' },
          { ko: '맑아요', en: 'It’s going to be clear' },
          { ko: '눈이 와요', en: 'It’s going to snow' },
        ],
        answer: 0,
        line: 1,
        why: 'Woojin says 그런데 내일은 비가 와요: “but tomorrow it’s going to rain.” 맑고 따뜻해요 (clear and warm) is today.',
      },
      {
        q: { ko: '민지 씨는 언제 자전거를 타요?', en: 'When does Minji go cycling?' },
        options: [
          { ko: '오늘', en: 'today' },
          { ko: '내일', en: 'tomorrow' },
          { ko: '주말', en: 'at the weekend' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Minji planned to ride tomorrow (내일), but it’s going to rain, so Woojin says 그냥 오늘 타세요 (just go today) and she agrees: 좋아요.',
      },
    ],
  },

  // ---------- Level 3 ----------
  {
    id: 'cafe-recommend',
    topic: 'cafe',
    level: 3,
    scene: '🥤',
    title: { ko: '추천해 주세요', en: 'What do you recommend?' },
    speakers: {
      A: { name: '직원', en: 'Barista', emoji: '👩‍🍳', voice: 'high' },
      B: { name: '시우', en: 'Siwoo', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 주문하시겠어요?', en: 'Welcome! Are you ready to order?' },
      { who: 'B', ko: '뭐가 맛있어요? 추천해 주세요.', en: 'What’s good here? Can you recommend something?' },
      { who: 'A', ko: '딸기 라테 어떠세요? 좀 달지만 맛있어요.', en: 'How about a strawberry latte? It’s a bit sweet, but it’s delicious.' },
      { who: 'B', ko: '음, 저는 단 거 안 좋아해요. 아이스 아메리카노 주세요.', en: 'Hmm, I don’t like sweet things. An iced americano, please.' },
      { who: 'A', ko: '드시고 가세요?', en: 'Is that for here?' },
      { who: 'B', ko: '아니요, 포장해 주세요.', en: 'No, to go, please.' },
      { who: 'A', ko: '포장하시면 오백 원 할인돼요. 사천 원입니다.', en: 'If it’s to go, you get 500 won off. That’s 4,000 won.' },
      { who: 'B', ko: '와, 좋네요. 여기 카드요.', en: 'Oh, nice. Here’s my card.' },
    ],
    words: ['cafe:recommend', 'cafe:sweet', 'cafe:americano', 'cafe:togo'],
    questions: [
      {
        q: { ko: '시우 씨는 뭘 주문해요?', en: 'What does Siwoo order?' },
        options: [
          { ko: '아이스 아메리카노', en: 'an iced americano' },
          { ko: '딸기 라테', en: 'a strawberry latte' },
          { ko: '아이스 라테', en: 'an iced latte' },
        ],
        answer: 0,
        line: 3,
        why: 'Siwoo says 아이스 아메리카노 주세요: “An iced americano, please.” The strawberry latte (딸기 라테) is only the barista’s idea.',
      },
      {
        q: { ko: '시우 씨는 왜 딸기 라테를 안 마셔요?', en: 'Why doesn’t Siwoo have the strawberry latte?' },
        options: [
          { ko: '단 걸 안 좋아해서', en: 'He doesn’t like sweet things' },
          { ko: '너무 비싸서', en: 'It’s too expensive' },
          { ko: '딸기가 없어서', en: 'They’re out of strawberries' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'The barista says it’s 좀 달지만 맛있어요 (a bit sweet, but delicious), and Siwoo says 저는 단 거 안 좋아해요: he doesn’t like sweet things.',
      },
      {
        q: { ko: '시우 씨는 얼마를 내요?', en: 'How much does Siwoo pay?' },
        options: [
          { ko: '4,000원', en: '4,000 won' },
          { ko: '4,500원', en: '4,500 won' },
          { ko: '500원', en: '500 won' },
        ],
        answer: 0,
        line: 6,
        why: 'To go is 500 won off (포장하시면 오백 원 할인돼요), so the barista says 사천 원입니다: 4,000 won.',
      },
    ],
  },
  {
    id: 'shopping-market',
    topic: 'shopping',
    level: 3,
    scene: '👖',
    title: { ko: '좀 깎아 주세요', en: 'Can you knock a bit off?' },
    speakers: {
      A: { name: '예린', en: 'Yerin', emoji: '👩', voice: 'high' },
      B: { name: '사장님', en: 'Shop owner', emoji: '🧔', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '저기요, 이 바지가 좀 작아서요. 더 큰 거 있어요?', en: 'Excuse me, these trousers are a bit small. Do you have a bigger pair?' },
      { who: 'B', ko: '죄송해요. 검은색은 없지만 파란색은 있어요.', en: 'Sorry, not in black. But we have them in blue.' },
      { who: 'A', ko: '그럼 파란색으로 할게요. 얼마예요?', en: 'Then I’ll take the blue ones. How much are they?' },
      { who: 'B', ko: '삼만 오천 원이에요.', en: 'They’re 35,000 won.' },
      { who: 'A', ko: '좀 깎아 주세요.', en: 'Could you knock a bit off?' },
      { who: 'B', ko: '현금으로 하시면 삼만 원에 드릴게요.', en: 'If you pay cash, you can have them for 30,000 won.' },
      { who: 'A', ko: '좋아요. 그럼 현금으로 할게요.', en: 'Great. I’ll pay cash, then.' },
      { who: 'B', ko: '감사합니다. 또 오세요!', en: 'Thank you! Come again!' },
    ],
    words: ['shopping:trousers', 'shopping:blue', 'shopping:cash', 'shopping:discountplease'],
    questions: [
      {
        q: { ko: '예린 씨는 뭘 찾아요?', en: 'What is Yerin looking for?' },
        options: [
          { ko: '더 큰 바지', en: 'bigger trousers' },
          { ko: '더 작은 바지', en: 'smaller trousers' },
          { ko: '더 싼 바지', en: 'cheaper trousers' },
        ],
        answer: 0,
        line: 0,
        why: 'Yerin says 이 바지가 좀 작아서요. 더 큰 거 있어요?: these are a bit small, so she wants a bigger pair.',
      },
      {
        q: { ko: '예린 씨는 무슨 색 바지를 사요?', en: 'What colour trousers does Yerin buy?' },
        options: [
          { ko: '파란색', en: 'blue' },
          { ko: '검은색', en: 'black' },
          { ko: '빨간색', en: 'red' },
        ],
        answer: 0,
        line: [1, 2],
        why: 'The owner says 검은색은 없지만 파란색은 있어요: there’s no bigger pair in black, but there is one in blue. So Yerin says 그럼 파란색으로 할게요.',
      },
      {
        q: { ko: '예린 씨는 얼마를 내요?', en: 'How much does Yerin pay?' },
        options: [
          { ko: '30,000원', en: '30,000 won' },
          { ko: '35,000원', en: '35,000 won' },
          { ko: '3,500원', en: '3,500 won' },
        ],
        answer: 0,
        line: [5, 6],
        why: 'The price is 삼만 오천 원 (35,000 won), but the owner says 현금으로 하시면 삼만 원에 드릴게요 (30,000 won in cash), and Yerin pays cash.',
      },
    ],
  },
  {
    id: 'directions-subway',
    topic: 'directions',
    level: 3,
    scene: '🚇',
    title: { ko: '어떻게 가요?', en: 'How do I get there?' },
    speakers: {
      A: { name: '도윤', en: 'Doyun', emoji: '👨', voice: 'low' },
      B: { name: '수아', en: 'Sua', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '수아 씨 집에 어떻게 가요?', en: 'Sua, how do I get to your place?' },
      { who: 'B', ko: '지하철 이호선을 타고 시청역에서 내리세요.', en: 'Take subway Line 2 and get off at City Hall Station.' },
      { who: 'A', ko: '시청역이요? 몇 번 출구로 나가요?', en: 'City Hall? Which exit do I take?' },
      { who: 'B', ko: '삼 번 출구로 나와서 오 분쯤 걸어오세요.', en: 'Come out of Exit 3 and walk for about five minutes.' },
      { who: 'A', ko: '버스는 없어요?', en: 'Isn’t there a bus?' },
      { who: 'B', ko: '버스도 있지만 길이 많이 막혀요. 지하철이 더 빨라요.', en: 'There is, but the traffic is really bad. The subway is faster.' },
      { who: 'A', ko: '알겠어요. 그럼 지하철 타고 갈게요.', en: 'OK. Then I’ll take the subway.' },
    ],
    words: ['directions:howgo', 'directions:ride', 'directions:getoff', 'directions:exit'],
    questions: [
      {
        q: { ko: '도윤 씨는 몇 호선을 타요?', en: 'Which subway line does Doyun take?' },
        options: [
          { ko: '2호선', en: 'Line 2' },
          { ko: '3호선', en: 'Line 3' },
          { ko: '5호선', en: 'Line 5' },
        ],
        answer: 0,
        line: 1,
        why: 'Sua says 지하철 이호선을 타고…: take subway Line 2 (이 = 2).',
      },
      {
        q: { ko: '몇 번 출구로 나가요?', en: 'Which exit does he take?' },
        options: [
          { ko: '3번 출구', en: 'Exit 3' },
          { ko: '2번 출구', en: 'Exit 2' },
          { ko: '5번 출구', en: 'Exit 5' },
        ],
        answer: 0,
        line: 3,
        why: 'Sua says 삼 번 출구로 나와서: come out of Exit 3 (삼 = 3). 오 분 is the five-minute walk after that.',
      },
      {
        q: { ko: '도윤 씨는 왜 버스를 안 타요?', en: 'Why doesn’t Doyun take the bus?' },
        options: [
          { ko: '길이 막혀서', en: 'The traffic is bad' },
          { ko: '버스가 없어서', en: 'There’s no bus' },
          { ko: '너무 비싸서', en: 'It’s too expensive' },
        ],
        answer: 0,
        line: 5,
        why: 'Sua says 버스도 있지만 길이 많이 막혀요: there is a bus, but the traffic is bad, so the subway is faster.',
      },
    ],
  },
  {
    id: 'past-busan',
    topic: 'past',
    level: 3,
    scene: '🌊',
    title: { ko: '부산 여행', en: 'A trip to Busan' },
    speakers: {
      A: { name: '건우', en: 'Geonwoo', emoji: '🧑', voice: 'low' },
      B: { name: '지은', en: 'Jieun', emoji: '👱‍♀️', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '지은 씨, 주말에 뭐 했어요?', en: 'Jieun, what did you do at the weekend?' },
      { who: 'B', ko: '친구하고 부산에 여행 갔어요.', en: 'I went on a trip to Busan with a friend.' },
      { who: 'A', ko: '와, 부산이요? 날씨는 어땠어요?', en: 'Wow, Busan? How was the weather?' },
      { who: 'B', ko: '토요일은 비가 와서 추웠어요. 일요일은 맑았어요.', en: 'It rained on Saturday, so it was cold. Sunday was sunny.' },
      { who: 'A', ko: '바다에도 갔어요?', en: 'Did you go to the beach, too?' },
      { who: 'B', ko: '네, 일요일에 갔어요. 사진도 많이 찍었어요.', en: 'Yes, on Sunday. We took lots of photos, too.' },
      { who: 'A', ko: '맛있는 것도 먹었어요?', en: 'Did you eat anything nice?' },
      { who: 'B', ko: '네, 회를 먹었어요. 좀 비쌌지만 진짜 맛있었어요.', en: 'Yes, we had raw fish. It was a bit pricey, but really delicious.' },
    ],
    words: ['past:went', 'past:wascold', 'past:wasdelicious', 'weather:raining'],
    questions: [
      {
        q: { ko: '토요일 날씨는 어땠어요?', en: 'What was the weather like on Saturday?' },
        options: [
          { ko: '비가 왔어요', en: 'It rained' },
          { ko: '맑았어요', en: 'It was sunny' },
          { ko: '눈이 왔어요', en: 'It snowed' },
        ],
        answer: 0,
        line: 3,
        why: 'Jieun says 토요일은 비가 와서 추웠어요: it rained on Saturday, so it was cold.',
      },
      {
        q: { ko: '지은 씨는 언제 바다에 갔어요?', en: 'When did Jieun go to the beach?' },
        options: [
          { ko: '일요일', en: 'on Sunday' },
          { ko: '토요일', en: 'on Saturday' },
          { ko: '금요일', en: 'on Friday' },
        ],
        answer: 0,
        line: 5,
        why: 'Jieun says 네, 일요일에 갔어요: they went on Sunday, the sunny day (일요일은 맑았어요).',
      },
      {
        q: { ko: '회는 어땠어요?', en: 'How was the raw fish?' },
        options: [
          { ko: '비쌌지만 맛있었어요', en: 'Pricey, but delicious' },
          { ko: '싸고 맛있었어요', en: 'Cheap and delicious' },
          { ko: '비싸고 맛없었어요', en: 'Pricey and not good' },
        ],
        answer: 0,
        line: 7,
        why: 'Jieun says 좀 비쌌지만 진짜 맛있었어요: it was a bit expensive, but (-지만) really delicious.',
      },
    ],
  },
  {
    id: 'hobbies-weekend',
    topic: 'hobbies',
    level: 3,
    scene: '🏊',
    title: { ko: '주말에 뭐 해요?', en: 'What do you do at weekends?' },
    speakers: {
      A: { name: '다은', en: 'Daeun', emoji: '👧', voice: 'high' },
      B: { name: '민호', en: 'Minho', emoji: '👦', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '민호 씨는 주말에 보통 뭐 해요?', en: 'Minho, what do you usually do at weekends?' },
      { who: 'B', ko: '날씨가 좋으면 등산해요. 다은 씨는요?', en: 'If the weather’s nice, I go hiking. What about you?' },
      { who: 'A', ko: '저는 집에서 그림을 그려요. 요즘은 수영도 배우고 싶어요.', en: 'I draw at home. And these days I’d like to learn to swim, too.' },
      { who: 'B', ko: '수영이요? 저는 작년에 배웠어요.', en: 'Swimming? I learned last year.' },
      { who: 'A', ko: '진짜요? 어려웠어요?', en: 'Really? Was it hard?' },
      { who: 'B', ko: '처음에는 무서웠지만 지금은 재미있어요.', en: 'At first it was scary, but now it’s fun.' },
      { who: 'A', ko: '그럼 다음 주에 같이 수영장에 가요!', en: 'Then let’s go to the pool together next week!' },
      { who: 'B', ko: '좋아요. 제가 가르쳐 줄게요.', en: 'Sure. I’ll teach you.' },
    ],
    words: ['hobbies:hiking', 'hobbies:swim', 'hobbies:draw', 'hobbies:wanttolearn'],
    questions: [
      {
        q: { ko: '민호 씨는 주말에 보통 뭐 해요?', en: 'What does Minho usually do at weekends?' },
        options: [
          { ko: '등산해요', en: 'He goes hiking' },
          { ko: '그림을 그려요', en: 'He draws' },
          { ko: '수영을 배워요', en: 'He takes swimming lessons' },
        ],
        answer: 0,
        line: 1,
        why: 'Minho says 날씨가 좋으면 등산해요: if the weather’s nice, he goes hiking. Drawing is Daeun’s hobby, and he learned to swim last year.',
      },
      {
        q: { ko: '민호 씨는 처음에 수영이 어땠어요?', en: 'How did Minho find swimming at first?' },
        options: [
          { ko: '무서웠어요', en: 'It was scary' },
          { ko: '재미있었어요', en: 'It was fun' },
          { ko: '쉬웠어요', en: 'It was easy' },
        ],
        answer: 0,
        line: 5,
        why: 'Minho says 처음에는 무서웠지만 지금은 재미있어요: at first it was scary, but (-지만) now it’s fun.',
      },
      {
        q: { ko: '두 사람은 다음 주에 뭐 해요?', en: 'What will they do next week?' },
        options: [
          { ko: '같이 수영장에 가요', en: 'Go to the pool together' },
          { ko: '같이 등산해요', en: 'Go hiking together' },
          { ko: '같이 그림을 그려요', en: 'Draw together' },
        ],
        answer: 0,
        line: [6, 7],
        why: 'Daeun says 그럼 다음 주에 같이 수영장에 가요!, and Minho agrees; he’ll even teach her (제가 가르쳐 줄게요).',
      },
    ],
  },
  {
    id: 'travel-bus-ticket',
    topic: 'travel',
    level: 2,
    scene: '🚍',
    title: { ko: '버스가 벌써 출발했어요?', en: 'Has the bus already left?' },
    speakers: {
      A: { name: '직원', en: 'Ticket clerk', emoji: '👩‍💼', voice: 'high' },
      B: { name: '현수', en: 'Hyunsu', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 어디 가세요?', en: 'Hello! Where are you going?' },
      { who: 'B', ko: '강릉이요. 세 시 버스 벌써 출발했어요?', en: 'Gangneung. Has the three o’clock bus already left?' },
      { who: 'A', ko: '네, 오 분 전에 출발했어요.', en: 'Yes, it left five minutes ago.' },
      { who: 'B', ko: '아, 늦었네요! 다음 버스는 몇 시에 있어요?', en: 'Oh no, I’m too late! When’s the next bus?' },
      { who: 'A', ko: '네 시 버스는 자리가 없어요. 네 시 반 버스 괜찮으세요?', en: 'The four o’clock is full. Is the four-thirty all right?' },
      { who: 'B', ko: '네, 괜찮아요. 네 시 반 버스로 표 한 장 주세요.', en: 'Yes, that’s fine. One ticket for the four-thirty, please.' },
      { who: 'A', ko: '여기 있습니다. 칠 번 타는 곳으로 가세요.', en: 'Here you are. Please go to boarding gate 7.' },
    ],
    words: ['travel:ticket', 'travel:sheet', 'travel:depart'],
    questions: [
      {
        q: { ko: '세 시 버스는 어떻게 됐어요?', en: 'What happened to the three o’clock bus?' },
        options: [
          { ko: '벌써 출발했어요', en: 'It has already left' },
          { ko: '자리가 없어요', en: 'It’s full' },
          { ko: '5분 후에 출발해요', en: 'It leaves in five minutes' },
        ],
        answer: 0,
        line: [1, 2],
        why: 'Hyunsu asks 세 시 버스 벌써 출발했어요?, and the clerk says 네, 오 분 전에 출발했어요: it left five minutes ago (전 = before). It’s the four o’clock bus that’s full (자리가 없어요).',
      },
      {
        q: { ko: '현수 씨는 몇 시 버스를 타요?', en: 'Which bus does Hyunsu take?' },
        options: [
          { ko: '4시 30분', en: 'the 4:30' },
          { ko: '4시', en: 'the 4:00' },
          { ko: '3시', en: 'the 3:00' },
        ],
        answer: 0,
        line: [4, 5],
        why: 'The clerk says 네 시 버스는 자리가 없어요 (the 4:00 is full) and offers 네 시 반 버스, the 4:30. Hyunsu takes it: 네 시 반 버스로 표 한 장 주세요. The 3:00 has already left.',
      },
      {
        q: { ko: '버스는 몇 번 타는 곳에서 타요?', en: 'Which gate does Hyunsu’s bus leave from?' },
        options: [
          { ko: '7번', en: 'gate 7' },
          { ko: '5번', en: 'gate 5' },
          { ko: '4번', en: 'gate 4' },
        ],
        answer: 0,
        line: 6,
        why: 'The clerk says 칠 번 타는 곳으로 가세요: go to boarding gate 7 (칠 = 7). 오 (5) was the five minutes, and 네 (4) the time of the buses (네 시, 네 시 반).',
      },
    ],
  },
  {
    id: 'health-doctor',
    topic: 'health',
    level: 2,
    scene: '🩺',
    title: { ko: '어디가 아프세요?', en: 'Where does it hurt?' },
    speakers: {
      A: { name: '의사', en: 'Doctor', emoji: '🧑‍⚕️', voice: 'low' },
      B: { name: '하은', en: 'Haeun', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '어디가 아프세요?', en: 'What seems to be the problem?' },
      { who: 'B', ko: '열이 나고 목이 아파요.', en: 'I have a fever and a sore throat.' },
      { who: 'A', ko: '언제부터 아팠어요?', en: 'How long have you been ill?' },
      { who: 'B', ko: '어제 저녁부터요. 기침도 조금 해요.', en: 'Since yesterday evening. I’m coughing a bit, too.' },
      { who: 'A', ko: '감기예요. 약은 하루에 세 번 드세요.', en: 'It’s a cold. Take your medicine three times a day.' },
      { who: 'B', ko: '네 번이요?', en: 'Four times?' },
      { who: 'A', ko: '아니요, 세 번이요. 그리고 집에서 푹 쉬세요.', en: 'No, three times. And get plenty of rest at home.' },
      { who: 'B', ko: '네, 알겠습니다. 감사합니다.', en: 'All right. Thank you.' },
    ],
    words: ['health:fever', 'health:throat', 'health:day', 'health:rest'],
    questions: [
      {
        q: { ko: '하은 씨는 어디가 아파요?', en: 'Where is Haeun in pain?' },
        options: [
          { ko: '목', en: 'her throat' },
          { ko: '머리', en: 'her head' },
          { ko: '배', en: 'her stomach' },
        ],
        answer: 0,
        line: 1,
        why: 'Haeun says 열이 나고 목이 아파요: she has a fever (열이 나요), and her throat hurts (목이 아파요).',
      },
      {
        q: { ko: '약은 하루에 몇 번 먹어요?', en: 'How many times a day does she take the medicine?' },
        options: [
          { ko: '3번', en: '3 times' },
          { ko: '4번', en: '4 times' },
          { ko: '2번', en: 'twice' },
        ],
        answer: 0,
        line: [4, 5, 6],
        why: 'The doctor says 하루에 세 번 (three times a day: 셋 becomes 세 before 번). Haeun thinks she heard 네 번 (four times), so the doctor says it again: 아니요, 세 번이요.',
      },
      {
        q: { ko: '의사는 또 뭐라고 해요?', en: 'What else does the doctor tell her?' },
        options: [
          { ko: '집에서 푹 쉬세요', en: 'Get plenty of rest at home' },
          { ko: '물을 많이 드세요', en: 'Drink lots of water' },
          { ko: '내일 또 오세요', en: 'Come back tomorrow' },
        ],
        answer: 0,
        line: 6,
        why: 'After the medicine, the doctor says 그리고 집에서 푹 쉬세요: “and get plenty of rest at home.”',
      },
    ],
  },
  {
    id: 'work-firstday',
    topic: 'work',
    level: 2,
    scene: '🏢',
    title: { ko: '첫날 어땠어요?', en: 'How was your first day?' },
    speakers: {
      A: { name: '지은', en: 'Jieun', emoji: '👩‍💼', voice: 'high' },
      B: { name: '마크', en: 'Mark', emoji: '🧑‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '마크 씨, 첫날 어땠어요?', en: 'Mark, how was your first day?' },
      { who: 'B', ko: '좀 떨렸어요. 그래도 동료들이 다 친절해요.', en: 'I was a bit nervous. But all my colleagues are kind.' },
      { who: 'A', ko: '다행이에요. 아, 내일 아침 아홉 시에 회의가 있어요.', en: 'I’m glad. Oh, there’s a meeting at nine tomorrow morning.' },
      { who: 'B', ko: '아홉 시요? 회의는 어디에서 해요?', en: 'At nine? Where’s the meeting?' },
      { who: 'A', ko: '삼 층 회의실이에요. 늦지 마세요!', en: 'In the meeting room on the third floor. Don’t be late!' },
      { who: 'B', ko: '네, 알겠습니다. 그럼 먼저 가 보겠습니다.', en: 'OK, got it. Well, I’ll be off now.' },
      { who: 'A', ko: '네, 수고하셨습니다. 내일 봐요!', en: 'OK, thanks for your hard work. See you tomorrow!' },
    ],
    words: ['work:firstday', 'work:meeting', 'work:colleague', 'work:thanksforwork'],
    questions: [
      {
        q: { ko: '마크 씨는 첫날 어땠어요?', en: 'How was Mark’s first day?' },
        options: [
          { ko: '좀 떨렸어요', en: 'He was a bit nervous' },
          { ko: '재미없었어요', en: 'It was boring' },
          { ko: '힘들었어요', en: 'It was hard work' },
        ],
        answer: 0,
        line: 1,
        why: 'Mark says 좀 떨렸어요: he was a bit nervous (떨리다). But it went well: 동료들이 다 친절해요, his colleagues are all kind.',
      },
      {
        q: { ko: '내일 회의는 몇 시에 해요?', en: 'What time is tomorrow’s meeting?' },
        options: [
          { ko: '9시', en: '9:00' },
          { ko: '3시', en: '3:00' },
          { ko: '10시', en: '10:00' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'Jieun says 내일 아침 아홉 시에 회의가 있어요: the meeting is at nine a.m. (아홉 = 9), and Mark checks: 아홉 시요? The 3 (삼) is the floor: 삼 층 회의실.',
      },
      {
        q: { ko: '마크 씨는 퇴근해요. 뭐라고 인사해요?', en: 'Mark is leaving work. What does he say?' },
        options: [
          { ko: '먼저 가 보겠습니다', en: 'I’ll be off now (before you)' },
          { ko: '수고하세요', en: 'Keep up the good work' },
          { ko: '잘 부탁드립니다', en: 'I look forward to working with you' },
        ],
        answer: 0,
        line: 5,
        why: 'Mark is leaving before Jieun (먼저 = first), so he says 그럼 먼저 가 보겠습니다: “Well, I’ll be off now.” Jieun answers 수고하셨습니다: thanks for your hard work.',
      },
    ],
  },

  // ---------- More dialogues: level 1 ----------
  {
    id: 'shopping-no-bags',
    topic: 'shopping',
    level: 1,
    scene: '🧦',
    title: { ko: '가방도 팔아요?', en: 'Do you sell bags?' },
    speakers: {
      A: { name: '유진', en: 'Yujin', emoji: '👩', voice: 'high' },
      B: { name: '점원', en: 'Shop assistant', emoji: '🧑‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '저기요, 여기 가방도 팔아요?', en: 'Excuse me, do you sell bags here too?' },
      { who: 'B', ko: '아니요, 가방은 안 팔아요. 옷하고 양말만 팔아요.', en: 'No, we don’t sell bags. Just clothes and socks.' },
      { who: 'A', ko: '아, 그럼 이 양말 주세요. 가방은 어디에서 팔아요?', en: 'Oh. Then I’ll take these socks. Where do they sell bags?' },
      { who: 'B', ko: '저 가게에서 팔아요. 거기 가방이 싸고 예뻐요.', en: 'That shop over there sells them. Their bags are cheap and pretty.' },
      { who: 'A', ko: '네, 감사합니다!', en: 'OK, thank you!' },
    ],
    words: ['shopping:bag', 'shopping:sell', 'shopping:socks', 'shopping:shop'],
    questions: [
      {
        q: { ko: '유진 씨는 이 가게에서 뭘 사요?', en: 'What does Yujin buy in this shop?' },
        options: [
          { ko: '양말', en: 'socks' },
          { ko: '가방', en: 'a bag' },
          { ko: '옷', en: 'clothes' },
        ],
        answer: 0,
        line: [1, 2],
        why: 'This shop doesn’t sell bags (가방은 안 팔아요), only clothes and socks (옷하고 양말만). So Yujin says 그럼 이 양말 주세요: “then I’ll take these socks.”',
      },
      {
        q: { ko: '가방은 어디에서 팔아요?', en: 'Where do they sell bags?' },
        options: [
          { ko: '저 가게', en: 'at that shop over there' },
          { ko: '이 가게', en: 'in this shop' },
          { ko: '역 앞 가게', en: 'at a shop in front of the station' },
        ],
        answer: 0,
        line: 3,
        why: 'The assistant says 저 가게에서 팔아요: that shop over there (저 = over there) sells them, and its bags are cheap and pretty (싸고 예뻐요).',
      },
    ],
  },
  {
    id: 'health-toothache',
    topic: 'health',
    level: 1,
    scene: '🦷',
    title: { ko: '왜 점심 안 먹어요?', en: 'Why aren’t you eating?' },
    speakers: {
      A: { name: '가은', en: 'Gaeun', emoji: '👩‍💼', voice: 'high' },
      B: { name: '준서', en: 'Junseo', emoji: '👨‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '준서 씨, 왜 점심 안 먹어요? 배 아파요?', en: 'Junseo, why aren’t you eating your lunch? Have you got a stomachache?' },
      { who: 'B', ko: '아니요, 이가 아파요.', en: 'No, I’ve got a toothache.' },
      { who: 'A', ko: '아이고, 약은 먹었어요?', en: 'Oh no! Have you taken any medicine?' },
      { who: 'B', ko: '네, 아침에 먹었어요. 그런데 아직 아파요.', en: 'Yes, this morning. But it still hurts.' },
      { who: 'A', ko: '그럼 오늘 치과에 가 보세요.', en: 'Then go and see a dentist today.' },
    ],
    words: ['health:toothache', 'health:medicine', 'health:stomach'],
    questions: [
      {
        q: { ko: '준서 씨는 어디가 아파요?', en: 'What’s hurting Junseo?' },
        options: [
          { ko: '이가 아파요', en: 'He has a toothache' },
          { ko: '배가 아파요', en: 'He has a stomachache' },
          { ko: '머리가 아파요', en: 'He has a headache' },
        ],
        answer: 0,
        line: [0, 1],
        why: 'Gaeun guesses 배 아파요? (is it your stomach?), but Junseo says 아니요, 이가 아파요: no, it’s his tooth (이) that hurts.',
      },
      {
        q: { ko: '가은 씨는 뭐라고 해요?', en: 'What does Gaeun tell him to do?' },
        options: [
          { ko: '치과에 가 보세요', en: 'Go to the dentist' },
          { ko: '약을 드세요', en: 'Take some medicine' },
          { ko: '점심을 드세요', en: 'Eat your lunch' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Junseo took medicine this morning (아침에 먹었어요), but it still hurts (아직 아파요). So Gaeun says 그럼 오늘 치과에 가 보세요: go to the dentist (치과) today.',
      },
    ],
  },
  {
    id: 'travel-taxi-passport',
    topic: 'travel',
    level: 1,
    scene: '🚕',
    title: { ko: '택시에서', en: 'In a taxi' },
    speakers: {
      A: { name: '엠마', en: 'Emma', emoji: '👱‍♀️', voice: 'high' },
      B: { name: '기사님', en: 'Driver', emoji: '👨‍🦳', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '기사님, 공항으로 가 주세요.', en: 'To the airport, please.' },
      { who: 'B', ko: '네. 몇 시 비행기예요?', en: 'Sure. What time is your flight?' },
      { who: 'A', ko: '세 시예요. 어? 잠깐만요! 여권이 없어요!', en: 'At three. Oh! Wait! I haven’t got my passport!' },
      { who: 'B', ko: '어떡해요! 그럼 어디로 갈까요?', en: 'Oh no! So where shall I take you?' },
      { who: 'A', ko: '먼저 호텔로 가 주세요. 여권이 호텔에 있어요.', en: 'To the hotel first, please. My passport’s at the hotel.' },
    ],
    words: ['travel:takemeto', 'travel:airport', 'travel:passport', 'travel:hotel'],
    questions: [
      {
        q: { ko: '엠마 씨는 뭐가 없어요?', en: 'What hasn’t Emma got with her?' },
        options: [
          { ko: '여권', en: 'her passport' },
          { ko: '표', en: 'her ticket' },
          { ko: '가방', en: 'her bag' },
        ],
        answer: 0,
        line: 2,
        why: 'Emma suddenly says 여권이 없어요! (I haven’t got my passport!): it’s still at the hotel (여권이 호텔에 있어요).',
      },
      {
        q: { ko: '택시는 먼저 어디로 가요?', en: 'Where does the taxi go first?' },
        options: [
          { ko: '호텔', en: 'to the hotel' },
          { ko: '공항', en: 'to the airport' },
          { ko: '역', en: 'to the station' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Emma first asks for the airport (공항으로 가 주세요), but her passport is at the hotel. So she says 먼저 호텔로 가 주세요: “to the hotel first, please.”',
      },
    ],
  },

  // ---------- More dialogues: level 2 ----------
  {
    id: 'cafe-wrong-order',
    topic: 'cafe',
    level: 2,
    scene: '🍪',
    title: { ko: '주문이 잘못 나왔어요', en: 'The wrong order' },
    speakers: {
      A: { name: '직원', en: 'Barista', emoji: '👩‍🍳', voice: 'high' },
      B: { name: '태윤', en: 'Taeyun', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '주문하신 아이스 아메리카노 두 잔 나왔습니다.', en: 'Here’s your order: two iced americanos.' },
      { who: 'B', ko: '어? 한 잔은 뜨거운 걸로 주문했어요.', en: 'Oh? I ordered one of them hot.' },
      { who: 'A', ko: '아, 정말 죄송합니다. 금방 다시 만들어 드릴게요.', en: 'Oh, I’m so sorry. I’ll make it again for you right away.' },
      { who: 'B', ko: '괜찮아요. 오래 걸려요?', en: 'That’s OK. Will it take long?' },
      { who: 'A', ko: '아니요, 삼 분이면 돼요. 그리고 이 쿠키는 서비스예요.', en: 'No, just three minutes. And this cookie is on the house.' },
      { who: 'B', ko: '와, 감사합니다!', en: 'Oh, thank you!' },
    ],
    words: ['cafe:hot', 'cafe:cup', 'cafe:order', 'cafe:cookie'],
    questions: [
      {
        q: { ko: '태윤 씨는 뭘 주문했어요?', en: 'What did Taeyun order?' },
        options: [
          { ko: '아이스 한 잔하고 뜨거운 거 한 잔', en: 'one iced and one hot' },
          { ko: '아이스 두 잔', en: 'two iced' },
          { ko: '뜨거운 거 두 잔', en: 'two hot' },
        ],
        answer: 0,
        line: [0, 1],
        why: 'The barista brings 아이스 아메리카노 두 잔 (two iced americanos), but Taeyun says 한 잔은 뜨거운 걸로 주문했어요: he ordered one of them hot (뜨거운).',
      },
      {
        q: { ko: '뜨거운 커피는 얼마나 걸려요?', en: 'How long will the hot coffee take?' },
        options: [
          { ko: '3분', en: '3 minutes' },
          { ko: '2분', en: '2 minutes' },
          { ko: '10분', en: '10 minutes' },
        ],
        answer: 0,
        line: 4,
        why: 'The barista says 삼 분이면 돼요: three minutes (삼 = 3) is all it takes. 두 (2) was the number of cups: 두 잔.',
      },
      {
        q: { ko: '직원은 뭘 서비스로 줘요?', en: 'What does the barista give him on the house?' },
        options: [
          { ko: '쿠키', en: 'a cookie' },
          { ko: '케이크', en: 'a slice of cake' },
          { ko: '아이스 아메리카노', en: 'an iced americano' },
        ],
        answer: 0,
        line: 4,
        why: 'To make up for the mistake, the barista says 이 쿠키는 서비스예요: the cookie is on the house. In a Korean café or restaurant, 서비스 is something extra you get for free.',
      },
    ],
  },
  {
    id: 'hobbies-dance-festival',
    topic: 'hobbies',
    level: 2,
    scene: '💃',
    title: { ko: '요즘 왜 이렇게 바빠?', en: 'Why are you so busy?' },
    speakers: {
      A: { name: '하린', en: 'Harin', emoji: '👩‍🦱', voice: 'high' },
      B: { name: '지호', en: 'Jiho', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '지호야, 요즘 왜 이렇게 바빠? 아르바이트해?', en: 'Jiho, why are you so busy these days? Have you got a part-time job?' },
      { who: 'B', ko: '아니, 매일 춤 연습해. 다음 주 토요일에 학교 축제가 있어.', en: 'No, I practise dancing every day. The school festival is next Saturday.' },
      { who: 'A', ko: '와, 너 춤도 춰? 몰랐어!', en: 'Wow, you dance too? I had no idea!' },
      { who: 'B', ko: '응, 친구 네 명하고 같이 춰. 너도 보러 올래?', en: 'Yeah, with four friends. Do you want to come and watch?' },
      { who: 'A', ko: '당연하지! 몇 시에 해?', en: 'Of course! What time is it?' },
      { who: 'B', ko: '저녁 여섯 시에 시작해.', en: 'It starts at six in the evening.' },
      { who: 'A', ko: '좋아. 내가 사진 많이 찍어 줄게!', en: 'Great. I’ll take lots of photos of you!' },
    ],
    words: ['hobbies:dance', 'hobbies:practise', 'numbers:people', 'numbers:saturday'],
    questions: [
      {
        q: { ko: '지호는 요즘 왜 바빠요?', en: 'Why is Jiho busy these days?' },
        options: [
          { ko: '춤 연습을 해서', en: 'He’s practising dancing' },
          { ko: '아르바이트를 해서', en: 'He has a part-time job' },
          { ko: '시험공부를 해서', en: 'He’s studying for exams' },
        ],
        answer: 0,
        line: [0, 1],
        why: 'Harin guesses 아르바이트해? (a part-time job?), but Jiho says 아니, 매일 춤 연습해: no, he practises dancing every day, for the school festival (학교 축제) next Saturday.',
      },
      {
        q: { ko: '지호는 친구 몇 명하고 같이 춤을 춰요?', en: 'How many friends does Jiho dance with?' },
        options: [
          { ko: '4명', en: '4 friends' },
          { ko: '6명', en: '6 friends' },
          { ko: '5명', en: '5 friends' },
        ],
        answer: 0,
        line: 3,
        why: 'Jiho says 친구 네 명하고 같이 춰: he dances with four friends (넷 becomes 네 before 명). 여섯 (6) is the time of the show: 저녁 여섯 시.',
      },
      {
        q: { ko: '두 사람은 어떤 사이예요?', en: 'What’s the relationship between them?' },
        options: [
          { ko: '친한 친구', en: 'They’re close friends' },
          { ko: '처음 만난 사이', en: 'They’ve just met' },
          { ko: '선생님하고 학생', en: 'A teacher and a student' },
        ],
        answer: 0,
        line: [0, 1],
        why: 'They talk in 반말, with no 요: 왜 이렇게 바빠? (Harin), 아니, 매일 춤 연습해 (Jiho). She calls him 지호야, and he says 응 for “yes”: that’s how close friends of the same age talk.',
      },
    ],
  },
  {
    id: 'weather-below-zero',
    topic: 'weather',
    level: 2,
    scene: '🥶',
    title: { ko: '밖에 추워요?', en: 'Is it cold out?' },
    speakers: {
      A: { name: '서진', en: 'Seojin', emoji: '🧔', voice: 'low' },
      B: { name: '다인', en: 'Dain', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '다인 씨, 편의점에 잠깐 갔다 올게요.', en: 'Dain, I’m just popping out to the convenience store.' },
      { who: 'B', ko: '그렇게 입고요? 밖에 영하 오 도예요!', en: 'Dressed like that? It’s five below zero outside!' },
      { who: 'A', ko: '네? 영하요? 어제는 십 도였어요.', en: 'What? Below zero? It was ten degrees yesterday.' },
      { who: 'B', ko: '오늘은 바람도 많이 불어요. 코트 입고 가세요.', en: 'And it’s really windy today. Put a coat on.' },
      { who: 'A', ko: '알겠어요. 코트 입고 모자도 쓸게요.', en: 'All right. I’ll put on a coat, and a hat too.' },
      { who: 'B', ko: '네, 감기 조심하세요!', en: 'Good. Mind you don’t catch a cold!' },
    ],
    words: ['weather:belowzero', 'weather:degrees', 'weather:wind', 'shopping:wear'],
    questions: [
      {
        q: { ko: '오늘 밖은 몇 도예요?', en: 'What’s the temperature outside today?' },
        options: [
          { ko: '영하 5도', en: '−5°C' },
          { ko: '5도', en: '5°C' },
          { ko: '10도', en: '10°C' },
        ],
        answer: 0,
        line: 1,
        why: 'Dain says 밖에 영하 오 도예요: it’s minus five outside (영하 = below zero). 십 도 (10°C) was yesterday.',
      },
      {
        q: { ko: '서진 씨는 어떻게 나가요?', en: 'How does Seojin go out?' },
        options: [
          { ko: '코트를 입고 나가요', en: 'He puts on a coat' },
          { ko: '그냥 나가요', en: 'He goes out as he is' },
          { ko: '안 나가요', en: 'He stays in' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Dain says 코트 입고 가세요 (put a coat on), and Seojin agrees: 코트 입고 모자도 쓸게요, he’ll wear a coat and a hat too.',
      },
    ],
  },
  {
    id: 'work-presentation',
    topic: 'work',
    level: 2,
    scene: '📊',
    title: { ko: '점심 먹으러 가요!', en: 'Let’s go for lunch!' },
    speakers: {
      A: { name: '예준', en: 'Yejun', emoji: '👨‍💼', voice: 'low' },
      B: { name: '소희', en: 'Sohee', emoji: '👩‍💼', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '소희 씨, 회의 끝났어요? 점심 먹으러 가요!', en: 'Sohee, is your meeting over? Let’s go for lunch!' },
      { who: 'B', ko: '네, 끝났어요. 그런데 저는 못 가요. 두 시에 발표가 있어요.', en: 'Yes, it’s over. But I can’t come: I have a presentation at two.' },
      { who: 'A', ko: '아, 발표 준비 아직 안 끝났어요?', en: 'Oh, haven’t you finished getting it ready?' },
      { who: 'B', ko: '네, 아직 할 게 많아요.', en: 'No, I still have a lot to do.' },
      { who: 'A', ko: '그럼 제가 김밥 사 올게요. 뭐 마실래요?', en: 'Then I’ll bring you back some gimbap. What would you like to drink?' },
      { who: 'B', ko: '고마워요! 녹차 부탁해요. 커피는 벌써 세 잔 마셨어요.', en: 'Thanks! A green tea, please. I’ve already had three coffees.' },
      { who: 'A', ko: '하하, 알겠어요. 발표 잘하세요!', en: 'Ha ha, OK. Good luck with the presentation!' },
    ],
    words: ['work:presentation', 'work:prepare', 'work:meeting', 'day:lunch'],
    questions: [
      {
        q: { ko: '소희 씨는 왜 점심을 먹으러 못 가요?', en: 'Why can’t Sohee go for lunch?' },
        options: [
          { ko: '발표가 있어서', en: 'She has a presentation' },
          { ko: '회의가 있어서', en: 'She has a meeting' },
          { ko: '배가 안 고파서', en: 'She isn’t hungry' },
        ],
        answer: 0,
        line: 1,
        why: 'Sohee says 네, 끝났어요: the meeting is over. But she can’t come (못 가요), because 두 시에 발표가 있어요: she has a presentation at two.',
      },
      {
        q: { ko: '예준 씨는 뭘 사 와요?', en: 'What will Yejun bring back for her?' },
        options: [
          { ko: '김밥하고 녹차', en: 'gimbap and a green tea' },
          { ko: '김밥하고 커피', en: 'gimbap and a coffee' },
          { ko: '샌드위치하고 녹차', en: 'a sandwich and a green tea' },
        ],
        answer: 0,
        line: [4, 5],
        why: 'Yejun offers to get 김밥, and Sohee asks for 녹차 (green tea), not coffee: 커피는 벌써 세 잔 마셨어요, she’s already had three today.',
      },
      {
        q: { ko: '소희 씨는 오늘 커피를 몇 잔 마셨어요?', en: 'How many coffees has Sohee had today?' },
        options: [
          { ko: '3잔', en: '3 cups' },
          { ko: '2잔', en: '2 cups' },
          { ko: '1잔', en: '1 cup' },
        ],
        answer: 0,
        line: 5,
        why: 'Sohee says 커피는 벌써 세 잔 마셨어요: she’s already had three (셋 becomes 세 before 잔). 두 (2) is the time of her presentation: 두 시.',
      },
    ],
  },

  // ---------- More dialogues: level 3 ----------
  {
    id: 'day-study-place',
    topic: 'day',
    level: 3,
    scene: '📚',
    title: { ko: '어디에서 공부해?', en: 'Where do you study?' },
    speakers: {
      A: { name: '승현', en: 'Seunghyun', emoji: '👦', voice: 'low' },
      B: { name: '채원', en: 'Chaewon', emoji: '👧', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '채원아, 너는 보통 어디에서 공부해?', en: 'Chaewon, where do you usually study?' },
      { who: 'B', ko: '나는 도서관에서 해. 조용해서 좋아.', en: 'At the library. I like it because it’s quiet.' },
      { who: 'A', ko: '나는 도서관은 너무 조용해서 졸려. 그래서 카페에서 해.', en: 'The library’s so quiet it makes me sleepy. So I study in cafés.' },
      { who: 'B', ko: '카페는 시끄럽지 않아?', en: 'Aren’t cafés noisy?' },
      { who: 'A', ko: '좀 시끄럽지만 나는 그게 더 좋아.', en: 'A bit, but I like it better that way.' },
      { who: 'B', ko: '그래? 그럼 내일은 나도 같이 가 볼래.', en: 'Really? Then tomorrow I’ll come along and try it.' },
      { who: 'A', ko: '좋아! 학교 앞 카페에서 열 시에 만나자.', en: 'Great! Let’s meet at the café in front of school at ten.' },
      { who: 'B', ko: '응! 커피는 내가 살게.', en: 'OK! The coffee’s on me.' },
    ],
    words: ['day:usually', 'day:study', 'day:library', 'day:together'],
    questions: [
      {
        q: { ko: '두 사람은 서로 어떻게 말해요?', en: 'How do they talk to each other?' },
        options: [
          { ko: '반말로 말해요', en: 'In 반말 (casual)' },
          { ko: '해요체로 말해요', en: 'In 해요체 (polite)' },
          { ko: '합니다체로 말해요', en: 'In 합니다체 (formal)' },
        ],
        answer: 0,
        line: [0, 1],
        why: 'No line ends in 요: 어디에서 공부해? (Seunghyun), 나는 도서관에서 해 (Chaewon). They say 나 for “I” and 너 for “you”, and he calls her 채원아: that’s 반말, the way friends of the same age talk.',
      },
      {
        q: { ko: '승현은 왜 도서관에서 공부를 안 해요?', en: 'Why doesn’t Seunghyun study at the library?' },
        options: [
          { ko: '졸려서', en: 'It makes him sleepy' },
          { ko: '시끄러워서', en: 'It’s noisy' },
          { ko: '멀어서', en: 'It’s far' },
        ],
        answer: 0,
        line: 2,
        why: 'Seunghyun says 도서관은 너무 조용해서 졸려: the library is so quiet that it makes him sleepy. Noisy (시끄럽지 않아?) is what Chaewon asks about cafés.',
      },
      {
        q: { ko: '두 사람은 내일 어디에서 공부해요?', en: 'Where will they study tomorrow?' },
        options: [
          { ko: '카페', en: 'at a café' },
          { ko: '도서관', en: 'at the library' },
          { ko: '집', en: 'at home' },
        ],
        answer: 0,
        line: [5, 6],
        why: 'Chaewon usually studies at the library, but she says 내일은 나도 같이 가 볼래: tomorrow she’ll try the café with him. They meet at 학교 앞 카페 at ten (열 시).',
      },
    ],
  },
  {
    id: 'people-blind-date',
    topic: 'people',
    level: 3,
    scene: '💌',
    title: { ko: '친구 소개해 줄까요?', en: 'Shall I set you up?' },
    speakers: {
      A: { name: '정우', en: 'Jeongwoo', emoji: '👨', voice: 'low' },
      B: { name: '수빈', en: 'Subin', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '수빈 씨, 혹시 남자 친구 있어요?', en: 'Subin, have you got a boyfriend, by any chance?' },
      { who: 'B', ko: '아니요, 없어요. 왜요?', en: 'No, I haven’t. Why?' },
      { who: 'A', ko: '제 친구 소개해 줄까요? 키가 크고 정말 착해요.', en: 'Shall I introduce you to a friend of mine? He’s tall and really kind.' },
      { who: 'B', ko: '와, 몇 살이에요?', en: 'Oh! How old is he?' },
      { who: 'A', ko: '서른 살이에요. 수빈 씨보다 두 살 많아요.', en: 'He’s thirty. Two years older than you.' },
      { who: 'B', ko: '무슨 일을 해요?', en: 'What does he do?' },
      { who: 'A', ko: '병원에서 일해요. 의사는 아니고 간호사예요.', en: 'He works at a hospital. Not as a doctor: he’s a nurse.' },
      { who: 'B', ko: '좋아요. 그럼 한번 만나 볼게요.', en: 'OK. I’ll meet him, then.' },
    ],
    words: ['people:tall', 'people:kind', 'people:doctor', 'numbers:age'],
    questions: [
      {
        q: { ko: '정우 씨 친구는 몇 살이에요?', en: 'How old is Jeongwoo’s friend?' },
        options: [
          { ko: '30살', en: '30 years old' },
          { ko: '28살', en: '28 years old' },
          { ko: '32살', en: '32 years old' },
        ],
        answer: 0,
        line: 4,
        why: 'Jeongwoo says 서른 살이에요: his friend is thirty (서른 = 30; ages use the native numbers). 두 살 많아요 means he’s two years older than Subin, so 28 is her age.',
      },
      {
        q: { ko: '정우 씨 친구는 무슨 일을 해요?', en: 'What does Jeongwoo’s friend do?' },
        options: [
          { ko: '간호사', en: 'He’s a nurse' },
          { ko: '의사', en: 'He’s a doctor' },
          { ko: '회사원', en: 'He’s an office worker' },
        ],
        answer: 0,
        line: 6,
        why: 'Jeongwoo says 의사는 아니고 간호사예요: his friend works at a hospital, but not as a doctor (의사): he’s a nurse (간호사).',
      },
      {
        q: { ko: '정우 씨 친구는 어떤 사람이에요?', en: 'What is Jeongwoo’s friend like?' },
        options: [
          { ko: '키가 크고 착해요', en: 'He’s tall and kind' },
          { ko: '키가 작고 착해요', en: 'He’s short and kind' },
          { ko: '키가 크고 재미있어요', en: 'He’s tall and funny' },
        ],
        answer: 0,
        line: 2,
        why: 'Jeongwoo says 키가 크고 정말 착해요: his friend is tall (키가 커요) and (-고) really kind (착해요).',
      },
    ],
  },
  {
    id: 'feelings-driving-test',
    topic: 'feelings',
    level: 3,
    scene: '🚗',
    title: { ko: '무슨 일 있어?', en: 'What’s wrong?' },
    speakers: {
      A: { name: '주원', en: 'Juwon', emoji: '🧑', voice: 'low' },
      B: { name: '혜린', en: 'Hyerin', emoji: '👩‍🦰', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '혜린아, 무슨 일 있어? 기분이 안 좋아 보여.', en: 'Hyerin, what’s up? You look a bit down.' },
      { who: 'B', ko: '응, 오늘 운전면허 시험에 떨어졌어.', en: 'Yeah. I failed my driving test today.' },
      { who: 'A', ko: '아, 진짜? 많이 속상하겠다.', en: 'Oh no, really? You must be really upset.' },
      { who: 'B', ko: '응. 너무 떨려서 실수를 많이 했어.', en: 'Yeah. I was so nervous that I made lots of mistakes.' },
      { who: 'A', ko: '괜찮아. 나도 처음에는 떨어졌어.', en: 'Don’t worry. I failed the first time too.' },
      { who: 'B', ko: '정말? 너도?', en: 'Really? You too?' },
      { who: 'A', ko: '응, 두 번째에 합격했어. 너도 다음에는 꼭 합격할 거야.', en: 'Yeah, I passed the second time. You’ll pass next time, for sure.' },
      { who: 'B', ko: '고마워. 다음 달에 다시 볼 거야!', en: 'Thanks. I’m taking it again next month!' },
    ],
    words: ['feelings:upset', 'feelings:nervous', 'feelings:mood', 'work:passed'],
    questions: [
      {
        q: { ko: '혜린은 왜 실수를 많이 했어요?', en: 'Why did Hyerin make lots of mistakes?' },
        options: [
          { ko: '너무 떨려서', en: 'She was too nervous' },
          { ko: '너무 피곤해서', en: 'She was too tired' },
          { ko: '연습을 안 해서', en: 'She hadn’t practised' },
        ],
        answer: 0,
        line: 3,
        why: 'Hyerin failed her driving test (시험에 떨어졌어), and she says 너무 떨려서 실수를 많이 했어: she was so nervous (떨리다) that she made lots of mistakes.',
      },
      {
        q: { ko: '주원은 운전면허 시험을 몇 번 봤어요?', en: 'How many times did Juwon take the driving test?' },
        options: [
          { ko: '2번', en: 'twice' },
          { ko: '1번', en: 'once' },
          { ko: '3번', en: 'three times' },
        ],
        answer: 0,
        line: [4, 6],
        why: 'Juwon says 나도 처음에는 떨어졌어 (I failed the first time too) and 두 번째에 합격했어 (I passed the second time): so he took it twice.',
      },
      {
        q: { ko: '혜린은 주원한테 어떻게 고맙다고 해요?', en: 'How does Hyerin thank Juwon?' },
        options: [
          { ko: '고마워', en: 'Thanks (반말, casual)' },
          { ko: '고마워요', en: 'Thanks (해요체, polite)' },
          { ko: '고맙습니다', en: 'Thank you (합니다체, formal)' },
        ],
        answer: 0,
        line: 7,
        why: 'Hyerin says 고마워, with no 요: that’s 반말, the way close friends talk, like the whole chat (무슨 일 있어?, 응, 너도?). 고마워요 would be polite 해요체.',
      },
    ],
  },
]);
