/**
 * Listening dialogues, played in the Dialogues game (js/games/dialogues.js):
 * a short conversation between two people is read aloud (one higher voice,
 * one lower) with the script hidden, then the learner answers questions about it.
 *
 * Numbers in the lines are written in Hangul (세 시 반, 사천오백 원), so the
 * speech reads them the Korean way. The answer options use digits (3시 30분,
 * 4,500원): you have to map what you heard to the number.
 *
 * Fields: id, topic (a topic id), level (1–3), scene (an emoji for the place),
 *         title { ko, en },
 *         speakers { A, B: { name, en, emoji, voice: 'high' | 'low' } },
 *         lines [{ who: 'A' | 'B', ko, en }],
 *         words (2–4 vocabulary refs, 'topic:id': the dialogue unlocks once they're learned),
 *         questions [{ q { ko, en }, options (3 × { ko, en }), answer (index of the
 *                      right option; the game shuffles them), line (0-based index of
 *                      the line with the answer, or a list), why (shown after answering) }].
 */
Mallang.content.registerDialogues([
  // ---------- Level 1 ----------
  {
    id: 'cafe-order',
    topic: 'cafe',
    level: 1,
    scene: '☕',
    title: { ko: '카페에서 주문하기', en: 'Ordering at a café' },
    speakers: {
      A: { name: '직원', en: 'Barista', emoji: '🧑‍🍳', voice: 'low' },
      B: { name: '서연', en: 'Seoyeon', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 뭐 드릴까요?', en: 'Welcome! What can I get you?' },
      { who: 'B', ko: '라테 한 잔하고 쿠키 하나 주세요.', en: 'A latte and a cookie, please.' },
      { who: 'A', ko: '죄송합니다. 쿠키는 지금 없어요.', en: 'I’m sorry, we don’t have any cookies right now.' },
      { who: 'B', ko: '아, 그럼 케이크 하나 주세요.', en: 'Oh, then a slice of cake, please.' },
      { who: 'A', ko: '네, 라테 한 잔하고 케이크 하나요.', en: 'Sure: one latte and one slice of cake.' },
    ],
    words: ['cafe:latte', 'cafe:cookie', 'cafe:cake', 'cafe:please'],
    questions: [
      {
        q: { ko: '서연 씨는 뭘 마셔요?', en: 'What does Seoyeon drink?' },
        options: [
          { ko: '라테', en: 'a latte' },
          { ko: '녹차', en: 'a green tea' },
          { ko: '주스', en: 'a juice' },
        ],
        answer: 0,
        line: 1,
        why: 'Seoyeon says 라테 한 잔하고 쿠키 하나 주세요: “A latte and a cookie, please.”',
      },
      {
        q: { ko: '서연 씨는 뭘 먹어요?', en: 'What does Seoyeon eat?' },
        options: [
          { ko: '케이크', en: 'cake' },
          { ko: '쿠키', en: 'a cookie' },
          { ko: '샌드위치', en: 'a sandwich' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'The barista says 쿠키는 지금 없어요 (“we don’t have cookies right now”), so Seoyeon changes her order: 그럼 케이크 하나 주세요, “then a slice of cake, please”.',
      },
    ],
  },
  {
    id: 'day-now',
    topic: 'day',
    level: 1,
    scene: '📱',
    title: { ko: '지금 뭐 해요?', en: 'What are you up to?' },
    speakers: {
      A: { name: '지수', en: 'Jisu', emoji: '👩', voice: 'high' },
      B: { name: '민수', en: 'Minsu', emoji: '👨', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '민수 씨, 지금 뭐 해요?', en: 'Minsu, what are you doing right now?' },
      { who: 'B', ko: '집에서 밥 먹어요. 왜요?', en: 'I’m eating at home. Why?' },
      { who: 'A', ko: '저 지금 카페에 있어요. 같이 커피 마셔요!', en: 'I’m at a café right now. Let’s have a coffee together!' },
      { who: 'B', ko: '미안해요. 오늘은 좀 피곤해요. 내일 어때요?', en: 'Sorry, I’m a bit tired today. How about tomorrow?' },
      { who: 'A', ko: '좋아요. 그럼 내일 봐요!', en: 'OK. See you tomorrow, then!' },
    ],
    words: ['day:now', 'day:eat', 'day:today', 'day:tomorrow'],
    questions: [
      {
        q: { ko: '민수 씨는 지금 뭐 해요?', en: 'What is Minsu doing right now?' },
        options: [
          { ko: '밥을 먹어요', en: 'He’s having a meal' },
          { ko: '커피를 마셔요', en: 'He’s having a coffee' },
          { ko: '게임을 해요', en: 'He’s playing a game' },
        ],
        answer: 0,
        line: 1,
        why: 'Minsu says 집에서 밥 먹어요: he’s eating at home. The coffee is Jisu’s idea: she’s the one at the café.',
      },
      {
        q: { ko: '두 사람은 언제 만나요?', en: 'When will they meet?' },
        options: [
          { ko: '내일', en: 'tomorrow' },
          { ko: '오늘', en: 'today' },
          { ko: '지금', en: 'right now' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Minsu says 오늘은 좀 피곤해요. 내일 어때요?: he’s tired today, so he suggests tomorrow. Jisu agrees: 내일 봐요!',
      },
    ],
  },
  {
    id: 'numbers-movie',
    topic: 'numbers',
    level: 1,
    scene: '🎬',
    title: { ko: '영화 몇 시예요?', en: 'What time is the movie?' },
    speakers: {
      A: { name: '유나', en: 'Yuna', emoji: '👧', voice: 'high' },
      B: { name: '성민', en: 'Seongmin', emoji: '👦', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '성민 씨, 영화 몇 시예요?', en: 'Seongmin, what time is the movie?' },
      { who: 'B', ko: '네 시예요.', en: 'It’s at four.' },
      { who: 'A', ko: '세 시요?', en: 'At three?' },
      { who: 'B', ko: '아니요, 네 시요. 지금 두 시예요.', en: 'No, at four. It’s two o’clock now.' },
      { who: 'A', ko: '아, 그럼 밥 먼저 먹어요!', en: 'Oh, then let’s eat first!' },
    ],
    words: ['numbers:oclock', 'numbers:howmany', 'numbers:three', 'numbers:four'],
    questions: [
      {
        q: { ko: '영화는 몇 시예요?', en: 'What time is the movie?' },
        options: [
          { ko: '4시', en: '4:00' },
          { ko: '3시', en: '3:00' },
          { ko: '2시', en: '2:00' },
        ],
        answer: 0,
        line: [1, 3],
        why: 'Seongmin says 네 시예요: four o’clock (넷 becomes 네 before 시). Yuna hears 세 시 (three), so he says it again: 아니요, 네 시요.',
      },
      {
        q: { ko: '지금 몇 시예요?', en: 'What time is it now?' },
        options: [
          { ko: '2시', en: '2:00' },
          { ko: '4시', en: '4:00' },
          { ko: '3시', en: '3:00' },
        ],
        answer: 0,
        line: 3,
        why: 'Seongmin says 지금 두 시예요: it’s two o’clock now (둘 becomes 두 before 시), so they have time to eat first.',
      },
    ],
  },
  {
    id: 'directions-meet',
    topic: 'directions',
    level: 1,
    scene: '🚉',
    title: { ko: '어디에 있어요?', en: 'Where are you?' },
    speakers: {
      A: { name: '지아', en: 'Jia', emoji: '👩‍🦱', voice: 'high' },
      B: { name: '준호', en: 'Junho', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '준호 씨, 지금 어디에 있어요?', en: 'Junho, where are you right now?' },
      { who: 'B', ko: '역 앞에 있어요. 지아 씨는요?', en: 'I’m in front of the station. What about you?' },
      { who: 'A', ko: '저는 역 뒤 카페에 있어요.', en: 'I’m at the café behind the station.' },
      { who: 'B', ko: '아, 역 뒤요? 그럼 제가 거기로 갈게요.', en: 'Oh, behind the station? Then I’ll come over there.' },
      { who: 'A', ko: '네, 카페에서 기다릴게요.', en: 'OK, I’ll wait in the café.' },
    ],
    words: ['directions:where', 'directions:front', 'directions:behind', 'directions:station'],
    questions: [
      {
        q: { ko: '준호 씨는 지금 어디에 있어요?', en: 'Where is Junho right now?' },
        options: [
          { ko: '역 앞', en: 'in front of the station' },
          { ko: '역 뒤', en: 'behind the station' },
          { ko: '카페', en: 'at the café' },
        ],
        answer: 0,
        line: 1,
        why: 'Junho says 역 앞에 있어요: “I’m in front of the station.” Jia is the one behind it (역 뒤), at the café.',
      },
      {
        q: { ko: '두 사람은 어디에서 만나요?', en: 'Where do they meet?' },
        options: [
          { ko: '역 뒤 카페', en: 'at the café behind the station' },
          { ko: '역 앞', en: 'in front of the station' },
          { ko: '역 앞 카페', en: 'at a café in front of the station' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'Jia is at 역 뒤 카페 (the café behind the station), and Junho says 제가 거기로 갈게요: “I’ll come over there.”',
      },
    ],
  },
  {
    id: 'past-yesterday',
    topic: 'past',
    level: 1,
    scene: '🗓️',
    title: { ko: '어제 뭐 했어요?', en: 'What did you do yesterday?' },
    speakers: {
      A: { name: '은지', en: 'Eunji', emoji: '👱‍♀️', voice: 'high' },
      B: { name: '태민', en: 'Taemin', emoji: '👨‍🦱', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '태민 씨, 어제 뭐 했어요?', en: 'Taemin, what did you do yesterday?' },
      { who: 'B', ko: '친구하고 카페에 갔어요. 샌드위치도 먹었어요.', en: 'I went to a café with a friend. We had sandwiches, too.' },
      { who: 'A', ko: '와, 맛있었어요?', en: 'Oh, were they good?' },
      { who: 'B', ko: '네, 진짜 맛있었어요. 은지 씨는요?', en: 'Yes, really good. What about you?' },
      { who: 'A', ko: '저는 그냥 집에서 잤어요. 너무 피곤했어요.', en: 'I just slept at home. I was so tired.' },
    ],
    words: ['past:whatdid', 'past:went', 'past:ate'],
    questions: [
      {
        q: { ko: '태민 씨는 어제 어디에 갔어요?', en: 'Where did Taemin go yesterday?' },
        options: [
          { ko: '카페', en: 'to a café' },
          { ko: '친구 집', en: 'to a friend’s house' },
          { ko: '학교', en: 'to school' },
        ],
        answer: 0,
        line: 1,
        why: 'Taemin says 친구하고 카페에 갔어요: he went to a café with (하고) a friend, not to a friend’s house.',
      },
      {
        q: { ko: '은지 씨는 어제 뭐 했어요?', en: 'What did Eunji do yesterday?' },
        options: [
          { ko: '집에서 잤어요', en: 'She slept at home' },
          { ko: '카페에 갔어요', en: 'She went to a café' },
          { ko: '샌드위치를 먹었어요', en: 'She had a sandwich' },
        ],
        answer: 0,
        line: 4,
        why: 'Eunji says 저는 그냥 집에서 잤어요: she just slept at home, because she was so tired (너무 피곤했어요). The café and the sandwiches were Taemin’s day.',
      },
    ],
  },

  // ---------- Level 2 ----------
  {
    id: 'day-getup',
    topic: 'day',
    level: 2,
    scene: '⏰',
    title: { ko: '몇 시에 일어나요?', en: 'What time do you get up?' },
    speakers: {
      A: { name: '소연', en: 'Soyeon', emoji: '👩‍💼', voice: 'high' },
      B: { name: '지훈', en: 'Jihoon', emoji: '👨‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '지훈 씨는 매일 몇 시에 일어나요?', en: 'Jihoon, what time do you get up every day?' },
      { who: 'B', ko: '여섯 시에 일어나요.', en: 'I get up at six.' },
      { who: 'A', ko: '와, 일찍 일어나네요! 왜요?', en: 'Wow, that’s early! Why?' },
      { who: 'B', ko: '회사가 좀 멀어요. 지하철로 한 시간 걸려요.', en: 'My office is quite far. It takes an hour by subway.' },
      { who: 'A', ko: '그래요? 저는 회사가 가까워요. 그래서 여덟 시에 일어나요.', en: 'Really? My office is close, so I get up at eight.' },
      { who: 'B', ko: '와, 부러워요!', en: 'Wow, I’m jealous!' },
    ],
    words: ['day:getup', 'day:everyday', 'day:company'],
    questions: [
      {
        q: { ko: '지훈 씨는 몇 시에 일어나요?', en: 'What time does Jihoon get up?' },
        options: [
          { ko: '6시', en: '6:00' },
          { ko: '8시', en: '8:00' },
          { ko: '7시', en: '7:00' },
        ],
        answer: 0,
        line: 1,
        why: 'Jihoon says 여섯 시에 일어나요: he gets up at six (여섯 = 6).',
      },
      {
        q: { ko: '지훈 씨는 왜 일찍 일어나요?', en: 'Why does Jihoon get up early?' },
        options: [
          { ko: '회사가 멀어서', en: 'His office is far away' },
          { ko: '아침에 운동해서', en: 'He works out in the morning' },
          { ko: '일이 많아서', en: 'He has a lot of work' },
        ],
        answer: 0,
        line: 3,
        why: 'Jihoon says 회사가 좀 멀어요. 지하철로 한 시간 걸려요: his office is far, an hour away by subway.',
      },
      {
        q: { ko: '소연 씨는 몇 시에 일어나요?', en: 'What time does Soyeon get up?' },
        options: [
          { ko: '8시', en: '8:00' },
          { ko: '6시', en: '6:00' },
          { ko: '7시', en: '7:00' },
        ],
        answer: 0,
        line: 4,
        why: 'Soyeon’s office is close (회사가 가까워요), so she says 그래서 여덟 시에 일어나요: she gets up at eight (여덟 = 8).',
      },
    ],
  },
  {
    id: 'people-photo',
    topic: 'people',
    level: 2,
    scene: '📷',
    title: { ko: '가족 사진', en: 'A family photo' },
    speakers: {
      A: { name: '하나', en: 'Hana', emoji: '👩', voice: 'high' },
      B: { name: '현우', en: 'Hyunwoo', emoji: '👨', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '현우 씨, 이거 우리 가족 사진이에요.', en: 'Hyunwoo, this is a photo of my family.' },
      { who: 'B', ko: '와! 이 사람은 누구예요?', en: 'Wow! Who’s this?' },
      { who: 'A', ko: '우리 언니예요. 언니는 선생님이에요.', en: 'That’s my older sister. She’s a teacher.' },
      { who: 'B', ko: '이 남자는요? 오빠예요?', en: 'And this guy? Is he your older brother?' },
      { who: 'A', ko: '아니요, 남동생이에요. 아직 학생이에요.', en: 'No, he’s my younger brother. He’s still a student.' },
      { who: 'B', ko: '진짜요? 키가 정말 커요!', en: 'Really? He’s so tall!' },
    ],
    words: ['people:unni', 'people:oppa', 'people:sibling', 'people:teacher'],
    questions: [
      {
        q: { ko: '하나 씨 언니는 뭐 해요?', en: 'What does Hana’s older sister do?' },
        options: [
          { ko: '선생님이에요', en: 'She’s a teacher' },
          { ko: '학생이에요', en: 'She’s a student' },
          { ko: '의사예요', en: 'She’s a doctor' },
        ],
        answer: 0,
        line: 2,
        why: 'Hana says 우리 언니예요. 언니는 선생님이에요: it’s her older sister, and she’s a teacher.',
      },
      {
        q: { ko: '사진 속 남자는 누구예요?', en: 'Who is the man in the photo?' },
        options: [
          { ko: '남동생', en: 'her younger brother' },
          { ko: '오빠', en: 'her older brother' },
          { ko: '남자 친구', en: 'her boyfriend' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Hyunwoo guesses 오빠예요? (her older brother?), but Hana says 아니요, 남동생이에요: he’s her younger brother.',
      },
      {
        q: { ko: '하나 씨 남동생은 뭐 해요?', en: 'What does Hana’s younger brother do?' },
        options: [
          { ko: '학생이에요', en: 'He’s a student' },
          { ko: '선생님이에요', en: 'He’s a teacher' },
          { ko: '회사원이에요', en: 'He’s an office worker' },
        ],
        answer: 0,
        line: 4,
        why: 'Hana says 아직 학생이에요: her younger brother is still a student.',
      },
    ],
  },
  {
    id: 'numbers-booking',
    topic: 'numbers',
    level: 2,
    scene: '📞',
    title: { ko: '식당 예약', en: 'Booking a table' },
    speakers: {
      A: { name: '직원', en: 'Staff', emoji: '🙋‍♀️', voice: 'high' },
      B: { name: '민준', en: 'Minjun', emoji: '🧔', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '네, 한강식당입니다.', en: 'Hello, Hangang Restaurant.' },
      { who: 'B', ko: '안녕하세요. 토요일 저녁에 예약되나요?', en: 'Hello. Can I book a table for Saturday evening?' },
      { who: 'A', ko: '네. 몇 분이세요?', en: 'Yes, of course. For how many people?' },
      { who: 'B', ko: '네 명이요. 일곱 시에 돼요?', en: 'Four. Is seven o’clock OK?' },
      { who: 'A', ko: '죄송합니다. 일곱 시는 자리가 없어요. 일곱 시 반 괜찮으세요?', en: 'I’m sorry, we have no tables at seven. Would seven thirty be all right?' },
      { who: 'B', ko: '네, 좋아요. 그럼 일곱 시 반에 갈게요.', en: 'Yes, that’s fine. We’ll come at seven thirty, then.' },
    ],
    words: ['numbers:saturday', 'numbers:people', 'numbers:half', 'numbers:howmany'],
    questions: [
      {
        q: { ko: '무슨 요일에 가요?', en: 'What day are they going?' },
        options: [
          { ko: '토요일', en: 'Saturday' },
          { ko: '일요일', en: 'Sunday' },
          { ko: '월요일', en: 'Monday' },
        ],
        answer: 0,
        line: 1,
        why: 'Minjun asks 토요일 저녁에 예약되나요?: “Can I book for Saturday evening?”',
      },
      {
        q: { ko: '몇 명이 가요?', en: 'How many people are going?' },
        options: [
          { ko: '4명', en: '4 people' },
          { ko: '7명', en: '7 people' },
          { ko: '3명', en: '3 people' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'The staff asks 몇 분이세요? (the polite way to ask how many people), and Minjun says 네 명이요: four people (넷 becomes 네 before 명).',
      },
      {
        q: { ko: '몇 시에 가요?', en: 'What time are they going?' },
        options: [
          { ko: '7시 30분', en: '7:30' },
          { ko: '7시', en: '7:00' },
          { ko: '8시', en: '8:00' },
        ],
        answer: 0,
        line: [4, 5],
        why: 'Seven is full (일곱 시는 자리가 없어요), so the staff offers 일곱 시 반, and Minjun says 일곱 시 반에 갈게요: they’ll come at 7:30.',
      },
    ],
  },
  {
    id: 'shopping-gift',
    topic: 'shopping',
    level: 2,
    scene: '🎁',
    title: { ko: '친구 선물', en: 'A present for a friend' },
    speakers: {
      A: { name: '점원', en: 'Shop assistant', emoji: '👩‍💼', voice: 'high' },
      B: { name: '동현', en: 'Donghyun', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 뭐 찾으세요?', en: 'Welcome! What are you looking for?' },
      { who: 'B', ko: '친구 선물이요. 이 모자 얼마예요?', en: 'A present for a friend. How much is this hat?' },
      { who: 'A', ko: '그 모자는 팔천 원이에요.', en: 'That hat is 8,000 won.' },
      { who: 'B', ko: '그럼 이 티셔츠는요?', en: 'And this T-shirt?' },
      { who: 'A', ko: '티셔츠는 구천오백 원이에요.', en: 'The T-shirt is 9,500 won.' },
      { who: 'B', ko: '음, 친구 사이즈를 몰라요. 그냥 모자 살게요.', en: 'Hmm, I don’t know my friend’s size. I’ll just get the hat.' },
    ],
    words: ['shopping:hat', 'shopping:tshirt', 'shopping:gift', 'shopping:buy'],
    questions: [
      {
        q: { ko: '동현 씨는 뭘 사요?', en: 'What does Donghyun buy?' },
        options: [
          { ko: '모자', en: 'a hat' },
          { ko: '티셔츠', en: 'a T-shirt' },
          { ko: '가방', en: 'a bag' },
        ],
        answer: 0,
        line: 5,
        why: 'Donghyun says 그냥 모자 살게요: “I’ll just get the hat.”',
      },
      {
        q: { ko: '모자는 얼마예요?', en: 'How much is the hat?' },
        options: [
          { ko: '8,000원', en: '8,000 won' },
          { ko: '9,500원', en: '9,500 won' },
          { ko: '8,500원', en: '8,500 won' },
        ],
        answer: 0,
        line: 2,
        why: 'The assistant says 그 모자는 팔천 원이에요: 8,000 won. 구천오백 원 (9,500 won) is the T-shirt.',
      },
      {
        q: { ko: '동현 씨는 왜 티셔츠를 안 사요?', en: 'Why doesn’t Donghyun buy the T-shirt?' },
        options: [
          { ko: '친구 사이즈를 몰라서', en: 'He doesn’t know his friend’s size' },
          { ko: '티셔츠가 비싸서', en: 'The T-shirt is too expensive' },
          { ko: '색깔이 안 예뻐서', en: 'He doesn’t like the colour' },
        ],
        answer: 0,
        line: 5,
        why: 'Donghyun says 친구 사이즈를 몰라요: he doesn’t know his friend’s size, so he gets the hat instead.',
      },
    ],
  },
  {
    id: 'feelings-tired',
    topic: 'feelings',
    level: 2,
    scene: '😪',
    title: { ko: '화났어요?', en: 'Are you angry?' },
    speakers: {
      A: { name: '나연', en: 'Nayeon', emoji: '👩‍🦰', voice: 'high' },
      B: { name: '재민', en: 'Jaemin', emoji: '👨‍💼', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '재민 씨, 혹시 화났어요?', en: 'Jaemin, are you angry or something?' },
      { who: 'B', ko: '아니요, 화 안 났어요. 그냥 좀 피곤해요.', en: 'No, I’m not angry. I’m just a bit tired.' },
      { who: 'A', ko: '왜요? 어제 늦게 잤어요?', en: 'Why? Did you go to bed late last night?' },
      { who: 'B', ko: '네. 요즘 일이 많아서 너무 바빠요.', en: 'Yes. I have so much work these days, I’m really busy.' },
      { who: 'A', ko: '아, 힘내요! 제가 커피 살게요.', en: 'Oh, hang in there! I’ll buy you a coffee.' },
      { who: 'B', ko: '와, 고마워요. 기분이 좋아졌어요.', en: 'Aw, thanks. I feel better already.' },
    ],
    words: ['feelings:tired', 'feelings:angry', 'feelings:busy', 'feelings:mood'],
    questions: [
      {
        q: { ko: '재민 씨는 화났어요?', en: 'Is Jaemin angry?' },
        options: [
          { ko: '아니요, 피곤해요', en: 'No, he’s tired' },
          { ko: '네, 화났어요', en: 'Yes, he’s angry' },
          { ko: '아니요, 슬퍼요', en: 'No, he’s sad' },
        ],
        answer: 0,
        line: 1,
        why: 'Nayeon asks 혹시 화났어요? (are you angry?), but Jaemin says 아니요, 화 안 났어요. 그냥 좀 피곤해요: he’s not angry, just a bit tired.',
      },
      {
        q: { ko: '재민 씨는 왜 바빠요?', en: 'Why is Jaemin busy?' },
        options: [
          { ko: '일이 많아서', en: 'He has a lot of work' },
          { ko: '숙제가 많아서', en: 'He has a lot of homework' },
          { ko: '시험이 있어서', en: 'He has an exam' },
        ],
        answer: 0,
        line: 3,
        why: 'Jaemin says 요즘 일이 많아서 너무 바빠요: he has a lot of work these days, so he’s very busy.',
      },
    ],
  },
  {
    id: 'weather-rain',
    topic: 'weather',
    level: 2,
    scene: '🌦️',
    title: { ko: '내일은 비가 와요', en: 'Rain tomorrow' },
    speakers: {
      A: { name: '민지', en: 'Minji', emoji: '👧', voice: 'high' },
      B: { name: '우진', en: 'Woojin', emoji: '👦', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '우진 씨, 오늘 날씨 진짜 좋아요!', en: 'Woojin, the weather’s really nice today!' },
      { who: 'B', ko: '네, 맑고 따뜻해요. 그런데 내일은 비가 와요.', en: 'Yes, it’s clear and warm. But it’s going to rain tomorrow.' },
      { who: 'A', ko: '진짜요? 내일 친구하고 자전거 타요.', en: 'Really? I’m going cycling with a friend tomorrow.' },
      { who: 'B', ko: '비가 많이 와요. 그냥 오늘 타세요!', en: 'It’s going to rain a lot. Just go today!' },
      { who: 'A', ko: '좋아요. 지금 친구한테 전화할게요.', en: 'Good idea. I’ll call my friend now.' },
    ],
    words: ['weather:weather', 'weather:clear', 'weather:warm', 'weather:raining'],
    questions: [
      {
        q: { ko: '내일 날씨는 어때요?', en: 'What will the weather be like tomorrow?' },
        options: [
          { ko: '비가 와요', en: 'It’s going to rain' },
          { ko: '맑아요', en: 'It’s going to be clear' },
          { ko: '눈이 와요', en: 'It’s going to snow' },
        ],
        answer: 0,
        line: 1,
        why: 'Woojin says 그런데 내일은 비가 와요: “but tomorrow it’s going to rain.” 맑고 따뜻해요 (clear and warm) is today.',
      },
      {
        q: { ko: '민지 씨는 언제 자전거를 타요?', en: 'When does Minji go cycling?' },
        options: [
          { ko: '오늘', en: 'today' },
          { ko: '내일', en: 'tomorrow' },
          { ko: '주말', en: 'at the weekend' },
        ],
        answer: 0,
        line: [3, 4],
        why: 'Minji planned to ride tomorrow (내일), but it’s going to rain, so Woojin says 그냥 오늘 타세요 (just go today) and she agrees: 좋아요.',
      },
    ],
  },

  // ---------- Level 3 ----------
  {
    id: 'cafe-recommend',
    topic: 'cafe',
    level: 3,
    scene: '🥤',
    title: { ko: '추천해 주세요', en: 'What do you recommend?' },
    speakers: {
      A: { name: '직원', en: 'Barista', emoji: '👩‍🍳', voice: 'high' },
      B: { name: '시우', en: 'Siwoo', emoji: '🧑', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '어서 오세요. 주문하시겠어요?', en: 'Welcome! Are you ready to order?' },
      { who: 'B', ko: '뭐가 맛있어요? 추천해 주세요.', en: 'What’s good here? Can you recommend something?' },
      { who: 'A', ko: '딸기 라테 어떠세요? 좀 달지만 맛있어요.', en: 'How about a strawberry latte? It’s a bit sweet, but it’s delicious.' },
      { who: 'B', ko: '음, 저는 단 거 안 좋아해요. 아이스 아메리카노 주세요.', en: 'Hmm, I don’t like sweet things. An iced americano, please.' },
      { who: 'A', ko: '드시고 가세요?', en: 'Is that for here?' },
      { who: 'B', ko: '아니요, 포장해 주세요.', en: 'No, to go, please.' },
      { who: 'A', ko: '포장하시면 오백 원 할인돼요. 사천 원입니다.', en: 'If it’s to go, you get 500 won off. That’s 4,000 won.' },
      { who: 'B', ko: '와, 좋네요. 여기 카드요.', en: 'Oh, nice. Here’s my card.' },
    ],
    words: ['cafe:recommend', 'cafe:sweet', 'cafe:americano', 'cafe:togo'],
    questions: [
      {
        q: { ko: '시우 씨는 뭘 주문해요?', en: 'What does Siwoo order?' },
        options: [
          { ko: '아이스 아메리카노', en: 'an iced americano' },
          { ko: '딸기 라테', en: 'a strawberry latte' },
          { ko: '아이스 라테', en: 'an iced latte' },
        ],
        answer: 0,
        line: 3,
        why: 'Siwoo says 아이스 아메리카노 주세요: “An iced americano, please.” The strawberry latte (딸기 라테) is only the barista’s idea.',
      },
      {
        q: { ko: '시우 씨는 왜 딸기 라테를 안 마셔요?', en: 'Why doesn’t Siwoo have the strawberry latte?' },
        options: [
          { ko: '단 걸 안 좋아해서', en: 'He doesn’t like sweet things' },
          { ko: '너무 비싸서', en: 'It’s too expensive' },
          { ko: '딸기가 없어서', en: 'They’re out of strawberries' },
        ],
        answer: 0,
        line: [2, 3],
        why: 'The barista says it’s 좀 달지만 맛있어요 (a bit sweet, but delicious), and Siwoo says 저는 단 거 안 좋아해요: he doesn’t like sweet things.',
      },
      {
        q: { ko: '시우 씨는 얼마를 내요?', en: 'How much does Siwoo pay?' },
        options: [
          { ko: '4,000원', en: '4,000 won' },
          { ko: '4,500원', en: '4,500 won' },
          { ko: '500원', en: '500 won' },
        ],
        answer: 0,
        line: 6,
        why: 'To go is 500 won off (포장하시면 오백 원 할인돼요), so the barista says 사천 원입니다: 4,000 won.',
      },
    ],
  },
  {
    id: 'shopping-market',
    topic: 'shopping',
    level: 3,
    scene: '👖',
    title: { ko: '좀 깎아 주세요', en: 'Can you knock a bit off?' },
    speakers: {
      A: { name: '예린', en: 'Yerin', emoji: '👩', voice: 'high' },
      B: { name: '사장님', en: 'Shop owner', emoji: '🧔', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '저기요, 이 바지가 좀 작아서요. 더 큰 거 있어요?', en: 'Excuse me, these trousers are a bit small. Do you have a bigger pair?' },
      { who: 'B', ko: '죄송해요. 검은색은 없지만 파란색은 있어요.', en: 'Sorry, not in black. But we have them in blue.' },
      { who: 'A', ko: '그럼 파란색으로 할게요. 얼마예요?', en: 'Then I’ll take the blue ones. How much are they?' },
      { who: 'B', ko: '삼만 오천 원이에요.', en: 'They’re 35,000 won.' },
      { who: 'A', ko: '좀 깎아 주세요.', en: 'Could you knock a bit off?' },
      { who: 'B', ko: '현금으로 하시면 삼만 원에 드릴게요.', en: 'If you pay cash, you can have them for 30,000 won.' },
      { who: 'A', ko: '좋아요. 그럼 현금으로 할게요.', en: 'Great. I’ll pay cash, then.' },
      { who: 'B', ko: '감사합니다. 또 오세요!', en: 'Thank you! Come again!' },
    ],
    words: ['shopping:trousers', 'shopping:blue', 'shopping:cash', 'shopping:discountplease'],
    questions: [
      {
        q: { ko: '예린 씨는 뭘 찾아요?', en: 'What is Yerin looking for?' },
        options: [
          { ko: '더 큰 바지', en: 'bigger trousers' },
          { ko: '더 작은 바지', en: 'smaller trousers' },
          { ko: '더 싼 바지', en: 'cheaper trousers' },
        ],
        answer: 0,
        line: 0,
        why: 'Yerin says 이 바지가 좀 작아서요. 더 큰 거 있어요?: these are a bit small, so she wants a bigger pair.',
      },
      {
        q: { ko: '예린 씨는 무슨 색 바지를 사요?', en: 'What colour trousers does Yerin buy?' },
        options: [
          { ko: '파란색', en: 'blue' },
          { ko: '검은색', en: 'black' },
          { ko: '빨간색', en: 'red' },
        ],
        answer: 0,
        line: [1, 2],
        why: 'The owner says 검은색은 없지만 파란색은 있어요: there’s no bigger pair in black, but there is one in blue. So Yerin says 그럼 파란색으로 할게요.',
      },
      {
        q: { ko: '예린 씨는 얼마를 내요?', en: 'How much does Yerin pay?' },
        options: [
          { ko: '30,000원', en: '30,000 won' },
          { ko: '35,000원', en: '35,000 won' },
          { ko: '3,500원', en: '3,500 won' },
        ],
        answer: 0,
        line: [5, 6],
        why: 'The price is 삼만 오천 원 (35,000 won), but the owner says 현금으로 하시면 삼만 원에 드릴게요 (30,000 won in cash), and Yerin pays cash.',
      },
    ],
  },
  {
    id: 'directions-subway',
    topic: 'directions',
    level: 3,
    scene: '🚇',
    title: { ko: '어떻게 가요?', en: 'How do I get there?' },
    speakers: {
      A: { name: '도윤', en: 'Doyun', emoji: '👨', voice: 'low' },
      B: { name: '수아', en: 'Sua', emoji: '👩', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '수아 씨 집에 어떻게 가요?', en: 'Sua, how do I get to your place?' },
      { who: 'B', ko: '지하철 이 호선을 타고 시청역에서 내리세요.', en: 'Take subway Line 2 and get off at City Hall Station.' },
      { who: 'A', ko: '시청역이요? 몇 번 출구로 나가요?', en: 'City Hall? Which exit do I take?' },
      { who: 'B', ko: '삼 번 출구로 나와서 오 분쯤 걸어오세요.', en: 'Come out of Exit 3 and walk for about five minutes.' },
      { who: 'A', ko: '버스는 없어요?', en: 'Isn’t there a bus?' },
      { who: 'B', ko: '버스도 있지만 길이 많이 막혀요. 지하철이 더 빨라요.', en: 'There is, but the traffic is really bad. The subway is faster.' },
      { who: 'A', ko: '알겠어요. 그럼 지하철 타고 갈게요.', en: 'OK. Then I’ll take the subway.' },
    ],
    words: ['directions:howgo', 'directions:ride', 'directions:getoff', 'directions:exit'],
    questions: [
      {
        q: { ko: '도윤 씨는 몇 호선을 타요?', en: 'Which subway line does Doyun take?' },
        options: [
          { ko: '2호선', en: 'Line 2' },
          { ko: '3호선', en: 'Line 3' },
          { ko: '5호선', en: 'Line 5' },
        ],
        answer: 0,
        line: 1,
        why: 'Sua says 지하철 이 호선을 타고…: take subway Line 2 (이 = 2).',
      },
      {
        q: { ko: '몇 번 출구로 나가요?', en: 'Which exit does he take?' },
        options: [
          { ko: '3번 출구', en: 'Exit 3' },
          { ko: '2번 출구', en: 'Exit 2' },
          { ko: '5번 출구', en: 'Exit 5' },
        ],
        answer: 0,
        line: 3,
        why: 'Sua says 삼 번 출구로 나와서: come out of Exit 3 (삼 = 3). 오 분 is the five-minute walk after that.',
      },
      {
        q: { ko: '도윤 씨는 왜 버스를 안 타요?', en: 'Why doesn’t Doyun take the bus?' },
        options: [
          { ko: '길이 막혀서', en: 'The traffic is bad' },
          { ko: '버스가 없어서', en: 'There’s no bus' },
          { ko: '너무 비싸서', en: 'It’s too expensive' },
        ],
        answer: 0,
        line: 5,
        why: 'Sua says 버스도 있지만 길이 많이 막혀요: there is a bus, but the traffic is bad, so the subway is faster.',
      },
    ],
  },
  {
    id: 'past-busan',
    topic: 'past',
    level: 3,
    scene: '🌊',
    title: { ko: '부산 여행', en: 'A trip to Busan' },
    speakers: {
      A: { name: '건우', en: 'Geonwoo', emoji: '🧑', voice: 'low' },
      B: { name: '지은', en: 'Jieun', emoji: '👱‍♀️', voice: 'high' },
    },
    lines: [
      { who: 'A', ko: '지은 씨, 주말에 뭐 했어요?', en: 'Jieun, what did you do at the weekend?' },
      { who: 'B', ko: '친구하고 부산에 여행 갔어요.', en: 'I went on a trip to Busan with a friend.' },
      { who: 'A', ko: '와, 부산이요? 날씨는 어땠어요?', en: 'Wow, Busan? How was the weather?' },
      { who: 'B', ko: '토요일은 비가 와서 추웠어요. 일요일은 맑았어요.', en: 'It rained on Saturday, so it was cold. Sunday was sunny.' },
      { who: 'A', ko: '바다에도 갔어요?', en: 'Did you go to the beach, too?' },
      { who: 'B', ko: '네, 일요일에 갔어요. 사진도 많이 찍었어요.', en: 'Yes, on Sunday. We took lots of photos, too.' },
      { who: 'A', ko: '맛있는 것도 먹었어요?', en: 'Did you eat anything nice?' },
      { who: 'B', ko: '네, 회를 먹었어요. 좀 비쌌지만 진짜 맛있었어요.', en: 'Yes, we had raw fish. It was a bit pricey, but really delicious.' },
    ],
    words: ['past:went', 'past:wascold', 'past:wasdelicious', 'weather:raining'],
    questions: [
      {
        q: { ko: '토요일 날씨는 어땠어요?', en: 'What was the weather like on Saturday?' },
        options: [
          { ko: '비가 왔어요', en: 'It rained' },
          { ko: '맑았어요', en: 'It was sunny' },
          { ko: '눈이 왔어요', en: 'It snowed' },
        ],
        answer: 0,
        line: 3,
        why: 'Jieun says 토요일은 비가 와서 추웠어요: it rained on Saturday, so it was cold.',
      },
      {
        q: { ko: '지은 씨는 언제 바다에 갔어요?', en: 'When did Jieun go to the beach?' },
        options: [
          { ko: '일요일', en: 'on Sunday' },
          { ko: '토요일', en: 'on Saturday' },
          { ko: '금요일', en: 'on Friday' },
        ],
        answer: 0,
        line: 5,
        why: 'Jieun says 네, 일요일에 갔어요: they went on Sunday, the sunny day (일요일은 맑았어요).',
      },
      {
        q: { ko: '회는 어땠어요?', en: 'How was the raw fish?' },
        options: [
          { ko: '비쌌지만 맛있었어요', en: 'Pricey, but delicious' },
          { ko: '싸고 맛있었어요', en: 'Cheap and delicious' },
          { ko: '비싸고 맛없었어요', en: 'Pricey and not good' },
        ],
        answer: 0,
        line: 7,
        why: 'Jieun says 좀 비쌌지만 진짜 맛있었어요: it was a bit expensive, but (-지만) really delicious.',
      },
    ],
  },
  {
    id: 'hobbies-weekend',
    topic: 'hobbies',
    level: 3,
    scene: '🏊',
    title: { ko: '주말에 뭐 해요?', en: 'What do you do at weekends?' },
    speakers: {
      A: { name: '다은', en: 'Daeun', emoji: '👧', voice: 'high' },
      B: { name: '민호', en: 'Minho', emoji: '👦', voice: 'low' },
    },
    lines: [
      { who: 'A', ko: '민호 씨는 주말에 보통 뭐 해요?', en: 'Minho, what do you usually do at weekends?' },
      { who: 'B', ko: '날씨가 좋으면 등산해요. 다은 씨는요?', en: 'If the weather’s nice, I go hiking. What about you?' },
      { who: 'A', ko: '저는 집에서 그림을 그려요. 요즘은 수영도 배우고 싶어요.', en: 'I draw at home. And these days I’d like to learn to swim, too.' },
      { who: 'B', ko: '수영이요? 저는 작년에 배웠어요.', en: 'Swimming? I learned last year.' },
      { who: 'A', ko: '진짜요? 어려웠어요?', en: 'Really? Was it hard?' },
      { who: 'B', ko: '처음에는 무서웠지만 지금은 재미있어요.', en: 'At first it was scary, but now it’s fun.' },
      { who: 'A', ko: '그럼 다음 주에 같이 수영장에 가요!', en: 'Then let’s go to the pool together next week!' },
      { who: 'B', ko: '좋아요. 제가 가르쳐 줄게요.', en: 'Sure. I’ll teach you.' },
    ],
    words: ['hobbies:hiking', 'hobbies:swim', 'hobbies:draw', 'hobbies:wanttolearn'],
    questions: [
      {
        q: { ko: '민호 씨는 주말에 보통 뭐 해요?', en: 'What does Minho usually do at weekends?' },
        options: [
          { ko: '등산해요', en: 'He goes hiking' },
          { ko: '그림을 그려요', en: 'He draws' },
          { ko: '수영을 배워요', en: 'He takes swimming lessons' },
        ],
        answer: 0,
        line: 1,
        why: 'Minho says 날씨가 좋으면 등산해요: if the weather’s nice, he goes hiking. Drawing is Daeun’s hobby, and he learned to swim last year.',
      },
      {
        q: { ko: '민호 씨는 처음에 수영이 어땠어요?', en: 'How did Minho find swimming at first?' },
        options: [
          { ko: '무서웠어요', en: 'It was scary' },
          { ko: '재미있었어요', en: 'It was fun' },
          { ko: '쉬웠어요', en: 'It was easy' },
        ],
        answer: 0,
        line: 5,
        why: 'Minho says 처음에는 무서웠지만 지금은 재미있어요: at first it was scary, but (-지만) now it’s fun.',
      },
      {
        q: { ko: '두 사람은 다음 주에 뭐 해요?', en: 'What will they do next week?' },
        options: [
          { ko: '같이 수영장에 가요', en: 'Go to the pool together' },
          { ko: '같이 등산해요', en: 'Go hiking together' },
          { ko: '같이 그림을 그려요', en: 'Draw together' },
        ],
        answer: 0,
        line: [6, 7],
        why: 'Daeun says 그럼 다음 주에 같이 수영장에 가요!, and Minho agrees; he’ll even teach her (제가 가르쳐 줄게요).',
      },
    ],
  },
]);
