/**
 * Topic: 길 찾기 · Finding the way — asking where things are, places in town and transport.
 * Verbs are listed in the polite present form (해요체) with the dictionary form
 * alongside; the sentences also use the polite instruction form -(으)세요
 * (가세요 = please go). Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'directions',
  order: 7,
  emoji: '🗺️',
  color: 'mint',
  title: { ko: '길 찾기', en: 'Finding the way' },
  description: { ko: '길 묻기, 교통', en: 'Ask the way, take the subway' },

  notes: [
    {
      title: { ko: '어디예요?', en: 'Asking where' },
      text: 'Ask **…이/가 어디예요?** (“Where is …?”) or **…이/가 어디에 있어요?** (“Where is … located?”). Point with **여기** (here, near me), **거기** (there, near you) and **저기** (over there, away from us both).',
      examples: [
        { ko: '화장실이 어디예요?', en: 'Where is the restroom?' },
        { ko: '은행이 어디에 있어요?', en: 'Where is the bank?' },
        { ko: '저기 있어요.', en: 'It’s over there.' },
      ],
    },
    {
      title: { ko: '앞 · 뒤 · 옆', en: 'In front, behind, next to' },
      text: 'Say the place first, then the position word + **에**: 역 앞에 = in front of the station. With **있어요** this tells you where something is. For something you do there (meeting, waiting), use **에서** instead.',
      examples: [
        { ko: '은행 앞에 있어요.', en: 'It’s in front of the bank.' },
        { ko: '역 옆에 카페가 있어요.', en: 'There’s a café next to the station.' },
        { ko: '역 앞에서 만나요.', en: 'Let’s meet in front of the station.' },
      ],
    },
    {
      title: { ko: '(으)로', en: 'Which way and how' },
      text: '**(으)로** marks the direction you go and the way you travel. Use **으로** after a consonant (받침), and **로** after a vowel or after ㄹ.',
      examples: [
        { ko: '오른쪽으로 가세요.', en: 'Go right.' },
        { ko: '버스로 가요.', en: 'I go by bus.' },
        { ko: '지하철로 가요.', en: 'I go by subway.' },
      ],
    },
    {
      title: { ko: '-(으)세요', en: 'Polite instructions' },
      text: 'Tell someone politely what to do with **-(으)세요**: 가다 → **가세요**, 건너다 → **건너세요**, 타다 → **타세요**, 내리다 → **내리세요**. Careful: 돌다 → **도세요** (the ㄹ drops) and 걷다 → **걸으세요** (ㄷ turns into ㄹ).',
      examples: [
        { ko: '똑바로 가세요.', en: 'Go straight ahead.' },
        { ko: '사거리에서 왼쪽으로 도세요.', en: 'Turn left at the crossroads.' },
        { ko: '다음 역에서 내리세요.', en: 'Get off at the next station.' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'where', ko: '어디', en: 'where', level: 1, pos: 'pronoun', emoji: '📍', rom: 'eodi',
      note: 'In quick questions the 에 is often dropped: 어디 가요? = Where are you going?',
      example: { ko: '어디 가요?', en: 'Where are you going?' } },
    { id: 'here', ko: '여기', en: 'here', level: 1, pos: 'pronoun', emoji: '👇', rom: 'yeogi',
      note: '여기 is near me, 거기 near you, 저기 away from us both. (Calling out 여기요! means “excuse me!” in a café.)',
      example: { ko: '여기에 있어요!', en: 'It’s here!' } },
    { id: 'there', ko: '거기', en: 'there (near you)', level: 1, pos: 'pronoun', emoji: '👉', rom: 'geogi',
      note: 'For a place near the person you’re talking to, or a place you’ve both just mentioned.',
      example: { ko: '거기서 만나요!', en: 'Let’s meet there!' } },
    { id: 'overthere', ko: '저기', en: 'over there', level: 1, pos: 'pronoun', emoji: '🔭', rom: 'jeogi',
      note: 'For a place away from both of you, often while pointing. 저기요! is another way to say “excuse me!”.',
      example: { ko: '은행은 저기 있어요.', en: 'The bank is over there.' } },
    { id: 'right', ko: '오른쪽', en: 'right (side)', level: 1, pos: 'noun', emoji: '➡️', rom: 'oreunjjok',
      note: '쪽 means “side”, so 오른쪽 is “the right side”.',
      example: { ko: '오른쪽으로 가세요.', en: 'Go right.' } },
    { id: 'left', ko: '왼쪽', en: 'left (side)', level: 1, pos: 'noun', emoji: '⬅️', rom: 'oenjjok',
      note: '왼쪽에 = on the left. 왼쪽으로 = to the left.',
      example: { ko: '화장실은 왼쪽에 있어요.', en: 'The restroom is on the left.' } },
    { id: 'front', ko: '앞', en: 'front', level: 1, pos: 'noun', emoji: '🔼', rom: 'ap', pron: '압', avoid: ['straight'],
      enAlt: ['in front', 'in front of'],
      note: 'On its own it sounds like [압], but before a vowel the ㅍ comes back: 앞에 [아페].',
      example: { ko: '역 앞에서 만나요.', en: 'Let’s meet in front of the station.' } },
    { id: 'behind', ko: '뒤', en: 'back / behind', level: 1, pos: 'noun', emoji: '🔙', rom: 'dwi',
      note: 'The opposite of 앞 (front): 역 뒤에 = behind the station.',
      example: { ko: '제 뒤에 있어요.', en: 'It’s behind me.' } },
    { id: 'station', ko: '역', en: 'station', level: 1, pos: 'noun', emoji: '🚉', rom: 'yeok',
      note: 'Station names end in 역: 서울역 (Seoul Station), 강남역 (Gangnam Station).',
      example: { ko: '역이 어디예요?', en: 'Where is the station?' } },

    // ---- Level 2 ----
    { id: 'subway', ko: '지하철', en: 'subway / metro', level: 2, pos: 'noun', emoji: '🚇', rom: 'jihacheol',
      enAlt: ['underground', 'tube'],
      note: '“By subway” is 지하철로: after ㄹ, use 로 (not 으로).',
      example: { ko: '지하철로 가요.', en: 'I go by subway.' } },
    { id: 'bus', ko: '버스', en: 'bus', level: 2, pos: 'noun', emoji: '🚌', rom: 'beoseu',
      note: '“Take the bus” is 버스를 타요.',
      example: { ko: '버스로 가요?', en: 'Are you going by bus?' } },
    { id: 'taxi', ko: '택시', en: 'taxi', level: 2, pos: 'noun', emoji: '🚕', rom: 'taeksi', pron: '택씨', enAlt: ['cab'],
      note: 'After a ㄱ 받침, ㅅ gets tense: [택씨].',
      example: { ko: '택시를 타요.', en: 'I’ll take a taxi.' } },
    { id: 'toilet', ko: '화장실', en: 'toilet / restroom', level: 2, pos: 'noun', emoji: '🚻', rom: 'hwajangsil',
      enAlt: ['bathroom', 'washroom', 'loo', 'lavatory'],
      note: '화장 means “make-up”, so it’s literally a “powder room”.',
      example: { ko: '화장실이 어디예요?', en: 'Where is the restroom?' } },
    { id: 'bank', ko: '은행', en: 'bank', level: 2, pos: 'noun', emoji: '🏦', rom: 'eunhaeng',
      note: 'In fast speech the ㅎ is often weak, so it can sound like 으냉.',
      example: { ko: '은행이 어디에 있어요?', en: 'Where is the bank?' } },
    { id: 'hospital', ko: '병원', en: 'hospital', level: 2, pos: 'noun', emoji: '🏥', rom: 'byeongwon', enAlt: ['clinic'],
      note: '병원 is any clinic or hospital, so 병원에 가요 often just means “I’m going to the doctor’s”.',
      example: { ko: '병원에 가요.', en: 'I’m going to the doctor’s.' } },
    { id: 'near', ko: '가까워요', en: "it's close / near", level: 2, pos: 'adjective', emoji: '🤏', rom: 'gakkawoyo',
      dict: '가깝다', enAlt: ['is close', 'is near', 'nearby', 'close by'],
      note: 'ㅂ-irregular: 가깝 + 어요 → 가까워요. “Close to …” is …에서 가까워요.',
      example: { ko: '역에서 가까워요.', en: 'It’s close to the station.' } },
    { id: 'far', ko: '멀어요', en: "it's far", level: 2, pos: 'adjective', emoji: '🏔️', rom: 'meoreoyo', pron: '머러요',
      dict: '멀다', enAlt: ['is far', 'far away'],
      note: '“Far from …” is …에서 멀어요. The opposite is 가까워요.',
      example: { ko: '집이 멀어요?', en: 'Do you live far away?' } },
    { id: 'straight', ko: '똑바로', en: 'straight (ahead)', level: 2, pos: 'adverb', emoji: '⬆️', rom: 'ttokbaro',
      pron: '똑빠로', enAlt: ['straight on'],
      note: 'After a ㄱ 받침, ㅂ gets tense: [똑빠로]. You’ll also hear 쭉 가세요 (go straight on).',
      example: { ko: '똑바로 가세요.', en: 'Go straight ahead.' } },
    { id: 'next', ko: '옆', en: 'next to / beside', level: 2, pos: 'noun', emoji: '↔️', rom: 'yeop', pron: '엽', avoid: ['near'],
      enAlt: ['next', 'side'],
      note: 'On its own it sounds like [엽], but before a vowel the ㅍ comes back: 옆에 [여페].',
      example: { ko: '은행 옆에 카페가 있어요.', en: 'There’s a café next to the bank.' } },

    // ---- Level 3 ----
    { id: 'ride', ko: '타요', en: 'ride / get on', level: 3, pos: 'verb', emoji: '🎫', rom: 'tayo', dict: '타다',
      enAlt: ['take', 'get in', 'board'],
      note: 'What you ride takes 을/를: 버스를 타요 = I take the bus.',
      example: { ko: '지하철을 타요.', en: 'I take the subway.' } },
    { id: 'getoff', ko: '내려요', en: 'get off', level: 3, pos: 'verb', emoji: '🚏', rom: 'naeryeoyo', dict: '내리다',
      enAlt: ['get out'],
      note: 'You get off from a vehicle, so it takes 에서: 버스에서 내려요. 내리 + 어요 → 내려요.',
      example: { ko: '다음 역에서 내려요.', en: 'I get off at the next station.' } },
    { id: 'walk', ko: '걸어요', en: 'walk', level: 3, pos: 'verb', emoji: '👟', rom: 'georeoyo', pron: '거러요', dict: '걷다',
      note: 'ㄷ-irregular: before a vowel ㄷ turns into ㄹ (걷다 → 걸어요). “Go on foot” is 걸어서 가요.',
      example: { ko: '저는 매일 걸어요.', en: 'I walk every day.' } },
    { id: 'cross', ko: '건너요', en: 'cross (the road)', level: 3, pos: 'verb', emoji: '🚸', rom: 'geonneoyo', dict: '건너다',
      enAlt: ['cross the street'],
      note: 'What you cross takes 을/를: 길을 건너요.',
      example: { ko: '여기서 길을 건너요.', en: 'We cross the road here.' } },
    { id: 'turn', ko: '돌아요', en: 'turn', level: 3, pos: 'verb', emoji: '↪️', rom: 'dorayo', pron: '도라요', dict: '돌다',
      note: 'The polite instruction is 도세요: the ㄹ drops before -세요.',
      example: { ko: '왼쪽으로 돌아요.', en: 'You turn left.' } },
    { id: 'road', ko: '길', en: 'road / way', level: 3, pos: 'noun', emoji: '🛣️', rom: 'gil', enAlt: ['street', 'path', 'route'],
      note: 'Also “the way (to somewhere)”: 길을 잃었어요 = I’m lost.',
      example: { ko: '이 길로 가세요.', en: 'Go this way.' } },
    { id: 'crossroads', ko: '사거리', en: 'crossroads / intersection', level: 3, pos: 'noun', emoji: '🚦', rom: 'sageori',
      accept: ['네거리'], enAlt: ['junction'],
      note: '사 (four) + 거리 (streets): where four roads meet. It’s also called 네거리.',
      example: { ko: '사거리에서 왼쪽으로 가세요.', en: 'Go left at the crossroads.' } },
    { id: 'exit', ko: '출구', en: 'exit', level: 3, pos: 'noun', emoji: '🚪', rom: 'chulgu', enAlt: ['way out'],
      note: 'Subway exits are numbered: 3번 출구 = Exit 3. The entrance is 입구.',
      example: { ko: '3번 출구로 나오세요.', en: 'Come out of Exit 3.' } },
    { id: 'howgo', ko: '어떻게 가요?', en: 'how do I get there?', level: 3, pos: 'phrase', emoji: '🧭', rom: 'eotteoke gayo',
      pron: '어떠케 가요', enAlt: ['how do i get there', 'how to get there', 'how do i go there', 'how do you get there', 'how do i go'],
      note: 'Put the place first: 역에 어떻게 가요? ㅎ + ㄱ sounds like ㅋ: [어떠케].',
      example: { ko: '서울역에 어떻게 가요?', en: 'How do I get to Seoul Station?' } },
    { id: 'takes', ko: '걸려요', en: 'it takes (time)', level: 3, pos: 'verb', emoji: '⏱️', rom: 'geollyeoyo', dict: '걸리다',
      enAlt: ['takes', 'takes time', 'it takes time'],
      note: 'For time: 10분 걸려요 = it takes 10 minutes. Don’t mix it up with 걸어요 (walk).',
      example: { ko: '얼마나 걸려요?', en: 'How long does it take?' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-where', en: 'Where are we?', ko: '여기가 어디예요?',
      tiles: ['여기가', '어디예요'], gloss: ['here (subject)', 'where is it?'], words: ['here', 'where'] },
    { id: 's-overthere', en: 'The station is over there.', ko: '역은 저기 있어요.',
      tiles: ['역은', '저기', '있어요'], gloss: ['station (topic)', 'over there', 'is (there)'],
      words: ['station', 'overthere', 'day:have'],
      traps: [{ tile: '여기', why: '여기 means “here”. “Over there” is 저기.' }] },
    { id: 's-left', en: 'Go left, please.', ko: '왼쪽으로 가세요.',
      tiles: ['왼쪽으로', '가세요'], gloss: ['to the left', 'please go'], words: ['left', 'day:go'],
      traps: [
        { tile: '왼쪽에', why: 'To say which way to go, use (으)로: 왼쪽으로 가세요. 에 marks a place you go to, like 학교에.' },
        { tile: '오른쪽으로', why: '오른쪽 means “right”. “Left” is 왼쪽.' },
      ] },
    { id: 's-front', en: 'The café is in front of the station.', ko: '카페는 역 앞에 있어요.',
      tiles: ['카페는', '역', '앞에', '있어요'], gloss: ['café (topic)', 'station', 'in front (of)', 'is (there)'],
      words: ['cafe:cafe', 'station', 'front', 'day:have'],
      traps: [{ tile: '앞에서', why: 'To say where something is, use 에 with 있어요: 앞에 있어요. 에서 is for where an action happens.' }] },

    // ---- Level 2 ----
    { id: 's-next', level: 2, en: 'The restroom is next to the bank.', ko: '화장실은 은행 옆에 있어요.',
      tiles: ['화장실은', '은행', '옆에', '있어요'], gloss: ['restroom (topic)', 'bank', 'next to', 'is (there)'],
      words: ['toilet', 'bank', 'next', 'day:have'],
      traps: [{ tile: '앞에', why: '앞 means “in front”. “Next to” is 옆.' }] },
    { id: 's-behind', level: 2, en: 'The hospital is behind the station.', ko: '병원은 역 뒤에 있어요.',
      tiles: ['병원은', '역', '뒤에', '있어요'], gloss: ['hospital (topic)', 'station', 'behind', 'is (there)'],
      words: ['hospital', 'station', 'behind', 'day:have'],
      traps: [{ tile: '뒤에서', why: 'To say where something is, use 에 with 있어요: 뒤에 있어요. 에서 is for where an action happens.' }] },
    { id: 's-subway', level: 2, en: 'I take the subway to work.', ko: '회사에 지하철로 가요.',
      tiles: ['회사에', '지하철로', '가요'], gloss: ['to the office', 'by subway', 'go'],
      words: ['day:company', 'subway', 'day:go'], alts: [['지하철로', '회사에', '가요']],
      traps: [
        { tile: '지하철으로', why: 'After ㄹ, use 로, not 으로: 지하철로.' },
        { tile: '회사에서', why: '에 marks where you are going. 회사에서 would mean “from the office”.' },
      ] },
    { id: 's-near', level: 2, en: 'Is the hospital near here?', ko: '병원이 여기서 가까워요?',
      tiles: ['병원이', '여기서', '가까워요'], gloss: ['hospital (subject)', 'from here', 'is it close?'],
      words: ['hospital', 'here', 'near'], alts: [['여기서', '병원이', '가까워요']],
      traps: [{ tile: '멀어요', why: '멀어요 means “it’s far”. “Close / near” is 가까워요.' }] },
    { id: 's-far', level: 2, en: 'My school is far from home.', ko: '학교가 집에서 멀어요.',
      tiles: ['학교가', '집에서', '멀어요'], gloss: ['school (subject)', 'from home', 'is far'],
      words: ['day:school', 'day:home', 'far'], alts: [['집에서', '학교가', '멀어요']],
      traps: [
        { tile: '집에', why: '“Far from” a place takes 에서 (from): 집에서 멀어요.' },
        { tile: '가까워요', why: '가까워요 means “it’s close”. “Far” is 멀어요.' },
      ] },
    { id: 's-straight', level: 2, en: 'Go straight ahead from here.', ko: '여기서 똑바로 가세요.',
      tiles: ['여기서', '똑바로', '가세요'], gloss: ['from here', 'straight', 'please go'], words: ['here', 'straight', 'day:go'],
      traps: [{ tile: '오른쪽으로', why: '오른쪽으로 means “to the right”. “Straight ahead” is 똑바로.' }] },

    // ---- Level 3 ----
    // No particle questions here: 돌다 also takes 을/를 for the place you turn at (모퉁이를 돌다),
    // so 사거리를 isn't clearly wrong.
    { id: 's-turn', level: 3, en: 'Turn right at the crossroads.', ko: '사거리에서 오른쪽으로 도세요.', drill: false,
      tiles: ['사거리에서', '오른쪽으로', '도세요'], gloss: ['at the crossroads', 'to the right', 'please turn'],
      words: ['crossroads', 'right', 'turn'],
      traps: [
        { tile: '돌세요', why: '돌다 loses its ㄹ before -세요: 도세요, not 돌세요.' },
        { tile: '사거리에', why: 'Turning is something you do there, so the place takes 에서: 사거리에서.' },
      ] },
    { id: 's-cross', level: 3, en: 'Cross the road here.', ko: '여기서 길을 건너세요.',
      tiles: ['여기서', '길을', '건너세요'], gloss: ['here', 'road (object)', 'please cross'],
      words: ['here', 'road', 'cross'], alts: [['길을', '여기서', '건너세요']],
      traps: [{ tile: '길에서', why: 'The road is what you cross (the object), so it takes 을: 길을 건너세요.' }] },
    { id: 's-walk', level: 3, en: 'I walk from home to school.', ko: '집에서 학교까지 걸어요.',
      tiles: ['집에서', '학교까지', '걸어요'], gloss: ['from home', 'to school', 'walk'],
      words: ['day:home', 'day:school', 'walk'],
      traps: [
        { tile: '집에', why: '“From” a place is 에서: 집에서 학교까지 = from home to school.' },
        { tile: '걸려요', why: '걸려요 means “it takes (time)”. “Walk” is 걸어요.' },
      ] },
    { id: 's-exit', level: 3, en: 'Take a taxi at the exit.', ko: '출구에서 택시를 타세요.',
      tiles: ['출구에서', '택시를', '타세요'], gloss: ['at the exit', 'taxi (object)', 'please take (ride)'],
      words: ['exit', 'taxi', 'ride'], alts: [['택시를', '출구에서', '타세요']],
      traps: [
        { tile: '출구에', why: 'Taking a taxi is something you do there, so the place takes 에서: 출구에서.' },
        { tile: '내리세요', why: '내리세요 means “please get off”. To get on, use 타세요.' },
      ] },
    // No particle question here: 버스를 내리다 is also heard, so 를 isn't clearly wrong.
    { id: 's-getoff', level: 3, en: 'I get off the bus.', ko: '버스에서 내려요.', drill: false,
      tiles: ['버스에서', '내려요'], gloss: ['from the bus', 'get off'], words: ['bus', 'getoff'],
      traps: [
        { tile: '버스에', why: 'You get off (out of) a vehicle, so it takes 에서 (from): 버스에서 내려요.' },
        { tile: '타요', why: '타요 means “get on / ride”. Getting off is 내려요.' },
      ] },
    { id: 's-howgo', level: 3, en: 'How do I get there?', ko: '거기에 어떻게 가요?',
      tiles: ['거기에', '어떻게', '가요'], gloss: ['(to) there', 'how', 'do I go?'], words: ['there', 'howgo'],
      alts: [['어떻게', '거기에', '가요']],
      traps: [{ tile: '거기에서', why: '에서 would mean “from there”. For the place you’re going to, use 에: 거기에 어떻게 가요?' }] },
    { id: 's-takes', level: 3, en: 'It takes ten minutes from home to the station.', ko: '집에서 역까지 십 분 걸려요.',
      tiles: ['집에서', '역까지', '십', '분', '걸려요'], gloss: ['from home', 'to the station', 'ten', 'minutes', 'it takes'],
      words: ['day:home', 'station', 'numbers:sip', 'numbers:minute', 'takes'],
      traps: [{ tile: '열', why: 'Minutes use Sino-Korean numbers: 십 분, not 열 분.' }] },
  ],
});
