/**
 * Topic: 기분 · Feelings — saying how you feel.
 * Feeling words are taught in the polite 해요 form, with the dictionary form
 * alongside. As in Korean, they describe the speaker (“I”) or ask about “you”.
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'feelings',
  order: 6,
  emoji: '💗',
  color: 'pink',
  title: { ko: '기분', en: 'Feelings' },
  description: { ko: '기분 말하기', en: 'Say how you feel' },

  notes: [
    {
      title: { ko: '기분이 어때요?', en: 'How do you feel?' },
      text: 'Ask **기분이 어때요?** (How are you feeling?) and answer with a feeling word: **기분이 좋아요** (I’m in a good mood) or **기분이 안 좋아요** (I’m not). Make it stronger with **정말** or **너무** (really, so), softer with **조금** or **좀** (a little). Feeling words describe you, or ask about “you”: **피곤해요?** = Are you tired?',
      examples: [
        { ko: '오늘 기분이 정말 좋아요.', en: 'I’m in a really good mood today.' },
        { ko: '조금 피곤해요.', en: 'I’m a little tired.' },
        { ko: '괜찮아요? 아파요?', en: 'Are you okay? Are you sick?' },
      ],
    },
    {
      title: { ko: '좋아요 vs 좋아해요', en: 'Good vs like' },
      text: '**좋아요** comes from 좋다 (“to be good”), so the thing you like is its subject and takes **이/가**: **커피가 좋아요**. **좋아해요** comes from 좋아하다 (“to like”), an action verb, so the thing takes **을/를**: **커피를 좋아해요**. Both mean “I like coffee”. For other people, use 좋아해요. **싫어요** (I don’t like it) works like 좋아요.',
      examples: [
        { ko: '커피가 좋아요.', en: 'I like coffee.' },
        { ko: '친구가 커피를 좋아해요.', en: 'My friend likes coffee.' },
        { ko: '우유가 싫어요.', en: 'I don’t like milk.' },
      ],
    },
    {
      title: { ko: '재미있어요 · 심심해요', en: 'Fun, boring and bored' },
      text: '**재미있어요** (it’s fun / interesting) and **재미없어요** (it’s boring) describe a thing: a movie, a book, a class. **심심해요** means “I’m bored”: you have nothing to do. So a boring movie is 재미없어요, and you, with nothing to do, are 심심해요.',
      examples: [
        { ko: '이 영화 재미있어요!', en: 'This movie is fun!' },
        { ko: '이 책은 재미없어요.', en: 'This book is boring.' },
        { ko: '심심해요. 같이 놀아요!', en: 'I’m bored. Let’s hang out!' },
      ],
    },
    {
      title: { ko: '슬퍼요 · 무서워요 · 놀랐어요', en: 'Feelings that change shape' },
      text: 'When a stem ends in **ㅡ**, the ㅡ drops and the ending follows the vowel before it: **슬프다 → 슬퍼요**, **바쁘다 → 바빠요** (ㅏ, so 아요). In ㅂ-irregulars, **ㅂ** turns into **우**: **무섭다 → 무서워요**, **외롭다 → 외로워요**. Some feelings “happen” to you, so Korean often uses the past for how you feel now: **놀랐어요** (I’m surprised), **화났어요** (I’m angry).',
      examples: [
        { ko: '슬프다 → 슬퍼요', en: 'sad' },
        { ko: '바쁘다 → 바빠요', en: 'busy' },
        { ko: '무섭다 → 무서워요', en: 'scared / scary' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'good', ko: '좋아요', en: "it's good / I like it", level: 1, pos: 'adjective', emoji: '🙆', rom: 'joayo',
      pron: '조아요', dict: '좋다', avoid: ['cafe:okay', 'cafe:delicious'], enAlt: ['nice', 'sounds good'],
      note: 'The ㅎ is silent: [조아요]. 좋다 means “to be good”, so the thing you like takes 이/가: 커피가 좋아요.',
      example: { ko: '이 카페 정말 좋아요!', en: 'I really like this café!' } },
    { id: 'mood', ko: '기분', en: 'mood / feeling', level: 1, pos: 'noun', emoji: '🎭', rom: 'gibun',
      note: 'How you feel right now: 기분이 좋아요 = I’m in a good mood, 기분이 안 좋아요 = I’m in a bad mood.',
      example: { ko: '오늘 기분이 어때요?', en: 'How are you feeling today?' } },
    { id: 'happy', ko: '행복해요', en: "I'm happy", level: 1, pos: 'adjective', emoji: '😊', rom: 'haengbokaeyo',
      pron: '행보캐요', dict: '행복하다',
      note: '행복 (happiness) + 하다. The ㄱ and ㅎ blend into ㅋ: [행보캐요]. It’s a deep, warm happiness; for joy about good news, 기뻐요 is more usual.',
      example: { ko: '지금 정말 행복해요.', en: 'I’m really happy right now.' } },
    { id: 'sad', ko: '슬퍼요', en: "I'm sad", level: 1, pos: 'adjective', emoji: '😢', rom: 'seulpeoyo', dict: '슬프다',
      note: '슬프다 drops its ㅡ before 어요: 슬프 + 어요 → 슬퍼요. A sad movie or song is 슬퍼요 too.',
      example: { ko: '왜 슬퍼요? 괜찮아요?', en: 'Why are you sad? Are you okay?' } },
    { id: 'tired', ko: '피곤해요', en: "I'm tired", level: 1, pos: 'adjective', emoji: '🥱', rom: 'pigonhaeyo', dict: '피곤하다',
      note: '피곤 (tiredness) + 하다. For “sleepy”, Koreans say 졸려요.',
      example: { ko: '오늘 너무 피곤해요.', en: 'I’m so tired today.' } },
    { id: 'hurts', ko: '아파요', en: "it hurts / I'm sick", level: 1, pos: 'adjective', emoji: '🤕', rom: 'apayo', dict: '아프다',
      enAlt: ['painful', 'ill'],
      note: 'What hurts takes 이/가: 배가 아파요 = my stomach hurts. On its own, 아파요 means “I’m sick”.',
      example: { ko: '어디가 아파요?', en: 'Where does it hurt?' } },
    { id: 'fun', ko: '재미있어요', en: "it's fun / interesting", level: 1, pos: 'adjective', emoji: '😆', rom: 'jaemiisseoyo',
      pron: '재미이써요', dict: '재미있다',
      note: '재미 (fun) + 있어요 (there is). The opposite is 재미없어요 (it’s boring).',
      example: { ko: '이 영화 정말 재미있어요!', en: 'This movie is really fun!' } },
    { id: 'dislike', ko: '싫어요', en: "I don't like it", level: 1, pos: 'adjective', emoji: '👎', rom: 'sireoyo',
      pron: '시러요', dict: '싫다', enAlt: ['dislike', "don't like", "don't like it"],
      note: 'The ㅎ is silent: [시러요]. It works like 좋아요, with 이/가: 숙제가 싫어요. On its own it’s a blunt “No, I don’t want to!”',
      example: { ko: '저는 매운 음식이 싫어요.', en: 'I don’t like spicy food.' } },
    { id: 'love', ko: '사랑해요', en: 'I love you / love', level: 1, pos: 'verb', emoji: '💕', rom: 'saranghaeyo',
      dict: '사랑하다',
      note: '사랑 (love) + 하다. The one you love takes 을/를: 가족을 사랑해요 (I love my family).',
      example: { ko: '엄마, 사랑해요!', en: 'I love you, Mom!' } },

    // ---- Level 2 ----
    { id: 'glad', ko: '기뻐요', en: "I'm glad", level: 2, pos: 'adjective', emoji: '😁', rom: 'gippeoyo', dict: '기쁘다',
      avoid: ['happy'], enAlt: ['happy', 'joyful'],
      note: '기쁘다 drops its ㅡ: 기쁘 + 어요 → 기뻐요. It’s joy about something that happened, like good news.',
      example: { ko: '시험에 합격했어요! 너무 기뻐요!', en: 'I passed the exam! I’m so glad!' } },
    { id: 'bored', ko: '심심해요', en: "I'm bored", level: 2, pos: 'adjective', emoji: '😑', rom: 'simsimhaeyo', dict: '심심하다',
      note: 'You’re bored because you have nothing to do. If a thing (a movie, a class) is boring, say 재미없어요.',
      example: { ko: '심심해요. 뭐 해요?', en: 'I’m bored. What are you doing?' } },
    { id: 'angry', ko: '화나요', en: "I'm angry", level: 2, pos: 'verb', emoji: '😠', rom: 'hwanayo', dict: '화나다',
      enAlt: ['mad'],
      note: '화 (anger) + 나다 (to come out). For anger you feel right now, Koreans often use the past: 화났어요.',
      example: { ko: '왜 화났어요?', en: 'Why are you angry?' } },
    { id: 'scared', ko: '무서워요', en: "I'm scared / it's scary", level: 2, pos: 'adjective', emoji: '😱', rom: 'museowoyo',
      dict: '무섭다', enAlt: ['afraid'],
      note: 'ㅂ-irregular: 무섭 + 어요 → 무서워요. It means both “I’m scared” and “it’s scary”.',
      example: { ko: '이 영화 너무 무서워요!', en: 'This movie is so scary!' } },
    { id: 'busy', ko: '바빠요', en: "I'm busy", level: 2, pos: 'adjective', emoji: '🐝', rom: 'bappayo', dict: '바쁘다',
      note: '바쁘다 drops its ㅡ, and 바 has ㅏ, so it takes 아요: 바빠요 (not 바뻐요).',
      example: { ko: '요즘 너무 바빠요.', en: 'I’m really busy these days.' } },
    { id: 'worried', ko: '걱정돼요', en: "I'm worried", level: 2, pos: 'verb', emoji: '😟', rom: 'geokjeongdwaeyo',
      pron: '걱쩡돼요', dict: '걱정되다', enAlt: ['concerned'],
      note: 'What you’re worried about takes 이/가: 친구가 걱정돼요. Spelling tip: 되 + 어요 → 돼요 (never 되요).',
      example: { ko: '내일 시험이 걱정돼요.', en: 'I’m worried about tomorrow’s exam.' } },
    { id: 'like', ko: '좋아해요', en: 'like (something)', level: 2, pos: 'verb', emoji: '😍', rom: 'joahaeyo',
      pron: '조아해요', dict: '좋아하다', avoid: ['good'],
      note: 'An action verb (“to like”), so what you like takes 을/를: 커피를 좋아해요. Compare 좋아요, which takes 이/가: 커피가 좋아요.',
      example: { ko: '무슨 음식을 좋아해요?', en: 'What food do you like?' } },
    { id: 'boring', ko: '재미없어요', en: "it's boring", level: 2, pos: 'adjective', emoji: '😒', rom: 'jaemieopseoyo',
      pron: '재미업써요', dict: '재미없다', avoid: ['bored'],
      note: 'The opposite of 재미있어요, said about a thing: a movie, a book, a class. For “I’m bored”, say 심심해요.',
      example: { ko: '이 책은 좀 재미없어요.', en: 'This book is a bit boring.' } },
    { id: 'nervous', ko: '떨려요', en: "I'm nervous", level: 2, pos: 'verb', emoji: '😬', rom: 'tteollyeoyo', dict: '떨리다',
      avoid: ['worried'], enAlt: ['shaking', 'trembling'],
      note: '떨리다 means “to tremble”: your heart pounds before an exam, an interview or a first date.',
      example: { ko: '내일 면접이 있어요. 너무 떨려요.', en: 'I have an interview tomorrow. I’m so nervous.' } },
    { id: 'lonely', ko: '외로워요', en: "I'm lonely", level: 2, pos: 'adjective', emoji: '🥺', rom: 'oerowoyo', dict: '외롭다',
      note: 'ㅂ-irregular: 외롭 + 어요 → 외로워요.',
      example: { ko: '주말에는 가끔 외로워요.', en: 'I sometimes feel lonely on weekends.' } },

    // ---- Level 3 ----
    { id: 'excited', ko: '신나요', en: "I'm excited", level: 3, pos: 'verb', emoji: '🤩', rom: 'sinnayo', dict: '신나다',
      avoid: ['fun'], enAlt: ['exciting', 'thrilled'],
      note: 'Bubbly excitement while doing something fun: a party, a concert, the start of the holidays. For looking forward to something, 기대돼요 is common too.',
      example: { ko: '방학이에요! 너무 신나요!', en: 'It’s the holidays! I’m so excited!' } },
    { id: 'shy', ko: '부끄러워요', en: "I'm shy / embarrassed", level: 3, pos: 'adjective', emoji: '😳', rom: 'bukkeureowoyo',
      dict: '부끄럽다',
      note: 'ㅂ-irregular: 부끄럽 + 어요 → 부끄러워요. It covers feeling shy and feeling embarrassed.',
      example: { ko: '아, 너무 부끄러워요!', en: 'Oh, I’m so embarrassed!' } },
    { id: 'stress', ko: '스트레스', en: 'stress', level: 3, pos: 'noun', emoji: '🤯', rom: 'seuteureseu', enAlt: ['stressed'],
      note: 'You “receive” stress in Korean: 스트레스를 받아요 = I get stressed.',
      example: { ko: '요즘 스트레스를 많이 받아요.', en: 'I’m really stressed these days.' } },
    { id: 'heart', ko: '마음', en: 'heart / mind', level: 3, pos: 'noun', emoji: '💖', rom: 'maeum', avoid: ['mood'],
      note: 'Your heart in the emotional sense: your feelings and mind. The heart that beats is 심장.',
      example: { ko: '제 마음이에요. 받아 주세요.', en: 'It’s from my heart. Please take it.' } },
    { id: 'smile', ko: '웃어요', en: 'laugh / smile', level: 3, pos: 'verb', emoji: '😃', rom: 'useoyo', pron: '우서요',
      dict: '웃다',
      note: '웃다 means both “laugh” and “smile”. If something is funny, say 웃겨요!',
      example: { ko: '친구가 많이 웃어요.', en: 'My friend laughs a lot.' } },
    { id: 'cry', ko: '울어요', en: 'cry', level: 3, pos: 'verb', emoji: '😭', rom: 'ureoyo', pron: '우러요', dict: '울다',
      note: 'The ㄹ slides over: [우러요]. When things are tough, Koreans say 울고 싶어요 (I want to cry).',
      example: { ko: '아기가 울어요.', en: 'The baby is crying.' } },
    { id: 'hard', ko: '힘들어요', en: "it's hard / I'm struggling", level: 3, pos: 'adjective', emoji: '😩',
      rom: 'himdeureoyo', pron: '힘드러요', dict: '힘들다', avoid: ['tired'], enAlt: ['tough', 'tiring'],
      note: '힘 (strength) + 들다 (to take): it takes a lot out of you. For a hard question or subject, 어려워요 (difficult) is better.',
      example: { ko: '오늘 일이 너무 힘들어요.', en: 'Work is really tough today.' } },
    { id: 'surprised', ko: '놀랐어요', en: 'I was surprised', level: 3, pos: 'verb', emoji: '😲', rom: 'nollasseoyo',
      pron: '놀라써요', dict: '놀라다', form: 'past', enAlt: ['surprised', 'was surprised'],
      note: 'Koreans use the past, 놀랐어요, even for “I’m surprised!” right now. Add 깜짝 for a sudden fright: 깜짝 놀랐어요!',
      example: { ko: '와, 정말 놀랐어요!', en: 'Wow, I was really surprised!' } },
    { id: 'upset', ko: '속상해요', en: "I'm upset", level: 3, pos: 'adjective', emoji: '😞', rom: 'soksanghaeyo',
      pron: '속쌍해요', dict: '속상하다', avoid: ['sad', 'angry'],
      note: '속 (inside) + 상하다 (to be hurt): upset when things go wrong. The ㅅ after ㄱ gets tense: [속쌍해요].',
      example: { ko: '지갑을 잃어버렸어요. 너무 속상해요.', en: 'I lost my wallet. I’m so upset.' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-mood', en: "I'm tired. I'm not in a good mood.", ko: '피곤해요. 기분이 안 좋아요.',
      tiles: ['피곤해요', '기분이', '안', '좋아요'], gloss: ["I'm tired", 'mood (subject)', 'not', 'is good'],
      words: ['tired', 'mood', 'good'],
      traps: [
        { tile: '기분을', why: '좋아요 describes something (“is good”), so 기분 is its subject and takes 이: 기분이 좋아요.' },
        { tile: '기분에', why: '기분에 안 좋아요 would mean “it’s bad for your mood” (like 건강에 안 좋아요, bad for your health). Here your mood itself isn’t good, so 기분 is the subject: 기분이 안 좋아요.' },
        { tile: '좋아해요', why: '좋아해요 means “to like (something)”. For your mood, use 좋아요: 기분이 좋아요.' },
      ] },
    { id: 's-coffee', en: "I like coffee. I don't like milk.", ko: '커피가 좋아요. 우유는 싫어요.',
      tiles: ['커피가', '좋아요', '우유는', '싫어요'], gloss: ['coffee (subject)', 'is good (I like it)', 'milk (topic)', "I don't like it"],
      words: ['cafe:coffee', 'good', 'cafe:milk', 'dislike'],
      traps: [
        { tile: '커피를', why: '좋아요 means “is good”, so the thing you like is its subject and takes 가: 커피가 좋아요. (커피를 goes with 좋아해요.)' },
        { tile: '커피에', why: '커피에 좋아요 would mean “it’s good for coffee” (like 건강에 좋아요, good for your health). To say you like coffee, coffee is the subject: 커피가 좋아요.' },
      ] },
    { id: 's-love', en: "I love you. I'm really happy.", ko: '사랑해요. 정말 행복해요.',
      tiles: ['사랑해요', '정말', '행복해요'], gloss: ['I love you', 'really', "I'm happy"], words: ['love', 'happy'],
      traps: [
        { tile: '좋아해요', why: '좋아해요 means “I like you”. “I love you” is 사랑해요.' },
        { tile: '슬퍼요', why: '슬퍼요 means “I’m sad”. “Happy” is 행복해요.' },
        { tile: '행복했어요', why: '행복했어요 is the past (“I was happy”). For how you feel now, say 행복해요.' },
      ] },
    { id: 's-fun', en: 'Korean is fun.', ko: '한국어가 재미있어요.',
      tiles: ['한국어가', '재미있어요'], gloss: ['Korean (subject)', 'is fun'], words: ['day:korean', 'fun'],
      traps: [
        { tile: '한국어를', why: '재미있어요 describes something, so the thing that is fun is its subject and takes 가: 한국어가 재미있어요.' },
        { tile: '재미없어요', why: '재미없어요 means “it’s boring”. “Fun” is 재미있어요.' },
      ] },

    // ---- Level 2 ----
    { id: 's-likemovies', level: 2, en: 'My friend likes movies.', ko: '친구가 영화를 좋아해요.',
      tiles: ['친구가', '영화를', '좋아해요'], gloss: ['friend (subject)', 'movies (object)', 'likes'],
      words: ['day:friend', 'day:movie', 'like'],
      traps: [{ tile: '영화가', why: '좋아해요 is an action verb (“to like”), so what someone likes is its object and takes 를: 영화를 좋아해요.' }] },
    { id: 's-worried', level: 2, en: "My friend is sick. I'm worried.", ko: '친구가 아파요. 걱정돼요.',
      tiles: ['친구가', '아파요', '걱정돼요'], gloss: ['friend (subject)', 'is sick', "I'm worried"],
      words: ['day:friend', 'hurts', 'worried'],
      traps: [
        { tile: '걱정되요', why: '되 + 어요 merge into 돼요, so it’s 걱정돼요. 되요 is a common misspelling.' },
        { tile: '친구를', why: '아파요 describes your friend, so 친구 is the subject and takes 가: 친구가 아파요.' },
      ] },
    { id: 's-bored', level: 2, en: "This movie is boring. I'm bored.", ko: '이 영화는 재미없어요. 심심해요.',
      tiles: ['이', '영화는', '재미없어요', '심심해요'], gloss: ['this', 'movie (topic)', "it's boring", "I'm bored"],
      words: ['day:movie', 'boring', 'bored'] },
    { id: 's-lonely', level: 2, en: 'I get a little lonely at night.', ko: '밤에는 좀 외로워요.',
      tiles: ['밤에는', '좀', '외로워요'], gloss: ['at night (topic)', 'a little', "I'm lonely"], words: ['day:night', 'lonely'],
      traps: [{ tile: '외롭어요', why: '외롭다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 외로워요.' }] },

    // ---- Level 3 ----
    { id: 's-busy', level: 3, en: "I'm so busy at work. It's hard.", ko: '회사에서 너무 바빠요. 힘들어요.',
      tiles: ['회사에서', '너무', '바빠요', '힘들어요'], gloss: ['at the company', 'so', "I'm busy", "it's hard"],
      words: ['day:company', 'busy', 'hard'],
      traps: [
        { tile: '바뻐요', why: '바쁘다 drops its ㅡ, and the vowel before it is ㅏ, so it takes 아요: 바빠요.' },
        { tile: '바빴어요', why: '바빴어요 is the past (“I was busy”). For now, say 바빠요.' },
        { tile: '회사에', why: '회사에서 means “at work”, where things happen. 회사에 is for going there (회사에 가요) or being there (회사에 있어요).' },
      ] },
    { id: 's-upset', level: 3, en: "My friend is angry. I'm upset.", ko: '친구가 화났어요. 속상해요.',
      tiles: ['친구가', '화났어요', '속상해요'], gloss: ['friend (subject)', 'is angry (got angry)', "I'm upset"],
      words: ['day:friend', 'angry', 'upset'],
      traps: [
        { tile: '친구를', why: '화나다 has no object: the one who is angry is the subject and takes 가: 친구가 화났어요.' },
        { tile: '친구에', why: '친구 is the one who is angry (the subject), so it takes 가: 친구가 화났어요.' },
      ] },
    { id: 's-surprised', level: 3, en: "I was surprised. I'm really glad!", ko: '놀랐어요. 정말 기뻐요!',
      tiles: ['놀랐어요', '정말', '기뻐요'], gloss: ['I was surprised', 'really', "I'm glad"], words: ['surprised', 'glad'],
      traps: [
        { tile: '놀라요', why: '“I was surprised” is past, and Korean uses the past for surprise anyway: 놀랐어요.' },
        { tile: '기빠요', why: '기쁘다 drops its ㅡ, and the vowel before it is ㅣ (not ㅏ or ㅗ), so it takes 어요: 기뻐요.' },
        { tile: '슬퍼요', why: '슬퍼요 means “I’m sad”. “Glad” is 기뻐요.' },
      ] },
    { id: 's-nervous', level: 3, en: "I'm so nervous. I'm a bit shy.", ko: '너무 떨려요. 좀 부끄러워요.',
      tiles: ['너무', '떨려요', '좀', '부끄러워요'], gloss: ['so', "I'm nervous", 'a little', "I'm shy"], words: ['nervous', 'shy'],
      traps: [
        { tile: '떨리요', why: '떨리다 → 떨리 + 어요: ㅣ and ㅓ merge into ㅕ → 떨려요.' },
        { tile: '부끄럽어요', why: '부끄럽다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 부끄러워요.' },
        { tile: '신나요', why: '신나요 means “I’m excited”. “Nervous” is 떨려요.' },
      ] },
    { id: 's-scared', level: 3, en: "I'm so scared. I want to cry.", ko: '너무 무서워요. 울고 싶어요.',
      tiles: ['너무', '무서워요', '울고', '싶어요'], gloss: ['so', "I'm scared", 'to cry', 'I want'], words: ['scared', 'cry'],
      traps: [
        { tile: '무섭어요', why: '무섭다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 무서워요.' },
        { tile: '웃고', why: '웃고 싶어요 means “I want to laugh”. “Cry” is 울다: 울고 싶어요.' },
      ] },
    { id: 's-heart', level: 3, en: "My heart aches. I'm so sad.", ko: '마음이 아파요. 너무 슬퍼요.',
      tiles: ['마음이', '아파요', '너무', '슬퍼요'], gloss: ['heart (subject)', 'hurts', 'so', "I'm sad"],
      words: ['heart', 'hurts', 'sad'],
      traps: [
        { tile: '마음을', why: '아파요 describes how something feels, so what hurts is its subject and takes 이: 마음이 아파요.' },
        { tile: '슬파요', why: '슬프다 drops its ㅡ, and the vowel before it is ㅡ (not ㅏ or ㅗ), so it takes 어요: 슬퍼요.' },
      ] },
    { id: 's-smile', level: 3, en: "I'm laughing with my friend. I'm so excited!", ko: '친구하고 웃어요. 너무 신나요!',
      tiles: ['친구하고', '웃어요', '너무', '신나요'], gloss: ['with my friend', 'laugh', 'so', "I'm excited"],
      words: ['day:friend', 'smile', 'excited'],
      traps: [
        { tile: '울어요', why: '울어요 means “cry”. “Laugh” is 웃어요.' },
        { tile: '심심해요', why: '심심해요 means “I’m bored”. “Excited” is 신나요.' },
        { tile: '재미없어요', why: '재미없어요 means “it’s boring”. “Excited” is 신나요.' },
      ] },
    { id: 's-stress', level: 3, en: 'I have no stress on weekends.', ko: '주말에는 스트레스가 없어요.',
      tiles: ['주말에는', '스트레스가', '없어요'], gloss: ['on weekends (topic)', 'stress (subject)', "there isn't"],
      words: ['day:weekend', 'stress', 'day:nothave'], alts: [['스트레스가', '주말에는', '없어요']],
      traps: [{ tile: '스트레스를', why: '없어요 says that something isn’t there. That thing is the subject, so it takes 가: 스트레스가 없어요.' }] },
  ],
});
