/**
 * Grammar patterns, practised in Grammar Cards (js/games/grammar-cards.js):
 * the endings that join two ideas (-고, -지만, -아서/어서, -(으)면, -(으)려고,
 * -(으)면서…), the helper endings for "can", "must" and "may", and the everyday
 * endings -고 있어요, -아/어 보다, -(으)ㄹ게요, -는데, -(으)ㄴ 적이 있어요, the polite
 * -(으)세요 / -(으)셨어요 and -지 마세요.
 *
 * Each pattern has an intro card (meaning, how to make it, a note, examples;
 * the table of forms is built by the grammar engine) and questions: a sentence
 * with one word blanked out, to be filled with the right form.
 *
 * A question only names the word and its ending — the grammar engine
 * (js/core/grammar.js) makes the form, checks `answer` against it, and builds
 * the wrong options with their explanations:
 *   contrast: other endings that give the sentence a different meaning (the
 *             English shows which one is meant). Never list one that could
 *             also be right here: -(으)면/-(으)ㄹ 때, -아서/-(으)니까,
 *             -아서/-고, -(으)ㄴ 후에/-고/-아서, -(으)ㄹ 수 있어요/-아도 돼요,
 *             -는데/-지만/-(으)니까/-고, -(으)세요/-아/어 보세요, -(으)러/-(으)려고,
 *             -아/어 봤어요/-(으)ㄴ 적이 있어요 (or 없어요).
 *   traps:    hand-written wrong options, each with its reason.
 *   meaning:  what the ending means in this sentence, if it's not the usual one.
 * Fields: id, ko, en, answer (the form as it appears in ko), dict, pos
 * ('verb' | 'adjective'), tense ('past' for -고, -지만, -(으)니까, -(으)ㄹ 때, -는데),
 * form (another ending of this pattern), words (vocabulary refs, 'topic:id':
 * questions whose words you know come first).
 */
Mallang.content.registerGrammar([
  {
    id: 'go',
    order: 1,
    level: 1,
    emoji: '➕',
    form: 'go',
    title: { ko: '-고', en: 'and' },
    meaning: 'Joins two actions or two facts: “and”. With actions, it also means “and then”.',
    how: 'Put **고** straight onto the stem (the dictionary form without 다): 먹다 → **먹고**, 가다 → **가고**, 춥다 → **춥고**. No 아/어, no 으, and irregular words don’t change.',
    note: 'Usually only the last verb shows the tense: 어제 점심을 **먹고** 산책했어요 = Yesterday I had lunch and then took a walk. To say how you travel, Korean uses -고 too: 버스를 **타고** 가요 = I go by bus.',
    examples: [
      { ko: '이 카페는 싸고 맛있어요.', en: 'This café is cheap and tasty.' },
      { ko: '주말에 청소하고 쉬어요.', en: 'At the weekend I clean and then rest.' },
      { ko: '어제 친구하고 영화를 보고 밥을 먹었어요.', en: 'Yesterday I watched a movie with a friend and then had a meal.' },
    ],
    questions: [
      {
        id: 'shower',
        ko: '아침에 샤워하고 커피를 마셔요.',
        en: 'In the morning I shower and then drink coffee.',
        answer: '샤워하고',
        dict: '샤워하다',
        words: ['day:morning', 'day:shower', 'cafe:coffee', 'day:drink'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'cheap',
        ko: '이 가게는 싸고 좋아요.',
        en: 'This shop is cheap and good.',
        answer: '싸고',
        dict: '싸다',
        pos: 'adjective',
        words: ['shopping:shop', 'shopping:cheap', 'feelings:good'],
        contrast: ['jiman', 'myeon'],
        traps: [{ text: '싸서', why: '싸서 is -아서/어서: “it’s cheap, so it’s good”. The sentence just adds two facts: cheap and good → 싸고.' }],
      },
      {
        id: 'exercise',
        ko: '저녁에 운동하고 샤워해요.',
        en: 'In the evening I work out and then shower.',
        answer: '운동하고',
        dict: '운동하다',
        words: ['day:evening', 'day:exercise', 'day:shower'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'clear',
        ko: '오늘은 날씨가 맑고 따뜻해요.',
        en: 'Today the weather is clear and warm.',
        answer: '맑고',
        dict: '맑다',
        pos: 'adjective',
        words: ['day:today', 'weather:weather', 'weather:clear', 'weather:warm'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'lunch',
        ko: '점심을 먹고 산책해요.',
        en: 'I have lunch and then take a walk.',
        answer: '먹고',
        dict: '먹다',
        words: ['day:lunch', 'day:eat', 'hobbies:stroll'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'cold',
        ko: '어제는 춥고 흐렸어요.',
        en: 'Yesterday it was cold and cloudy.',
        answer: '춥고',
        dict: '춥다',
        pos: 'adjective',
        words: ['day:yesterday', 'weather:cold', 'weather:cloudy'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'bus',
        ko: '저는 버스를 타고 학교에 가요.',
        en: 'I go to school by bus.',
        answer: '타고',
        dict: '타다',
        words: ['directions:bus', 'directions:ride', 'day:school', 'day:go'],
        contrast: ['jiman', 'myeon'],
        traps: [{ text: '타서', why: 'To say how you travel, Korean uses -고: 버스를 타고 가요 = I go by bus. -아서/어서 gives a reason or the next step, not the way you go.' }],
      },
      {
        id: 'music',
        ko: '주말에 음악을 듣고 책을 읽었어요.',
        en: 'On the weekend I listened to music and read a book.',
        answer: '듣고',
        dict: '듣다',
        words: ['day:weekend', 'hobbies:music', 'hobbies:listen', 'day:book', 'day:read'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'umbrella',
        ko: '아침에 우산을 들고 나갔어요.',
        en: 'In the morning I took an umbrella and went out.',
        answer: '들고',
        dict: '들다',
        words: ['day:morning', 'weather:umbrella', 'day:goout'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'graduate',
        ko: '동생은 작년에 대학교를 졸업했고 지금은 회사에 다녀요.',
        en: 'My younger sibling graduated from university last year and now works at a company.',
        answer: '졸업했고',
        dict: '졸업하다',
        tense: 'past',
        meaning: '“and” (the first part is in the past, the second is about now)',
        words: ['people:sibling', 'past:lastyear', 'work:university', 'work:graduation', 'work:attend'],
        contrast: ['jiman', 'myeon'],
        traps: [{ text: '졸업했어고', why: 'For the past, -고 goes straight onto the past stem (졸업했어요 without 어요): 졸업했 + 고 → 졸업했고.' }],
      },
      {
        id: 'cute',
        ko: '옆집 아이는 귀엽고 착해요.',
        en: 'The kid next door is cute and kind.',
        answer: '귀엽고',
        dict: '귀엽다',
        pos: 'adjective',
        words: ['directions:next', 'day:home', 'people:child', 'people:kind'],
        contrast: ['jiman', 'myeon'],
      },
    ],
  },

  {
    id: 'jiman',
    order: 2,
    level: 1,
    emoji: '⚖️',
    form: 'jiman',
    title: { ko: '-지만', en: 'but' },
    meaning: 'Joins two ideas that go against each other: “but”.',
    how: 'Put **지만** straight onto the stem, just like -고: 먹다 → **먹지만**, 비싸다 → **비싸지만**, 춥다 → **춥지만**. No 아/어, no 으, and irregular words don’t change. For the past, add it to the past stem: 갔어요 → **갔지만**, 먹었어요 → **먹었지만**.',
    note: 'Put 은/는 on the two things you compare: 여름**은** 좋지만 겨울**은** 싫어요 = I like summer, but I don’t like winter.',
    examples: [
      { ko: '한국어는 어렵지만 재미있어요.', en: 'Korean is hard, but it’s fun.' },
      { ko: '이 가방은 싸지만 좋아요.', en: 'This bag is cheap, but it’s good.' },
      { ko: '어제는 피곤했지만 운동했어요.', en: 'I was tired yesterday, but I worked out.' },
    ],
    questions: [
      {
        id: 'expensive',
        ko: '좀 비싸지만 이걸로 할게요.',
        en: 'It’s a bit expensive, but I’ll take this one.',
        answer: '비싸지만',
        dict: '비싸다',
        pos: 'adjective',
        words: ['shopping:expensive', 'shopping:takethis'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'busy',
        ko: '어제는 바빴지만 재미있었어요.',
        en: 'Yesterday I was busy, but it was fun.',
        answer: '바빴지만',
        dict: '바쁘다',
        pos: 'adjective',
        tense: 'past',
        words: ['day:yesterday', 'past:wasbusy', 'past:wasfun'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'coffee',
        ko: '커피는 좋아하지만 우유는 안 좋아해요.',
        en: 'I like coffee, but I don’t like milk.',
        answer: '좋아하지만',
        dict: '좋아하다',
        words: ['cafe:coffee', 'feelings:like', 'cafe:milk'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'spicy',
        ko: '김치는 맵지만 맛있어요.',
        en: 'Kimchi is spicy, but it’s tasty.',
        answer: '맵지만',
        dict: '맵다',
        pos: 'adjective',
        words: ['cafe:kimchi', 'cafe:spicy', 'cafe:delicious'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'near',
        ko: '학교가 가깝지만 버스를 타요.',
        en: 'School is close, but I take the bus.',
        answer: '가깝지만',
        dict: '가깝다',
        pos: 'adjective',
        words: ['day:school', 'directions:near', 'directions:bus', 'directions:ride'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'late',
        ko: '어젯밤 늦게 잤지만 일찍 일어났어요.',
        en: 'I went to bed late last night, but I got up early.',
        answer: '잤지만',
        dict: '자다',
        tense: 'past',
        words: ['past:lastnight', 'past:slept', 'day:early', 'day:getup'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'cold',
        ko: '어제는 추웠지만 오늘은 따뜻해요.',
        en: 'Yesterday it was cold, but today it’s warm.',
        answer: '추웠지만',
        dict: '춥다',
        pos: 'adjective',
        tense: 'past',
        words: ['day:yesterday', 'past:wascold', 'day:today', 'weather:warm'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'music',
        ko: '한국 음악을 매일 듣지만 한국어는 잘 몰라요.',
        en: 'I listen to Korean music every day, but I don’t know Korean well.',
        answer: '듣지만',
        dict: '듣다',
        words: ['hobbies:music', 'day:everyday', 'hobbies:listen', 'day:korean'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'korean',
        ko: '처음에는 한국어를 하나도 몰랐지만 지금은 조금 알아요.',
        en: 'At first I didn’t know any Korean at all, but now I know a little.',
        answer: '몰랐지만',
        dict: '모르다',
        tense: 'past',
        words: ['day:korean', 'past:didntknow'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'laptop',
        ko: '제 노트북은 좀 무겁지만 빨라요.',
        en: 'My laptop is a bit heavy, but it’s fast.',
        answer: '무겁지만',
        dict: '무겁다',
        pos: 'adjective',
        words: ['people:me', 'travel:heavy', 'travel:fast'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'shop',
        ko: '이 가게는 옷은 팔지만 신발은 안 팔아요.',
        en: 'This shop sells clothes, but it doesn’t sell shoes.',
        answer: '팔지만',
        dict: '팔다',
        words: ['shopping:shop', 'shopping:clothes', 'shopping:sell', 'shopping:shoes'],
        contrast: ['myeon', 'aseo'],
      },
    ],
  },

  {
    id: 'aseo',
    order: 3,
    level: 2,
    emoji: '➡️',
    form: 'aseo',
    title: { ko: '-아서/어서', en: 'so / and then' },
    meaning: 'Two uses. A reason, “so / because”: **추워서** = it’s cold, so… Or the next step, “and then”, when the second action happens where you went, with the person you met, or with what you just got: **가서** (go there and…), **만나서** (meet and … together), **사서** (buy it and…).',
    how: 'Take the 아/어 form (the present without 요) and add **서**: 가요 → **가서**, 먹어요 → **먹어서**, 해요 → **해서**, 마셔요 → **마셔서**. Irregular words change just as in the present: 들어요 → **들어서**, 추워요 → **추워서**.',
    note: '-아서/어서 never takes the past; the last verb shows the tense: 어제 **바빠서** 못 갔어요 = I was busy yesterday, so I couldn’t go (not 바빴어서). For a reason, don’t use it before a request or a suggestion (…세요, …(으)ㄹ까요?): that’s what -(으)니까 is for. For “and then” it’s fine: 빵을 **사서** 같이 먹을까요? = Shall we buy some bread and eat it together? Two fixed phrases: **만나서** 반가워요 = Nice to meet you, **늦어서** 미안해요 = Sorry I’m late.',
    examples: [
      { ko: '시간이 없어서 택시를 탔어요.', en: 'I didn’t have time, so I took a taxi.' },
      { ko: '학교에 가서 친구를 만났어요.', en: 'I went to school and met a friend there.' },
      { ko: '빵을 사서 먹었어요.', en: 'I bought some bread and ate it.' },
    ],
    questions: [
      {
        id: 'cold',
        ko: '어제는 추워서 집에 있었어요.',
        en: 'It was cold yesterday, so I stayed home.',
        answer: '추워서',
        dict: '춥다',
        pos: 'adjective',
        meaning: '“so / because” (a reason)',
        words: ['day:yesterday', 'weather:cold', 'day:home', 'day:have'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'hungry',
        ko: '배고파서 빵을 먹었어요.',
        en: 'I was hungry, so I ate some bread.',
        answer: '배고파서',
        dict: '배고프다',
        pos: 'adjective',
        meaning: '“so / because” (a reason)',
        words: ['cafe:hungry', 'cafe:bread', 'past:ate'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'rain',
        ko: '비가 와서 우산을 샀어요.',
        en: 'It was raining, so I bought an umbrella.',
        answer: '와서',
        dict: '오다',
        meaning: '“so / because” (a reason)',
        words: ['weather:raining', 'weather:umbrella', 'past:bought'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'way',
        ko: '길을 몰라서 늦었어요.',
        en: 'I didn’t know the way, so I was late.',
        answer: '몰라서',
        dict: '모르다',
        meaning: '“so / because” (a reason)',
        words: ['directions:road', 'past:didntknow'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'walk',
        ko: '오늘 많이 걸어서 피곤해요.',
        en: 'I walked a lot today, so I’m tired.',
        answer: '걸어서',
        dict: '걷다',
        meaning: '“so / because” (a reason)',
        words: ['day:today', 'directions:walk', 'feelings:tired'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'meet',
        ko: '친구를 만나서 영화를 봤어요.',
        en: 'I met up with a friend and we watched a movie.',
        answer: '만나서',
        dict: '만나다',
        meaning: '“and then” (you meet up, then do the next thing together)',
        words: ['day:friend', 'day:meet', 'day:movie', 'past:saw'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'library',
        ko: '도서관에 가서 공부했어요.',
        en: 'I went to the library and studied there.',
        answer: '가서',
        dict: '가다',
        meaning: '“and then” (you go there, then do the next thing there)',
        words: ['day:library', 'day:go', 'past:studied'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'cake',
        ko: '케이크를 만들어서 친구에게 줬어요.',
        en: 'I made a cake and gave it to my friend.',
        answer: '만들어서',
        dict: '만들다',
        meaning: '“and then” (you make it, then do the next thing with it)',
        words: ['cafe:cake', 'past:made', 'day:friend', 'cafe:please'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'homework',
        ko: '숙제가 너무 어려워서 친구한테 전화했어요.',
        en: 'The homework was too hard, so I called a friend.',
        answer: '어려워서',
        dict: '어렵다',
        pos: 'adjective',
        meaning: '“so / because” (a reason)',
        words: ['day:homework', 'work:difficult', 'day:friend'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'full',
        ko: '벌써 배불러서 더 못 먹어요.',
        en: 'I’m already full, so I can’t eat any more.',
        answer: '배불러서',
        dict: '배부르다',
        pos: 'adjective',
        meaning: '“so / because” (a reason)',
        words: ['past:already', 'cafe:full', 'cafe:more', 'day:eat'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'sofa',
        ko: '소파에 누워서 텔레비전을 봤어요.',
        en: 'I lay down on the sofa and watched TV.',
        answer: '누워서',
        dict: '눕다',
        meaning: '“and then” (you lie down, then do the next thing lying there)',
        words: ['health:liedown', 'day:watch', 'past:saw'],
        contrast: ['myeon', 'jiman'],
      },
    ],
  },

  {
    id: 'myeon',
    order: 4,
    level: 2,
    emoji: '🤔',
    form: 'myeon',
    title: { ko: '-(으)면', en: 'if / when' },
    meaning: '“If”, or “when / whenever”: the first part is the condition for the second.',
    how: 'After a vowel or ㄹ, add **면**; after any other consonant, add **으면**: 가다 → **가면**, 살다 → **살면**, 먹다 → **먹으면**. Irregular: 듣다 → **들으면** (ㄷ → ㄹ), 춥다 → **추우면** (ㅂ → 우).',
    note: 'Even about the future, -(으)면 stays the same; only the last verb changes: 내일 날씨가 **좋으면** 공원에 갈 거예요 = If the weather is nice tomorrow, I’ll go to the park. For one particular time in the past (“when I was little”), use -(으)ㄹ 때 instead.',
    examples: [
      { ko: '피곤하면 쉬세요.', en: 'If you’re tired, get some rest.' },
      { ko: '여기서 걸으면 십 분 걸려요.', en: 'It’s ten minutes from here if you walk.' },
    ],
    questions: [
      {
        id: 'rain',
        ko: '내일 비가 오면 집에 있을 거예요.',
        en: 'If it rains tomorrow, I’ll stay home.',
        answer: '오면',
        dict: '오다',
        words: ['day:tomorrow', 'weather:raining', 'day:home', 'day:have'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'time',
        ko: '시간이 있으면 같이 영화 볼까요?',
        en: 'If you have time, shall we watch a movie together?',
        answer: '있으면',
        dict: '있다',
        words: ['numbers:hour', 'day:have', 'day:together', 'day:movie', 'day:watch'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'cash',
        ko: '현금이 없으면 카드도 괜찮아요.',
        en: 'If you don’t have cash, a card is fine too.',
        answer: '없으면',
        dict: '없다',
        words: ['shopping:cash', 'day:nothave', 'shopping:card', 'cafe:okay'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'hot',
        ko: '더우면 물을 많이 마시세요.',
        en: 'If it’s hot, drink lots of water.',
        answer: '더우면',
        dict: '덥다',
        pos: 'adjective',
        words: ['weather:hot', 'cafe:water', 'day:drink'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'song',
        ko: '이 노래를 들으면 기분이 좋아요.',
        en: 'Whenever I hear this song, I feel good.',
        answer: '들으면',
        dict: '듣다',
        words: ['hobbies:song', 'hobbies:listen', 'feelings:mood', 'feelings:good'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'far',
        ko: '멀면 택시를 타세요.',
        en: 'If it’s far, take a taxi.',
        answer: '멀면',
        dict: '멀다',
        pos: 'adjective',
        words: ['directions:far', 'directions:taxi', 'directions:ride'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'medicine',
        ko: '이 약을 먹으면 괜찮을 거예요.',
        en: 'If you take this medicine, you’ll be okay.',
        answer: '먹으면',
        dict: '먹다',
        words: ['day:eat', 'cafe:okay'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'seoul',
        ko: '서울에 살면 지하철을 많이 타요.',
        en: 'If you live in Seoul, you take the subway a lot.',
        answer: '살면',
        dict: '살다',
        words: ['directions:subway', 'directions:ride'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'ask',
        ko: '모르면 선생님한테 물어보세요.',
        en: 'If you don’t know, ask the teacher.',
        answer: '모르면',
        dict: '모르다',
        words: ['past:didntknow', 'people:teacher'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'dizzy',
        ko: '어지러우면 여기 잠깐 앉으세요.',
        en: 'If you feel dizzy, sit here for a moment.',
        answer: '어지러우면',
        dict: '어지럽다',
        pos: 'adjective',
        words: ['health:dizzy', 'directions:here'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'better',
        ko: '감기가 나으면 같이 등산 가요!',
        en: 'When your cold gets better, let’s go hiking together!',
        answer: '나으면',
        dict: '낫다',
        words: ['weather:acold', 'health:getbetter', 'day:together', 'hobbies:hiking'],
        contrast: ['jiman', 'aseo'],
      },
    ],
  },

  {
    id: 'reo',
    order: 5,
    level: 2,
    emoji: '🚶',
    form: 'reo',
    title: { ko: '-(으)러', en: '(go / come) to do' },
    meaning: 'Says why you go or come somewhere: “(go / come) to do …”.',
    how: 'After a vowel or ㄹ, add **러**; after any other consonant, add **으러**: 보다 → **보러**, 놀다 → **놀러**, 먹다 → **먹으러**. Irregular: 듣다 → **들으러** (ㄷ → ㄹ). Then comes 가다 or 오다: 보러 가요, 놀러 오세요.',
    note: 'It only goes before verbs of coming and going, like 가다 and 오다. For other verbs, Korean uses -(으)려고, which comes later. The place can go before or after: 카페에 공부하러 가요 = 공부하러 카페에 가요.',
    examples: [
      { ko: '우리 집에 놀러 오세요!', en: 'Come over to my place to hang out!' },
      { ko: '한국어를 배우러 한국에 왔어요.', en: 'I came to Korea to learn Korean.' },
    ],
    questions: [
      {
        id: 'lunch',
        ko: '같이 점심 먹으러 갈까요?',
        en: 'Shall we go get lunch together?',
        answer: '먹으러',
        dict: '먹다',
        words: ['day:together', 'day:lunch', 'day:eat', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'movie',
        ko: '어제 친구하고 영화 보러 갔어요.',
        en: 'Yesterday I went to see a movie with a friend.',
        answer: '보러',
        dict: '보다',
        words: ['day:yesterday', 'day:friend', 'day:movie', 'day:watch', 'past:went'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'milk',
        ko: '우유 사러 가게에 가요.',
        en: 'I’m going to the shop to buy milk.',
        answer: '사러',
        dict: '사다',
        words: ['cafe:milk', 'shopping:buy', 'shopping:shop', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'read',
        ko: '책을 읽으러 도서관에 가요.',
        en: 'I go to the library to read.',
        answer: '읽으러',
        dict: '읽다',
        words: ['day:book', 'day:read', 'day:library', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'photo',
        ko: '사진을 찍으러 공원에 갔어요.',
        en: 'I went to the park to take pictures.',
        answer: '찍으러',
        dict: '찍다',
        words: ['hobbies:photo', 'hobbies:take', 'past:went'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'play',
        ko: '친구가 집에 놀러 왔어요.',
        en: 'A friend came over to hang out.',
        answer: '놀러',
        dict: '놀다',
        words: ['day:friend', 'day:home', 'hobbies:play', 'past:came'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'class',
        ko: '한국어 수업을 들으러 학교에 가요.',
        en: 'I go to school to take a Korean class.',
        answer: '들으러',
        dict: '듣다',
        words: ['day:korean', 'hobbies:listen', 'day:school', 'day:go'],
        contrast: ['myeon', 'go'],
      },
      {
        id: 'meet',
        ko: '내일 친구를 만나러 카페에 갈 거예요.',
        en: 'Tomorrow I’m going to a café to meet a friend.',
        answer: '만나러',
        dict: '만나다',
        words: ['day:tomorrow', 'day:friend', 'day:meet', 'cafe:cafe', 'hobbies:willgo'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'haircut',
        ko: '오후에 머리 자르러 미용실에 가요.',
        en: 'This afternoon I’m going to the hair salon to get my hair cut.',
        answer: '자르러',
        dict: '자르다',
        words: ['numbers:pm', 'health:head', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'bank',
        ko: '점심시간에 돈 찾으러 은행에 갔어요.',
        en: 'At lunchtime I went to the bank to take out some money.',
        answer: '찾으러',
        dict: '찾다',
        words: ['day:lunch', 'shopping:money', 'directions:find', 'directions:bank', 'past:went'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'sea',
        ko: '아이들이 수영하러 바다에 갔어요.',
        en: 'The kids went to the beach to swim.',
        answer: '수영하러',
        dict: '수영하다',
        words: ['people:child', 'hobbies:swim', 'weather:sea', 'past:went'],
        contrast: ['aseo', 'myeon', 'go'],
      },
    ],
  },

  {
    id: 'su',
    order: 6,
    level: 2,
    emoji: '💪',
    form: 'su',
    title: { ko: '-(으)ㄹ 수 있어요', en: 'can / can’t' },
    meaning: '“Can”: you’re able to, or it’s possible. With **없어요** instead of 있어요, it means “can’t”.',
    how: 'After a vowel, put **ㄹ** under the last syllable and add **수 있어요**; after a consonant, add **을 수 있어요**: 가다 → **갈 수 있어요**, 먹다 → **먹을 수 있어요**. ㄹ stems just add 수 있어요: 만들다 → **만들 수 있어요**. Irregular: 듣다 → **들을 수 있어요**. For “can’t”: 갈 수 **없어요**.',
    note: 'The short way to say “can’t” is **못** + verb: 못 가요 = 갈 수 없어요. With 하다 verbs like 수영하다, 못 goes right before 해요: 수영 못 해요.',
    examples: [
      { ko: '내일 몇 시에 올 수 있어요?', en: 'What time can you come tomorrow?' },
      { ko: '오늘은 너무 바빠서 만날 수 없어요.', en: 'I’m too busy today, so I can’t meet up.' },
    ],
    questions: [
      {
        id: 'swim',
        ko: '동생은 다섯 살이지만 수영할 수 있어요.',
        en: 'My little brother is five, but he can swim.',
        answer: '수영할 수 있어요',
        dict: '수영하다',
        words: ['people:sibling', 'numbers:five', 'numbers:age', 'hobbies:swim'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'kimchi',
        ko: '김치를 만들 수 있어요?',
        en: 'Can you make kimchi?',
        answer: '만들 수 있어요',
        dict: '만들다',
        words: ['cafe:kimchi', 'past:made'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'read',
        ko: '한국어를 읽을 수 있어요?',
        en: 'Can you read Korean?',
        answer: '읽을 수 있어요',
        dict: '읽다',
        words: ['day:korean', 'day:read'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'sing',
        ko: '한국 노래도 부를 수 있어요.',
        en: 'I can sing Korean songs too.',
        answer: '부를 수 있어요',
        dict: '부르다',
        words: ['hobbies:song', 'hobbies:sing'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'bike',
        ko: '자전거를 탈 수 있어요?',
        en: 'Can you ride a bike?',
        answer: '탈 수 있어요',
        dict: '타다',
        words: ['hobbies:bike', 'directions:ride'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'spicy',
        ko: '너무 매워서 먹을 수 없어요.',
        en: 'It’s too spicy. I can’t eat it.',
        answer: '먹을 수 없어요',
        dict: '먹다',
        form: 'suNot',
        words: ['cafe:spicy', 'day:eat'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'walk',
        ko: '피곤해서 더 걸을 수 없어요.',
        en: 'I’m tired. I can’t walk any further.',
        answer: '걸을 수 없어요',
        dict: '걷다',
        form: 'suNot',
        words: ['feelings:tired', 'cafe:more', 'directions:walk'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'work',
        ko: '회사에서는 음악을 들을 수 없어요.',
        en: 'I can’t listen to music at work.',
        answer: '들을 수 없어요',
        dict: '듣다',
        form: 'suNot',
        words: ['day:company', 'hobbies:music', 'hobbies:listen'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'tomorrow',
        ko: '미안해요, 내일은 갈 수 없어요.',
        en: 'Sorry, I can’t go tomorrow.',
        answer: '갈 수 없어요',
        dict: '가다',
        form: 'suNot',
        words: ['day:tomorrow', 'day:go'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'order',
        ko: '이제 한국어로 주문할 수 있어요!',
        en: 'Now I can order in Korean!',
        answer: '주문할 수 있어요',
        dict: '주문하다',
        words: ['day:korean', 'cafe:order'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'colour',
        ko: '이 가방은 색깔도 고를 수 있어요.',
        en: 'With this bag, you can choose the colour too.',
        answer: '고를 수 있어요',
        dict: '고르다',
        words: ['shopping:bag', 'shopping:colour'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'exam',
        ko: '내일 시험이 있어서 오늘은 놀 수 없어요.',
        en: 'I have an exam tomorrow, so I can’t hang out today.',
        answer: '놀 수 없어요',
        dict: '놀다',
        form: 'suNot',
        words: ['day:tomorrow', 'work:exam', 'day:today', 'hobbies:play'],
        contrast: ['su', 'aya'],
      },
    ],
  },

  {
    id: 'aya',
    order: 7,
    level: 2,
    emoji: '❗',
    form: 'aya',
    title: { ko: '-아/어야 해요', en: 'have to / must' },
    meaning: '“Have to / must”: something you need to do.',
    how: 'Take the 아/어 form (the present without 요) and add **야 해요**: 가요 → **가야 해요**, 먹어요 → **먹어야 해요**, 해요 → **해야 해요**, 마셔요 → **마셔야 해요**. Irregular words change just as in the present: 들어요 → **들어야 해요**.',
    note: '**야 돼요** means the same as 야 해요, and both are very common: 가야 돼요 = 가야 해요. For “don’t have to”, Korean says “it’s okay not to”: **안 가도 돼요** = I don’t have to go (more on -아/어도 돼요 later).',
    examples: [
      { ko: '약을 먹어야 해요.', en: 'You have to take your medicine.' },
      { ko: '몇 시까지 가야 돼요?', en: 'What time do I have to be there by?' },
    ],
    questions: [
      {
        id: 'homework',
        ko: '오늘은 숙제를 해야 해요.',
        en: 'Today I have to do my homework.',
        answer: '해야 해요',
        dict: '하다',
        words: ['day:today', 'day:homework', 'day:do'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'getup',
        ko: '내일 아침 일찍 일어나야 돼요.',
        en: 'I have to get up early tomorrow morning.',
        answer: '일어나야 돼요',
        dict: '일어나다',
        words: ['day:tomorrow', 'day:morning', 'day:early', 'day:getup'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'walk',
        ko: '버스가 없어서 걸어야 해요.',
        en: 'There’s no bus, so I have to walk.',
        answer: '걸어야 해요',
        dict: '걷다',
        words: ['directions:bus', 'day:nothave', 'directions:walk'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'song',
        ko: '이 노래 꼭 들어야 해요!',
        en: 'You have to hear this song!',
        answer: '들어야 해요',
        dict: '듣다',
        words: ['hobbies:song', 'hobbies:listen'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'subway',
        ko: '여기서 지하철을 타야 해요.',
        en: 'You have to take the subway from here.',
        answer: '타야 해요',
        dict: '타다',
        words: ['directions:here', 'directions:subway', 'directions:ride'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'getoff',
        ko: '다음 역에서 내려야 돼요.',
        en: 'We have to get off at the next station.',
        answer: '내려야 돼요',
        dict: '내리다',
        words: ['directions:station', 'directions:getoff'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'book',
        ko: '학교에 책을 가져가야 해요.',
        en: 'I have to take my book to school.',
        answer: '가져가야 해요',
        dict: '가져가다',
        words: ['day:school', 'day:book'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'clean',
        ko: '주말에 집을 청소해야 돼요.',
        en: 'I have to clean the house on the weekend.',
        answer: '청소해야 돼요',
        dict: '청소하다',
        words: ['day:weekend', 'day:home', 'day:clean'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'help',
        ko: '토요일마다 엄마 가게 일을 도와야 해요.',
        en: 'Every Saturday I have to help out at my mom’s shop.',
        answer: '도와야 해요',
        dict: '돕다',
        words: ['numbers:saturday', 'people:mom', 'shopping:shop'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'phone',
        ko: '영화관에서는 핸드폰을 꺼야 돼요.',
        en: 'You have to turn off your phone in the cinema.',
        answer: '꺼야 돼요',
        dict: '끄다',
        words: ['day:movie', 'day:phone'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'wedding',
        ko: '내일 친구 결혼식에서 노래를 불러야 해요.',
        en: 'Tomorrow I have to sing at my friend’s wedding.',
        answer: '불러야 해요',
        dict: '부르다',
        words: ['day:tomorrow', 'day:friend', 'hobbies:song', 'hobbies:sing'],
        contrast: ['su', 'ado'],
      },
    ],
  },

  {
    id: 'nikka',
    order: 8,
    level: 3,
    emoji: '💬',
    form: 'nikka',
    title: { ko: '-(으)니까', en: 'because / since' },
    meaning: '“Because / since”: gives a reason. It’s the one to use before a request or a suggestion (…세요, …(으)ㄹ까요?, let’s …).',
    how: 'After a vowel, add **니까**; after a consonant, add **으니까**: 가다 → **가니까**, 먹다 → **먹으니까**. ㄹ drops before ㄴ: 살다 → **사니까**, 멀다 → **머니까**. Irregular: 듣다 → **들으니까**, 춥다 → **추우니까**. For the past, add **으니까** to the past stem: 갔어요 → **갔으니까**.',
    note: 'Both -아서/어서 and -(으)니까 give reasons, and for plain facts -아서/어서 is the usual choice: 피곤해서 일찍 잤어요 = I was tired, so I went to bed early. But before a request or a suggestion, only -(으)니까 works: **늦었으니까** 택시를 탈까요? = We’re late, so shall we take a taxi? (never 늦어서).',
    examples: [
      { ko: '배고프니까 밥 먹으러 가요!', en: 'I’m hungry, so let’s go eat!' },
      { ko: '시간이 없으니까 빨리 가요.', en: 'There’s no time, so let’s hurry.' },
      { ko: '추우니까 따뜻한 옷을 입으세요.', en: 'It’s cold, so wear something warm.' },
    ],
    questions: [
      {
        id: 'rain',
        ko: '지금 비가 오니까 우산을 가져가세요.',
        en: 'It’s raining now, so take an umbrella.',
        answer: '오니까',
        dict: '오다',
        words: ['day:now', 'weather:raining', 'weather:umbrella'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '와서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 오니까.' }],
      },
      {
        id: 'far',
        ko: '역이 머니까 택시를 탈까요?',
        en: 'The station is far, so shall we take a taxi?',
        answer: '머니까',
        dict: '멀다',
        pos: 'adjective',
        words: ['directions:station', 'directions:far', 'directions:taxi', 'directions:ride'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '멀어서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 머니까.' }],
      },
      {
        id: 'coffee',
        ko: '아까 커피를 마셨으니까 지금은 물 주세요.',
        en: 'I had coffee earlier, so just water for me now, please.',
        answer: '마셨으니까',
        dict: '마시다',
        tense: 'past',
        words: ['past:earlier', 'cafe:coffee', 'past:drank', 'cafe:water', 'cafe:please'],
        contrast: ['myeon'],
        traps: [{ text: '마셔서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 마셨으니까.' }],
      },
      {
        id: 'walked',
        ko: '어제 많이 걸었으니까 오늘은 집에서 쉴까요?',
        en: 'We walked a lot yesterday, so shall we rest at home today?',
        answer: '걸었으니까',
        dict: '걷다',
        tense: 'past',
        words: ['day:yesterday', 'past:walked', 'day:today', 'day:rest'],
        contrast: ['myeon'],
        traps: [{ text: '걸어서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 걸었으니까.' }],
      },
      {
        id: 'busy',
        ko: '오늘은 제가 좀 바쁘니까 내일 만날까요?',
        en: 'I’m a bit busy today, so shall we meet tomorrow?',
        answer: '바쁘니까',
        dict: '바쁘다',
        pos: 'adjective',
        words: ['day:today', 'feelings:busy', 'day:tomorrow', 'day:meet'],
        contrast: ['myeon'],
        traps: [{ text: '바빠서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 바쁘니까.' }],
      },
      {
        id: 'clean',
        ko: '어제 청소했으니까 오늘은 안 해도 돼요.',
        en: 'I cleaned yesterday, so I don’t have to today.',
        answer: '청소했으니까',
        dict: '청소하다',
        tense: 'past',
        words: ['day:yesterday', 'day:clean', 'day:today', 'day:do'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'live',
        ko: '저도 거기 사니까 같이 가요!',
        en: 'I live there too, so let’s go together!',
        answer: '사니까',
        dict: '살다',
        words: ['people:me', 'directions:there', 'day:together', 'day:go'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '살아서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 사니까.' }],
      },
      {
        id: 'cake',
        ko: '이 케이크 정말 맛있으니까 먹어 보세요.',
        en: 'This cake is really good, so try some.',
        answer: '맛있으니까',
        dict: '맛있다',
        pos: 'adjective',
        words: ['cafe:cake', 'cafe:delicious', 'day:eat'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '맛있어서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 맛있으니까.' }],
      },
      {
        id: 'aircon',
        ko: '지금 너무 더우니까 에어컨을 켤까요?',
        en: 'It’s really hot right now, so shall we turn on the air conditioner?',
        answer: '더우니까',
        dict: '덥다',
        pos: 'adjective',
        words: ['day:now', 'weather:hot', 'weather:aircon'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '더워서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 더우니까.' }],
      },
      {
        id: 'dishes',
        ko: '제가 저녁을 만들었으니까 설거지는 오빠가 해요!',
        en: 'I made dinner, so you do the dishes! (to an older brother)',
        answer: '만들었으니까',
        dict: '만들다',
        tense: 'past',
        words: ['day:evening', 'past:made', 'day:dishes', 'people:oppa'],
        contrast: ['myeon'],
        traps: [{ text: '만들어서', why: '-아서/어서 can’t give the reason for a request (here 해요! means “do it!”). Use -(으)니까: 만들었으니까.' }],
      },
      {
        id: 'subway',
        ko: '지금은 지하철이 더 빠르니까 지하철을 타세요.',
        en: 'Right now the subway is faster, so take the subway.',
        answer: '빠르니까',
        dict: '빠르다',
        pos: 'adjective',
        words: ['day:now', 'directions:subway', 'travel:fast', 'directions:ride'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '빨라서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 빠르니까.' }],
      },
    ],
  },

  {
    id: 'ttae',
    order: 9,
    level: 3,
    emoji: '⏰',
    form: 'ttae',
    title: { ko: '-(으)ㄹ 때', en: 'when' },
    meaning: '“When …”: the time something happens.',
    how: 'After a vowel, put **ㄹ** under the last syllable and add **때**; after a consonant, add **을 때**: 가다 → **갈 때**, 먹다 → **먹을 때**. ㄹ stems just add 때: 살다 → **살 때**. Irregular: 듣다 → **들을 때**, 춥다 → **추울 때**. Adjectives work the same way. For the past, add **을 때** to the past stem: 갔어요 → **갔을 때**.',
    note: 'With 때 it’s always the (으)ㄹ form, even for adjectives: 피곤**할** 때, never 피곤한 때. Nouns take 때 directly: 방학 때 = in the school holidays, 생일 때 = on your birthday.',
    examples: [
      { ko: '한국에 갔을 때 친구를 많이 만났어요.', en: 'When I went to Korea, I met lots of friends.' },
      { ko: '방학 때 뭐 할 거예요?', en: 'What are you going to do in the school holidays?' },
      { ko: '피곤할 때는 일찍 자요.', en: 'When I’m tired, I go to bed early.' },
    ],
    questions: [
      {
        id: 'shower',
        ko: '샤워할 때 노래를 불러요.',
        en: 'I sing when I take a shower.',
        answer: '샤워할 때',
        dict: '샤워하다',
        words: ['day:shower', 'hobbies:song', 'hobbies:sing'],
        contrast: ['gijeone', 'hue'],
      },
      {
        id: 'walk',
        ko: '걸을 때 음악을 들어요.',
        en: 'I listen to music when I walk.',
        answer: '걸을 때',
        dict: '걷다',
        words: ['directions:walk', 'hobbies:music', 'hobbies:listen'],
        contrast: ['gijeone', 'hue'],
      },
      {
        id: 'play',
        ko: '친구하고 놀 때 제일 행복해요.',
        en: 'I’m happiest when I’m hanging out with friends.',
        answer: '놀 때',
        dict: '놀다',
        words: ['day:friend', 'hobbies:play', 'feelings:happy'],
        contrast: ['gijeone', 'hue'],
      },
      {
        id: 'met',
        ko: '처음 만났을 때 정말 떨렸어요.',
        en: 'When we first met, I was really nervous.',
        answer: '만났을 때',
        dict: '만나다',
        tense: 'past',
        words: ['past:met', 'feelings:nervous'],
        contrast: ['gijeone', 'hue'],
        traps: [{ text: '만난 때', why: 'With 때, always use the (으)ㄹ form. For something in the past, add 을 때 to the past stem: 만났을 때.' }],
      },
      {
        id: 'bored',
        ko: '심심할 때 뭐 해요?',
        en: 'What do you do when you’re bored?',
        answer: '심심할 때',
        dict: '심심하다',
        pos: 'adjective',
        words: ['feelings:bored', 'day:what', 'day:do'],
        contrast: ['jiman'],
        traps: [{ text: '심심한 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 심심할 때.' }],
      },
      {
        id: 'cold',
        ko: '추울 때 뜨거운 차를 마셔요.',
        en: 'When it’s cold, I drink hot tea.',
        answer: '추울 때',
        dict: '춥다',
        pos: 'adjective',
        words: ['weather:cold', 'cafe:hot', 'cafe:tea', 'day:drink'],
        contrast: ['jiman'],
        traps: [{ text: '추운 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 추울 때.' }],
      },
      {
        id: 'sad',
        ko: '슬플 때는 울어도 돼요.',
        en: 'It’s okay to cry when you’re sad.',
        answer: '슬플 때',
        dict: '슬프다',
        pos: 'adjective',
        words: ['feelings:sad', 'feelings:cry'],
        contrast: ['jiman'],
        traps: [{ text: '슬픈 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 슬플 때.' }],
      },
      {
        id: 'little',
        ko: '어렸을 때 김치를 안 좋아했어요.',
        en: 'When I was little, I didn’t like kimchi.',
        answer: '어렸을 때',
        dict: '어리다',
        pos: 'adjective',
        tense: 'past',
        words: ['cafe:kimchi', 'feelings:like'],
        contrast: ['jiman', 'nikka'],
        traps: [{ text: '어린 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 어릴 때 or 어렸을 때 (both mean “when I was little”).' }],
      },
      {
        id: 'lonely',
        ko: '외로울 때 가족한테 전화해요.',
        en: 'When I’m lonely, I call my family.',
        answer: '외로울 때',
        dict: '외롭다',
        pos: 'adjective',
        words: ['feelings:lonely', 'people:family'],
        contrast: ['jiman'],
        traps: [{ text: '외로운 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 외로울 때.' }],
      },
      {
        id: 'heard',
        ko: '그 노래를 들었을 때 엄마 생각이 났어요.',
        en: 'When I heard that song, I thought of my mom.',
        answer: '들었을 때',
        dict: '듣다',
        tense: 'past',
        words: ['hobbies:song', 'past:listened', 'people:mom'],
        contrast: ['gijeone', 'jiman'],
        traps: [{ text: '들은 때', why: 'With 때, always use the (으)ㄹ form. For something in the past, add 을 때 to the past stem: 들었을 때.' }],
      },
      {
        id: 'grandma',
        ko: '할머니하고 같이 살 때 매일 아침 산책했어요.',
        en: 'When I lived with my grandma, we went for a walk every morning.',
        answer: '살 때',
        dict: '살다',
        words: ['people:grandma', 'people:live', 'day:morning', 'hobbies:stroll'],
        contrast: ['gijeone', 'hue'],
      },
    ],
  },

  {
    id: 'gijeone',
    order: 10,
    level: 3,
    emoji: '⏪',
    form: 'gijeone',
    title: { ko: '-기 전에', en: 'before' },
    meaning: '“Before …”: what you do before something else.',
    how: 'Put **기 전에** straight onto the stem: 가다 → **가기 전에**, 먹다 → **먹기 전에**, 자다 → **자기 전에**. No 아/어, no 으, and irregular words don’t change: 듣다 → **듣기 전에**.',
    note: 'It never takes the past; the last verb shows the tense: 친구를 **만나기 전에** 선물을 샀어요 = I bought a present before I met my friend. Nouns take 전에 directly: 수업 전에 = before class. After an amount of time, 전에 means “ago”: 한 시간 전에 = an hour ago.',
    examples: [
      { ko: '자기 전에 책을 읽어요.', en: 'I read before bed.' },
      { ko: '수업 전에 커피를 마셔요.', en: 'I have a coffee before class.' },
    ],
    questions: [
      {
        id: 'wash',
        ko: '밥을 먹기 전에 손을 씻어요.',
        en: 'I wash my hands before I eat.',
        answer: '먹기 전에',
        dict: '먹다',
        words: ['day:meal', 'day:eat', 'day:wash'],
        contrast: ['hue'],
      },
      {
        id: 'sleep',
        ko: '어젯밤 자기 전에 샤워했어요.',
        en: 'Last night I took a shower before bed.',
        answer: '자기 전에',
        dict: '자다',
        words: ['past:lastnight', 'day:sleep', 'day:shower'],
        contrast: ['hue'],
      },
      {
        id: 'movie',
        ko: '영화 보기 전에 밥 먹을까요?',
        en: 'Shall we eat before the movie?',
        answer: '보기 전에',
        dict: '보다',
        words: ['day:movie', 'day:watch', 'day:meal', 'day:eat'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'friend',
        ko: '친구가 오기 전에 청소해야 해요.',
        en: 'I have to clean before my friend comes.',
        answer: '오기 전에',
        dict: '오다',
        words: ['day:friend', 'day:come', 'day:clean'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'korea',
        ko: '한국에 가기 전에 한국어를 배우고 싶어요.',
        en: 'I want to learn Korean before I go to Korea.',
        answer: '가기 전에',
        dict: '가다',
        words: ['day:go', 'day:korean', 'hobbies:wanttolearn'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'tryon',
        ko: '사기 전에 입어 보세요.',
        en: 'Try it on before you buy it.',
        answer: '사기 전에',
        dict: '사다',
        words: ['shopping:buy', 'shopping:wear'],
        contrast: ['hue'],
      },
      {
        id: 'exercise',
        ko: '운동하기 전에 물을 마셔요.',
        en: 'I drink some water before I work out.',
        answer: '운동하기 전에',
        dict: '운동하다',
        words: ['day:exercise', 'cafe:water', 'day:drink'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'cross',
        ko: '길을 건너기 전에 왼쪽을 보세요.',
        en: 'Look left before you cross the road.',
        answer: '건너기 전에',
        dict: '건너다',
        words: ['directions:road', 'directions:cross', 'directions:left', 'day:watch'],
        contrast: ['hue'],
      },
      {
        id: 'play',
        ko: '놀기 전에 숙제부터 하세요.',
        en: 'Do your homework before you play.',
        answer: '놀기 전에',
        dict: '놀다',
        words: ['hobbies:play', 'day:homework', 'day:do'],
        contrast: ['hue'],
      },
      {
        id: 'married',
        ko: '결혼하기 전에 서울에서 살았어요.',
        en: 'I lived in Seoul before I got married.',
        answer: '결혼하기 전에',
        dict: '결혼하다',
        words: ['people:married', 'people:live'],
        contrast: ['hue'],
      },
      {
        id: 'depart',
        ko: '출발하기 전에 화장실에 다녀오세요.',
        en: 'Go to the restroom before we set off.',
        answer: '출발하기 전에',
        dict: '출발하다',
        words: ['travel:depart', 'directions:toilet'],
        contrast: ['hue'],
      },
    ],
  },

  {
    id: 'hue',
    order: 11,
    level: 3,
    emoji: '⏩',
    form: 'hue',
    title: { ko: '-(으)ㄴ 후에', en: 'after' },
    meaning: '“After …”: first one thing, then the other.',
    how: 'After a vowel, put **ㄴ** under the last syllable; after a consonant, add **은**; then add **후에**: 가다 → **간 후에**, 먹다 → **먹은 후에**. ㄹ stems drop the ㄹ: 살다 → **산 후에**, 만들다 → **만든 후에**. Irregular: 듣다 → **들은 후에**.',
    note: '**-(으)ㄴ 다음에** means the same: 먹은 다음에 = 먹은 후에. Nouns take 후에 directly: 수업 후에 = after class. Only the last verb shows the tense.',
    examples: [
      { ko: '수업 후에 뭐 해요?', en: 'What are you doing after class?' },
      { ko: '숙제를 한 다음에 게임을 해요.', en: 'I play games after I do my homework.' },
    ],
    questions: [
      {
        id: 'movie',
        ko: '영화를 본 후에 카페에 갔어요.',
        en: 'After the movie, we went to a café.',
        answer: '본 후에',
        dict: '보다',
        words: ['day:movie', 'day:watch', 'cafe:cafe', 'past:went'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'cake',
        ko: '케이크를 만든 후에 사진을 찍었어요.',
        en: 'After I made the cake, I took a photo of it.',
        answer: '만든 후에',
        dict: '만들다',
        words: ['cafe:cake', 'past:made', 'hobbies:photo', 'hobbies:take'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'play',
        ko: '친구하고 논 후에 집에 왔어요.',
        en: 'After hanging out with a friend, I came home.',
        answer: '논 후에',
        dict: '놀다',
        words: ['day:friend', 'hobbies:play', 'day:home', 'past:came'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'class',
        ko: '수업을 들은 후에 도서관에 가요.',
        en: 'After class, I go to the library.',
        answer: '들은 후에',
        dict: '듣다',
        words: ['hobbies:listen', 'day:library', 'day:go'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'walk',
        ko: '많이 걸은 후에 좀 쉬었어요.',
        en: 'After walking a lot, I rested for a bit.',
        answer: '걸은 후에',
        dict: '걷다',
        words: ['directions:walk', 'past:rested'],
        contrast: ['gijeone'],
      },
      {
        id: 'exercise',
        ko: '운동한 후에 샤워해요.',
        en: 'I shower after I work out.',
        answer: '운동한 후에',
        dict: '운동하다',
        words: ['day:exercise', 'day:shower'],
        contrast: ['gijeone'],
      },
      {
        id: 'lunch',
        ko: '점심을 먹은 후에 커피를 마셔요.',
        en: 'I have coffee after lunch.',
        answer: '먹은 후에',
        dict: '먹다',
        words: ['day:lunch', 'day:eat', 'cafe:coffee', 'day:drink'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'getoff',
        ko: '버스에서 내린 후에 오른쪽으로 가세요.',
        en: 'After you get off the bus, go right.',
        answer: '내린 후에',
        dict: '내리다',
        words: ['directions:bus', 'directions:getoff', 'directions:right', 'day:go'],
        contrast: ['gijeone'],
      },
      {
        id: 'ramen',
        ko: '라면에 물을 부은 후에 삼 분 기다리세요.',
        en: 'After you pour the water into the ramen, wait three minutes.',
        answer: '부은 후에',
        dict: '붓다',
        words: ['cafe:water', 'numbers:sam', 'numbers:minute', 'day:wait'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'kiosk',
        ko: '메뉴를 고른 후에 카드로 계산하세요.',
        en: 'After you choose from the menu, pay by card.',
        answer: '고른 후에',
        dict: '고르다',
        words: ['cafe:menu', 'shopping:card', 'cafe:bill'],
        contrast: ['gijeone'],
      },
      {
        id: 'arrive',
        ko: '집에 도착한 후에 전화할게요.',
        en: 'I’ll call you after I get home.',
        answer: '도착한 후에',
        dict: '도착하다',
        words: ['day:home', 'directions:arrive'],
        contrast: ['gijeone'],
      },
    ],
  },

  {
    id: 'ado',
    order: 12,
    level: 3,
    emoji: '👌',
    form: 'ado',
    title: { ko: '-아/어도 돼요', en: 'may / it’s okay to' },
    meaning: '“May / it’s okay to”: asks for or gives permission. With ? it asks: **먹어도 돼요?** = May I eat it?',
    how: 'Take the 아/어 form (the present without 요) and add **도 돼요**: 가요 → **가도 돼요**, 먹어요 → **먹어도 돼요**, 해요 → **해도 돼요**, 앉아요 → **앉아도 돼요**.',
    note: 'To say no: **아니요, 안 돼요.** You can also say **괜찮아요** instead of 돼요: 먹어도 괜찮아요? With 안 in front, it means “don’t have to”: 내일은 **안 와도 돼요** = You don’t have to come tomorrow.',
    examples: [
      { ko: '창문 좀 열어도 돼요? — 네, 열어도 돼요.', en: 'May I open the window? — Yes, go ahead.' },
      { ko: '이거 먹어 봐도 돼요?', en: 'May I try this?' },
    ],
    questions: [
      {
        id: 'seat',
        ko: '이 자리에 앉아도 괜찮아요?',
        en: 'Is it okay if I sit in this seat?',
        answer: '앉아도 괜찮아요',
        dict: '앉다',
        words: ['cafe:seat', 'cafe:okay'],
        contrast: ['aya'],
        traps: [
          { text: '앉어도 괜찮아요', why: '앉다 → 앉 + 아요: the last vowel is ㅏ, so it takes 아. So: 앉아도 괜찮아요.' },
          { text: '앉도 괜찮아요', why: 'After a consonant, the 아/어 can’t be left out: 앉아도 괜찮아요.' },
        ],
      },
      {
        id: 'photo',
        ko: '여기서 사진을 찍어도 돼요?',
        en: 'May I take pictures here?',
        answer: '찍어도 돼요',
        dict: '찍다',
        words: ['directions:here', 'hobbies:photo', 'hobbies:take'],
        contrast: ['aya'],
      },
      {
        id: 'eat',
        ko: '네, 다 먹어도 돼요.',
        en: 'Yes, you can eat all of it.',
        answer: '먹어도 돼요',
        dict: '먹다',
        words: ['cafe:yes', 'day:eat'],
        contrast: ['aya'],
      },
      {
        id: 'music',
        ko: '공부할 때 음악을 들어도 돼요?',
        en: 'Is it okay to listen to music while I study?',
        answer: '들어도 돼요',
        dict: '듣다',
        words: ['day:study', 'hobbies:music', 'hobbies:listen'],
        contrast: ['aya'],
        traps: [{ text: '들어도 해요', why: '“May” is -아/어도 돼요, not 해요 (해요 goes with -아/어야: “have to”). So: 들어도 돼요.' }],
      },
      {
        id: 'late',
        ko: '내일 좀 늦게 와도 돼요?',
        en: 'Is it okay if I come a bit late tomorrow?',
        answer: '와도 돼요',
        dict: '오다',
        words: ['day:tomorrow', 'day:come'],
        contrast: ['aya'],
      },
      {
        id: 'card',
        ko: '카드로 계산해도 돼요?',
        en: 'Can I pay by card?',
        answer: '계산해도 돼요',
        dict: '계산하다',
        words: ['shopping:card', 'cafe:bill'],
        contrast: ['aya'],
        traps: [{ text: '계산해도 되요', why: '되요 is a common misspelling: 되 + 어요 → 돼요. So: 계산해도 돼요.' }],
      },
      {
        id: 'go',
        ko: '네, 지금 가도 돼요.',
        en: 'Yes, you can go now.',
        answer: '가도 돼요',
        dict: '가다',
        words: ['cafe:yes', 'day:now', 'day:go'],
        contrast: ['aya'],
        traps: [{ text: '가도 해요', why: '“May” is -아/어도 돼요, not 해요 (해요 goes with -아/어야: “have to”). So: 가도 돼요.' }],
      },
      {
        id: 'play',
        ko: '엄마, 친구하고 놀아도 돼요?',
        en: 'Mom, can I play with my friend?',
        answer: '놀아도 돼요',
        dict: '놀다',
        words: ['people:mom', 'day:friend', 'hobbies:play'],
        contrast: ['aya'],
      },
      {
        id: 'liedown',
        ko: '머리가 좀 아파요. 잠깐 누워도 돼요?',
        en: 'I have a bit of a headache. May I lie down for a moment?',
        answer: '누워도 돼요',
        dict: '눕다',
        words: ['health:head', 'feelings:hurts', 'health:liedown'],
        contrast: ['aya'],
        traps: [{ text: '누워도 되요', why: '되요 is a common misspelling: 되 + 어요 → 돼요. So: 누워도 돼요.' }],
      },
      {
        id: 'cream',
        ko: '손이 너무 건조해요. 이 크림 좀 발라도 돼요?',
        en: 'My hands are so dry. May I put on some of this cream?',
        answer: '발라도 돼요',
        dict: '바르다',
        words: ['health:hand', 'weather:dry', 'health:apply'],
        contrast: ['aya'],
        traps: [{ text: '발라도 해요', why: '“May” is -아/어도 돼요, not 해요 (해요 goes with -아/어야: “have to”). So: 발라도 돼요.' }],
      },
      {
        id: 'light',
        ko: '불 좀 꺼도 돼요? 피곤해서 자고 싶어요.',
        en: 'May I turn off the light? I’m tired and want to sleep.',
        answer: '꺼도 돼요',
        dict: '끄다',
        words: ['feelings:tired', 'day:sleep'],
        contrast: ['aya'],
        traps: [{ text: '끄도 돼요', why: '끄다 + 어 → 꺼: the ㅡ drops, but the 어 stays. So: 꺼도 돼요.' }],
      },
    ],
  },

  {
    id: 'seyo',
    order: 13,
    level: 2,
    emoji: '🙏',
    form: 'seyo',
    title: { ko: '-(으)세요', en: 'please / polite asking' },
    meaning: 'Two uses. A polite request, “please …”: **들어오세요** = Please come in. Or the polite present, when you ask the person you’re talking to, or talk about someone you respect: **어디 가세요?** = Where are you going? 할머니는 부산에 **사세요** = My grandma lives in Busan.',
    how: 'After a vowel, add **세요**; after a consonant, add **으세요**: 가다 → **가세요**, 앉다 → **앉으세요**. ㄹ drops before ㅅ: 살다 → **사세요**, 만들다 → **만드세요**. Irregular: 듣다 → **들으세요** (ㄷ → ㄹ), 돕다 → **도우세요** (ㅂ → 우).',
    note: 'Some verbs have their own polite words: 먹다, 마시다 → **드세요**, 자다 → **주무세요**, 있다 (be somewhere) → **계세요**: 맛있게 드세요 = Enjoy your meal, 안녕히 계세요 = Goodbye (to someone who’s staying). Never use -(으)세요 about yourself: 어디 가세요? — 학교에 **가요**. With adjectives, it’s only about people, never things: **바쁘세요?** = Are you busy?, but 이 가방은 **비싸요** (not 비싸세요).',
    examples: [
      { ko: '여기에 이름을 쓰세요.', en: 'Please write your name here.' },
      { ko: '무슨 음악 좋아하세요?', en: 'What kind of music do you like?' },
      { ko: '안녕히 가세요!', en: 'Goodbye! (to someone who’s leaving)' },
    ],
    questions: [
      {
        id: 'seat',
        ko: '할머니, 여기 앉으세요.',
        en: 'Grandma, please sit here.',
        answer: '앉으세요',
        dict: '앉다',
        meaning: '“please …” (a polite request)',
        words: ['people:grandma', 'directions:here'],
        contrast: ['lgeyo', 'su', 'aya'],
      },
      {
        id: 'bank',
        ko: '은행 앞에서 기다리세요. 제가 갈게요.',
        en: 'Please wait in front of the bank. I’ll come to you.',
        answer: '기다리세요',
        dict: '기다리다',
        meaning: '“please …” (a polite request)',
        words: ['directions:bank', 'directions:front', 'day:wait', 'day:go'],
        contrast: ['lgeyo', 'su'],
      },
      {
        id: 'rest',
        ko: '오늘은 집에서 푹 쉬세요.',
        en: 'Please get a good rest at home today.',
        answer: '쉬세요',
        dict: '쉬다',
        meaning: '“please …” (a polite request)',
        words: ['day:today', 'day:home', 'day:rest'],
        contrast: ['lgeyo', 'su'],
      },
      {
        id: 'walk',
        ko: '매일 삼십 분 걸으세요.',
        en: 'Please walk for thirty minutes every day.',
        answer: '걸으세요',
        dict: '걷다',
        meaning: '“please …” (a polite request)',
        words: ['day:everyday', 'numbers:sam', 'numbers:sip', 'numbers:minute', 'directions:walk'],
        contrast: ['lgeyo', 'su'],
      },
      {
        id: 'turn',
        ko: '사거리에서 오른쪽으로 도세요.',
        en: 'Please turn right at the crossroads.',
        answer: '도세요',
        dict: '돌다',
        meaning: '“please …” (a polite request)',
        words: ['directions:crossroads', 'directions:right', 'directions:turn'],
        contrast: ['lgeyo', 'su'],
      },
      {
        id: 'live',
        ko: '지금 어디에 사세요?',
        en: 'Where do you live now?',
        answer: '사세요',
        dict: '살다',
        meaning: 'a polite question about the person you’re talking to',
        words: ['day:now', 'directions:where', 'people:live'],
        contrast: ['aya', 'su', 'lgeyo'],
      },
      {
        id: 'weekend',
        ko: '주말에 보통 뭐 하세요?',
        en: 'What do you usually do at the weekend?',
        answer: '하세요',
        dict: '하다',
        meaning: 'a polite question about the person you’re talking to',
        words: ['day:weekend', 'day:usually', 'day:what', 'day:do'],
        contrast: ['aya', 'su', 'lgeyo'],
      },
      {
        id: 'cold',
        ko: '추우세요? 따뜻한 차 드세요.',
        en: 'Are you cold? Have some warm tea.',
        answer: '추우세요',
        dict: '춥다',
        pos: 'adjective',
        meaning: 'a polite question about the person you’re talking to',
        words: ['weather:cold', 'weather:warm', 'cafe:tea'],
        contrast: ['aya'],
      },
      {
        id: 'milk',
        ko: '여기 우유 파세요?',
        en: 'Do you sell milk here?',
        answer: '파세요',
        dict: '팔다',
        meaning: 'a polite question about the person you’re talking to',
        words: ['directions:here', 'cafe:milk', 'shopping:sell'],
        contrast: ['aya', 'su', 'lgeyo'],
      },
      {
        id: 'classical',
        ko: '아버지는 클래식 음악만 들으세요.',
        en: 'My father only listens to classical music.',
        answer: '들으세요',
        dict: '듣다',
        meaning: 'the polite present, about someone you respect',
        words: ['people:father', 'hobbies:music', 'hobbies:listen'],
        contrast: ['lgeyo', 'su', 'aya'],
      },
      {
        id: 'healthy',
        ko: '우리 할머니는 아직도 정말 건강하세요.',
        en: 'My grandma is still really healthy.',
        answer: '건강하세요',
        dict: '건강하다',
        pos: 'adjective',
        meaning: 'the polite present, about someone you respect',
        words: ['people:we', 'people:grandma', 'health:healthy'],
        contrast: ['aya'],
      },
    ],
  },

  {
    id: 'goIt',
    order: 14,
    level: 2,
    emoji: '⏳',
    form: 'goIt',
    title: { ko: '-고 있어요', en: 'am …-ing' },
    meaning: 'Something going on right now, “am / is / are …-ing”: 비가 **오고 있어요** = It’s raining. It can also be something going on these days: 요즘 매일 **운동하고 있어요** = I’m working out every day these days.',
    how: 'Put **고 있어요** straight onto the stem, just like -고: 가다 → **가고 있어요**, 먹다 → **먹고 있어요**, 공부하다 → **공부하고 있어요**. No 아/어, and irregular words don’t change: 듣다 → **듣고 있어요**.',
    note: 'The plain present can mean “am …-ing” too: 지금 뭐 해요? — 밥 먹어요. -고 있어요 stresses that it’s happening right now. For someone you respect, it’s **-고 계세요**: 선생님은 지금 전화하**고 계세요**.',
    examples: [
      { ko: '누구하고 이야기하고 있어요?', en: 'Who are you talking to?' },
      { ko: '요즘 무슨 책 읽고 있어요?', en: 'What book are you reading these days?' },
    ],
    questions: [
      {
        id: 'what',
        ko: '지금 뭐 하고 있어요?',
        en: 'What are you doing right now?',
        answer: '하고 있어요',
        dict: '하다',
        words: ['day:now', 'day:what', 'day:do'],
        contrast: ['su', 'aya', 'lgeyo'],
      },
      {
        id: 'lunch',
        ko: '지금 점심 먹고 있어요.',
        en: 'I’m having lunch right now.',
        answer: '먹고 있어요',
        dict: '먹다',
        words: ['day:now', 'day:lunch', 'day:eat'],
        contrast: ['lgeyo', 'su', 'aya'],
      },
      {
        id: 'wait',
        ko: '역 앞에서 친구를 기다리고 있어요.',
        en: 'I’m waiting for a friend in front of the station.',
        answer: '기다리고 있어요',
        dict: '기다리다',
        words: ['directions:station', 'directions:front', 'day:friend', 'day:wait'],
        contrast: ['lgeyo', 'su', 'aya'],
      },
      {
        id: 'music',
        ko: '지금 버스에서 음악을 듣고 있어요.',
        en: 'I’m listening to music on the bus right now.',
        answer: '듣고 있어요',
        dict: '듣다',
        words: ['day:now', 'directions:bus', 'hobbies:music', 'hobbies:listen'],
        contrast: ['lgeyo', 'su', 'aya'],
      },
      {
        id: 'sleep',
        ko: '쉿! 동생이 자고 있어요.',
        en: 'Shh! My little brother is sleeping.',
        answer: '자고 있어요',
        dict: '자다',
        words: ['people:sibling', 'day:sleep'],
        contrast: ['su', 'aya', 'lgeyo'],
      },
      {
        id: 'play',
        ko: '아이들이 공원에서 놀고 있어요.',
        en: 'The kids are playing in the park.',
        answer: '놀고 있어요',
        dict: '놀다',
        words: ['people:child', 'hobbies:play'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'korean',
        ko: '요즘 한국어를 배우고 있어요.',
        en: 'I’m learning Korean these days.',
        answer: '배우고 있어요',
        dict: '배우다',
        meaning: '“am …-ing” (going on these days)',
        words: ['day:korean', 'hobbies:learn'],
        contrast: ['bwasseoyo', 'su', 'aya'],
      },
      {
        id: 'work',
        ko: '요즘 카페에서 일하고 있어요.',
        en: 'I’m working at a café these days.',
        answer: '일하고 있어요',
        dict: '일하다',
        meaning: '“am …-ing” (going on these days)',
        words: ['cafe:cafe', 'day:work'],
        contrast: ['bwasseoyo', 'su', 'aya'],
      },
      {
        id: 'river',
        ko: '지금 한강에서 걷고 있어요.',
        en: 'I’m walking by the Han River right now.',
        answer: '걷고 있어요',
        dict: '걷다',
        words: ['day:now', 'directions:walk'],
        contrast: ['su', 'aya', 'lgeyo'],
      },
      {
        id: 'baby',
        ko: '아기가 배고파서 울고 있어요.',
        en: 'The baby is crying because it’s hungry.',
        answer: '울고 있어요',
        dict: '울다',
        words: ['cafe:hungry', 'feelings:cry'],
        contrast: ['su', 'aya', 'lgeyo'],
      },
      {
        id: 'words',
        ko: '요즘 매일 단어를 외우고 있어요.',
        en: 'These days I’m memorising words every day.',
        answer: '외우고 있어요',
        dict: '외우다',
        meaning: '“am …-ing” (going on these days)',
        words: ['day:thesedays', 'day:everyday', 'work:word', 'work:memorise'],
        contrast: ['bwasseoyo', 'su', 'aya'],
      },
    ],
  },

  {
    id: 'boda',
    order: 15,
    level: 2,
    emoji: '🧪',
    form: 'boseyo',
    title: { ko: '-아/어 보다', en: 'try …-ing' },
    meaning: 'After the 아/어 form, 보다 (see) means “try”: 이 신발 **신어 보세요** = Try these shoes on. In the past, it’s something you’ve tried, or have ever done: 김치 **먹어 봤어요?** = Have you ever tried kimchi?',
    how: 'Take the 아/어 form (the present without 요) and add **보세요** (please try) or **봤어요** (have tried), with a space: 먹어요 → **먹어 보세요**, 가요 → **가 봤어요**, 해요 → **해 보세요**. Irregular words change just as in the present: 들어요 → **들어 보세요**.',
    note: 'You’ll often hear **한번** (once) with it: 한번 해 보세요 = Give it a go. With 보다 itself, just use 보세요 or 봤어요: 이 영화 **봤어요?** = Have you seen this movie?',
    examples: [
      { ko: '한국에 가 봤어요? — 아니요, 아직 못 가 봤어요.', en: 'Have you ever been to Korea? — No, not yet.' },
      { ko: '이 앱 한번 써 보세요. 정말 좋아요.', en: 'Give this app a try. It’s really good.' },
    ],
    questions: [
      {
        id: 'cake',
        ko: '이 케이크 한번 먹어 보세요.',
        en: 'Try this cake.',
        answer: '먹어 보세요',
        dict: '먹다',
        words: ['cafe:cake', 'day:eat'],
        contrast: ['lgeyo', 'su', 'bwasseoyo'],
      },
      {
        id: 'tshirt',
        ko: '이 티셔츠 한번 입어 보세요.',
        en: 'Try this T-shirt on.',
        answer: '입어 보세요',
        dict: '입다',
        words: ['shopping:tshirt', 'shopping:wear'],
        contrast: ['lgeyo', 'su', 'goIt'],
      },
      {
        id: 'song',
        ko: '이 노래 한번 들어 보세요.',
        en: 'Try listening to this song.',
        answer: '들어 보세요',
        dict: '듣다',
        words: ['hobbies:song', 'hobbies:listen'],
        contrast: ['lgeyo', 'su', 'goIt'],
      },
      {
        id: 'tea',
        ko: '이 녹차도 마셔 보세요.',
        en: 'Try this green tea too.',
        answer: '마셔 보세요',
        dict: '마시다',
        words: ['cafe:greentea', 'day:drink'],
        contrast: ['lgeyo', 'su', 'bwasseoyo'],
      },
      {
        id: 'photo',
        ko: '여기서 사진을 찍어 보세요.',
        en: 'Try taking a photo from here.',
        answer: '찍어 보세요',
        dict: '찍다',
        words: ['directions:here', 'hobbies:photo', 'hobbies:take'],
        contrast: ['lgeyo', 'su', 'goIt'],
      },
      {
        id: 'kimchi',
        ko: '김치를 만들어 봤어요?',
        en: 'Have you ever made kimchi?',
        answer: '만들어 봤어요',
        dict: '만들다',
        form: 'bwasseoyo',
        words: ['cafe:kimchi', 'past:made'],
        contrast: ['su', 'boseyo', 'aya'],
      },
      {
        id: 'jeju',
        ko: '네, 제주도에 두 번 가 봤어요.',
        en: 'Yes, I’ve been to Jeju Island twice.',
        answer: '가 봤어요',
        dict: '가다',
        form: 'bwasseoyo',
        words: ['cafe:yes', 'cafe:two', 'day:go'],
        contrast: ['su', 'lgeyo', 'aya'],
      },
      {
        id: 'karaoke',
        ko: '노래방에서 한국 노래 불러 봤어요?',
        en: 'Have you ever sung a Korean song at karaoke?',
        answer: '불러 봤어요',
        dict: '부르다',
        form: 'bwasseoyo',
        words: ['hobbies:song', 'hobbies:sing'],
        contrast: ['su', 'boseyo', 'goIt'],
      },
      {
        id: 'subway',
        ko: '서울에서 지하철을 타 봤어요?',
        en: 'Have you ever taken the subway in Seoul?',
        answer: '타 봤어요',
        dict: '타다',
        form: 'bwasseoyo',
        words: ['directions:subway', 'directions:ride'],
        contrast: ['su', 'boseyo', 'goIt'],
      },
      {
        id: 'street',
        ko: '이 길로 한번 걸어 보세요. 정말 예뻐요.',
        en: 'Try walking along this street. It’s really pretty.',
        answer: '걸어 보세요',
        dict: '걷다',
        words: ['directions:road', 'directions:walk', 'shopping:pretty'],
        contrast: ['lgeyo', 'su', 'goIt'],
      },
      {
        id: 'abroad',
        ko: '다른 나라에서 살아 봤어요?',
        en: 'Have you ever lived in another country?',
        answer: '살아 봤어요',
        dict: '살다',
        form: 'bwasseoyo',
        words: ['shopping:other', 'people:country', 'people:live'],
        contrast: ['su', 'boseyo', 'goIt'],
      },
      {
        id: 'bread',
        ko: '집에서 빵을 구워 봤어요?',
        en: 'Have you ever baked bread at home?',
        answer: '구워 봤어요',
        dict: '굽다',
        form: 'bwasseoyo',
        words: ['day:home', 'cafe:bread'],
        contrast: ['su', 'boseyo', 'aya'],
      },
    ],
  },

  {
    id: 'lgeyo',
    order: 16,
    level: 2,
    emoji: '🤝',
    form: 'lgeyo',
    title: { ko: '-(으)ㄹ게요', en: 'I’ll …' },
    meaning: '“I’ll …”: a promise or a decision you tell someone, often in answer to them: 내일 **전화할게요** = I’ll call you tomorrow. 네, **기다릴게요** = Okay, I’ll wait.',
    how: 'After a vowel, put **ㄹ** under the last syllable and add **게요**; after a consonant, add **을게요**: 가다 → **갈게요**, 먹다 → **먹을게요**. ㄹ stems just add 게요: 만들다 → **만들게요**. Irregular: 듣다 → **들을게요** (ㄷ → ㄹ).',
    note: 'It’s only about yourself (“I”, or “we”): never about someone else, and never a question. It sounds like [께요], but it’s spelled **게요**. For a plan you’re just telling someone about, use -(으)ㄹ 거예요 instead: 내일 부산에 **갈 거예요** = I’m going to Busan tomorrow.',
    examples: [
      { ko: '제가 창문 열게요.', en: 'I’ll open the window.' },
      { ko: '알겠어요. 조심할게요!', en: 'Got it. I’ll be careful!' },
    ],
    questions: [
      {
        id: 'clean',
        ko: '청소는 제가 할게요.',
        en: 'I’ll do the cleaning.',
        answer: '할게요',
        dict: '하다',
        words: ['day:clean', 'people:me', 'day:do'],
        contrast: ['seyo', 'goIt', 'aya'],
      },
      {
        id: 'tea',
        ko: '저는 녹차 마실게요.',
        en: 'I’ll have the green tea.',
        answer: '마실게요',
        dict: '마시다',
        words: ['people:me', 'cafe:greentea', 'day:drink'],
        contrast: ['seyo', 'goIt', 'su'],
      },
      {
        id: 'early',
        ko: '내일은 일찍 올게요.',
        en: 'I’ll come early tomorrow.',
        answer: '올게요',
        dict: '오다',
        words: ['day:tomorrow', 'day:early', 'day:come'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'coffee',
        ko: '오늘은 제가 커피 살게요.',
        en: 'I’ll buy the coffee today.',
        answer: '살게요',
        dict: '사다',
        words: ['day:today', 'cafe:coffee', 'shopping:buy'],
        contrast: ['seyo', 'goIt', 'aya'],
      },
      {
        id: 'dinner',
        ko: '오늘 저녁은 제가 만들게요.',
        en: 'I’ll make dinner tonight.',
        answer: '만들게요',
        dict: '만들다',
        words: ['day:today', 'day:evening', 'past:made'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'listen',
        ko: '고마워요! 집에 가서 들을게요.',
        en: 'Thanks! I’ll listen to it when I get home.',
        answer: '들을게요',
        dict: '듣다',
        words: ['day:home', 'day:go', 'hobbies:listen'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'leave',
        ko: '저 먼저 갈게요. 내일 봐요!',
        en: 'I’ll head off first. See you tomorrow!',
        answer: '갈게요',
        dict: '가다',
        words: ['people:me', 'day:tomorrow', 'day:watch'],
        contrast: ['seyo', 'su'],
      },
      {
        id: 'photo',
        ko: '사진은 제가 찍을게요.',
        en: 'I’ll take the photos.',
        answer: '찍을게요',
        dict: '찍다',
        words: ['hobbies:photo', 'people:me', 'hobbies:take'],
        contrast: ['seyo', 'goIt', 'aya'],
      },
      {
        id: 'meat',
        ko: '고기는 제가 구울게요. 맛있게 드세요!',
        en: 'I’ll grill the meat. Enjoy your meal!',
        answer: '구울게요',
        dict: '굽다',
        words: ['people:me', 'health:pleasehave'],
        contrast: ['seyo', 'goIt', 'aya'],
      },
      {
        id: 'cake',
        ko: '자, 이제 생일 케이크를 자를게요!',
        en: 'Okay, now I’ll cut the birthday cake!',
        answer: '자를게요',
        dict: '자르다',
        words: ['numbers:birthday', 'cafe:cake'],
        contrast: ['seyo', 'goIt', 'aya'],
      },
      {
        id: 'taxi',
        ko: '밖에 비가 와요. 택시 부를게요.',
        en: 'It’s raining outside. I’ll call a taxi.',
        answer: '부를게요',
        dict: '부르다',
        words: ['directions:outside', 'weather:raining', 'directions:taxi'],
        contrast: ['seyo', 'goIt', 'aya'],
      },
    ],
  },

  {
    id: 'neunde',
    order: 17,
    level: 3,
    emoji: '🎬',
    form: 'neunde',
    title: { ko: '-는데', en: '…, and / but / so …' },
    meaning: 'Sets the scene for what comes next. Often it’s the background to a question, a request or a suggestion: **배고픈데** 뭐 먹을까요? = I’m hungry — what shall we eat? It can also be a soft “but”: 좀 **비싼데** 맛있어요 = It’s a bit pricey, but it’s good.',
    how: 'Verbs, and words ending in 있다/없다, add **는데** to the stem: 가다 → **가는데**, 먹다 → **먹는데**, 맛있다 → **맛있는데**; ㄹ drops before ㄴ: 살다 → **사는데**. Adjectives take **(으)ㄴ데**, with the same (으)ㄴ as in -(으)ㄴ 후에: 비싸다 → **비싼데**, 좋다 → **좋은데**, 멀다 → **먼데**, 춥다 → **추운데**. For the past, add **는데** to the past stem, even for adjectives: 갔어요 → **갔는데**, 추웠어요 → **추웠는데**.',
    note: 'It’s softer than -지만 (but) and -(으)니까 (so): it just gives the background, and the rest of the sentence shows how it fits. Unlike the “so” of -아서/어서, it’s fine before a request or a suggestion: 시간이 **없는데** 택시 탈까요? = We’re short on time — shall we take a taxi?',
    examples: [
      { ko: '어제 영화를 봤는데 재미있었어요.', en: 'I saw a movie yesterday, and it was fun.' },
      { ko: '지금 카페에 가는데 같이 갈래요?', en: 'I’m going to a café now — do you want to come?' },
    ],
    questions: [
      {
        id: 'rain',
        ko: '비가 오는데 우산 있어요?',
        en: 'It’s raining — do you have an umbrella?',
        answer: '오는데',
        dict: '오다',
        meaning: '“…, so …” (setting the scene for the question)',
        words: ['weather:raining', 'weather:umbrella', 'day:have'],
        contrast: ['myeon', 'ttae'],
      },
      {
        id: 'cold',
        ko: '오늘 추운데 따뜻하게 입으세요.',
        en: 'It’s cold today, so dress warmly.',
        answer: '추운데',
        dict: '춥다',
        pos: 'adjective',
        meaning: '“…, so …” (setting the scene for the request)',
        words: ['day:today', 'weather:cold', 'weather:warm', 'shopping:wear'],
        contrast: ['myeon'],
        traps: [{ text: '추워서', why: '-아서/어서 can’t give the reason for a request (…세요). -는데 can: it sets the scene for the request. So: 추운데.' }],
      },
      {
        id: 'walk',
        ko: '날씨가 좋은데 산책할까요?',
        en: 'The weather’s nice — shall we go for a walk?',
        answer: '좋은데',
        dict: '좋다',
        pos: 'adjective',
        meaning: '“…, so …” (setting the scene for the suggestion)',
        words: ['weather:weather', 'feelings:good', 'hobbies:stroll'],
        contrast: ['myeon'],
        traps: [{ text: '좋아서', why: '-아서/어서 can’t give the reason for a suggestion (…(으)ㄹ까요?). -는데 can: it sets the scene for the suggestion. So: 좋은데.' }],
      },
      {
        id: 'busan',
        ko: '제 친구는 부산에 사는데 다음 주에 서울에 와요.',
        en: 'My friend lives in Busan and is coming to Seoul next week.',
        answer: '사는데',
        dict: '살다',
        meaning: '“…, and …” (the background for what comes next)',
        words: ['people:me', 'day:friend', 'people:live', 'hobbies:nextweek', 'day:come'],
        contrast: ['myeon', 'ttae'],
      },
      {
        id: 'cake',
        ko: '이 카페는 케이크가 맛있는데 좀 비싸요.',
        en: 'The cake at this café is tasty, but it’s a bit expensive.',
        answer: '맛있는데',
        dict: '맛있다',
        pos: 'adjective',
        meaning: '“…, but …” (a soft contrast)',
        words: ['cafe:cafe', 'cafe:cake', 'cafe:delicious', 'shopping:expensive'],
        contrast: ['myeon', 'ttae'],
      },
      {
        id: 'far',
        ko: '그 가게는 좀 먼데 자주 가요.',
        en: 'That shop is a bit far, but I go there often.',
        answer: '먼데',
        dict: '멀다',
        pos: 'adjective',
        meaning: '“…, but …” (a soft contrast)',
        words: ['shopping:shop', 'directions:far', 'day:go'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'slept',
        ko: '어젯밤에 많이 잤는데 아직도 피곤해요.',
        en: 'I slept a lot last night, but I’m still tired.',
        answer: '잤는데',
        dict: '자다',
        tense: 'past',
        meaning: '“…, but …” (a soft contrast)',
        words: ['past:lastnight', 'past:slept', 'feelings:tired'],
        contrast: ['myeon', 'ttae'],
      },
      {
        id: 'busy',
        ko: '어제는 바빴는데 오늘은 시간이 있어요.',
        en: 'I was busy yesterday, but today I have time.',
        answer: '바빴는데',
        dict: '바쁘다',
        pos: 'adjective',
        tense: 'past',
        meaning: '“…, but …” (a soft contrast)',
        words: ['day:yesterday', 'past:wasbusy', 'day:today', 'numbers:hour'],
        contrast: ['myeon', 'ttae'],
        traps: [{ text: '바빴은데', why: 'After the past 았/었, it’s always 는데, even for adjectives: 바빴는데.' }],
      },
      {
        id: 'restaurant',
        ko: '제가 좋은 식당을 아는데 같이 갈까요?',
        en: 'I know a good restaurant — shall we go together?',
        answer: '아는데',
        dict: '알다',
        meaning: '“…, so …” (setting the scene for the suggestion)',
        words: ['people:me', 'feelings:good', 'day:together', 'day:go'],
        contrast: ['myeon', 'ttae'],
      },
      {
        id: 'learned',
        ko: '한국어를 일 년 배웠는데 아직도 어려워요.',
        en: 'I learned Korean for a year, but it’s still hard.',
        answer: '배웠는데',
        dict: '배우다',
        tense: 'past',
        meaning: '“…, but …” (a soft contrast)',
        words: ['day:korean', 'hobbies:learn', 'work:difficult'],
        contrast: ['myeon', 'ttae'],
      },
      {
        id: 'night',
        ko: '밤에는 이 길이 좀 무서운데 낮에는 괜찮아요.',
        en: 'This street is a bit scary at night, but it’s fine during the day.',
        answer: '무서운데',
        dict: '무섭다',
        pos: 'adjective',
        meaning: '“…, but …” (a soft contrast)',
        words: ['day:night', 'directions:road', 'feelings:scared', 'cafe:okay'],
        contrast: ['myeon', 'ttae'],
      },
    ],
  },

  {
    id: 'si',
    order: 18,
    level: 3,
    emoji: '🙇',
    form: 'si',
    title: { ko: '-(으)셨어요', en: 'did … (polite)' },
    meaning: 'The polite past, “did …”: about someone you respect, or when you ask the person you’re talking to. 아까 선생님이 **전화하셨어요** = The teacher called earlier. 한국어는 어디서 **배우셨어요?** = Where did you learn Korean?',
    how: '-(으)세요 is really **-(으)시-** + 어요; in the past, 시 + 었어요 → **셨어요**. So the rules are the same as for -(으)세요: after a vowel, add **셨어요**; after a consonant, add **으셨어요**: 가다 → **가셨어요**, 읽다 → **읽으셨어요**. ㄹ drops before ㅅ: 만들다 → **만드셨어요**. Irregular: 듣다 → **들으셨어요**, 돕다 → **도우셨어요**.',
    note: '-(으)시- honours the person doing the action, so never use it about yourself: 어디 가셨어요? — 저는 도서관에 **갔어요** (not 가셨어요). The special polite words work in the past too: 점심 **드셨어요?** = Have you had lunch?, 안녕히 **주무셨어요?** = Did you sleep well?',
    examples: [
      { ko: '주말 잘 보내셨어요?', en: 'Did you have a good weekend?' },
      { ko: '선생님은 방금 나가셨어요.', en: 'The teacher has just gone out.' },
    ],
    questions: [
      {
        id: 'when',
        ko: '할머니, 언제 오셨어요?',
        en: 'Grandma, when did you get here?',
        answer: '오셨어요',
        dict: '오다',
        words: ['people:grandma', 'numbers:when', 'day:come'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'weekend',
        ko: '주말에 어디 가셨어요?',
        en: 'Where did you go at the weekend?',
        answer: '가셨어요',
        dict: '가다',
        words: ['day:weekend', 'directions:where', 'day:go'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'yesterday',
        ko: '어제 뭐 하셨어요?',
        en: 'What did you do yesterday?',
        answer: '하셨어요',
        dict: '하다',
        words: ['day:yesterday', 'day:what', 'day:do'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'kimchi',
        ko: '어머니가 김치를 만드셨어요.',
        en: 'My mother made the kimchi.',
        answer: '만드셨어요',
        dict: '만들다',
        words: ['people:mother', 'cafe:kimchi', 'past:made'],
        contrast: ['seyo', 'goIt', 'su'],
      },
      {
        id: 'photo',
        ko: '아버지가 이 사진을 찍으셨어요.',
        en: 'My father took this photo.',
        answer: '찍으셨어요',
        dict: '찍다',
        words: ['people:father', 'hobbies:photo', 'hobbies:take'],
        contrast: ['seyo', 'goIt', 'su'],
      },
      {
        id: 'song',
        ko: '할아버지는 매일 이 노래를 들으셨어요.',
        en: 'Grandpa listened to this song every day.',
        answer: '들으셨어요',
        dict: '듣다',
        words: ['people:grandpa', 'day:everyday', 'hobbies:song', 'hobbies:listen'],
        contrast: ['seyo', 'goIt'],
      },
      {
        id: 'before',
        ko: '한국에 오기 전에 어디에 사셨어요?',
        en: 'Where did you live before you came to Korea?',
        answer: '사셨어요',
        dict: '살다',
        words: ['day:come', 'directions:where', 'people:live'],
        contrast: ['seyo', 'su', 'aya'],
      },
      {
        id: 'busy',
        ko: '지난주에 많이 바쁘셨어요?',
        en: 'Were you very busy last week?',
        answer: '바쁘셨어요',
        dict: '바쁘다',
        pos: 'adjective',
        meaning: '“were …” (the polite past, asking the person you’re talking to)',
        words: ['past:lastweek', 'feelings:busy'],
        contrast: ['seyo', 'aya'],
      },
      {
        id: 'house',
        ko: '할아버지가 이 집을 지으셨어요.',
        en: 'My grandfather built this house.',
        answer: '지으셨어요',
        dict: '짓다',
        words: ['people:grandpa', 'day:home'],
        contrast: ['seyo', 'goIt', 'su'],
      },
      {
        id: 'hiking',
        ko: '어제 등산 많이 힘드셨어요?',
        en: 'Was yesterday’s hike very hard for you?',
        answer: '힘드셨어요',
        dict: '힘들다',
        pos: 'adjective',
        meaning: '“was …” (the polite past, asking the person you’re talking to)',
        words: ['day:yesterday', 'hobbies:hiking', 'feelings:hard'],
        contrast: ['seyo', 'aya'],
      },
      {
        id: 'shop',
        ko: '사장님이 새 가게를 여셨어요.',
        en: 'The boss has opened a new shop.',
        answer: '여셨어요',
        dict: '열다',
        words: ['work:boss', 'shopping:shop'],
        contrast: ['seyo', 'su', 'aya'],
      },
    ],
  },
  {
    id: 'jimaseyo',
    order: 19,
    level: 1,
    emoji: '🚫',
    form: 'jimaseyo',
    title: { ko: '-지 마세요', en: 'please don’t …' },
    meaning: '“Please don’t …”: asks someone politely not to do something. You’ll see it on signs everywhere: **만지지 마세요** = Please don’t touch.',
    how: 'Put **지 마세요** straight onto the stem (the dictionary form without 다): 가다 → **가지 마세요**, 먹다 → **먹지 마세요**, 만들다 → **만들지 마세요**. No 아/어, no 으, and irregular words don’t change: 듣다 → **듣지 마세요**.',
    note: 'It’s the “don’t” of -(으)세요: 앉으세요 = please sit, **앉지 마세요** = please don’t sit. 마세요 comes from 말다 (stop), whose ㄹ drops: never 말세요. Don’t use 안 for it: 안 가세요 means “you’re not going”. With friends, it’s **-지 마**. And 걱정하지 마세요 is often shortened to **걱정 마세요**.',
    examples: [
      { ko: '여기에 주차하지 마세요.', en: 'Please don’t park here.' },
      { ko: '아직 가지 마세요. 같이 저녁 먹어요!', en: 'Don’t go yet. Let’s have dinner together!' },
      { ko: '울지 마. 다 괜찮아.', en: 'Don’t cry. It’s all okay. (to a friend)' },
    ],
    questions: [
      {
        id: 'museum',
        ko: '박물관 안에서는 사진을 찍지 마세요.',
        en: 'Please don’t take photos inside the museum.',
        answer: '찍지 마세요',
        dict: '찍다',
        words: ['directions:inside', 'hobbies:photo', 'hobbies:take'],
        contrast: ['seyo', 'aya', 'su'],
      },
      {
        id: 'worry',
        ko: '걱정하지 마세요. 잘할 거예요.',
        en: 'Don’t worry. You’ll do great.',
        answer: '걱정하지 마세요',
        dict: '걱정하다',
        words: ['feelings:dontworry', 'feelings:worried'],
        contrast: ['seyo', 'aya'],
        traps: [
          { text: '걱정 안 하세요', why: '걱정 안 하세요 says that someone doesn’t worry (or asks “aren’t you worried?”). To ask someone not to, use -지 마세요: 걱정하지 마세요.' },
          { text: '안 걱정하세요', why: 'With 걱정하다, 안 goes right before 하다: 걱정 안 하세요, never 안 걱정하세요. And even that only says someone doesn’t worry. To ask someone not to, use -지 마세요: 걱정하지 마세요.' },
        ],
      },
      {
        id: 'late',
        ko: '내일 아침 일곱 시예요. 늦지 마세요!',
        en: 'It’s at seven tomorrow morning. Don’t be late!',
        answer: '늦지 마세요',
        dict: '늦다',
        words: ['day:tomorrow', 'day:morning', 'numbers:seven', 'numbers:oclock', 'past:late'],
        contrast: ['seyo', 'aya', 'su'],
      },
      {
        id: 'phone',
        ko: '수업 시간에는 핸드폰을 보지 마세요.',
        en: 'Please don’t look at your phone during class.',
        answer: '보지 마세요',
        dict: '보다',
        words: ['work:class', 'numbers:hour', 'day:phone', 'day:watch'],
        contrast: ['seyo', 'aya', 'su'],
      },
      {
        id: 'walk',
        ko: '다리가 아파요? 그럼 너무 많이 걷지 마세요.',
        en: 'Does your leg hurt? Then don’t walk too much.',
        answer: '걷지 마세요',
        dict: '걷다',
        words: ['health:leg', 'feelings:hurts', 'directions:walk'],
        contrast: ['seyo', 'aya', 'su'],
      },
      {
        id: 'window',
        ko: '밖에 미세먼지가 많아요. 창문을 열지 마세요.',
        en: 'There’s a lot of fine dust outside. Please don’t open the windows.',
        answer: '열지 마세요',
        dict: '열다',
        words: ['directions:outside', 'weather:finedust'],
        contrast: ['seyo', 'aya', 'su'],
      },
      {
        id: 'taxi',
        ko: '택시를 타지 마세요. 지하철이 더 빨라요.',
        en: 'Don’t take a taxi. The subway is faster.',
        answer: '타지 마세요',
        dict: '타다',
        words: ['directions:taxi', 'directions:ride', 'directions:subway', 'travel:fast'],
        contrast: ['seyo', 'aya', 'su'],
      },
      {
        id: 'coffee',
        ko: '밤에는 커피를 마시지 마세요. 잠을 못 자요.',
        en: 'Don’t drink coffee at night. You won’t be able to sleep.',
        answer: '마시지 마세요',
        dict: '마시다',
        words: ['day:night', 'cafe:coffee', 'day:drink', 'day:sleep'],
        contrast: ['seyo', 'aya', 'su'],
      },
    ],
  },

  {
    id: 'ryeogo',
    order: 20,
    level: 2,
    emoji: '🎯',
    form: 'ryeogo',
    title: { ko: '-(으)려고', en: 'in order to …' },
    meaning: '“(In order) to …, so (that) …”: what you do something for. 살을 **빼려고** 운동해요 = I work out to lose weight.',
    how: 'After a vowel or ㄹ, add **려고**; after any other consonant, add **으려고**: 가다 → **가려고**, 만들다 → **만들려고**, 먹다 → **먹으려고**. Irregular: 듣다 → **들으려고** (ㄷ → ㄹ), 돕다 → **도우려고** (ㅂ → 우), 낫다 → **나으려고** (ㅅ drops).',
    note: '-(으)러 says what for too, but it only goes before verbs of coming and going (가다, 오다, 다니다…); -(으)려고 goes before any verb: 일찍 **일어나려고** 알람을 맞췄어요 = I set an alarm so I’d get up early. It isn’t used before a request or a suggestion (…세요, …(으)ㄹ까요?). You’ll often hear [먹을려고], but it’s spelled **먹으려고**.',
    examples: [
      { ko: '한국어를 배우려고 학원에 다녀요.', en: 'I go to a language school to learn Korean.' },
      { ko: '돈을 아끼려고 집에서 커피를 마셔요.', en: 'I drink coffee at home to save money.' },
      { ko: '잊어버리지 않으려고 메모했어요.', en: 'I wrote it down so I wouldn’t forget.' },
    ],
    questions: [
      {
        id: 'flowers',
        ko: '여자 친구에게 주려고 꽃을 샀어요.',
        en: 'I bought some flowers to give to my girlfriend.',
        answer: '주려고',
        dict: '주다',
        words: ['people:girlfriend', 'weather:flower', 'past:bought'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'photo',
        ko: '예쁜 사진을 찍으려고 아침 일찍 일어났어요.',
        en: 'I got up early in the morning to take some nice photos.',
        answer: '찍으려고',
        dict: '찍다',
        words: ['hobbies:photo', 'hobbies:take', 'day:morning', 'day:early', 'day:getup'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'phone',
        ko: '새 핸드폰을 사려고 돈을 모으고 있어요.',
        en: 'I’m saving money to buy a new phone.',
        answer: '사려고',
        dict: '사다',
        words: ['day:phone', 'shopping:buy', 'shopping:money'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'grandma',
        ko: '할머니 목소리를 들으려고 전화했어요.',
        en: 'I called my grandma to hear her voice.',
        answer: '들으려고',
        dict: '듣다',
        words: ['people:grandma', 'hobbies:listen'],
        contrast: ['myeon', 'aseo', 'nikka'],
      },
      {
        id: 'dinner',
        ko: '저녁을 만들려고 일찍 퇴근했어요.',
        en: 'I left work early to make dinner.',
        answer: '만들려고',
        dict: '만들다',
        words: ['day:evening', 'past:made', 'day:early', 'day:leavework'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'exam',
        ko: '시험에 합격하려고 열심히 공부했어요.',
        en: 'I studied hard to pass the exam.',
        answer: '합격하려고',
        dict: '합격하다',
        words: ['work:exam', 'work:passed', 'work:hard', 'past:studied'],
        contrast: ['myeon', 'aseo', 'nikka'],
      },
      {
        id: 'cold',
        ko: '감기에 안 걸리려고 손을 자주 씻어요.',
        en: 'I wash my hands often so I don’t catch a cold.',
        answer: '걸리려고',
        dict: '걸리다',
        meaning: '“so (that) …” (with 안 before it: “so that … not”)',
        words: ['weather:acold', 'health:hand', 'day:often', 'day:wash'],
        contrast: ['myeon', 'aseo', 'nikka'],
      },
      {
        id: 'better',
        ko: '빨리 나으려고 약을 먹고 푹 쉬었어요.',
        en: 'I took some medicine and got plenty of rest so I’d get better quickly.',
        answer: '나으려고',
        dict: '낫다',
        words: ['health:getbetter', 'health:medicine', 'day:eat', 'day:rest'],
        contrast: ['myeon', 'aseo', 'nikka'],
      },
    ],
  },

  {
    id: 'myeonseo',
    order: 21,
    level: 2,
    emoji: '🤹',
    form: 'myeonseo',
    title: { ko: '-(으)면서', en: 'while …' },
    meaning: '“While …”: one person doing two things at the same time. 음악을 **들으면서** 공부해요 = I study while listening to music. With adjectives, it means “and at the same time”: 이 식당은 **싸면서** 맛있어요 = This restaurant is both cheap and tasty.',
    how: 'After a vowel or ㄹ, add **면서**; after any other consonant, add **으면서**: 가다 → **가면서**, 살다 → **살면서**, 먹다 → **먹으면서**. Adjectives work the same way: 싸다 → **싸면서**. Irregular: 듣다 → **들으면서** (ㄷ → ㄹ), 맵다 → **매우면서** (ㅂ → 우).',
    note: 'Only the last verb shows the tense: 어제 **걸으면서** 전화했어요 = Yesterday I made a phone call while I walked. -고 is “and then”: 밥을 **먹고** 텔레비전을 봐요 = I eat, then I watch TV. -(으)면서 is both at once: 밥을 **먹으면서** 텔레비전을 봐요 = I watch TV while I eat.',
    examples: [
      { ko: '운전하면서 전화하지 마세요.', en: 'Don’t talk on the phone while you’re driving.' },
      { ko: '그 아이는 웃으면서 인사했어요.', en: 'The child said hello with a smile.' },
    ],
    questions: [
      {
        id: 'radio',
        ko: '아빠는 라디오를 들으면서 운전해요.',
        en: 'My dad listens to the radio while he drives.',
        answer: '들으면서',
        dict: '듣다',
        words: ['people:dad', 'hobbies:listen'],
        contrast: ['myeon', 'jiman', 'aseo'],
      },
      {
        id: 'park',
        ko: '어제 친구하고 공원을 걸으면서 이야기했어요.',
        en: 'Yesterday my friend and I talked while we walked in the park.',
        answer: '걸으면서',
        dict: '걷다',
        words: ['day:yesterday', 'day:friend', 'directions:walk'],
        contrast: ['myeon', 'jiman', 'aseo', 'go'],
      },
      {
        id: 'snack',
        ko: '아이들이 과자를 먹으면서 만화를 봐요.',
        en: 'The kids watch cartoons while they eat snacks.',
        answer: '먹으면서',
        dict: '먹다',
        words: ['people:child', 'day:eat', 'day:watch'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'cafe',
        ko: '어제 카페에서 커피를 마시면서 책을 읽었어요.',
        en: 'Yesterday I read a book at a café while drinking coffee.',
        answer: '마시면서',
        dict: '마시다',
        words: ['cafe:cafe', 'cafe:coffee', 'day:drink', 'day:book', 'past:read'],
        contrast: ['myeon', 'jiman', 'aseo', 'go'],
      },
      {
        id: 'bus',
        ko: '아까 버스를 기다리면서 단어를 외웠어요.',
        en: 'Earlier, I memorised some words while I waited for the bus.',
        answer: '기다리면서',
        dict: '기다리다',
        words: ['past:earlier', 'directions:bus', 'day:wait', 'work:word', 'work:memorise'],
        contrast: ['myeon', 'jiman', 'aseo', 'go'],
      },
      {
        id: 'korea',
        ko: '한국에 살면서 한국어를 배웠어요.',
        en: 'I learned Korean while I was living in Korea.',
        answer: '살면서',
        dict: '살다',
        words: ['people:live', 'day:korean', 'hobbies:learn'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'shoes',
        ko: '이 신발은 예쁘면서 편해요.',
        en: 'These shoes are pretty and comfortable at the same time.',
        answer: '예쁘면서',
        dict: '예쁘다',
        pos: 'adjective',
        meaning: '“and at the same time” (two things that are both true)',
        words: ['shopping:shoes', 'shopping:pretty', 'travel:comfortable'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'spicy',
        ko: '이 떡볶이는 매우면서 달아요.',
        en: 'This tteokbokki is spicy and sweet at the same time.',
        answer: '매우면서',
        dict: '맵다',
        pos: 'adjective',
        meaning: '“and at the same time” (two things that are both true)',
        words: ['cafe:spicy', 'cafe:sweet'],
        contrast: ['myeon', 'aseo'],
      },
    ],
  },

  {
    id: 'jeogi',
    order: 22,
    level: 2,
    emoji: '🗺️',
    form: 'jeogi',
    title: { ko: '-(으)ㄴ 적이 있어요', en: 'have (ever) …' },
    meaning: 'Something you’ve done at least once, “have (ever) …”: 한국에 **간 적이 있어요** = I’ve been to Korea. With **없어요** instead of 있어요, it means “have never …”: 한국 음식을 **먹은 적이 없어요** = I’ve never had Korean food.',
    how: 'Make the (으)ㄴ form and add **적이 있어요** (or **적이 없어요**). After a vowel, put **ㄴ** under the last syllable; after a consonant, add **은**: 가다 → **간 적이 있어요**, 먹다 → **먹은 적이 있어요**. ㄹ stems drop the ㄹ: 만들다 → **만든 적이 있어요**. Irregular: 듣다 → **들은 적이 있어요** (ㄷ → ㄹ), 돕다 → **도운 적이 있어요** (ㅂ → 우).',
    note: '**-아/어 본 적이 있어요** means the same, with a hint of “tried”: 먹어 본 적이 있어요 = 먹은 적이 있어요. Here 적 always takes the (으)ㄴ form: 먹은 적, never 먹는 적 or 먹을 적. In everyday speech, the 이 often drops: 간 적 있어요?',
    examples: [
      { ko: '한국 영화를 본 적이 있어요? — 네, 많이 봤어요.', en: 'Have you ever seen a Korean movie? — Yes, lots.' },
      { ko: '저는 한 번도 이사한 적이 없어요.', en: 'I’ve never moved house, not even once.' },
      { ko: '번지 점프를 해 본 적이 있어요?', en: 'Have you ever tried bungee jumping?' },
    ],
    questions: [
      {
        id: 'hanbok',
        ko: '한복을 입고 사진을 찍은 적이 있어요?',
        en: 'Have you ever taken photos in a hanbok?',
        answer: '찍은 적이 있어요',
        dict: '찍다',
        words: ['shopping:wear', 'hobbies:photo', 'hobbies:take'],
        contrast: ['su', 'goIt'],
      },
      {
        id: 'passport',
        ko: '여행 중에 여권을 잃어버린 적이 있어요.',
        en: 'I’ve lost my passport on a trip before.',
        answer: '잃어버린 적이 있어요',
        dict: '잃어버리다',
        words: ['hobbies:trip', 'travel:passport', 'past:lost'],
        contrast: ['jeogiNot', 'su'],
      },
      {
        id: 'song',
        ko: '이 노래를 들은 적이 있어요?',
        en: 'Have you ever heard this song?',
        answer: '들은 적이 있어요',
        dict: '듣다',
        words: ['hobbies:song', 'hobbies:listen'],
        contrast: ['su', 'goIt'],
      },
      {
        id: 'abroad',
        ko: '다른 나라에서 산 적이 있어요?',
        en: 'Have you ever lived in another country?',
        answer: '산 적이 있어요',
        dict: '살다',
        words: ['shopping:other', 'people:country', 'people:live'],
        contrast: ['su', 'goIt'],
      },
      {
        id: 'class',
        ko: '수업 시간에 잔 적이 있어요.',
        en: 'I’ve fallen asleep in class before.',
        answer: '잔 적이 있어요',
        dict: '자다',
        words: ['work:class', 'numbers:hour', 'day:sleep'],
        contrast: ['jeogiNot', 'su', 'goIt', 'lgeyo'],
      },
      {
        id: 'late',
        ko: '저는 약속에 늦은 적이 없어요.',
        en: 'I’ve never been late for an appointment.',
        answer: '늦은 적이 없어요',
        dict: '늦다',
        form: 'jeogiNot',
        words: ['people:me', 'hobbies:promise', 'past:late'],
        contrast: ['jeogi', 'su', 'lgeyo'],
      },
      {
        id: 'sea',
        ko: '바다에서 수영한 적이 없어요.',
        en: 'I’ve never swum in the sea.',
        answer: '수영한 적이 없어요',
        dict: '수영하다',
        form: 'jeogiNot',
        words: ['weather:sea', 'hobbies:swim'],
        contrast: ['jeogi', 'suNot', 'goIt'],
      },
      {
        id: 'plane',
        ko: '저는 비행기를 탄 적이 없어요.',
        en: 'I’ve never been on a plane.',
        answer: '탄 적이 없어요',
        dict: '타다',
        form: 'jeogiNot',
        words: ['people:me', 'travel:plane', 'directions:ride'],
        contrast: ['jeogi', 'su', 'lgeyo'],
        traps: [{ text: '안 탄 적이 있어요', why: '안 탄 적이 있어요 means “there was a time I didn’t take it”. For “have never …”, it’s 적이 없어요: 탄 적이 없어요.' }],
      },
    ],
  },
]);
