/**
 * Grammar patterns, practised in Grammar Cards (js/games/grammar-cards.js):
 * the endings that join two ideas (-고, -지만, -아서/어서, -(으)면…) and the
 * helper endings for "can", "must" and "may".
 *
 * Each pattern has an intro card (meaning, how to make it, a note, examples;
 * the table of forms is built by the grammar engine) and questions: a sentence
 * with one word blanked out, to be filled with the right form.
 *
 * A question only names the word and its ending — the grammar engine
 * (js/core/grammar.js) makes the form, checks `answer` against it, and builds
 * the wrong options with their explanations:
 *   contrast: other endings that give the sentence a different meaning (the
 *             English shows which one is meant). Never list one that could
 *             also be right here: -(으)면/-(으)ㄹ 때, -아서/-(으)니까,
 *             -아서/-고, -(으)ㄴ 후에/-고/-아서, -(으)ㄹ 수 있어요/-아도 돼요.
 *   traps:    hand-written wrong options, each with its reason.
 *   meaning:  what the ending means in this sentence, if it's not the usual one.
 * Fields: id, ko, en, answer (the form as it appears in ko), dict, pos
 * ('verb' | 'adjective'), tense ('past' for -고, -지만, -(으)니까, -(으)ㄹ 때),
 * form (another ending of this pattern), words (vocabulary refs, 'topic:id':
 * questions whose words you know come first).
 */
Mallang.content.registerGrammar([
  {
    id: 'go',
    order: 1,
    level: 1,
    emoji: '➕',
    form: 'go',
    title: { ko: '-고', en: 'and' },
    meaning: 'Joins two actions or two facts: “and”. With actions, it also means “and then”.',
    how: 'Put **고** straight onto the stem (the dictionary form without 다): 먹다 → **먹고**, 가다 → **가고**, 춥다 → **춥고**. No 아/어, no 으, and irregular words don’t change.',
    note: 'Usually only the last verb shows the tense: 어제 점심을 **먹고** 산책했어요 = Yesterday I had lunch and then took a walk. To say how you travel, Korean uses -고 too: 버스를 **타고** 가요 = I go by bus.',
    examples: [
      { ko: '이 카페는 싸고 맛있어요.', en: 'This café is cheap and tasty.' },
      { ko: '주말에 청소하고 쉬어요.', en: 'At the weekend I clean and then rest.' },
      { ko: '어제 친구하고 영화를 보고 밥을 먹었어요.', en: 'Yesterday I watched a movie with a friend and then had a meal.' },
    ],
    questions: [
      {
        id: 'shower',
        ko: '아침에 샤워하고 커피를 마셔요.',
        en: 'In the morning I shower and then drink coffee.',
        answer: '샤워하고',
        dict: '샤워하다',
        words: ['day:morning', 'day:shower', 'cafe:coffee', 'day:drink'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'cheap',
        ko: '이 가게는 싸고 좋아요.',
        en: 'This shop is cheap and good.',
        answer: '싸고',
        dict: '싸다',
        pos: 'adjective',
        words: ['shopping:shop', 'shopping:cheap', 'feelings:good'],
        contrast: ['jiman', 'myeon'],
        traps: [{ text: '싸서', why: '싸서 is -아서/어서: “it’s cheap, so it’s good”. The sentence just adds two facts: cheap and good → 싸고.' }],
      },
      {
        id: 'exercise',
        ko: '저녁에 운동하고 샤워해요.',
        en: 'In the evening I work out and then shower.',
        answer: '운동하고',
        dict: '운동하다',
        words: ['day:evening', 'day:exercise', 'day:shower'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'clear',
        ko: '오늘은 날씨가 맑고 따뜻해요.',
        en: 'Today the weather is clear and warm.',
        answer: '맑고',
        dict: '맑다',
        pos: 'adjective',
        words: ['day:today', 'weather:weather', 'weather:clear', 'weather:warm'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'lunch',
        ko: '점심을 먹고 산책해요.',
        en: 'I have lunch and then take a walk.',
        answer: '먹고',
        dict: '먹다',
        words: ['day:lunch', 'day:eat', 'hobbies:stroll'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'cold',
        ko: '어제는 춥고 흐렸어요.',
        en: 'Yesterday it was cold and cloudy.',
        answer: '춥고',
        dict: '춥다',
        pos: 'adjective',
        words: ['day:yesterday', 'weather:cold', 'weather:cloudy'],
        contrast: ['jiman', 'myeon'],
      },
      {
        id: 'bus',
        ko: '저는 버스를 타고 학교에 가요.',
        en: 'I go to school by bus.',
        answer: '타고',
        dict: '타다',
        words: ['directions:bus', 'directions:ride', 'day:school', 'day:go'],
        contrast: ['jiman', 'myeon'],
        traps: [{ text: '타서', why: 'To say how you travel, Korean uses -고: 버스를 타고 가요 = I go by bus. -아서/어서 gives a reason or the next step, not the way you go.' }],
      },
      {
        id: 'music',
        ko: '주말에 음악을 듣고 책을 읽었어요.',
        en: 'On the weekend I listened to music and read a book.',
        answer: '듣고',
        dict: '듣다',
        words: ['day:weekend', 'hobbies:music', 'hobbies:listen', 'day:book', 'day:read'],
        contrast: ['jiman', 'myeon'],
      },
    ],
  },

  {
    id: 'jiman',
    order: 2,
    level: 1,
    emoji: '⚖️',
    form: 'jiman',
    title: { ko: '-지만', en: 'but' },
    meaning: 'Joins two ideas that go against each other: “but”.',
    how: 'Put **지만** straight onto the stem, just like -고: 먹다 → **먹지만**, 비싸다 → **비싸지만**, 춥다 → **춥지만**. No 아/어, no 으, and irregular words don’t change. For the past, add it to the past stem: 갔어요 → **갔지만**, 먹었어요 → **먹었지만**.',
    note: 'Put 은/는 on the two things you compare: 여름**은** 좋지만 겨울**은** 싫어요 = I like summer, but I don’t like winter.',
    examples: [
      { ko: '한국어는 어렵지만 재미있어요.', en: 'Korean is hard, but it’s fun.' },
      { ko: '이 가방은 싸지만 좋아요.', en: 'This bag is cheap, but it’s good.' },
      { ko: '어제는 피곤했지만 운동했어요.', en: 'I was tired yesterday, but I worked out.' },
    ],
    questions: [
      {
        id: 'expensive',
        ko: '좀 비싸지만 이걸로 할게요.',
        en: 'It’s a bit expensive, but I’ll take this one.',
        answer: '비싸지만',
        dict: '비싸다',
        pos: 'adjective',
        words: ['shopping:expensive', 'shopping:takethis'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'busy',
        ko: '어제는 바빴지만 재미있었어요.',
        en: 'Yesterday I was busy, but it was fun.',
        answer: '바빴지만',
        dict: '바쁘다',
        pos: 'adjective',
        tense: 'past',
        words: ['day:yesterday', 'past:wasbusy', 'past:wasfun'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'coffee',
        ko: '커피는 좋아하지만 우유는 안 좋아해요.',
        en: 'I like coffee, but I don’t like milk.',
        answer: '좋아하지만',
        dict: '좋아하다',
        words: ['cafe:coffee', 'feelings:like', 'cafe:milk'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'spicy',
        ko: '김치는 맵지만 맛있어요.',
        en: 'Kimchi is spicy, but it’s tasty.',
        answer: '맵지만',
        dict: '맵다',
        pos: 'adjective',
        words: ['cafe:kimchi', 'cafe:spicy', 'cafe:delicious'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'near',
        ko: '학교가 가깝지만 버스를 타요.',
        en: 'School is close, but I take the bus.',
        answer: '가깝지만',
        dict: '가깝다',
        pos: 'adjective',
        words: ['day:school', 'directions:near', 'directions:bus', 'directions:ride'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'late',
        ko: '어젯밤 늦게 잤지만 일찍 일어났어요.',
        en: 'I went to bed late last night, but I got up early.',
        answer: '잤지만',
        dict: '자다',
        tense: 'past',
        words: ['past:lastnight', 'past:slept', 'day:early', 'day:getup'],
        contrast: ['myeon', 'aseo', 'go'],
      },
      {
        id: 'cold',
        ko: '어제는 추웠지만 오늘은 따뜻해요.',
        en: 'Yesterday it was cold, but today it’s warm.',
        answer: '추웠지만',
        dict: '춥다',
        pos: 'adjective',
        tense: 'past',
        words: ['day:yesterday', 'past:wascold', 'day:today', 'weather:warm'],
        contrast: ['myeon', 'aseo'],
      },
      {
        id: 'music',
        ko: '한국 음악을 매일 듣지만 한국어는 잘 몰라요.',
        en: 'I listen to Korean music every day, but I don’t know Korean well.',
        answer: '듣지만',
        dict: '듣다',
        words: ['hobbies:music', 'day:everyday', 'hobbies:listen', 'day:korean'],
        contrast: ['myeon', 'aseo'],
      },
    ],
  },

  {
    id: 'aseo',
    order: 3,
    level: 2,
    emoji: '➡️',
    form: 'aseo',
    title: { ko: '-아서/어서', en: 'so / and then' },
    meaning: 'Two uses. A reason, “so / because”: **추워서** = it’s cold, so… Or the next step, “and then”, when the second action happens where you went, with the person you met, or with what you just got: **가서** (go there and…), **만나서** (meet and … together), **사서** (buy it and…).',
    how: 'Take the 아/어 form (the present without 요) and add **서**: 가요 → **가서**, 먹어요 → **먹어서**, 해요 → **해서**, 마셔요 → **마셔서**. Irregular words change just as in the present: 들어요 → **들어서**, 추워요 → **추워서**.',
    note: '-아서/어서 never takes the past; the last verb shows the tense: 어제 **바빠서** 못 갔어요 = I was busy yesterday, so I couldn’t go (not 바빴어서). For a reason, don’t use it before a request or a suggestion (…세요, …(으)ㄹ까요?): that’s what -(으)니까 is for. For “and then” it’s fine: 빵을 **사서** 같이 먹을까요? = Shall we buy some bread and eat it together? Two fixed phrases: **만나서** 반가워요 = Nice to meet you, **늦어서** 미안해요 = Sorry I’m late.',
    examples: [
      { ko: '시간이 없어서 택시를 탔어요.', en: 'I didn’t have time, so I took a taxi.' },
      { ko: '학교에 가서 친구를 만났어요.', en: 'I went to school and met a friend there.' },
      { ko: '빵을 사서 먹었어요.', en: 'I bought some bread and ate it.' },
    ],
    questions: [
      {
        id: 'cold',
        ko: '어제는 추워서 집에 있었어요.',
        en: 'It was cold yesterday, so I stayed home.',
        answer: '추워서',
        dict: '춥다',
        pos: 'adjective',
        meaning: '“so / because” (a reason)',
        words: ['day:yesterday', 'weather:cold', 'day:home', 'day:have'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'hungry',
        ko: '배고파서 빵을 먹었어요.',
        en: 'I was hungry, so I ate some bread.',
        answer: '배고파서',
        dict: '배고프다',
        pos: 'adjective',
        meaning: '“so / because” (a reason)',
        words: ['cafe:hungry', 'cafe:bread', 'past:ate'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'rain',
        ko: '비가 와서 우산을 샀어요.',
        en: 'It was raining, so I bought an umbrella.',
        answer: '와서',
        dict: '오다',
        meaning: '“so / because” (a reason)',
        words: ['weather:raining', 'weather:umbrella', 'past:bought'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'way',
        ko: '길을 몰라서 늦었어요.',
        en: 'I didn’t know the way, so I was late.',
        answer: '몰라서',
        dict: '모르다',
        meaning: '“so / because” (a reason)',
        words: ['directions:road', 'past:didntknow'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'walk',
        ko: '오늘 많이 걸어서 피곤해요.',
        en: 'I walked a lot today, so I’m tired.',
        answer: '걸어서',
        dict: '걷다',
        meaning: '“so / because” (a reason)',
        words: ['day:today', 'directions:walk', 'feelings:tired'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'meet',
        ko: '친구를 만나서 영화를 봤어요.',
        en: 'I met up with a friend and we watched a movie.',
        answer: '만나서',
        dict: '만나다',
        meaning: '“and then” (you meet up, then do the next thing together)',
        words: ['day:friend', 'day:meet', 'day:movie', 'past:saw'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'library',
        ko: '도서관에 가서 공부했어요.',
        en: 'I went to the library and studied there.',
        answer: '가서',
        dict: '가다',
        meaning: '“and then” (you go there, then do the next thing there)',
        words: ['day:library', 'day:go', 'past:studied'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'cake',
        ko: '케이크를 만들어서 친구에게 줬어요.',
        en: 'I made a cake and gave it to my friend.',
        answer: '만들어서',
        dict: '만들다',
        meaning: '“and then” (you make it, then do the next thing with it)',
        words: ['cafe:cake', 'past:made', 'day:friend', 'cafe:please'],
        contrast: ['myeon', 'jiman'],
      },
    ],
  },

  {
    id: 'myeon',
    order: 4,
    level: 2,
    emoji: '🤔',
    form: 'myeon',
    title: { ko: '-(으)면', en: 'if / when' },
    meaning: '“If”, or “when / whenever”: the first part is the condition for the second.',
    how: 'After a vowel or ㄹ, add **면**; after any other consonant, add **으면**: 가다 → **가면**, 살다 → **살면**, 먹다 → **먹으면**. Irregular: 듣다 → **들으면** (ㄷ → ㄹ), 춥다 → **추우면** (ㅂ → 우).',
    note: 'Even about the future, -(으)면 stays the same; only the last verb changes: 내일 날씨가 **좋으면** 공원에 갈 거예요 = If the weather is nice tomorrow, I’ll go to the park. For one particular time in the past (“when I was little”), use -(으)ㄹ 때 instead.',
    examples: [
      { ko: '피곤하면 쉬세요.', en: 'If you’re tired, get some rest.' },
      { ko: '여기서 걸으면 십 분 걸려요.', en: 'It’s ten minutes from here if you walk.' },
    ],
    questions: [
      {
        id: 'rain',
        ko: '내일 비가 오면 집에 있을 거예요.',
        en: 'If it rains tomorrow, I’ll stay home.',
        answer: '오면',
        dict: '오다',
        words: ['day:tomorrow', 'weather:raining', 'day:home', 'day:have'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'time',
        ko: '시간이 있으면 같이 영화 볼까요?',
        en: 'If you have time, shall we watch a movie together?',
        answer: '있으면',
        dict: '있다',
        words: ['numbers:hour', 'day:have', 'day:together', 'day:movie', 'day:watch'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'cash',
        ko: '현금이 없으면 카드도 괜찮아요.',
        en: 'If you don’t have cash, a card is fine too.',
        answer: '없으면',
        dict: '없다',
        words: ['shopping:cash', 'day:nothave', 'shopping:card', 'cafe:okay'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'hot',
        ko: '더우면 물을 많이 마시세요.',
        en: 'If it’s hot, drink lots of water.',
        answer: '더우면',
        dict: '덥다',
        pos: 'adjective',
        words: ['weather:hot', 'cafe:water', 'day:drink'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'song',
        ko: '이 노래를 들으면 기분이 좋아요.',
        en: 'Whenever I hear this song, I feel good.',
        answer: '들으면',
        dict: '듣다',
        words: ['hobbies:song', 'hobbies:listen', 'feelings:mood', 'feelings:good'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'far',
        ko: '멀면 택시를 타세요.',
        en: 'If it’s far, take a taxi.',
        answer: '멀면',
        dict: '멀다',
        pos: 'adjective',
        words: ['directions:far', 'directions:taxi', 'directions:ride'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'medicine',
        ko: '이 약을 먹으면 괜찮을 거예요.',
        en: 'If you take this medicine, you’ll be okay.',
        answer: '먹으면',
        dict: '먹다',
        words: ['day:eat', 'cafe:okay'],
        contrast: ['jiman', 'aseo'],
      },
      {
        id: 'seoul',
        ko: '서울에 살면 지하철을 많이 타요.',
        en: 'If you live in Seoul, you take the subway a lot.',
        answer: '살면',
        dict: '살다',
        words: ['directions:subway', 'directions:ride'],
        contrast: ['jiman', 'aseo'],
      },
    ],
  },

  {
    id: 'reo',
    order: 5,
    level: 2,
    emoji: '🚶',
    form: 'reo',
    title: { ko: '-(으)러', en: '(go / come) to do' },
    meaning: 'Says why you go or come somewhere: “(go / come) to do …”.',
    how: 'After a vowel or ㄹ, add **러**; after any other consonant, add **으러**: 보다 → **보러**, 놀다 → **놀러**, 먹다 → **먹으러**. Irregular: 듣다 → **들으러** (ㄷ → ㄹ). Then comes 가다 or 오다: 보러 가요, 놀러 오세요.',
    note: 'It only goes before verbs of coming and going, like 가다 and 오다. For other verbs, Korean uses -(으)려고, which comes later. The place can go before or after: 카페에 공부하러 가요 = 공부하러 카페에 가요.',
    examples: [
      { ko: '우리 집에 놀러 오세요!', en: 'Come over to my place to hang out!' },
      { ko: '한국어를 배우러 한국에 왔어요.', en: 'I came to Korea to learn Korean.' },
    ],
    questions: [
      {
        id: 'lunch',
        ko: '같이 점심 먹으러 갈까요?',
        en: 'Shall we go get lunch together?',
        answer: '먹으러',
        dict: '먹다',
        words: ['day:together', 'day:lunch', 'day:eat', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'movie',
        ko: '어제 친구하고 영화 보러 갔어요.',
        en: 'Yesterday I went to see a movie with a friend.',
        answer: '보러',
        dict: '보다',
        words: ['day:yesterday', 'day:friend', 'day:movie', 'day:watch', 'past:went'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'milk',
        ko: '우유 사러 가게에 가요.',
        en: 'I’m going to the shop to buy milk.',
        answer: '사러',
        dict: '사다',
        words: ['cafe:milk', 'shopping:buy', 'shopping:shop', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'read',
        ko: '책을 읽으러 도서관에 가요.',
        en: 'I go to the library to read.',
        answer: '읽으러',
        dict: '읽다',
        words: ['day:book', 'day:read', 'day:library', 'day:go'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'photo',
        ko: '사진을 찍으러 공원에 갔어요.',
        en: 'I went to the park to take pictures.',
        answer: '찍으러',
        dict: '찍다',
        words: ['hobbies:photo', 'hobbies:take', 'past:went'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'play',
        ko: '친구가 집에 놀러 왔어요.',
        en: 'A friend came over to hang out.',
        answer: '놀러',
        dict: '놀다',
        words: ['day:friend', 'day:home', 'hobbies:play', 'past:came'],
        contrast: ['aseo', 'myeon', 'go'],
      },
      {
        id: 'class',
        ko: '한국어 수업을 들으러 학교에 가요.',
        en: 'I go to school to take a Korean class.',
        answer: '들으러',
        dict: '듣다',
        words: ['day:korean', 'hobbies:listen', 'day:school', 'day:go'],
        contrast: ['myeon', 'go'],
      },
      {
        id: 'meet',
        ko: '내일 친구를 만나러 카페에 갈 거예요.',
        en: 'Tomorrow I’m going to a café to meet a friend.',
        answer: '만나러',
        dict: '만나다',
        words: ['day:tomorrow', 'day:friend', 'day:meet', 'cafe:cafe', 'hobbies:willgo'],
        contrast: ['aseo', 'myeon', 'go'],
      },
    ],
  },

  {
    id: 'su',
    order: 6,
    level: 2,
    emoji: '💪',
    form: 'su',
    title: { ko: '-(으)ㄹ 수 있어요', en: 'can / can’t' },
    meaning: '“Can”: you’re able to, or it’s possible. With **없어요** instead of 있어요, it means “can’t”.',
    how: 'After a vowel, put **ㄹ** under the last syllable and add **수 있어요**; after a consonant, add **을 수 있어요**: 가다 → **갈 수 있어요**, 먹다 → **먹을 수 있어요**. ㄹ stems just add 수 있어요: 만들다 → **만들 수 있어요**. Irregular: 듣다 → **들을 수 있어요**. For “can’t”: 갈 수 **없어요**.',
    note: 'The short way to say “can’t” is **못** + verb: 못 가요 = 갈 수 없어요. With 하다 verbs like 수영하다, 못 goes right before 해요: 수영 못 해요.',
    examples: [
      { ko: '내일 몇 시에 올 수 있어요?', en: 'What time can you come tomorrow?' },
      { ko: '오늘은 너무 바빠서 만날 수 없어요.', en: 'I’m too busy today, so I can’t meet up.' },
    ],
    questions: [
      {
        id: 'swim',
        ko: '동생은 다섯 살이지만 수영할 수 있어요.',
        en: 'My little brother is five, but he can swim.',
        answer: '수영할 수 있어요',
        dict: '수영하다',
        words: ['people:sibling', 'numbers:five', 'numbers:age', 'hobbies:swim'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'kimchi',
        ko: '김치를 만들 수 있어요?',
        en: 'Can you make kimchi?',
        answer: '만들 수 있어요',
        dict: '만들다',
        words: ['cafe:kimchi', 'past:made'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'read',
        ko: '한국어를 읽을 수 있어요?',
        en: 'Can you read Korean?',
        answer: '읽을 수 있어요',
        dict: '읽다',
        words: ['day:korean', 'day:read'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'sing',
        ko: '한국 노래도 부를 수 있어요.',
        en: 'I can sing Korean songs too.',
        answer: '부를 수 있어요',
        dict: '부르다',
        words: ['hobbies:song', 'hobbies:sing'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'bike',
        ko: '자전거를 탈 수 있어요?',
        en: 'Can you ride a bike?',
        answer: '탈 수 있어요',
        dict: '타다',
        words: ['hobbies:bike', 'directions:ride'],
        contrast: ['aya', 'suNot'],
      },
      {
        id: 'spicy',
        ko: '너무 매워서 먹을 수 없어요.',
        en: 'It’s too spicy. I can’t eat it.',
        answer: '먹을 수 없어요',
        dict: '먹다',
        form: 'suNot',
        words: ['cafe:spicy', 'day:eat'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'walk',
        ko: '피곤해서 더 걸을 수 없어요.',
        en: 'I’m tired. I can’t walk any further.',
        answer: '걸을 수 없어요',
        dict: '걷다',
        form: 'suNot',
        words: ['feelings:tired', 'cafe:more', 'directions:walk'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'work',
        ko: '회사에서는 음악을 들을 수 없어요.',
        en: 'I can’t listen to music at work.',
        answer: '들을 수 없어요',
        dict: '듣다',
        form: 'suNot',
        words: ['day:company', 'hobbies:music', 'hobbies:listen'],
        contrast: ['su', 'aya'],
      },
      {
        id: 'tomorrow',
        ko: '미안해요, 내일은 갈 수 없어요.',
        en: 'Sorry, I can’t go tomorrow.',
        answer: '갈 수 없어요',
        dict: '가다',
        form: 'suNot',
        words: ['day:tomorrow', 'day:go'],
        contrast: ['su', 'aya'],
      },
    ],
  },

  {
    id: 'aya',
    order: 7,
    level: 2,
    emoji: '❗',
    form: 'aya',
    title: { ko: '-아/어야 해요', en: 'have to / must' },
    meaning: '“Have to / must”: something you need to do.',
    how: 'Take the 아/어 form (the present without 요) and add **야 해요**: 가요 → **가야 해요**, 먹어요 → **먹어야 해요**, 해요 → **해야 해요**, 마셔요 → **마셔야 해요**. Irregular words change just as in the present: 들어요 → **들어야 해요**.',
    note: '**야 돼요** means the same as 야 해요, and both are very common: 가야 돼요 = 가야 해요. For “don’t have to”, Korean says “it’s okay not to”: **안 가도 돼요** = I don’t have to go (more on -아/어도 돼요 later).',
    examples: [
      { ko: '약을 먹어야 해요.', en: 'You have to take your medicine.' },
      { ko: '몇 시까지 가야 돼요?', en: 'What time do I have to be there by?' },
    ],
    questions: [
      {
        id: 'homework',
        ko: '오늘은 숙제를 해야 해요.',
        en: 'Today I have to do my homework.',
        answer: '해야 해요',
        dict: '하다',
        words: ['day:today', 'day:homework', 'day:do'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'getup',
        ko: '내일 아침 일찍 일어나야 돼요.',
        en: 'I have to get up early tomorrow morning.',
        answer: '일어나야 돼요',
        dict: '일어나다',
        words: ['day:tomorrow', 'day:morning', 'day:early', 'day:getup'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'walk',
        ko: '버스가 없어서 걸어야 해요.',
        en: 'There’s no bus, so I have to walk.',
        answer: '걸어야 해요',
        dict: '걷다',
        words: ['directions:bus', 'day:nothave', 'directions:walk'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'song',
        ko: '이 노래 꼭 들어야 해요!',
        en: 'You have to hear this song!',
        answer: '들어야 해요',
        dict: '듣다',
        words: ['hobbies:song', 'hobbies:listen'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'subway',
        ko: '여기서 지하철을 타야 해요.',
        en: 'You have to take the subway from here.',
        answer: '타야 해요',
        dict: '타다',
        words: ['directions:here', 'directions:subway', 'directions:ride'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'getoff',
        ko: '다음 역에서 내려야 돼요.',
        en: 'We have to get off at the next station.',
        answer: '내려야 돼요',
        dict: '내리다',
        words: ['directions:station', 'directions:getoff'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'book',
        ko: '학교에 책을 가져가야 해요.',
        en: 'I have to take my book to school.',
        answer: '가져가야 해요',
        dict: '가져가다',
        words: ['day:school', 'day:book'],
        contrast: ['su', 'ado'],
      },
      {
        id: 'clean',
        ko: '주말에 집을 청소해야 돼요.',
        en: 'I have to clean the house on the weekend.',
        answer: '청소해야 돼요',
        dict: '청소하다',
        words: ['day:weekend', 'day:home', 'day:clean'],
        contrast: ['su', 'ado'],
      },
    ],
  },

  {
    id: 'nikka',
    order: 8,
    level: 3,
    emoji: '💬',
    form: 'nikka',
    title: { ko: '-(으)니까', en: 'because / since' },
    meaning: '“Because / since”: gives a reason. It’s the one to use before a request or a suggestion (…세요, …(으)ㄹ까요?, let’s …).',
    how: 'After a vowel, add **니까**; after a consonant, add **으니까**: 가다 → **가니까**, 먹다 → **먹으니까**. ㄹ drops before ㄴ: 살다 → **사니까**, 멀다 → **머니까**. Irregular: 듣다 → **들으니까**, 춥다 → **추우니까**. For the past, add **으니까** to the past stem: 갔어요 → **갔으니까**.',
    note: 'Both -아서/어서 and -(으)니까 give reasons, and for plain facts -아서/어서 is the usual choice: 피곤해서 일찍 잤어요 = I was tired, so I went to bed early. But before a request or a suggestion, only -(으)니까 works: **늦었으니까** 택시를 탈까요? = We’re late, so shall we take a taxi? (never 늦어서).',
    examples: [
      { ko: '배고프니까 밥 먹으러 가요!', en: 'I’m hungry, so let’s go eat!' },
      { ko: '시간이 없으니까 빨리 가요.', en: 'There’s no time, so let’s hurry.' },
      { ko: '추우니까 따뜻한 옷을 입으세요.', en: 'It’s cold, so wear something warm.' },
    ],
    questions: [
      {
        id: 'rain',
        ko: '지금 비가 오니까 우산을 가져가세요.',
        en: 'It’s raining now, so take an umbrella.',
        answer: '오니까',
        dict: '오다',
        words: ['day:now', 'weather:raining', 'weather:umbrella'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '와서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 오니까.' }],
      },
      {
        id: 'far',
        ko: '역이 머니까 택시를 탈까요?',
        en: 'The station is far, so shall we take a taxi?',
        answer: '머니까',
        dict: '멀다',
        pos: 'adjective',
        words: ['directions:station', 'directions:far', 'directions:taxi', 'directions:ride'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '멀어서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 머니까.' }],
      },
      {
        id: 'coffee',
        ko: '아까 커피를 마셨으니까 지금은 물 주세요.',
        en: 'I had coffee earlier, so just water for me now, please.',
        answer: '마셨으니까',
        dict: '마시다',
        tense: 'past',
        words: ['past:earlier', 'cafe:coffee', 'past:drank', 'cafe:water', 'cafe:please'],
        contrast: ['myeon'],
        traps: [{ text: '마셔서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 마셨으니까.' }],
      },
      {
        id: 'walked',
        ko: '어제 많이 걸었으니까 오늘은 집에서 쉴까요?',
        en: 'We walked a lot yesterday, so shall we rest at home today?',
        answer: '걸었으니까',
        dict: '걷다',
        tense: 'past',
        words: ['day:yesterday', 'past:walked', 'day:today', 'day:rest'],
        contrast: ['myeon'],
        traps: [{ text: '걸어서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 걸었으니까.' }],
      },
      {
        id: 'busy',
        ko: '오늘은 제가 좀 바쁘니까 내일 만날까요?',
        en: 'I’m a bit busy today, so shall we meet tomorrow?',
        answer: '바쁘니까',
        dict: '바쁘다',
        pos: 'adjective',
        words: ['day:today', 'feelings:busy', 'day:tomorrow', 'day:meet'],
        contrast: ['myeon'],
        traps: [{ text: '바빠서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 바쁘니까.' }],
      },
      {
        id: 'clean',
        ko: '어제 청소했으니까 오늘은 안 해도 돼요.',
        en: 'I cleaned yesterday, so I don’t have to today.',
        answer: '청소했으니까',
        dict: '청소하다',
        tense: 'past',
        words: ['day:yesterday', 'day:clean', 'day:today', 'day:do'],
        contrast: ['myeon', 'jiman'],
      },
      {
        id: 'live',
        ko: '저도 거기 사니까 같이 가요!',
        en: 'I live there too, so let’s go together!',
        answer: '사니까',
        dict: '살다',
        words: ['people:me', 'directions:there', 'day:together', 'day:go'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '살아서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 사니까.' }],
      },
      {
        id: 'cake',
        ko: '이 케이크 정말 맛있으니까 먹어 보세요.',
        en: 'This cake is really good, so try some.',
        answer: '맛있으니까',
        dict: '맛있다',
        pos: 'adjective',
        words: ['cafe:cake', 'cafe:delicious', 'day:eat'],
        contrast: ['myeon', 'jiman'],
        traps: [{ text: '맛있어서', why: '-아서/어서 can’t give the reason for a request or suggestion (…세요, …(으)ㄹ까요?). Use -(으)니까: 맛있으니까.' }],
      },
    ],
  },

  {
    id: 'ttae',
    order: 9,
    level: 3,
    emoji: '⏰',
    form: 'ttae',
    title: { ko: '-(으)ㄹ 때', en: 'when' },
    meaning: '“When …”: the time something happens.',
    how: 'After a vowel, put **ㄹ** under the last syllable and add **때**; after a consonant, add **을 때**: 가다 → **갈 때**, 먹다 → **먹을 때**. ㄹ stems just add 때: 살다 → **살 때**. Irregular: 듣다 → **들을 때**, 춥다 → **추울 때**. Adjectives work the same way. For the past, add **을 때** to the past stem: 갔어요 → **갔을 때**.',
    note: 'With 때 it’s always the (으)ㄹ form, even for adjectives: 피곤**할** 때, never 피곤한 때. Nouns take 때 directly: 방학 때 = in the school holidays, 생일 때 = on your birthday.',
    examples: [
      { ko: '한국에 갔을 때 친구를 많이 만났어요.', en: 'When I went to Korea, I met lots of friends.' },
      { ko: '방학 때 뭐 할 거예요?', en: 'What are you going to do in the school holidays?' },
      { ko: '피곤할 때는 일찍 자요.', en: 'When I’m tired, I go to bed early.' },
    ],
    questions: [
      {
        id: 'shower',
        ko: '샤워할 때 노래를 불러요.',
        en: 'I sing when I take a shower.',
        answer: '샤워할 때',
        dict: '샤워하다',
        words: ['day:shower', 'hobbies:song', 'hobbies:sing'],
        contrast: ['gijeone', 'hue'],
      },
      {
        id: 'walk',
        ko: '걸을 때 음악을 들어요.',
        en: 'I listen to music when I walk.',
        answer: '걸을 때',
        dict: '걷다',
        words: ['directions:walk', 'hobbies:music', 'hobbies:listen'],
        contrast: ['gijeone', 'hue'],
      },
      {
        id: 'play',
        ko: '친구하고 놀 때 제일 행복해요.',
        en: 'I’m happiest when I’m hanging out with friends.',
        answer: '놀 때',
        dict: '놀다',
        words: ['day:friend', 'hobbies:play', 'feelings:happy'],
        contrast: ['gijeone', 'hue'],
      },
      {
        id: 'met',
        ko: '처음 만났을 때 정말 떨렸어요.',
        en: 'When we first met, I was really nervous.',
        answer: '만났을 때',
        dict: '만나다',
        tense: 'past',
        words: ['past:met', 'feelings:nervous'],
        contrast: ['gijeone', 'hue'],
        traps: [{ text: '만난 때', why: 'With 때, always use the (으)ㄹ form. For something in the past, add 을 때 to the past stem: 만났을 때.' }],
      },
      {
        id: 'bored',
        ko: '심심할 때 뭐 해요?',
        en: 'What do you do when you’re bored?',
        answer: '심심할 때',
        dict: '심심하다',
        pos: 'adjective',
        words: ['feelings:bored', 'day:what', 'day:do'],
        contrast: ['jiman'],
        traps: [{ text: '심심한 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 심심할 때.' }],
      },
      {
        id: 'cold',
        ko: '추울 때 뜨거운 차를 마셔요.',
        en: 'When it’s cold, I drink hot tea.',
        answer: '추울 때',
        dict: '춥다',
        pos: 'adjective',
        words: ['weather:cold', 'cafe:hot', 'cafe:tea', 'day:drink'],
        contrast: ['jiman'],
        traps: [{ text: '추운 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 추울 때.' }],
      },
      {
        id: 'sad',
        ko: '슬플 때는 울어도 돼요.',
        en: 'It’s okay to cry when you’re sad.',
        answer: '슬플 때',
        dict: '슬프다',
        pos: 'adjective',
        words: ['feelings:sad', 'feelings:cry'],
        contrast: ['jiman'],
        traps: [{ text: '슬픈 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 슬플 때.' }],
      },
      {
        id: 'little',
        ko: '어렸을 때 김치를 안 좋아했어요.',
        en: 'When I was little, I didn’t like kimchi.',
        answer: '어렸을 때',
        dict: '어리다',
        pos: 'adjective',
        tense: 'past',
        words: ['cafe:kimchi', 'feelings:like'],
        contrast: ['jiman', 'nikka'],
        traps: [{ text: '어린 때', why: 'With 때, always use the (으)ㄹ form, even for adjectives: 어릴 때 or 어렸을 때 (both mean “when I was little”).' }],
      },
    ],
  },

  {
    id: 'gijeone',
    order: 10,
    level: 3,
    emoji: '⏪',
    form: 'gijeone',
    title: { ko: '-기 전에', en: 'before' },
    meaning: '“Before …”: what you do before something else.',
    how: 'Put **기 전에** straight onto the stem: 가다 → **가기 전에**, 먹다 → **먹기 전에**, 자다 → **자기 전에**. No 아/어, no 으, and irregular words don’t change: 듣다 → **듣기 전에**.',
    note: 'It never takes the past; the last verb shows the tense: 친구를 **만나기 전에** 선물을 샀어요 = I bought a present before I met my friend. Nouns take 전에 directly: 수업 전에 = before class. After an amount of time, 전에 means “ago”: 한 시간 전에 = an hour ago.',
    examples: [
      { ko: '자기 전에 책을 읽어요.', en: 'I read before bed.' },
      { ko: '수업 전에 커피를 마셔요.', en: 'I have a coffee before class.' },
    ],
    questions: [
      {
        id: 'wash',
        ko: '밥을 먹기 전에 손을 씻어요.',
        en: 'I wash my hands before I eat.',
        answer: '먹기 전에',
        dict: '먹다',
        words: ['day:meal', 'day:eat', 'day:wash'],
        contrast: ['hue'],
      },
      {
        id: 'sleep',
        ko: '어젯밤 자기 전에 샤워했어요.',
        en: 'Last night I took a shower before bed.',
        answer: '자기 전에',
        dict: '자다',
        words: ['past:lastnight', 'day:sleep', 'day:shower'],
        contrast: ['hue'],
      },
      {
        id: 'movie',
        ko: '영화 보기 전에 밥 먹을까요?',
        en: 'Shall we eat before the movie?',
        answer: '보기 전에',
        dict: '보다',
        words: ['day:movie', 'day:watch', 'day:meal', 'day:eat'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'friend',
        ko: '친구가 오기 전에 청소해야 해요.',
        en: 'I have to clean before my friend comes.',
        answer: '오기 전에',
        dict: '오다',
        words: ['day:friend', 'day:come', 'day:clean'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'korea',
        ko: '한국에 가기 전에 한국어를 배우고 싶어요.',
        en: 'I want to learn Korean before I go to Korea.',
        answer: '가기 전에',
        dict: '가다',
        words: ['day:go', 'day:korean', 'hobbies:wanttolearn'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'tryon',
        ko: '사기 전에 입어 보세요.',
        en: 'Try it on before you buy it.',
        answer: '사기 전에',
        dict: '사다',
        words: ['shopping:buy', 'shopping:wear'],
        contrast: ['hue'],
      },
      {
        id: 'exercise',
        ko: '운동하기 전에 물을 마셔요.',
        en: 'I drink some water before I work out.',
        answer: '운동하기 전에',
        dict: '운동하다',
        words: ['day:exercise', 'cafe:water', 'day:drink'],
        contrast: ['hue', 'ttae'],
      },
      {
        id: 'cross',
        ko: '길을 건너기 전에 왼쪽을 보세요.',
        en: 'Look left before you cross the road.',
        answer: '건너기 전에',
        dict: '건너다',
        words: ['directions:road', 'directions:cross', 'directions:left', 'day:watch'],
        contrast: ['hue'],
      },
    ],
  },

  {
    id: 'hue',
    order: 11,
    level: 3,
    emoji: '⏩',
    form: 'hue',
    title: { ko: '-(으)ㄴ 후에', en: 'after' },
    meaning: '“After …”: first one thing, then the other.',
    how: 'After a vowel, put **ㄴ** under the last syllable; after a consonant, add **은**; then add **후에**: 가다 → **간 후에**, 먹다 → **먹은 후에**. ㄹ stems drop the ㄹ: 살다 → **산 후에**, 만들다 → **만든 후에**. Irregular: 듣다 → **들은 후에**.',
    note: '**-(으)ㄴ 다음에** means the same: 먹은 다음에 = 먹은 후에. Nouns take 후에 directly: 수업 후에 = after class. Only the last verb shows the tense.',
    examples: [
      { ko: '수업 후에 뭐 해요?', en: 'What are you doing after class?' },
      { ko: '숙제를 한 다음에 게임을 해요.', en: 'I play games after I do my homework.' },
    ],
    questions: [
      {
        id: 'movie',
        ko: '영화를 본 후에 카페에 갔어요.',
        en: 'After the movie, we went to a café.',
        answer: '본 후에',
        dict: '보다',
        words: ['day:movie', 'day:watch', 'cafe:cafe', 'past:went'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'cake',
        ko: '케이크를 만든 후에 사진을 찍었어요.',
        en: 'After I made the cake, I took a photo of it.',
        answer: '만든 후에',
        dict: '만들다',
        words: ['cafe:cake', 'past:made', 'hobbies:photo', 'hobbies:take'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'play',
        ko: '친구하고 논 후에 집에 왔어요.',
        en: 'After hanging out with a friend, I came home.',
        answer: '논 후에',
        dict: '놀다',
        words: ['day:friend', 'hobbies:play', 'day:home', 'past:came'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'class',
        ko: '수업을 들은 후에 도서관에 가요.',
        en: 'After class, I go to the library.',
        answer: '들은 후에',
        dict: '듣다',
        words: ['hobbies:listen', 'day:library', 'day:go'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'walk',
        ko: '많이 걸은 후에 좀 쉬었어요.',
        en: 'After walking a lot, I rested for a bit.',
        answer: '걸은 후에',
        dict: '걷다',
        words: ['directions:walk', 'past:rested'],
        contrast: ['gijeone'],
      },
      {
        id: 'exercise',
        ko: '운동한 후에 샤워해요.',
        en: 'I shower after I work out.',
        answer: '운동한 후에',
        dict: '운동하다',
        words: ['day:exercise', 'day:shower'],
        contrast: ['gijeone'],
      },
      {
        id: 'lunch',
        ko: '점심을 먹은 후에 커피를 마셔요.',
        en: 'I have coffee after lunch.',
        answer: '먹은 후에',
        dict: '먹다',
        words: ['day:lunch', 'day:eat', 'cafe:coffee', 'day:drink'],
        contrast: ['gijeone', 'ttae'],
      },
      {
        id: 'getoff',
        ko: '버스에서 내린 후에 오른쪽으로 가세요.',
        en: 'After you get off the bus, go right.',
        answer: '내린 후에',
        dict: '내리다',
        words: ['directions:bus', 'directions:getoff', 'directions:right', 'day:go'],
        contrast: ['gijeone'],
      },
    ],
  },

  {
    id: 'ado',
    order: 12,
    level: 3,
    emoji: '👌',
    form: 'ado',
    title: { ko: '-아/어도 돼요', en: 'may / it’s okay to' },
    meaning: '“May / it’s okay to”: asks for or gives permission. With ? it asks: **먹어도 돼요?** = May I eat it?',
    how: 'Take the 아/어 form (the present without 요) and add **도 돼요**: 가요 → **가도 돼요**, 먹어요 → **먹어도 돼요**, 해요 → **해도 돼요**, 앉아요 → **앉아도 돼요**.',
    note: 'To say no: **아니요, 안 돼요.** You can also say **괜찮아요** instead of 돼요: 먹어도 괜찮아요? With 안 in front, it means “don’t have to”: 내일은 **안 와도 돼요** = You don’t have to come tomorrow.',
    examples: [
      { ko: '창문 좀 열어도 돼요? — 네, 열어도 돼요.', en: 'May I open the window? — Yes, go ahead.' },
      { ko: '이거 먹어 봐도 돼요?', en: 'May I try this?' },
    ],
    questions: [
      {
        id: 'seat',
        ko: '이 자리에 앉아도 괜찮아요?',
        en: 'Is it okay if I sit in this seat?',
        answer: '앉아도 괜찮아요',
        dict: '앉다',
        words: ['cafe:seat', 'cafe:okay'],
        contrast: ['aya'],
        traps: [
          { text: '앉어도 괜찮아요', why: '앉다 → 앉 + 아요: the last vowel is ㅏ, so it takes 아. So: 앉아도 괜찮아요.' },
          { text: '앉도 괜찮아요', why: 'After a consonant, the 아/어 can’t be left out: 앉아도 괜찮아요.' },
        ],
      },
      {
        id: 'photo',
        ko: '여기서 사진을 찍어도 돼요?',
        en: 'May I take pictures here?',
        answer: '찍어도 돼요',
        dict: '찍다',
        words: ['directions:here', 'hobbies:photo', 'hobbies:take'],
        contrast: ['aya'],
      },
      {
        id: 'eat',
        ko: '네, 다 먹어도 돼요.',
        en: 'Yes, you can eat all of it.',
        answer: '먹어도 돼요',
        dict: '먹다',
        words: ['cafe:yes', 'day:eat'],
        contrast: ['aya'],
      },
      {
        id: 'music',
        ko: '공부할 때 음악을 들어도 돼요?',
        en: 'Is it okay to listen to music while I study?',
        answer: '들어도 돼요',
        dict: '듣다',
        words: ['day:study', 'hobbies:music', 'hobbies:listen'],
        contrast: ['aya'],
        traps: [{ text: '들어도 해요', why: '“May” is -아/어도 돼요, not 해요 (해요 goes with -아/어야: “have to”). So: 들어도 돼요.' }],
      },
      {
        id: 'late',
        ko: '내일 좀 늦게 와도 돼요?',
        en: 'Is it okay if I come a bit late tomorrow?',
        answer: '와도 돼요',
        dict: '오다',
        words: ['day:tomorrow', 'day:come'],
        contrast: ['aya'],
      },
      {
        id: 'card',
        ko: '카드로 계산해도 돼요?',
        en: 'Can I pay by card?',
        answer: '계산해도 돼요',
        dict: '계산하다',
        words: ['shopping:card', 'cafe:bill'],
        contrast: ['aya'],
        traps: [{ text: '계산해도 되요', why: '되요 is a common misspelling: 되 + 어요 → 돼요. So: 계산해도 돼요.' }],
      },
      {
        id: 'go',
        ko: '네, 지금 가도 돼요.',
        en: 'Yes, you can go now.',
        answer: '가도 돼요',
        dict: '가다',
        words: ['cafe:yes', 'day:now', 'day:go'],
        contrast: ['aya'],
        traps: [{ text: '가도 해요', why: '“May” is -아/어도 돼요, not 해요 (해요 goes with -아/어야: “have to”). So: 가도 돼요.' }],
      },
      {
        id: 'play',
        ko: '엄마, 친구하고 놀아도 돼요?',
        en: 'Mom, can I play with my friend?',
        answer: '놀아도 돼요',
        dict: '놀다',
        words: ['people:mom', 'day:friend', 'hobbies:play'],
        contrast: ['aya'],
      },
    ],
  },
]);
