/**
 * Topic: 병원과 약국 · At the doctor’s — saying what hurts, and buying medicine.
 * Body parts, symptoms, the doctor’s and the pharmacist’s questions, advice,
 * getting hurt and getting better. Verbs and adjectives are in the polite 해요
 * form with the dictionary form alongside (다쳤어요 is taught in the past, with
 * form: 'past'); set phrases like 열이 나요 (“I have a fever”) are pos 'phrase'.
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'health',
  order: 12,
  emoji: '💊',
  color: 'mint',
  title: { ko: '병원과 약국', en: 'At the doctor’s' },
  description: { ko: '아픈 곳 말하기 · 약 사기', en: 'Say what hurts, buy medicine' },

  notes: [
    {
      title: { ko: '어디가 아프세요?', en: 'Saying what hurts' },
      text: 'The doctor asks **어디가 아프세요?** (Where does it hurt?). Answer with the body part + **이/가**, then **아파요**: **머리가 아파요** (I have a headache), **배가 아파요** (a stomach ache), **목이 아파요** (a sore throat). Keep -세요 for other people: about yourself, it’s just 아파요. The next question is often **언제부터 아팠어요?** (Since when?): **부터** means “from, since”.',
      examples: [
        { ko: '어디가 아프세요? — 머리가 아파요.', en: 'Where does it hurt? — I have a headache.' },
        { ko: '언제부터 아팠어요? — 어제부터요.', en: 'How long has it hurt? — Since yesterday.' },
        { ko: '목이 너무 아파요.', en: 'I have a really sore throat.' },
      ],
    },
    {
      title: { ko: '열이 나요', en: 'Symptoms that “come out”' },
      text: 'A fever, a runny nose and blood all “come out” in Korean, with **나다**: **열이 나요** (I have a fever), **콧물이 나요** (my nose is running), **피가 나요** (it’s bleeding). A cough can come out too (**기침이 나요**), or you “do” it: **기침을 해요**. And you get “caught” by a cold: **감기에 걸렸어요** (I’ve caught a cold).',
      examples: [
        { ko: '어젯밤부터 열이 나요.', en: 'I’ve had a fever since last night.' },
        { ko: '감기에 걸렸어요. 콧물이 나요.', en: 'I’ve caught a cold. My nose is running.' },
        { ko: '괜찮아요? 피가 나요!', en: 'Are you okay? You’re bleeding!' },
      ],
    },
    {
      title: { ko: '하루에 세 번', en: 'At the pharmacy' },
      text: 'Medicine is “eaten” in Korean: **약을 먹어요** (I take medicine). The pharmacist tells you how often and when: **하루에 세 번** (three times a day, with a native number before 번) and **식후 삼십 분** (30 minutes after meals, with a Sino-Korean number before 분). **드세요** is the polite “please have it”, for both 먹다 and 마시다. About yourself, you still say 약을 먹어요.',
      examples: [
        { ko: '감기약 좀 주세요.', en: 'Some cold medicine, please.' },
        { ko: '하루에 세 번 드세요.', en: 'Take it three times a day.' },
        { ko: '식후 삼십 분에 드세요.', en: 'Take it 30 minutes after meals.' },
      ],
    },
    {
      title: { ko: '다쳤어요 · 나았어요', en: 'Getting hurt, getting better' },
      text: 'Give advice with -(으)세요: **푹 쉬세요** (get plenty of rest), **물을 많이 드세요** (drink lots of water). Say you got hurt in the past tense, with the body part as the object: **다리를 다쳤어요** (I hurt my leg). **낫다** (to get better) is ㅅ-irregular: the ㅅ drops before a vowel, so 나아요, **나았어요** (I got better) and **빨리 나으세요!** (Get well soon!).',
      examples: [
        { ko: '집에서 푹 쉬세요.', en: 'Get plenty of rest at home.' },
        { ko: '어제 다리를 다쳤어요.', en: 'I hurt my leg yesterday.' },
        { ko: '빨리 나으세요!', en: 'Get well soon!' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'medicine', ko: '약', en: 'medicine', level: 1, pos: 'noun', emoji: '💊', rom: 'yak',
      enAlt: ['medication', 'meds', 'pills', 'pill'],
      note: 'You “eat” medicine in Korean: 약을 먹어요 = I take medicine. It’s the 약 in 약국 (pharmacy) and 감기약 (cold medicine).',
      example: { ko: '약 먹었어요?', en: 'Have you taken your medicine?' } },
    { id: 'head', ko: '머리', en: 'head', level: 1, pos: 'noun', emoji: '💆', rom: 'meori', enAlt: ['hair'],
      note: '머리가 아파요 = I have a headache. 머리 also means “hair”: 머리를 잘랐어요 = I got a haircut.',
      example: { ko: '머리가 아파요. 약 있어요?', en: 'I have a headache. Do you have any medicine?' } },
    { id: 'stomach', ko: '배', en: 'stomach / belly', level: 1, pos: 'noun', emoji: '🤢', rom: 'bae',
      enAlt: ['tummy', 'abdomen'],
      note: '배가 아파요 = I have a stomach ache. It’s the 배 in 배고파요 (I’m hungry) and 배불러요 (I’m full). 배 also means “pear” and “boat”!',
      example: { ko: '배가 아파요? 괜찮아요?', en: 'Does your stomach hurt? Are you okay?' } },
    { id: 'throat', ko: '목', en: 'throat / neck', level: 1, pos: 'noun', emoji: '🧣', rom: 'mok',
      note: '목 is both the throat and the neck, so 목이 아파요 is a sore throat (or a stiff neck). It’s the 목 in 목말라요 (I’m thirsty).',
      example: { ko: '목이 아파요. 따뜻한 물 주세요.', en: 'My throat hurts. Some warm water, please.' } },
    { id: 'hand', ko: '손', en: 'hand', level: 1, pos: 'noun', emoji: '🤚', rom: 'son', enAlt: ['hands'],
      note: 'A finger is 손가락: 가락 is a long, thin piece, as in 숟가락 (spoon) and 젓가락 (chopsticks).',
      example: { ko: '손 씻었어요?', en: 'Did you wash your hands?' } },
    { id: 'foot', ko: '발', en: 'foot', level: 1, pos: 'noun', emoji: '🦶', rom: 'bal', enAlt: ['feet'],
      note: 'It’s the 발 in 신발 (shoes). A toe is 발가락, and the ankle is 발목 (foot + neck).',
      example: { ko: '신발이 작아요. 발이 아파요.', en: 'These shoes are too small. My feet hurt.' } },
    { id: 'leg', ko: '다리', en: 'leg', level: 1, pos: 'noun', emoji: '🦵', rom: 'dari', enAlt: ['legs'],
      note: '다리 also means “bridge”: context tells you which.',
      example: { ko: '다리가 정말 길어요!', en: 'Your legs are so long!' } },
    { id: 'arm', ko: '팔', en: 'arm', level: 1, pos: 'noun', emoji: '💪', rom: 'pal', enAlt: ['arms'],
      note: '팔 is also “eight” in Sino-Korean numbers (칠, 팔, 구): context tells you which.',
      example: { ko: '팔이 아파요. 가방이 너무 무거워요.', en: 'My arm hurts. The bag is so heavy.' } },
    { id: 'nose', ko: '코', en: 'nose', level: 1, pos: 'noun', emoji: '👃', rom: 'ko',
      note: 'A blocked nose: 코가 막혔어요. A runny nose: 콧물이 나요 (콧물 = 코 + 물, “nose water”).',
      example: { ko: '코가 막혔어요.', en: 'My nose is blocked.' } },
    { id: 'body', ko: '몸', en: 'body', level: 1, pos: 'noun', emoji: '🧘', rom: 'mom',
      note: '몸이 안 좋아요 (my body isn’t good) = I don’t feel well. 몸에 좋아요 = it’s good for you.',
      example: { ko: '물은 몸에 좋아요.', en: 'Water is good for you.' } },
    { id: 'toothache', ko: '이가 아파요', en: 'I have a toothache', level: 1, pos: 'phrase', emoji: '🦷', rom: 'iga apayo',
      dict: '아프다', accept: ['이 아파요', '이빨이 아파요'], avoid: ['feelings:hurts'],
      enAlt: ['toothache', 'have a toothache', 'my tooth hurts', 'my teeth hurt', 'tooth hurts'],
      note: '이 means “tooth” here (it sounds just like 이, “two”). In casual speech you’ll also hear 이빨: 이빨이 아파요.',
      example: { ko: '밤에 이가 너무 아파요.', en: 'My tooth hurts so much at night.' } },
    { id: 'fever', ko: '열이 나요', en: 'I have a fever', level: 1, pos: 'phrase', emoji: '🤒', rom: 'yeori nayo',
      pron: '여리 나요', dict: '나다', accept: ['열 나요', '열이 있어요'],
      enAlt: ['fever', 'have a fever', "i've got a fever", 'i have a temperature', 'have a temperature', 'feverish'],
      note: 'Literally “heat comes out” (나다 = come out). The ㄹ slides over: [여리 나요]. A high fever is 열이 많이 나요.',
      example: { ko: '열이 나요? 병원에 가요!', en: 'You have a fever? Let’s go to the doctor’s!' } },

    // ---- Level 2 ----
    { id: 'cough', ko: '기침', en: 'cough', level: 2, pos: 'noun', emoji: '🫁', rom: 'gichim', enAlt: ['a cough', 'coughing'],
      note: 'A cough “comes out” (기침이 나요), or you “do” it (기침을 해요). Both mean “I have a cough”.',
      example: { ko: '밤에 기침을 많이 해요.', en: 'I cough a lot at night.' } },
    { id: 'runnynose', ko: '콧물', en: 'runny nose', level: 2, pos: 'noun', emoji: '👃💧', rom: 'konmul', pron: '콘물',
      enAlt: ['a runny nose', 'snot', 'nasal mucus'],
      note: '코 (nose) + 물 (water), with an ㅅ in between, said [콘물]. My nose is running: 콧물이 나요.',
      example: { ko: '휴지 있어요? 콧물이 나요.', en: 'Do you have a tissue? My nose is running.' } },
    { id: 'coldmedicine', ko: '감기약', en: 'cold medicine', level: 2, pos: 'noun', emoji: '🤧💊', rom: 'gamgiyak',
      enAlt: ['cold medication', 'cold pills', 'cold remedy'],
      note: '감기 (a cold) + 약 (medicine). Pills for a headache are 두통약.',
      example: { ko: '감기약 먹고 잤어요.', en: 'I took some cold medicine and went to bed.' } },
    { id: 'wherehurt', ko: '어디가 아프세요?', en: 'where does it hurt?', level: 2, pos: 'phrase', emoji: '🩺',
      rom: 'eodiga apeuseyo', dict: '아프다', accept: ['어디가 아파요?', '어디 아프세요?'],
      enAlt: ['where does it hurt', "what's wrong", 'what seems to be the problem', 'where are you sick', 'where is the pain'],
      note: 'The doctor’s first question, with the polite -(으)세요. Answer about yourself without -세요: 배가 아파요.',
      example: { ko: '어디가 아프세요? — 목이 아파요.', en: 'Where does it hurt? — My throat hurts.' } },
    { id: 'rest', ko: '푹 쉬세요', en: 'get plenty of rest', level: 2, pos: 'phrase', emoji: '🛋️', rom: 'puk swiseyo',
      pron: '푹 쒸세요', dict: '쉬다', accept: ['푹 쉬어요'],
      enAlt: ['get some rest', 'rest well', 'have a good rest', 'get a good rest', 'rest up'],
      note: '푹 means “deeply, well” (푹 자요 = I sleep soundly), and 쉬세요 is “please rest”, from 쉬다. After 푹, the ㅅ is said tense: [푹 쒸세요].',
      example: { ko: '감기예요? 집에서 푹 쉬세요.', en: 'Is it a cold? Get plenty of rest at home.' } },
    { id: 'hurt', ko: '다쳤어요', en: 'got hurt / injured', level: 2, pos: 'verb', emoji: '🩼', rom: 'dachyeosseoyo',
      pron: '다처써요', dict: '다치다', form: 'past',
      enAlt: ['hurt', 'injured', 'got injured', 'was injured', 'i got hurt', 'hurt myself', 'i hurt myself', "i'm hurt"],
      note: 'The past of 다치다 (to get hurt). The body part takes 을/를: 다리를 다쳤어요 = I hurt my leg. (With 아파요, it takes 이/가: 다리가 아파요.)',
      example: { ko: '괜찮아요? 어디 다쳤어요?', en: 'Are you okay? Are you hurt anywhere?' } },
    { id: 'dentist', ko: '치과', en: 'dentist (clinic)', level: 2, pos: 'noun', emoji: '🪥', rom: 'chigwa', pron: '치꽈',
      enAlt: ["dentist's", 'dental clinic', "dentist's office", 'dentist office'],
      note: '치 (teeth) + 과 (department). Other clinics end in 과 too: 내과 (internal medicine: where you go with a cold), 안과 (eyes). Said [치꽈].',
      example: { ko: '내일 치과에 가요.', en: 'I’m going to the dentist tomorrow.' } },
    { id: 'day', ko: '하루', en: 'a day / one day', level: 2, pos: 'noun', emoji: '☀️🌙', rom: 'haru',
      enAlt: ['day', 'one whole day'],
      note: '하루에 세 번 = three times a day (에 = per). 하루 종일 = all day long.',
      example: { ko: '하루에 커피를 세 잔 마셔요.', en: 'I drink three cups of coffee a day.' } },
    { id: 'blood', ko: '피', en: 'blood', level: 2, pos: 'noun', emoji: '🩸', rom: 'pi',
      note: 'Blood “comes out” in Korean: 피가 나요 = it’s bleeding. A nosebleed is 코피 (코 + 피).',
      example: { ko: '손에서 피가 나요.', en: 'My hand is bleeding.' } },
    { id: 'healthy', ko: '건강해요', en: 'healthy', level: 2, pos: 'adjective', emoji: '🥗', rom: 'geonganghaeyo',
      dict: '건강하다', enAlt: ["i'm healthy", 'is healthy', 'in good health'],
      note: '건강 (health) + 하다. 건강하세요! (Stay healthy!) is a warm goodbye or New Year’s wish. Good for your health: 건강에 좋아요.',
      example: { ko: '걱정 마세요. 저는 건강해요!', en: 'Don’t worry. I’m healthy!' } },
    { id: 'getbetter', ko: '나아요', en: 'get better / heal', level: 2, pos: 'verb', emoji: '📈', rom: 'naayo', dict: '낫다',
      avoid: ['getwell'], enAlt: ['gets better', 'heals', 'recover', 'get well'],
      note: '낫다 is ㅅ-irregular: before a vowel, the ㅅ drops → 나아요, 나았어요 (got better), 빨리 나으세요 (get well soon).',
      example: { ko: '감기가 안 나아요.', en: 'My cold isn’t getting better.' } },
    { id: 'bandage', ko: '밴드', en: 'plaster / Band-Aid', level: 2, pos: 'noun', emoji: '🩹', rom: 'baendeu',
      accept: ['반창고', '일회용 밴드'], enAlt: ['bandaid', 'band aid', 'adhesive bandage', 'bandage', 'sticking plaster'],
      note: 'Short for 일회용 밴드 (a disposable plaster). The standard word is 반창고. 밴드 is also a (music) band!',
      example: { ko: '손에 밴드를 붙였어요.', en: 'I put a plaster on my hand.' } },
    { id: 'pleasehave', ko: '드세요', en: 'please have (eat, drink)', level: 2, pos: 'phrase', emoji: '🫴', rom: 'deuseyo',
      dict: '드시다', enAlt: ['please eat', 'please drink', 'please take', 'please have some', 'have some', 'help yourself'],
      note: 'The polite way to tell someone to eat or drink: 먹다 and 마시다 both become 드세요. About yourself, you still say 먹어요 or 마셔요. The pharmacist says 하루에 세 번 드세요.',
      example: { ko: '이 약은 밥 먹고 드세요.', en: 'Take this medicine after you eat.' } },

    // ---- Level 3 ----
    { id: 'shot', ko: '주사', en: 'injection / shot', level: 3, pos: 'noun', emoji: '💉', rom: 'jusa', enAlt: ['jab'],
      note: 'In Korean you’re “hit” by a shot: 주사를 맞아요 (맞다 = be hit). The nurse may say 조금 따끔해요 (it’ll sting a little).',
      example: { ko: '주사 맞았어요? 안 아팠어요?', en: 'Did you get a shot? Didn’t it hurt?' } },
    { id: 'prescription', ko: '처방전', en: 'prescription', level: 3, pos: 'noun', emoji: '📃', rom: 'cheobangjeon',
      note: 'The doctor gives you a 처방전, and you take it to a 약국. In Korea there’s usually a pharmacy right next to the clinic, or downstairs.',
      example: { ko: '처방전 여기 있어요.', en: 'Here’s my prescription.' } },
    { id: 'aftermeals', ko: '식후', en: 'after meals', level: 3, pos: 'noun', emoji: '🍚⏱️', rom: 'sikhu', pron: '시쿠',
      enAlt: ['after a meal', 'after eating', 'after food'],
      note: '식 (meal) + 후 (after); before meals is 식전. Medicine bags say 식후 30분: 30 minutes after a meal.',
      example: { ko: '커피는 식후에 마셔요.', en: 'I have my coffee after meals.' } },
    { id: 'dizzy', ko: '어지러워요', en: "I'm dizzy", level: 3, pos: 'adjective', emoji: '😵', rom: 'eojireowoyo', dict: '어지럽다',
      enAlt: ['dizzy', 'i feel dizzy', 'lightheaded', 'light-headed'],
      note: 'ㅂ-irregular: 어지럽 + 어요 → 어지러워요. It can also describe a messy room: 방이 어지러워요.',
      example: { ko: '갑자기 어지러워요.', en: 'I suddenly feel dizzy.' } },
    { id: 'liedown', ko: '누워요', en: 'lie down', level: 3, pos: 'verb', emoji: '🛌', rom: 'nuwoyo', dict: '눕다',
      enAlt: ['lie', 'lay down', 'lying down'],
      note: 'ㅂ-irregular: 눕 + 어요 → 누워요. At the doctor’s: 여기 누우세요 (please lie down here).',
      example: { ko: '침대에 누워서 쉬어요.', en: 'I lie in bed and rest.' } },
    { id: 'back', ko: '허리', en: 'lower back / waist', level: 3, pos: 'noun', emoji: '🙇', rom: 'heori',
      avoid: ['directions:behind'], enAlt: ['back', 'waist'],
      note: '허리가 아파요 = my back hurts (the lower back). It’s also the waist, as in 허리 사이즈 (waist size).',
      example: { ko: '허리가 좀 아파요.', en: 'My back hurts a bit.' } },
    { id: 'painkiller', ko: '진통제', en: 'painkiller', level: 3, pos: 'noun', emoji: '🤕💊', rom: 'jintongje',
      avoid: ['medicine'], enAlt: ['painkillers', 'pain reliever', 'pain relief', 'pain medicine', 'pain pills'],
      note: '진통 (easing pain) + 제 (a medicine). For a headache you can also ask for 두통약.',
      example: { ko: '진통제 먹었어요. 이제 괜찮아요.', en: 'I took a painkiller. I’m fine now.' } },
    { id: 'apply', ko: '발라요', en: 'apply / put on (cream)', level: 3, pos: 'verb', emoji: '🧴', rom: 'ballayo', dict: '바르다',
      enAlt: ['put on cream', 'rub on', 'spread on', 'apply cream', 'put cream on'],
      note: '르-irregular: 바르 + 아요 → 발라요. It’s for anything you spread on: 약을 발라요 (ointment), 선크림을 발라요 (sunscreen).',
      example: { ko: '손에 크림을 발라요.', en: 'I put cream on my hands.' } },
    { id: 'allergy', ko: '알레르기', en: 'allergy', level: 3, pos: 'noun', emoji: '🥜', rom: 'allereugi', accept: ['알러지'],
      enAlt: ['allergies', 'allergic'],
      note: 'From German “Allergie”, so it doesn’t sound like the English word. I’m allergic to milk: 우유 알레르기가 있어요.',
      example: { ko: '알레르기 있어요?', en: 'Do you have any allergies?' } },
    { id: 'getwell', ko: '빨리 나으세요', en: 'get well soon', level: 3, pos: 'phrase', emoji: '💐', rom: 'ppalli naeuseyo',
      dict: '낫다', avoid: ['getbetter'], accept: ['빨리 나아요'],
      enAlt: ['get better soon', 'feel better soon', 'feel better', 'hope you feel better'],
      note: '빨리 (quickly) + 나으세요 (please get better): what you say to someone who’s ill. 낫다 is ㅅ-irregular: 낫 + 으세요 → 나으세요.',
      example: { ko: '감기 걸렸어요? 빨리 나으세요!', en: 'You’ve caught a cold? Get well soon!' } },
    { id: 'symptom', ko: '증상', en: 'symptom', level: 3, pos: 'noun', emoji: '🌡️', rom: 'jeungsang', enAlt: ['symptoms'],
      note: 'Answer with what you feel: 열이 나요, 기침을 해요. Cold symptoms are 감기 증상.',
      example: { ko: '어떤 증상이 있으세요?', en: 'What symptoms do you have?' } },

    // ---- More words ----
    { id: 'ear', ko: '귀', en: 'ear', level: 1, pos: 'noun', emoji: '👂', rom: 'gwi', enAlt: ['ears'],
      note: '귀가 아파요 = I have an earache. Earrings are 귀걸이: “something hung on the ear”.',
      example: { ko: '왼쪽 귀가 아파요.', en: 'My left ear hurts.' } },
    { id: 'face', ko: '얼굴', en: 'face', level: 1, pos: 'noun', emoji: '☺️', rom: 'eolgul', enAlt: ['faces'],
      note: '얼굴이 안 좋아요 (“your face isn’t good”) means “you don’t look well”. And in Korea, 얼굴이 작아요 (you have a small face) is a compliment!',
      example: { ko: '얼굴이 안 좋아요. 피곤해요?', en: 'You don’t look well. Are you tired?' } },
    { id: 'shoulder', ko: '어깨', en: 'shoulder', level: 1, pos: 'noun', emoji: '🤷‍♀️', rom: 'eokkae', enAlt: ['shoulders'],
      note: 'Stiff shoulders from sitting at a desk all day: 어깨가 뭉쳤어요 (my shoulders are all knotted up).',
      example: { ko: '어깨가 좀 아파요.', en: 'My shoulder hurts a bit.' } },
    { id: 'areyouok', ko: '괜찮으세요?', en: 'are you all right?', level: 1, pos: 'phrase', emoji: '❤️‍🩹', rom: 'gwaenchaneuseyo',
      pron: '괜차느세요', dict: '괜찮다', avoid: ['cafe:okay'],
      enAlt: ['are you okay', 'are you ok', 'are you alright', 'you okay', 'is everything okay'],
      note: 'The polite way to ask if someone is all right: 괜찮 + 으세요. Answer about yourself without -세요: 네, 괜찮아요. The ㅎ is silent: [괜차느세요].',
      example: { ko: '괜찮으세요? 많이 아프세요?', en: 'Are you all right? Does it hurt a lot?' } },
    { id: 'nurse', ko: '간호사', en: 'nurse', level: 2, pos: 'noun', emoji: '👩‍⚕️', rom: 'ganhosa', enAlt: ['nurses'],
      note: '간호 (nursing) + 사 (a professional), like 의사 (doctor) and 약사 (pharmacist). At the hospital, call a nurse 간호사님.',
      example: { ko: '제 동생은 간호사예요.', en: 'My younger sibling is a nurse.' } },
    { id: 'caughtcold', ko: '감기에 걸렸어요', en: "I've caught a cold", level: 2, pos: 'phrase', emoji: '🦠',
      rom: 'gamgie geollyeosseoyo', pron: '감기에 걸려써요', dict: '걸리다', form: 'past', accept: ['감기 걸렸어요'],
      avoid: ['weather:acold'], enAlt: ['caught a cold', 'i caught a cold', 'i have a cold', "i've got a cold", 'got a cold', 'have a cold'],
      note: 'You get “caught” by a cold: 감기 + 에, then 걸렸어요, the past of 걸리다. In speech the 에 is often dropped: 감기 걸렸어요.',
      example: { ko: '감기에 걸렸어요? 약 먹었어요?', en: 'You’ve caught a cold? Have you taken any medicine?' } },
    { id: 'fell', ko: '넘어졌어요', en: 'fell over', level: 2, pos: 'verb', emoji: '🧎', rom: 'neomeojyeosseoyo',
      pron: '너머저써요', dict: '넘어지다', form: 'past',
      enAlt: ['fell', 'fell down', 'i fell', 'i fell over', 'i fell down', 'tripped', 'tripped and fell', 'took a fall'],
      note: 'The past of 넘어지다 (to fall over, trip). For things dropping from a height, use 떨어졌어요. 져 is said like 저: [너머저써요].',
      example: { ko: '넘어졌어요? 괜찮아요?', en: 'Did you fall? Are you okay?' } },
    { id: 'stickon', ko: '붙여요', en: 'stick on / attach', level: 2, pos: 'verb', emoji: '🧷', rom: 'buchyeoyo', pron: '부처요',
      dict: '붙이다', avoid: ['apply'], enAlt: ['stick', 'attach', 'stick on', 'put on a plaster', 'stick on a plaster'],
      note: '붙이 + 어요 → 붙여요 (ㅣ + ㅓ merge into ㅕ). ㅌ before ㅣ sounds like ㅊ (as in 같이 [가치]): 붙이다 is said [부치다], and 붙여요 [부처요] (쳐 is said like 처). It’s for plasters, patches and stickers.',
      example: { ko: '다리에 밴드를 붙여요.', en: 'I put a plaster on my leg.' } },
    { id: 'ankle', ko: '발목', en: 'ankle', level: 2, pos: 'noun', emoji: '🩰', rom: 'balmok', enAlt: ['ankles'],
      note: '발 (foot) + 목 (neck): the foot’s “neck”. The wrist is 손목 (hand + neck).',
      example: { ko: '발목이 많이 아파요?', en: 'Does your ankle hurt a lot?' } },
    { id: 'severe', ko: '심해요', en: "it's severe / bad", level: 3, pos: 'adjective', emoji: '‼️', rom: 'simhaeyo', dict: '심하다',
      enAlt: ['severe', 'serious', "it's serious", 'bad', 'really bad', 'is severe', 'is serious', 'too much', "it's too much"],
      note: 'It says how bad something is: 기침이 심해요 = I have a bad cough. About someone’s words or behaviour, 너무 심해요! means “That’s going too far!”',
      example: { ko: '감기가 좀 심해요.', en: 'My cold is pretty bad.' } },
    { id: 'swollen', ko: '부었어요', en: "it's swollen", level: 3, pos: 'verb', emoji: '🐡', rom: 'bueosseoyo', pron: '부어써요',
      dict: '붓다', form: 'past',
      enAlt: ['swollen', 'is swollen', 'swelled', 'swelled up', 'it swelled up', 'swollen up', 'puffy', "it's puffy"],
      note: 'The past of 붓다 (to swell), for how it is now: 발목이 부었어요 = my ankle is swollen. ㅅ-irregular: the ㅅ drops before a vowel (부어요, 부었어요), but stays before a consonant: 붓고.',
      example: { ko: '아침에 얼굴이 부었어요.', en: 'My face is puffy this morning.' } },
    { id: 'indigestion', ko: '체했어요', en: 'I have indigestion', level: 3, pos: 'verb', emoji: '🍙😣', rom: 'chehaesseoyo',
      pron: '체해써요', dict: '체하다', form: 'past',
      enAlt: ['indigestion', 'have indigestion', 'got indigestion', 'i got indigestion', 'upset stomach', 'i have an upset stomach'],
      note: 'Food has “got stuck” and sits heavy, often after eating too fast: a very common complaint in Korea. Like 다쳤어요, you say it in the past.',
      example: { ko: '밥을 너무 빨리 먹었어요. 체했어요.', en: 'I ate too fast. Now I have indigestion.' } },
    { id: 'digestive', ko: '소화제', en: 'digestive medicine', level: 3, pos: 'noun', emoji: '🍽️💊', rom: 'sohwaje',
      enAlt: ['digestive', 'digestive aid', 'digestive pills', 'indigestion medicine', 'antacid', 'antacids'],
      note: '소화 (digestion) + 제 (a medicine), like 진통제 (painkiller). For 체했어요, ask for it at any 약국: no prescription needed.',
      example: { ko: '약국에서 소화제를 샀어요.', en: 'I bought some digestive medicine at the pharmacy.' } },
    { id: 'patch', ko: '파스', en: 'pain relief patch', level: 3, pos: 'noun', emoji: '🩹💪', rom: 'paseu',
      avoid: ['bandage', 'painkiller', 'medicine'],
      enAlt: ['pain patch', 'patch', 'medicated patch', 'pain relief plaster', 'medicated plaster', 'heat patch', 'cooling patch'],
      note: 'A medicated patch for aching muscles, sold at every pharmacy: cooling ones (쿨파스) and warming ones (핫파스). You stick it on: 파스를 붙여요.',
      example: { ko: '허리에 파스를 붙였어요.', en: 'I put a pain relief patch on my back.' } },
    { id: 'er', ko: '응급실', en: 'emergency room', level: 3, pos: 'noun', emoji: '🚑', rom: 'eunggeupsil', pron: '응급씰',
      enAlt: ['er', 'emergency', 'emergency department', 'casualty', 'emergency ward'],
      note: '응급 (emergency) + 실 (room), like 교실. For an ambulance (구급차), call 119 (일일구): the number for both fire and ambulance in Korea.',
      example: { ko: '밤에 응급실에 갔어요.', en: 'I went to the emergency room at night.' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-headache', en: 'My head and throat hurt.', ko: '머리하고 목이 아파요.',
      tiles: ['머리하고', '목이', '아파요'], gloss: ['head and', 'throat (subject)', 'hurt'],
      words: ['head', 'throat', 'feelings:hurts'],
      traps: [
        { tile: '목을', why: '아파요 describes how something feels, so what hurts is its subject and takes 이: 목이 아파요.' },
        { tile: '배하고', why: '배 means “stomach”. “Head” is 머리.' },
      ] },
    { id: 's-stomach', en: 'I’ve had a stomach ache since yesterday.', ko: '어제부터 배가 아파요.',
      tiles: ['어제부터', '배가', '아파요'], gloss: ['since yesterday', 'stomach (subject)', 'hurts'],
      words: ['day:yesterday', 'stomach', 'feelings:hurts'], alts: [['배가', '어제부터', '아파요']],
      traps: [
        { tile: '어제까지', why: '까지 means “until”. “Since yesterday” is 어제부터.' },
        { tile: '배를', why: '아파요 describes how something feels, so what hurts is its subject and takes 가: 배가 아파요.' },
      ] },
    { id: 's-body', en: 'I don’t feel well.', ko: '몸이 안 좋아요.',
      tiles: ['몸이', '안', '좋아요'], gloss: ['body (subject)', 'not', 'is good'], words: ['body', 'feelings:good'],
      traps: [
        { tile: '몸에', why: '몸에 안 좋아요 means “it’s bad for your health”. To say you don’t feel well, 몸 is the subject: 몸이 안 좋아요.' },
        { tile: '몸을', why: '좋아요 describes your body, so 몸 is its subject and takes 이: 몸이 안 좋아요.' },
      ] },
    { id: 's-medicine', en: 'I take my medicine in the morning.', ko: '아침에 약을 먹어요.',
      tiles: ['아침에', '약을', '먹어요'], gloss: ['in the morning', 'medicine (object)', 'eat (take)'],
      words: ['day:morning', 'medicine', 'day:eat'], alts: [['약을', '아침에', '먹어요']],
      traps: [
        { tile: '마셔요', why: 'Medicine is “eaten” in Korean, even when you swallow it with water: 약을 먹어요.' },
        { tile: '아침에서', why: 'To say when something happens, use 에, not 에서: 아침에.' },
      ] },
    { id: 's-fever', en: 'My child has a fever.', ko: '우리 아이가 열이 나요.',
      tiles: ['우리', '아이가', '열이', '나요'], gloss: ['our (my)', 'child (subject)', 'fever (subject)', 'comes out'],
      words: ['people:we', 'people:child', 'fever'],
      traps: [
        { tile: '열을', why: 'A fever “comes out” (나다), so 열 is the subject and takes 이: 열이 나요.' },
        { tile: '아이를', why: '아이 is the one with the fever, not an object. In 아이가 열이 나요, both 아이 and 열 take 이/가.' },
      ] },

    // ---- Level 2 ----
    { id: 's-cough', level: 2, en: 'I have a fever, and I’m coughing too.', ko: '열이 나고 기침도 해요.',
      tiles: ['열이', '나고', '기침도', '해요'], gloss: ['fever (subject)', 'comes out, and', 'cough, too', 'do'],
      words: ['fever', 'cough', 'day:do'],
      traps: [
        { tile: '열을', why: 'A fever “comes out” (나다), so 열 is the subject and takes 이: 열이 나고.' },
        { tile: '콧물도', why: '콧물 means “runny nose”, and it “comes out” (콧물이 나요). A cough is 기침: 기침도 해요.' },
      ] },
    { id: 's-nose', level: 2, en: 'My nose is blocked, and it’s running.', ko: '코가 막히고 콧물이 나요.',
      tiles: ['코가', '막히고', '콧물이', '나요'], gloss: ['nose (subject)', 'is blocked, and', 'runny nose (subject)', 'comes out'],
      words: ['nose', 'runnynose'],
      traps: [
        { tile: '콧물을', why: 'A runny nose “comes out” (나다), so 콧물 is the subject and takes 이: 콧물이 나요.' },
        { tile: '코를', why: '코 is what’s blocked (the subject), so it takes 가: 코가 막히고.' },
      ] },
    { id: 's-dentist', level: 2, en: 'I have a toothache. I’m going to the dentist.', ko: '이가 아파요. 치과에 가요.',
      tiles: ['이가', '아파요', '치과에', '가요'], gloss: ['tooth (subject)', 'hurts', 'to the dentist’s', 'go'],
      words: ['toothache', 'dentist', 'day:go'],
      traps: [
        { tile: '이를', why: '아파요 describes how something feels, so what hurts is its subject and takes 가: 이가 아파요.' },
        { tile: '치과에서', why: '에 marks where you are going: 치과에 가요. 치과에서 would mean “from the dentist’s”.' },
      ] },
    { id: 's-rest', level: 2, en: 'Get plenty of rest, and drink lots of water.', ko: '푹 쉬세요. 물을 많이 드세요.',
      tiles: ['푹', '쉬세요', '물을', '많이', '드세요'], gloss: ['deeply, well', 'please rest', 'water (object)', 'a lot', 'please have (drink)'],
      words: ['rest', 'cafe:water', 'pleasehave'],
      traps: [
        { tile: '많아요', why: '많아요 means “there’s a lot”. Before a verb, “a lot” is 많이: 많이 드세요.' },
        { tile: '물이', why: '물 is what you drink (the object), so it takes 을: 물을 드세요.' },
      ] },
    // No particle question here: 다리가 다쳤어요 is also heard, so 가 isn't clearly wrong.
    { id: 's-hurt', level: 2, en: 'I hurt my arm and my leg.', ko: '팔하고 다리를 다쳤어요.', drill: false,
      tiles: ['팔하고', '다리를', '다쳤어요'], gloss: ['arm and', 'leg (object)', 'hurt (injured)'],
      words: ['arm', 'leg', 'hurt'],
      traps: [{ tile: '아팠어요', why: '아팠어요 means “it hurt / I was ill”. To say you injured it, use 다쳤어요.' }] },
    { id: 's-bandage', level: 2, en: 'It’s bleeding! Do you have a plaster?', ko: '피가 나요! 밴드 있어요?',
      tiles: ['피가', '나요', '밴드', '있어요'], gloss: ['blood (subject)', 'comes out', 'plaster', 'is there? / do you have?'],
      words: ['blood', 'bandage', 'day:have'],
      traps: [{ tile: '피를', why: 'Blood “comes out” (나다), so 피 is the subject and takes 가: 피가 나요.' }] },
    { id: 's-wherehurt', level: 2, en: 'Where does it hurt? — My feet hurt.', ko: '어디가 아프세요? 발이 아파요.',
      tiles: ['어디가', '아프세요', '발이', '아파요'], gloss: ['where (subject)', 'does it hurt? (polite)', 'foot (subject)', 'hurts'],
      words: ['wherehurt', 'foot', 'feelings:hurts'],
      traps: [
        { tile: '발을', why: '아파요 describes how something feels, so what hurts is its subject and takes 이: 발이 아파요.' },
        { tile: '다리가', why: '다리 means “leg”. “Foot” is 발.' },
      ] },
    // Kept out of Particle Lab (drill: false), like numbers:s-threetimes: its 에 means “per”, which the generic
    // explanation of 에 doesn't cover. The traps below explain it.
    { id: 's-day', level: 2, en: 'Take this medicine three times a day.', ko: '이 약은 하루에 세 번 드세요.', drill: false,
      tiles: ['이', '약은', '하루에', '세', '번', '드세요'], gloss: ['this', 'medicine (topic)', 'a day (per day)', 'three', 'times', 'please take'],
      words: ['medicine', 'day', 'numbers:three', 'numbers:times', 'pleasehave'],
      traps: [
        { tile: '삼', why: '번 (times) counts with native numbers: 세 번, not 삼 번.' },
        { tile: '셋', why: 'Before a counter, 셋 shortens to 세: 세 번.' },
        { tile: '하루에서', why: 'Here, 에 means “per”: 하루에 세 번 = three times a day. 에서 is for places.' },
        { tile: '하루가', why: '하루 isn’t the subject here: 하루에 means “per day”, like 일주일에 한 번 (once a week).' },
      ] },
    { id: 's-getbetter', level: 2, en: 'My cold is all gone.', ko: '감기가 다 나았어요.',
      tiles: ['감기가', '다', '나았어요'], gloss: ['cold (subject)', 'completely', 'got better'],
      words: ['weather:acold', 'getbetter'],
      traps: [
        { tile: '낫았어요', why: '낫다 is ㅅ-irregular: before a vowel, the ㅅ drops → 나았어요.' },
        { tile: '감기를', why: '낫다 (get better) has no object: the cold is what gets better, so it’s the subject and takes 가: 감기가 나았어요.' },
      ] },

    // ---- Level 3 ----
    { id: 's-healthy', level: 3, en: 'My grandma is very healthy.', ko: '우리 할머니는 아주 건강하세요.',
      tiles: ['우리', '할머니는', '아주', '건강하세요'], gloss: ['our (my)', 'grandma (topic)', 'very', 'is healthy (polite)'],
      words: ['people:we', 'people:grandma', 'healthy'],
      traps: [{ tile: '아프세요', why: '아프세요 means “she’s ill”. “Healthy” is 건강하다: 건강하세요.' }] },
    { id: 's-dizzy', level: 3, en: 'Do you feel dizzy? Lie down here.', ko: '어지러워요? 여기 누우세요.',
      tiles: ['어지러워요', '여기', '누우세요'], gloss: ['are you dizzy?', 'here', 'please lie down'],
      words: ['dizzy', 'directions:here', 'liedown'],
      traps: [
        { tile: '눕으세요', why: '눕다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 누우세요.' },
        { tile: '어지럽어요', why: '어지럽다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 어지러워요.' },
      ] },
    { id: 's-shot', level: 3, en: 'I got a shot and a prescription at the clinic.', ko: '병원에서 주사를 맞고 처방전을 받았어요.',
      tiles: ['병원에서', '주사를', '맞고', '처방전을', '받았어요'],
      gloss: ['at the clinic', 'shot (object)', 'got (a shot), and', 'prescription (object)', 'received'],
      words: ['directions:hospital', 'shot', 'prescription', 'past:received'],
      traps: [
        { tile: '병원에', why: 'Getting a shot is something you do there, so the place takes 에서: 병원에서.' },
        { tile: '먹고', why: 'You swallow medicine (먹어요), but a shot is 맞아요: 주사를 맞고.' },
      ] },
    { id: 's-aftermeals', level: 3, en: 'Take the medicine 30 minutes after meals.', ko: '약은 식후 삼십 분에 드세요.',
      tiles: ['약은', '식후', '삼십', '분에', '드세요'], gloss: ['medicine (topic)', 'after meals', 'thirty', 'minutes (at)', 'please take'],
      words: ['medicine', 'aftermeals', 'numbers:sam', 'numbers:sip', 'numbers:minute', 'pleasehave'],
      traps: [
        { tile: '식전', why: '식전 means “before meals”. “After meals” is 식후.' },
        { tile: '서른', why: 'Minutes use Sino-Korean numbers: 삼십 분, not 서른 분.' },
      ] },
    { id: 's-back', level: 3, en: 'My back hurts. Do you have any painkillers?', ko: '허리가 아파요. 진통제 있어요?',
      tiles: ['허리가', '아파요', '진통제', '있어요'], gloss: ['lower back (subject)', 'hurts', 'painkiller', 'is there? / do you have?'],
      words: ['back', 'feelings:hurts', 'painkiller', 'day:have'],
      traps: [
        { tile: '허리를', why: '아파요 describes how something feels, so what hurts is its subject and takes 가: 허리가 아파요.' },
        { tile: '감기약', why: '감기약 is cold medicine. For pain, ask for 진통제 (a painkiller).' },
      ] },
    { id: 's-allergy', level: 3, en: 'I’m allergic to milk.', ko: '저는 우유 알레르기가 있어요.',
      tiles: ['저는', '우유', '알레르기가', '있어요'], gloss: ['I (topic)', 'milk', 'allergy (subject)', 'there is (I have)'],
      words: ['people:me', 'cafe:milk', 'allergy', 'day:have'],
      traps: [{ tile: '알레르기를', why: '있어요 says that something is there. That thing is the subject, so it takes 가: 알레르기가 있어요.' }] },
    { id: 's-apply', level: 3, en: 'Put this medicine on your hand.', ko: '손에 이 약을 바르세요.',
      tiles: ['손에', '이', '약을', '바르세요'], gloss: ['on (your) hand', 'this', 'medicine (object)', 'please put on'],
      words: ['hand', 'medicine', 'apply'], alts: [['이', '약을', '손에', '바르세요']],
      traps: [
        { tile: '발르세요', why: '바르다 changes only before 아/어 (발라요). Before -세요, it stays 바르: 바르세요.' },
        { tile: '드세요', why: '드세요 is for medicine you swallow. Medicine that goes on your skin is 바르세요.' },
        { tile: '손에서', why: 'The place you put medicine on takes 에 (onto): 손에 바르세요.' },
        { tile: '손이', why: 'With 이, the hand would be the subject. The place the medicine goes takes 에: 손에 바르세요.' },
      ] },
    { id: 's-getwell', level: 3, en: 'Are you very sick? Get well soon!', ko: '많이 아파요? 빨리 나으세요!',
      tiles: ['많이', '아파요', '빨리', '나으세요'], gloss: ['a lot, very', 'are you sick?', 'quickly', 'please get better'],
      words: ['feelings:hurts', 'getwell'],
      traps: [
        { tile: '낫으세요', why: '낫다 is ㅅ-irregular: the ㅅ drops before a vowel → 나으세요.' },
        { tile: '많아요', why: '많아요 means “there’s a lot”. Before a verb, “a lot / very” is 많이: 많이 아파요?' },
      ] },
    { id: 's-symptom', level: 3, en: 'I have cold symptoms. Cold medicine, please.', ko: '감기 증상이 있어요. 감기약 주세요.',
      tiles: ['감기', '증상이', '있어요', '감기약', '주세요'], gloss: ['cold', 'symptom (subject)', 'there is (I have)', 'cold medicine', 'please give'],
      words: ['weather:acold', 'symptom', 'day:have', 'coldmedicine', 'cafe:please'],
      traps: [
        { tile: '증상을', why: '있어요 says that something is there. That thing is the subject, so it takes 이: 증상이 있어요.' },
        { tile: '진통제', why: '진통제 is a painkiller. For a cold, ask for 감기약.' },
      ] },

    // ---- More sentences ----
    { id: 's-face', en: 'You don’t look well. Are you all right?', ko: '얼굴이 안 좋아요. 괜찮으세요?',
      tiles: ['얼굴이', '안', '좋아요', '괜찮으세요'], gloss: ['face (subject)', 'not', 'is good', 'are you all right? (polite)'],
      words: ['face', 'feelings:good', 'areyouok'],
      traps: [
        { tile: '얼굴에', why: '얼굴에 안 좋아요 means “it’s bad for your face”. To say someone doesn’t look well, 얼굴 is the subject: 얼굴이 안 좋아요.' },
        { tile: '얼굴을', why: '좋아요 describes the face, so 얼굴 is its subject and takes 이: 얼굴이 안 좋아요.' },
      ] },
    { id: 's-ankle', level: 2, en: 'I fell over yesterday. My ankle hurts.', ko: '어제 넘어졌어요. 발목이 아파요.',
      tiles: ['어제', '넘어졌어요', '발목이', '아파요'], gloss: ['yesterday', 'fell over', 'ankle (subject)', 'hurts'],
      words: ['day:yesterday', 'fell', 'ankle', 'feelings:hurts'],
      traps: [
        { tile: '발목을', why: '아파요 describes how something feels, so what hurts is its subject and takes 이: 발목이 아파요.' },
        { tile: '발이', why: '발 means “foot”. The ankle is 발목 (foot + neck).' },
        { tile: '넘어져요', why: 'It happened yesterday, so use the past: 넘어졌어요.' },
      ] },
    { id: 's-patch', level: 3, en: 'I put a pain relief patch on my shoulder.', ko: '어깨에 파스를 붙여요.',
      tiles: ['어깨에', '파스를', '붙여요'], gloss: ['on (my) shoulder', 'pain relief patch (object)', 'stick on'],
      words: ['shoulder', 'patch', 'stickon'], alts: [['파스를', '어깨에', '붙여요']],
      traps: [
        { tile: '어깨에서', why: 'The place you stick something on takes 에 (onto): 어깨에 붙여요.' },
        { tile: '어깨가', why: 'With 가, the shoulder would be the subject. The place the patch goes takes 에: 어깨에 붙여요.' },
        { tile: '발라요', why: '발라요 is for cream you spread on. A patch is stuck on: 붙여요.' },
      ] },
    { id: 's-caughtcold', level: 3, en: 'I’ve caught a cold. My throat is swollen, and I have a bad cough.',
      ko: '감기에 걸렸어요. 목이 붓고 기침이 심해요.',
      tiles: ['감기에 걸렸어요', '목이', '붓고', '기침이', '심해요'],
      gloss: ['I’ve caught a cold', 'throat (subject)', 'is swollen, and', 'cough (subject)', 'is bad (severe)'],
      words: ['caughtcold', 'throat', 'swollen', 'cough', 'severe'],
      traps: [
        { tile: '부고', why: '붓다 is ㅅ-irregular, but the ㅅ only drops before a vowel. Before -고 it stays: 붓고. (부고 is another word: an obituary.)' },
        { tile: '목을', why: '붓다 (to swell) has no object: the throat is what swells, so it’s the subject and takes 이: 목이 붓고.' },
        { tile: '기침을', why: '심해요 describes the cough, so 기침 is its subject and takes 이: 기침이 심해요.' },
      ] },
    { id: 's-indigestion', level: 3, en: 'Got indigestion? Take this digestive medicine.', ko: '체했어요? 이 소화제 드세요.',
      tiles: ['체했어요', '이', '소화제', '드세요'], gloss: ['do you have indigestion?', 'this', 'digestive medicine', 'please take'],
      words: ['indigestion', 'digestive', 'pleasehave'],
      traps: [
        { tile: '진통제', why: '진통제 is a painkiller. For indigestion, take 소화제.' },
        { tile: '바르세요', why: '바르세요 is for medicine that goes on your skin. A digestive medicine is swallowed: 드세요.' },
        { tile: '체해요', why: '체하다 is said in the past for how you feel now: 체했어요?' },
      ] },
    { id: 's-er', level: 3, en: 'Nurse, where’s the emergency room?', ko: '간호사님, 응급실이 어디예요?',
      tiles: ['간호사님', '응급실이', '어디예요'], gloss: ['nurse (calling them, polite)', 'emergency room (subject)', 'where is it?'],
      words: ['nurse', 'er', 'directions:where'],
      traps: [
        { tile: '응급실을', why: '어디예요? asks where something is. That thing is the subject, so it takes 이: 응급실이 어디예요?' },
        { tile: '간호사', why: 'When you call or speak to a nurse, add 님 for respect: 간호사님.' },
        { tile: '어디에요', why: '어디 ends in a vowel, so it takes 예요: 어디예요? (이에요 goes after a consonant.)' },
      ] },
  ],
});
