/**
 * Topic: 취미와 계획 · Hobbies & plans — free time, "I want to…" (-고 싶어요)
 * and plans (-(으)ㄹ 거예요). Verbs are taught in the polite present form, except
 * the words marked `form: 'future'` or `form: 'want'` (checked against
 * js/core/conjugate.js). Field reference: see content/cafe.js and README → "Adding content".
 */
Mallang.content.registerTopic({
  id: 'hobbies',
  order: 10,
  emoji: '🎨',
  color: 'lilac',
  title: { ko: '취미와 계획', en: 'Hobbies & plans' },
  description: { ko: '취미와 주말 계획', en: 'Free time and plans' },

  notes: [
    {
      title: { ko: '취미가 뭐예요?', en: 'Talking about hobbies' },
      text: 'Ask **취미가 뭐예요?** (What’s your hobby?) and answer **제 취미는 … 이에요 / 예요**: **이에요** after a consonant (받침), **예요** after a vowel. You can also just say what you do: **주말에 등산해요**.',
      examples: [
        { ko: '취미가 뭐예요?', en: 'What’s your hobby?' },
        { ko: '제 취미는 여행이에요.', en: 'My hobby is travelling.' },
        { ko: '제 취미는 축구예요.', en: 'My hobby is football.' },
      ],
    },
    {
      title: { ko: '노래를 불러요', en: 'Which verb goes with it?' },
      text: 'Some nouns have their own verb: **노래를 불러요** (sing a song), **사진을 찍어요** (take a photo), **그림을 그려요** (draw a picture), **음악을 들어요** (listen to music). Sports and games use **해요**, not 놀아요: **축구를 해요**, **게임을 해요**. Watch the irregular ones: **부르다 → 불러요** (르-irregular) and **듣다 → 들어요** (ㄷ-irregular).',
      examples: [
        { ko: '친구가 노래를 불러요.', en: 'My friend is singing a song.' },
        { ko: '카페에서 사진을 찍어요.', en: 'I take photos at the café.' },
        { ko: '주말에 축구를 해요.', en: 'I play football on weekends.' },
      ],
    },
    {
      title: { ko: '-고 싶어요', en: 'I want to…' },
      text: 'Add **고 싶어요** straight to the verb stem (the dictionary form minus 다): **배우다 → 배우고 싶어요**, **가다 → 가고 싶어요**, **먹다 → 먹고 싶어요**. The verb itself doesn’t change. Ask someone with **뭐 하고 싶어요?**',
      examples: [
        { ko: '자전거를 배우고 싶어요.', en: 'I want to learn to ride a bike.' },
        { ko: '캠핑을 가고 싶어요.', en: 'I want to go camping.' },
        { ko: '주말에 뭐 하고 싶어요?', en: 'What do you want to do this weekend?' },
      ],
    },
    {
      title: { ko: '-(으)ㄹ 거예요', en: 'Plans: going to…' },
      text: 'Talk about plans with **-(으)ㄹ 거예요** (“I’m going to…”). After a vowel, put **ㄹ** under the last syllable: 하다 → **할 거예요**, 가다 → **갈 거예요**. After a consonant, add **을**: 먹다 → **먹을 거예요**. A stem that already ends in ㄹ adds nothing: 놀다 → **놀 거예요**. Use it with future time words like **내일**, **주말에** and **다음 주에**.',
      examples: [
        { ko: '내일 축구를 할 거예요.', en: 'I’m going to play football tomorrow.' },
        { ko: '다음 주에 콘서트에 갈 거예요.', en: 'I’m going to a concert next week.' },
        { ko: '방학에 뭐 할 거예요?', en: 'What are you going to do in the school holidays?' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'hobby', ko: '취미', en: 'hobby', level: 1, pos: 'noun', emoji: '🎨', rom: 'chwimi',
      note: 'Ask 취미가 뭐예요? (What’s your hobby?) and answer 제 취미는 … 이에요 / 예요.',
      example: { ko: '제 취미는 요리예요.', en: 'My hobby is cooking.' } },
    { id: 'music', ko: '음악', en: 'music', level: 1, pos: 'noun', emoji: '🎵', rom: 'eumak', pron: '으막',
      note: 'The ㅁ slides into the next syllable: [으막]. You listen to it: 음악을 들어요.',
      example: { ko: '무슨 음악 좋아해요?', en: 'What kind of music do you like?' } },
    { id: 'song', ko: '노래', en: 'song', level: 1, pos: 'noun', emoji: '🎶', rom: 'norae', avoid: ['music'],
      note: 'Songs are “called” in Korean: 노래를 불러요 = I sing a song. 노래해요 also means “I sing”.',
      example: { ko: '이 노래 알아요?', en: 'Do you know this song?' } },
    { id: 'game', ko: '게임', en: 'game', level: 1, pos: 'noun', emoji: '🎮', rom: 'geim', enAlt: ['games', 'video game', 'video games'],
      note: 'You “do” games in Korean: 게임을 해요 = I play games.',
      example: { ko: '저녁에 게임을 해요.', en: 'I play games in the evening.' } },
    { id: 'photo', ko: '사진', en: 'photo / picture', level: 1, pos: 'noun', emoji: '🖼️', rom: 'sajin',
      note: 'Photos go with 찍다: 사진을 찍어요 = I take a photo.',
      example: { ko: '사진 좀 찍어 주세요.', en: 'Could you take a picture for me?' } },
    { id: 'trip', ko: '여행', en: 'trip / travel', level: 1, pos: 'noun', emoji: '🧳', rom: 'yeohaeng', enAlt: ['travelling', 'journey'],
      note: '여행을 가요 = I go on a trip. 여행해요 = I travel.',
      example: { ko: '여행 좋아해요?', en: 'Do you like travelling?' } },
    { id: 'listen', ko: '들어요', en: 'listen / hear', level: 1, pos: 'verb', emoji: '🎧', rom: 'deureoyo', pron: '드러요', dict: '듣다',
      note: '듣다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 들 + 어요 → 들어요.',
      example: { ko: '지금 뭐 들어요?', en: 'What are you listening to?' } },
    { id: 'play', ko: '놀아요', en: 'play / hang out', level: 1, pos: 'verb', emoji: '🤹', rom: 'norayo', pron: '노라요', dict: '놀다',
      note: '놀다 is playing for fun or hanging out with friends. Sports and games use 해요 instead: 축구를 해요, 게임을 해요.',
      example: { ko: '같이 놀아요!', en: 'Let’s hang out!' } },

    // ---- Level 2 ----
    { id: 'sing', ko: '불러요', en: 'sing (a song)', level: 2, pos: 'verb', emoji: '🎤', rom: 'bulleoyo', dict: '부르다',
      note: '부르다 is 르-irregular: 르 turns into ㄹ러 → 불러요. It also means “to call” someone.',
      example: { ko: '노래방에서 노래를 불러요.', en: 'We sing songs at karaoke.' } },
    { id: 'dance', ko: '춤춰요', en: 'dance', level: 2, pos: 'verb', emoji: '💃', rom: 'chumchwoyo', dict: '춤추다', accept: ['춤추어요'],
      note: '춤 (a dance) + 추다 (to dance): 추 + 어요 → 춰요 (ㅜ + ㅓ merge into ㅝ).',
      example: { ko: '같이 춤춰요!', en: 'Let’s dance together!' } },
    { id: 'take', ko: '찍어요', en: 'take (a photo)', level: 2, pos: 'verb', emoji: '📸', rom: 'jjigeoyo', pron: '찌거요', dict: '찍다',
      enAlt: ['take a picture'],
      note: 'For photos and videos: 사진을 찍어요 = I take a photo. The ㄱ slides over: [찌거요].',
      example: { ko: '여기서 사진 찍어요!', en: 'Let’s take a picture here!' } },
    { id: 'draw', ko: '그려요', en: 'draw / paint', level: 2, pos: 'verb', emoji: '🖌️', rom: 'geuryeoyo', dict: '그리다',
      note: '그리다 → 그리 + 어요 → 그려요 (ㅣ + ㅓ merge into ㅕ). A picture or drawing is 그림: 그림을 그려요.',
      example: { ko: '주말에 그림을 그려요.', en: 'I draw on weekends.' } },
    { id: 'swim', ko: '수영해요', en: 'swim', level: 2, pos: 'verb', emoji: '🏊', rom: 'suyeonghaeyo', dict: '수영하다',
      enAlt: ['go swimming'],
      note: '수영 (swimming) + 해요. For “don’t swim”, 안 goes right before 해요: 수영 안 해요.',
      example: { ko: '매일 수영해요.', en: 'I swim every day.' } },
    { id: 'soccer', ko: '축구', en: 'football / soccer', level: 2, pos: 'noun', emoji: '⚽', rom: 'chukgu', pron: '축꾸',
      note: 'Sports are “done” in Korean: 축구를 해요 = I play football. After ㄱ, the next ㄱ is tense: [축꾸].',
      example: { ko: '친구하고 축구를 해요.', en: 'I play football with my friends.' } },
    { id: 'bike', ko: '자전거', en: 'bicycle', level: 2, pos: 'noun', emoji: '🚲', rom: 'jajeongeo', enAlt: ['bike'],
      note: 'You ride it with 타다: 자전거를 타요 = I ride a bike.',
      example: { ko: '주말에 자전거를 타요.', en: 'I ride my bike on weekends.' } },
    { id: 'stroll', ko: '산책해요', en: 'take a walk', level: 2, pos: 'verb', emoji: '🌳', rom: 'sanchaekaeyo', pron: '산채캐요',
      dict: '산책하다', enAlt: ['go for a walk', 'walk', 'stroll'],
      note: '산책 (a walk) + 해요. ㄱ and ㅎ together sound like ㅋ: [산채캐요].',
      example: { ko: '저녁에 공원에서 산책해요.', en: 'I take a walk in the park in the evening.' } },
    { id: 'concert', ko: '콘서트', en: 'concert', level: 2, pos: 'noun', emoji: '🎸', rom: 'konseoteu',
      note: 'Going to one takes 에: 콘서트에 가요. Doing something there takes 에서: 콘서트에서 춤춰요.',
      example: { ko: '같이 콘서트에 가요!', en: 'Let’s go to a concert together!' } },

    // ---- Level 3 ----
    { id: 'plan', ko: '계획', en: 'plan', level: 3, pos: 'noun', emoji: '🗒️', rom: 'gyehoek', enAlt: ['plans'],
      note: 'Ask 계획 있어요? (Do you have plans?) — 계획 is the thing you have, so with a particle it’s 계획이 있어요?',
      example: { ko: '주말에 무슨 계획 있어요?', en: 'Do you have any plans for the weekend?' } },
    { id: 'nextweek', ko: '다음 주', en: 'next week', level: 3, pos: 'noun', emoji: '⏭️', rom: 'daeum ju',
      note: '다음 (next) + 주 (week), written with a space. Last week is 지난주, written as one word.',
      example: { ko: '다음 주에 봐요!', en: 'See you next week!' } },
    { id: 'vacation', ko: '방학', en: 'school holidays', level: 3, pos: 'noun', emoji: '🎒', rom: 'banghak',
      enAlt: ['school vacation', 'vacation', 'school break'],
      note: 'The school or university holidays. Time off work is 휴가.',
      example: { ko: '방학이 언제예요?', en: 'When are your school holidays?' } },
    { id: 'holiday', ko: '휴가', en: 'holiday / time off (work)', level: 3, pos: 'noun', emoji: '🏝️', rom: 'hyuga',
      avoid: ['vacation'], enAlt: ['vacation', 'leave'],
      note: 'Time off work: 휴가를 가요 = I go on holiday. School holidays are 방학.',
      example: { ko: '휴가 때 뭐 할 거예요?', en: 'What are you going to do on your holiday?' } },
    { id: 'willdo', ko: '할 거예요', en: 'I will do (it)', level: 3, pos: 'verb', emoji: '💪', rom: 'hal geoyeyo', pron: '할 꺼예요',
      dict: '하다', form: 'future', enAlt: ['will do', 'going to do', 'will do it'],
      note: '하다 → 하 + ㄹ 거예요 → 할 거예요 (I’m going to do). After the ㄹ, 거 is said tense: [할 꺼예요].',
      example: { ko: '주말에 뭐 할 거예요?', en: 'What are you going to do this weekend?' } },
    { id: 'willgo', ko: '갈 거예요', en: 'I will go', level: 3, pos: 'verb', emoji: '🗺️', rom: 'gal geoyeyo', pron: '갈 꺼예요',
      dict: '가다', form: 'future', enAlt: ['will go', 'going to go'],
      note: '가다 → 가 + ㄹ 거예요 → 갈 거예요. After a consonant, add 을 instead: 먹을 거예요.',
      example: { ko: '다음 주에 부산에 갈 거예요.', en: 'I’m going to Busan next week.' } },
    { id: 'wanttolearn', ko: '배우고 싶어요', en: 'I want to learn', level: 3, pos: 'verb', emoji: '🤓', rom: 'baeugo sipeoyo',
      pron: '배우고 시퍼요', dict: '배우다', form: 'want', enAlt: ['want to learn'],
      note: '배우다 (to learn) + 고 싶어요 (want to). 고 싶어요 goes straight onto the stem, and the verb doesn’t change.',
      example: { ko: '춤을 배우고 싶어요.', en: 'I want to learn to dance.' } },
    { id: 'hiking', ko: '등산해요', en: 'go hiking', level: 3, pos: 'verb', emoji: '⛰️', rom: 'deungsanhaeyo', dict: '등산하다',
      enAlt: ['hike', 'hiking', 'climb a mountain'],
      note: '등산 = climbing a mountain (산 means mountain). Hiking is a hugely popular weekend hobby in Korea.',
      example: { ko: '주말에 친구하고 등산해요.', en: 'I go hiking with friends on weekends.' } },
    { id: 'camping', ko: '캠핑', en: 'camping', level: 3, pos: 'noun', emoji: '🏕️', rom: 'kaemping', enAlt: ['go camping'],
      note: '캠핑을 가요, or just 캠핑 가요 = I go camping.',
      example: { ko: '캠핑 좋아해요?', en: 'Do you like camping?' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-hobby', en: 'My hobby is gaming.', ko: '제 취미는 게임이에요.',
      tiles: ['제', '취미는', '게임이에요'], gloss: ['my', 'hobby (topic)', 'is games'], words: ['hobby', 'game'],
      traps: [{ tile: '게임예요', why: '게임 ends in a consonant (받침), so it takes 이에요. 예요 goes after vowels.' }] },
    { id: 's-music', en: 'I listen to music at home.', ko: '집에서 음악을 들어요.',
      tiles: ['집에서', '음악을', '들어요'], gloss: ['at home', 'music (object)', 'listen'], words: ['day:home', 'music', 'listen'],
      alts: [['음악을', '집에서', '들어요']],
      traps: [
        { tile: '집에', why: 'Listening to music is something you do there, so the place takes 에서: 집에서.' },
        { tile: '듣어요', why: '듣다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 들어요.' },
      ] },
    { id: 's-play', en: "I'm hanging out with a friend today.", ko: '오늘 친구하고 놀아요.',
      tiles: ['오늘', '친구하고', '놀아요'], gloss: ['today', 'with a friend', 'play / hang out'],
      words: ['day:today', 'day:friend', 'play'], alts: [['친구하고', '오늘', '놀아요']],
      traps: [
        { tile: '놀았어요', why: 'The English says “I’m hanging out”, not “hung out”, so use the present: 놀아요.' },
        { tile: '노라요', why: '놀다 keeps its ㄹ in writing: 놀 + 아요 → 놀아요. It only sounds like [노라요].' },
        { tile: '오늘에', why: '오늘 (today) works on its own as a time word: no 에.' },
      ] },
    { id: 's-trip', en: "I'm going on a trip tomorrow.", ko: '내일 여행을 가요.',
      tiles: ['내일', '여행을', '가요'], gloss: ['tomorrow', 'trip (object)', 'go'], words: ['day:tomorrow', 'trip', 'day:go'],
      alts: [['여행을', '내일', '가요']],
      traps: [
        { tile: '갔어요', why: '내일 (tomorrow) is in the future, so 갔어요 (went) doesn’t fit. Use 가요 (or 갈 거예요).' },
        { tile: '와요', why: '와요 means “come”. For “go”, use 가요.' },
      ] },

    // ---- Level 2 ----
    { id: 's-sing', level: 2, en: 'My friend is singing a song.', ko: '친구가 노래를 불러요.',
      tiles: ['친구가', '노래를', '불러요'], gloss: ['friend (subject)', 'song (object)', 'sings'], words: ['day:friend', 'song', 'sing'],
      traps: [
        { tile: '친구를', why: 'Your friend is the one singing (the subject), so it takes 가: 친구가.' },
        { tile: '부러요', why: '부르다 is 르-irregular: 르 turns into ㄹ러 → 불러요.' },
      ] },
    { id: 's-photo', level: 2, en: 'I take photos at the café.', ko: '카페에서 사진을 찍어요.',
      tiles: ['카페에서', '사진을', '찍어요'], gloss: ['at the café', 'photo (object)', 'take'], words: ['cafe:cafe', 'photo', 'take'],
      alts: [['사진을', '카페에서', '찍어요']],
      traps: [
        { tile: '카페에', why: 'Taking photos is something you do there, so the place takes 에서: 카페에서.' },
        { tile: '그려요', why: '그려요 means “draw”. Photos are taken: 사진을 찍어요.' },
      ] },
    { id: 's-draw', level: 2, en: 'What are you drawing now?', ko: '지금 뭐 그려요?',
      tiles: ['지금', '뭐', '그려요'], gloss: ['now', 'what', 'draw'], words: ['day:now', 'day:what', 'draw'],
      traps: [
        { tile: '찍어요', why: '찍어요 is for photos. For drawing, use 그려요.' },
        { tile: '그렸어요', why: 'The English says “are drawing” (now), so use the present: 그려요.' },
      ] },
    { id: 's-noswim', level: 2, en: "I'm not swimming today.", ko: '오늘은 수영 안 해요.',
      tiles: ['오늘은', '수영', '안', '해요'], gloss: ['today (topic)', 'swimming', 'not', 'do'], words: ['day:today', 'swim'],
      traps: [{ tile: '수영해요', why: '수영하다 is 수영 (a noun) + 하다, so 안 goes right before 해요: 수영 안 해요.' }] },
    { id: 's-stroll', level: 2, en: 'I take a walk with a friend in the evening.', ko: '저녁에 친구하고 산책해요.',
      tiles: ['저녁에', '친구하고', '산책해요'], gloss: ['in the evening', 'with a friend', 'take a walk'],
      words: ['day:evening', 'day:friend', 'stroll'], alts: [['친구하고', '저녁에', '산책해요']],
      traps: [
        { tile: '저녁에서', why: 'To say when something happens, use 에, not 에서: 저녁에 (in the evening).' },
        { tile: '산책했어요', why: 'The English is in the present (I take a walk), so use 산책해요. 산책했어요 is the past.' },
        { tile: '산책헤요', why: 'Every 하다 verb becomes 해요, with ㅐ: 산책해요.' },
      ] },
    { id: 's-dance', level: 2, en: 'I dance at concerts.', ko: '콘서트에서 춤춰요.',
      tiles: ['콘서트에서', '춤춰요'], gloss: ['at a concert', 'dance'], words: ['concert', 'dance'],
      traps: [{ tile: '콘서트에', why: 'Dancing is something you do there, so the place takes 에서: 콘서트에서.' }] },

    // ---- Level 3 ----
    { id: 's-concert', level: 3, en: "I'm going to a concert next week.", ko: '다음 주에 콘서트에 갈 거예요.',
      tiles: ['다음 주에', '콘서트에', '갈', '거예요'], gloss: ['next week', 'to a concert', 'go (future form)', 'will / going to'],
      words: ['nextweek', 'concert', 'willgo'], alts: [['콘서트에', '다음 주에', '갈', '거예요']],
      traps: [
        { tile: '갔어요', why: '다음 주 (next week) is in the future, so use 갈 거예요. 갔어요 means “went”.' },
        { tile: '콘서트에서', why: '에 marks where you are going. 에서 marks where an action happens.' },
        { tile: '가을', why: 'After a vowel, just put ㄹ under it: 가 → 갈 거예요. (가을 means “autumn”!)' },
      ] },
    { id: 's-soccer', level: 3, en: "I'm going to play football tomorrow.", ko: '내일 축구를 할 거예요.',
      tiles: ['내일', '축구를', '할', '거예요'], gloss: ['tomorrow', 'football (object)', 'do (future form)', 'will / going to'],
      words: ['day:tomorrow', 'soccer', 'willdo'], alts: [['축구를', '내일', '할', '거예요']],
      traps: [
        { tile: '했어요', why: '내일 (tomorrow) is in the future, so use 할 거예요. 했어요 means “did”.' },
        { tile: '놀', why: 'Sports use 하다: 축구를 할 거예요. 놀다 is for playing around or hanging out.' },
      ] },
    { id: 's-plan', level: 3, en: 'Do you have any plans for your time off?', ko: '휴가 계획이 있어요?',
      tiles: ['휴가', '계획이', '있어요'], gloss: ['holiday (time off)', 'plan (subject)', 'is there? / do you have?'],
      words: ['holiday', 'plan', 'day:have'],
      traps: [{ tile: '계획을', why: '있어요 says that something is there. The thing you have is the subject, so it takes 이: 계획이 있어요?' }] },
    { id: 's-bike', level: 3, en: 'I want to learn to ride a bike.', ko: '자전거를 배우고 싶어요.',
      tiles: ['자전거를', '배우고', '싶어요'], gloss: ['bicycle (object)', 'learn', 'want to'], words: ['bike', 'wanttolearn'],
      traps: [{ tile: '배워요', why: '고 싶어요 goes straight onto the stem: 배우 + 고 싶어요. Don’t conjugate the verb first.' }] },
    { id: 's-camping', level: 3, en: "I'm going camping in the school holidays.", ko: '방학에 캠핑을 갈 거예요.',
      tiles: ['방학에', '캠핑을', '갈', '거예요'], gloss: ['in the school holidays', 'camping (object)', 'go (future form)', 'will / going to'],
      words: ['vacation', 'camping', 'willgo'], alts: [['캠핑을', '방학에', '갈', '거예요']],
      traps: [
        { tile: '갔어요', why: 'This is a plan, so use 갈 거예요. 갔어요 means “went”.' },
        { tile: '방학에서', why: 'To say when something happens, use 에, not 에서: 방학에.' },
      ] },
    { id: 's-hiking', level: 3, en: 'I usually go hiking on weekends.', ko: '보통 주말에 등산해요.',
      tiles: ['보통', '주말에', '등산해요'], gloss: ['usually', 'on weekends', 'go hiking'],
      words: ['day:usually', 'day:weekend', 'hiking'], alts: [['주말에', '보통', '등산해요']],
      traps: [{ tile: '주말에서', why: 'To say when something happens, use 에, not 에서: 주말에 (on weekends).' }] },
  ],
});
