/**
 * Topic: 취미와 계획 · Hobbies & plans — free time, "I want to…" (-고 싶어요)
 * and plans (-(으)ㄹ 거예요). Verbs are taught in the polite present form, except
 * the words marked `form: 'future'` or `form: 'want'` (checked against
 * js/core/conjugate.js). Field reference: see content/cafe.js and README → "Adding content".
 */
Mallang.content.registerTopic({
  id: 'hobbies',
  order: 10,
  emoji: '🎨',
  color: 'lilac',
  title: { ko: '취미와 계획', en: 'Hobbies & plans' },
  description: { ko: '취미와 주말 계획', en: 'Free time and plans' },

  notes: [
    {
      title: { ko: '취미가 뭐예요?', en: 'Talking about hobbies' },
      text: 'Ask **취미가 뭐예요?** (What’s your hobby?) and answer **제 취미는 … 이에요 / 예요**: **이에요** after a consonant (받침), **예요** after a vowel. You can also just say what you do: **주말에 등산해요**.',
      examples: [
        { ko: '취미가 뭐예요?', en: 'What’s your hobby?' },
        { ko: '제 취미는 여행이에요.', en: 'My hobby is travelling.' },
        { ko: '제 취미는 축구예요.', en: 'My hobby is football.' },
      ],
    },
    {
      title: { ko: '노래를 불러요', en: 'Which verb goes with it?' },
      text: 'Some nouns have their own verb: **노래를 불러요** (sing a song), **사진을 찍어요** (take a photo), **그림을 그려요** (draw a picture), **음악을 들어요** (listen to music). Sports and games use **해요**, not 놀아요: **축구를 해요**, **게임을 해요**. Watch the irregular ones: **부르다 → 불러요** (르-irregular) and **듣다 → 들어요** (ㄷ-irregular).',
      examples: [
        { ko: '친구가 노래를 불러요.', en: 'My friend is singing a song.' },
        { ko: '카페에서 사진을 찍어요.', en: 'I take photos at the café.' },
        { ko: '주말에 축구를 해요.', en: 'I play football on weekends.' },
      ],
    },
    {
      title: { ko: '-고 싶어요', en: 'I want to…' },
      text: 'Add **고 싶어요** straight to the verb stem (the dictionary form minus 다): **배우다 → 배우고 싶어요**, **가다 → 가고 싶어요**, **먹다 → 먹고 싶어요**. The verb itself doesn’t change. Ask someone with **뭐 하고 싶어요?**',
      examples: [
        { ko: '자전거를 배우고 싶어요.', en: 'I want to learn to ride a bike.' },
        { ko: '캠핑을 가고 싶어요.', en: 'I want to go camping.' },
        { ko: '주말에 뭐 하고 싶어요?', en: 'What do you want to do this weekend?' },
      ],
    },
    {
      title: { ko: '-(으)ㄹ 거예요', en: 'Plans: going to…' },
      text: 'Talk about plans with **-(으)ㄹ 거예요** (“I’m going to…”). After a vowel, put **ㄹ** under the last syllable: 하다 → **할 거예요**, 가다 → **갈 거예요**. After a consonant, add **을**: 먹다 → **먹을 거예요**. A stem that already ends in ㄹ adds nothing: 놀다 → **놀 거예요**. Use it with future time words like **내일**, **주말에** and **다음 주에**.',
      examples: [
        { ko: '내일 축구를 할 거예요.', en: 'I’m going to play football tomorrow.' },
        { ko: '다음 주에 콘서트에 갈 거예요.', en: 'I’m going to a concert next week.' },
        { ko: '방학에 뭐 할 거예요?', en: 'What are you going to do in the school holidays?' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'hobby', ko: '취미', en: 'hobby', level: 1, pos: 'noun', emoji: '🎨', rom: 'chwimi',
      note: 'Ask 취미가 뭐예요? (What’s your hobby?) and answer 제 취미는 … 이에요 / 예요.',
      example: { ko: '제 취미는 요리예요.', en: 'My hobby is cooking.' } },
    { id: 'music', ko: '음악', en: 'music', level: 1, pos: 'noun', emoji: '🎵', rom: 'eumak', pron: '으막',
      note: 'The ㅁ slides into the next syllable: [으막]. You listen to it: 음악을 들어요.',
      example: { ko: '무슨 음악 좋아해요?', en: 'What kind of music do you like?' } },
    { id: 'song', ko: '노래', en: 'song', level: 1, pos: 'noun', emoji: '🎶', rom: 'norae', avoid: ['music'],
      note: 'Songs are “called” in Korean: 노래를 불러요 = I sing a song. 노래해요 also means “I sing”.',
      example: { ko: '이 노래 알아요?', en: 'Do you know this song?' } },
    { id: 'game', ko: '게임', en: 'game', level: 1, pos: 'noun', emoji: '🎮', rom: 'geim', enAlt: ['games', 'video game', 'video games'],
      note: 'You “do” games in Korean: 게임을 해요 = I play games.',
      example: { ko: '저녁에 게임을 해요.', en: 'I play games in the evening.' } },
    { id: 'photo', ko: '사진', en: 'photo / picture', level: 1, pos: 'noun', emoji: '🖼️', rom: 'sajin',
      note: 'Photos go with 찍다: 사진을 찍어요 = I take a photo.',
      example: { ko: '사진 좀 찍어 주세요.', en: 'Could you take a picture for me?' } },
    { id: 'trip', ko: '여행', en: 'trip / travel', level: 1, pos: 'noun', emoji: '🧳', rom: 'yeohaeng', enAlt: ['travelling', 'journey'],
      note: '여행을 가요 = I go on a trip. 여행해요 = I travel.',
      example: { ko: '여행 좋아해요?', en: 'Do you like travelling?' } },
    { id: 'listen', ko: '들어요', en: 'listen / hear', level: 1, pos: 'verb', emoji: '🎧', rom: 'deureoyo', pron: '드러요', dict: '듣다',
      note: '듣다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 들 + 어요 → 들어요.',
      example: { ko: '지금 뭐 들어요?', en: 'What are you listening to?' } },
    { id: 'play', ko: '놀아요', en: 'play / hang out', level: 1, pos: 'verb', emoji: '🤹', rom: 'norayo', pron: '노라요', dict: '놀다',
      note: '놀다 is playing for fun or hanging out with friends. Sports and games use 해요 instead: 축구를 해요, 게임을 해요.',
      example: { ko: '같이 놀아요!', en: 'Let’s hang out!' } },

    // ---- Level 2 ----
    { id: 'sing', ko: '불러요', en: 'sing (a song)', level: 2, pos: 'verb', emoji: '🎤', rom: 'bulleoyo', dict: '부르다',
      note: '부르다 is 르-irregular: 르 turns into ㄹ러 → 불러요. It also means “to call” someone.',
      example: { ko: '노래방에서 노래를 불러요.', en: 'We sing songs at karaoke.' } },
    { id: 'dance', ko: '춤춰요', en: 'dance', level: 2, pos: 'verb', emoji: '💃', rom: 'chumchwoyo', dict: '춤추다', accept: ['춤추어요'],
      note: '춤 (a dance) + 추다 (to dance): 추 + 어요 → 춰요 (ㅜ + ㅓ merge into ㅝ).',
      example: { ko: '같이 춤춰요!', en: 'Let’s dance together!' } },
    { id: 'take', ko: '찍어요', en: 'take (a photo)', level: 2, pos: 'verb', emoji: '📸', rom: 'jjigeoyo', pron: '찌거요', dict: '찍다',
      enAlt: ['take a picture'],
      note: 'For photos and videos: 사진을 찍어요 = I take a photo. The ㄱ slides over: [찌거요].',
      example: { ko: '여기서 사진 찍어요!', en: 'Let’s take a picture here!' } },
    { id: 'draw', ko: '그려요', en: 'draw / paint', level: 2, pos: 'verb', emoji: '🖌️', rom: 'geuryeoyo', dict: '그리다',
      note: '그리다 → 그리 + 어요 → 그려요 (ㅣ + ㅓ merge into ㅕ). A picture or drawing is 그림: 그림을 그려요.',
      example: { ko: '주말에 그림을 그려요.', en: 'I draw on weekends.' } },
    { id: 'swim', ko: '수영해요', en: 'swim', level: 2, pos: 'verb', emoji: '🏊', rom: 'suyeonghaeyo', dict: '수영하다',
      enAlt: ['go swimming'],
      note: '수영 (swimming) + 해요. For “don’t swim”, 안 goes right before 해요: 수영 안 해요.',
      example: { ko: '매일 수영해요.', en: 'I swim every day.' } },
    { id: 'soccer', ko: '축구', en: 'football / soccer', level: 2, pos: 'noun', emoji: '⚽', rom: 'chukgu', pron: '축꾸',
      note: 'Sports are “done” in Korean: 축구를 해요 = I play football. After ㄱ, the next ㄱ is tense: [축꾸].',
      example: { ko: '친구하고 축구를 해요.', en: 'I play football with my friends.' } },
    { id: 'bike', ko: '자전거', en: 'bicycle', level: 2, pos: 'noun', emoji: '🚲', rom: 'jajeongeo', enAlt: ['bike'],
      note: 'You ride it with 타다: 자전거를 타요 = I ride a bike.',
      example: { ko: '주말에 자전거를 타요.', en: 'I ride my bike on weekends.' } },
    { id: 'stroll', ko: '산책해요', en: 'take a walk', level: 2, pos: 'verb', emoji: '🌳', rom: 'sanchaekaeyo', pron: '산채캐요',
      dict: '산책하다', enAlt: ['go for a walk', 'walk', 'stroll'],
      note: '산책 (a walk) + 해요. ㄱ and ㅎ together sound like ㅋ: [산채캐요].',
      example: { ko: '저녁에 공원에서 산책해요.', en: 'I take a walk in the park in the evening.' } },
    { id: 'concert', ko: '콘서트', en: 'concert', level: 2, pos: 'noun', emoji: '🎸', rom: 'konseoteu',
      note: 'Going to one takes 에: 콘서트에 가요. Doing something there takes 에서: 콘서트에서 춤춰요.',
      example: { ko: '같이 콘서트에 가요!', en: 'Let’s go to a concert together!' } },

    // ---- Level 3 ----
    { id: 'plan', ko: '계획', en: 'plan', level: 3, pos: 'noun', emoji: '🗒️', rom: 'gyehoek', enAlt: ['plans'],
      note: 'Ask 계획 있어요? (Do you have plans?) — 계획 is the thing you have, so with a particle it’s 계획이 있어요?',
      example: { ko: '주말에 무슨 계획 있어요?', en: 'Do you have any plans for the weekend?' } },
    { id: 'nextweek', ko: '다음 주', en: 'next week', level: 3, pos: 'noun', emoji: '⏭️', rom: 'daeum ju',
      note: '다음 (next) + 주 (week), written with a space. Last week is 지난주, written as one word.',
      example: { ko: '다음 주에 봐요!', en: 'See you next week!' } },
    { id: 'vacation', ko: '방학', en: 'school holidays', level: 3, pos: 'noun', emoji: '🎒', rom: 'banghak',
      enAlt: ['school vacation', 'vacation', 'school break'],
      note: 'The school or university holidays. Time off work is 휴가.',
      example: { ko: '방학이 언제예요?', en: 'When are your school holidays?' } },
    { id: 'holiday', ko: '휴가', en: 'holiday / time off (work)', level: 3, pos: 'noun', emoji: '🏝️', rom: 'hyuga',
      avoid: ['vacation'], enAlt: ['vacation', 'leave'],
      note: 'Time off work: 휴가를 가요 = I go on holiday. School holidays are 방학.',
      example: { ko: '휴가 때 뭐 할 거예요?', en: 'What are you going to do on your holiday?' } },
    { id: 'willdo', ko: '할 거예요', en: 'I will do (it)', level: 3, pos: 'verb', emoji: '💪', rom: 'hal geoyeyo', pron: '할 꺼예요',
      dict: '하다', form: 'future', enAlt: ['will do', 'going to do', 'will do it'],
      note: '하다 → 하 + ㄹ 거예요 → 할 거예요 (I’m going to do). After the ㄹ, 거 is said tense: [할 꺼예요].',
      example: { ko: '주말에 뭐 할 거예요?', en: 'What are you going to do this weekend?' } },
    { id: 'willgo', ko: '갈 거예요', en: 'I will go', level: 3, pos: 'verb', emoji: '🗺️', rom: 'gal geoyeyo', pron: '갈 꺼예요',
      dict: '가다', form: 'future', enAlt: ['will go', 'going to go'],
      note: '가다 → 가 + ㄹ 거예요 → 갈 거예요. After a consonant, add 을 instead: 먹을 거예요.',
      example: { ko: '다음 주에 부산에 갈 거예요.', en: 'I’m going to Busan next week.' } },
    { id: 'wanttolearn', ko: '배우고 싶어요', en: 'I want to learn', level: 3, pos: 'verb', emoji: '🤓', rom: 'baeugo sipeoyo',
      pron: '배우고 시퍼요', dict: '배우다', form: 'want', enAlt: ['want to learn'],
      note: '배우다 (to learn) + 고 싶어요 (want to). 고 싶어요 goes straight onto the stem, and the verb doesn’t change.',
      example: { ko: '춤을 배우고 싶어요.', en: 'I want to learn to dance.' } },
    { id: 'hiking', ko: '등산해요', en: 'go hiking', level: 3, pos: 'verb', emoji: '⛰️', rom: 'deungsanhaeyo', dict: '등산하다',
      enAlt: ['hike', 'hiking', 'climb a mountain'],
      note: '등산 = climbing a mountain (산 means mountain). Hiking is a hugely popular weekend hobby in Korea.',
      example: { ko: '주말에 친구하고 등산해요.', en: 'I go hiking with friends on weekends.' } },
    { id: 'camping', ko: '캠핑', en: 'camping', level: 3, pos: 'noun', emoji: '🏕️', rom: 'kaemping', enAlt: ['go camping'],
      note: '캠핑을 가요, or just 캠핑 가요 = I go camping.',
      example: { ko: '캠핑 좋아해요?', en: 'Do you like camping?' } },

    // ---- More words ----
    { id: 'painting', ko: '그림', en: 'drawing / painting', level: 1, pos: 'noun', emoji: '🖍️', rom: 'geurim',
      avoid: ['photo', 'draw'], enAlt: ['picture', 'art'],
      note: 'A picture you draw or paint: 그림을 그려요 (I draw). A photo is 사진.',
      example: { ko: '이 그림 정말 좋아요!', en: 'I really like this painting!' } },
    { id: 'piano', ko: '피아노', en: 'piano', level: 1, pos: 'noun', emoji: '🎹', rom: 'piano',
      note: 'You “hit” (치다) a piano in Korean: 피아노를 쳐요 = I play the piano.',
      example: { ko: '피아노 쳐요?', en: 'Do you play the piano?' } },
    { id: 'learn', ko: '배워요', en: 'learn', level: 1, pos: 'verb', emoji: '📚', rom: 'baewoyo', dict: '배우다',
      accept: ['배우어요'], avoid: ['day:study'], enAlt: ['take lessons', 'learning'],
      note: '배우다 → 배우 + 어요 → 배워요 (ㅜ + ㅓ merge into ㅝ). What you learn takes 을/를: 한국어를 배워요.',
      example: { ko: '요즘 수영을 배워요.', en: 'I’m learning to swim these days.' } },
    { id: 'playpiano', ko: '쳐요', en: 'play (piano, tennis…)', level: 2, pos: 'verb', emoji: '🥁', rom: 'chyeoyo', dict: '치다',
      accept: ['치어요'], avoid: ['play', 'day:do'], enAlt: ['play the piano', 'play piano', 'play tennis', 'hit'],
      note: '치다 (literally “to hit”) → 치 + 어요 → 쳐요 (ㅣ + ㅓ merge into ㅕ). It’s for the piano, the guitar and the drums, and for tennis or golf: 테니스를 쳐요.',
      example: { ko: '주말에 테니스를 쳐요.', en: 'I play tennis on weekends.' } },
    { id: 'karaoke', ko: '노래방', en: 'karaoke (room)', level: 2, pos: 'noun', emoji: '🎙️', rom: 'noraebang',
      enAlt: ['karaoke', 'singing room', 'noraebang'],
      note: '노래 (song) + 방 (room): a private room you rent with friends to sing.',
      example: { ko: '같이 노래방에 가요!', en: 'Let’s go to karaoke together!' } },
    { id: 'practise', ko: '연습해요', en: 'practise', level: 2, pos: 'verb', emoji: '🔁', rom: 'yeonseupaeyo', pron: '연스패요',
      dict: '연습하다', enAlt: ['rehearse', 'train'],
      note: '연습 (practice) + 해요. The ㅂ and ㅎ blend into ㅍ: [연스패요].',
      example: { ko: '매일 피아노를 연습해요.', en: 'I practise the piano every day.' } },
    { id: 'promise', ko: '약속', en: 'plans (to meet) / promise', level: 2, pos: 'noun', emoji: '🤝', rom: 'yaksok', pron: '약쏙',
      avoid: ['plan'], enAlt: ['appointment', 'plans', 'engagement'],
      note: 'An arrangement to meet someone, or a promise: 약속이 있어요 = I have plans. After ㄱ, the ㅅ is tense: [약쏙].',
      example: { ko: '주말에 약속 있어요?', en: 'Do you have plans this weekend?' } },
    { id: 'nextyear', ko: '내년', en: 'next year', level: 3, pos: 'noun', emoji: '🎆', rom: 'naenyeon',
      note: '내 (coming) + 년 (year). This year is 올해, and last year is 작년.',
      example: { ko: '내년에 한국에 갈 거예요.', en: 'I’m going to Korea next year.' } },
    { id: 'definitely', ko: '꼭', en: 'definitely / for sure', level: 3, pos: 'adverb', emoji: '✅', rom: 'kkok',
      enAlt: ['surely', 'certainly', 'without fail', 'be sure to'],
      note: 'For plans and promises you really mean: 꼭 갈게요! (I’ll be there for sure!) In a request, it means “be sure to”: 꼭 오세요!',
      example: { ko: '다음 주에 꼭 갈 거예요!', en: 'I’m definitely going next week!' } },
    { id: 'dream', ko: '꿈', en: 'dream', level: 3, pos: 'noun', emoji: '🌠', rom: 'kkum', enAlt: ['dreams'],
      note: 'Both a dream for the future and a dream at night. To dream is 꿈을 꿔요.',
      example: { ko: '제 꿈은 가수예요.', en: 'My dream is to be a singer.' } },

    // ---- More words: sport, free time and plans ----
    { id: 'sport', ko: '운동', en: 'sport / exercise', level: 1, pos: 'noun', emoji: '🤸', rom: 'undong',
      avoid: ['day:exercise'], enAlt: ['sports', 'exercise', 'workout'],
      note: 'Exercise, and sport in general. 운동을 해요 (or just 운동해요) = I exercise / I work out.',
      example: { ko: '무슨 운동 좋아해요?', en: 'What sports do you like?' } },
    { id: 'guitar', ko: '기타', en: 'guitar', level: 1, pos: 'noun', emoji: '🎸', rom: 'gita', avoid: ['shopping:other'],
      note: 'You “hit” a guitar, like a piano: 기타를 쳐요 = I play the guitar. In lists and on forms, 기타 also means “other”.',
      example: { ko: '이거 제 기타예요.', en: 'This is my guitar.' } },
    { id: 'drama', ko: '드라마', en: 'TV drama', level: 1, pos: 'noun', emoji: '📺', rom: 'deurama',
      enAlt: ['drama', 'dramas', 'K-drama', 'K-dramas', 'TV series', 'series', 'soap opera'],
      note: 'A TV series, like the K-dramas you may know. You watch it with 보다: 드라마를 봐요. Subtitles are 자막.',
      example: { ko: '이 드라마 정말 재미있어요!', en: 'This drama is really good!' } },
    { id: 'tennis', ko: '테니스', en: 'tennis', level: 1, pos: 'noun', emoji: '🎾', rom: 'teniseu',
      note: 'Sports with a racket, and golf, are “hit” (치다): 테니스를 쳐요. Most other sports take 하다: 축구를 해요.',
      example: { ko: '친구하고 테니스를 쳐요.', en: 'I play tennis with a friend.' } },
    { id: 'baseball', ko: '야구', en: 'baseball', level: 2, pos: 'noun', emoji: '⚾', rom: 'yagu',
      note: 'One of Korea’s favourite sports to watch. Playing it takes 하다 (야구를 해요); watching it is 야구를 봐요.',
      example: { ko: '아빠는 야구를 정말 좋아해요.', en: 'My dad really loves baseball.' } },
    { id: 'run', ko: '뛰어요', en: 'run', level: 2, pos: 'verb', emoji: '🏃‍♀️', rom: 'ttwieoyo', dict: '뛰다',
      enAlt: ['jog', 'go running', 'go for a run'],
      note: '뛰 + 어요 → 뛰어요: ㅟ doesn’t merge with 어, so both syllables stay. Walking is 걸어요; running is 뛰어요.',
      example: { ko: '아침에 공원에서 뛰어요.', en: 'I go running in the park in the morning.' } },
    { id: 'make', ko: '만들어요', en: 'make', level: 2, pos: 'verb', emoji: '🧶', rom: 'mandeureoyo', pron: '만드러요',
      dict: '만들다', enAlt: ['create', 'make something'],
      note: 'For food, crafts, videos… The ㄹ stays: 만들 + 어요 → 만들어요, said [만드러요]. For plans, an ㄹ stem adds nothing: 만들 거예요.',
      example: { ko: '주말에 빵을 만들어요.', en: 'I make bread on weekends.' } },
    { id: 'team', ko: '팀', en: 'team', level: 2, pos: 'noun', emoji: '🎽', rom: 'tim', enAlt: ['teams'],
      note: 'For sport and for work: 우리 팀 = our team (or my team at the office). Supporting a team is 응원해요 (cheering for it).',
      example: { ko: '어느 팀을 응원해요?', en: 'Which team do you support?' } },
    // A phrase, not a verb, so Verb Magic leaves it out: it would ask for 안 잘해요, but “not good at it” is 잘 못해요.
    { id: 'goodat', ko: '잘해요', en: 'be good at (something)', level: 2, pos: 'phrase', emoji: '⭐', rom: 'jalhaeyo',
      dict: '잘하다', enAlt: ['good at', 'is good at', "I'm good at it", 'do well', 'do it well'],
      note: '잘 (well) + 해요, written as one word. What you’re good at takes 을/를: 수영을 잘해요. Not good at it? 잘 못해요.',
      example: { ko: '와, 노래를 정말 잘해요!', en: 'Wow, you’re really good at singing!' } },
    { id: 'club', ko: '동아리', en: 'club (at school or university)', level: 3, pos: 'noun', emoji: '👯', rom: 'dongari',
      enAlt: ['club', 'student club', 'school club', 'society'],
      note: 'A student club, like a photo or hiking club: 사진 동아리, 등산 동아리. Joining one is 동아리에 들어가요. Adults’ hobby clubs are usually called 동호회.',
      example: { ko: '무슨 동아리에 들어가고 싶어요?', en: 'Which club do you want to join?' } },
    { id: 'match', ko: '경기', en: 'match / game (sport)', level: 3, pos: 'noun', emoji: '🏟️', rom: 'gyeonggi',
      enAlt: ['match', 'game', 'sports match', 'sports game'],
      note: 'A sports match: 축구 경기 = a football match. You watch one (경기를 봐요) or win one (경기에서 이겨요). A video game is 게임.',
      example: { ko: '오늘 저녁에 야구 경기가 있어요.', en: 'There’s a baseball game this evening.' } },
    { id: 'win', ko: '이겨요', en: 'win', level: 3, pos: 'verb', emoji: '🏆', rom: 'igyeoyo', dict: '이기다',
      accept: ['이기어요'], enAlt: ['beat', 'defeat', 'win a game'],
      note: '이기 + 어요 → 이겨요 (ㅣ + ㅓ merge into ㅕ). Who you beat takes 을/를: 형을 이겼어요 = I beat my brother. Losing is 져요 (지다).',
      example: { ko: '우리 팀이 이겼어요!', en: 'Our team won!' } },
    { id: 'collect', ko: '모아요', en: 'collect / save up', level: 3, pos: 'verb', emoji: '🗃️', rom: 'moayo', dict: '모으다',
      enAlt: ['collect', 'gather', 'save', 'save money', 'save up money'],
      note: '모으 + 아요 → 모아요: the ㅡ drops, and the ㅗ before it brings 아 (like 바빠요). A hobby: 우표를 모아요 (I collect stamps). Money: 돈을 모아요 (I’m saving up).',
      example: { ko: '요즘 돈을 모아요.', en: 'I’m saving up these days.' } },
    { id: 'mostly', ko: '주로', en: 'mostly / mainly', level: 3, pos: 'adverb', emoji: '🎯', rom: 'juro',
      avoid: ['day:usually'], enAlt: ['mainly', 'mostly', 'usually', 'chiefly'],
      note: 'For the thing you do most of the time: 주말에 주로 뭐 해요? = What do you mostly do at weekends? It’s close to 보통 (usually).',
      example: { ko: '저는 주로 지하철을 타요.', en: 'I mostly take the subway.' } },
    { id: 'nexttime', ko: '다음에', en: 'next time', level: 3, pos: 'adverb', emoji: '🤞', rom: 'daeume', pron: '다으메',
      enAlt: ['another time', 'some other time', 'later'],
      note: 'A friendly way to put off an invitation, or to make one: 다음에 같이 가요! = Let’s go together next time! 다음 on its own means “next”: 다음 주.',
      example: { ko: '미안해요. 다음에 만나요!', en: 'Sorry. Let’s meet up another time!' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-hobby', en: 'My hobby is gaming.', ko: '제 취미는 게임이에요.',
      tiles: ['제', '취미는', '게임이에요'], gloss: ['my', 'hobby (topic)', 'is games'], words: ['hobby', 'game'],
      traps: [{ tile: '게임예요', why: '게임 ends in a consonant (받침), so it takes 이에요. 예요 goes after vowels.' }] },
    { id: 's-music', en: 'I listen to music at home.', ko: '집에서 음악을 들어요.',
      tiles: ['집에서', '음악을', '들어요'], gloss: ['at home', 'music (object)', 'listen'], words: ['day:home', 'music', 'listen'],
      alts: [['음악을', '집에서', '들어요']],
      traps: [
        { tile: '집에', why: 'Listening to music is something you do there, so the place takes 에서: 집에서.' },
        { tile: '듣어요', why: '듣다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 들어요.' },
      ] },
    { id: 's-play', en: "I'm hanging out with a friend today.", ko: '오늘 친구하고 놀아요.',
      tiles: ['오늘', '친구하고', '놀아요'], gloss: ['today', 'with a friend', 'play / hang out'],
      words: ['day:today', 'day:friend', 'play'], alts: [['친구하고', '오늘', '놀아요']],
      traps: [
        { tile: '놀았어요', why: 'The English says “I’m hanging out”, not “hung out”, so use the present: 놀아요.' },
        { tile: '노라요', why: '놀다 keeps its ㄹ in writing: 놀 + 아요 → 놀아요. It only sounds like [노라요].' },
        { tile: '오늘에', why: '오늘 (today) works on its own as a time word: no 에.' },
      ] },
    { id: 's-trip', en: "I'm going on a trip tomorrow.", ko: '내일 여행을 가요.',
      tiles: ['내일', '여행을', '가요'], gloss: ['tomorrow', 'trip (object)', 'go'], words: ['day:tomorrow', 'trip', 'day:go'],
      alts: [['여행을', '내일', '가요']],
      traps: [
        { tile: '갔어요', why: '내일 (tomorrow) is in the future, so 갔어요 (went) doesn’t fit. Use 가요 (or 갈 거예요).' },
        { tile: '와요', why: '와요 means “come”. For “go”, use 가요.' },
      ] },

    // ---- Level 2 ----
    { id: 's-sing', level: 2, en: 'My friend is singing a song.', ko: '친구가 노래를 불러요.',
      tiles: ['친구가', '노래를', '불러요'], gloss: ['friend (subject)', 'song (object)', 'sings'], words: ['day:friend', 'song', 'sing'],
      traps: [
        { tile: '친구를', why: 'Your friend is the one singing (the subject), so it takes 가: 친구가.' },
        { tile: '부러요', why: '부르다 is 르-irregular: 르 turns into ㄹ러 → 불러요.' },
      ] },
    { id: 's-photo', level: 2, en: 'I take photos at the café.', ko: '카페에서 사진을 찍어요.',
      tiles: ['카페에서', '사진을', '찍어요'], gloss: ['at the café', 'photo (object)', 'take'], words: ['cafe:cafe', 'photo', 'take'],
      alts: [['사진을', '카페에서', '찍어요']],
      traps: [
        { tile: '카페에', why: 'Taking photos is something you do there, so the place takes 에서: 카페에서.' },
        { tile: '그려요', why: '그려요 means “draw”. Photos are taken: 사진을 찍어요.' },
      ] },
    { id: 's-draw', level: 2, en: 'What are you drawing now?', ko: '지금 뭐 그려요?',
      tiles: ['지금', '뭐', '그려요'], gloss: ['now', 'what', 'draw'], words: ['day:now', 'day:what', 'draw'],
      traps: [
        { tile: '찍어요', why: '찍어요 is for photos. For drawing, use 그려요.' },
        { tile: '그렸어요', why: 'The English says “are drawing” (now), so use the present: 그려요.' },
      ] },
    { id: 's-noswim', level: 2, en: "I'm not swimming today.", ko: '오늘은 수영 안 해요.',
      tiles: ['오늘은', '수영', '안', '해요'], gloss: ['today (topic)', 'swimming', 'not', 'do'], words: ['day:today', 'swim'],
      traps: [{ tile: '수영해요', why: '수영하다 is 수영 (a noun) + 하다, so 안 goes right before 해요: 수영 안 해요.' }] },
    { id: 's-stroll', level: 2, en: 'I take a walk with a friend in the evening.', ko: '저녁에 친구하고 산책해요.',
      tiles: ['저녁에', '친구하고', '산책해요'], gloss: ['in the evening', 'with a friend', 'take a walk'],
      words: ['day:evening', 'day:friend', 'stroll'], alts: [['친구하고', '저녁에', '산책해요']],
      traps: [
        { tile: '저녁에서', why: 'To say when something happens, use 에, not 에서: 저녁에 (in the evening).' },
        { tile: '산책했어요', why: 'The English is in the present (I take a walk), so use 산책해요. 산책했어요 is the past.' },
        { tile: '산책헤요', why: 'Every 하다 verb becomes 해요, with ㅐ: 산책해요.' },
      ] },
    { id: 's-dance', level: 2, en: 'I dance at concerts.', ko: '콘서트에서 춤춰요.',
      tiles: ['콘서트에서', '춤춰요'], gloss: ['at a concert', 'dance'], words: ['concert', 'dance'],
      traps: [{ tile: '콘서트에', why: 'Dancing is something you do there, so the place takes 에서: 콘서트에서.' }] },

    // ---- Level 3 ----
    { id: 's-concert', level: 3, en: "I'm going to a concert next week.", ko: '다음 주에 콘서트에 갈 거예요.',
      tiles: ['다음 주에', '콘서트에', '갈', '거예요'], gloss: ['next week', 'to a concert', 'go (future form)', 'will / going to'],
      words: ['nextweek', 'concert', 'willgo'], alts: [['콘서트에', '다음 주에', '갈', '거예요']],
      traps: [
        { tile: '갔어요', why: '다음 주 (next week) is in the future, so use 갈 거예요. 갔어요 means “went”.' },
        { tile: '콘서트에서', why: '에 marks where you are going. 에서 marks where an action happens.' },
        { tile: '가을', why: 'After a vowel, just put ㄹ under it: 가 → 갈 거예요. (가을 means “autumn”!)' },
      ] },
    { id: 's-soccer', level: 3, en: "I'm going to play football tomorrow.", ko: '내일 축구를 할 거예요.',
      tiles: ['내일', '축구를', '할', '거예요'], gloss: ['tomorrow', 'football (object)', 'do (future form)', 'will / going to'],
      words: ['day:tomorrow', 'soccer', 'willdo'], alts: [['축구를', '내일', '할', '거예요']],
      traps: [
        { tile: '했어요', why: '내일 (tomorrow) is in the future, so use 할 거예요. 했어요 means “did”.' },
        { tile: '놀', why: 'Sports use 하다: 축구를 할 거예요. 놀다 is for playing around or hanging out.' },
      ] },
    { id: 's-plan', level: 3, en: 'Do you have any plans for your time off?', ko: '휴가 계획이 있어요?',
      tiles: ['휴가', '계획이', '있어요'], gloss: ['holiday (time off)', 'plan (subject)', 'is there? / do you have?'],
      words: ['holiday', 'plan', 'day:have'],
      traps: [{ tile: '계획을', why: '있어요 says that something is there. The thing you have is the subject, so it takes 이: 계획이 있어요?' }] },
    { id: 's-bike', level: 3, en: 'I want to learn to ride a bike.', ko: '자전거를 배우고 싶어요.',
      tiles: ['자전거를', '배우고', '싶어요'], gloss: ['bicycle (object)', 'learn', 'want to'], words: ['bike', 'wanttolearn'],
      traps: [{ tile: '배워요', why: '고 싶어요 goes straight onto the stem: 배우 + 고 싶어요. Don’t conjugate the verb first.' }] },
    { id: 's-camping', level: 3, en: "I'm going camping in the school holidays.", ko: '방학에 캠핑을 갈 거예요.',
      tiles: ['방학에', '캠핑을', '갈', '거예요'], gloss: ['in the school holidays', 'camping (object)', 'go (future form)', 'will / going to'],
      words: ['vacation', 'camping', 'willgo'], alts: [['캠핑을', '방학에', '갈', '거예요']],
      traps: [
        { tile: '갔어요', why: 'This is a plan, so use 갈 거예요. 갔어요 means “went”.' },
        { tile: '방학에서', why: 'To say when something happens, use 에, not 에서: 방학에.' },
      ] },
    { id: 's-hiking', level: 3, en: 'I usually go hiking on weekends.', ko: '보통 주말에 등산해요.',
      tiles: ['보통', '주말에', '등산해요'], gloss: ['usually', 'on weekends', 'go hiking'],
      words: ['day:usually', 'day:weekend', 'hiking'], alts: [['주말에', '보통', '등산해요']],
      traps: [{ tile: '주말에서', why: 'To say when something happens, use 에, not 에서: 주말에 (on weekends).' }] },

    // ---- More sentences ----
    { id: 's-painting', en: "I'm learning to draw in the evenings.", ko: '저녁에 그림을 배워요.',
      tiles: ['저녁에', '그림을', '배워요'], gloss: ['in the evening', 'drawing (object)', 'learn'],
      words: ['day:evening', 'painting', 'learn'], alts: [['그림을', '저녁에', '배워요']],
      traps: [
        { tile: '저녁에서', why: 'To say when something happens, use 에, not 에서: 저녁에 (in the evening).' },
        { tile: '그려요', why: '그려요 means “draw”. The English says “learning to draw”: 그림을 배워요.' },
      ] },
    { id: 's-piano', level: 2, en: 'My friend plays the piano, and I sing.', ko: '친구가 피아노를 쳐요. 저는 노래를 불러요.',
      tiles: ['친구가', '피아노를', '쳐요', '저는', '노래를', '불러요'],
      gloss: ['friend (subject)', 'piano (object)', 'plays', 'I (topic)', 'song (object)', 'sing'],
      words: ['day:friend', 'piano', 'playpiano', 'people:me', 'song', 'sing'],
      traps: [
        { tile: '놀아요', why: '놀아요 is playing for fun or hanging out. For the piano, use 치다: 피아노를 쳐요.' },
        { tile: '부러요', why: '부르다 is 르-irregular: 르 turns into ㄹ러 → 불러요.' },
      ] },
    { id: 's-nextyear', level: 3, en: "I'm definitely going to learn the piano next year.", ko: '내년에 꼭 피아노를 배울 거예요.',
      tiles: ['내년에', '꼭', '피아노를', '배울', '거예요'],
      gloss: ['next year', 'definitely', 'piano (object)', 'learn (future form)', 'will / going to'],
      words: ['nextyear', 'definitely', 'piano', 'learn'], alts: [['내년에', '피아노를', '꼭', '배울', '거예요']],
      traps: [
        { tile: '작년에', why: '작년 means “last year”. “Next year” is 내년.' },
        { tile: '배웠어요', why: '내년 (next year) is in the future, so use 배울 거예요. 배웠어요 means “learned”.' },
        { tile: '배우을', why: 'After a vowel, just put ㄹ under it: 배우 → 배울 거예요.' },
      ] },

    // ---- More sentences: sport, free time and plans ----
    { id: 's-goodat', level: 2, en: 'My older sister is good at sports. She runs every morning.', ko: '언니는 운동을 잘해요. 매일 아침 뛰어요.',
      tiles: ['언니는', '운동을', '잘해요', '매일', '아침', '뛰어요'],
      gloss: ['older sister (topic)', 'sport (object)', 'is good at', 'every day', 'morning', 'runs'],
      words: ['people:unni', 'sport', 'goodat', 'day:everyday', 'day:morning', 'run'],
      traps: [
        { tile: '운동이', why: 'What you’re good at is the object of 잘해요, so it takes 을/를: 운동을 잘해요.' },
        { tile: '걸어요', why: '걸어요 means “walk”. “Run” is 뛰어요.' },
      ] },
    { id: 's-tennis', level: 3, en: 'Are you free tomorrow? Let’s play tennis together!', ko: '내일 시간 있어요? 같이 테니스를 쳐요!',
      tiles: ['내일', '시간', '있어요', '같이', '테니스를', '쳐요'],
      gloss: ['tomorrow', 'time', 'is there?', 'together', 'tennis (object)', 'play (hit)'],
      words: ['day:tomorrow', 'numbers:hour', 'day:have', 'day:together', 'tennis', 'playpiano'],
      alts: [['내일', '시간', '있어요', '테니스를', '같이', '쳐요']],
      traps: [
        { tile: '내일에', why: '내일 (tomorrow) works on its own as a time word: no 에.' },
        { tile: '없어요', why: '없어요 means “there isn’t”. To ask if someone is free: 시간 있어요?' },
        { tile: '놀아요', why: '놀아요 is playing for fun or hanging out. Tennis is “hit”: 테니스를 쳐요.' },
      ] },
    { id: 's-drama', level: 3, en: 'In the evenings, I mostly watch dramas.', ko: '저녁에는 주로 드라마를 봐요.',
      tiles: ['저녁에는', '주로', '드라마를', '봐요'], gloss: ['in the evening (topic)', 'mostly', 'drama (object)', 'watch'],
      words: ['day:evening', 'mostly', 'drama', 'day:watch'], alts: [['저녁에는', '드라마를', '주로', '봐요']],
      traps: [
        { tile: '들어요', why: '들어요 means “listen”. Dramas are watched: 드라마를 봐요.' },
        { tile: '저녁에서는', why: 'To say when something happens, use 에, not 에서: 저녁에는 (in the evenings).' },
        { tile: '봤어요', why: 'The English is in the present (I mostly watch), so use 봐요. 봤어요 is the past.' },
      ] },
    { id: 's-baseball', level: 3, en: 'Did you watch the baseball game? Our team won!', ko: '야구 경기 봤어요? 우리 팀이 이겼어요!',
      tiles: ['야구', '경기', '봤어요', '우리', '팀이', '이겼어요'],
      gloss: ['baseball', 'game (match)', 'watched', 'our', 'team (subject)', 'won'],
      words: ['baseball', 'match', 'past:saw', 'people:we', 'team', 'win'],
      traps: [
        { tile: '팀을', why: 'The team is the one that won (the subject), so it takes 이: 우리 팀이 이겼어요. 팀을 이겼어요 would mean someone beat the team!' },
        { tile: '이겨요', why: 'The game is over, so use the past: 이겼어요 (won).' },
      ] },
    { id: 's-club', level: 3, en: 'I’m learning the guitar at my club.', ko: '동아리에서 기타를 배워요.',
      tiles: ['동아리에서', '기타를', '배워요'], gloss: ['at the club', 'guitar (object)', 'learn'],
      words: ['club', 'guitar', 'learn'], alts: [['기타를', '동아리에서', '배워요']],
      traps: [
        { tile: '동아리에', why: 'Learning is something you do there, so the place takes 에서: 동아리에서.' },
        { tile: '쳐요', why: '쳐요 means “play”. The English says “learning”: 배워요.' },
      ] },
    { id: 's-cookies', level: 3, en: 'Let’s make cookies together next time!', ko: '다음에 같이 쿠키를 만들어요!',
      tiles: ['다음에', '같이', '쿠키를', '만들어요'], gloss: ['next time', 'together', 'cookie (object)', 'make'],
      words: ['nexttime', 'day:together', 'cafe:cookie', 'make'], alts: [['다음에', '쿠키를', '같이', '만들어요']],
      traps: [
        { tile: '만들었어요', why: '다음에 (next time) is in the future, so 만들었어요 (made) doesn’t fit. To suggest it, use 만들어요.' },
        { tile: '만드러요', why: '만들다 keeps its ㄹ in writing: 만들 + 어요 → 만들어요. It only sounds like [만드러요].' },
      ] },
  ],
});
