/**
 * Honorifics (높임말), practised in the Honorifics game: showing respect for the
 * person you talk *about* (the one doing the action), where speech levels are
 * about the person you talk *to*.
 *   -(으)시-:        가요 → 가세요, 갔어요 → 가셨어요, 갈 거예요 → 가실 거예요.
 *   their own word:  자다 → 주무시다, 먹다 → 드시다, 집 → 댁, 이/가 → 께서, 한테 → 께.
 *   humble words:    what *you* do for them: 주다 → 드리다, 묻다 → 여쭤보다, 만나다 → 뵙다.
 *
 * card:  what a new learner sees first (📖 reopens it): title { ko, en }, text,
 *        sections [{ title { ko, en }, text, examples [{ ko, en }] }] (who honorifics are for;
 *                 how -(으)시- is made; verbs with a word of their own; respectful nouns,
 *                 께서 and 께; humble words),
 *        table [{ en, plain, honor }] (the special words),
 *        note (practical advice),
 *        wrong { respect, self, younger, child, friend, thing }: why a choice is wrong
 *                 (a plain form about someone you respect; an honorific about yourself,
 *                 a younger brother or sister, a child, a friend your age, a thing).
 * items: the same idea said about someone you respect and about someone else:
 *        id, level (1–3), note (what changes, and why),
 *        words (1–3 vocabulary refs, 'topic:id': the item opens once they're learned),
 *        honor { ko, en, answer, dict }: a sentence about someone you respect; `answer`
 *              (the blank) is the respectful word, `dict` its dictionary form,
 *        plain { ko, en, answer, dict, who }: the same sentence about someone else, in the
 *              same tense with the same ending; `who`: self | younger | child | friend | thing,
 *        traps [{ text, why }]: wrong forms learners really make (자세요, 가으세요,
 *              드리셨어요, 연세께서…), wrong in both sentences, each with its reason.
 * Levels: 1 = -(으)세요 in the present, and the commonest verbs with a word of their own;
 *         2 = the past -(으)셨어요, 말씀하세요, 편찮으세요, 있으세요 vs 계세요, polite questions;
 *         3 = respectful nouns, humble verbs, 돌아가셨어요, -(으)실 거예요.
 * Numbers are written in Hangul (여섯 시), the way they're read aloud.
 */
Mallang.content.registerHonorifics({
  card: {
    title: { ko: '높임말', en: 'Showing respect' },
    text: 'Speech levels are about who you talk **to**. Honorifics are about who you talk **about**: when the person doing something is someone you respect, the verb shows it with **-(으)시-** (가요 → **가세요**). A few words have a respectful form of their own (자요 → **주무세요**, 집 → **댁**), and humble words lower **you** instead (줘요 → **드려요**).',
    sections: [
      {
        title: { ko: '누구를 높여요?', en: 'Who gets respect' },
        text: 'Show respect when the person you’re talking **about** is above you: grandparents, parents, teachers, your boss, customers, older people. Never about **yourself**, and not about a younger brother or sister, a child, a friend your age, or a thing. The person you’re talking **to** counts too when you ask about them: **어디 가세요?** is polite to any adult.',
        examples: [
          { ko: '할머니께서 주무세요.', en: 'Grandma is sleeping.' },
          { ko: '손님, 뭐 찾으세요?', en: 'What are you looking for? (shop staff to a customer)' },
          { ko: '저는 학교에 가요.', en: 'I’m going to school. (about yourself: never 가세요)' },
        ],
      },
      {
        title: { ko: '-(으)시-', en: 'Adding -(으)시-' },
        text: 'Put **-(으)시-** on the stem: **-시-** after a vowel, **-으시-** after a consonant. With -어요 it becomes **-(으)세요**: 가다 → **가세요**, 읽다 → **읽으세요**. The past is **-(으)셨어요** (가셨어요), the future **-(으)실 거예요** (가실 거예요). A final ㄹ drops: 살다 → **사세요**; in 듣다 and 걷다, ㄷ becomes ㄹ: **들으세요**. Adjectives take it too: **바쁘세요**.',
        examples: [
          { ko: '할머니는 부산에 사세요.', en: 'My grandma lives in Busan.' },
          { ko: '아버지께서 신문을 읽으셨어요.', en: 'My father read the newspaper.' },
          { ko: '사장님은 요즘 바쁘세요.', en: 'The boss is busy these days.' },
        ],
      },
      {
        title: { ko: '드세요 · 주무세요 · 계세요', en: 'Verbs with a word of their own' },
        text: 'A few verbs have a respectful word of their own: 먹다 / 마시다 → **드시다**, 자다 → **주무시다**, 있다 (be somewhere) → **계시다**, 말하다 → **말씀하시다**, 아프다 (be ill) → **편찮으시다**, 죽다 → **돌아가시다**. Use the word: **주무세요**, not 자세요; **계세요**, not 있으세요. But 있다 for having just takes -(으)시-: **시간 있으세요?**',
        examples: [
          { ko: '할아버지께서 저녁을 드세요.', en: 'Grandpa is having dinner.' },
          { ko: '어머니는 지금 회사에 계세요.', en: 'My mother is at work right now.' },
          { ko: '선생님, 내일 시간 있으세요?', en: 'Are you free tomorrow? (to a teacher)' },
        ],
      },
      {
        title: { ko: '댁 · 연세 · 께서', en: 'Respectful nouns, 께서 and 께' },
        text: 'Some nouns have a respectful word too: 집 → **댁**, 나이 → **연세**, 이름 → **성함**, 생일 → **생신**, 말 → **말씀**, 밥 → **진지** (mostly to grandparents; **식사** works with anyone). They count most when you speak to an older person (**연세가 어떻게 되세요?**); in casual talk, 할머니 집 is common too. **께서** is the respectful 이/가, and **께** the respectful 한테 (to). In everyday speech they’re optional: **할머니가 주무세요** is fine too.',
        examples: [
          { ko: '할머니 댁은 부산이에요.', en: 'Grandma’s house is in Busan.' },
          { ko: '할아버지는 연세가 많으세요.', en: 'My grandfather is quite old.' },
          { ko: '사장님께서 전화하셨어요.', en: 'The boss called.' },
        ],
      },
      {
        title: { ko: '드려요 · 여쭤봐요 · 봬요', en: 'Humble words for what you do' },
        text: 'When **you** do something for someone you respect, you never honour yourself: a humble word lowers you instead. 주다 → **드리다**, 묻다 → **여쭤보다**, 만나다 → **뵙다** (뵈어요, or **봬요**), 데리고 가다 → **모시고 가다**, 말하다 → **말씀드리다**. In the same way, “I” is **저** and “we” is **저희**. 드리다 and 모시다 are always expected; the others count most when you speak to the person themselves (**내일 봬요!**).',
        examples: [
          { ko: '어머니께 전화를 드렸어요.', en: 'I called my mother.' },
          { ko: '선생님, 내일 봬요!', en: 'See you tomorrow! (to a teacher)' },
          { ko: '제가 할머니를 모시고 갈게요.', en: 'I’ll take Grandma there.' },
        ],
      },
    ],
    table: [
      { en: 'eat, drink', plain: '먹다 · 마시다', honor: '드시다' },
      { en: 'sleep', plain: '자다', honor: '주무시다' },
      { en: 'be (somewhere)', plain: '있다', honor: '계시다' },
      { en: 'say, speak', plain: '말하다', honor: '말씀하시다' },
      { en: 'be ill', plain: '아프다', honor: '편찮으시다' },
      { en: 'die', plain: '죽다', honor: '돌아가시다' },
      { en: 'home, house', plain: '집', honor: '댁' },
      { en: 'age', plain: '나이', honor: '연세' },
      { en: 'name', plain: '이름', honor: '성함' },
      { en: 'birthday', plain: '생일', honor: '생신' },
      { en: 'meal', plain: '밥', honor: '진지' },
      { en: 'who does it (subject)', plain: '이 / 가', honor: '께서' },
      { en: 'to (a person)', plain: '한테', honor: '께' },
      { en: 'give (to them)', plain: '주다', honor: '드리다' },
      { en: 'ask (them)', plain: '묻다 · 물어보다', honor: '여쭤보다' },
      { en: 'meet, see (them)', plain: '만나다', honor: '뵙다' },
    ],
    note: 'Not sure? With anyone older, or anyone you don’t know well, use honorifics: a little too much respect is safer than too little. Never use them about yourself: **저는 가요**, not 저는 가세요. And don’t honour things: shops often say **커피 나오셨습니다** (your coffee is ready), but it’s a well-known mistake; the coffee isn’t a person: **커피 나왔습니다**.',
    wrong: {
      respect: 'Someone you respect is in this sentence, so show it: -(으)시- on their verb, their own special word (주무세요, 연세), or a humble word for what you do for them (드렸어요, 봬요).',
      self: 'This sentence is about you, and you never honour yourself: use the plain form.',
      younger: 'A younger brother or sister doesn’t get honorifics: use the plain form. Respectful and humble words (주무세요, 드렸어요) are for people above you.',
      child: 'A child doesn’t get honorifics or humble words, even when you speak politely to an adult about them: use the plain form.',
      friend: 'A friend your age doesn’t get honorifics or humble words when you talk about them: use the plain form. (Speaking politely **to** an adult your age, 어디 가세요? is still fine.)',
      thing: 'Honorifics are for people, never for things or animals: use the plain form.',
    },
  },
  items: [
    // Level 1: -(으)세요 in the present, and the commonest verbs with a word of their own.
    { id: 'sleep', level: 1, words: ['day:sleep', 'day:now'],
      honor: { ko: '할머니께서 지금 주무세요.', en: 'Grandma is sleeping now.', answer: '주무세요', dict: '주무시다' },
      plain: { ko: '동생이 지금 자요.', en: 'My little sister is sleeping now.', answer: '자요', dict: '자다', who: 'younger' },
      traps: [{ text: '자세요', why: 'Not the respectful form: 자다 has its own word, 주무시다 (주무세요). About anyone else, it’s just 자요.' }],
      note: '자다 → 주무시다: a verb with an honorific word of its own. 안녕히 주무세요 = Good night (to someone older).' },
    { id: 'eat', level: 1, words: ['day:eat', 'day:morning'],
      honor: { ko: '할아버지가 아침을 드세요.', en: 'Grandpa is having breakfast.', answer: '드세요', dict: '드시다' },
      plain: { ko: '아이가 아침을 먹어요.', en: 'The child is having breakfast.', answer: '먹어요', dict: '먹다', who: 'child' },
      traps: [
        { text: '먹어세요', why: 'Not a form: -(으)세요 goes on the stem 먹, not on 먹어요. For someone you respect eating, the word is 드세요; for anyone else, 먹어요.' },
        { text: '먹세요', why: 'Not a form: 먹 ends in a consonant, so it would need -으세요. For someone you respect eating, the word is 드세요; for anyone else, 먹어요.' },
      ],
      note: '먹다 → 드시다: a verb with an honorific word of its own. 맛있게 드세요 = Enjoy your meal. (먹으세요 is heard too, but 드세요 is more respectful.)' },
    { id: 'drink', level: 1, words: ['day:drink', 'cafe:coffee'],
      honor: { ko: '아버지는 아침에 커피를 드세요.', en: 'My father has coffee in the morning.', answer: '드세요', dict: '드시다' },
      plain: { ko: '저는 아침에 커피를 마셔요.', en: 'I have coffee in the morning.', answer: '마셔요', dict: '마시다', who: 'self' },
      traps: [
        { text: '마셔세요', why: '-(으)세요 goes on the stem (마시 + 세요), not on 마셔요. For someone you respect, the usual word is 드세요.' },
        { text: '들으세요', why: '들으세요 comes from 듣다 (listen). Drinking, for someone you respect, is 드세요 (드시다).' },
      ],
      note: '마시다 → 드시다, the same word as for eating. (마시세요 is heard too, but 드세요 is more respectful.)' },
    { id: 'in-class', level: 1, words: ['day:have', 'work:classroom'],
      honor: { ko: '선생님은 지금 교실에 계세요.', en: 'The teacher is in the classroom now.', answer: '계세요', dict: '계시다' },
      plain: { ko: '저는 지금 교실에 있어요.', en: 'I’m in the classroom now.', answer: '있어요', dict: '있다', who: 'self' },
      traps: [
        { text: '있으세요', why: 'For being somewhere, 있다 has its own respectful word, 계시다: 계세요. 있으세요 is for having something (시간 있으세요?). About yourself, it’s just 있어요.' },
        { text: '있세요', why: 'Not a form: after a consonant it’s -으세요. And for being somewhere, the respectful word is 계세요.' },
      ],
      note: '있다 → 계시다 for being somewhere: 있어요 → 계세요.' },
    { id: 'go', level: 1, words: ['day:go'],
      honor: { ko: '할머니께서 시장에 가세요.', en: 'Grandma is going to the market.', answer: '가세요', dict: '가시다' },
      plain: { ko: '저는 시장에 가요.', en: 'I’m going to the market.', answer: '가요', dict: '가다', who: 'self' },
      traps: [{ text: '가으세요', why: '가 ends in a vowel, so -세요 goes straight on: 가세요. -으세요 is for stems ending in a consonant (읽으세요).' }],
      note: '가요 → 가세요: -(으)시- shows respect for Grandma. About yourself, it’s just 가요.' },
    { id: 'come', level: 1, words: ['day:today', 'day:home'],
      honor: { ko: '오늘 부모님이 우리 집에 오세요.', en: 'My parents are coming to my place today.', answer: '오세요', dict: '오시다' },
      plain: { ko: '오늘 친구가 우리 집에 와요.', en: 'A friend is coming to my place today.', answer: '와요', dict: '오다', who: 'friend' },
      traps: [{ text: '와세요', why: '-(으)세요 goes on the stem 오, not on 와요: 오세요.' }],
      note: '오다 → 오시다: 와요 → 오세요. -(으)시- goes on the stem 오 (와요 is 오 + 아요).' },
    { id: 'find', level: 1, words: ['directions:find', 'day:phone'],
      honor: { ko: '할아버지가 핸드폰을 찾으세요.', en: 'Grandpa is looking for his phone.', answer: '찾으세요', dict: '찾으시다' },
      plain: { ko: '동생이 핸드폰을 찾아요.', en: 'My little brother is looking for his phone.', answer: '찾아요', dict: '찾다', who: 'younger' },
      traps: [
        { text: '찾세요', why: '찾 ends in a consonant, so it takes -으세요: 찾으세요.' },
        { text: '찾아세요', why: '-(으)세요 goes on the stem 찾, not on 찾아요: 찾으세요.' },
      ],
      note: '찾다 ends in a consonant, so -(으)시- needs its 으: 찾아요 → 찾으세요.' },
    { id: 'like', level: 1, words: ['weather:flower'],
      honor: { ko: '우리 할머니는 꽃을 좋아하세요.', en: 'My grandma likes flowers.', answer: '좋아하세요', dict: '좋아하시다' },
      plain: { ko: '저는 꽃을 좋아해요.', en: 'I like flowers.', answer: '좋아해요', dict: '좋아하다', who: 'self' },
      traps: [
        { text: '좋아해세요', why: '-(으)세요 goes on the stem 좋아하, not on 좋아해요: 좋아하세요.' },
        { text: '좋으세요', why: '좋다 (be good) can’t take 을/를: to like something, use 좋아하다.' },
      ],
      note: 'Every 하다 verb works the same way: 좋아해요 → 좋아하세요, 공부해요 → 공부하세요.' },
    { id: 'teach', level: 1, words: ['work:teach', 'hobbies:piano'],
      honor: { ko: '어머니는 피아노를 가르치세요.', en: 'My mother teaches piano.', answer: '가르치세요', dict: '가르치시다' },
      plain: { ko: '제 친구는 피아노를 가르쳐요.', en: 'My friend teaches piano.', answer: '가르쳐요', dict: '가르치다', who: 'friend' },
      traps: [
        { text: '가르쳐세요', why: '-(으)세요 goes on the stem 가르치, not on 가르쳐요: 가르치세요.' },
        { text: '가르키세요', why: '가르키다 isn’t standard Korean: “teach” is 가르치다 (가르치세요). 가리키다 means “point at”.' },
      ],
      note: '가르치다 ends in a vowel, so it just adds -세요: 가르쳐요 → 가르치세요.' },
    { id: 'listen', level: 1, words: ['hobbies:listen', 'hobbies:music'],
      honor: { ko: '할아버지는 매일 음악을 들으세요.', en: 'Grandpa listens to music every day.', answer: '들으세요', dict: '들으시다' },
      plain: { ko: '저는 매일 음악을 들어요.', en: 'I listen to music every day.', answer: '들어요', dict: '듣다', who: 'self' },
      traps: [
        { text: '듣으세요', why: '듣다 is irregular: its ㄷ turns into ㄹ before a vowel, so it’s 들으세요 (like 들어요).' },
        { text: '들세요', why: 'Keep the 으: 듣다 → 들으세요, like 들어요.' },
      ],
      note: '듣다 is ㄷ-irregular: the ㄷ becomes ㄹ before a vowel (들어요), and before -으세요 too: 들으세요.' },
    { id: 'sell', level: 1, words: ['shopping:sell', 'shopping:clothes'],
      honor: { ko: '할머니께서 시장에서 옷을 파세요.', en: 'Grandma sells clothes at the market.', answer: '파세요', dict: '파시다' },
      plain: { ko: '친구가 시장에서 옷을 팔아요.', en: 'My friend sells clothes at the market.', answer: '팔아요', dict: '팔다', who: 'friend' },
      traps: [
        { text: '팔으세요', why: '팔다 ends in ㄹ: the ㄹ drops before -세요, and there’s no 으: 파세요.' },
        { text: '팔세요', why: 'The ㄹ of 팔다 drops before ㅅ: 파세요.' },
      ],
      note: 'Verbs ending in ㄹ drop it before -세요, with no 으: 팔다 → 파세요, 살다 → 사세요.' },
    { id: 'tired', level: 1, words: ['feelings:tired'],
      honor: { ko: '어머니께서 요즘 많이 피곤하세요.', en: 'My mother is very tired these days.', answer: '피곤하세요', dict: '피곤하시다' },
      plain: { ko: '저는 요즘 많이 피곤해요.', en: 'I’m very tired these days.', answer: '피곤해요', dict: '피곤하다', who: 'self' },
      traps: [{ text: '피곤해세요', why: '-(으)세요 goes on the stem 피곤하, not on 피곤해요: 피곤하세요.' }],
      note: 'Adjectives take -(으)시- too when they describe someone you respect: 피곤해요 → 피곤하세요.' },
    { id: 'learn', level: 1, words: ['hobbies:learn', 'hobbies:painting'],
      honor: { ko: '할머니께서 요즘 그림을 배우세요.', en: 'Grandma is learning to paint these days.', answer: '배우세요', dict: '배우시다' },
      plain: { ko: '동생이 요즘 그림을 배워요.', en: 'My little brother is learning to paint these days.', answer: '배워요', dict: '배우다', who: 'younger' },
      traps: [{ text: '배워세요', why: '-(으)세요 goes on the stem 배우, not on 배워요: 배우세요.' }],
      note: '배우다 ends in a vowel, so it just adds -세요: 배워요 → 배우세요.' },
    { id: 'read', level: 1, words: ['people:teacher', 'people:child'],
      honor: { ko: '선생님께서 책을 읽으세요.', en: 'The teacher is reading a book.', answer: '읽으세요', dict: '읽으시다' },
      plain: { ko: '아이가 책을 읽어요.', en: 'The child is reading a book.', answer: '읽어요', dict: '읽다', who: 'child' },
      traps: [
        { text: '읽세요', why: '읽 ends in a consonant, so it takes -으세요: 읽으세요.' },
        { text: '읽어세요', why: '-(으)세요 goes on the stem 읽, not on 읽어요: 읽으세요.' },
      ],
      note: '읽다 ends in a consonant, so it takes -으세요: 읽어요 → 읽으세요.' },
    // Level 2: the past -(으)셨어요, 말씀하세요, 편찮으세요, 있으세요 vs 계세요, polite questions.
    { id: 'went', level: 2, words: ['past:went', 'directions:hospital'],
      honor: { ko: '할머니께서 어제 병원에 가셨어요.', en: 'Grandma went to the hospital yesterday.', answer: '가셨어요', dict: '가시다' },
      plain: { ko: '저는 어제 병원에 갔어요.', en: 'I went to the hospital yesterday.', answer: '갔어요', dict: '가다', who: 'self' },
      traps: [
        { text: '갔으세요', why: 'Not a form: in the past, -(으)시- comes first and makes -(으)셨어요: 가셨어요.' },
        { text: '가으셨어요', why: '가 ends in a vowel, so no 으: 가셨어요.' },
      ],
      note: 'In the past, -(으)시- + -었어요 becomes -(으)셨어요: 갔어요 → 가셨어요.' },
    { id: 'lunch', level: 2, words: ['past:ate', 'day:lunch', 'past:already'],
      honor: { ko: '아버지께서 벌써 점심을 드셨어요.', en: 'My father has already had lunch.', answer: '드셨어요', dict: '드시다' },
      plain: { ko: '동생이 벌써 점심을 먹었어요.', en: 'My little sister has already had lunch.', answer: '먹었어요', dict: '먹다', who: 'younger' },
      traps: [
        { text: '먹었으세요', why: 'Not a form: in the past, -(으)시- comes first and makes -(으)셨어요. For someone you respect eating, it’s 드셨어요; for anyone else, 먹었어요.' },
        { text: '들으셨어요', why: '들으셨어요 comes from 듣다 (listen). Eating, for someone you respect, is 드셨어요 (드시다).' },
      ],
      note: '드시다 in the past: 먹었어요 → 드셨어요. 점심 드셨어요? (Have you had lunch?) is an everyday greeting.' },
    { id: 'slept-well', level: 2, words: ['past:slept', 'past:lastnight'],
      honor: { ko: '할머니, 어젯밤에 잘 주무셨어요?', en: 'Grandma, did you sleep well last night?', answer: '주무셨어요', dict: '주무시다' },
      plain: { ko: '아이는 어젯밤에 잘 잤어요?', en: 'Did your child sleep well last night?', answer: '잤어요', dict: '자다', who: 'child' },
      traps: [{ text: '자셨어요', why: '자다 has its own respectful word, 주무시다: 주무셨어요. About anyone else, it’s just 잤어요.' }],
      note: 'A question to an older person about themselves takes the respectful form too: 잘 주무셨어요? is a morning greeting.' },
    { id: 'speak', level: 2, words: ['day:korean', 'work:class'],
      honor: { ko: '선생님께서는 수업 시간에 한국어로만 말씀하세요.', en: 'In class, the teacher speaks only Korean.', answer: '말씀하세요', dict: '말씀하시다' },
      plain: { ko: '저는 수업 시간에 한국어로만 말해요.', en: 'In class, I speak only Korean.', answer: '말해요', dict: '말하다', who: 'self' },
      traps: [
        { text: '말씀해세요', why: '-(으)세요 goes on the stem 말씀하, not on 말씀해요: 말씀하세요.' },
        { text: '말씀드리세요', why: '말씀드리다 is the humble word for telling someone above you. When someone you respect is the one speaking, it’s 말씀하세요; about yourself, just 말해요.' },
      ],
      note: '말하다 → 말씀하시다: a verb with an honorific word of its own (말씀 is a respectful word for what someone says).' },
    { id: 'unwell', level: 2, words: ['feelings:hurts', 'past:lastweek'],
      honor: { ko: '할아버지께서 지난주부터 편찮으세요.', en: 'Grandpa has been unwell since last week.', answer: '편찮으세요', dict: '편찮으시다' },
      plain: { ko: '동생이 지난주부터 아파요.', en: 'My little brother has been ill since last week.', answer: '아파요', dict: '아프다', who: 'younger' },
      traps: [
        { text: '편찮세요', why: '편찮다 ends in a consonant, so it takes -으세요: 편찮으세요.' },
        { text: '아파세요', why: 'Not a form: -(으)세요 goes on the stem 아프, not on 아파요. For someone you respect who is ill, the word is 편찮으세요.' },
      ],
      note: '아프다 → 편찮으시다 when someone you respect is ill (아프세요 is heard too, but 편찮으세요 is more respectful). For a part of the body, it’s always 아프세요: 다리가 아프세요.' },
    { id: 'free-time', level: 2, words: ['numbers:hour', 'work:boss'],
      honor: { ko: '사장님은 오늘 시간이 있으세요.', en: 'The boss is free today.', answer: '있으세요', dict: '있으시다' },
      plain: { ko: '제 친구는 오늘 시간이 있어요.', en: 'My friend is free today.', answer: '있어요', dict: '있다', who: 'friend' },
      traps: [
        { text: '계세요', why: '계시다 is only for being somewhere. Having something (time, a car…) is 있다: 있으세요 for someone you respect, 있어요 for anyone else.' },
        { text: '있세요', why: '있다 ends in a consonant, so it takes -으세요: 있으세요.' },
      ],
      note: '있다 has two respectful forms: 계시다 for being somewhere (교실에 계세요), 있으시다 for having (시간이 있으세요).' },
    { id: 'was-in-class', level: 2, words: ['past:earlier', 'work:classroom'],
      honor: { ko: '선생님은 아까 교실에 계셨어요.', en: 'The teacher was in the classroom earlier.', answer: '계셨어요', dict: '계시다' },
      plain: { ko: '저는 아까 교실에 있었어요.', en: 'I was in the classroom earlier.', answer: '있었어요', dict: '있다', who: 'self' },
      traps: [{ text: '있으셨어요', why: 'For being somewhere, the respectful word is 계시다: 계셨어요. 있으셨어요 is for having something. About yourself, it’s just 있었어요.' }],
      note: '계시다 in the past: 있었어요 → 계셨어요.' },
    { id: 'arrived', level: 2, words: ['past:came', 'directions:bus'],
      honor: { ko: '선생님께서 방금 오셨어요.', en: 'The teacher has just arrived.', answer: '오셨어요', dict: '오시다' },
      plain: { ko: '버스가 방금 왔어요.', en: 'The bus has just come.', answer: '왔어요', dict: '오다', who: 'thing' },
      traps: [
        { text: '와셨어요', why: '-(으)시- goes on the stem 오, not on 와요: 오셨어요.' },
        { text: '왔셨어요', why: 'Mark the past only once: 오 + 셨어요 = 오셨어요.' },
      ],
      note: '오다 → 오시다: 왔어요 → 오셨어요. A bus is a thing, so it never takes -(으)시-.' },
    { id: 'made', level: 2, words: ['cafe:kimchi', 'people:mother'],
      honor: { ko: '어머니께서 김치를 만드셨어요.', en: 'My mother made the kimchi.', answer: '만드셨어요', dict: '만드시다' },
      plain: { ko: '제가 김치를 만들었어요.', en: 'I made the kimchi.', answer: '만들었어요', dict: '만들다', who: 'self' },
      traps: [
        { text: '만들으셨어요', why: '만들다 ends in ㄹ: the ㄹ drops before -시-, and there’s no 으: 만드셨어요.' },
        { text: '만들셨어요', why: 'The ㄹ of 만들다 drops before ㅅ: 만드셨어요.' },
      ],
      note: 'A final ㄹ drops before -(으)시-: 만들었어요 → 만드셨어요.' },
    { id: 'weekend', level: 2, words: ['past:whatdid', 'past:did'],
      honor: { ko: '사장님, 주말에 뭐 하셨어요?', en: 'What did you do at the weekend? (to your boss)', answer: '하셨어요', dict: '하시다' },
      plain: { ko: '아이는 주말에 뭐 했어요?', en: 'What did your child do at the weekend?', answer: '했어요', dict: '하다', who: 'child' },
      traps: [
        { text: '해셨어요', why: '-(으)시- goes on the stem 하, not on 해요: 하셨어요.' },
        { text: '했셨어요', why: 'Mark the past only once: 하 + 셨어요 = 하셨어요.' },
      ],
      note: 'Asking an older person about themselves, use -(으)시-: 뭐 하셨어요? About a child, it’s just 뭐 했어요?' },
    { id: 'live', level: 2, words: ['people:live', 'directions:where'],
      honor: { ko: '선생님, 지금 어디 사세요?', en: 'Where do you live now? (to a teacher)', answer: '사세요', dict: '사시다' },
      plain: { ko: '그 친구는 지금 어디 살아요?', en: 'Where does that friend of yours live now?', answer: '살아요', dict: '살다', who: 'friend' },
      traps: [
        { text: '살으세요', why: '살다 ends in ㄹ: the ㄹ drops before -세요, and there’s no 으: 사세요.' },
        { text: '살세요', why: 'The ㄹ of 살다 drops before ㅅ: 사세요.' },
      ],
      note: '살다 → 사시다 (the ㄹ drops): 살아요 → 사세요. 어디 사세요? is the polite way to ask any adult.' },
    { id: 'busy', level: 2, words: ['feelings:busy', 'day:yesterday'],
      honor: { ko: '아버지는 어제 많이 바쁘셨어요.', en: 'My father was very busy yesterday.', answer: '바쁘셨어요', dict: '바쁘시다' },
      plain: { ko: '저는 어제 많이 바빴어요.', en: 'I was very busy yesterday.', answer: '바빴어요', dict: '바쁘다', who: 'self' },
      traps: [
        { text: '바빠셨어요', why: '-(으)시- goes on the stem 바쁘, not on 바빠요: 바쁘셨어요.' },
        { text: '바쁘었어요', why: '바쁘다 loses its ㅡ before 었: 바빴어요. With -(으)시-, it’s 바쁘셨어요.' },
      ],
      note: 'Adjectives take -(으)셨어요 too: 바빴어요 → 바쁘셨어요.' },
    { id: 'got-up', level: 2, words: ['past:gotup', 'numbers:oclock'],
      honor: { ko: '할아버지께서 여섯 시에 일어나셨어요.', en: 'Grandpa got up at six.', answer: '일어나셨어요', dict: '일어나시다' },
      plain: { ko: '아이가 여섯 시에 일어났어요.', en: 'The child got up at six.', answer: '일어났어요', dict: '일어나다', who: 'child' },
      traps: [
        { text: '일어났셨어요', why: 'Mark the past only once: 일어나 + 셨어요 = 일어나셨어요.' },
        { text: '일어났으세요', why: 'Not a form: in the past, -(으)시- comes first and makes -(으)셨어요: 일어나셨어요.' },
      ],
      note: '일어나다 → 일어나시다: 일어났어요 → 일어나셨어요.' },
    { id: 'walk', level: 2, words: ['day:everyday', 'numbers:hour'],
      honor: { ko: '어머니는 매일 한 시간씩 걸으세요.', en: 'My mother walks for an hour every day.', answer: '걸으세요', dict: '걸으시다' },
      plain: { ko: '저는 매일 한 시간씩 걸어요.', en: 'I walk for an hour every day.', answer: '걸어요', dict: '걷다', who: 'self' },
      traps: [
        { text: '걷으세요', why: '걷다 is irregular: its ㄷ becomes ㄹ before a vowel, so it’s 걸으세요 (like 걸어요).' },
        { text: '걸세요', why: 'Keep the 으: 걷다 → 걸으세요, like 걸어요.' },
      ],
      note: '걷다 is ㄷ-irregular like 듣다: 걸어요 → 걸으세요.' },
    // Level 3: respectful nouns, humble verbs, 돌아가셨어요, -(으)실 거예요.
    { id: 'age', level: 3, words: ['people:grandpa', 'people:sibling'],
      honor: { ko: '할아버지 연세가 어떻게 되세요?', en: 'How old is your grandfather?', answer: '연세가', dict: '연세' },
      plain: { ko: '동생 나이가 어떻게 돼요?', en: 'How old is your little brother?', answer: '나이가', dict: '나이', who: 'younger' },
      traps: [{ text: '연세께서', why: '께서 marks the person you respect, never their age or anything else they have: 연세가.' }],
      note: '나이 → 연세. 연세가 어떻게 되세요? is the polite way to ask an older person’s age.' },
    { id: 'name', level: 3, words: ['people:name', 'people:child'],
      honor: { ko: '할머니, 성함이 어떻게 되세요?', en: 'What’s your name, ma’am? (to an elderly woman)', answer: '성함이', dict: '성함' },
      plain: { ko: '아이 이름이 어떻게 돼요?', en: 'What’s your child’s name?', answer: '이름이', dict: '이름', who: 'child' },
      traps: [{ text: '성함께서', why: '께서 is only for the person you respect, never for their name: 성함이.' }],
      note: '이름 → 성함. You’ll hear it in 성함이 어떻게 되세요? (May I have your name?), said to customers and older people.' },
    { id: 'tell', level: 3, words: ['work:boss', 'day:friend', 'day:tomorrow'],
      honor: { ko: '사장님, 제가 내일 말씀드릴게요.', en: 'I’ll tell you tomorrow. (to your boss)', answer: '말씀드릴게요', dict: '말씀드리다' },
      plain: { ko: '제가 내일 친구한테 말할게요.', en: 'I’ll tell my friend tomorrow.', answer: '말할게요', dict: '말하다', who: 'friend' },
      traps: [{ text: '말씀하실게요', why: 'You’re the one speaking, and you never honour yourself: no -(으)시-. To tell someone you respect, use the humble 말씀드리다.' }],
      note: 'A humble word lowers you instead of raising them: 말하다 → 말씀드리다 when you tell someone you respect, above all to their face.' },
    { id: 'gave', level: 3, words: ['shopping:gift', 'people:grandma'],
      honor: { ko: '저는 할머니께 선물을 드렸어요.', en: 'I gave Grandma a present.', answer: '드렸어요', dict: '드리다' },
      plain: { ko: '저는 동생한테 선물을 줬어요.', en: 'I gave my little brother a present.', answer: '줬어요', dict: '주다', who: 'younger' },
      traps: [
        { text: '주셨어요', why: '주셨어요 is for someone you respect doing the giving, but here you’re the one giving: 드렸어요 to someone you respect, 줬어요 to anyone else.' },
        { text: '드리셨어요', why: 'You’re the one giving, and you never honour yourself: no -(으)시-.' },
      ],
      note: '주다 → 드리다 when you give to someone you respect, and 한테 → 께.' },
    { id: 'see-you', level: 3, words: ['day:meet', 'people:teacher'],
      honor: { ko: '선생님, 내일 봬요!', en: 'See you tomorrow! (to a teacher)', answer: '봬요', dict: '뵈다' },
      plain: { ko: '저는 내일 친구를 만나요.', en: 'I’m meeting a friend tomorrow.', answer: '만나요', dict: '만나다', who: 'friend' },
      traps: [
        { text: '뵙어요', why: 'Not a form: 뵙다 only goes before a consonant (뵙겠습니다). Before -어요 it’s 뵈어요, or short 봬요.' },
        { text: '뵈요', why: 'Not a form: 뵈 needs 어 before 요: 뵈어요, or short 봬요.' },
      ],
      note: '만나다 → 뵙다 when you meet someone you respect, above all to their face: 내일 봬요 = See you tomorrow, 처음 뵙겠습니다 = Nice to meet you.' },
    { id: 'take', level: 3, words: ['directions:hospital', 'people:grandma'],
      honor: { ko: '오늘 제가 할머니를 병원에 모시고 가요.', en: 'Today I’m taking Grandma to the hospital.', answer: '모시고', dict: '모시다' },
      plain: { ko: '오늘 제가 아이를 병원에 데리고 가요.', en: 'Today I’m taking my child to the hospital.', answer: '데리고', dict: '데리다', who: 'child' },
      traps: [{ text: '데리시고', why: '-(으)시- would honour you, the one taking. Take someone you respect: 모시고 가요; take a child: 데리고 가요.' }],
      note: '데리고 가다 → 모시고 가다 when the person you take somewhere is someone you respect.' },
    { id: 'passed-away', level: 3, words: ['people:grandpa', 'past:lastyear'],
      honor: { ko: '작년에 할아버지께서 돌아가셨어요.', en: 'My grandfather passed away last year.', answer: '돌아가셨어요', dict: '돌아가시다' },
      plain: { ko: '작년에 우리 강아지가 죽었어요.', en: 'Our dog died last year.', answer: '죽었어요', dict: '죽다', who: 'thing' },
      traps: [{ text: '죽으셨어요', why: '죽다 has its own respectful word, 돌아가시다 (돌아가셨어요, passed away), for people you respect. An animal just 죽었어요.' }],
      note: '죽다 → 돌아가시다: the respectful, gentle way to say someone has died.' },
    { id: 'will-make', level: 3, words: ['past:made', 'hobbies:willdo', 'cafe:bread'],
      honor: { ko: '어머니께서 내일 빵을 만드실 거예요.', en: 'My mother is going to make bread tomorrow.', answer: '만드실 거예요', dict: '만드시다' },
      plain: { ko: '저는 내일 빵을 만들 거예요.', en: 'I’m going to make bread tomorrow.', answer: '만들 거예요', dict: '만들다', who: 'self' },
      traps: [
        { text: '만들으실 거예요', why: '만들다 ends in ㄹ: the ㄹ drops before -시-, and there’s no 으: 만드실 거예요.' },
        { text: '만들실 거예요', why: 'The ㄹ of 만들다 drops before ㅅ: 만드실 거예요.' },
      ],
      note: 'The future -(으)ㄹ 거예요 becomes -(으)실 거예요, and the ㄹ drops: 만들 거예요 → 만드실 거예요.' },
    { id: 'will-sleep', level: 3, words: ['day:sleep', 'hobbies:willdo'],
      honor: { ko: '할아버지는 아홉 시에 주무실 거예요.', en: 'Grandpa will go to bed at nine.', answer: '주무실 거예요', dict: '주무시다' },
      plain: { ko: '아이는 아홉 시에 잘 거예요.', en: 'The child will go to bed at nine.', answer: '잘 거예요', dict: '자다', who: 'child' },
      traps: [{ text: '자실 거예요', why: '자다 has its own respectful word, 주무시다: 주무실 거예요. About a child, it’s just 잘 거예요.' }],
      note: '주무시다 in the future: 잘 거예요 → 주무실 거예요.' },
    { id: 'will-be-home', level: 3, words: ['day:home', 'day:evening', 'hobbies:willdo'],
      honor: { ko: '할머니는 저녁에 집에 계실 거예요.', en: 'Grandma will be at home this evening.', answer: '계실 거예요', dict: '계시다' },
      plain: { ko: '저는 저녁에 집에 있을 거예요.', en: 'I’ll be at home this evening.', answer: '있을 거예요', dict: '있다', who: 'self' },
      traps: [{ text: '있으실 거예요', why: 'For being somewhere, the respectful word is 계시다: 계실 거예요. About yourself, it’s just 있을 거예요.' }],
      note: '계시다 in the future: 있을 거예요 → 계실 거예요.' },
    { id: 'will-like', level: 3, words: ['shopping:gift', 'feelings:like', 'hobbies:willdo'],
      honor: { ko: '할머니께서 이 선물을 좋아하실 거예요.', en: 'Grandma will like this present.', answer: '좋아하실 거예요', dict: '좋아하시다' },
      plain: { ko: '동생이 이 선물을 좋아할 거예요.', en: 'My little sister will like this present.', answer: '좋아할 거예요', dict: '좋아하다', who: 'younger' },
      traps: [
        { text: '좋아해실 거예요', why: '-(으)시- goes on the stem 좋아하, not on 좋아해요: 좋아하실 거예요.' },
        { text: '좋으실 거예요', why: '좋다 (be good) can’t take 을/를: to like something, use 좋아하다.' },
      ],
      note: 'The future -(으)ㄹ 거예요 becomes -(으)실 거예요: 좋아할 거예요 → 좋아하실 거예요.' },
    { id: 'will-wait', level: 3, words: ['day:wait', 'directions:station', 'hobbies:willdo'],
      honor: { ko: '어머니께서 역에서 기다리실 거예요.', en: 'My mother will be waiting at the station.', answer: '기다리실 거예요', dict: '기다리시다' },
      plain: { ko: '친구가 역에서 기다릴 거예요.', en: 'My friend will be waiting at the station.', answer: '기다릴 거예요', dict: '기다리다', who: 'friend' },
      traps: [{ text: '기다려실 거예요', why: '-(으)시- goes on the stem 기다리, not on 기다려요: 기다리실 거예요.' }],
      note: '기다리다 ends in a vowel, so it just adds -실 거예요: 기다릴 거예요 → 기다리실 거예요.' },
    { id: 'dont-know', level: 3, words: ['past:didntknow', 'hobbies:song'],
      honor: { ko: '할머니께서는 그 노래를 모르세요.', en: 'Grandma doesn’t know that song.', answer: '모르세요', dict: '모르시다' },
      plain: { ko: '저는 그 노래를 몰라요.', en: 'I don’t know that song.', answer: '몰라요', dict: '모르다', who: 'self' },
      traps: [
        { text: '몰라세요', why: '-(으)세요 goes on the stem 모르, not on 몰라요: 모르세요.' },
        { text: '몰으세요', why: 'The stem stays 모르, which ends in a vowel: 모르세요.' },
      ],
      note: '모르다 only changes before 아/어 (몰라요), so with -(으)시- it’s simply 모르세요.' },
    { id: 'tall', level: 3, words: ['people:tall', 'people:grandpa'],
      honor: { ko: '우리 할아버지는 키가 크세요.', en: 'My grandfather is tall.', answer: '크세요', dict: '크시다' },
      plain: { ko: '제 동생은 키가 커요.', en: 'My little brother is tall.', answer: '커요', dict: '크다', who: 'younger' },
      traps: [
        { text: '커세요', why: '-(으)세요 goes on the stem 크, not on 커요: 크세요.' },
        { text: '크으세요', why: '크 ends in a vowel, so no 으: 크세요.' },
      ],
      note: 'What belongs to someone you respect (their height, their time, their legs) takes -(으)시- too: 키가 크세요.' },
  ],
});
