/**
 * Topic: 나의 하루 · My day — daily routine, time words and everyday verbs.
 * Verbs are taught in the polite present form (해요체) you actually say,
 * with the dictionary form alongside. Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'day',
  order: 2,
  emoji: '🌞',
  color: 'mint',
  title: { ko: '나의 하루', en: 'My day' },
  description: { ko: '일상 이야기', en: 'Talk about your daily routine' },

  notes: [
    {
      title: { ko: '-아요 / -어요', en: 'Present tense' },
      text: 'Take the dictionary form and drop **다**. Add **아요** if the last vowel is ㅏ or ㅗ, otherwise **어요**. Every **하다** verb becomes **해요**. Vowels often merge: 가 + 아요 → **가요**, 보 + 아요 → **봐요**, 마시 + 어요 → **마셔요**.',
      examples: [
        { ko: '먹다 → 먹어요', en: 'eat' },
        { ko: '보다 → 봐요', en: 'see / watch' },
        { ko: '공부하다 → 공부해요', en: 'study' },
      ],
    },
    {
      title: { ko: '을 / 를', en: 'The object particle' },
      text: 'Mark the thing an action is done to with **을** after a consonant (받침) or **를** after a vowel.',
      examples: [
        { ko: '책을 읽어요.', en: 'I read a book.' },
        { ko: '커피를 마셔요.', en: 'I drink coffee.' },
      ],
    },
    {
      title: { ko: '에 vs 에서', en: 'Where and when' },
      text: '**에** marks where you go and when something happens. **에서** marks the place where you do something.',
      examples: [
        { ko: '학교에 가요.', en: 'I go to school.' },
        { ko: '아침에 일어나요.', en: 'I get up in the morning.' },
        { ko: '집에서 쉬어요.', en: 'I rest at home.' },
      ],
    },
    {
      title: { ko: '어순', en: 'Word order' },
      text: 'The verb always comes **last**. A common order is: time → place → object → verb.',
      examples: [{ ko: '주말에 집에서 영화를 봐요.', en: 'On weekends I watch movies at home.' }],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'home', ko: '집', en: 'home / house', level: 1, pos: 'noun', emoji: '🏠', rom: 'jip',
      example: { ko: '집이 어디예요?', en: 'Where is your home?' } },
    { id: 'go', ko: '가요', en: 'go', level: 1, pos: 'verb', emoji: '🚶', rom: 'gayo', dict: '가다',
      note: '가다 → 가 + 아요 → 가요 (the two ㅏ merge).',
      example: { ko: '어디 가요?', en: 'Where are you going?' } },
    { id: 'today', ko: '오늘', en: 'today', level: 1, pos: 'noun', emoji: '📅', rom: 'oneul',
      example: { ko: '오늘 뭐 해요?', en: 'What are you doing today?' } },
    { id: 'eat', ko: '먹어요', en: 'eat', level: 1, pos: 'verb', emoji: '🍚', rom: 'meogeoyo', pron: '머거요', dict: '먹다',
      note: '먹다 → 먹 + 어요. The ㄱ slides into the next syllable: [머거요].',
      example: { ko: '밥 먹었어요?', en: 'Have you eaten? (a friendly greeting)' } },
    { id: 'drink', ko: '마셔요', en: 'drink', level: 1, pos: 'verb', emoji: '🥤', rom: 'masyeoyo', dict: '마시다',
      note: '마시다 → 마시 + 어요 → 마셔요 (ㅣ + ㅓ merge into ㅕ).',
      example: { ko: '커피 마셔요?', en: 'Do you drink coffee?' } },
    { id: 'morning', ko: '아침', en: 'morning / breakfast', level: 1, pos: 'noun', emoji: '🌅', rom: 'achim',
      note: '아침 means both “morning” and “breakfast”.',
      example: { ko: '아침에 커피를 마셔요.', en: 'I drink coffee in the morning.' } },
    { id: 'evening', ko: '저녁', en: 'evening / dinner', level: 1, pos: 'noun', emoji: '🌆', rom: 'jeonyeok',
      note: '저녁 means both “evening” and “dinner”.',
      example: { ko: '저녁 뭐 먹어요?', en: 'What are you having for dinner?' } },
    { id: 'sleep', ko: '자요', en: 'sleep', level: 1, pos: 'verb', emoji: '😴', rom: 'jayo', dict: '자다',
      example: { ko: '보통 열한 시에 자요.', en: 'I usually go to bed at eleven.' } },
    { id: 'now', ko: '지금', en: 'now', level: 1, pos: 'adverb', emoji: '⏰', rom: 'jigeum',
      example: { ko: '지금 뭐 해요?', en: 'What are you doing now?' } },
    { id: 'friend', ko: '친구', en: 'friend', level: 1, pos: 'noun', emoji: '👫', rom: 'chingu',
      example: { ko: '제 친구예요.', en: 'This is my friend.' } },
    { id: 'tomorrow', ko: '내일', en: 'tomorrow', level: 1, pos: 'noun', emoji: '🔜', rom: 'naeil',
      example: { ko: '내일 봐요!', en: 'See you tomorrow!' } },
    { id: 'yesterday', ko: '어제', en: 'yesterday', level: 1, pos: 'noun', emoji: '⏪', rom: 'eoje',
      example: { ko: '어제 뭐 했어요?', en: 'What did you do yesterday?' } },
    { id: 'korean', ko: '한국어', en: 'Korean (language)', level: 1, pos: 'noun', emoji: '🗣️', rom: 'hangugeo',
      pron: '한구거',
      note: '한국 (Korea) + 어 (language). The ㄱ slides over: [한구거].',
      example: { ko: '한국어 어려워요?', en: 'Is Korean difficult?' } },

    // ---- Level 2 ----
    { id: 'lunch', ko: '점심', en: 'lunch', level: 2, pos: 'noun', emoji: '🍱', rom: 'jeomsim',
      note: 'The middle meal: 아침 → 점심 → 저녁.',
      example: { ko: '점심 먹었어요?', en: 'Did you have lunch?' } },
    { id: 'getup', ko: '일어나요', en: 'get up / wake up', level: 2, pos: 'verb', emoji: '🛏️', rom: 'ireonayo',
      pron: '이러나요', dict: '일어나다',
      example: { ko: '일곱 시에 일어나요.', en: 'I get up at seven.' } },
    { id: 'come', ko: '와요', en: 'come', level: 2, pos: 'verb', emoji: '🏃', rom: 'wayo', dict: '오다',
      note: '오다 → 오 + 아요 → 와요 (ㅗ + ㅏ = ㅘ).',
      example: { ko: '언제 와요?', en: 'When are you coming?' } },
    { id: 'watch', ko: '봐요', en: 'see / watch', level: 2, pos: 'verb', emoji: '👀', rom: 'bwayo', dict: '보다',
      note: '보다 → 보 + 아요 → 봐요 (ㅗ + ㅏ = ㅘ).',
      example: { ko: '뭐 봐요?', en: 'What are you watching?' } },
    { id: 'meet', ko: '만나요', en: 'meet', level: 2, pos: 'verb', emoji: '🤝', rom: 'mannayo', dict: '만나다',
      example: { ko: '어디서 만나요?', en: 'Where shall we meet?' } },
    { id: 'study', ko: '공부해요', en: 'study', level: 2, pos: 'verb', emoji: '📚', rom: 'gongbuhaeyo', dict: '공부하다',
      note: 'Every 하다 verb becomes 해요: 공부하다 → 공부해요.',
      example: { ko: '도서관에서 공부해요.', en: 'I study at the library.' } },
    { id: 'work', ko: '일해요', en: 'work', level: 2, pos: 'verb', emoji: '💼', rom: 'ilhaeyo', pron: '이래요', dict: '일하다',
      note: '일 (work) + 하다. The ㅎ goes quiet after ㄹ: [이래요].',
      example: { ko: '오늘도 일해요?', en: 'Are you working today too?' } },
    { id: 'school', ko: '학교', en: 'school', level: 2, pos: 'noun', emoji: '🏫', rom: 'hakgyo', pron: '학꾜',
      note: 'After a ㄱ 받침, the next ㄱ gets tense: [학꾜].',
      example: { ko: '학교가 어디예요?', en: 'Where is your school?' } },
    { id: 'company', ko: '회사', en: 'company / office', level: 2, pos: 'noun', emoji: '🏢', rom: 'hoesa',
      note: '회사원 = office worker.',
      example: { ko: '회사가 멀어요.', en: 'My office is far away.' } },
    { id: 'everyday', ko: '매일', en: 'every day', level: 2, pos: 'adverb', emoji: '🔁', rom: 'maeil',
      note: '매 (every) + 일 (day).',
      example: { ko: '매일 운동해요.', en: 'I work out every day.' } },
    { id: 'movie', ko: '영화', en: 'movie', level: 2, pos: 'noun', emoji: '🎬', rom: 'yeonghwa',
      note: '영화관 = cinema.',
      example: { ko: '같이 영화 봐요!', en: 'Let’s watch a movie together!' } },

    // ---- Level 3 ----
    { id: 'weekend', ko: '주말', en: 'weekend', level: 3, pos: 'noun', emoji: '🎉', rom: 'jumal',
      note: '주 (week) + 말 (end).',
      example: { ko: '주말에 뭐 해요?', en: 'What are you doing this weekend?' } },
    { id: 'exercise', ko: '운동해요', en: 'exercise / work out', level: 3, pos: 'verb', emoji: '🏋️', rom: 'undonghaeyo',
      dict: '운동하다',
      example: { ko: '헬스장에서 운동해요.', en: 'I work out at the gym.' } },
    { id: 'cook', ko: '요리해요', en: 'cook', level: 3, pos: 'verb', emoji: '🍳', rom: 'yorihaeyo', dict: '요리하다',
      example: { ko: '집에서 요리해요.', en: 'I cook at home.' } },
    { id: 'rest', ko: '쉬어요', en: 'rest', level: 3, pos: 'verb', emoji: '🛋️', rom: 'swieoyo', dict: '쉬다',
      example: { ko: '좀 쉬어요.', en: 'Take a little rest.' } },
    { id: 'book', ko: '책', en: 'book', level: 3, pos: 'noun', emoji: '📕', rom: 'chaek',
      example: { ko: '무슨 책이에요?', en: 'What book is it?' } },
    { id: 'read', ko: '읽어요', en: 'read', level: 3, pos: 'verb', emoji: '📖', rom: 'ilgeoyo', pron: '일거요', dict: '읽다',
      note: '읽다 has a double 받침 ㄺ: the ㄹ stays and the ㄱ slides over → [일거요].',
      example: { ko: '뭐 읽어요?', en: 'What are you reading?' } },
    { id: 'usually', ko: '보통', en: 'usually', level: 3, pos: 'adverb', emoji: '🙂', rom: 'botong',
      note: 'Also means “normal / regular”, e.g. 보통 사이즈.',
      example: { ko: '보통 일곱 시에 일어나요.', en: 'I usually get up at seven.' } },
    { id: 'sometimes', ko: '가끔', en: 'sometimes', level: 3, pos: 'adverb', emoji: '🎲', rom: 'gakkeum',
      example: { ko: '가끔 카페에 가요.', en: 'I sometimes go to a café.' } },
    { id: 'together', ko: '같이', en: 'together', level: 3, pos: 'adverb', emoji: '👭', rom: 'gachi', pron: '가치',
      note: 'ㅌ before 이 sounds like ㅊ: [가치].',
      example: { ko: '같이 먹어요!', en: 'Let’s eat together!' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-gohome', en: "I'm going home.", ko: '집에 가요.',
      tiles: ['집에', '가요'], gloss: ['to home', 'go'], words: ['home', 'go'],
      traps: [{ tile: '집에서', why: '에 marks where you are going. 에서 marks where an action happens.' }] },
    { id: 's-drinkwater', en: 'I drink water.', ko: '물을 마셔요.',
      tiles: ['물을', '마셔요'], gloss: ['water (object)', 'drink'], words: ['cafe:water', 'drink'],
      traps: [{ tile: '먹어요', why: '먹어요 means “eat”. For drinks, use 마셔요.' }] },
    { id: 's-breakfast', en: 'I eat breakfast.', ko: '아침을 먹어요.',
      tiles: ['아침을', '먹어요'], gloss: ['breakfast (object)', 'eat'], words: ['morning', 'eat'],
      traps: [{ tile: '마셔요', why: '마셔요 means “drink”. For food, use 먹어요.' }] },
    { id: 's-gonow', en: "I'm going home now.", ko: '지금 집에 가요.',
      tiles: ['지금', '집에', '가요'], gloss: ['now', 'to home', 'go'], words: ['now', 'home', 'go'],
      traps: [{ tile: '집에서', why: '에 marks where you are going. 에서 marks where an action happens.' }] },

    // ---- Level 2 ----
    { id: 's-meetfriend', level: 2, en: "I'm meeting a friend tomorrow.", ko: '내일 친구를 만나요.',
      tiles: ['내일', '친구를', '만나요'], gloss: ['tomorrow', 'friend (object)', 'meet'], words: ['tomorrow', 'friend', 'meet'] },
    { id: 's-studykorean', level: 2, en: 'I study Korean every day.', ko: '매일 한국어를 공부해요.',
      tiles: ['매일', '한국어를', '공부해요'], gloss: ['every day', 'Korean (object)', 'study'],
      words: ['everyday', 'korean', 'study'], alts: [['한국어를', '매일', '공부해요']] },
    { id: 's-school', level: 2, en: "I'm going to school today.", ko: '오늘 학교에 가요.',
      tiles: ['오늘', '학교에', '가요'], gloss: ['today', 'to school', 'go'], words: ['today', 'school', 'go'],
      traps: [{ tile: '학교에서', why: '에 marks the place you go to. 에서 marks where an action happens.' }] },
    { id: 's-work', level: 2, en: 'I work at a company.', ko: '회사에서 일해요.',
      tiles: ['회사에서', '일해요'], gloss: ['at the company', 'work'], words: ['company', 'work'],
      traps: [{ tile: '회사에', why: 'Working is something you do there, so the place takes 에서: 회사에서 일해요.' }] },
    { id: 's-getup', level: 2, en: 'I get up in the morning.', ko: '아침에 일어나요.',
      tiles: ['아침에', '일어나요'], gloss: ['in the morning', 'get up'], words: ['morning', 'getup'],
      traps: [{ tile: '아침에서', why: 'Time words take 에, never 에서: 아침에 (in the morning).' }] },
    { id: 's-movie', level: 2, en: 'I watch a movie.', ko: '영화를 봐요.',
      tiles: ['영화를', '봐요'], gloss: ['movie (object)', 'watch'], words: ['movie', 'watch'] },
    { id: 's-friendcomes', level: 2, en: 'My friend is coming to my house.', ko: '친구가 집에 와요.',
      tiles: ['친구가', '집에', '와요'], gloss: ['friend (subject)', 'to home', 'come'], words: ['friend', 'home', 'come'],
      traps: [{ tile: '친구를', why: 'Your friend is the one coming (the subject), so it takes 가: 친구가.' }] },
    { id: 's-seeyou', level: 2, en: 'See you tomorrow!', ko: '내일 만나요!',
      tiles: ['내일', '만나요'], gloss: ['tomorrow', "(let's) meet"], words: ['tomorrow', 'meet'] },

    // ---- Level 3 ----
    { id: 's-rest', level: 3, en: 'I rest at home on the weekend.', ko: '주말에 집에서 쉬어요.',
      tiles: ['주말에', '집에서', '쉬어요'], gloss: ['on the weekend', 'at home', 'rest'], words: ['weekend', 'home', 'rest'],
      alts: [['집에서', '주말에', '쉬어요']],
      traps: [{ tile: '집에', why: 'Resting is something you do there, so the place takes 에서: 집에서 쉬어요.' }] },
    { id: 's-workout', level: 3, en: 'I usually work out in the evening.', ko: '보통 저녁에 운동해요.',
      tiles: ['보통', '저녁에', '운동해요'], gloss: ['usually', 'in the evening', 'work out'],
      words: ['usually', 'evening', 'exercise'], alts: [['저녁에', '보통', '운동해요']],
      traps: [{ tile: '저녁에서', why: 'Time words take 에: 저녁에 (in the evening).' }] },
    { id: 's-together', level: 3, en: "Let's go together!", ko: '같이 가요!',
      tiles: ['같이', '가요'], gloss: ['together', "(let's) go"], words: ['together', 'go'] },
    { id: 's-cook', level: 3, en: 'I sometimes cook on weekends.', ko: '주말에 가끔 요리해요.',
      tiles: ['주말에', '가끔', '요리해요'], gloss: ['on weekends', 'sometimes', 'cook'],
      words: ['weekend', 'sometimes', 'cook'], alts: [['가끔', '주말에', '요리해요']] },
    { id: 's-read', level: 3, en: 'I read books every day.', ko: '매일 책을 읽어요.',
      tiles: ['매일', '책을', '읽어요'], gloss: ['every day', 'book (object)', 'read'], words: ['everyday', 'book', 'read'],
      alts: [['책을', '매일', '읽어요']] },
    { id: 's-cafestudy', level: 3, en: 'I study Korean at a café.', ko: '카페에서 한국어를 공부해요.',
      tiles: ['카페에서', '한국어를', '공부해요'], gloss: ['at a café', 'Korean (object)', 'study'],
      words: ['cafe:cafe', 'korean', 'study'], alts: [['한국어를', '카페에서', '공부해요']],
      traps: [{ tile: '카페에', why: 'Studying is something you do there, so the place takes 에서: 카페에서.' }] },
  ],
});
