/**
 * Topic: 나의 하루 · My day — daily routine, time words and everyday verbs.
 * Verbs are taught in the polite present form (해요체) you actually say,
 * with the dictionary form alongside. Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'day',
  order: 2,
  emoji: '🌞',
  color: 'mint',
  title: { ko: '나의 하루', en: 'My day' },
  description: { ko: '일상 이야기', en: 'Talk about your daily routine' },

  notes: [
    {
      title: { ko: '-아요 / -어요', en: 'Present tense' },
      text: 'Take the dictionary form and drop **다**. Add **아요** if the last vowel is ㅏ or ㅗ, otherwise **어요**. Every **하다** verb becomes **해요**. Vowels often merge: 가 + 아요 → **가요**, 보 + 아요 → **봐요**, 마시 + 어요 → **마셔요**.',
      examples: [
        { ko: '먹다 → 먹어요', en: 'eat' },
        { ko: '보다 → 봐요', en: 'see / watch' },
        { ko: '공부하다 → 공부해요', en: 'study' },
      ],
    },
    {
      title: { ko: '을 / 를', en: 'The object particle' },
      text: 'Mark the thing an action is done to with **을** after a consonant (받침) or **를** after a vowel.',
      examples: [
        { ko: '책을 읽어요.', en: 'I read a book.' },
        { ko: '커피를 마셔요.', en: 'I drink coffee.' },
      ],
    },
    {
      title: { ko: '에 vs 에서', en: 'Where and when' },
      text: '**에** marks where you go and when something happens — but 오늘, 내일, 어제, 지금 and 매일 need no 에. **에서** marks the place where you do something.',
      examples: [
        { ko: '학교에 가요.', en: 'I go to school.' },
        { ko: '아침에 일어나요.', en: 'I get up in the morning.' },
        { ko: '집에서 쉬어요.', en: 'I rest at home.' },
      ],
    },
    {
      title: { ko: '있어요 / 없어요', en: 'There is / there isn’t' },
      text: '**있어요** means “there is”, “I have”, or “(someone) is at a place”. **없어요** is the opposite. The thing that is there takes 이/가.',
      examples: [
        { ko: '집에 우유가 있어요.', en: 'There’s milk at home.' },
        { ko: '오늘은 숙제가 없어요.', en: 'I have no homework today.' },
      ],
    },
    {
      title: { ko: '어순', en: 'Word order' },
      text: 'The verb always comes **last**. A common order is: time → place → object → verb.',
      examples: [{ ko: '주말에 집에서 영화를 봐요.', en: 'On weekends I watch movies at home.' }],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'home', ko: '집', en: 'home / house', level: 1, pos: 'noun', emoji: '🏠', rom: 'jip',
      example: { ko: '집이 어디예요?', en: 'Where is your home?' } },
    { id: 'go', ko: '가요', en: 'go', level: 1, pos: 'verb', emoji: '🚶', rom: 'gayo', dict: '가다',
      note: '가다 → 가 + 아요 → 가요 (the two ㅏ merge).',
      example: { ko: '어디 가요?', en: 'Where are you going?' } },
    { id: 'today', ko: '오늘', en: 'today', level: 1, pos: 'noun', emoji: '📅', rom: 'oneul',
      example: { ko: '오늘 뭐 해요?', en: 'What are you doing today?' } },
    { id: 'eat', ko: '먹어요', en: 'eat', level: 1, pos: 'verb', emoji: '🍚', rom: 'meogeoyo', pron: '머거요', dict: '먹다',
      note: '먹다 → 먹 + 어요. The ㄱ slides into the next syllable: [머거요].',
      example: { ko: '밥 먹었어요?', en: 'Have you eaten? (a friendly greeting)' } },
    { id: 'drink', ko: '마셔요', en: 'drink', level: 1, pos: 'verb', emoji: '🥤', rom: 'masyeoyo', dict: '마시다',
      note: '마시다 → 마시 + 어요 → 마셔요 (ㅣ + ㅓ merge into ㅕ).',
      example: { ko: '커피 마셔요?', en: 'Do you drink coffee?' } },
    { id: 'morning', ko: '아침', en: 'morning / breakfast', level: 1, pos: 'noun', emoji: '🌅', rom: 'achim',
      note: '아침 means both “morning” and “breakfast”.',
      example: { ko: '아침에 커피를 마셔요.', en: 'I drink coffee in the morning.' } },
    { id: 'evening', ko: '저녁', en: 'evening / dinner', level: 1, pos: 'noun', emoji: '🌆', rom: 'jeonyeok',
      note: '저녁 means both “evening” and “dinner”.',
      example: { ko: '저녁 뭐 먹어요?', en: 'What are you having for dinner?' } },
    { id: 'sleep', ko: '자요', en: 'sleep', level: 1, pos: 'verb', emoji: '😴', rom: 'jayo', dict: '자다',
      example: { ko: '보통 열한 시에 자요.', en: 'I usually go to bed at eleven.' } },
    { id: 'now', ko: '지금', en: 'now', level: 1, pos: 'adverb', emoji: '⏰', rom: 'jigeum',
      example: { ko: '지금 뭐 해요?', en: 'What are you doing now?' } },
    { id: 'friend', ko: '친구', en: 'friend', level: 1, pos: 'noun', emoji: '👫', rom: 'chingu',
      example: { ko: '제 친구예요.', en: 'This is my friend.' } },
    { id: 'tomorrow', ko: '내일', en: 'tomorrow', level: 1, pos: 'noun', emoji: '🔜', rom: 'naeil',
      example: { ko: '내일 봐요!', en: 'See you tomorrow!' } },
    { id: 'yesterday', ko: '어제', en: 'yesterday', level: 1, pos: 'noun', emoji: '⏪', rom: 'eoje',
      example: { ko: '어제 뭐 했어요?', en: 'What did you do yesterday?' } },
    { id: 'korean', ko: '한국어', en: 'Korean (language)', level: 1, pos: 'noun', emoji: '🗣️', rom: 'hangugeo',
      pron: '한구거',
      note: '한국 (Korea) + 어 (language). The ㄱ slides over: [한구거].',
      example: { ko: '한국어 어려워요?', en: 'Is Korean difficult?' } },
    { id: 'what', ko: '뭐', en: 'what', level: 1, pos: 'pronoun', emoji: '❓', rom: 'mwo', accept: ['무엇'],
      note: 'The everyday spoken form of 무엇. 뭐예요? = What is it?',
      example: { ko: '지금 뭐 해요?', en: 'What are you doing now?' } },
    { id: 'do', ko: '해요', en: 'do', level: 1, pos: 'verb', emoji: '✅', rom: 'haeyo', dict: '하다',
      note: '하다 → 해요. It also builds many verbs: 공부 (study) + 하다 → 공부해요.',
      example: { ko: '주말에 뭐 해요?', en: 'What do you do on weekends?' } },
    { id: 'meal', ko: '밥', en: 'rice / meal', level: 1, pos: 'noun', emoji: '🍚', rom: 'bap',
      note: '밥 먹었어요? (“Have you eaten?”) is a friendly way to say hello.',
      example: { ko: '같이 밥 먹어요!', en: 'Let’s eat together!' } },
    { id: 'night', ko: '밤', en: 'night', level: 1, pos: 'noun', emoji: '🌙', rom: 'bam',
      example: { ko: '밤에 책을 읽어요.', en: 'I read at night.' } },
    { id: 'have', ko: '있어요', en: 'there is / I have', level: 1, pos: 'verb', emoji: '📦', rom: 'isseoyo', pron: '이써요',
      dict: '있다', enAlt: ['have', 'there is', 'is there'],
      note: 'Also “to be (somewhere)”: 집에 있어요 = I’m at home. The opposite is 없어요.',
      example: { ko: '시간 있어요?', en: 'Do you have time?' } },
    { id: 'nothave', ko: '없어요', en: "there isn't / I don't have", level: 1, pos: 'verb', emoji: '🫙', rom: 'eopseoyo',
      pron: '업써요', dict: '없다', enAlt: ["don't have", 'there is no', 'there isnt'],
      example: { ko: '오늘은 시간이 없어요.', en: 'I don’t have time today.' } },

    // ---- Level 2 ----
    { id: 'lunch', ko: '점심', en: 'lunch', level: 2, pos: 'noun', emoji: '🍱', rom: 'jeomsim',
      note: 'The middle meal: 아침 → 점심 → 저녁.',
      example: { ko: '점심 먹었어요?', en: 'Did you have lunch?' } },
    { id: 'getup', ko: '일어나요', en: 'get up / wake up', level: 2, pos: 'verb', emoji: '🛏️', rom: 'ireonayo',
      pron: '이러나요', dict: '일어나다',
      example: { ko: '일곱 시에 일어나요.', en: 'I get up at seven.' } },
    { id: 'come', ko: '와요', en: 'come', level: 2, pos: 'verb', emoji: '🏃', rom: 'wayo', dict: '오다',
      note: '오다 → 오 + 아요 → 와요 (ㅗ + ㅏ = ㅘ).',
      example: { ko: '언제 와요?', en: 'When are you coming?' } },
    { id: 'watch', ko: '봐요', en: 'see / watch', level: 2, pos: 'verb', emoji: '👀', rom: 'bwayo', dict: '보다',
      note: '보다 → 보 + 아요 → 봐요 (ㅗ + ㅏ = ㅘ).',
      example: { ko: '뭐 봐요?', en: 'What are you watching?' } },
    { id: 'meet', ko: '만나요', en: 'meet', level: 2, pos: 'verb', emoji: '🤝', rom: 'mannayo', dict: '만나다', avoid: ['watch'],
      example: { ko: '어디서 만나요?', en: 'Where shall we meet?' } },
    { id: 'study', ko: '공부해요', en: 'study', level: 2, pos: 'verb', emoji: '📚', rom: 'gongbuhaeyo', dict: '공부하다',
      note: 'Every 하다 verb becomes 해요: 공부하다 → 공부해요.',
      example: { ko: '도서관에서 공부해요.', en: 'I study at the library.' } },
    { id: 'work', ko: '일해요', en: 'work', level: 2, pos: 'verb', emoji: '💼', rom: 'ilhaeyo', dict: '일하다',
      note: '일 (work) + 하다 → 일해요. In fast speech the ㅎ softens, so it often sounds like “이래요”.',
      example: { ko: '오늘도 일해요?', en: 'Are you working today too?' } },
    { id: 'school', ko: '학교', en: 'school', level: 2, pos: 'noun', emoji: '🏫', rom: 'hakgyo', pron: '학꾜',
      note: 'After a ㄱ 받침, the next ㄱ gets tense: [학꾜].',
      example: { ko: '학교가 어디예요?', en: 'Where is your school?' } },
    { id: 'company', ko: '회사', en: 'company / office', level: 2, pos: 'noun', emoji: '🏢', rom: 'hoesa',
      note: '회사원 = office worker.',
      example: { ko: '회사가 멀어요.', en: 'My office is far away.' } },
    { id: 'everyday', ko: '매일', en: 'every day', level: 2, pos: 'adverb', emoji: '🔁', rom: 'maeil',
      note: '매 (every) + 일 (day).',
      example: { ko: '매일 운동해요.', en: 'I work out every day.' } },
    { id: 'movie', ko: '영화', en: 'movie', level: 2, pos: 'noun', emoji: '🎬', rom: 'yeonghwa',
      note: '영화관 = cinema.',
      example: { ko: '같이 영화 봐요!', en: 'Let’s watch a movie together!' } },
    { id: 'wash', ko: '씻어요', en: 'wash (yourself)', level: 2, pos: 'verb', emoji: '🧼', rom: 'ssiseoyo', pron: '씨서요',
      dict: '씻다', enAlt: ['wash up', 'get washed'],
      example: { ko: '손을 씻어요.', en: 'I wash my hands.' } },
    { id: 'shower', ko: '샤워해요', en: 'take a shower', level: 2, pos: 'verb', emoji: '🚿', rom: 'syawohaeyo',
      dict: '샤워하다', enAlt: ['shower'],
      example: { ko: '아침에 샤워해요.', en: 'I shower in the morning.' } },
    { id: 'clean', ko: '청소해요', en: 'clean (the house)', level: 2, pos: 'verb', emoji: '🧹', rom: 'cheongsohaeyo',
      dict: '청소하다',
      example: { ko: '주말에 집을 청소해요.', en: 'I clean the house on weekends.' } },
    { id: 'homework', ko: '숙제', en: 'homework', level: 2, pos: 'noun', emoji: '📝', rom: 'sukje', pron: '숙쩨',
      example: { ko: '숙제 다 했어요?', en: 'Have you finished your homework?' } },
    { id: 'library', ko: '도서관', en: 'library', level: 2, pos: 'noun', emoji: '🏛️', rom: 'doseogwan',
      example: { ko: '도서관에서 공부해요.', en: 'I study at the library.' } },

    // ---- Level 3 ----
    { id: 'weekend', ko: '주말', en: 'weekend', level: 3, pos: 'noun', emoji: '🎉', rom: 'jumal',
      note: '주 (week) + 말 (end).',
      example: { ko: '주말에 뭐 해요?', en: 'What are you doing this weekend?' } },
    { id: 'exercise', ko: '운동해요', en: 'exercise / work out', level: 3, pos: 'verb', emoji: '🏋️', rom: 'undonghaeyo',
      dict: '운동하다',
      example: { ko: '헬스장에서 운동해요.', en: 'I work out at the gym.' } },
    { id: 'cook', ko: '요리해요', en: 'cook', level: 3, pos: 'verb', emoji: '🍳', rom: 'yorihaeyo', dict: '요리하다',
      example: { ko: '집에서 요리해요.', en: 'I cook at home.' } },
    { id: 'rest', ko: '쉬어요', en: 'rest', level: 3, pos: 'verb', emoji: '🛋️', rom: 'swieoyo', dict: '쉬다',
      example: { ko: '좀 쉬어요.', en: 'Take a little rest.' } },
    { id: 'book', ko: '책', en: 'book', level: 3, pos: 'noun', emoji: '📕', rom: 'chaek',
      example: { ko: '무슨 책이에요?', en: 'What book is it?' } },
    { id: 'read', ko: '읽어요', en: 'read', level: 3, pos: 'verb', emoji: '📖', rom: 'ilgeoyo', pron: '일거요', dict: '읽다',
      note: '읽다 has a double 받침 ㄺ: the ㄹ stays and the ㄱ slides over → [일거요].',
      example: { ko: '뭐 읽어요?', en: 'What are you reading?' } },
    { id: 'usually', ko: '보통', en: 'usually', level: 3, pos: 'adverb', emoji: '🙂', rom: 'botong',
      note: 'Also means “normal / regular”, e.g. 보통 사이즈.',
      example: { ko: '보통 일곱 시에 일어나요.', en: 'I usually get up at seven.' } },
    { id: 'sometimes', ko: '가끔', en: 'sometimes', level: 3, pos: 'adverb', emoji: '🎲', rom: 'gakkeum',
      example: { ko: '가끔 카페에 가요.', en: 'I sometimes go to a café.' } },
    { id: 'together', ko: '같이', en: 'together', level: 3, pos: 'adverb', emoji: '👭', rom: 'gachi', pron: '가치',
      note: 'ㅌ before 이 sounds like ㅊ: [가치].',
      example: { ko: '같이 먹어요!', en: 'Let’s eat together!' } },
    { id: 'gotowork', ko: '출근해요', en: 'go to work', level: 3, pos: 'verb', emoji: '🚇', rom: 'chulgeunhaeyo',
      dict: '출근하다', note: '출근 = arriving at work. The opposite is 퇴근 (leaving work).',
      example: { ko: '아침 일찍 출근해요.', en: 'I go to work early in the morning.' } },
    { id: 'leavework', ko: '퇴근해요', en: 'leave work (for the day)', level: 3, pos: 'verb', emoji: '🌇', rom: 'toegeunhaeyo',
      dict: '퇴근하다', enAlt: ['leave work', 'finish work', 'get off work'],
      example: { ko: '보통 저녁에 퇴근해요.', en: 'I usually finish work in the evening.' } },
    { id: 'early', ko: '일찍', en: 'early', level: 3, pos: 'adverb', emoji: '🐓', rom: 'iljjik',
      example: { ko: '오늘은 일찍 자요.', en: 'I’m going to bed early today.' } },

    // ---- More words ----
    { id: 'room', ko: '방', en: 'room', level: 1, pos: 'noun', emoji: '🚪', rom: 'bang', enAlt: ['bedroom'],
      note: '방 also turns up in words for places: 노래방 = a karaoke room.',
      example: { ko: '방에서 쉬어요.', en: 'I’m resting in my room.' } },
    { id: 'phone', ko: '핸드폰', en: 'mobile phone', level: 1, pos: 'noun', emoji: '📱', rom: 'haendeupon',
      accept: ['휴대폰', '휴대 전화'], enAlt: ['cell phone', 'cellphone', 'phone', 'smartphone', 'mobile'],
      note: 'Also called 휴대폰. To call someone is 전화해요.',
      example: { ko: '제 핸드폰 어디 있어요?', en: 'Where’s my phone?' } },
    { id: 'thanksfood', ko: '잘 먹겠습니다', en: 'thanks for the food (before eating)', level: 1, pos: 'phrase', emoji: '🥢',
      rom: 'jal meokgetseumnida', pron: '잘 먹껟씀니다', avoid: ['cafe:thanks'],
      enAlt: ['thanks for the food', 'thank you for the food', 'thanks for the meal', 'thank you for the meal'],
      note: 'Said just before eating, to thank the cook or whoever is paying. After the meal: 잘 먹었습니다.',
      example: { ko: '엄마, 잘 먹겠습니다!', en: 'Thanks for the food, Mom!' } },
    { id: 'often', ko: '자주', en: 'often', level: 2, pos: 'adverb', emoji: '🔄', rom: 'jaju', enAlt: ['frequently'],
      note: 'From most to least often: 항상 (always) → 자주 (often) → 가끔 (sometimes).',
      example: { ko: '친구를 자주 만나요.', en: 'I often meet my friends.' } },
    { id: 'always', ko: '항상', en: 'always', level: 2, pos: 'adverb', emoji: '♾️', rom: 'hangsang', accept: ['언제나'],
      enAlt: ['all the time'],
      note: '언제나 also means “always”.',
      example: { ko: '아침에는 항상 커피를 마셔요.', en: 'I always drink coffee in the morning.' } },
    { id: 'wait', ko: '기다려요', en: 'wait', level: 2, pos: 'verb', emoji: '⏳', rom: 'gidaryeoyo', dict: '기다리다',
      enAlt: ['wait for'],
      note: '기다리 + 어요 → 기다려요 (ㅣ + ㅓ merge into ㅕ). What you wait for takes 을/를.',
      example: { ko: '버스를 기다려요.', en: 'I’m waiting for the bus.' } },
    { id: 'thesedays', ko: '요즘', en: 'these days', level: 2, pos: 'noun', emoji: '🗓️', rom: 'yojeum', accept: ['요즈음'],
      enAlt: ['nowadays', 'lately', 'recently'], avoid: ['now'],
      note: 'Short for 요즈음. 요즘 어때요? = How are things these days?',
      example: { ko: '요즘 바빠요.', en: 'I’m busy these days.' } },
    { id: 'sleepin', ko: '늦잠', en: 'sleeping in', level: 3, pos: 'noun', emoji: '😪', rom: 'neutjam', pron: '늗짬',
      enAlt: ['oversleeping', 'oversleep', 'sleep in', 'sleeping late', 'lie-in', 'lie in'], avoid: ['sleep'],
      note: '늦 (late) + 잠 (sleep). 늦잠을 자요 = I sleep in; 늦잠 잤어요! = I overslept!',
      example: { ko: '주말에는 늦잠을 자요.', en: 'I sleep in on weekends.' } },
    { id: 'dishes', ko: '설거지해요', en: 'wash the dishes', level: 3, pos: 'verb', emoji: '🧽', rom: 'seolgeojihaeyo',
      dict: '설거지하다', enAlt: ['do the dishes', 'wash up', 'do the washing up', 'wash dishes'], avoid: ['wash'],
      note: '설거지 means “washing up”, so you don’t need a word for “dishes”.',
      example: { ko: '오늘은 제가 설거지해요.', en: 'I’m doing the dishes today.' } },
    { id: 'goout', ko: '나가요', en: 'go out / leave', level: 3, pos: 'verb', emoji: '👟', rom: 'nagayo', dict: '나가다',
      enAlt: ['get out', 'exit', 'leave the house'], avoid: ['gotowork', 'leavework'],
      note: 'To leave a place: 집에서 나가요 = I leave the house. The opposite is 들어가요 (go in).',
      example: { ko: '몇 시에 나가요?', en: 'What time are you heading out?' } },
    { id: 'bed', ko: '침대', en: 'bed', level: 1, pos: 'noun', emoji: '🛏️', rom: 'chimdae',
      note: 'Sleeping is something you do there, so it takes 에서: 침대에서 자요. Lying down takes 에: 침대에 누워요.',
      example: { ko: '침대에서 핸드폰을 봐요.', en: 'I look at my phone in bed.' } },
    { id: 'tv', ko: '텔레비전', en: 'TV / television', level: 1, pos: 'noun', emoji: '📺', rom: 'tellebijeon',
      accept: ['티비', '티브이'], enAlt: ['telly'],
      note: 'In everyday speech, most people just say 티비 (TV).',
      example: { ko: '저녁에 텔레비전을 봐요.', en: 'I watch TV in the evening.' } },
    { id: 'andthen', ko: '그리고', en: 'and (then)', level: 1, pos: 'adverb', emoji: '🔗', rom: 'geurigo',
      enAlt: ['and also'],
      note: 'It starts a new sentence: 밥을 먹어요. 그리고 학교에 가요. To join two nouns, use 하고 instead: 빵하고 우유.',
      example: { ko: '샤워해요. 그리고 아침을 먹어요.', en: 'I take a shower. Then I have breakfast.' } },
    { id: 'quickly', ko: '빨리', en: 'quickly / fast', level: 1, pos: 'adverb', emoji: '🏎️', rom: 'ppalli', avoid: ['travel:fast'],
      enAlt: ['quick', 'hurry', 'hurry up'],
      note: 'It’s about speed: for “early”, use 일찍 (일찍 일어나요 = I get up early). 빨리빨리! (“hurry, hurry!”) is a famous Korean phrase.',
      example: { ko: '빨리 와요!', en: 'Come quickly!' } },
    { id: 'daytime', ko: '낮', en: 'daytime', level: 2, pos: 'noun', emoji: '🏙️', rom: 'nat', pron: '낟',
      enAlt: ['during the day', 'day time', 'the daytime', 'midday'], avoid: ['numbers:pm'],
      note: 'The opposite of 밤 (night): 낮에는 일하고 밤에는 자요. On its own it sounds like [낟], but before a vowel the ㅈ comes back: 낮에 [나제].',
      example: { ko: '낮에는 회사에 있어요.', en: 'During the day, I’m at the office.' } },
    { id: 'late', ko: '늦게', en: 'late', level: 2, pos: 'adverb', emoji: '🦉', rom: 'neutge', pron: '늗께',
      note: 'The opposite of 일찍 (early): 늦게 자요 = I go to bed late. It comes from 늦다 (to be late).',
      example: { ko: '어제 늦게 잤어요.', en: 'I went to bed late yesterday.' } },
    { id: 'call', ko: '전화해요', en: 'call (on the phone)', level: 2, pos: 'verb', emoji: '☎️', rom: 'jeonhwahaeyo', dict: '전화하다',
      enAlt: ['phone', 'make a phone call', 'give a call', 'ring'],
      note: '전화 (phone call) + 하다. The person you call takes 한테 (or 에게): 엄마한테 전화해요 = I call my mom.',
      example: { ko: '친구한테 전화해요.', en: 'I’m calling my friend.' } },
    { id: 'turnoff', ko: '꺼요', en: 'turn off', level: 2, pos: 'verb', emoji: '📴', rom: 'kkeoyo', dict: '끄다',
      enAlt: ['switch off', 'turn it off', 'shut off'],
      note: 'From 끄다: the ㅡ drops before 어요 (끄 + 어요 → 꺼요). The opposite is 켜요 (turn on).',
      example: { ko: '불 좀 꺼 주세요.', en: 'Could you turn off the light, please?' } },
    { id: 'turnon', ko: '켜요', en: 'turn on', level: 2, pos: 'verb', emoji: '💡', rom: 'kyeoyo', dict: '켜다',
      enAlt: ['switch on', 'turn it on'],
      note: '켜다 → 켜요 (ㅕ swallows the 어): 불을 켜요 = I turn on the light. The opposite is 꺼요.',
      example: { ko: '에어컨 좀 켜 주세요.', en: 'Could you turn on the air conditioner, please?' } },
    { id: 'dawn', ko: '새벽', en: 'early morning / dawn', level: 3, pos: 'noun', emoji: '🌌', rom: 'saebyeok',
      enAlt: ['the early hours', 'early hours', 'small hours', 'before dawn', 'daybreak'], avoid: ['morning', 'numbers:am'],
      note: 'The hours after midnight, until the sun comes up: 새벽 두 시 = 2 a.m. 새벽에 일어나요 = I get up at dawn.',
      example: { ko: '새벽 두 시에 자요.', en: 'I go to bed at 2 a.m.' } },
    { id: 'weekday', ko: '평일', en: 'weekday', level: 3, pos: 'noun', emoji: '📆', rom: 'pyeongil',
      enAlt: ['weekdays', 'on weekdays'],
      note: '평 (ordinary) + 일 (day): Monday to Friday. The opposite is 주말 (weekend).',
      example: { ko: '평일에는 회사에 가요.', en: 'On weekdays, I go to the office.' } },
    { id: 'dayafter', ko: '모레', en: 'the day after tomorrow', level: 3, pos: 'noun', emoji: '⏩', rom: 'more',
      enAlt: ['in two days'],
      note: '어제 (yesterday) → 오늘 (today) → 내일 (tomorrow) → 모레. Like 내일, it needs no 에: 모레 만나요.',
      example: { ko: '내일은 바빠요. 모레 만나요!', en: 'I’m busy tomorrow. Let’s meet the day after!' } },
    { id: 'washface', ko: '세수해요', en: 'wash your face', level: 3, pos: 'verb', emoji: '🧖', rom: 'sesuhaeyo', dict: '세수하다',
      enAlt: ['wash my face', 'wash face'], avoid: ['wash'],
      note: '세수 means washing your face (and hands), so you don’t need a word for “face”.',
      example: { ko: '아침에 일어나서 세수해요.', en: 'I get up in the morning and wash my face.' } },
    { id: 'brush', ko: '닦아요', en: 'brush (teeth) / wipe', level: 3, pos: 'verb', emoji: '🪥', rom: 'dakkayo', pron: '다까요', dict: '닦다',
      enAlt: ['brush my teeth', 'wipe clean', 'polish'],
      note: '이를 닦아요 = I brush my teeth; 테이블을 닦아요 = I wipe the table. The ㄲ slides over into the next syllable: [다까요].',
      example: { ko: '밥을 먹고 이를 닦아요.', en: 'I brush my teeth after I eat.' } },
    { id: 'comeback', ko: '돌아와요', en: 'come back', level: 3, pos: 'verb', emoji: '🪃', rom: 'dorawayo', pron: '도라와요', dict: '돌아오다',
      enAlt: ['return', 'get back', 'be back', 'come home'], avoid: ['travel:return'],
      note: '돌다 (turn) + 오다 (come). The other way is 돌아가요 (go back).',
      example: { ko: '몇 시에 돌아와요?', en: 'What time are you coming back?' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-gohome', en: "I'm going home.", ko: '집에 가요.',
      tiles: ['집에', '가요'], gloss: ['to home', 'go'], words: ['home', 'go'],
      traps: [{ tile: '집에서', why: '에 marks where you are going. 에서 marks where an action happens.' }] },
    { id: 's-drinkwater', en: 'I drink water.', ko: '물을 마셔요.',
      tiles: ['물을', '마셔요'], gloss: ['water (object)', 'drink'], words: ['cafe:water', 'drink'],
      traps: [{ tile: '먹어요', why: '먹어요 means “eat”. For “drink”, use 마셔요 — the usual verb for drinks.' }] },
    { id: 's-breakfast', en: 'I eat breakfast.', ko: '아침을 먹어요.',
      tiles: ['아침을', '먹어요'], gloss: ['breakfast (object)', 'eat'], words: ['morning', 'eat'],
      traps: [{ tile: '마셔요', why: '마셔요 means “drink”. For food, use 먹어요.' }] },
    { id: 's-whatdo', en: 'What are you doing today?', ko: '오늘 뭐 해요?',
      tiles: ['오늘', '뭐', '해요'], gloss: ['today', 'what', 'do'], words: ['today', 'what', 'do'] },
    { id: 's-meal', en: 'I have a meal with a friend.', ko: '친구하고 밥 먹어요.',
      tiles: ['친구하고', '밥', '먹어요'], gloss: ['with a friend', 'meal', 'eat'], words: ['friend', 'meal', 'eat'] },
    { id: 's-milkhome', en: 'There’s milk at home.', ko: '집에 우유가 있어요.',
      tiles: ['집에', '우유가', '있어요'], gloss: ['at home', 'milk (subject)', 'there is'], words: ['home', 'cafe:milk', 'have'],
      alts: [['우유가', '집에', '있어요']],
      traps: [{ tile: '우유를', why: '있어요 says that something is there. The thing that is there is the subject, so it takes 가: 우유가 있어요.' }] },
    { id: 's-gonow', en: "I'm going home now.", ko: '지금 집에 가요.',
      tiles: ['지금', '집에', '가요'], gloss: ['now', 'to home', 'go'], words: ['now', 'home', 'go'], alts: [['집에', '지금', '가요']],
      traps: [{ tile: '집에서', why: '에 marks where you are going. 에서 marks where an action happens.' }] },

    // ---- Level 2 ----
    { id: 's-meetfriend', level: 2, en: "I'm meeting a friend tomorrow.", ko: '내일 친구를 만나요.',
      tiles: ['내일', '친구를', '만나요'], gloss: ['tomorrow', 'friend (object)', 'meet'], words: ['tomorrow', 'friend', 'meet'],
      alts: [['친구를', '내일', '만나요']] },
    { id: 's-studykorean', level: 2, en: 'I study Korean every day.', ko: '매일 한국어를 공부해요.',
      tiles: ['매일', '한국어를', '공부해요'], gloss: ['every day', 'Korean (object)', 'study'],
      words: ['everyday', 'korean', 'study'], alts: [['한국어를', '매일', '공부해요']] },
    { id: 's-school', level: 2, en: "I'm going to school today.", ko: '오늘 학교에 가요.',
      tiles: ['오늘', '학교에', '가요'], gloss: ['today', 'to school', 'go'], words: ['today', 'school', 'go'], alts: [['학교에', '오늘', '가요']],
      traps: [{ tile: '학교에서', why: '에 marks the place you go to. 에서 marks where an action happens.' }] },
    { id: 's-work', level: 2, en: 'I work at a company.', ko: '회사에서 일해요.',
      tiles: ['회사에서', '일해요'], gloss: ['at the company', 'work'], words: ['company', 'work'],
      traps: [{ tile: '회사에', why: 'Working is something you do there, so the place takes 에서: 회사에서 일해요.' }] },
    { id: 's-getup', level: 2, en: 'I get up in the morning.', ko: '아침에 일어나요.',
      tiles: ['아침에', '일어나요'], gloss: ['in the morning', 'get up'], words: ['morning', 'getup'],
      traps: [{ tile: '아침에서', why: 'To say when something happens, use 에, not 에서: 아침에 (in the morning).' }] },
    { id: 's-movie', level: 2, en: 'I watch a movie.', ko: '영화를 봐요.',
      tiles: ['영화를', '봐요'], gloss: ['movie (object)', 'watch'], words: ['movie', 'watch'] },
    { id: 's-friendcomes', level: 2, en: 'My friend is coming to my house.', ko: '친구가 집에 와요.',
      tiles: ['친구가', '집에', '와요'], gloss: ['friend (subject)', 'to home', 'come'], words: ['friend', 'home', 'come'],
      alts: [['집에', '친구가', '와요']],
      traps: [{ tile: '친구를', why: 'Your friend is the one coming (the subject), so it takes 가: 친구가.' }] },
    { id: 's-seeyou', level: 2, en: "Let's meet tomorrow!", ko: '내일 만나요!',
      tiles: ['내일', '만나요'], gloss: ['tomorrow', "(let's) meet"], words: ['tomorrow', 'meet'] },
    { id: 's-nohomework', level: 2, en: 'I have no homework today.', ko: '오늘은 숙제가 없어요.',
      tiles: ['오늘은', '숙제가', '없어요'], gloss: ['today (topic)', 'homework (subject)', "there isn't"],
      words: ['today', 'homework', 'nothave'],
      traps: [{ tile: '숙제를', why: '없어요 says that something isn’t there. That thing is the subject, so it takes 가: 숙제가 없어요.' }] },
    { id: 's-shower', level: 2, en: 'I shower in the morning.', ko: '아침에 샤워해요.',
      tiles: ['아침에', '샤워해요'], gloss: ['in the morning', 'take a shower'], words: ['morning', 'shower'],
      traps: [{ tile: '아침에서', why: 'To say when something happens, use 에, not 에서: 아침에 (in the morning).' }] },
    { id: 's-library', level: 2, en: 'I do my homework at the library.', ko: '도서관에서 숙제를 해요.',
      tiles: ['도서관에서', '숙제를', '해요'], gloss: ['at the library', 'homework (object)', 'do'],
      words: ['library', 'homework', 'do'], alts: [['숙제를', '도서관에서', '해요']],
      traps: [{ tile: '도서관에', why: 'Doing homework is something you do there, so the place takes 에서: 도서관에서.' }] },

    // ---- Level 3 ----
    { id: 's-rest', level: 3, en: 'I rest at home on the weekend.', ko: '주말에 집에서 쉬어요.',
      tiles: ['주말에', '집에서', '쉬어요'], gloss: ['on the weekend', 'at home', 'rest'], words: ['weekend', 'home', 'rest'],
      alts: [['집에서', '주말에', '쉬어요']],
      traps: [{ tile: '집에', why: 'Resting is something you do there, so the place takes 에서: 집에서 쉬어요.' }] },
    { id: 's-workout', level: 3, en: 'I usually work out in the evening.', ko: '보통 저녁에 운동해요.',
      tiles: ['보통', '저녁에', '운동해요'], gloss: ['usually', 'in the evening', 'work out'],
      words: ['usually', 'evening', 'exercise'], alts: [['저녁에', '보통', '운동해요']],
      traps: [{ tile: '저녁에서', why: 'To say when something happens, use 에, not 에서: 저녁에 (in the evening).' }] },
    { id: 's-together', level: 3, en: "Let's go together!", ko: '같이 가요!',
      tiles: ['같이', '가요'], gloss: ['together', "(let's) go"], words: ['together', 'go'] },
    { id: 's-cook', level: 3, en: 'I sometimes cook on weekends.', ko: '주말에 가끔 요리해요.',
      tiles: ['주말에', '가끔', '요리해요'], gloss: ['on weekends', 'sometimes', 'cook'],
      words: ['weekend', 'sometimes', 'cook'], alts: [['가끔', '주말에', '요리해요']] },
    { id: 's-read', level: 3, en: 'I read books every day.', ko: '매일 책을 읽어요.',
      tiles: ['매일', '책을', '읽어요'], gloss: ['every day', 'book (object)', 'read'], words: ['everyday', 'book', 'read'],
      alts: [['책을', '매일', '읽어요']] },
    { id: 's-lunch', level: 3, en: "Let's have lunch together!", ko: '점심 같이 먹어요!',
      tiles: ['점심', '같이', '먹어요'], gloss: ['lunch', 'together', "(let's) eat"], words: ['lunch', 'together', 'eat'],
      alts: [['같이', '점심', '먹어요']] },
    { id: 's-night', level: 3, en: 'I read books at night.', ko: '밤에 책을 읽어요.',
      tiles: ['밤에', '책을', '읽어요'], gloss: ['at night', 'book (object)', 'read'], words: ['night', 'book', 'read'],
      alts: [['책을', '밤에', '읽어요']],
      traps: [{ tile: '밤에서', why: 'To say when something happens, use 에, not 에서: 밤에 (at night).' }] },
    { id: 's-clean', level: 3, en: 'I clean the house on the weekend.', ko: '주말에 집을 청소해요.',
      tiles: ['주말에', '집을', '청소해요'], gloss: ['on the weekend', 'house (object)', 'clean'],
      words: ['weekend', 'home', 'clean'], alts: [['집을', '주말에', '청소해요']],
      traps: [{ tile: '집에', why: 'The English says “clean the house”: the house is what you clean (the object), so it takes 을: 집을 청소해요.' }] },
    { id: 's-early', level: 3, en: 'I’m going to bed early today.', ko: '오늘은 일찍 자요.',
      tiles: ['오늘은', '일찍', '자요'], gloss: ['today (topic)', 'early', 'sleep'], words: ['today', 'early', 'sleep'] },
    { id: 's-gotowork', level: 3, en: 'I go to work early every day.', ko: '매일 일찍 출근해요.',
      tiles: ['매일', '일찍', '출근해요'], gloss: ['every day', 'early', 'go to work'], words: ['everyday', 'early', 'gotowork'] },
    { id: 's-leavework', level: 3, en: 'I usually leave work in the evening.', ko: '보통 저녁에 퇴근해요.',
      tiles: ['보통', '저녁에', '퇴근해요'], gloss: ['usually', 'in the evening', 'leave work'],
      words: ['usually', 'evening', 'leavework'], alts: [['저녁에', '보통', '퇴근해요']],
      traps: [{ tile: '저녁에서', why: 'To say when something happens, use 에, not 에서: 저녁에 (in the evening).' }] },
    { id: 's-cafestudy', level: 3, en: 'I study Korean at a café.', ko: '카페에서 한국어를 공부해요.',
      tiles: ['카페에서', '한국어를', '공부해요'], gloss: ['at a café', 'Korean (object)', 'study'],
      words: ['cafe:cafe', 'korean', 'study'], alts: [['한국어를', '카페에서', '공부해요']],
      traps: [{ tile: '카페에', why: 'Studying is something you do there, so the place takes 에서: 카페에서.' }] },

    // ---- More sentences ----
    { id: 's-sleepin', level: 3, en: 'I often sleep in these days.', ko: '요즘 자주 늦잠을 자요.',
      tiles: ['요즘', '자주', '늦잠을', '자요'], gloss: ['these days', 'often', 'sleeping in (object)', 'sleep'],
      words: ['thesedays', 'often', 'sleepin', 'sleep'], alts: [['요즘', '늦잠을', '자주', '자요']],
      traps: [
        { tile: '가끔', why: '가끔 means “sometimes”. “Often” is 자주.' },
        { tile: '늦잠이', why: '“Sleep in” is 늦잠을 자요: 늦잠 is the object of 자요, so it takes 을.' },
      ] },
    { id: 's-always', level: 2, en: 'I always study in my room.', ko: '항상 방에서 공부해요.',
      tiles: ['항상', '방에서', '공부해요'], gloss: ['always', 'in the room', 'study'], words: ['always', 'room', 'study'],
      alts: [['방에서', '항상', '공부해요']],
      traps: [{ tile: '방에', why: 'Studying is something you do there, so the place takes 에서: 방에서 공부해요.' }] },
    { id: 's-wait', level: 2, en: "I'm waiting for my friend now.", ko: '지금 친구를 기다려요.',
      tiles: ['지금', '친구를', '기다려요'], gloss: ['now', 'friend (object)', 'wait'], words: ['now', 'friend', 'wait'],
      alts: [['친구를', '지금', '기다려요']],
      traps: [{ tile: '친구가', why: '친구가 기다려요 means “my friend is waiting”. Your friend is the one you wait for (the object), so it takes 를: 친구를 기다려요.' }] },
    { id: 's-washface', level: 3, en: 'I wash my face. Then I brush my teeth.', ko: '세수해요. 그리고 이를 닦아요.',
      tiles: ['세수해요', '그리고', '이를', '닦아요'], gloss: ['wash (my) face', 'and then', 'teeth (object)', 'brush'],
      words: ['washface', 'andthen', 'brush'],
      traps: [{ tile: '이가', why: 'Your teeth are what you brush (the object), so 이 takes 를: 이를 닦아요. (이가 아파요 = I have a toothache.)' }] },
    { id: 's-callmom', level: 2, en: 'I call my mom during the day.', ko: '낮에 엄마한테 전화해요.',
      tiles: ['낮에', '엄마한테', '전화해요'], gloss: ['during the day', 'to Mom', 'call'],
      words: ['daytime', 'people:mom', 'call'], alts: [['엄마한테', '낮에', '전화해요']],
      traps: [
        { tile: '밤에', why: '밤 means “night”. “During the day” is 낮에.' },
        { tile: '엄마를', why: '전화하다 doesn’t take the person as an object: the person you call takes 한테 (“to”): 엄마한테 전화해요.' },
      ] },
    { id: 's-bedtv', level: 2, en: 'I watch TV in bed.', ko: '침대에서 텔레비전을 봐요.',
      tiles: ['침대에서', '텔레비전을', '봐요'], gloss: ['in bed', 'TV (object)', 'watch'],
      words: ['bed', 'tv', 'watch'], alts: [['텔레비전을', '침대에서', '봐요']],
      traps: [{ tile: '침대에', why: 'Watching TV is something you do there, so the place takes 에서: 침대에서.' }] },
    { id: 's-weekday', level: 3, en: 'On weekdays, I leave work late.', ko: '평일에는 늦게 퇴근해요.',
      tiles: ['평일에는', '늦게', '퇴근해요'], gloss: ['on weekdays (topic)', 'late', 'leave work'],
      words: ['weekday', 'late', 'leavework'],
      traps: [{ tile: '일찍', why: '일찍 means “early”. “Late” is 늦게.' }] },
    { id: 's-dayafter', level: 3, en: 'I’ll be back the day after tomorrow, early in the morning.', ko: '모레 새벽에 돌아와요.',
      tiles: ['모레', '새벽에', '돌아와요'], gloss: ['the day after tomorrow', 'early in the morning', 'come back'],
      words: ['dayafter', 'dawn', 'comeback'],
      traps: [{ tile: '내일', why: '내일 means “tomorrow”. “The day after tomorrow” is 모레.' }] },
    { id: 's-phoneoff', level: 2, en: 'Turn off your phone and go to sleep, quick!', ko: '핸드폰을 끄고 빨리 자요!',
      tiles: ['핸드폰을', '끄고', '빨리', '자요'], gloss: ['phone (object)', 'turn off and', 'quickly', 'sleep'],
      words: ['phone', 'turnoff', 'quickly', 'sleep'], alts: [['빨리', '핸드폰을', '끄고', '자요']],
      traps: [{ tile: '켜고', why: '켜다 means “turn on”. To switch something off, use 끄다: 끄고.' }] },
  ],
});
