/**
 * Topic: 숫자와 시간 · Numbers & time — the two number systems, counters,
 * telling the time and the days of the week. Numbers are written in Hangul
 * (세 시 삼십 분), so the listening modes read them the Korean way.
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'numbers',
  order: 4,
  emoji: '🔢',
  color: 'sky',
  title: { ko: '숫자와 시간', en: 'Numbers & time' },
  description: { ko: '숫자, 시간, 요일', en: 'Count, tell the time, name the days' },

  notes: [
    {
      title: { ko: '하나, 둘 / 일, 이', en: 'Two sets of numbers' },
      text: 'Korean has two sets of numbers. **Native** numbers (**하나, 둘, 셋, 넷, 다섯… 열**) count things and people, and tell the hour and your age. **Sino-Korean** numbers (**일, 이, 삼, 사, 오… 십**) are for prices, minutes, dates and phone numbers. Big numbers are built from **십** (10), **백** (100), **천** (1,000) and **만** (10,000), with no 일 in front: 만 이천 = 12,000.',
      examples: [
        { ko: '사과 세 개 주세요.', en: 'Three apples, please.' },
        { ko: '삼천 원이에요.', en: 'It’s 3,000 won.' },
        { ko: '저는 스물다섯 살이에요.', en: 'I’m twenty-five.' },
      ],
    },
    {
      title: { ko: '한, 두, 세, 네', en: 'Before a counter' },
      text: 'Counters say what you are counting: **개** (things), **명** (people), **시** (o’clock), **살** (years old). Before a counter, **하나 → 한**, **둘 → 두**, **셋 → 세**, **넷 → 네**, and 20 **스물 → 스무**. The other numbers stay the same: 다섯 개, 열 명.',
      examples: [
        { ko: '친구 두 명이 와요.', en: 'Two friends are coming.' },
        { ko: '사과 네 개 주세요.', en: 'Four apples, please.' },
        { ko: '스무 살이에요.', en: 'I’m twenty.' },
      ],
    },
    {
      title: { ko: '몇 시예요?', en: 'Telling the time' },
      text: 'Hours use native numbers + **시**, minutes use Sino-Korean numbers + **분**. **반** means half past. Put **오전** (a.m.) or **오후** (p.m.) in front, and add **에** for “at”.',
      examples: [
        { ko: '세 시 삼십 분이에요.', en: 'It’s 3:30.' },
        { ko: '세 시 반이에요.', en: 'It’s half past three.' },
        { ko: '오후 두 시에 만나요.', en: 'Let’s meet at 2 p.m.' },
      ],
    },
    {
      title: { ko: '요일', en: 'Days of the week' },
      text: 'Add **요일** to 월 화 수 목 금 토 일: **월요일** (Monday) … **일요일** (Sunday). Use **에** for “on”, and **부터 … 까지** for “from … to”.',
      examples: [
        { ko: '토요일에 친구를 만나요.', en: 'I’m meeting a friend on Saturday.' },
        { ko: '월요일부터 금요일까지 일해요.', en: 'I work from Monday to Friday.' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'three', ko: '셋', en: 'three (native number)', level: 1, pos: 'number', emoji: '3️⃣', rom: 'set', pron: '섿',
      enAlt: ['3'],
      note: 'Before a counter it shortens to 세: 세 개, 세 시. On its own, the ㅅ sounds like a quiet t: [섿].',
      example: { ko: '하나, 둘, 셋!', en: 'One, two, three!' } },
    { id: 'four', ko: '넷', en: 'four (native number)', level: 1, pos: 'number', emoji: '4️⃣', rom: 'net', pron: '넫',
      enAlt: ['4'], avoid: ['cafe:yes'],
      note: 'Before a counter it shortens to 네: 네 명, 네 시 (the same sound as 네, “yes”).',
      example: { ko: '우리 가족은 넷이에요.', en: 'There are four of us in my family.' } },
    { id: 'five', ko: '다섯', en: 'five (native number)', level: 1, pos: 'number', emoji: '5️⃣', rom: 'daseot', pron: '다섣',
      enAlt: ['5'],
      note: '다섯 stays the same before a counter: 다섯 개, 다섯 시. Only 하나, 둘, 셋, 넷 (and 스물) have short forms.',
      example: { ko: '사과 다섯 개 주세요.', en: 'Five apples, please.' } },
    { id: 'ten', ko: '열', en: 'ten (native number)', level: 1, pos: 'number', emoji: '🔟', rom: 'yeol', enAlt: ['10'],
      note: 'Keep counting with 열 + 1–9: 열하나 (11), 열둘 (12). Before a counter: 열한 시, 열두 시.',
      example: { ko: '열 시에 만나요.', en: 'Let’s meet at ten.' } },
    { id: 'il', ko: '일', en: 'one (Sino-Korean number)', level: 1, pos: 'number', emoji: '☝️', rom: 'il', enAlt: ['1'],
      avoid: ['day:work'],
      note: 'Sino-Korean numbers: 일, 이, 삼, 사, 오, 육, 칠, 팔, 구, 십. 일 also means “day” and “work”, so listen for context.',
      example: { ko: '화장실은 일 층에 있어요.', en: 'The restroom is on the first floor.' } },
    { id: 'i', ko: '이', en: 'two (Sino-Korean number)', level: 1, pos: 'number', emoji: '✌️', rom: 'i', enAlt: ['2'],
      avoid: ['cafe:this'],
      note: '이 also means “this” (이 가방 = this bag), so listen for context. 이십 = 20.',
      example: { ko: '이천 원이에요.', en: 'It’s 2,000 won.' } },
    { id: 'sam', ko: '삼', en: 'three (Sino-Korean number)', level: 1, pos: 'number', emoji: '☘️', rom: 'sam', enAlt: ['3'],
      note: 'Prices and minutes use Sino-Korean numbers: 삼천 원 (3,000 won), 삼 분 (3 minutes). Hours don’t: 3 o’clock is 세 시.',
      example: { ko: '삼 분만 기다려 주세요.', en: 'Please wait just three minutes.' } },
    { id: 'sip', ko: '십', en: 'ten (Sino-Korean number)', level: 1, pos: 'number', emoji: '🙌', rom: 'sip', enAlt: ['10'],
      note: 'Just 십, not 일십. The tens are “two ten”, “three ten”: 이십 (20), 삼십 (30).',
      example: { ko: '십 분 걸려요.', en: 'It takes ten minutes.' } },
    { id: 'oclock', ko: '시', en: "o'clock", level: 1, pos: 'counter', emoji: '🕒', rom: 'si',
      note: 'Hours use native numbers: 한 시, 두 시, 세 시, 네 시… 열두 시.',
      example: { ko: '지금 두 시예요.', en: 'It’s two o’clock now.' } },
    { id: 'howmany', ko: '몇', en: 'how many / what number', level: 1, pos: 'determiner', emoji: '🔢', rom: 'myeot', pron: '멷',
      note: 'It goes before a counter: 몇 개? (how many?), 몇 명? (how many people?), 몇 시? (what time?).',
      example: { ko: '사과 몇 개 있어요?', en: 'How many apples are there?' } },

    // ---- Level 2 ----
    { id: 'hundred', ko: '백', en: 'hundred', level: 2, pos: 'number', emoji: '💯', rom: 'baek', enAlt: ['100', 'one hundred'],
      note: 'Just 백 for 100 (not 일백): 백 원, 오백 원 (500 won).',
      example: { ko: '오백 원이에요.', en: 'It’s 500 won.' } },
    { id: 'thousand', ko: '천', en: 'thousand', level: 2, pos: 'number', emoji: '💴', rom: 'cheon',
      enAlt: ['1000', '1,000', 'one thousand'],
      note: 'Just 천 for 1,000: 천 원. Then 이천 (2,000), 삼천 (3,000)…',
      example: { ko: '커피가 삼천 원이에요.', en: 'The coffee is 3,000 won.' } },
    { id: 'won', ko: '원', en: 'won (Korean money)', level: 2, pos: 'counter', emoji: '🪙', rom: 'won',
      note: 'Prices use Sino-Korean numbers. With digits it’s written 5,000원; in Hangul, with a space: 오천 원.',
      example: { ko: '이거 오천 원이에요.', en: 'This is 5,000 won.' } },
    { id: 'minute', ko: '분', en: 'minute', level: 2, pos: 'counter', emoji: '⏱️', rom: 'bun', enAlt: ['minutes'],
      note: 'Minutes use Sino-Korean numbers: 오 분, 십 분, 삼십 분. (분 is also the polite counter for people: 몇 분이세요?)',
      example: { ko: '오 분 후에 가요.', en: 'I’m leaving in five minutes.' } },
    { id: 'half', ko: '반', en: 'half (past the hour)', level: 2, pos: 'noun', emoji: '🌗', rom: 'ban',
      note: '세 시 반 = half past three (3:30). 반 also means “class”: 한국어 반 = Korean class.',
      example: { ko: '지금 두 시 반이에요.', en: 'It’s half past two now.' } },
    { id: 'item', ko: '개', en: 'item (counter)', level: 2, pos: 'counter', emoji: '🧺', rom: 'gae',
      enAlt: ['thing', 'things', 'items'],
      note: 'The everyday counter for things, with native numbers: 한 개, 두 개, 세 개. (개 also means “dog”!)',
      example: { ko: '이거 세 개 주세요.', en: 'Three of these, please.' } },
    { id: 'people', ko: '명', en: 'people (counter)', level: 2, pos: 'counter', emoji: '👥', rom: 'myeong',
      enAlt: ['person', 'persons'],
      note: 'Counts people with native numbers: 한 명, 두 명. Staff use the polite 분: 몇 분이세요? (How many of you?)',
      example: { ko: '친구 세 명이 와요.', en: 'Three friends are coming.' } },
    { id: 'hour', ko: '시간', en: 'hour / time', level: 2, pos: 'noun', emoji: '⏳', rom: 'sigan', enAlt: ['hours'],
      note: '두 시 = two o’clock, but 두 시간 = two hours (native numbers again). 시간 있어요? = Do you have time?',
      example: { ko: '두 시간 공부했어요.', en: 'I studied for two hours.' } },
    { id: 'whattime', ko: '몇 시예요?', en: 'what time is it?', level: 2, pos: 'phrase', emoji: '⌚', rom: 'myeot siyeyo',
      pron: '멷 씨예요', enAlt: ['what time', "what's the time"],
      note: '몇 (what number) + 시 (o’clock). Answer with a native number: 세 시예요.',
      example: { ko: '한국은 지금 몇 시예요?', en: 'What time is it in Korea now?' } },
    { id: 'monday', ko: '월요일', en: 'Monday', level: 2, pos: 'noun', emoji: '🌙', rom: 'woryoil', pron: '워료일',
      note: '월 means “moon”. The days 월 화 수 목 금 토 일 are moon, fire, water, tree, gold, earth and sun.',
      example: { ko: '월요일에 학교에 가요.', en: 'I go to school on Monday.' } },
    { id: 'saturday', ko: '토요일', en: 'Saturday', level: 2, pos: 'noun', emoji: '⛰️', rom: 'toyoil',
      note: '토 means “earth / soil”.',
      example: { ko: '토요일에 친구를 만나요.', en: 'I’m meeting a friend on Saturday.' } },
    { id: 'sunday', ko: '일요일', en: 'Sunday', level: 2, pos: 'noun', emoji: '☀️', rom: 'iryoil', pron: '이료일',
      note: '일 means “sun” here: 일요일 is the “sun day”.',
      example: { ko: '일요일에 집에서 쉬어요.', en: 'I rest at home on Sunday.' } },

    // ---- Level 3 ----
    { id: 'tenthousand', ko: '만', en: 'ten thousand', level: 3, pos: 'number', emoji: '💸', rom: 'man', enAlt: ['10000', '10,000'],
      note: 'Korean groups big numbers by 만 (10,000): 이만 (20,000), 십만 (100,000). 10,000 is just 만.',
      example: { ko: '이 가방은 오만 원이에요.', en: 'This bag is 50,000 won.' } },
    { id: 'age', ko: '살', en: 'years old', level: 3, pos: 'counter', emoji: '🎈', rom: 'sal', enAlt: ['years', 'year old', 'age'],
      note: 'Age uses native numbers: 스무 살 (20), 스물다섯 살 (25). To someone older, ask politely: 나이가 어떻게 되세요?',
      example: { ko: '저는 스물다섯 살이에요.', en: 'I’m twenty-five.' } },
    { id: 'am', ko: '오전', en: 'a.m. (before noon)', level: 3, pos: 'noun', emoji: '🌄', rom: 'ojeon',
      enAlt: ['am', 'before noon', 'morning'], avoid: ['day:morning'],
      note: 'It goes before the time: 오전 열 시 = 10 a.m. On its own, 오전에 = in the morning.',
      example: { ko: '오전에 수업이 있어요.', en: 'I have class in the morning.' } },
    { id: 'pm', ko: '오후', en: 'p.m. / afternoon', level: 3, pos: 'noun', emoji: '🌤️', rom: 'ohu', enAlt: ['pm'],
      note: 'It goes before the time: 오후 두 시 = 2 p.m. On its own, 오후에 = in the afternoon.',
      example: { ko: '오후에 시간 있어요?', en: 'Are you free this afternoon?' } },
    { id: 'tuesday', ko: '화요일', en: 'Tuesday', level: 3, pos: 'noun', emoji: '🔥', rom: 'hwayoil',
      note: '화 means “fire”.',
      example: { ko: '화요일에 뭐 해요?', en: 'What are you doing on Tuesday?' } },
    { id: 'wednesday', ko: '수요일', en: 'Wednesday', level: 3, pos: 'noun', emoji: '💧', rom: 'suyoil',
      note: '수 means “water”.',
      example: { ko: '수요일에 영화를 봐요.', en: 'I’m watching a movie on Wednesday.' } },
    { id: 'thursday', ko: '목요일', en: 'Thursday', level: 3, pos: 'noun', emoji: '🌳', rom: 'mogyoil', pron: '모교일',
      note: '목 means “tree”. The ㄱ slides into the next syllable: [모교일].',
      example: { ko: '목요일에 친구가 와요.', en: 'My friend is coming on Thursday.' } },
    { id: 'friday', ko: '금요일', en: 'Friday', level: 3, pos: 'noun', emoji: '🥇', rom: 'geumyoil', pron: '그묘일',
      note: '금 means “gold”. The ㅁ slides into the next syllable: [그묘일].',
      example: { ko: '금요일에 뭐 해요?', en: 'What are you doing on Friday?' } },
    { id: 'birthday', ko: '생일', en: 'birthday', level: 3, pos: 'noun', emoji: '🎂', rom: 'saengil',
      note: '생일 축하해요! = Happy birthday!',
      example: { ko: '오늘은 제 생일이에요!', en: 'Today is my birthday!' } },
    { id: 'when', ko: '언제', en: 'when', level: 3, pos: 'adverb', emoji: '🗓️', rom: 'eonje',
      note: '언제예요? = When is it? Like 오늘 and 내일, it takes no 에.',
      example: { ko: '언제 시간 있어요?', en: 'When are you free?' } },
    { id: 'phone', ko: '전화번호', en: 'phone number', level: 3, pos: 'noun', emoji: '📞', rom: 'jeonhwabeonho',
      enAlt: ['telephone number', 'mobile number'],
      note: '전화 (phone) + 번호 (number). Read it digit by digit in Sino-Korean, with 공 for 0: 010 = 공일공.',
      example: { ko: '전화번호 좀 알려 주세요.', en: 'Could you give me your phone number?' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-fournow', en: "It's four o'clock now.", ko: '지금 네 시예요.',
      tiles: ['지금', '네', '시예요'], gloss: ['now', 'four (before a counter)', "o'clock (it is)"], words: ['day:now', 'four', 'oclock'],
      traps: [
        { tile: '넷', why: 'Before a counter like 시, 넷 shortens to 네: 네 시.' },
        { tile: '사', why: 'Hours use native Korean numbers: 네 시, not 사 시.' },
      ] },
    { id: 's-tenbed', en: 'I go to bed at ten.', ko: '열 시에 자요.',
      tiles: ['열', '시에', '자요'], gloss: ['ten', "at … o'clock", 'sleep'], words: ['ten', 'oclock', 'day:sleep'],
      traps: [
        { tile: '십', why: 'Hours use native Korean numbers: 열 시, not 십 시.' },
        { tile: '시에서', why: 'To say at what time something happens, use 에: 열 시에.' },
      ] },

    // ---- Level 2 ----
    { id: 's-whattime', level: 2, en: 'What time is it now?', ko: '지금 몇 시예요?',
      tiles: ['지금', '몇', '시예요'], gloss: ['now', 'what number', "o'clock (is it)?"], words: ['day:now', 'whattime'],
      traps: [{ tile: '언제', why: '언제 means “when”. To ask the time, use 몇 시: 지금 몇 시예요?' }] },
    { id: 's-fivehalf', level: 2, en: "I'm leaving at half past five.", ko: '다섯 시 반에 가요.',
      tiles: ['다섯', '시', '반에', '가요'], gloss: ['five', "o'clock", 'at half past', 'go'], words: ['five', 'oclock', 'half', 'day:go'],
      traps: [
        { tile: '반에서', why: 'To say at what time something happens, use 에: 다섯 시 반에.' },
        { tile: '반이', why: '다섯 시 반 is when you go, not the subject, so it takes 에: 다섯 시 반에.' },
      ] },
    { id: 's-threethirty', level: 2, en: "It's 3:30.", ko: '세 시 삼십 분이에요.',
      tiles: ['세', '시', '삼십', '분이에요'], gloss: ['three (before a counter)', "o'clock", 'thirty', 'minutes (it is)'],
      words: ['three', 'oclock', 'sam', 'sip', 'minute'],
      traps: [
        { tile: '서른', why: 'Minutes use Sino-Korean numbers: 삼십 분, not 서른 분.' },
        { tile: '삼', why: 'Hours use native Korean numbers: 세 시, not 삼 시. (And 30 minutes is 삼십 분: 삼 on its own is 3.)' },
      ] },
    { id: 's-oneoone', level: 2, en: "It's 1:01.", ko: '한 시 일 분이에요.',
      tiles: ['한', '시', '일', '분이에요'], gloss: ['one (native, before a counter)', "o'clock", 'one (Sino-Korean)', 'minute (it is)'],
      words: ['cafe:one', 'oclock', 'il', 'minute'],
      traps: [{ tile: '하나', why: 'Before a counter like 시, 하나 shortens to 한: 한 시.' }] },
    { id: 's-threeapples', level: 2, en: 'Three apples, please.', ko: '사과 세 개 주세요.',
      tiles: ['사과', '세', '개', '주세요'], gloss: ['apple', 'three (before a counter)', 'items', 'please give'],
      words: ['cafe:apple', 'three', 'item', 'cafe:please'],
      traps: [
        { tile: '삼', why: 'Count things with native Korean numbers: 세 개, not 삼 개.' },
        { tile: '잔', why: '잔 counts cups and glasses. For apples, use 개: 세 개.' },
      ] },
    { id: 's-monsat', level: 2, en: 'I work from Monday to Saturday.', ko: '월요일부터 토요일까지 일해요.',
      tiles: ['월요일부터', '토요일까지', '일해요'], gloss: ['from Monday', 'until Saturday', 'work'],
      words: ['monday', 'saturday', 'day:work'],
      traps: [{ tile: '월요일까지', why: '부터 means “from” and 까지 means “until”: 월요일부터 토요일까지.' }] },

    // ---- Level 3 ----
    { id: 's-bigprice', level: 3, en: "It's 13,200 won.", ko: '만 삼천이백 원이에요.',
      tiles: ['만', '삼천이백', '원이에요'], gloss: ['ten thousand', 'three thousand two hundred', 'won (it is)'],
      words: ['tenthousand', 'sam', 'thousand', 'i', 'hundred', 'won'],
      traps: [
        { tile: '십삼천', why: 'Korean counts big numbers in 만 (10,000), so 13,000 is 만 삼천 (one 만 + 3,000), not 십삼천.' },
        { tile: '세천', why: 'Prices use Sino-Korean numbers: 삼천, not 세천.' },
      ] },
    { id: 's-howold', level: 3, en: 'How old are you?', ko: '몇 살이에요?',
      tiles: ['몇', '살이에요'], gloss: ['how many', 'years old (is it)?'], words: ['howmany', 'age'],
      traps: [{ tile: '시예요', why: '몇 시예요? asks the time. To ask someone’s age, use 살: 몇 살이에요?' }] },
    { id: 's-birthday', level: 3, en: 'When is your birthday?', ko: '생일이 언제예요?',
      tiles: ['생일이', '언제예요'], gloss: ['birthday (subject)', 'when is it?'], words: ['birthday', 'when'],
      traps: [{ tile: '생일을', why: '생일 is what you’re asking about (the subject of “when is it?”), so it takes 이: 생일이 언제예요?' }] },
    { id: 's-phone', level: 3, en: "What's your phone number?", ko: '전화번호가 뭐예요?',
      tiles: ['전화번호가', '뭐예요'], gloss: ['phone number (subject)', 'what is it?'], words: ['phone', 'day:what'],
      traps: [{ tile: '전화번호를', why: '전화번호 is what you’re asking about (the subject of “what is it?”), so it takes 가: 전화번호가 뭐예요?' }] },
    { id: 's-tuethu', level: 3, en: 'I study Korean on Tuesdays and Thursdays.', ko: '화요일하고 목요일에 한국어를 공부해요.',
      tiles: ['화요일하고', '목요일에', '한국어를', '공부해요'], gloss: ['Tuesday and', 'on Thursday', 'Korean (object)', 'study'],
      words: ['tuesday', 'thursday', 'day:korean', 'day:study'], alts: [['한국어를', '화요일하고', '목요일에', '공부해요']],
      traps: [{ tile: '목요일에서', why: 'To say on which day something happens, use 에: 목요일에.' }] },
    // No particle questions here: spoken Korean also says 일요일이 시간이 있어요 (“Sunday is when I’m free”),
    // so 이 isn't clearly wrong after 일요일.
    { id: 's-wedsun', level: 3, en: "I'm free on Wednesday and Sunday.", ko: '수요일하고 일요일에 시간이 있어요.', drill: false,
      tiles: ['수요일하고', '일요일에', '시간이', '있어요'], gloss: ['Wednesday and', 'on Sunday', 'time (subject)', 'there is'],
      words: ['wednesday', 'sunday', 'hour', 'day:have'], alts: [['시간이', '수요일하고', '일요일에', '있어요']],
      traps: [{ tile: '시간을', why: '있어요 says that something is there. The thing that is there is the subject, so it takes 이: 시간이 있어요.' }] },
    { id: 's-fridayam', level: 3, en: "Let's meet at 10 a.m. on Friday.", ko: '금요일 오전 열 시에 만나요.',
      tiles: ['금요일', '오전', '열', '시에', '만나요'], gloss: ['Friday', 'a.m.', 'ten', "at … o'clock", 'meet'],
      words: ['friday', 'am', 'ten', 'oclock', 'day:meet'],
      traps: [
        { tile: '오후', why: '오후 means p.m. (after noon). For a.m., use 오전.' },
        { tile: '십', why: 'Hours use native Korean numbers: 열 시, not 십 시.' },
      ] },
    { id: 's-friendspm', level: 3, en: 'Two friends are coming in the afternoon.', ko: '오후에 친구 두 명이 와요.',
      tiles: ['오후에', '친구', '두', '명이', '와요'], gloss: ['in the afternoon', 'friend', 'two (before a counter)', 'people (subject)', 'come'],
      words: ['pm', 'day:friend', 'cafe:two', 'people', 'day:come'], alts: [['친구', '두', '명이', '오후에', '와요']],
      traps: [
        { tile: '이', why: 'Count people with native Korean numbers: 두 명, not 이 명.' },
        { tile: '개가', why: '개 counts things. For people, use 명: 두 명.' },
      ] },
  ],
});
