/**
 * Topic: 어제 뭐 했어요? · What did you do? — the past tense.
 * Verbs are taught in the polite past form (-았어요 / -었어요) you actually say,
 * with the dictionary form alongside. `form: 'past'` tells the game which form
 * each word is (checked against js/core/conjugate.js). The present forms are in
 * my-day.js. Field reference: see content/cafe.js and README → "Adding content".
 */
Mallang.content.registerTopic({
  id: 'past',
  order: 8,
  emoji: '📔',
  color: 'butter',
  title: { ko: '어제 뭐 했어요?', en: 'What did you do? (past tense)' },
  description: { ko: '지난 일 이야기하기', en: 'Talk about what you did' },

  notes: [
    {
      title: { ko: '-았어요 / -었어요', en: 'Past tense' },
      text: 'Drop **다**, then add **았어요** if the last vowel is ㅏ or ㅗ, otherwise **었어요**. Every **하다** verb becomes **했어요**. Vowels merge just as in the present: **갔어요**, **봤어요**, **마셨어요**, **왔어요**. Shortcut: take the present form, drop 요, put **ㅆ** under the last syllable and add **어요**: 와요 → **왔어요**.',
      examples: [
        { ko: '먹다 → 먹었어요', en: 'ate' },
        { ko: '만나다 → 만났어요', en: 'met' },
        { ko: '공부하다 → 공부했어요', en: 'studied' },
      ],
    },
    {
      title: { ko: '불규칙 동사', en: 'Irregular verbs' },
      text: 'Irregular verbs change just as they do in the present, so the shortcut still works: 들어요 → **들었어요** and 걸어요 → **걸었어요** (ㄷ → ㄹ), 추워요 → **추웠어요** (ㅂ → 우), 몰라요 → **몰랐어요** (르 → ㄹ라), 바빠요 → **바빴어요** (the ㅡ drops).',
      examples: [
        { ko: '어제 음악을 들었어요.', en: 'I listened to music yesterday.' },
        { ko: '어제 정말 추웠어요.', en: 'It was really cold yesterday.' },
        { ko: '미안해요, 몰랐어요.', en: 'Sorry, I didn’t know.' },
      ],
    },
    {
      title: { ko: '어제, 지난주, 작년', en: 'Past time words' },
      text: 'Time words usually come first. **어제** (yesterday) and **아까** (earlier) never take 에. **지난주**, **작년** and **어젯밤** often take 에 (지난주에, 작년에), but it can be left out. **오늘** works for the past too: 오늘 뭐 했어요?',
      examples: [
        { ko: '어제 친구를 만났어요.', en: 'I met a friend yesterday.' },
        { ko: '지난주에 카페에 갔어요.', en: 'I went to a café last week.' },
        { ko: '작년에 한국어를 공부했어요.', en: 'I studied Korean last year.' },
      ],
    },
    {
      title: { ko: '뭐 했어요?', en: 'Asking about the past' },
      text: '**뭐 했어요?** = What did you do? Ask how something was with **어땠어요?** (How was it?), and answer with a past adjective: **재미있었어요**, **맛있었어요**, **추웠어요**. Raise your voice at the end to make any of them a question: **재미있었어요?** The same form also means “have done”: **밥 먹었어요?** = Have you eaten?',
      examples: [
        { ko: '주말에 뭐 했어요?', en: 'What did you do on the weekend?' },
        { ko: '영화 어땠어요? — 재미있었어요!', en: 'How was the movie? — It was fun!' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'went', ko: '갔어요', en: 'went', level: 1, pos: 'verb', emoji: '👣', rom: 'gasseoyo', pron: '가써요', dict: '가다', form: 'past',
      note: '가다 → 가 + 았어요 → 갔어요 (the two ㅏ merge). The ㅆ slides into the next syllable: [가써요].',
      example: { ko: '어제 학교에 갔어요.', en: 'I went to school yesterday.' } },
    { id: 'ate', ko: '먹었어요', en: 'ate', level: 1, pos: 'verb', emoji: '🍽️', rom: 'meogeosseoyo', pron: '머거써요', dict: '먹다',
      form: 'past',
      note: '먹다 → 먹 + 었어요: the vowel is ㅓ (not ㅏ or ㅗ), so it takes 었어요.',
      example: { ko: '아침 먹었어요?', en: 'Did you have breakfast?' } },
    { id: 'did', ko: '했어요', en: 'did', level: 1, pos: 'verb', emoji: '☑️', rom: 'haesseoyo', pron: '해써요', dict: '하다', form: 'past',
      note: '하다 → 했어요. Every 하다 verb works the same way: 공부하다 → 공부했어요.',
      example: { ko: '숙제를 했어요.', en: 'I did my homework.' } },
    { id: 'whatdid', ko: '뭐 했어요?', en: 'what did you do?', level: 1, pos: 'phrase', emoji: '🤔', rom: 'mwo haesseoyo',
      pron: '뭐 해써요', accept: ['뭘 했어요?', '무엇을 했어요?'],
      note: '뭐 (what) + 했어요 (did). Put a time word in front: 어제 뭐 했어요?',
      example: { ko: '주말에 뭐 했어요?', en: 'What did you do on the weekend?' } },
    { id: 'lastweek', ko: '지난주', en: 'last week', level: 1, pos: 'noun', emoji: '🗓️', rom: 'jinanju',
      note: '지난 (last, gone by) + 주 (week), written as one word. Next week is 다음 주, with a space.',
      example: { ko: '지난주에 친구를 만났어요.', en: 'I met a friend last week.' } },
    { id: 'lastnight', ko: '어젯밤', en: 'last night', level: 1, pos: 'noun', emoji: '🌃', rom: 'eojetbam', pron: '어제빰',
      note: '어제 (yesterday) + 밤 (night). The ㅅ in the middle makes the ㅂ tense: [어제빰].',
      example: { ko: '어젯밤 늦게 잤어요.', en: 'I went to bed late last night.' } },

    // ---- Level 2 ----
    { id: 'saw', ko: '봤어요', en: 'saw / watched', level: 2, pos: 'verb', emoji: '📺', rom: 'bwasseoyo', pron: '봐써요', dict: '보다',
      form: 'past', accept: ['보았어요'],
      note: '보다 → 보 + 았어요 → 봤어요 (ㅗ + ㅏ merge into ㅘ). 보았어요 is also correct, just less common.',
      example: { ko: '그 영화 봤어요?', en: 'Have you seen that movie?' } },
    { id: 'bought', ko: '샀어요', en: 'bought', level: 2, pos: 'verb', emoji: '🛒', rom: 'sasseoyo', pron: '사써요', dict: '사다',
      form: 'past',
      note: '사다 → 사 + 았어요 → 샀어요 (the two ㅏ merge).',
      example: { ko: '카페에서 케이크를 샀어요.', en: 'I bought a cake at the café.' } },
    { id: 'met', ko: '만났어요', en: 'met', level: 2, pos: 'verb', emoji: '👋', rom: 'mannasseoyo', pron: '만나써요', dict: '만나다',
      form: 'past', avoid: ['saw'],
      note: '만나다 → 만나 + 았어요 → 만났어요. The person you meet takes 을/를: 친구를 만났어요.',
      example: { ko: '어디에서 만났어요?', en: 'Where did you meet?' } },
    { id: 'slept', ko: '잤어요', en: 'slept', level: 2, pos: 'verb', emoji: '💤', rom: 'jasseoyo', pron: '자써요', dict: '자다',
      form: 'past', enAlt: ['went to bed', 'went to sleep'],
      note: '자다 → 자 + 았어요 → 잤어요. 잘 잤어요? (Did you sleep well?) is a common good-morning greeting.',
      example: { ko: '잘 잤어요?', en: 'Did you sleep well?' } },
    { id: 'drank', ko: '마셨어요', en: 'drank', level: 2, pos: 'verb', emoji: '🍹', rom: 'masyeosseoyo', pron: '마셔써요',
      dict: '마시다', form: 'past', accept: ['마시었어요'],
      note: '마시다 → 마시 + 었어요 → 마셨어요 (ㅣ + ㅓ merge into ㅕ).',
      example: { ko: '아침에 커피를 마셨어요.', en: 'I had coffee in the morning.' } },
    { id: 'came', ko: '왔어요', en: 'came', level: 2, pos: 'verb', emoji: '🚪', rom: 'wasseoyo', pron: '와써요', dict: '오다',
      form: 'past',
      note: '오다 → 오 + 았어요 → 왔어요 (ㅗ + ㅏ merge into ㅘ). Rain “comes” in Korean: 비가 왔어요 = It rained.',
      example: { ko: '언제 왔어요?', en: 'When did you get here?' } },
    { id: 'studied', ko: '공부했어요', en: 'studied', level: 2, pos: 'verb', emoji: '✏️', rom: 'gongbuhaesseoyo',
      pron: '공부해써요', dict: '공부하다', form: 'past',
      note: '공부 (study) + 했어요. Every 하다 verb becomes 했어요 in the past.',
      example: { ko: '어제 한국어를 공부했어요.', en: 'I studied Korean yesterday.' } },
    { id: 'worked', ko: '일했어요', en: 'worked', level: 2, pos: 'verb', emoji: '💻', rom: 'ilhaesseoyo', pron: '일해써요',
      dict: '일하다', form: 'past',
      note: '일 (work) + 했어요. In fast speech the ㅎ softens, so it can sound like “이래써요”.',
      example: { ko: '주말에도 일했어요.', en: 'I worked on the weekend too.' } },
    { id: 'wasfun', ko: '재미있었어요', en: 'it was fun', level: 2, pos: 'adjective', emoji: '🥳', rom: 'jaemiisseosseoyo',
      pron: '재미이써써요', dict: '재미있다', form: 'past', accept: ['재밌었어요'],
      enAlt: ['was fun', 'it was interesting', 'was interesting'],
      note: '재미 (fun) + 있었어요 (there was). In speech it’s often shortened to 재밌었어요. The opposite is 재미없었어요.',
      example: { ko: '영화 재미있었어요?', en: 'Did you enjoy the movie?' } },
    { id: 'wasdelicious', ko: '맛있었어요', en: 'it was delicious', level: 2, pos: 'adjective', emoji: '🍲',
      rom: 'masisseosseoyo', pron: '마시써써요', dict: '맛있다', form: 'past',
      enAlt: ['was delicious', 'it was tasty', 'was tasty'],
      note: '맛있어요 (it’s delicious) → 맛있었어요 (it was delicious): 있 + 었어요. Say it [마시써써요].',
      example: { ko: '케이크 정말 맛있었어요!', en: 'The cake was really delicious!' } },
    { id: 'lastyear', ko: '작년', en: 'last year', level: 2, pos: 'noun', emoji: '📆', rom: 'jangnyeon', pron: '장년',
      note: 'ㄱ before ㄴ sounds like ㅇ: [장년]. This year is 올해, and next year is 내년.',
      example: { ko: '작년에 한국에 갔어요.', en: 'I went to Korea last year.' } },
    { id: 'earlier', ko: '아까', en: 'a moment ago / earlier', level: 2, pos: 'adverb', emoji: '⏱️', rom: 'akka',
      avoid: ['day:early'], enAlt: ['a while ago', 'a little while ago'],
      note: 'A little while ago, earlier today. Like 어제, it never takes 에.',
      example: { ko: '아까 뭐 먹었어요?', en: 'What did you eat earlier?' } },

    // ---- Level 3 ----
    { id: 'listened', ko: '들었어요', en: 'listened / heard', level: 3, pos: 'verb', emoji: '👂', rom: 'deureosseoyo',
      pron: '드러써요', dict: '듣다', form: 'past',
      note: '듣다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 들 + 었어요 → 들었어요.',
      example: { ko: '그 이야기 들었어요?', en: 'Did you hear about that?' } },
    { id: 'walked', ko: '걸었어요', en: 'walked', level: 3, pos: 'verb', emoji: '🥾', rom: 'georeosseoyo', pron: '거러써요',
      dict: '걷다', form: 'past',
      note: '걷다 is ㄷ-irregular, like 듣다: 걷 → 걸 + 었어요 → 걸었어요.',
      example: { ko: '오늘 많이 걸었어요.', en: 'I walked a lot today.' } },
    { id: 'wascold', ko: '추웠어요', en: 'it was cold', level: 3, pos: 'adjective', emoji: '🥶', rom: 'chuwosseoyo',
      pron: '추워써요', dict: '춥다', form: 'past', enAlt: ['was cold', 'I was cold'],
      note: '춥다 is ㅂ-irregular: ㅂ turns into 우 → 추우 + 었어요 → 추웠어요. It’s for the weather and feeling cold; cold things (like water) are 차가워요.',
      example: { ko: '어제 정말 추웠어요.', en: 'It was really cold yesterday.' } },
    { id: 'wasbusy', ko: '바빴어요', en: 'I was busy', level: 3, pos: 'adjective', emoji: '😫', rom: 'bappasseoyo',
      pron: '바빠써요', dict: '바쁘다', form: 'past', enAlt: ['was busy'],
      note: '바쁘다: the ㅡ drops, and 바 has ㅏ, so it takes 았어요 → 바빴어요.',
      example: { ko: '지난주에 정말 바빴어요.', en: 'I was really busy last week.' } },
    { id: 'didntknow', ko: '몰랐어요', en: "I didn't know", level: 3, pos: 'verb', emoji: '🤷', rom: 'mollasseoyo',
      pron: '몰라써요', dict: '모르다', form: 'past', enAlt: ["didn't know", 'did not know', 'I did not know'],
      note: '모르다 is 르-irregular: 르 turns into ㄹ라 → 몰라요 → 몰랐어요. Its opposite, 알았어요, also means “Got it!”',
      example: { ko: '미안해요, 몰랐어요.', en: 'Sorry, I didn’t know.' } },
    { id: 'played', ko: '놀았어요', en: 'played / hung out', level: 3, pos: 'verb', emoji: '🎡', rom: 'norasseoyo',
      pron: '노라써요', dict: '놀다', form: 'past',
      note: '놀다 → 놀 + 았어요 → 놀았어요. It’s playing for fun or hanging out; for sports and games, use 했어요.',
      example: { ko: '주말에 친구하고 놀았어요.', en: 'I hung out with friends on the weekend.' } },
    { id: 'travelled', ko: '여행했어요', en: 'travelled', level: 3, pos: 'verb', emoji: '✈️', rom: 'yeohaenghaesseoyo',
      pron: '여행해써요', dict: '여행하다', form: 'past', enAlt: ['went on a trip', 'took a trip'],
      note: '여행 (trip) + 했어요. You can also say 여행을 갔어요 (I went on a trip).',
      example: { ko: '작년에 한국을 여행했어요.', en: 'I travelled around Korea last year.' } },
    { id: 'rested', ko: '쉬었어요', en: 'rested', level: 3, pos: 'verb', emoji: '😌', rom: 'swieosseoyo', pron: '쉬어써요',
      dict: '쉬다', form: 'past', enAlt: ['took a rest', 'took a break', 'relaxed'],
      note: '쉬다 → 쉬 + 었어요 → 쉬었어요 (ㅟ doesn’t merge with ㅓ).',
      example: { ko: '어제는 집에서 쉬었어요.', en: 'Yesterday I rested at home.' } },
    { id: 'made', ko: '만들었어요', en: 'made', level: 3, pos: 'verb', emoji: '🛠️', rom: 'mandeureosseoyo', pron: '만드러써요',
      dict: '만들다', form: 'past',
      note: '만들다 → 만들 + 었어요 (the last vowel is ㅡ, so 었어요). The ㄹ slides over: [만드러써요].',
      example: { ko: '제가 이 케이크를 만들었어요!', en: 'I made this cake!' } },
    { id: 'read', ko: '읽었어요', en: 'read (past)', level: 3, pos: 'verb', emoji: '📗', rom: 'ilgeosseoyo', pron: '일거써요',
      dict: '읽다', form: 'past',
      note: '읽다 → 읽 + 었어요. As in 읽어요, the ㄹ stays and the ㄱ slides over: [일거써요].',
      example: { ko: '이 책 읽었어요?', en: 'Have you read this book?' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-whatdid', en: 'What did you do yesterday?', ko: '어제 뭐 했어요?',
      tiles: ['어제', '뭐', '했어요'], gloss: ['yesterday', 'what', 'did'], words: ['day:yesterday', 'whatdid', 'did'],
      traps: [
        { tile: '해요', why: '어제 (yesterday) needs the past tense: 했어요.' },
        { tile: '어제에', why: '어제 (yesterday) never takes 에. Just say 어제.' },
      ] },
    { id: 's-ate', en: 'I had a meal with a friend yesterday.', ko: '어제 친구하고 밥을 먹었어요.',
      tiles: ['어제', '친구하고', '밥을', '먹었어요'], gloss: ['yesterday', 'with a friend', 'meal (object)', 'ate'],
      words: ['day:yesterday', 'day:friend', 'day:meal', 'ate'],
      alts: [['친구하고', '어제', '밥을', '먹었어요'], ['어제', '밥을', '친구하고', '먹었어요']],
      traps: [
        { tile: '먹어요', why: '어제 (yesterday) needs the past tense: 먹었어요.' },
        { tile: '마셨어요', why: '마셨어요 means “drank”. For a meal, use 먹었어요.' },
      ] },
    { id: 's-went', en: 'I went to a café last week.', ko: '지난주에 카페에 갔어요.',
      tiles: ['지난주에', '카페에', '갔어요'], gloss: ['last week', 'to a café', 'went'], words: ['lastweek', 'cafe:cafe', 'went'],
      alts: [['카페에', '지난주에', '갔어요']],
      traps: [
        { tile: '카페에서', why: '에 marks where you went. 에서 marks where an action happens.' },
        { tile: '가요', why: '지난주 (last week) needs the past tense: 갔어요.' },
      ] },

    // ---- Level 2 ----
    { id: 's-movie', level: 2, en: 'I watched a movie last night. It was fun!', ko: '어젯밤 영화를 봤어요. 재미있었어요!',
      tiles: ['어젯밤', '영화를', '봤어요', '재미있었어요'], gloss: ['last night', 'movie (object)', 'watched', 'it was fun'],
      words: ['lastnight', 'day:movie', 'saw', 'wasfun'],
      alts: [['영화를', '어젯밤', '봤어요', '재미있었어요']],
      traps: [
        { tile: '봐요', why: '어젯밤 (last night) needs the past tense: 봤어요.' },
        { tile: '재미있어요', why: 'The movie is over, so use the past: 재미있었어요 (it was fun).' },
      ] },
    { id: 's-bought', level: 2, en: 'I bought bread and milk earlier.', ko: '아까 빵하고 우유를 샀어요.',
      tiles: ['아까', '빵하고', '우유를', '샀어요'], gloss: ['earlier', 'bread and', 'milk (object)', 'bought'],
      words: ['earlier', 'cafe:bread', 'cafe:milk', 'bought'],
      alts: [['빵하고', '우유를', '아까', '샀어요']],
      traps: [{ tile: '사요', why: '아까 (earlier) is in the past, so use 샀어요 (bought).' }] },
    { id: 's-studied', level: 2, en: 'I studied at the library yesterday.', ko: '어제 도서관에서 공부했어요.',
      tiles: ['어제', '도서관에서', '공부했어요'], gloss: ['yesterday', 'at the library', 'studied'],
      words: ['day:yesterday', 'day:library', 'studied'], alts: [['도서관에서', '어제', '공부했어요']],
      traps: [
        { tile: '도서관에', why: 'Studying is something you do there, so the place takes 에서: 도서관에서.' },
        { tile: '공부해요', why: '어제 (yesterday) needs the past tense: 공부했어요.' },
      ] },
    { id: 's-slept', level: 2, en: 'I slept at my friend’s place.', ko: '친구 집에서 잤어요.',
      tiles: ['친구', '집에서', '잤어요'], gloss: ['friend’s', 'at the house', 'slept'], words: ['day:friend', 'day:home', 'slept'],
      traps: [
        { tile: '집에', why: 'Sleeping is something you do there, so the place takes 에서: 집에서.' },
        { tile: '자요', why: 'The English says “slept” (the past), so use 잤어요.' },
      ] },
    { id: 's-worked', level: 2, en: 'I worked at the office today.', ko: '오늘 회사에서 일했어요.',
      tiles: ['오늘', '회사에서', '일했어요'], gloss: ['today', 'at the office', 'worked'],
      words: ['day:today', 'day:company', 'worked'], alts: [['회사에서', '오늘', '일했어요']],
      traps: [
        { tile: '회사에', why: 'Working is something you do there, so the place takes 에서: 회사에서.' },
        { tile: '일해요', why: 'The English says “worked” (the past), so use 일했어요.' },
      ] },

    // ---- Level 3 ----
    { id: 's-met', level: 3, en: 'I met a friend at a café. We had coffee.', ko: '카페에서 친구를 만났어요. 커피를 마셨어요.',
      tiles: ['카페에서', '친구를', '만났어요', '커피를', '마셨어요'],
      gloss: ['at a café', 'friend (object)', 'met', 'coffee (object)', 'drank'],
      words: ['cafe:cafe', 'day:friend', 'met', 'cafe:coffee', 'drank'],
      alts: [['친구를', '카페에서', '만났어요', '커피를', '마셨어요']],
      traps: [
        { tile: '카페에', why: 'Meeting someone is something you do there, so the place takes 에서: 카페에서.' },
        { tile: '마셔요', why: 'This already happened, so use the past: 마셨어요.' },
      ] },
    { id: 's-came', level: 3, en: 'My friend came over. We hung out together!', ko: '친구가 집에 왔어요. 같이 놀았어요!',
      tiles: ['친구가', '집에', '왔어요', '같이', '놀았어요'],
      gloss: ['friend (subject)', 'to (my) home', 'came', 'together', 'played / hung out'],
      words: ['day:friend', 'day:home', 'came', 'day:together', 'played'],
      alts: [['집에', '친구가', '왔어요', '같이', '놀았어요']],
      traps: [
        { tile: '친구를', why: 'Your friend is the one who came (the subject), so it takes 가: 친구가.' },
        { tile: '놀아요', why: 'This already happened, so use the past: 놀았어요.' },
      ] },
    { id: 's-made', level: 3, en: 'I made a cake. It was delicious!', ko: '케이크를 만들었어요. 맛있었어요!',
      tiles: ['케이크를', '만들었어요', '맛있었어요'], gloss: ['cake (object)', 'made', 'it was delicious'],
      words: ['cafe:cake', 'made', 'wasdelicious'],
      traps: [
        { tile: '만들았어요', why: 'The last vowel of 만들다 is ㅡ (not ㅏ or ㅗ), so it takes 었어요: 만들었어요.' },
        { tile: '맛있어요', why: 'The English says “was”, so use the past: 맛있었어요.' },
      ] },
    { id: 's-busy', level: 3, en: 'You were busy earlier? I didn’t know!', ko: '아까 바빴어요? 몰랐어요!',
      tiles: ['아까', '바빴어요', '몰랐어요'], gloss: ['earlier', 'were (you) busy?', 'I didn’t know'],
      words: ['earlier', 'wasbusy', 'didntknow'],
      traps: [
        { tile: '바뻤어요', why: 'After the ㅡ drops, 바쁘다 follows the vowel of 바 (ㅏ), so it takes 았어요: 바빴어요.' },
        { tile: '몰라요', why: '몰라요 means “I don’t know”. “I didn’t know” is the past: 몰랐어요.' },
      ] },
    { id: 's-walked', level: 3, en: 'I walked a little in the evening. It was cold!', ko: '저녁에 좀 걸었어요. 추웠어요!',
      tiles: ['저녁에', '좀', '걸었어요', '추웠어요'], gloss: ['in the evening', 'a little', 'walked', 'it was cold'],
      words: ['day:evening', 'walked', 'wascold'],
      traps: [
        { tile: '걷었어요', why: '걷다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 걸었어요.' },
        { tile: '춥었어요', why: '춥다 is ㅂ-irregular: ㅂ turns into 우 → 추웠어요.' },
      ] },
    { id: 's-rested', level: 3, en: 'I rested at home on the weekend. I read a book.', ko: '주말에 집에서 쉬었어요. 책을 읽었어요.',
      tiles: ['주말에', '집에서', '쉬었어요', '책을', '읽었어요'],
      gloss: ['on the weekend', 'at home', 'rested', 'book (object)', 'read'],
      words: ['day:weekend', 'day:home', 'rested', 'day:book', 'read'],
      alts: [['집에서', '주말에', '쉬었어요', '책을', '읽었어요']],
      traps: [
        { tile: '집에', why: 'Resting is something you do there, so the place takes 에서: 집에서.' },
        { tile: '읽어요', why: 'This already happened, so use the past: 읽었어요.' },
      ] },
    { id: 's-music', level: 3, en: 'I listened to music yesterday.', ko: '어제 음악을 들었어요.',
      tiles: ['어제', '음악을', '들었어요'], gloss: ['yesterday', 'music (object)', 'listened'],
      words: ['day:yesterday', 'hobbies:music', 'listened'], alts: [['음악을', '어제', '들었어요']],
      traps: [
        { tile: '듣었어요', why: '듣다 is ㄷ-irregular: before a vowel, ㄷ turns into ㄹ → 들었어요.' },
        { tile: '들어요', why: '어제 (yesterday) needs the past tense: 들었어요.' },
      ] },
    { id: 's-travelled', level: 3, en: 'I travelled with a friend last year.', ko: '작년에 친구하고 여행했어요.',
      tiles: ['작년에', '친구하고', '여행했어요'], gloss: ['last year', 'with a friend', 'travelled'],
      words: ['lastyear', 'day:friend', 'travelled'], alts: [['친구하고', '작년에', '여행했어요']],
      traps: [
        { tile: '여행해요', why: '작년 (last year) needs the past tense: 여행했어요.' },
        { tile: '작년에서', why: 'To say when something happens, use 에, not 에서: 작년에.' },
        { tile: '여행했요', why: 'The past tense ends in ㅆ + 어요, not just ㅆ요: 여행했어요.' },
      ] },
  ],
});
