/**
 * Topic: 가족과 사람 · Family & people — introducing yourself and your family.
 * Some family words depend on who is speaking (형/오빠, 누나/언니), and some
 * come in a plain and a polite version (엄마/어머니). Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'people',
  order: 3,
  emoji: '👨‍👩‍👧',
  color: 'butter',
  title: { ko: '가족과 사람', en: 'Family & people' },
  description: { ko: '나와 가족 소개하기', en: 'Introduce yourself and your family' },

  notes: [
    {
      title: { ko: '저는 ~이에요 / 예요', en: 'Introducing yourself' },
      text: 'Start with **저는** (“I”, as the topic) and end with **이에요** after a consonant (받침) or **예요** after a vowel. For your name, say **제 이름은** … (제 = my).',
      examples: [
        { ko: '저는 학생이에요.', en: 'I’m a student.' },
        { ko: '저는 의사예요.', en: 'I’m a doctor.' },
        { ko: '제 이름은 민지예요.', en: 'My name is Minji.' },
      ],
    },
    {
      title: { ko: '형, 오빠, 누나, 언니', en: 'Older brother or sister?' },
      text: 'These words depend on **who is speaking**. A man says **형** (older brother) and **누나** (older sister). A woman says **오빠** (older brother) and **언니** (older sister). A younger brother or sister is **동생**, whoever is speaking. Koreans also use these words for close older friends.',
      examples: [
        { ko: '형이 있어요.', en: 'I have an older brother. (a man speaking)' },
        { ko: '언니가 있어요.', en: 'I have an older sister. (a woman speaking)' },
      ],
    },
    {
      title: { ko: '엄마 / 어머니', en: 'Mom or mother?' },
      text: '**엄마** and **아빠** are the everyday words, and adults use them too. **어머니** and **아버지** are more polite, for formal situations. When you talk to older people like your grandparents, the verb often takes the extra-polite **-세요** ending: 어디 가세요?',
      examples: [
        { ko: '엄마하고 아빠는 집에 있어요.', en: 'Mom and Dad are at home.' },
        { ko: '아버지, 어머니, 감사합니다!', en: 'Thank you, Father and Mother!' },
        { ko: '할머니, 어디 가세요?', en: 'Grandma, where are you going?' },
      ],
    },
    {
      title: { ko: '있어요? · 누구예요?', en: 'Asking about people' },
      text: 'Ask about someone’s family with **있어요?** (“do you have…?”). The family member takes **이/가**. Answer **네, 있어요** or **아니요, 없어요**. To ask who someone is, use **누구예요?**',
      examples: [
        { ko: '동생이 있어요?', en: 'Do you have a younger brother or sister?' },
        { ko: '아니요, 없어요.', en: 'No, I don’t.' },
        { ko: '이 사람은 누구예요?', en: 'Who is this person?' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'me', ko: '저', en: 'I / me (polite)', level: 1, pos: 'pronoun', emoji: '🙋', rom: 'jeo',
      note: 'The polite word for “I”. 제 means “my” (제 이름 = my name), and 저 + 가 becomes 제가.',
      example: { ko: '저도 학생이에요.', en: 'I’m a student, too.' } },
    { id: 'family', ko: '가족', en: 'family', level: 1, pos: 'noun', emoji: '👪', rom: 'gajok',
      note: 'Koreans usually say 우리 가족 (“our family”) for “my family”.',
      example: { ko: '가족이 몇 명이에요?', en: 'How many people are in your family?' } },
    { id: 'mom', ko: '엄마', en: 'mom / mum', level: 1, pos: 'noun', emoji: '👩', rom: 'eomma', avoid: ['mother'],
      enAlt: ['mother', 'mommy', 'mummy'],
      note: 'The everyday word, used by children and adults alike. The more polite word is 어머니.',
      example: { ko: '엄마, 배고파요!', en: 'Mom, I’m hungry!' } },
    { id: 'dad', ko: '아빠', en: 'dad', level: 1, pos: 'noun', emoji: '👨', rom: 'appa', avoid: ['father'],
      enAlt: ['father', 'daddy'],
      note: 'The everyday word for “dad”. The more polite word is 아버지.',
      example: { ko: '아빠, 어디 가요?', en: 'Dad, where are you going?' } },
    { id: 'person', ko: '사람', en: 'person / people', level: 1, pos: 'noun', emoji: '🧍', rom: 'saram',
      note: 'Country + 사람 = someone from that country: 한국 사람 (a Korean), 미국 사람 (an American).',
      example: { ko: '한국 사람이에요?', en: 'Are you Korean?' } },
    { id: 'name', ko: '이름', en: 'name', level: 1, pos: 'noun', emoji: '📛', rom: 'ireum',
      note: 'Say “my name is …” with 제 이름은 …이에요/예요.',
      example: { ko: '이름이 뭐예요?', en: 'What’s your name?' } },
    { id: 'who', ko: '누구', en: 'who', level: 1, pos: 'pronoun', emoji: '🤔', rom: 'nugu',
      note: 'With 가, 누구 shortens to 누가: 누가 와요? = Who’s coming?',
      example: { ko: '이 사람은 누구예요?', en: 'Who is this person?' } },
    { id: 'child', ko: '아이', en: 'child / kid', level: 1, pos: 'noun', emoji: '🧒', rom: 'ai', accept: ['애'],
      enAlt: ['children', 'kids'],
      note: 'In speech it’s often shortened to 애.',
      example: { ko: '아이가 둘 있어요.', en: 'I have two kids.' } },
    { id: 'teacher', ko: '선생님', en: 'teacher', level: 1, pos: 'noun', emoji: '🧑‍🏫', rom: 'seonsaengnim', avoid: ['doctor'],
      note: '님 adds respect. You call your teacher 선생님, not by their name.',
      example: { ko: '한국어 선생님이 누구예요?', en: 'Who is your Korean teacher?' } },

    // ---- Level 2 ----
    { id: 'mother', ko: '어머니', en: 'mother', level: 2, pos: 'noun', emoji: '👩‍👧', rom: 'eomeoni', enAlt: ['mom'],
      note: 'More polite and formal than 엄마, e.g. when you talk about your mother to someone older.',
      example: { ko: '어머니하고 점심을 먹어요.', en: 'I’m having lunch with my mother.' } },
    { id: 'father', ko: '아버지', en: 'father', level: 2, pos: 'noun', emoji: '👨‍👦', rom: 'abeoji', enAlt: ['dad'],
      note: 'More polite and formal than 아빠.',
      example: { ko: '아버지하고 영화를 봐요.', en: 'I’m watching a movie with my father.' } },
    { id: 'hyung', ko: '형', en: 'older brother (of a male)', level: 2, pos: 'noun', emoji: '👦', rom: 'hyeong',
      enAlt: ['big brother', 'elder brother'],
      note: 'The word men and boys use. Men also call close older male friends 형.',
      example: { ko: '형이 두 명 있어요.', en: 'I have two older brothers.' } },
    { id: 'oppa', ko: '오빠', en: 'older brother (of a female)', level: 2, pos: 'noun', emoji: '🧑', rom: 'oppa',
      avoid: ['boyfriend'], enAlt: ['big brother', 'elder brother'],
      note: 'The word women and girls use. Women also call close older male friends, or a boyfriend, 오빠.',
      example: { ko: '오빠는 회사원이에요.', en: 'My older brother is an office worker.' } },
    { id: 'nuna', ko: '누나', en: 'older sister (of a male)', level: 2, pos: 'noun', emoji: '👧', rom: 'nuna',
      enAlt: ['big sister', 'elder sister'],
      note: 'The word men and boys use, also for close older female friends.',
      example: { ko: '누나는 의사예요.', en: 'My older sister is a doctor.' } },
    { id: 'unni', ko: '언니', en: 'older sister (of a female)', level: 2, pos: 'noun', emoji: '👩‍🦰', rom: 'eonni',
      enAlt: ['big sister', 'elder sister'],
      note: 'The word women and girls use, also for close older female friends.',
      example: { ko: '언니하고 카페에 가요.', en: 'I’m going to a café with my older sister.' } },
    { id: 'sibling', ko: '동생', en: 'younger sibling', level: 2, pos: 'noun', emoji: '🐣', rom: 'dongsaeng',
      enAlt: ['younger brother', 'younger sister', 'little brother', 'little sister', 'sibling'],
      note: 'For a younger brother or sister, whoever is speaking. To be exact: 남동생 (younger brother), 여동생 (younger sister).',
      example: { ko: '동생이 있어요?', en: 'Do you have a younger brother or sister?' } },
    { id: 'man', ko: '남자', en: 'man', level: 2, pos: 'noun', emoji: '🚹', rom: 'namja', enAlt: ['male', 'guy'],
      note: 'Also means “male”: 남자 화장실 = men’s restroom.',
      example: { ko: '남자 화장실이 어디예요?', en: 'Where is the men’s restroom?' } },
    { id: 'woman', ko: '여자', en: 'woman', level: 2, pos: 'noun', emoji: '🚺', rom: 'yeoja', enAlt: ['female', 'lady'],
      note: 'Also means “female”: 여자 화장실 = women’s restroom.',
      example: { ko: '저 여자는 선생님이에요.', en: 'That woman is a teacher.' } },
    { id: 'student', ko: '학생', en: 'student', level: 2, pos: 'noun', emoji: '🎒', rom: 'haksaeng', pron: '학쌩',
      note: 'After a ㄱ 받침, ㅅ gets tense: [학쌩].',
      example: { ko: '저는 학생이에요.', en: 'I’m a student.' } },

    // ---- Level 3 ----
    { id: 'grandma', ko: '할머니', en: 'grandmother', level: 3, pos: 'noun', emoji: '👵', rom: 'halmeoni',
      enAlt: ['grandma', 'granny'],
      note: 'Also a friendly, polite way to address any elderly woman.',
      example: { ko: '할머니, 안녕하세요!', en: 'Hello, Grandma!' } },
    { id: 'grandpa', ko: '할아버지', en: 'grandfather', level: 3, pos: 'noun', emoji: '👴', rom: 'harabeoji', pron: '하라버지',
      enAlt: ['grandpa'],
      note: 'The ㄹ slides into the next syllable: [하라버지]. Also a polite way to address any elderly man.',
      example: { ko: '할아버지, 감사합니다!', en: 'Thank you, Grandpa!' } },
    { id: 'husband', ko: '남편', en: 'husband', level: 3, pos: 'noun', emoji: '🤵', rom: 'nampyeon',
      note: 'Someone else’s husband is politely called 남편분.',
      example: { ko: '남편이 매일 요리해요.', en: 'My husband cooks every day.' } },
    { id: 'wife', ko: '아내', en: 'wife', level: 3, pos: 'noun', emoji: '👰', rom: 'anae',
      note: 'Someone else’s wife is politely called 부인.',
      example: { ko: '아내하고 점심을 먹어요.', en: 'I’m having lunch with my wife.' } },
    { id: 'boyfriend', ko: '남자 친구', en: 'boyfriend', level: 3, pos: 'noun', emoji: '💑', rom: 'namja chingu',
      note: '남자 (man) + 친구 (friend). In casual talk it’s often shortened to 남친.',
      example: { ko: '남자 친구 있어요?', en: 'Do you have a boyfriend?' } },
    { id: 'girlfriend', ko: '여자 친구', en: 'girlfriend', level: 3, pos: 'noun', emoji: '💕', rom: 'yeoja chingu',
      note: '여자 (woman) + 친구 (friend). In casual talk it’s often shortened to 여친.',
      example: { ko: '제 여자 친구예요.', en: 'This is my girlfriend.' } },
    { id: 'doctor', ko: '의사', en: 'doctor', level: 3, pos: 'noun', emoji: '🧑‍⚕️', rom: 'uisa',
      note: 'When you speak to a doctor, call them 선생님 or 의사 선생님.',
      example: { ko: '저는 의사예요.', en: 'I’m a doctor.' } },
    { id: 'officeworker', ko: '회사원', en: 'office worker', level: 3, pos: 'noun', emoji: '👔', rom: 'hoesawon',
      enAlt: ['office employee', 'company employee', 'employee', 'salaryman'],
      note: '회사 (company) + 원 (member).',
      example: { ko: '저는 회사원이에요.', en: 'I’m an office worker.' } },
    { id: 'married', ko: '결혼했어요', en: "I'm married", level: 3, pos: 'verb', emoji: '💍', rom: 'gyeolhonhaesseoyo',
      pron: '결혼해써요', dict: '결혼하다', form: 'past', enAlt: ['got married', 'is married', 'are married'],
      note: 'Korean uses the past form for “I’m married” (literally “I got married”). 결혼했어요? = Are you married?',
      example: { ko: '네, 결혼했어요.', en: 'Yes, I’m married.' } },
    { id: 'tall', ko: '키가 커요', en: '(someone) is tall', level: 3, pos: 'phrase', emoji: '🦒', rom: 'kiga keoyo',
      accept: ['키 커요'], enAlt: ['tall', 'is tall'],
      note: '키 (height) + 커요 (is big) → tall. The opposite is 키가 작아요.',
      example: { ko: '와, 키가 정말 커요!', en: 'Wow, you’re really tall!' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-name', en: 'What’s this person’s name?', ko: '이 사람 이름이 뭐예요?',
      tiles: ['이', '사람', '이름이', '뭐예요'], gloss: ['this', 'person', 'name (subject)', 'what is it?'],
      words: ['person', 'name', 'day:what'],
      traps: [{ tile: '이름을', why: '이름 is what you’re asking about (the subject of “what is it?”), so it takes 이: 이름이 뭐예요?' }] },
    { id: 's-teacher', en: 'I’m a teacher.', ko: '저는 선생님이에요.',
      tiles: ['저는', '선생님이에요'], gloss: ['I (topic)', 'am a teacher'], words: ['me', 'teacher'],
      traps: [{ tile: '선생님예요', why: '선생님 ends in a consonant (받침), so it takes 이에요. 예요 goes after vowels.' }] },
    { id: 's-momdad', en: 'Mom and Dad are at home.', ko: '엄마하고 아빠는 집에 있어요.',
      tiles: ['엄마하고', '아빠는', '집에', '있어요'], gloss: ['Mom and', 'Dad (topic)', 'at home', 'are (there)'],
      words: ['mom', 'dad', 'day:home', 'day:have'],
      traps: [{ tile: '집에서', why: 'To say where someone is, use 에 with 있어요: 집에 있어요. 에서 is for where an action happens.' }] },
    { id: 's-family', en: 'I have dinner with my family.', ko: '가족하고 저녁을 먹어요.',
      tiles: ['가족하고', '저녁을', '먹어요'], gloss: ['with (my) family', 'dinner (object)', 'eat'],
      words: ['family', 'day:evening', 'day:eat'], alts: [['저녁을', '가족하고', '먹어요']] },
    { id: 's-child', en: 'Do you have children?', ko: '아이가 있어요?',
      tiles: ['아이가', '있어요'], gloss: ['child (subject)', 'is there? / do you have?'], words: ['child', 'day:have'],
      traps: [{ tile: '아이를', why: '있어요 says that something is there. The thing that is there is the subject, so it takes 가: 아이가 있어요?' }] },

    // ---- Level 2 ----
    { id: 's-who', level: 2, en: 'Who is that man?', ko: '저 남자는 누구예요?',
      tiles: ['저', '남자는', '누구예요'], gloss: ['that', 'man (topic)', 'who is it?'], words: ['man', 'who'],
      traps: [
        { tile: '뭐예요', why: '뭐예요 means “what is it?”. To ask about a person, use 누구예요? (who is it?).' },
        { tile: '여자는', why: '여자 means “woman”. “Man” is 남자.' },
      ] },
    { id: 's-restroom', level: 2, en: 'Where is the women’s restroom?', ko: '여자 화장실이 어디예요?',
      tiles: ['여자', '화장실이', '어디예요'], gloss: ['women’s', 'restroom (subject)', 'where is it?'],
      words: ['woman', 'directions:toilet', 'directions:where'],
      traps: [{ tile: '남자', why: '남자 means “man”. The women’s restroom is 여자 화장실.' }] },
    { id: 's-student', level: 2, en: 'My younger sibling is a student.', ko: '동생은 학생이에요.',
      tiles: ['동생은', '학생이에요'], gloss: ['younger sibling (topic)', 'is a student'], words: ['sibling', 'student'],
      traps: [{ tile: '학생예요', why: '학생 ends in a consonant (받침), so it takes 이에요. 예요 goes after vowels.' }] },
    { id: 's-parents', level: 2, en: 'Thank you, Father and Mother!', ko: '아버지, 어머니, 감사합니다!',
      tiles: ['아버지', '어머니', '감사합니다'], gloss: ['Father', 'Mother', 'thank you'],
      words: ['father', 'mother', 'cafe:thanks'], alts: [['어머니', '아버지', '감사합니다']] },

    // ---- Level 3 ----
    { id: 's-hyung', level: 3, en: 'My older brother has a girlfriend. (said by a man)', ko: '형은 여자 친구가 있어요.',
      tiles: ['형은', '여자 친구가', '있어요'], gloss: ['older brother (topic)', 'girlfriend (subject)', 'there is / has'],
      words: ['hyung', 'girlfriend', 'day:have'],
      traps: [{ tile: '오빠는', why: 'A man calls his older brother 형. 오빠 is what a woman says.' }] },
    { id: 's-unni', level: 3, en: 'My older sister doesn’t have a boyfriend. (said by a woman)', ko: '언니는 남자 친구가 없어요.',
      tiles: ['언니는', '남자 친구가', '없어요'], gloss: ['older sister (topic)', 'boyfriend (subject)', 'there isn’t / doesn’t have'],
      words: ['unni', 'boyfriend', 'day:nothave'],
      traps: [
        { tile: '누나는', why: 'A woman calls her older sister 언니. 누나 is what a man says.' },
        { tile: '남자 친구를', why: '없어요 says that something isn’t there. That thing is the subject, so it takes 가: 남자 친구가 없어요.' },
      ] },
    { id: 's-oppa', level: 3, en: 'My older brother is tall. (said by a woman)', ko: '오빠는 키가 커요.',
      tiles: ['오빠는', '키가', '커요'], gloss: ['older brother (topic)', 'height (subject)', 'is big'], words: ['oppa', 'tall'],
      traps: [{ tile: '형은', why: 'A woman calls her older brother 오빠. 형 is what a man says.' }] },
    { id: 's-nuna', level: 3, en: 'My older sister is married. (said by a man)', ko: '누나는 결혼했어요.',
      tiles: ['누나는', '결혼했어요'], gloss: ['older sister (topic)', 'got married (is married)'], words: ['nuna', 'married'],
      traps: [
        { tile: '언니는', why: 'A man calls his older sister 누나. 언니 is what a woman says.' },
        { tile: '결혼해요', why: 'For “is married”, Korean uses the past form 결혼했어요 (“got married”). 결혼해요 means “gets married”.' },
      ] },
    { id: 's-husband', level: 3, en: 'My husband is a doctor.', ko: '남편은 의사예요.',
      tiles: ['남편은', '의사예요'], gloss: ['husband (topic)', 'is a doctor'], words: ['husband', 'doctor'],
      traps: [{ tile: '아내는', why: '아내 means “wife”. “Husband” is 남편.' }] },
    { id: 's-wife', level: 3, en: 'My wife is an office worker.', ko: '제 아내는 회사원이에요.',
      tiles: ['제', '아내는', '회사원이에요'], gloss: ['my', 'wife (topic)', 'is an office worker'], words: ['wife', 'officeworker'],
      traps: [
        { tile: '회사원예요', why: '회사원 ends in a consonant (받침), so it takes 이에요. 예요 goes after vowels.' },
        { tile: '남편은', why: '남편 means “husband”. “Wife” is 아내.' },
      ] },
    { id: 's-grandparents', level: 3, en: 'Grandma, Grandpa, where are you going?', ko: '할머니, 할아버지, 어디 가세요?',
      tiles: ['할머니', '할아버지', '어디', '가세요'], gloss: ['Grandma', 'Grandpa', 'where', 'are (you) going? (polite)'],
      words: ['grandma', 'grandpa', 'directions:where', 'day:go'], alts: [['할아버지', '할머니', '어디', '가세요']] },
  ],
});
