/**
 * Reading passages, practised in the Reading game (js/games/reading.js): a
 * short text for one topic (a diary entry, a text message, a notice, a menu…)
 * stays on screen while the learner answers questions about it. After each
 * answer the game shows the sentence that holds it, with its translation; at
 * the end, the whole text with translations and a 🔊 for every sentence.
 *
 * Diaries, messages, emails and letters use polite 해요체; a notice may use
 * 입니다 / 합니다. Numbers are in digits where a real text would have them
 * (prices and times on a menu, an ad, a notice or a timetable; subway lines and
 * exits), otherwise in Hangul (일곱 시, 열 살), so the learner maps them to the
 * digits in the answers.
 *
 * Fields: id, topic (a topic id), level (1–3), emoji,
 *         kind { ko, en } (what kind of text it is: 일기, 문자, 안내문…),
 *         title { ko, en },
 *         sentences [{ ko, en, say }] (the text, sentence by sentence or line by line;
 *                    the 🔊 reads digits with a counter in Hangul by itself (7시 → 일곱 시,
 *                    3,000원 → 삼천 원); `say` is the sentence as it's read aloud, only
 *                    where that isn't enough: 2번 출구 → 이번 출구),
 *         words (2–4 vocabulary refs, 'topic:id': the passage opens once they're learned),
 *         questions [{ q { ko, en }, options (3 × { ko, en }), answer (index of the
 *                      right option; the game shuffles them), line (0-based index of
 *                      the sentence with the answer, or a list), why (shown after answering) }].
 */
Mallang.content.registerReadings([
  // ---------- Level 1 ----------
  {
    id: 'cafe-menu',
    topic: 'cafe',
    level: 1,
    emoji: '📋',
    kind: { ko: '메뉴', en: 'A café menu board' },
    title: { ko: '말랑 카페 메뉴', en: 'The Mallang Café menu' },
    sentences: [
      { ko: '말랑 카페에 어서 오세요!', en: 'Welcome to Mallang Café!' },
      { ko: '커피는 3,000원, 라테는 3,500원이에요.', en: 'Coffee is 3,000 won, and a latte is 3,500 won.' },
      { ko: '차는 2,500원이에요.', en: 'Tea is 2,500 won.' },
      { ko: '케이크는 4,000원이에요.', en: 'Cake is 4,000 won.' },
      { ko: '죄송해요, 오늘은 쿠키가 없어요.', en: 'Sorry, no cookies today.' },
    ],
    words: ['cafe:coffee', 'cafe:latte', 'cafe:cake', 'cafe:cookie'],
    questions: [
      {
        q: { ko: '라테는 얼마예요?', en: 'How much is a latte?' },
        options: [
          { ko: '3,500원', en: '3,500 won' },
          { ko: '3,000원', en: '3,000 won' },
          { ko: '2,500원', en: '2,500 won' },
        ],
        answer: 0,
        line: 1,
        why: 'The board says 라테는 3,500원이에요: a latte is 3,500 won. 3,000원 is the coffee, and 2,500원 is the tea.',
      },
      {
        q: { ko: '오늘 뭐가 없어요?', en: 'What don’t they have today?' },
        options: [
          { ko: '쿠키', en: 'cookies' },
          { ko: '케이크', en: 'cake' },
          { ko: '차', en: 'tea' },
        ],
        answer: 0,
        line: 4,
        why: 'The last line says 오늘은 쿠키가 없어요: there are no cookies today (없어요 = there aren’t any). The cake is on the menu, at 4,000 won.',
      },
    ],
  },
  {
    id: 'day-note',
    topic: 'day',
    level: 1,
    emoji: '📝',
    kind: { ko: '메모', en: 'A note on the fridge' },
    title: { ko: '엄마에게', en: 'To Mom' },
    sentences: [
      { ko: '엄마, 저 지금 친구 집에 가요.', en: 'Mom, I’m going to my friend’s house now.' },
      { ko: '저녁은 친구 집에서 먹어요.', en: 'I’m having dinner at my friend’s.' },
      { ko: '밤 열 시에 집에 와요.', en: 'I’ll be home at ten tonight.' },
      { ko: '아, 케이크는 제가 먹었어요. 죄송해요!', en: 'Oh, and I ate the cake. Sorry!' },
    ],
    words: ['day:friend', 'day:home', 'day:evening', 'day:eat'],
    questions: [
      {
        q: { ko: '이 사람은 어디에서 저녁을 먹어요?', en: 'Where is the writer having dinner?' },
        options: [
          { ko: '친구 집에서', en: 'at a friend’s house' },
          { ko: '집에서', en: 'at home' },
          { ko: '카페에서', en: 'at a café' },
        ],
        answer: 0,
        line: 1,
        why: 'The note says 저녁은 친구 집에서 먹어요: “I’m having dinner at my friend’s house.” The writer only comes home (집에 와요) at ten.',
      },
      {
        q: { ko: '이 사람은 뭘 먹었어요?', en: 'What did the writer eat?' },
        options: [
          { ko: '케이크', en: 'the cake' },
          { ko: '저녁', en: 'dinner' },
          { ko: '빵', en: 'the bread' },
        ],
        answer: 0,
        line: 3,
        why: '케이크는 제가 먹었어요 is in the past (먹었어요, “ate”): the writer has already eaten the cake. Dinner is still to come: 저녁은 … 먹어요 is the present tense.',
      },
    ],
  },
  {
    id: 'people-intro',
    topic: 'people',
    level: 1,
    emoji: '🙋',
    kind: { ko: '자기소개', en: 'Introducing yourself' },
    title: { ko: '제 이름은 톰이에요', en: 'My name is Tom' },
    sentences: [
      { ko: '안녕하세요? 제 이름은 톰이에요.', en: 'Hello! My name is Tom.' },
      { ko: '저는 캐나다 사람이에요.', en: 'I’m Canadian.' },
      { ko: '지금은 서울에 살아요.', en: 'Now I live in Seoul.' },
      { ko: '저는 영어 선생님이에요.', en: 'I’m an English teacher.' },
      { ko: '제 가족은 캐나다에 있어요.', en: 'My family is in Canada.' },
    ],
    words: ['people:me', 'people:name', 'people:person', 'people:teacher'],
    questions: [
      {
        q: { ko: '톰 씨는 지금 어디에 살아요?', en: 'Where does Tom live now?' },
        options: [
          { ko: '서울', en: 'in Seoul' },
          { ko: '캐나다', en: 'in Canada' },
          { ko: '부산', en: 'in Busan' },
        ],
        answer: 0,
        line: 2,
        why: 'Tom is Canadian (캐나다 사람), but he says 지금은 서울에 살아요: “Now I live in Seoul.” It’s his family that is in Canada.',
      },
      {
        q: { ko: '톰 씨는 무슨 일을 해요?', en: 'What does Tom do?' },
        options: [
          { ko: '영어 선생님이에요', en: 'He’s an English teacher' },
          { ko: '한국어 선생님이에요', en: 'He’s a Korean teacher' },
          { ko: '학생이에요', en: 'He’s a student' },
        ],
        answer: 0,
        line: 3,
        why: 'Tom says 저는 영어 선생님이에요: he teaches English (영어). A Korean teacher would be 한국어 선생님.',
      },
    ],
  },
  {
    id: 'past-rainy-day',
    topic: 'past',
    level: 1,
    emoji: '🌧️',
    kind: { ko: '일기', en: 'A diary entry' },
    title: { ko: '비 오는 일요일', en: 'A rainy Sunday' },
    sentences: [
      { ko: '오늘은 비가 왔어요. 그래서 집에 있었어요.', en: 'It rained today, so I stayed at home.' },
      { ko: '아침에는 남동생하고 게임을 했어요.', en: 'In the morning I played games with my little brother.' },
      { ko: '저녁에는 비가 그쳤어요.', en: 'In the evening the rain stopped.' },
      { ko: '그래서 친구하고 카페에 갔어요.', en: 'So I went to a café with a friend.' },
      { ko: '거기에서 쿠키를 먹었어요. 정말 맛있었어요!', en: 'We had cookies there. They were really good!' },
    ],
    words: ['past:went', 'past:ate', 'past:did', 'weather:rain'],
    questions: [
      {
        q: { ko: '이 사람은 왜 집에 있었어요?', en: 'Why did the writer stay at home?' },
        options: [
          { ko: '비가 왔어요', en: 'It rained' },
          { ko: '눈이 왔어요', en: 'It snowed' },
          { ko: '아팠어요', en: 'They were ill' },
        ],
        answer: 0,
        line: 0,
        why: 'The diary starts 오늘은 비가 왔어요. 그래서 집에 있었어요: it rained, so (그래서) the writer stayed at home.',
      },
      {
        q: { ko: '이 사람은 저녁에 뭐 했어요?', en: 'What did the writer do in the evening?' },
        options: [
          { ko: '카페에 갔어요', en: 'Went to a café' },
          { ko: '게임을 했어요', en: 'Played games' },
          { ko: '집에 있었어요', en: 'Stayed at home' },
        ],
        answer: 0,
        line: [2, 3],
        why: '저녁에는 비가 그쳤어요: in the evening the rain stopped, 그래서 친구하고 카페에 갔어요: so the writer went to a café with a friend. The games were in the morning (아침에는).',
      },
    ],
  },
  {
    id: 'shopping-text',
    topic: 'shopping',
    level: 1,
    emoji: '📱',
    kind: { ko: '문자', en: 'A text message' },
    title: { ko: '여기 옷이 싸요!', en: 'The clothes here are cheap!' },
    sentences: [
      { ko: '유진 씨, 지금 뭐 해요?', en: 'Yujin, what are you up to?' },
      { ko: '저는 역 앞 가게에 있어요.', en: 'I’m at the shop in front of the station.' },
      { ko: '여기 옷이 정말 싸요!', en: 'The clothes here are really cheap!' },
      { ko: '가방도 싸요. 그런데 신발은 비싸요.', en: 'The bags are cheap too. But the shoes are expensive.' },
      { ko: '유진 씨도 오세요!', en: 'You should come too, Yujin!' },
    ],
    words: ['shopping:shop', 'shopping:clothes', 'shopping:cheap', 'shopping:expensive'],
    questions: [
      {
        q: { ko: '가게는 어디에 있어요?', en: 'Where is the shop?' },
        options: [
          { ko: '역 앞', en: 'in front of the station' },
          { ko: '역 뒤', en: 'behind the station' },
          { ko: '역 옆', en: 'next to the station' },
        ],
        answer: 0,
        line: 1,
        why: 'The message says 저는 역 앞 가게에 있어요: “I’m at the shop in front of (앞) the station.”',
      },
      {
        q: { ko: '뭐가 비싸요?', en: 'What is expensive?' },
        options: [
          { ko: '신발', en: 'the shoes' },
          { ko: '가방', en: 'the bags' },
          { ko: '옷', en: 'the clothes' },
        ],
        answer: 0,
        line: 3,
        why: '가방도 싸요. 그런데 신발은 비싸요: the bags are cheap too (도), but (그런데) the shoes are expensive. The clothes are cheap (옷이 정말 싸요).',
      },
    ],
  },

  // ---------- Level 2 ----------
  {
    id: 'day-email',
    topic: 'day',
    level: 2,
    emoji: '📧',
    kind: { ko: '이메일', en: 'An email to a friend' },
    title: { ko: '잘 지내요?', en: 'How are you?' },
    sentences: [
      { ko: '지수 씨, 잘 지내요? 저는 서울에서 잘 지내요.', en: 'Jisu, how are you? I’m doing well in Seoul.' },
      { ko: '요즘 매일 일곱 시에 일어나요.', en: 'These days I get up at seven every day.' },
      { ko: '아홉 시부터 한 시까지 학교에서 한국어를 공부해요.', en: 'From nine to one, I study Korean at school.' },
      { ko: '점심을 먹고 도서관에서 숙제를 해요.', en: 'After lunch, I do my homework in the library.' },
      { ko: '저녁에는 카페에서 일해요.', en: 'In the evening, I work at a café.' },
      { ko: '그래서 좀 바빠요. 그래도 정말 재미있어요!', en: 'So I’m a bit busy. But it’s really fun!' },
      { ko: '지수 씨도 요즘 바빠요?', en: 'Are you busy these days too, Jisu?' },
    ],
    words: ['day:getup', 'day:everyday', 'day:library', 'day:work'],
    questions: [
      {
        q: { ko: '이 사람은 몇 시에 일어나요?', en: 'What time does the writer get up?' },
        options: [
          { ko: '7시', en: '7:00' },
          { ko: '9시', en: '9:00' },
          { ko: '1시', en: '1:00' },
        ],
        answer: 0,
        line: 1,
        why: 'The email says 매일 일곱 시에 일어나요: the writer gets up at seven (일곱 = 7) every day. 아홉 시 (9:00) is when school starts.',
      },
      {
        q: { ko: '이 사람은 어디에서 숙제를 해요?', en: 'Where does the writer do their homework?' },
        options: [
          { ko: '도서관', en: 'at the library' },
          { ko: '학교', en: 'at school' },
          { ko: '카페', en: 'at a café' },
        ],
        answer: 0,
        line: 3,
        why: '점심을 먹고 도서관에서 숙제를 해요: after lunch, the homework gets done in the library. School (학교) is for the Korean lessons, and the café is where the writer works.',
      },
      {
        q: { ko: '이 사람은 왜 바빠요?', en: 'Why is the writer busy?' },
        options: [
          { ko: '공부도 하고 일도 해서', en: 'They both study and work' },
          { ko: '숙제가 너무 많아서', en: 'They have too much homework' },
          { ko: '학교가 너무 멀어서', en: 'Their school is too far away' },
        ],
        answer: 0,
        line: [2, 4, 5],
        why: 'The writer studies Korean at school (학교에서 한국어를 공부해요) and works at a café in the evening (저녁에는 카페에서 일해요): 그래서 좀 바빠요, “so I’m a bit busy”.',
      },
    ],
  },
  {
    id: 'numbers-class',
    topic: 'numbers',
    level: 2,
    emoji: '🗓️',
    kind: { ko: '시간표', en: 'A class timetable' },
    title: { ko: '한국어 교실 시간표', en: 'Korean class timetable' },
    sentences: [
      { ko: '말랑 한국어 교실은 월요일하고 토요일에 수업이 있어요.', en: 'Mallang Korean Class has lessons on Mondays and Saturdays.' },
      { ko: '월요일 수업은 회사원이 많아서 저녁 7시에 시작해요.', en: 'Lots of office workers come on Mondays, so that lesson starts at 7 p.m.' },
      { ko: '토요일 수업은 오전 10시 30분에 시작해요.', en: 'The Saturday lesson starts at 10:30 a.m.' },
      { ko: '수업 시간은 1시간 30분이에요.', en: 'Each lesson is an hour and a half long.' },
      { ko: '한 반에 학생이 8명 있어요.', en: 'There are eight students in each class.' },
      { ko: '책은 9,000원이에요.', en: 'The textbook costs 9,000 won.' },
    ],
    words: ['numbers:monday', 'numbers:saturday', 'numbers:hour', 'numbers:minute'],
    questions: [
      {
        q: { ko: '토요일 수업은 몇 시에 시작해요?', en: 'What time does the Saturday lesson start?' },
        options: [
          { ko: '10시 30분', en: '10:30' },
          { ko: '10시', en: '10:00' },
          { ko: '7시', en: '7:00' },
        ],
        answer: 0,
        line: 2,
        why: '토요일 수업은 오전 10시 30분에 시작해요: the Saturday lesson starts at 10:30 a.m. (오전 = a.m.), read 열 시 삼십 분 (or 열 시 반). 7시 is the Monday lesson.',
      },
      {
        q: { ko: '월요일 수업은 왜 저녁에 해요?', en: 'Why is the Monday lesson in the evening?' },
        options: [
          { ko: '회사원이 많아서', en: 'Many of the students work in offices' },
          { ko: '선생님이 아침에 바빠서', en: 'The teacher is busy in the mornings' },
          { ko: '아침에 교실이 없어서', en: 'There’s no classroom in the mornings' },
        ],
        answer: 0,
        line: 1,
        why: '월요일 수업은 회사원이 많아서 저녁 7시에 시작해요: many office workers (회사원) come to the Monday lesson, so it starts in the evening, after work.',
      },
      {
        q: { ko: '월요일 수업은 몇 시에 끝나요?', en: 'What time does the Monday lesson finish?' },
        options: [
          { ko: '8시 30분', en: '8:30' },
          { ko: '7시 30분', en: '7:30' },
          { ko: '9시', en: '9:00' },
        ],
        answer: 0,
        line: [1, 3],
        why: 'The Monday lesson starts at 7시, and 수업 시간은 1시간 30분이에요 (a lesson lasts an hour and a half), so it finishes at 8:30 (여덟 시 반).',
      },
    ],
  },
  {
    id: 'feelings-test',
    topic: 'feelings',
    level: 2,
    emoji: '📔',
    kind: { ko: '일기', en: 'A diary entry' },
    title: { ko: '말하기 시험', en: 'The speaking test' },
    sentences: [
      { ko: '오늘은 한국어 말하기 시험이 있었어요.', en: 'Today I had my Korean speaking test.' },
      { ko: '어젯밤에는 걱정돼서 잠을 잘 못 잤어요.', en: 'Last night I was so worried that I couldn’t sleep well.' },
      { ko: '아침에도 너무 떨렸어요.', en: 'This morning I was really nervous, too.' },
      { ko: '그런데 시험은 안 어려웠어요.', en: 'But the test wasn’t hard.' },
      { ko: '시험이 끝나고 친구하고 노래방에 갔어요.', en: 'After the test, I went to a karaoke room with a friend.' },
      { ko: '노래를 많이 불렀어요.', en: 'We sang lots of songs.' },
      { ko: '오늘은 정말 좋은 날이었어요!', en: 'It was a really good day!' },
    ],
    words: ['feelings:worried', 'feelings:nervous', 'feelings:good'],
    questions: [
      {
        q: { ko: '이 사람은 왜 잠을 잘 못 잤어요?', en: 'Why couldn’t the writer sleep well?' },
        options: [
          { ko: '걱정돼서', en: 'They were worried' },
          { ko: '노래방에 가서', en: 'They went to karaoke' },
          { ko: '숙제가 많아서', en: 'They had lots of homework' },
        ],
        answer: 0,
        line: 1,
        why: '어젯밤에는 걱정돼서 잠을 잘 못 잤어요: the writer was worried (걱정돼서, “because I was worried”) about the test. The karaoke came after the test, today.',
      },
      {
        q: { ko: '시험은 어땠어요?', en: 'How was the test?' },
        options: [
          { ko: '안 어려웠어요', en: 'It wasn’t hard' },
          { ko: '너무 어려웠어요', en: 'It was very hard' },
          { ko: '재미없었어요', en: 'It was boring' },
        ],
        answer: 0,
        line: 3,
        why: '그런데 시험은 안 어려웠어요: “But the test wasn’t hard.” 안 in front of 어려웠어요 (was hard) makes it negative.',
      },
      {
        q: { ko: '이 사람은 지금 기분이 어때요?', en: 'How does the writer feel now?' },
        options: [
          { ko: '좋아요', en: 'Good' },
          { ko: '떨려요', en: 'Nervous' },
          { ko: '걱정돼요', en: 'Worried' },
        ],
        answer: 0,
        line: [3, 6],
        why: 'The worry (걱정돼서) and the nerves (떨렸어요) were before the test. It wasn’t hard, and the writer ends with 정말 좋은 날이었어요: “it was a really good day”.',
      },
    ],
  },
  {
    id: 'weather-postcard',
    topic: 'weather',
    level: 2,
    emoji: '🏝️',
    kind: { ko: '엽서', en: 'A postcard' },
    title: { ko: '제주도에서', en: 'From Jeju Island' },
    sentences: [
      { ko: '소희 씨, 저는 지금 제주도에 있어요.', en: 'Sohee, I’m on Jeju Island right now.' },
      { ko: '여기는 벌써 봄이에요. 날씨가 정말 따뜻해요.', en: 'It’s already spring here. The weather is really warm.' },
      { ko: '어제는 비가 와서 호텔에서 쉬었어요.', en: 'Yesterday it rained, so I rested at the hotel.' },
      { ko: '오늘은 맑아요. 그래서 지금 바다에 있어요!', en: 'Today it’s sunny, so I’m at the beach now!' },
      { ko: '내일은 좀 흐려요.', en: 'Tomorrow it’ll be a bit cloudy.' },
      { ko: '그래도 산에 가요.', en: 'But I’m still going up the mountain.' },
      { ko: '서울은 아직 추워요? 보고 싶어요!', en: 'Is it still cold in Seoul? I miss you!' },
    ],
    words: ['weather:spring', 'weather:warm', 'weather:raining', 'weather:cloudy'],
    questions: [
      {
        q: { ko: '요즘 제주도 날씨는 어때요?', en: 'What’s the weather like on Jeju these days?' },
        options: [
          { ko: '따뜻해요', en: 'It’s warm' },
          { ko: '추워요', en: 'It’s cold' },
          { ko: '시원해요', en: 'It’s cool' },
        ],
        answer: 0,
        line: 1,
        why: '여기는 벌써 봄이에요. 날씨가 정말 따뜻해요: on Jeju it’s already spring, and really warm. 추워요 (cold) is the writer’s question about Seoul.',
      },
      {
        q: { ko: '이 사람은 어제 왜 호텔에서 쉬었어요?', en: 'Why did the writer rest at the hotel yesterday?' },
        options: [
          { ko: '비가 와서', en: 'It rained' },
          { ko: '흐려서', en: 'It was cloudy' },
          { ko: '추워서', en: 'It was cold' },
        ],
        answer: 0,
        line: 2,
        why: '어제는 비가 와서 호텔에서 쉬었어요: it rained yesterday (비가 와서, “because it rained”), so the writer rested at the hotel. The clouds (흐려요) are tomorrow.',
      },
      {
        q: { ko: '이 사람은 내일 뭐 해요?', en: 'What is the writer doing tomorrow?' },
        options: [
          { ko: '산에 가요', en: 'Going up the mountain' },
          { ko: '호텔에서 쉬어요', en: 'Resting at the hotel' },
          { ko: '바다에 가요', en: 'Going to the beach' },
        ],
        answer: 0,
        line: [4, 5],
        why: '내일은 좀 흐려요. 그래도 산에 가요: tomorrow will be a bit cloudy, but the writer is still (그래도, “even so”) going up the mountain.',
      },
    ],
  },
  {
    id: 'shopping-sale',
    topic: 'shopping',
    level: 2,
    emoji: '🏷️',
    kind: { ko: '광고', en: 'An ad' },
    title: { ko: '말랑 옷 가게 세일!', en: 'Sale at Mallang Clothes!' },
    sentences: [
      { ko: '말랑 옷 가게가 새로 문을 열었어요!', en: 'Mallang Clothes has just opened!' },
      { ko: '그래서 이번 주 토요일하고 일요일에 세일해요.', en: 'So this Saturday and Sunday, we’re having a sale.' },
      { ko: '티셔츠는 5,000원, 바지는 9,000원이에요.', en: 'T-shirts are 5,000 won, and trousers are 9,000 won.' },
      { ko: '모자는 모두 3,000원이에요.', en: 'All hats are 3,000 won.' },
      { ko: '토요일에는 선물도 드려요!', en: 'And on Saturday, there’s a free gift!' },
      { ko: '은행 옆에 있어요. 많이 오세요!', en: 'We’re next to the bank. Come along!' },
    ],
    words: ['shopping:tshirt', 'shopping:trousers', 'shopping:hat', 'shopping:gift'],
    questions: [
      {
        q: { ko: '바지는 얼마예요?', en: 'How much are the trousers?' },
        options: [
          { ko: '9,000원', en: '9,000 won' },
          { ko: '5,000원', en: '5,000 won' },
          { ko: '3,000원', en: '3,000 won' },
        ],
        answer: 0,
        line: 2,
        why: 'The ad says 바지는 9,000원이에요: trousers are 9,000 won. 5,000원 is the T-shirts, and 3,000원 is the hats.',
      },
      {
        q: { ko: '왜 세일해요?', en: 'Why is there a sale?' },
        options: [
          { ko: '새로 문을 열어서', en: 'The shop has just opened' },
          { ko: '여름이 끝나서', en: 'Summer is over' },
          { ko: '가게를 닫아서', en: 'The shop is closing down' },
        ],
        answer: 0,
        line: [0, 1],
        why: 'The shop 새로 문을 열었어요 (has just opened), 그래서 (so) it’s having a sale this weekend.',
      },
      {
        q: { ko: '선물을 받고 싶어요. 언제 가요?', en: 'You want the free gift. When should you go?' },
        options: [
          { ko: '토요일', en: 'on Saturday' },
          { ko: '일요일', en: 'on Sunday' },
          { ko: '월요일', en: 'on Monday' },
        ],
        answer: 0,
        line: [1, 4],
        why: 'The sale is on Saturday and Sunday, but 토요일에는 선물도 드려요: the free gift is only on Saturday.',
      },
    ],
  },
  {
    id: 'hobbies-club',
    topic: 'hobbies',
    level: 2,
    emoji: '🚲',
    kind: { ko: '포스터', en: 'A club poster' },
    title: { ko: '말랑 자전거 동아리', en: 'The Mallang Cycling Club' },
    sentences: [
      { ko: '자전거를 좋아해요? 말랑 자전거 동아리에 오세요!', en: 'Do you like cycling? Come and join the Mallang Cycling Club!' },
      { ko: '우리는 매주 토요일 아침 9시에 한강에서 만나요.', en: 'We meet by the Han River at 9 a.m. every Saturday.' },
      { ko: '오후에는 사람이 많아서 아침에 타요.', en: 'It gets crowded in the afternoon, so we ride in the morning.' },
      { ko: '두 시간쯤 자전거를 타고 같이 점심을 먹어요.', en: 'We ride for about two hours, then have lunch together.' },
      { ko: '자전거가 없어요? 괜찮아요. 빌려 드려요!', en: 'No bike? No problem: we’ll lend you one!' },
      { ko: '비가 오면 자전거를 안 타요.', en: 'If it rains, there’s no ride.' },
    ],
    words: ['hobbies:bike', 'numbers:saturday', 'day:meet', 'weather:raining'],
    questions: [
      {
        q: { ko: '동아리는 언제 만나요?', en: 'When does the club meet?' },
        options: [
          { ko: '토요일 아침', en: 'Saturday morning' },
          { ko: '토요일 오후', en: 'Saturday afternoon' },
          { ko: '일요일 아침', en: 'Sunday morning' },
        ],
        answer: 0,
        line: 1,
        why: '매주 토요일 아침 9시에 한강에서 만나요: they meet every Saturday at 9 in the morning. The afternoon (오후) is when it gets crowded.',
      },
      {
        q: { ko: '왜 아침에 자전거를 타요?', en: 'Why do they ride in the morning?' },
        options: [
          { ko: '오후에는 사람이 많아서', en: 'It’s crowded in the afternoon' },
          { ko: '오후에는 더워서', en: 'It’s hot in the afternoon' },
          { ko: '점심을 같이 먹어서', en: 'They have lunch together' },
        ],
        answer: 0,
        line: 2,
        why: '오후에는 사람이 많아서 아침에 타요: there are a lot of people (사람이 많아서) in the afternoon, so they ride in the morning. Lunch comes after the ride.',
      },
      {
        q: { ko: '토요일에 비가 와요. 동아리는 어떻게 해요?', en: 'It’s raining on Saturday. What does the club do?' },
        options: [
          { ko: '자전거를 안 타요', en: 'There’s no ride' },
          { ko: '오후에 타요', en: 'They ride in the afternoon' },
          { ko: '두 시간 타요', en: 'They ride for two hours' },
        ],
        answer: 0,
        line: 5,
        why: '비가 오면 자전거를 안 타요: if (-(으)면) it rains, they don’t ride.',
      },
    ],
  },

  // ---------- Level 3 ----------
  {
    id: 'cafe-notice',
    topic: 'cafe',
    level: 3,
    emoji: '📌',
    kind: { ko: '안내문', en: 'A notice' },
    title: { ko: '말랑 카페 안내', en: 'A notice from Mallang Café' },
    sentences: [
      { ko: '안녕하세요. 말랑 카페입니다.', en: 'Hello, this is Mallang Café.' },
      { ko: '이번 주 수요일은 카페를 청소해야 해서 쉽니다.', en: 'We’re closed this Wednesday, because we have to clean the café.' },
      { ko: '목요일부터는 오전 8시에 문을 엽니다.', en: 'From Thursday, we open at 8 a.m.' },
      { ko: '새 메뉴도 나왔습니다.', en: 'We also have new things on the menu.' },
      { ko: '딸기 라테는 5,000원이고, 딸기 케이크는 6,500원입니다.', en: 'A strawberry latte is 5,000 won, and strawberry cake is 6,500 won.' },
      { ko: '컵을 가져오시면 음료를 500원 할인해 드립니다.', en: 'If you bring your own cup, you get 500 won off your drink.' },
      { ko: '와이파이 비밀번호는 영수증에 있습니다.', en: 'The Wi-Fi password is on your receipt.' },
      { ko: '감사합니다.', en: 'Thank you.' },
    ],
    words: ['cafe:strawberry', 'cafe:latte', 'cafe:password', 'shopping:discount'],
    questions: [
      {
        q: { ko: '카페는 수요일에 왜 쉬어요?', en: 'Why is the café closed on Wednesday?' },
        options: [
          { ko: '청소해야 해서', en: 'They have to clean' },
          { ko: '사장님이 휴가를 가서', en: 'The owner is on holiday' },
          { ko: '새 메뉴를 만들어서', en: 'They’re making the new menu' },
        ],
        answer: 0,
        line: 1,
        why: '이번 주 수요일은 카페를 청소해야 해서 쉽니다: they have to clean the café (-아/어야 해서, “because we have to”), so it’s closed (쉽니다) on Wednesday.',
      },
      {
        q: { ko: '딸기 케이크는 얼마예요?', en: 'How much is the strawberry cake?' },
        options: [
          { ko: '6,500원', en: '6,500 won' },
          { ko: '5,000원', en: '5,000 won' },
          { ko: '6,000원', en: '6,000 won' },
        ],
        answer: 0,
        line: 4,
        why: '딸기 케이크는 6,500원입니다: the strawberry cake is 6,500 won. 5,000원 is the strawberry latte.',
      },
      {
        q: { ko: '컵을 가지고 가서 딸기 라테를 사요. 얼마예요?', en: 'You bring your own cup and buy a strawberry latte. How much is it?' },
        options: [
          { ko: '4,500원', en: '4,500 won' },
          { ko: '5,000원', en: '5,000 won' },
          { ko: '5,500원', en: '5,500 won' },
        ],
        answer: 0,
        line: [4, 5],
        why: 'A strawberry latte is 5,000원, and 컵을 가져오시면 음료를 500원 할인해 드립니다: with your own cup, drinks are 500 won off. 5,000 − 500 = 4,500 won.',
      },
    ],
  },
  {
    id: 'people-homestay',
    topic: 'people',
    level: 3,
    emoji: '🏠',
    kind: { ko: '이메일', en: 'An email' },
    title: { ko: '우리 가족을 소개할게요', en: 'Meet your homestay family' },
    sentences: [
      { ko: '리사 씨, 안녕하세요? 홈스테이 가족 김수진이에요.', en: 'Hello, Lisa! This is Kim Sujin, from your homestay family.' },
      { ko: '우리 가족을 소개할게요.', en: 'Let me introduce our family.' },
      { ko: '남편은 회사원이고, 저는 선생님이에요.', en: 'My husband is an office worker, and I’m a teacher.' },
      { ko: '아들 준우는 열 살이고 축구를 정말 좋아해요.', en: 'Our son Junwoo is ten, and he loves football.' },
      { ko: '딸 서아는 일곱 살인데, 그림을 잘 그려요.', en: 'Our daughter Seoa is seven, and she’s good at drawing.' },
      { ko: '그리고 할머니도 우리하고 같이 사세요.', en: 'And Grandma lives with us, too.' },
      { ko: '토요일에 저는 일이 있어서 공항에 못 가요.', en: 'I have work on Saturday, so I can’t come to the airport.' },
      { ko: '그래서 남편하고 준우가 공항에 갈 거예요.', en: 'So my husband and Junwoo will come to the airport.' },
      { ko: '빨리 만나고 싶어요!', en: 'We can’t wait to meet you!' },
    ],
    words: ['people:husband', 'people:grandma', 'people:officeworker', 'numbers:age'],
    questions: [
      {
        q: { ko: '서아는 몇 살이에요?', en: 'How old is Seoa?' },
        options: [
          { ko: '7살', en: '7 years old' },
          { ko: '10살', en: '10 years old' },
          { ko: '8살', en: '8 years old' },
        ],
        answer: 0,
        line: 4,
        why: '딸 서아는 일곱 살인데…: the daughter, Seoa, is seven (일곱 = 7). 열 살 (10) is her brother Junwoo.',
      },
      {
        q: { ko: '수진 씨는 왜 공항에 못 가요?', en: 'Why can’t Sujin go to the airport?' },
        options: [
          { ko: '일이 있어서', en: 'She has work' },
          { ko: '아이가 아파서', en: 'One of the children is ill' },
          { ko: '차가 없어서', en: 'She doesn’t have a car' },
        ],
        answer: 0,
        line: 6,
        why: '토요일에 저는 일이 있어서 공항에 못 가요: Sujin has work on Saturday (일이 있어서), so she can’t go. Her husband and Junwoo are going instead.',
      },
      {
        q: { ko: '지금 이 집에는 모두 몇 명이 살아요?', en: 'How many people live in the house now?' },
        options: [
          { ko: '5명', en: '5 people' },
          { ko: '4명', en: '4 people' },
          { ko: '6명', en: '6 people' },
        ],
        answer: 0,
        line: [2, 3, 4, 5],
        why: 'Sujin (저), her husband (남편), their son Junwoo, their daughter Seoa and Grandma (할머니도 우리하고 같이 사세요): five people. Lisa isn’t living there yet (지금 = now): she’ll make six once she arrives.',
      },
    ],
  },
  {
    id: 'directions-home',
    topic: 'directions',
    level: 3,
    emoji: '🗺️',
    kind: { ko: '문자', en: 'A text message' },
    title: { ko: '우리 집에 오는 길', en: 'How to get to my place' },
    sentences: [
      { ko: '수빈 씨, 토요일에 우리 집에 올 때 지하철을 타고 오세요.', en: 'Subin, when you come over on Saturday, come by subway.' },
      { ko: '4호선을 타고 혜화역에서 내리세요.', en: 'Take Line 4 and get off at Hyehwa Station.', say: '사호선을 타고 혜화역에서 내리세요.' },
      { ko: '2번 출구로 나와서 똑바로 걸어오세요.', en: 'Come out of Exit 2 and walk straight ahead.', say: '이번 출구로 나와서 똑바로 걸어오세요.' },
      { ko: '사거리에서 왼쪽으로 도세요.', en: 'Turn left at the crossroads.' },
      { ko: '조금 걸으면 오른쪽에 은행이 있어요.', en: 'A little further on, there’s a bank on your right.' },
      { ko: '우리 집은 은행 바로 뒤에 있어요.', en: 'My place is right behind the bank.' },
      { ko: '역에서 걸어서 십 분쯤 걸려요.', en: 'It’s about a ten-minute walk from the station.' },
      { ko: '가까우니까 택시는 안 타도 돼요.', en: 'It’s close, so there’s no need for a taxi.' },
      { ko: '길을 모르면 전화하세요!', en: 'If you get lost, call me!' },
    ],
    words: ['directions:ride', 'directions:getoff', 'directions:exit', 'directions:crossroads'],
    questions: [
      {
        q: { ko: '수빈 씨는 몇 번 출구로 나가요?', en: 'Which exit does Subin take?' },
        options: [
          { ko: '2번 출구', en: 'Exit 2' },
          { ko: '4번 출구', en: 'Exit 4' },
          { ko: '10번 출구', en: 'Exit 10' },
        ],
        answer: 0,
        line: 2,
        why: '2번 출구로 나와서…: come out of Exit 2. 4 is the subway line (4호선), and 십 분 (10 minutes) is the walk.',
      },
      {
        q: { ko: '사거리에서 어느 쪽으로 가요?', en: 'Which way does Subin go at the crossroads?' },
        options: [
          { ko: '왼쪽', en: 'left' },
          { ko: '오른쪽', en: 'right' },
          { ko: '똑바로', en: 'straight on' },
        ],
        answer: 0,
        line: 3,
        why: '사거리에서 왼쪽으로 도세요: turn left (왼쪽) at the crossroads. 오른쪽 (right) is the side of the road the bank is on, after the turn.',
      },
      {
        q: { ko: '왜 택시를 안 타도 돼요?', en: 'Why doesn’t Subin need a taxi?' },
        options: [
          { ko: '역에서 가까워서', en: 'It’s close to the station' },
          { ko: '택시가 비싸서', en: 'Taxis are expensive' },
          { ko: '길이 막혀서', en: 'The traffic is bad' },
        ],
        answer: 0,
        line: [6, 7],
        why: '역에서 걸어서 십 분쯤 걸려요 (about ten minutes on foot), and 가까우니까 택시는 안 타도 돼요: it’s close, so (-(으)니까) there’s no need to take a taxi.',
      },
    ],
  },
  {
    id: 'past-concert',
    topic: 'past',
    level: 3,
    emoji: '🎤',
    kind: { ko: '블로그', en: 'A blog post' },
    title: { ko: '어제 콘서트에 갔어요', en: 'I went to a concert yesterday' },
    sentences: [
      { ko: '어제 친구하고 콘서트에 갔어요.', en: 'Yesterday I went to a concert with a friend.' },
      { ko: '콘서트는 저녁 일곱 시에 시작했어요.', en: 'The concert started at seven in the evening.' },
      { ko: '그런데 우리는 티셔츠를 사고 싶어서 다섯 시에 갔어요.', en: 'But we wanted to buy T-shirts, so we got there at five.' },
      { ko: '사람이 정말 많았어요.', en: 'There were so many people.' },
      { ko: '가수가 노래를 부를 때 우리도 같이 불렀어요.', en: 'When the singer sang, we sang along.' },
      { ko: '너무 신나서 춤도 췄어요.', en: 'It was so exciting that we even danced.' },
      { ko: '콘서트가 끝난 후에 치킨을 먹었어요.', en: 'After the concert, we had fried chicken.' },
      { ko: '정말 행복한 하루였어요!', en: 'It was a really happy day!' },
    ],
    words: ['past:went', 'past:ate', 'hobbies:concert', 'feelings:excited'],
    questions: [
      {
        q: { ko: '콘서트가 시작하기 몇 시간 전에 갔어요?', en: 'How long before the concert started did they get there?' },
        options: [
          { ko: '2시간 전', en: '2 hours before' },
          { ko: '5시간 전', en: '5 hours before' },
          { ko: '7시간 전', en: '7 hours before' },
        ],
        answer: 0,
        line: [1, 2],
        why: 'The concert started at 일곱 시 (7:00), and they got there at 다섯 시 (5:00): two hours early.',
      },
      {
        q: { ko: '왜 다섯 시에 갔어요?', en: 'Why did they go at five?' },
        options: [
          { ko: '티셔츠를 사고 싶어서', en: 'They wanted to buy T-shirts' },
          { ko: '사람이 많아서', en: 'There were lots of people' },
          { ko: '치킨을 먹고 싶어서', en: 'They wanted to eat chicken' },
        ],
        answer: 0,
        line: 2,
        why: '우리는 티셔츠를 사고 싶어서 다섯 시에 갔어요: they wanted to buy T-shirts (-고 싶어서, “because we wanted to”), so they went early. 사람이 정말 많았어요 is what they found when they got there, not the reason, and the chicken came after the concert.',
      },
      {
        q: { ko: '콘서트가 끝난 후에 뭐 했어요?', en: 'What did they do after the concert?' },
        options: [
          { ko: '치킨을 먹었어요', en: 'Had fried chicken' },
          { ko: '티셔츠를 샀어요', en: 'Bought T-shirts' },
          { ko: '춤을 췄어요', en: 'Danced' },
        ],
        answer: 0,
        line: 6,
        why: '콘서트가 끝난 후에 치킨을 먹었어요: after (-(으)ㄴ 후에) the concert, they had fried chicken. The T-shirts were before it, and the dancing was during it.',
      },
    ],
  },
  {
    id: 'hobbies-holidays',
    topic: 'hobbies',
    level: 3,
    emoji: '⛺',
    kind: { ko: '편지', en: 'A letter to a pen pal' },
    title: { ko: '방학 계획', en: 'Holiday plans' },
    sentences: [
      { ko: '소피 씨, 안녕하세요? 다음 주부터 방학이에요!', en: 'Hello, Sophie! My school holidays start next week!' },
      { ko: '이번 방학에는 계획이 많아요.', en: 'I have lots of plans for these holidays.' },
      { ko: '먼저 수영을 배우고 싶어요.', en: 'First, I want to learn to swim.' },
      { ko: '오후에는 아르바이트를 하니까 아침에 수영장에 갈 거예요.', en: 'I have a part-time job in the afternoons, so I’ll go to the pool in the mornings.' },
      { ko: '그리고 방학이 끝나기 전에 가족하고 캠핑을 갈 거예요.', en: 'And before the holidays end, I’m going camping with my family.' },
      { ko: '캠핑장은 산 옆에 있어요.', en: 'The campsite is next to a mountain.' },
      { ko: '날씨가 좋으면 등산을 할 거예요.', en: 'If the weather is nice, we’ll go hiking.' },
      { ko: '비가 오면 텐트에서 보드게임을 할 거예요.', en: 'If it rains, we’ll play board games in the tent.' },
      { ko: '소피 씨는 방학에 뭐 할 거예요? 답장 기다릴게요!', en: 'What are you doing in your holidays? I’ll be waiting for your reply!' },
    ],
    words: ['hobbies:vacation', 'hobbies:wanttolearn', 'hobbies:camping', 'hobbies:hiking'],
    questions: [
      {
        q: { ko: '이 사람은 왜 아침에 수영장에 갈 거예요?', en: 'Why will the writer go to the pool in the mornings?' },
        options: [
          { ko: '오후에 아르바이트를 해서', en: 'They work part-time in the afternoons' },
          { ko: '아침에 사람이 없어서', en: 'Nobody is there in the mornings' },
          { ko: '오후에 캠핑을 가서', en: 'They go camping in the afternoons' },
        ],
        answer: 0,
        line: 3,
        why: '오후에는 아르바이트를 하니까 아침에 수영장에 갈 거예요: the writer has a part-time job in the afternoons (-(으)니까, “since”), so the swimming has to be in the mornings.',
      },
      {
        q: { ko: '비가 오면 캠핑장에서 뭐 할 거예요?', en: 'What will they do at the campsite if it rains?' },
        options: [
          { ko: '보드게임', en: 'Play board games' },
          { ko: '등산', en: 'Go hiking' },
          { ko: '수영', en: 'Go swimming' },
        ],
        answer: 0,
        line: [6, 7],
        why: '비가 오면 텐트에서 보드게임을 할 거예요: if it rains, they’ll play board games in the tent. Hiking (등산) is for when the weather is nice (날씨가 좋으면).',
      },
      {
        q: { ko: '이 사람은 언제 캠핑을 가요?', en: 'When is the writer going camping?' },
        options: [
          { ko: '방학이 끝나기 전에', en: 'Before the holidays end' },
          { ko: '방학이 끝난 후에', en: 'After the holidays end' },
          { ko: '방학 전에', en: 'Before the holidays start' },
        ],
        answer: 0,
        line: 4,
        why: '방학이 끝나기 전에 가족하고 캠핑을 갈 거예요: before the holidays end (-기 전에, “before”), so during the holidays, not after them (끝난 후에).',
      },
    ],
  },
]);
