/**
 * Topic: 쇼핑 · Shopping — clothes, colours, prices and paying.
 * Prices are written in Hangul (삼만 원) and use the numbers topic's words.
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'shopping',
  order: 5,
  emoji: '🛍️',
  color: 'lilac',
  title: { ko: '쇼핑', en: 'Shopping' },
  description: { ko: '옷 사기, 가격 묻기', en: 'Buy clothes, ask for prices' },

  notes: [
    {
      title: { ko: '있어요? / 없어요', en: 'Do you have…?' },
      text: 'Name what you want and ask **있어요?** (“Do you have…?”). The answer is **있어요** (we have it) or **없어요** (we don’t). Most colour words end in **색** (colour): **빨간색** (red), **파란색** (blue), **검은색** (black).',
      examples: [
        { ko: '빨간색 신발 있어요?', en: 'Do you have red shoes?' },
        { ko: '이거 검은색으로 있어요?', en: 'Do you have this in black?' },
        { ko: '죄송해요, 없어요.', en: 'Sorry, we don’t.' },
      ],
    },
    {
      title: { ko: '얼마예요?', en: 'Asking the price' },
      text: 'Point and ask **얼마예요?** (“How much is it?”). Prices use Sino-Korean numbers + **원**, grouped by **만** (10,000): 35,000 won is **삼만 오천 원**.',
      examples: [
        { ko: '이 가방 얼마예요?', en: 'How much is this bag?' },
        { ko: '삼만 오천 원이에요.', en: 'It’s 35,000 won.' },
        { ko: '티셔츠는 만 이천 원이에요.', en: 'The T-shirt is 12,000 won.' },
      ],
    },
    {
      title: { ko: '입어 봐도 돼요?', en: 'Trying things on' },
      text: 'The 아/어 form of a verb + **보다** means “try (doing)”: **입어 봐요** = try it on. Add **-도 돼요?** (“Is it okay if…?”) to ask: **입어 봐도 돼요?** Clothes use **입다**, but shoes use **신다** and hats use **쓰다**.',
      examples: [
        { ko: '이거 입어 봐도 돼요?', en: 'Can I try this on?' },
        { ko: '이 신발 신어 봐도 돼요?', en: 'Can I try these shoes on?' },
        { ko: '네, 입어 보세요.', en: 'Sure, go ahead and try it on.' },
      ],
    },
    {
      title: { ko: '(으)로 할게요', en: 'Choosing and paying' },
      text: 'Say what you choose with **(으)로 할게요** (“I’ll go with…”): **이걸로 할게요** = I’ll take this one (이걸로 is short for 이것으로). It also says how you pay. Use **으로** after a consonant (현금으로) and **로** after a vowel or ㄹ (카드로, 색깔로).',
      examples: [
        { ko: '이걸로 할게요.', en: 'I’ll take this one.' },
        { ko: '카드로 할게요.', en: 'I’ll pay by card.' },
        { ko: '현금으로 할게요.', en: 'I’ll pay in cash.' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'clothes', ko: '옷', en: 'clothes', level: 1, pos: 'noun', emoji: '👗', rom: 'ot', pron: '옫',
      note: 'On its own, the ㅅ sounds like a quiet t: [옫]. Before a vowel it comes back: 옷이 [오시].',
      example: { ko: '새 옷을 샀어요!', en: 'I bought new clothes!' } },
    { id: 'shoes', ko: '신발', en: 'shoes', level: 1, pos: 'noun', emoji: '👟', rom: 'sinbal',
      note: 'You don’t 입다 shoes: you 신다 them. 신발을 신어요 = I put on my shoes.',
      example: { ko: '신발이 예뻐요.', en: 'Your shoes are pretty.' } },
    { id: 'bag', ko: '가방', en: 'bag', level: 1, pos: 'noun', emoji: '👜', rom: 'gabang',
      note: 'A bag you carry, like a handbag or backpack. The bag you get at the checkout is 봉투.',
      example: { ko: '이 가방 얼마예요?', en: 'How much is this bag?' } },
    { id: 'money', ko: '돈', en: 'money', level: 1, pos: 'noun', emoji: '👛', rom: 'don',
      example: { ko: '돈 좀 있어요?', en: 'Have you got any money?' } },
    { id: 'buy', ko: '사요', en: 'buy', level: 1, pos: 'verb', emoji: '🛒', rom: 'sayo', dict: '사다',
      note: '사다 → 사 + 아요 → 사요 (the two ㅏ merge). Don’t mix it up with 싸요 (cheap), which has a tense ㅆ.',
      example: { ko: '뭐 사요?', en: 'What are you buying?' } },
    { id: 'cheap', ko: '싸요', en: "it's cheap", level: 1, pos: 'adjective', emoji: '📉', rom: 'ssayo', dict: '싸다',
      note: 'ㅆ is tense: say it tight, with no puff of air. 싸요 = cheap, but 사요 = buy.',
      example: { ko: '이 가게는 옷이 싸요.', en: 'The clothes in this shop are cheap.' } },
    { id: 'expensive', ko: '비싸요', en: "it's expensive", level: 1, pos: 'adjective', emoji: '💎', rom: 'bissayo', dict: '비싸다',
      note: 'The opposite is 싸요 (cheap). Too pricey? 너무 비싸요!',
      example: { ko: '이 가방 너무 비싸요.', en: 'This bag is too expensive.' } },
    { id: 'shop', ko: '가게', en: 'shop / store', level: 1, pos: 'noun', emoji: '🏪', rom: 'gage',
      note: 'A shop or small store. A big supermarket is 마트.',
      example: { ko: '가게에 가요.', en: 'I’m going to the shop.' } },
    { id: 'that', ko: '저거', en: 'that (thing over there)', level: 1, pos: 'pronoun', emoji: '👈', rom: 'jeogeo', accept: ['저것'],
      note: '이거 = this (near me), 그거 = that (near you), 저거 = that (over there, away from us both).',
      example: { ko: '저거 뭐예요?', en: 'What’s that?' } },

    // ---- Level 2 ----
    { id: 'card', ko: '카드', en: 'card (bank card)', level: 2, pos: 'noun', emoji: '💳', rom: 'kadeu',
      note: 'Cards are taken almost everywhere in Korea. 카드 돼요? = Can I pay by card?',
      example: { ko: '카드로 할게요.', en: 'I’ll pay by card.' } },
    { id: 'cash', ko: '현금', en: 'cash', level: 2, pos: 'noun', emoji: '💵', rom: 'hyeongeum', avoid: ['money'],
      note: '현금 ends in a consonant, so “in cash” is 현금으로: 현금으로 할게요.',
      example: { ko: '현금 있어요?', en: 'Do you have cash?' } },
    { id: 'hat', ko: '모자', en: 'hat / cap', level: 2, pos: 'noun', emoji: '🧢', rom: 'moja',
      note: 'You don’t 입다 a hat: you 쓰다 it. 모자를 써요 = I put on a hat.',
      example: { ko: '모자가 잘 어울려요.', en: 'The hat really suits you.' } },
    { id: 'tshirt', ko: '티셔츠', en: 'T-shirt', level: 2, pos: 'noun', emoji: '👕', rom: 'tisyeocheu', enAlt: ['tee', 'tee shirt'],
      example: { ko: '이 티셔츠 얼마예요?', en: 'How much is this T-shirt?' } },
    { id: 'trousers', ko: '바지', en: 'trousers / pants', level: 2, pos: 'noun', emoji: '👖', rom: 'baji',
      note: '청바지 = jeans (청 = blue).',
      example: { ko: '바지가 길어요.', en: 'The trousers are long.' } },
    { id: 'wear', ko: '입어요', en: 'wear / put on (clothes)', level: 2, pos: 'verb', emoji: '🧥', rom: 'ibeoyo', pron: '이버요',
      dict: '입다', enAlt: ['wear clothes'],
      note: '입다 is for clothes; shoes use 신다 and hats use 쓰다. For what you have on right now, Korean often uses the past: 청바지를 입었어요 = I’m wearing jeans (I’ve put them on). You’ll also hear 입고 있어요.',
      example: { ko: '내일 뭐 입어요?', en: 'What are you wearing tomorrow?' } },
    { id: 'big', ko: '커요', en: "it's big", level: 2, pos: 'adjective', emoji: '🐘', rom: 'keoyo', dict: '크다',
      note: '크다 → 커요: the ㅡ drops before 어요.',
      example: { ko: '이 신발은 좀 커요.', en: 'These shoes are a bit big.' } },
    { id: 'small', ko: '작아요', en: "it's small", level: 2, pos: 'adjective', emoji: '🐭', rom: 'jagayo', pron: '자가요',
      dict: '작다',
      note: 'The ㄱ slides into the next syllable: [자가요]. The opposite is 커요.',
      example: { ko: '이 가방은 좀 작아요.', en: 'This bag is a bit small.' } },
    { id: 'gift', ko: '선물', en: 'gift / present', level: 2, pos: 'noun', emoji: '🎁', rom: 'seonmul',
      note: '생일 선물 = birthday present.',
      example: { ko: '친구 생일 선물이에요.', en: 'It’s a birthday present for my friend.' } },
    { id: 'red', ko: '빨간색', en: 'red', level: 2, pos: 'noun', emoji: '🔴', rom: 'ppalgansaek', accept: ['빨강'],
      note: '빨간 (red) + 색 (colour). Before a noun you can also say just 빨간: 빨간 가방 = a red bag.',
      example: { ko: '빨간색 좋아해요?', en: 'Do you like red?' } },

    // ---- Level 3 ----
    { id: 'discountplease', ko: '깎아 주세요', en: 'please give me a discount', level: 3, pos: 'phrase', emoji: '🤏',
      rom: 'kkakka juseyo', pron: '까까 주세요', dict: '깎다', enAlt: ['give me a discount', 'discount please', 'a discount please'],
      note: 'Literally “please cut (the price)”. Haggling like this is normal at markets, but not in big stores.',
      example: { ko: '두 개 살게요. 좀 깎아 주세요.', en: 'I’ll buy two. Could you knock a bit off?' } },
    { id: 'takethis', ko: '이걸로 할게요', en: "I'll take this one", level: 3, pos: 'phrase', emoji: '🙆',
      rom: 'igeollo halgeyo', pron: '이걸로 할께요', enAlt: ['take this one', 'take this', "I'll take this", "I'll have this one"],
      note: '이걸로 is the spoken short form of 이것으로 (this + (으)로). (으)로 할게요 means “I’ll go with…”: 카드로 할게요 = I’ll pay by card.',
      example: { ko: '이 가방 예뻐요. 이걸로 할게요.', en: 'This bag is pretty. I’ll take this one.' } },
    { id: 'tryon', ko: '입어 봐도 돼요?', en: 'can I try it on?', level: 3, pos: 'phrase', emoji: '🪞',
      rom: 'ibeo bwado dwaeyo', pron: '이버 봐도 돼요', enAlt: ['try it on', 'try on', 'can I try this on', 'may I try it on'],
      note: '입어 봐요 = try it on, and -도 돼요? = is it okay if…? For shoes, ask 신어 봐도 돼요?',
      example: { ko: '이 바지 입어 봐도 돼요?', en: 'Can I try these trousers on?' } },
    { id: 'receipt', ko: '영수증', en: 'receipt', level: 3, pos: 'noun', emoji: '🧾', rom: 'yeongsujeung',
      note: 'At the till you’ll hear 영수증 드릴까요? (Would you like the receipt?). Answer 네, 주세요 or 괜찮아요 (no, thanks).',
      example: { ko: '영수증 주세요.', en: 'The receipt, please.' } },
    { id: 'plasticbag', ko: '봉투', en: 'plastic bag / envelope', level: 3, pos: 'noun', emoji: '🛍️', rom: 'bongtu',
      enAlt: ['bag', 'shopping bag', 'carrier bag'],
      note: 'At the checkout: 봉투 필요하세요? = Do you need a bag? Bags often cost a little extra in Korea.',
      example: { ko: '봉투 하나 주세요.', en: 'One bag, please.' } },
    { id: 'discount', ko: '할인', en: 'discount', level: 3, pos: 'noun', emoji: '🏷️', rom: 'harin', pron: '하린',
      enAlt: ['sale'],
      note: 'The ㄹ slides into the next syllable: [하린]. 할인해요 = there’s a discount / it’s on sale.',
      example: { ko: '학생 할인 있어요?', en: 'Is there a student discount?' } },
    { id: 'colour', ko: '색깔', en: 'colour', level: 3, pos: 'noun', emoji: '🎨', rom: 'saek-kkal',
      note: '색깔 and 색 both mean colour, and most colour names end in 색: 빨간색, 파란색, 검은색.',
      example: { ko: '무슨 색깔 좋아해요?', en: 'What colour do you like?' } },
    { id: 'blue', ko: '파란색', en: 'blue', level: 3, pos: 'noun', emoji: '🔵', rom: 'paransaek', accept: ['파랑'],
      note: '파란 (blue) + 색 (colour). Before a noun you can also say 파란: 파란 모자 = a blue hat.',
      example: { ko: '파란색 좋아해요.', en: 'I like blue.' } },
    { id: 'black', ko: '검은색', en: 'black', level: 3, pos: 'noun', emoji: '⚫', rom: 'geomeunsaek', pron: '거믄색',
      accept: ['검정'],
      note: 'The ㅁ slides into the next syllable: [거믄색]. You’ll also hear 검정 (black).',
      example: { ko: '검은색 신발을 샀어요.', en: 'I bought black shoes.' } },
    { id: 'justlooking', ko: '둘러볼게요', en: "I'm just looking", level: 3, pos: 'phrase', emoji: '🧐',
      rom: 'dulleobolgeyo', pron: '둘러볼께요', enAlt: ['just looking', 'just browsing', "I'll look around", 'look around'],
      note: '둘러보다 = look around. When staff ask 뭐 찾으세요? (What are you looking for?), say 그냥 둘러볼게요.',
      example: { ko: '그냥 좀 둘러볼게요.', en: 'I’m just looking around.' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-cheap', en: 'The bag is expensive. The shoes are cheap.', ko: '가방은 비싸요. 신발은 싸요.',
      tiles: ['가방은', '비싸요', '신발은', '싸요'], gloss: ['the bag (topic)', 'is expensive', 'the shoes (topic)', 'are cheap'],
      words: ['bag', 'expensive', 'shoes', 'cheap'], alts: [['신발은', '싸요', '가방은', '비싸요']],
      traps: [{ tile: '사요', why: '사요 (plain ㅅ) means “buy”. “It’s cheap” is 싸요, with the tense ㅆ.' }] },
    { id: 's-buyclothes', en: 'I buy clothes at the shop.', ko: '가게에서 옷을 사요.',
      tiles: ['가게에서', '옷을', '사요'], gloss: ['at the shop', 'clothes (object)', 'buy'], words: ['shop', 'clothes', 'buy'],
      alts: [['옷을', '가게에서', '사요']],
      traps: [
        { tile: '가게에', why: 'Buying is something you do there, so the place takes 에서: 가게에서 사요.' },
        { tile: '싸요', why: '싸요 (tense ㅆ) means “it’s cheap”. “Buy” is 사요, with a plain ㅅ.' },
      ] },
    { id: 's-nomoney', en: "I don't have any money.", ko: '돈이 없어요.',
      tiles: ['돈이', '없어요'], gloss: ['money (subject)', "there isn't"], words: ['money', 'day:nothave'],
      traps: [{ tile: '돈을', why: '없어요 says that something isn’t there. That thing is the subject, so it takes 이: 돈이 없어요.' }] },

    // ---- Level 2 ----
    { id: 's-that', level: 2, en: 'How much is that?', ko: '저거 얼마예요?',
      tiles: ['저거', '얼마예요'], gloss: ['that (over there)', 'how much is it?'], words: ['that', 'cafe:howmuch'],
      traps: [{ tile: '이거', why: '이거 means “this” (near the speaker). For “that” over there, use 저거.' }] },
    { id: 's-red', level: 2, en: "I'm wearing a red T-shirt tomorrow.", ko: '내일 빨간색 티셔츠를 입어요.',
      tiles: ['내일', '빨간색', '티셔츠를', '입어요'], gloss: ['tomorrow', 'red', 'T-shirt (object)', 'wear'],
      words: ['day:tomorrow', 'red', 'tshirt', 'wear'], alts: [['빨간색', '티셔츠를', '내일', '입어요']],
      traps: [{ tile: '신어요', why: '신어요 (신다) is for shoes and socks. For clothes like a T-shirt, use 입어요.' }] },
    { id: 's-small', level: 2, en: 'The hat is a bit small.', ko: '모자가 좀 작아요.',
      tiles: ['모자가', '좀', '작아요'], gloss: ['hat (subject)', 'a bit', 'is small'], words: ['hat', 'small'],
      traps: [{ tile: '커요', why: '커요 means “it’s big”. “Small” is 작아요.' }] },
    { id: 's-gift', level: 2, en: "I'm buying a present for my friend.", ko: '친구 선물을 사요.',
      tiles: ['친구', '선물을', '사요'], gloss: ['friend', 'present (object)', 'buy'], words: ['day:friend', 'gift', 'buy'],
      traps: [{ tile: '싸요', why: '싸요 (tense ㅆ) means “it’s cheap”. “Buy” is 사요, with a plain ㅅ.' }] },

    // ---- Level 3 ----
    { id: 's-blackbig', level: 3, en: 'The black trousers are a bit big.', ko: '검은색 바지가 좀 커요.',
      tiles: ['검은색', '바지가', '좀', '커요'], gloss: ['black', 'trousers (subject)', 'a bit', 'are big'],
      words: ['black', 'trousers', 'big'],
      traps: [{ tile: '작아요', why: '작아요 means “it’s small”. “Big” is 커요.' }] },
    { id: 's-blue', level: 3, en: 'Do you have blue shoes?', ko: '파란색 신발 있어요?',
      tiles: ['파란색', '신발', '있어요'], gloss: ['blue', 'shoes', 'do you have?'], words: ['blue', 'shoes', 'day:have'],
      traps: [{ tile: '빨간색', why: '빨간색 is red. Blue is 파란색.' }] },
    { id: 's-tryon', level: 3, en: 'Can I try this on?', ko: '이거 입어 봐도 돼요?',
      tiles: ['이거', '입어', '봐도', '돼요'], gloss: ['this (thing)', 'wear', 'if (I) try', 'is it okay?'],
      words: ['cafe:this', 'tryon'] },
    { id: 's-discountplease', level: 3, en: "It's a bit expensive. Can you give me a discount?", ko: '좀 비싸요. 깎아 주세요.',
      tiles: ['좀', '비싸요', '깎아', '주세요'], gloss: ['a bit', "it's expensive", 'cut (the price)', 'please'],
      words: ['expensive', 'discountplease'],
      alts: [['비싸요', '좀', '깎아', '주세요'], ['깎아', '주세요', '좀', '비싸요'], ['좀', '깎아', '주세요', '비싸요']],
      traps: [{ tile: '싸요', why: '싸요 means “it’s cheap”. You ask for a discount because it’s expensive: 비싸요.' }] },
    { id: 's-cardcash', level: 3, en: "I don't have cash. I'll pay by card.", ko: '현금이 없어요. 카드로 할게요.',
      tiles: ['현금이', '없어요', '카드로', '할게요'], gloss: ['cash (subject)', "there isn't", 'by card', "I'll do (it)"],
      words: ['cash', 'day:nothave', 'card', 'takethis'], alts: [['카드로', '할게요', '현금이', '없어요']],
      traps: [{ tile: '현금을', why: '없어요 says that something isn’t there. That thing is the subject, so it takes 이: 현금이 없어요.' }] },
    // No particle questions here: the right answer's rule would read “로 means by (bus, card…) or toward”,
    // which isn't what 로 does in (으)로 할게요 (choosing). The traps below still explain it in the Sentence Builder.
    { id: 's-colour', level: 3, en: "I'll take this colour.", ko: '이 색깔로 할게요.', drill: false,
      tiles: ['이', '색깔로', '할게요'], gloss: ['this', 'with (this) colour', "I'll do (it)"], words: ['colour', 'takethis'],
      traps: [
        { tile: '색깔을', why: 'To say what you choose, use (으)로 할게요: 이 색깔로 할게요 = I’ll go with this colour.' },
        { tile: '색깔에서', why: '에서 marks where an action happens. To say what you choose, use (으)로 할게요: 이 색깔로 할게요.' },
      ] },
    { id: 's-receiptbag', level: 3, en: 'A plastic bag and the receipt, please.', ko: '봉투하고 영수증 주세요.',
      tiles: ['봉투하고', '영수증', '주세요'], gloss: ['plastic bag and', 'receipt', 'please give'],
      words: ['plasticbag', 'receipt', 'cafe:please'],
      traps: [{ tile: '가방하고', why: '가방 is a bag you carry, like a handbag or backpack. The bag you get at the checkout is 봉투.' }] },
    { id: 's-discount', level: 3, en: 'Is there a discount today?', ko: '오늘 할인해요?',
      tiles: ['오늘', '할인해요'], gloss: ['today', 'is there a discount?'], words: ['day:today', 'discount', 'day:do'] },
    { id: 's-justlooking', level: 3, en: "I'm fine, thanks. I'm just looking around.", ko: '괜찮아요. 좀 둘러볼게요.',
      tiles: ['괜찮아요', '좀', '둘러볼게요'], gloss: ["it's okay", 'a bit', "I'll look around"], words: ['cafe:okay', 'justlooking'],
      traps: [{ tile: '살게요', why: '살게요 means “I’ll buy it”. To say you’re just looking around, use 둘러볼게요.' }] },
  ],
});
