/**
 * Sound changes (js/games/sound-changes.js): how Korean words really sound when
 * the letters meet. Each rule has a card; each item is a word or a short phrase
 * that the rule changes, asked as "how is it said?" (pick the pronunciation) and
 * "which spelling did you hear?" (pick the spelling).
 *
 * Rule fields: id, order (the teaching order), level (1–3), emoji, title { ko, en },
 *              text (the rule, Korean in **bold**), note (optional), examples [{ ko, pron, en }].
 * Item fields: id, rule (a rule id), level, ko (the spelling), pron (how it's said,
 *              in Hangul, without brackets), en, wrong (2–3 wrong pronunciations),
 *              spellings (2 wrong spellings a learner might write from the sound;
 *              never a real word that sounds the same), note (optional).
 */
Mallang.content.registerSoundChanges({
  rules: [
    {
      id: 'linking',
      order: 1,
      level: 1,
      emoji: '🔗',
      title: { ko: '연음', en: 'Linking' },
      text: 'When a syllable ends in a consonant (**받침**) and the next one starts with a silent **ㅇ**, the consonant moves over to start that syllable: **먹어요 → [머거요]**. With a double 받침, the first letter stays and the second one moves: **읽어요 → [일거요]**, **앉아요 → [안자요]**.',
      note: 'An **ㅇ** under a syllable is a real sound (ng), so it stays put: **영어** is just [영어]. And before an ending or a particle, the 받침 moves as the letter it is, not as the sound it has at the end of a word: **옷** is [옫], but **옷이 → [오시]**.',
      examples: [
        { ko: '먹어요', pron: '머거요', en: 'I eat' },
        { ko: '읽어요', pron: '일거요', en: 'I read' },
        { ko: '앉아요', pron: '안자요', en: 'I sit (down)' },
      ],
    },
    {
      id: 'h-silent',
      order: 2,
      level: 1,
      emoji: '🤫',
      title: { ko: 'ㅎ 탈락', en: 'Silent ㅎ' },
      text: 'A **ㅎ** at the bottom of a syllable goes quiet when the next syllable starts with **ㅇ**: **좋아요 → [조아요]**. In the double 받침 **ㄶ** and **ㅀ**, the ㅎ goes quiet and the ㄴ or ㄹ moves over: **많이 → [마니]**, **괜찮아요 → [괜차나요]**, **싫어요 → [시러요]**.',
      note: 'In fast everyday speech, an ㅎ that starts a syllable after a vowel or **ㄴ ㄹ ㅁ ㅇ** often fades too: **결혼** sounds like [겨론], **전화** like [저놔]. That is casual speech: the standard pronunciation keeps the ㅎ, [결혼], [전화].',
      examples: [
        { ko: '좋아요', pron: '조아요', en: "it's good" },
        { ko: '많이', pron: '마니', en: 'a lot' },
        { ko: '괜찮아요', pron: '괜차나요', en: "it's okay" },
        { ko: '싫어요', pron: '시러요', en: "I don't like it" },
      ],
    },
    {
      id: 'nasal',
      order: 3,
      level: 2,
      emoji: '👃',
      title: { ko: '비음화', en: 'Nasal sounds' },
      text: 'Before **ㄴ** or **ㅁ**, a 받침 that sounds like **ㄱ ㄷ ㅂ** becomes the nose sound made in the same spot: ㄱ → **ㅇ**, ㄷ → **ㄴ**, ㅂ → **ㅁ**: **학년 → [항년]**, **입니다 → [임니다]**. Letters that end like ㄷ (**ㅅ ㅆ ㅈ ㅊ ㅌ**) do it too: **거짓말 → [거진말]**.',
      note: 'Every **-ㅂ니다** ending does it: **감사합니다 → [감사함니다]**. It also works across a space when two words are said together: **밥 먹어요 → [밤 머거요]**.',
      examples: [
        { ko: '학년', pron: '항년', en: 'school year, grade' },
        { ko: '작년', pron: '장년', en: 'last year' },
        { ko: '거짓말', pron: '거진말', en: 'a lie' },
        { ko: '감사합니다', pron: '감사함니다', en: 'thank you' },
      ],
    },
    {
      id: 'aspiration',
      order: 4,
      level: 2,
      emoji: '💨',
      title: { ko: '격음화', en: 'Aspiration' },
      text: 'When **ㅎ** meets **ㄱ ㄷ ㅂ ㅈ**, before or after it, the two blend into one strong, breathy sound: **ㅋ ㅌ ㅍ ㅊ**. So **좋다 → [조타]**, **축하해요 → [추카해요]**, **입학 → [이팍]**.',
      note: 'Letters that end like ㄷ (**ㅅ ㅈ ㅊ ㅌ**) do it too, even across a space when the words are said together: **못 해요 → [모태요]**.',
      examples: [
        { ko: '좋다', pron: '조타', en: 'to be good' },
        { ko: '축하해요', pron: '추카해요', en: 'congratulations' },
        { ko: '입학', pron: '이팍', en: 'starting school' },
        { ko: '못 해요', pron: '모태요', en: "I can't (do it)" },
      ],
    },
    {
      id: 'tensing',
      order: 5,
      level: 2,
      emoji: '💪',
      title: { ko: '경음화', en: 'Tensing' },
      text: 'After a 받침 that sounds like **ㄱ ㄷ ㅂ**, a following **ㄱ ㄷ ㅂ ㅅ ㅈ** is said tense, as **ㄲ ㄸ ㅃ ㅆ ㅉ**: **학교 → [학꾜]**, **식당 → [식땅]**, **잡지 → [잡찌]**. The spelling never shows it, but everyone says it.',
      note: 'Letters that end like ㄷ count too: **맛집 → [맏찝]**. You also hear tense sounds after the future -ㄹ of a verb: **갈 거예요 → [갈 꺼예요]**.',
      examples: [
        { ko: '학교', pron: '학꾜', en: 'school' },
        { ko: '식당', pron: '식땅', en: 'restaurant' },
        { ko: '잡지', pron: '잡찌', en: 'magazine' },
        { ko: '맛집', pron: '맏찝', en: 'a great place to eat' },
      ],
    },
    {
      id: 'palatal',
      order: 6,
      level: 3,
      emoji: '👅',
      title: { ko: '구개음화', en: 'Palatalization' },
      text: 'When a 받침 **ㄷ** or **ㅌ** is followed by an added **이** (a particle or a suffix), it moves over and changes: ㄷ + 이 → **[지]**, ㅌ + 이 → **[치]**. So **같이 → [가치]**, **굳이 → [구지]**, **붙이다 → [부치다]**.',
      note: 'It works the same with **히**: ㄷ + 히 → **[치]**, as in **닫히다 → [다치다]**. Only a 받침 changes: a ㄷ or ㅌ that starts its syllable stays, as in **어디** [어디].',
      examples: [
        { ko: '같이', pron: '가치', en: 'together' },
        { ko: '굳이', pron: '구지', en: '(not) necessarily; bother to' },
        { ko: '붙이다', pron: '부치다', en: 'to stick (on)' },
      ],
    },
    {
      id: 'liquid',
      order: 7,
      level: 3,
      emoji: '💧',
      title: { ko: '유음화', en: 'ㄴ becomes ㄹ' },
      text: 'When **ㄴ** comes right before **ㄹ**, the ㄴ turns into ㄹ as well, so you hear a long [ㄹㄹ]: **신라 → [실라]**, **연락 → [열락]**. It works with the ㄹ first, too: **설날 → [설랄]**.',
      note: 'A few words built with parts like -량 or -력 go the other way and say ㄴㄴ: **생산량 → [생산냥]** (amount produced). You won\'t meet many of them at first.',
      examples: [
        { ko: '신라', pron: '실라', en: 'Silla (an old Korean kingdom)' },
        { ko: '연락', pron: '열락', en: 'contact, getting in touch' },
        { ko: '설날', pron: '설랄', en: 'Lunar New Year' },
        { ko: '편리해요', pron: '펼리해요', en: "it's convenient" },
      ],
    },
  ],
  items: [
    // ── linking 연음 ──
    {
      id: 'eumak',
      rule: 'linking',
      level: 1,
      ko: '음악',
      pron: '으막',
      en: 'music',
      wrong: ['음악', '음막'],
      spellings: ['으막', '음막'],
      note: 'The ㅁ of 음 moves over to start 악: 으-막.',
    },
    {
      id: 'hangugeo',
      rule: 'linking',
      level: 1,
      ko: '한국어',
      pron: '한구거',
      en: 'Korean (the language)',
      wrong: ['한국어', '한구어'],
      spellings: ['한구거', '한국거'],
      note: 'The ㄱ of 국 moves over to 어: 한-구-거.',
    },
    {
      id: 'isseoyo',
      rule: 'linking',
      level: 1,
      ko: '있어요',
      pron: '이써요',
      en: 'there is; I have',
      wrong: ['이서요', '이더요'],
      spellings: ['이써요', '잇어요'],
      note: 'The whole ㅆ moves over, and it stays tense: 이-써요.',
    },
    {
      id: 'jigeop',
      rule: 'linking',
      level: 1,
      ko: '직업',
      pron: '지겁',
      en: 'job, occupation',
      wrong: ['직업', '직껍'],
      spellings: ['지겁', '직겁'],
      note: 'The ㄱ of 직 moves over to 업: 지-겁.',
    },
    {
      id: 'ape',
      rule: 'linking',
      level: 1,
      ko: '앞에',
      pron: '아페',
      en: 'in front (of)',
      wrong: ['아베', '아뻬'],
      spellings: ['아페', '앞페'],
      note: 'On its own 앞 ends in a [ㅂ] sound, but before 에 the real letter ㅍ moves over: 아-페.',
    },
    {
      id: 'chajayo',
      rule: 'linking',
      level: 1,
      ko: '찾아요',
      pron: '차자요',
      en: 'I look for (it)',
      wrong: ['차다요', '차짜요'],
      spellings: ['차자요', '찻아요'],
      note: 'The ㅈ moves over as ㅈ, not as the [ㄷ] it sounds like at the end of a word: 차-자요.',
    },
    {
      id: 'mogyoil',
      rule: 'linking',
      level: 1,
      ko: '목요일',
      pron: '모교일',
      en: 'Thursday',
      wrong: ['몽요일', '모요일'],
      spellings: ['모교일', '목교일'],
      note: 'The ㄱ of 목 moves over to 요: 모-교-일.',
    },
    {
      id: 'malgayo',
      rule: 'linking',
      level: 2,
      ko: '맑아요',
      pron: '말가요',
      en: "it's clear (sunny)",
      wrong: ['마가요', '마라요'],
      spellings: ['말가요', '맑가요'],
      note: 'Of the double 받침 ㄺ, the ㄹ stays and the ㄱ moves over: 말-가요.',
    },
    {
      id: 'dalmasseoyo',
      rule: 'linking',
      level: 2,
      ko: '닮았어요',
      pron: '달마써요',
      en: 'looks like (someone)',
      wrong: ['다마써요', '다라써요'],
      spellings: ['달마써요', '달맜어요'],
      note: 'Of the double 받침 ㄻ, the ㄹ stays and the ㅁ moves over (달-마), then the ㅆ of 았 moves to 어 (써): 달-마-써요.',
    },
    // ── h-silent ㅎ 탈락 ──
    {
      id: 'joahaeyo',
      rule: 'h-silent',
      level: 1,
      ko: '좋아해요',
      pron: '조아해요',
      en: 'I like (it)',
      wrong: ['조하해요', '조다해요'],
      spellings: ['조아해요', '조하해요'],
      note: 'The ㅎ of 좋 goes quiet before 아: 조-아해요. The ㅎ of 해요 starts its syllable, so in careful speech it stays.',
    },
    {
      id: 'sireohaeyo',
      rule: 'h-silent',
      level: 1,
      ko: '싫어해요',
      pron: '시러해요',
      en: 'I dislike (it)',
      wrong: ['실허해요', '실러해요'],
      spellings: ['시러해요', '실어해요'],
      note: 'Of ㅀ, the ㅎ goes quiet and the ㄹ moves over: 시-러해요.',
    },
    {
      id: 'neoeoyo',
      rule: 'h-silent',
      level: 1,
      ko: '넣어요',
      pron: '너어요',
      en: 'I put (it) in',
      wrong: ['너허요', '너더요'],
      spellings: ['너어요', '너허요'],
      note: 'The ㅎ goes quiet, and nothing moves over: 너-어요.',
    },
    {
      id: 'joasseoyo',
      rule: 'h-silent',
      level: 1,
      ko: '좋았어요',
      pron: '조아써요',
      en: 'it was good',
      wrong: ['조하써요', '조다써요'],
      spellings: ['조았어요', '조아써요'],
      note: 'The ㅎ goes quiet (조-아), and the ㅆ of 았 moves over to 어: 조-아-써요.',
    },
    {
      id: 'noeuseyo',
      rule: 'h-silent',
      level: 2,
      ko: '놓으세요',
      pron: '노으세요',
      en: 'please put it (down)',
      wrong: ['노흐세요', '노드세요'],
      spellings: ['노으세요', '노흐세요'],
      note: 'The ㅎ of 놓 goes quiet before 으: 노-으세요.',
    },
    {
      id: 'kkeuneoyo',
      rule: 'h-silent',
      level: 2,
      ko: '끊어요',
      pron: '끄너요',
      en: 'I hang up (the phone); I quit',
      wrong: ['끈허요', '끈너요'],
      spellings: ['끄너요', '끈어요'],
      note: 'Of ㄶ, the ㅎ goes quiet and the ㄴ moves over: 끄-너요.',
    },
    {
      id: 'kkeuryeoyo',
      rule: 'h-silent',
      level: 2,
      ko: '끓여요',
      pron: '끄려요',
      en: 'I boil (it); I make (ramyeon, soup)',
      wrong: ['끌혀요', '끌려요'],
      spellings: ['끄려요', '끌여요'],
      note: 'Of ㅀ, the ㅎ goes quiet and the ㄹ moves over: 끄-려요.',
    },
    {
      id: 'gwichanayo',
      rule: 'h-silent',
      level: 2,
      ko: '귀찮아요',
      pron: '귀차나요',
      en: "it's a bother; I can't be bothered",
      wrong: ['귀찬하요', '귀찬나요'],
      spellings: ['귀차나요', '귀찬아요'],
      note: 'Like 괜찮아요: of ㄶ, the ㅎ goes quiet and the ㄴ moves over: 귀-차-나요.',
    },
    {
      id: 'ireobeoryeosseoyo',
      rule: 'h-silent',
      level: 2,
      ko: '잃어버렸어요',
      pron: '이러버려써요',
      en: 'I lost (it)',
      wrong: ['일허버려써요', '일러버려써요'],
      spellings: ['이러버렸어요', '일러버렸어요'],
      note: 'Of ㅀ, the ㅎ goes quiet and the ㄹ moves over (이-러), and the ㅆ of 렸 moves to 어 (써): 이-러-버-려-써요.',
    },
    // ── nasal 비음화 ──
    {
      id: 'mangnae',
      rule: 'nasal',
      level: 2,
      ko: '막내',
      pron: '망내',
      en: 'the youngest (in a family)',
      wrong: ['막내', '만내'],
      spellings: ['망내', '맘내'],
      note: 'ㄱ before ㄴ becomes ㅇ: 막 → 망.',
    },
    {
      id: 'gungmul',
      rule: 'nasal',
      level: 2,
      ko: '국물',
      pron: '궁물',
      en: 'soup, broth',
      wrong: ['국물', '굼물'],
      spellings: ['궁물', '굼물'],
      note: 'ㄱ before ㅁ becomes ㅇ: 국 → 궁.',
    },
    {
      id: 'mongmallayo',
      rule: 'nasal',
      level: 2,
      ko: '목말라요',
      pron: '몽말라요',
      en: "I'm thirsty",
      wrong: ['목말라요', '몸말라요'],
      spellings: ['몽말라요', '몸말라요'],
      note: 'ㄱ before ㅁ becomes ㅇ: 목 → 몽.',
    },
    {
      id: 'konmul',
      rule: 'nasal',
      level: 2,
      ko: '콧물',
      pron: '콘물',
      en: 'a runny nose',
      wrong: ['코물', '콛물'],
      spellings: ['콘물', '코물'],
      note: 'The ㅅ of 콧 sounds like ㄷ, and ㄷ before ㅁ becomes ㄴ: 콧 → 콘.',
    },
    {
      id: 'cheonnal',
      rule: 'nasal',
      level: 2,
      ko: '첫날',
      pron: '천날',
      en: 'the first day',
      wrong: ['첟날', '처날'],
      spellings: ['천날', '첨날'],
      note: 'The ㅅ of 첫 sounds like ㄷ, and ㄷ before ㄴ becomes ㄴ: 첫 → 천.',
    },
    {
      id: 'kkeunnasseoyo',
      rule: 'nasal',
      level: 2,
      ko: '끝났어요',
      pron: '끈나써요',
      en: "it's over; it ended",
      wrong: ['끋나써요', '끄나써요'],
      spellings: ['끈났어요', '끈나써요'],
      note: 'The ㅌ of 끝 sounds like ㄷ, and ㄷ before ㄴ becomes ㄴ (끝 → 끈); the ㅆ of 났 moves over to 어 (써).',
    },
    {
      id: 'simman',
      rule: 'nasal',
      level: 2,
      ko: '십만',
      pron: '심만',
      en: 'a hundred thousand',
      wrong: ['십만', '신만'],
      spellings: ['심만', '싱만'],
      note: 'ㅂ before ㅁ becomes ㅁ: 십 → 심. You hear it in prices: 십만 원 (100,000 won).',
    },
    {
      id: 'gamnida',
      rule: 'nasal',
      level: 2,
      ko: '갑니다',
      pron: '감니다',
      en: 'I go (formal)',
      wrong: ['갑니다', '간니다'],
      spellings: ['감니다', '간니다'],
      note: 'ㅂ before ㄴ becomes ㅁ: 갑 → 감.',
    },
    {
      id: 'monmeogeoyo',
      rule: 'nasal',
      level: 3,
      ko: '못 먹어요',
      pron: '몬 머거요',
      en: "I can't eat (it)",
      wrong: ['몽 머거요', '모 머거요'],
      spellings: ['몬 머거요', '못 머거요'],
      note: 'The ㅅ of 못 sounds like ㄷ, and before the ㅁ of 먹어요 it becomes ㄴ (the two words are said together): 몬. In 먹어요 the ㄱ links: 머-거요.',
    },
    // ── aspiration 격음화 ──
    {
      id: 'chakaeyo',
      rule: 'aspiration',
      level: 2,
      ko: '착해요',
      pron: '차캐요',
      en: '(someone) is kind',
      wrong: ['차개요', '착해요'],
      spellings: ['차캐요', '착캐요'],
      note: 'ㄱ + ㅎ → ㅋ: 차-캐요.',
    },
    {
      id: 'baekwajeom',
      rule: 'aspiration',
      level: 2,
      ko: '백화점',
      pron: '배콰점',
      en: 'department store',
      wrong: ['배과점', '배화점'],
      spellings: ['배콰점', '백콰점'],
      note: 'ㄱ + ㅎ → ㅋ: 배-콰-점.',
    },
    {
      id: 'sikhu',
      rule: 'aspiration',
      level: 2,
      ko: '식후',
      pron: '시쿠',
      en: 'after meals',
      wrong: ['시구', '시후'],
      spellings: ['시쿠', '식쿠'],
      note: 'ㄱ + ㅎ → ㅋ: 시-쿠. You see it on medicine packets.',
    },
    {
      id: 'daedapaeyo',
      rule: 'aspiration',
      level: 2,
      ko: '대답해요',
      pron: '대다패요',
      en: 'I answer',
      wrong: ['대다배요', '대답해요'],
      spellings: ['대다패요', '대답패요'],
      note: 'ㅂ + ㅎ → ㅍ: 대-다-패요.',
    },
    {
      id: 'geupaeyo',
      rule: 'aspiration',
      level: 2,
      ko: '급해요',
      pron: '그패요',
      en: "it's urgent; I'm in a hurry",
      wrong: ['그배요', '급해요'],
      spellings: ['그패요', '급패요'],
      note: 'ㅂ + ㅎ → ㅍ: 그-패요.',
    },
    {
      id: 'ttatteutaeyo',
      rule: 'aspiration',
      level: 2,
      ko: '따뜻해요',
      pron: '따뜨태요',
      en: "it's warm",
      wrong: ['따뜨새요', '따뜨해요'],
      spellings: ['따뜨태요', '따뜻태요'],
      note: 'The ㅅ of 뜻 sounds like ㄷ, and ㄷ + ㅎ → ㅌ: 따-뜨-태요.',
    },
    {
      id: 'eotteoke',
      rule: 'aspiration',
      level: 2,
      ko: '어떻게',
      pron: '어떠케',
      en: 'how',
      wrong: ['어떠게', '어떧께'],
      spellings: ['어떠케', '어떡게'],
      note: 'ㅎ + ㄱ → ㅋ: 어-떠-케.',
    },
    {
      id: 'geureochiman',
      rule: 'aspiration',
      level: 2,
      ko: '그렇지만',
      pron: '그러치만',
      en: 'but, however',
      wrong: ['그러지만', '그럳찌만'],
      spellings: ['그러치만', '그럿치만'],
      note: 'ㅎ + ㅈ → ㅊ: 그-러-치만.',
    },
    {
      id: 'giri-makyeoyo',
      rule: 'aspiration',
      level: 3,
      ko: '길이 막혀요',
      pron: '기리 마켜요',
      en: 'the traffic is bad',
      wrong: ['기리 마겨요', '기리 막혀요'],
      spellings: ['길이 마켜요', '길이 막켜요'],
      note: 'ㄱ + ㅎ → ㅋ: 마-켜요. In 길이 the ㄹ links: 기-리.',
    },
    // ── tensing 경음화 ──
    {
      id: 'sukje',
      rule: 'tensing',
      level: 2,
      ko: '숙제',
      pron: '숙쩨',
      en: 'homework',
      wrong: ['숙제', '숙체'],
      spellings: ['숙쩨', '숙째'],
      note: 'After the ㄱ of 숙, ㅈ becomes tense ㅉ: 숙-쩨.',
    },
    {
      id: 'yakguk',
      rule: 'tensing',
      level: 2,
      ko: '약국',
      pron: '약꾹',
      en: 'pharmacy',
      wrong: ['약국', '약쿡'],
      spellings: ['약꾹', '야꾹'],
      note: 'After the ㄱ of 약, ㄱ becomes tense ㄲ: 약-꾹.',
    },
    {
      id: 'haksaeng',
      rule: 'tensing',
      level: 2,
      ko: '학생',
      pron: '학쌩',
      en: 'student',
      wrong: ['학생', '하생'],
      spellings: ['학쌩', '하쌩'],
      note: 'After the ㄱ of 학, ㅅ becomes tense ㅆ: 학-쌩.',
    },
    {
      id: 'tteokbokki',
      rule: 'tensing',
      level: 2,
      ko: '떡볶이',
      pron: '떡뽀끼',
      en: 'tteokbokki (spicy rice cakes)',
      wrong: ['떡보끼', '떡포끼'],
      spellings: ['떡뽀끼', '떡뽁이'],
      note: 'After the ㄱ of 떡, ㅂ becomes tense ㅃ (떡-뽀), and the ㄲ of 볶 moves over to 이 (끼).',
    },
    {
      id: 'sutgarak',
      rule: 'tensing',
      level: 2,
      ko: '숟가락',
      pron: '숟까락',
      en: 'spoon',
      wrong: ['숟가락', '수가락'],
      spellings: ['숟까락', '숫가락'],
      note: 'After the ㄷ of 숟, ㄱ becomes tense ㄲ: 숟-까락.',
    },
    {
      id: 'jeopsi',
      rule: 'tensing',
      level: 2,
      ko: '접시',
      pron: '접씨',
      en: 'plate, dish',
      wrong: ['접시', '저시'],
      spellings: ['접씨', '젓시'],
      note: 'After the ㅂ of 접, ㅅ becomes tense ㅆ: 접-씨.',
    },
    {
      id: 'ipgu',
      rule: 'tensing',
      level: 2,
      ko: '입구',
      pron: '입꾸',
      en: 'entrance',
      wrong: ['입구', '입쿠'],
      spellings: ['입꾸', '이꾸'],
      note: 'After the ㅂ of 입, ㄱ becomes tense ㄲ: 입-꾸.',
    },
    {
      id: 'meokgo-sipeoyo',
      rule: 'tensing',
      level: 2,
      ko: '먹고 싶어요',
      pron: '먹꼬 시퍼요',
      en: 'I want to eat',
      wrong: ['먹고 시퍼요', '머고 시퍼요'],
      spellings: ['먹꼬 싶어요', '먹꼬 시퍼요'],
      note: 'After the ㄱ of 먹, the ㄱ of 고 becomes tense ㄲ: 먹-꼬. In 싶어요 the ㅍ links: 시-퍼요.',
    },
    {
      id: 'neutjam',
      rule: 'tensing',
      level: 3,
      ko: '늦잠',
      pron: '늗짬',
      en: 'sleeping in',
      wrong: ['늗잠', '느잠'],
      spellings: ['늗짬', '늦짬'],
      note: 'The ㅈ of 늦 sounds like ㄷ, so the next ㅈ becomes tense ㅉ: 늗-짬.',
    },
    // ── palatal 구개음화 ──
    {
      id: 'haedoji',
      rule: 'palatal',
      level: 3,
      ko: '해돋이',
      pron: '해도지',
      en: 'sunrise',
      wrong: ['해도디', '해도치'],
      spellings: ['해도지', '해돚이'],
      note: 'ㄷ + 이 → 지: 해-도-지.',
    },
    {
      id: 'midaji',
      rule: 'palatal',
      level: 3,
      ko: '미닫이',
      pron: '미다지',
      en: 'a sliding door',
      wrong: ['미다디', '미다치'],
      spellings: ['미다지', '미닺이'],
      note: 'ㄷ + 이 → 지: 미-다-지.',
    },
    {
      id: 'kkeuchieyo',
      rule: 'palatal',
      level: 3,
      ko: '끝이에요',
      pron: '끄치에요',
      en: "it's the end; that's all",
      wrong: ['끄티에요', '끄디에요'],
      spellings: ['끄치에요', '끝치에요'],
      note: 'ㅌ + 이 → 치: 끄-치에요.',
    },
    {
      id: 'michieyo',
      rule: 'palatal',
      level: 3,
      ko: '밑이에요',
      pron: '미치에요',
      en: "it's underneath",
      wrong: ['미티에요', '미디에요'],
      spellings: ['미치에요', '밑치에요'],
      note: 'ㅌ + 이 → 치: 미-치에요, as in 책상 밑이에요 (it\'s under the desk).',
    },
    {
      id: 'bakkachi-chuwoyo',
      rule: 'palatal',
      level: 3,
      ko: '바깥이 추워요',
      pron: '바까치 추워요',
      en: "it's cold outside",
      wrong: ['바까티 추워요', '바까디 추워요'],
      spellings: ['바까치 추워요', '바깥치 추워요'],
      note: 'ㅌ + 이 → 치: 바-까-치.',
    },
    {
      id: 'byeochi-joayo',
      rule: 'palatal',
      level: 3,
      ko: '볕이 좋아요',
      pron: '벼치 조아요',
      en: 'the sunshine is lovely',
      wrong: ['벼티 조아요', '벼디 조아요'],
      spellings: ['벼치 좋아요', '볕치 좋아요'],
      note: 'ㅌ + 이 → 치: 벼-치. And the ㅎ of 좋아요 goes quiet: 조-아요.',
    },
    {
      id: 'ttokgachi',
      rule: 'palatal',
      level: 3,
      ko: '똑같이',
      pron: '똑까치',
      en: 'exactly the same (way)',
      wrong: ['똑까티', '똑까디'],
      spellings: ['똑가치', '똑같치'],
      note: 'ㅌ + 이 → 치 (가-치), and after the ㄱ of 똑, the next ㄱ is tense: 똑-까-치.',
    },
    {
      id: 'satsachi',
      rule: 'palatal',
      level: 3,
      ko: '샅샅이',
      pron: '삳싸치',
      en: 'thoroughly, in every corner',
      wrong: ['삳싸티', '삳사치'],
      spellings: ['삿싸치', '샅싸치'],
      note: 'The first ㅌ sounds like ㄷ, so the ㅅ after it is tense (삳-싸); the second ㅌ + 이 → 치: 삳-싸-치.',
    },
    {
      id: 'gachyeosseoyo',
      rule: 'palatal',
      level: 3,
      ko: '갇혔어요',
      pron: '가처써요',
      en: 'I got stuck (shut in)',
      wrong: ['가텨써요', '가저써요'],
      spellings: ['가쳤어요', '갇쳤어요'],
      note: 'ㄷ + 히 sounds like 치 (갇히다 → [가치다]). Here 히 + 었 makes 혔: after ㅊ the ㅕ sounds like ㅓ, and the ㅆ moves over to 어: 가-처-써요.',
    },
    // ── liquid 유음화 ──
    {
      id: 'wollae',
      rule: 'liquid',
      level: 3,
      ko: '원래',
      pron: '월래',
      en: 'originally; by nature',
      wrong: ['원래', '원내'],
      spellings: ['월레', '원레'],
      note: 'ㄴ before ㄹ becomes ㄹ: 원 → 월.',
    },
    {
      id: 'hallyu',
      rule: 'liquid',
      level: 3,
      ko: '한류',
      pron: '할류',
      en: 'the Korean Wave',
      wrong: ['한류', '한뉴'],
      spellings: ['할류', '할뉴'],
      note: 'ㄴ before ㄹ becomes ㄹ: 한 → 할.',
    },
    {
      id: 'sillang',
      rule: 'liquid',
      level: 3,
      ko: '신랑',
      pron: '실랑',
      en: 'bridegroom',
      wrong: ['신랑', '신낭'],
      spellings: ['실랑', '실낭'],
      note: 'ㄴ before ㄹ becomes ㄹ: 신 → 실.',
    },
    {
      id: 'hallasan',
      rule: 'liquid',
      level: 3,
      ko: '한라산',
      pron: '할라산',
      en: 'Hallasan (the mountain on Jeju)',
      wrong: ['한라산', '한나산'],
      spellings: ['할라산', '할나산'],
      note: 'ㄴ before ㄹ becomes ㄹ: 한 → 할.',
    },
    {
      id: 'hullyeon',
      rule: 'liquid',
      level: 3,
      ko: '훈련',
      pron: '훌련',
      en: 'training',
      wrong: ['훈련', '훈년'],
      spellings: ['훌련', '훌년'],
      note: 'ㄴ before ㄹ becomes ㄹ: 훈 → 훌.',
    },
    {
      id: 'sillae',
      rule: 'liquid',
      level: 3,
      ko: '실내',
      pron: '실래',
      en: 'indoors',
      wrong: ['실내', '신내'],
      spellings: ['실래', '실네'],
      note: 'ㄴ after ㄹ becomes ㄹ: 내 → 래.',
    },
    {
      id: 'mullaengmyeon',
      rule: 'liquid',
      level: 3,
      ko: '물냉면',
      pron: '물랭면',
      en: 'cold noodles in broth',
      wrong: ['물냉면', '문냉면'],
      spellings: ['물랭면', '물렝면'],
      note: 'ㄴ after ㄹ becomes ㄹ: 냉 → 랭.',
    },
    {
      id: 'mullori',
      rule: 'liquid',
      level: 3,
      ko: '물놀이',
      pron: '물로리',
      en: 'playing in the water',
      wrong: ['물노리', '문노리'],
      spellings: ['물로리', '물롤이'],
      note: 'ㄴ after ㄹ becomes ㄹ (물-로), and the ㄹ of 놀 moves over to 이 (리): 물-로-리.',
    },
    {
      id: 'saengillal',
      rule: 'liquid',
      level: 3,
      ko: '생일날',
      pron: '생일랄',
      en: 'the birthday (the day itself)',
      wrong: ['생일날', '생인날'],
      spellings: ['생일랄', '생이랄'],
      note: 'ㄴ after ㄹ becomes ㄹ: 날 → 랄.',
    },
  ],
});
