/**
 * Speech levels (말투), practised in Speech Levels (js/games/speech-levels.js):
 * the same sentence in the three everyday levels, and when to use each.
 *   합니다체 (formal):  -ㅂ니다 / -습니다: the news, announcements, presentations, interviews.
 *   해요체 (polite):    -아요 / -어요: everyday polite speech, the safe default.
 *   반말 (casual):      -아 / -어 (해요 without 요): close friends your age, younger
 *                       brothers and sisters, children.
 *
 * card:   what a new learner sees first: title { ko, en }, text, note,
 *         levels (formal, polite, casual, in that order: { to, ko, en, emoji, ending,
 *                 when, example { ko, en } }),
 *         table (what changes: [{ en, formal, polite, casual }]),
 *         wrong[picked][wanted] (why the picked level doesn't fit a scene where the
 *                 wanted one does; shown after a wrong answer).
 * scenes: who you're talking to (or where), with the level that clearly fits:
 *         [{ id, to: 'formal' | 'polite' | 'casual', emoji, ko, en }].
 * items:  one sentence in all three levels, changing only what the level changes
 *         (the ending, 저 → 나, 제 → 내, 네 → 응…):
 *         id, level (1–3), en, formal, polite, casual,
 *         words (1–4 vocabulary refs, 'topic:id': the item opens once they're learned),
 *         scenes (2–4 scene ids where the sentence is natural, of at least two levels),
 *         note (optional: what else changes, and why),
 *         traps [{ to: 'casual' | 'formal', text, why }]: the wrong versions learners
 *               really make (저 kept in 반말, 가방야, 먹읍니다, 알습니다…), each with its reason.
 * Numbers are written in Hangul (일곱 시), the way they're read aloud.
 */
Mallang.content.registerSpeechLevels({
  card: {
    title: { ko: '합니다 · 해요 · 반말', en: 'Three ways to say it' },
    text: 'Korean changes the **end of the sentence** to suit who you’re talking to: formal **합니다체** for the news, presentations and interviews, polite **해요체** for everyday talk, and casual **반말** (해요 without **요**) for close friends and children. A few words change too: **저** (I) becomes **나**, and **네** (yes) becomes **응**.',
    note: 'Not sure? Use **해요체**: it’s polite without being stiff, and never rude. With adults, switch to **반말** only when the other person offers (**말 편하게 하세요** or **말 놓으세요**: “feel free to talk casually”), or when a friend your age agrees to it. Some set phrases are usually said in 합니다체 even in everyday talk: **감사합니다**, **죄송합니다**, **처음 뵙겠습니다**.',
    levels: [
      {
        to: 'formal',
        ko: '합니다체',
        en: 'Formal',
        emoji: '🎤',
        ending: '-ㅂ니다 / -습니다',
        when: 'Formal situations and big audiences: the news, announcements, presentations and speeches, job interviews, the army.',
        example: { ko: '저는 한국어를 공부합니다.', en: 'I study Korean.' },
      },
      {
        to: 'polite',
        ko: '해요체',
        en: 'Polite',
        emoji: '🙂',
        ending: '-아요 / -어요',
        when: 'Everyday polite speech with adults who aren’t close friends or family: shop staff, strangers, teachers, colleagues. The safe default.',
        example: { ko: '저는 한국어를 공부해요.', en: 'I study Korean.' },
      },
      {
        to: 'casual',
        ko: '반말',
        en: 'Casual',
        emoji: '👫',
        ending: '-아 / -어',
        when: 'Close friends your age, younger brothers and sisters, children, and often your own family. Rude to strangers, and to older people outside your family, unless they ask you to use it.',
        example: { ko: '나는 한국어를 공부해.', en: 'I study Korean.' },
      },
    ],
    table: [
      { en: 'I · my', formal: '저 · 제', polite: '저 · 제', casual: '나 · 내' },
      { en: 'we · our', formal: '저희 · 우리', polite: '저희 · 우리', casual: '우리' },
      { en: 'yes', formal: '네', polite: '네', casual: '응' },
      { en: 'no', formal: '아니요', polite: '아니요', casual: '아니' },
      { en: 'calling someone your age', formal: '민수 씨', polite: '민수 씨', casual: '민수야 · 지훈아' },
      { en: '“is” after a noun', formal: '입니다', polite: '이에요 · 예요', casual: '이야 · 야' },
      { en: 'statements', formal: '갑니다 · 먹습니다', polite: '가요 · 먹어요', casual: '가 · 먹어' },
      { en: 'questions', formal: '갑니까? · 먹습니까?', polite: '가요? · 먹어요?', casual: '가? · 먹어?' },
      { en: '“please do”', formal: '가십시오 · 앉으십시오', polite: '가세요 · 앉으세요', casual: '가 · 앉아' },
      { en: '“please give me”', formal: '주십시오', polite: '주세요', casual: '줘' },
      { en: '“let’s”', formal: '갑시다 · 먹읍시다', polite: '가요 · 먹어요', casual: '가자 · 먹자' },
      { en: 'the past', formal: '갔습니다 · 먹었습니다', polite: '갔어요 · 먹었어요', casual: '갔어 · 먹었어' },
    ],
    wrong: {
      formal: {
        polite: '합니다체 isn’t rude, but in everyday talk like this it sounds stiff, as if you were making an announcement. 해요체 is the natural choice here.',
        casual: 'Far too stiff for a close friend, a younger brother or sister, or a child: it sounds cold, or like a joke.',
      },
      polite: {
        formal: '해요체 is polite, but the news, announcements, presentations and job interviews call for the more formal 합니다체.',
        casual: 'Polite, but with a close friend, a younger brother or sister, or a child, it keeps them at a distance.',
      },
      casual: {
        formal: '반말 is for close friends, younger brothers and sisters, and children. In a formal setting like this, it sounds rude and out of place.',
        polite: '반말 sounds rude to adults who aren’t close friends or family: shop staff, strangers, teachers and colleagues get 해요체.',
      },
    },
  },

  scenes: [
    { id: 'friend', to: 'casual', emoji: '👫', ko: '친한 친구한테', en: 'To a close friend your age' },
    { id: 'sibling', to: 'casual', emoji: '👧', ko: '동생한테', en: 'To your younger brother or sister' },
    { id: 'child', to: 'casual', emoji: '🧒', ko: '어린아이한테', en: 'To a small child' },
    { id: 'chat', to: 'casual', emoji: '💬', ko: '친구들 채팅방에서', en: 'In your friends’ group chat' },
    { id: 'shop', to: 'polite', emoji: '🛍️', ko: '가게 직원한테', en: 'To a shop assistant' },
    { id: 'stranger', to: 'polite', emoji: '🙋', ko: '처음 만난 사람한테', en: 'To someone you’ve just met' },
    { id: 'teacher', to: 'polite', emoji: '👩‍🏫', ko: '선생님한테', en: 'To your teacher' },
    { id: 'colleague', to: 'polite', emoji: '🧑‍💼', ko: '회사 동료한테', en: 'To a colleague at work' },
    { id: 'news', to: 'formal', emoji: '📺', ko: '뉴스에서', en: 'Reading the news' },
    { id: 'announcement', to: 'formal', emoji: '📢', ko: '안내 방송에서', en: 'In a public announcement' },
    { id: 'presentation', to: 'formal', emoji: '📊', ko: '발표할 때', en: 'Giving a presentation' },
    { id: 'interview', to: 'formal', emoji: '💼', ko: '면접에서', en: 'In a job interview' },
  ],

  items: [
    // ---------- Level 1: simple statements and questions ----------
    { id: 'hello', level: 1, en: 'Hello.', formal: '안녕하십니까?', polite: '안녕하세요?', casual: '안녕?',
      words: ['people:hello'], scenes: ['news', 'shop', 'child'],
      note: '안녕하세요 and 안녕하십니까 both have the respectful 시 in them. 반말 keeps just 안녕 (between friends it also means “bye”).',
      traps: [
        { to: 'casual', text: '안녕하세?', why: 'Taking 요 off 안녕하세요 doesn’t make 반말. The casual greeting is just 안녕.' },
        { to: 'casual', text: '안녕해?', why: '안녕해 isn’t a greeting. Friends and children just get 안녕.' },
        { to: 'formal', text: '안녕합니까?', why: 'The formal greeting keeps the respectful 시: 안녕하십니까.' },
      ] },
    { id: 'bag', level: 1, en: 'This is my bag.', formal: '이거 제 가방입니다.', polite: '이거 제 가방이에요.', casual: '이거 내 가방이야.',
      words: ['shopping:bag', 'cafe:this'], scenes: ['sibling', 'friend', 'stranger'],
      note: '반말 uses 내 for “my” (제 when you’re polite), and 이야 for “is” after a consonant: 가방이야.',
      traps: [
        { to: 'casual', text: '이거 제 가방이야.', why: '제 is the polite “my”. In 반말 it’s 내: 내 가방이야.' },
        { to: 'casual', text: '이거 내 가방야.', why: '가방 ends in a consonant, so “is” is 이야: 가방이야. Plain 야 comes after a vowel (커피야).' },
        { to: 'formal', text: '이거 내 가방입니다.', why: '합니다체 goes with the polite “my”, 제: 제 가방입니다.' },
        { to: 'formal', text: '이거 제 가방이입니다.', why: '입니다 goes straight onto the noun, with no extra 이: 가방입니다.' },
      ] },
    { id: 'coffee', level: 1, en: 'I like coffee.', formal: '저는 커피가 좋습니다.', polite: '저는 커피가 좋아요.', casual: '나는 커피가 좋아.',
      words: ['cafe:coffee', 'feelings:good'], scenes: ['friend', 'colleague'],
      note: '반말 uses 나 for “I” (저 when you’re polite).',
      traps: [
        { to: 'casual', text: '저는 커피가 좋아.', why: '저 is the polite “I” and doesn’t go with 반말. With a friend it’s 나는.' },
        { to: 'casual', text: '나는 커피가 좋.', why: 'Only 요 comes off: 좋아요 → 좋아. 좋 on its own is just the stem.' },
        { to: 'formal', text: '나는 커피가 좋습니다.', why: '나 is the casual “I”; 합니다체 needs 저: 저는 커피가 좋습니다.' },
      ] },
    { id: 'learn', level: 1, en: 'I’m learning Korean.', formal: '저는 한국어를 배웁니다.', polite: '저는 한국어를 배워요.', casual: '나는 한국어를 배워.',
      words: ['day:korean', 'hobbies:learn'], scenes: ['presentation', 'stranger', 'friend'],
      traps: [
        { to: 'casual', text: '저는 한국어를 배워.', why: '저 with a 반말 ending mixes two levels: it’s 나는 한국어를 배워.' },
        { to: 'casual', text: '나는 한국어를 배우.', why: '배우 is just the stem. 반말 is the 해요 form without 요: 배워요 → 배워.' },
        { to: 'formal', text: '저는 한국어를 배우습니다.', why: 'After a vowel the ending is -ㅂ니다, joined to the stem: 배웁니다.' },
      ] },
    { id: 'name', level: 1, en: 'What’s your name?', formal: '이름이 무엇입니까?', polite: '이름이 뭐예요?', casual: '이름이 뭐야?',
      words: ['people:name', 'day:what'], scenes: ['child', 'stranger'],
      note: '합니다체 often has the full word 무엇 (“what”); 뭐 is its everyday short form. To an older person, ask 성함이 어떻게 되세요? instead.',
      traps: [
        { to: 'casual', text: '이름이 뭐이야?', why: '뭐 ends in a vowel, so “is” is just 야: 뭐야.' },
        { to: 'casual', text: '이름이 뭐예?', why: 'Taking 요 off 예요 doesn’t make 반말: after a noun, the casual “is” is 이야 / 야, so 뭐야.' },
        { to: 'formal', text: '이름이 무엇이입니까?', why: '입니까 goes straight onto the noun, with no extra 이: 무엇입니까.' },
      ] },
    { id: 'tired', level: 1, en: 'I’m a bit tired today.', formal: '저는 오늘 좀 피곤합니다.', polite: '저는 오늘 좀 피곤해요.', casual: '나는 오늘 좀 피곤해.',
      words: ['feelings:tired', 'day:today'], scenes: ['friend', 'sibling', 'colleague'],
      traps: [
        { to: 'casual', text: '저는 오늘 좀 피곤해.', why: '저 is for polite speech. In 반말, “I” is 나: 나는 오늘 좀 피곤해.' },
        { to: 'casual', text: '나는 오늘 좀 피곤하.', why: '피곤하 is just the stem. 하다 words end in 해 in 반말: 피곤해요 → 피곤해.' },
        { to: 'formal', text: '나는 오늘 좀 피곤합니다.', why: '합니다체 goes with 저, not 나: 저는 오늘 좀 피곤합니다.' },
      ] },
    { id: 'yes-good', level: 1, en: 'Yes, sounds good.', formal: '네, 좋습니다.', polite: '네, 좋아요.', casual: '응, 좋아.',
      words: ['cafe:yes', 'feelings:good'], scenes: ['friend', 'chat', 'interview'],
      note: '반말 says 응 for “yes” (네 when you’re polite).',
      traps: [
        { to: 'casual', text: '네, 좋아.', why: '네 is the polite “yes”. With a friend it’s 응: 응, 좋아.' },
        { to: 'casual', text: '응, 좋아요.', why: '응 is 반말, but 좋아요 still ends in the polite 요. Take it off: 응, 좋아.' },
        { to: 'formal', text: '응, 좋습니다.', why: '응 is the casual “yes”; 합니다체 needs 네.' },
      ] },
    { id: 'no-thanks', level: 1, en: 'No thanks, I’m fine.', formal: '아니요, 괜찮습니다.', polite: '아니요, 괜찮아요.', casual: '아니, 괜찮아.',
      words: ['cafe:no', 'cafe:okay'], scenes: ['interview', 'friend', 'sibling'],
      note: '반말 says 아니 for “no” (아니요 when you’re polite).',
      traps: [
        { to: 'casual', text: '아니요, 괜찮아.', why: '아니요 is the polite “no”. In 반말 it’s 아니: 아니, 괜찮아.' },
        { to: 'casual', text: '아니, 괜찮.', why: '괜찮 is only the stem. Take off just the 요: 괜찮아요 → 괜찮아.' },
        { to: 'formal', text: '아니요, 괜찮아습니다.', why: '-습니다 goes on the stem 괜찮, not on 괜찮아: 괜찮습니다.' },
      ] },
    { id: 'who', level: 1, en: 'Who is this person?', formal: '이 사람은 누구입니까?', polite: '이 사람은 누구예요?', casual: '이 사람은 누구야?',
      words: ['people:person', 'people:who'], scenes: ['presentation', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '이 사람은 누구이야?', why: '누구 ends in a vowel, so “is” is just 야: 누구야.' },
        { to: 'casual', text: '이 사람은 누구예?', why: 'Taking 요 off 예요 doesn’t make 반말. After a vowel, the casual “is” is 야: 누구야.' },
        { to: 'formal', text: '이 사람은 누구습니까?', why: '-습니까 goes on verbs. After a noun, “is” is 입니까: 누구입니까.' },
      ] },
    { id: 'bread', level: 1, en: 'I eat bread in the morning.', formal: '저는 아침에 빵을 먹습니다.', polite: '저는 아침에 빵을 먹어요.', casual: '나는 아침에 빵을 먹어.',
      words: ['day:morning', 'cafe:bread', 'day:eat'], scenes: ['presentation', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '나는 아침에 빵을 먹.', why: '먹 is just the stem. Only 요 comes off: 먹어요 → 먹어.' },
        { to: 'casual', text: '저는 아침에 빵을 먹어.', why: '저 belongs to polite speech; in 반말, “I” is 나.' },
        { to: 'formal', text: '저는 아침에 빵을 먹읍니다.', why: 'After a consonant the ending is -습니다: 먹습니다.' },
        { to: 'formal', text: '나는 아침에 빵을 먹습니다.', why: '나 is casual; 합니다체 goes with 저: 저는 아침에 빵을 먹습니다.' },
      ] },
    { id: 'phone', level: 1, en: 'Where’s my phone?', formal: '제 핸드폰이 어디 있습니까?', polite: '제 핸드폰이 어디 있어요?', casual: '내 핸드폰이 어디 있어?',
      words: ['day:phone', 'directions:where', 'day:have'], scenes: ['sibling', 'friend', 'colleague'],
      traps: [
        { to: 'casual', text: '제 핸드폰이 어디 있어?', why: '제 is the polite “my”; in 반말 it’s 내: 내 핸드폰.' },
        { to: 'casual', text: '내 핸드폰이 어디 있?', why: '있 is just the stem: 있어요 → 있어.' },
        { to: 'formal', text: '내 핸드폰이 어디 있습니까?', why: '합니다체 needs 제 for “my”, not 내.' },
      ] },
    { id: 'home-seven', level: 1, en: 'I go home at seven.', formal: '저는 일곱 시에 집에 갑니다.', polite: '저는 일곱 시에 집에 가요.', casual: '나는 일곱 시에 집에 가.',
      words: ['day:home', 'day:go', 'numbers:seven', 'numbers:oclock'], scenes: ['presentation', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '저는 일곱 시에 집에 가.', why: '반말 with 저 mixes two levels: it’s 나는 일곱 시에 집에 가.' },
        { to: 'casual', text: '나는 일곱 시에 집에 가요.', why: '반말 has no 요 at the end: 나는 일곱 시에 집에 가.' },
        { to: 'formal', text: '저는 일곱 시에 집에 갑습니다.', why: 'After a vowel it’s just -ㅂ니다: 갑니다.' },
      ] },
    { id: 'doing-now', level: 1, en: 'What are you doing now?', formal: '지금 뭐 합니까?', polite: '지금 뭐 해요?', casual: '지금 뭐 해?',
      words: ['day:now', 'day:what', 'day:do'], scenes: ['chat', 'friend', 'colleague'],
      traps: [
        { to: 'casual', text: '지금 뭐 하?', why: '하 is just the stem. 하다 becomes 해 in 반말: 해요 → 해.' },
        { to: 'casual', text: '지금 뭐 하다?', why: '하다 is the dictionary form. A 반말 question is the 해요 form without 요: 뭐 해?' },
        { to: 'formal', text: '지금 뭐 해습니까?', why: '-ㅂ니까 goes on the stem 하: 합니까. It never goes on 해.' },
      ] },
    { id: 'hobby', level: 1, en: 'My hobby is playing the piano.', formal: '제 취미는 피아노입니다.', polite: '제 취미는 피아노예요.', casual: '내 취미는 피아노야.',
      words: ['hobbies:hobby', 'hobbies:piano'], scenes: ['interview', 'teacher', 'friend'],
      note: '“is” after a vowel: 예요 in 해요체, 야 in 반말 (피아노야). 합니다체 has 입니다 after any noun.',
      traps: [
        { to: 'casual', text: '내 취미는 피아노이야.', why: '피아노 ends in a vowel, so it’s just 야: 피아노야.' },
        { to: 'casual', text: '제 취미는 피아노야.', why: '제 is the polite “my”. In 반말, “my” is 내.' },
        { to: 'formal', text: '내 취미는 피아노입니다.', why: '합니다체 goes with the polite 제 for “my”: 제 취미는…' },
      ] },
    { id: 'station', level: 1, en: 'This stop is Seoul Station.', formal: '이번 역은 서울역입니다.', polite: '이번 역은 서울역이에요.', casual: '이번 역은 서울역이야.',
      words: ['directions:station'], scenes: ['announcement', 'stranger', 'friend'],
      traps: [
        { to: 'casual', text: '이번 역은 서울역야.', why: '역 ends in a consonant, so “is” is 이야: 서울역이야.' },
        { to: 'casual', text: '이번 역은 서울역이에.', why: '이에요 without 요 isn’t 반말. After a noun, the casual “is” is 이야.' },
        { to: 'formal', text: '이번 역은 서울역이입니다.', why: '입니다 goes straight onto the noun: 서울역입니다.' },
      ] },

    // ---------- Level 2: the past, requests, 있어요 / 없어요, negatives ----------
    { id: 'movie', level: 2, en: 'I watched a movie yesterday.', formal: '저는 어제 영화를 봤습니다.', polite: '저는 어제 영화를 봤어요.', casual: '나는 어제 영화를 봤어.',
      words: ['day:yesterday', 'day:movie', 'past:saw'], scenes: ['presentation', 'teacher', 'friend'],
      traps: [
        { to: 'casual', text: '나는 어제 영화를 봤.', why: 'Keep the 어: 봤어요 → 봤어. 봤 on its own isn’t a word.' },
        { to: 'casual', text: '저는 어제 영화를 봤어.', why: '저 goes with polite endings; 반말 needs 나.' },
        { to: 'formal', text: '저는 어제 영화를 봤어습니다.', why: '-습니다 goes on the past stem 봤, not on 봤어: 봤습니다.' },
      ] },
    { id: 'lunch', level: 2, en: 'Minsu, did you have lunch?', formal: '민수 씨, 점심 먹었습니까?', polite: '민수 씨, 점심 먹었어요?', casual: '민수야, 점심 먹었어?',
      words: ['day:lunch', 'past:ate'], scenes: ['friend', 'colleague'],
      note: 'In 반말 you call a friend by name + 야 after a vowel (민수야), or + 아 after a consonant (지훈아), not 씨. To someone older, 점심 드셨어요? is more polite.',
      traps: [
        { to: 'casual', text: '민수아, 점심 먹었어?', why: '민수 ends in a vowel, so it’s 민수야. 아 comes after a consonant: 지훈아.' },
        { to: 'casual', text: '민수야, 점심 먹었?', why: 'Keep the 어: 먹었어요 → 먹었어.' },
        { to: 'formal', text: '민수야, 점심 먹었습니까?', why: 'Name + 야 is 반말. With 합니다체, call him 민수 씨.' },
      ] },
    { id: 'family-sea', level: 2, en: 'My family went to the sea last summer.', formal: '저희 가족은 작년 여름에 바다에 갔습니다.', polite: '저희 가족은 작년 여름에 바다에 갔어요.', casual: '우리 가족은 작년 여름에 바다에 갔어.',
      words: ['people:family', 'past:lastyear', 'weather:summer', 'weather:sea'], scenes: ['presentation', 'teacher', 'friend'],
      note: 'Polite speech often uses the humble 저희 for “our” (저희 가족); 반말 uses 우리. (우리 가족 is fine in polite speech too.)',
      traps: [
        { to: 'casual', text: '저희 가족은 작년 여름에 바다에 갔어.', why: '저희 is the humble “our” of polite speech. With friends it’s 우리 가족.' },
        { to: 'casual', text: '우리 가족은 작년 여름에 바다에 갔.', why: 'Keep the 어: 갔어요 → 갔어.' },
        { to: 'formal', text: '저희 가족은 작년 여름에 바다에 갔어습니다.', why: '-습니다 goes on the past stem 갔, not on 갔어: 갔습니다.' },
      ] },
    { id: 'wait', level: 2, en: 'Please wait a moment.', formal: '조금만 기다려 주십시오.', polite: '조금만 기다려 주세요.', casual: '조금만 기다려 줘.',
      words: ['day:wait'], scenes: ['shop', 'sibling', 'friend'],
      note: '주세요 (“please, for me”) is 주십시오 in 합니다체 and 줘 in 반말.',
      traps: [
        { to: 'casual', text: '조금만 기다려 주세.', why: 'Taking 요 off 주세요 doesn’t make 반말. The casual “please” is 줘.' },
        { to: 'casual', text: '조금만 기다려 주.', why: '주 is just the stem. In 반말, 주세요 becomes 줘: 기다려 줘.' },
        { to: 'formal', text: '조금만 기다려 줍니다.', why: 'That’s a statement (“waits for me”), not a request. The formal request is 주십시오.' },
      ] },
    { id: 'water', level: 2, en: 'Some water, please.', formal: '물 좀 주십시오.', polite: '물 좀 주세요.', casual: '물 좀 줘.',
      words: ['cafe:water', 'cafe:please'], scenes: ['shop', 'sibling', 'friend'],
      note: '좀 (“a little”) makes a request softer, at every level.',
      traps: [
        { to: 'casual', text: '물 좀 주세.', why: '주세요 without 요 isn’t 반말: it’s 줘.' },
        { to: 'casual', text: '물 좀 주.', why: '주 is just the stem. 주 + 어 becomes 줘: 물 좀 줘.' },
        { to: 'formal', text: '물 좀 줘십시오.', why: '-(으)십시오 goes on the stem 주, not on 줘: 주십시오.' },
      ] },
    { id: 'come-here', level: 2, en: 'Please come over here.', formal: '여기로 오십시오.', polite: '여기로 오세요.', casual: '여기로 와.',
      words: ['directions:here', 'day:come'], scenes: ['child', 'sibling', 'stranger'],
      note: 'A request is -(으)십시오 in 합니다체 and -(으)세요 in 해요체. In 반말 it’s the plain 해요 form without 요: 와요 → 와.',
      traps: [
        { to: 'casual', text: '여기로 오세.', why: 'Taking 요 off 오세요 doesn’t work. A 반말 request is 와요 without 요: 와.' },
        { to: 'casual', text: '여기로 오아.', why: '오 + 아 always shortens to 와: 여기로 와.' },
        { to: 'formal', text: '여기로 와십시오.', why: '-(으)십시오 goes on the stem 오: 오십시오.' },
      ] },
    { id: 'no-umbrella', level: 2, en: 'No, I don’t have an umbrella.', formal: '아니요, 우산이 없습니다.', polite: '아니요, 우산이 없어요.', casual: '아니, 우산이 없어.',
      words: ['weather:umbrella', 'day:nothave', 'cafe:no'], scenes: ['friend', 'sibling', 'teacher'],
      traps: [
        { to: 'casual', text: '아니요, 우산이 없어.', why: '아니요 is the polite “no”; with 반말 it’s 아니.' },
        { to: 'casual', text: '아니, 우산이 없.', why: '없 is just the stem: 없어요 → 없어.' },
        { to: 'formal', text: '아니요, 우산이 없어습니다.', why: '-습니다 goes on the stem 없, not on 없어: 없습니다.' },
      ] },
    { id: 'company', level: 2, en: 'I’m not going to the office tomorrow.', formal: '저는 내일 회사에 안 갑니다.', polite: '저는 내일 회사에 안 가요.', casual: '나는 내일 회사에 안 가.',
      words: ['day:tomorrow', 'day:company', 'day:go'], scenes: ['colleague', 'friend'],
      note: '안 (“not”) goes before the verb and stays the same at every level: 안 갑니다, 안 가요, 안 가.',
      traps: [
        { to: 'casual', text: '저는 내일 회사에 안 가.', why: '저 doesn’t go with 반말: 나는 내일 회사에 안 가.' },
        { to: 'casual', text: '나는 내일 회사에 안 가다.', why: '가다 is the dictionary form. 반말 is 가요 without 요: 안 가.' },
        { to: 'formal', text: '나는 내일 회사에 안 갑니다.', why: '합니다체 goes with 저, not 나: 저는 내일 회사에 안 갑니다.' },
      ] },
    { id: 'no-coffee', level: 2, en: 'I don’t drink coffee.', formal: '저는 커피를 안 마십니다.', polite: '저는 커피를 안 마셔요.', casual: '나는 커피를 안 마셔.',
      words: ['cafe:coffee', 'day:drink'], scenes: ['interview', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '나는 커피를 안 마시.', why: '마시 is just the stem. 마셔요 without 요 is 마셔.' },
        { to: 'casual', text: '저는 커피를 안 마셔.', why: '저 is polite; in 반말, “I” is 나.' },
        { to: 'formal', text: '저는 커피를 안 마시습니다.', why: 'After a vowel it’s -ㅂ니다: 마십니다.' },
      ] },
    { id: 'swim', level: 2, en: 'I can’t swim.', formal: '저는 수영을 못합니다.', polite: '저는 수영을 못해요.', casual: '나는 수영을 못해.',
      words: ['hobbies:swim'], scenes: ['stranger', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '저는 수영을 못해.', why: '반말 needs 나, not 저: 나는 수영을 못해.' },
        { to: 'casual', text: '나는 수영을 못하.', why: '못하 is just the stem. 하다 words end in 해 in 반말: 못해요 → 못해.' },
        { to: 'formal', text: '저는 수영을 못해습니다.', why: '-ㅂ니다 goes on the stem 못하, not on 못해: 못합니다.' },
      ] },
    { id: 'was-fun', level: 2, en: 'Yes, it was fun.', formal: '네, 재미있었습니다.', polite: '네, 재미있었어요.', casual: '응, 재미있었어.',
      words: ['past:wasfun', 'cafe:yes'], scenes: ['friend', 'chat', 'colleague'],
      traps: [
        { to: 'casual', text: '네, 재미있었어.', why: '네 is the polite “yes”. In 반말 it’s 응.' },
        { to: 'casual', text: '응, 재미있었.', why: 'Keep the 어: 재미있었어요 → 재미있었어.' },
        { to: 'formal', text: '네, 재미있었어습니다.', why: '-습니다 goes on the past stem 재미있었: 재미있었습니다.' },
      ] },
    { id: 'sunday', level: 2, en: 'Yesterday was Sunday.', formal: '어제는 일요일이었습니다.', polite: '어제는 일요일이었어요.', casual: '어제는 일요일이었어.',
      words: ['day:yesterday', 'numbers:sunday'], scenes: ['friend', 'colleague'],
      note: '“was” after a noun: 이었어요 after a consonant (일요일이었어요), 였어요 after a vowel (친구였어요). 반말 just drops the 요.',
      traps: [
        { to: 'casual', text: '어제는 일요일였어.', why: '일요일 ends in a consonant, so it’s 이었어. 였어 comes after a vowel.' },
        { to: 'casual', text: '어제는 일요일이었.', why: 'Keep the 어: 이었어요 → 이었어.' },
        { to: 'formal', text: '어제는 일요일였습니다.', why: 'After a consonant it’s 이었습니다: 일요일이었습니다.' },
      ] },
    { id: 'dont-worry', level: 2, en: 'Don’t worry.', formal: '걱정하지 마십시오.', polite: '걱정하지 마세요.', casual: '걱정하지 마.',
      words: ['feelings:dontworry'], scenes: ['sibling', 'friend', 'stranger'],
      note: '“Don’t…” is -지 마십시오 / -지 마세요 / -지 마. (-지 않아요 means “doesn’t”: a statement, not a request.)',
      traps: [
        { to: 'casual', text: '걱정하지 마세.', why: 'Taking 요 off 마세요 doesn’t make 반말: it’s 걱정하지 마.' },
        { to: 'casual', text: '걱정하지 않아.', why: 'That means “I don’t worry”. To tell someone not to do something, use -지 마.' },
        { to: 'formal', text: '걱정하지 않습니다.', why: 'That’s a statement (“I don’t worry”). “Don’t…” in 합니다체 is -지 마십시오.' },
      ] },
    { id: 'sibling', level: 2, en: 'Yes, I have a younger brother.', formal: '네, 동생이 있습니다.', polite: '네, 동생이 있어요.', casual: '응, 동생이 있어.',
      words: ['people:sibling', 'day:have', 'cafe:yes'], scenes: ['interview', 'stranger', 'friend'],
      traps: [
        { to: 'casual', text: '네, 동생이 있어.', why: '반말 says 응 for “yes”, not 네.' },
        { to: 'casual', text: '응, 동생이 있.', why: '있 is just the stem. Only 요 comes off: 있어요 → 있어.' },
        { to: 'formal', text: '응, 동생이 있습니다.', why: '응 is 반말; in 합니다체, “yes” is 네.' },
      ] },
    { id: 'rain', level: 2, en: 'It’s going to rain tomorrow.', formal: '내일은 비가 옵니다.', polite: '내일은 비가 와요.', casual: '내일은 비가 와.',
      words: ['weather:raining', 'day:tomorrow'], scenes: ['news', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '내일은 비가 오아.', why: '오 + 아 always shortens to 와: 비가 와.' },
        { to: 'casual', text: '내일은 비가 오다.', why: '오다 is the dictionary form, not 반말: 와요 → 와.' },
        { to: 'formal', text: '내일은 비가 와습니다.', why: '-ㅂ니다 goes on the stem 오: 옵니다.' },
      ] },

    // ---------- Level 3: “let’s”, irregular verbs, longer sentences ----------
    { id: 'lunch-together', level: 3, en: 'Let’s have lunch together tomorrow.', formal: '내일 같이 점심을 먹읍시다.', polite: '내일 같이 점심을 먹어요.', casual: '내일 같이 점심을 먹자.',
      words: ['day:together', 'day:lunch', 'day:eat'], scenes: ['colleague', 'friend', 'chat'],
      note: '“Let’s” is -(으)ㅂ시다, the plain 해요 form (먹어요 can mean “let’s eat”), or -자. -(으)ㅂ시다 sounds like someone leading a group, so don’t use it to an older person: 같이 먹어요 is safer.',
      traps: [
        { to: 'casual', text: '내일 같이 점심을 먹어자.', why: '-자 goes straight onto the stem: 먹자, not 먹어 + 자.' },
        { to: 'formal', text: '내일 같이 점심을 먹습시다.', why: 'There’s no -습시다: after a consonant, “let’s” is -읍시다 (먹읍시다).' },
      ] },
    { id: 'movie-weekend', level: 3, en: 'If you’re free, let’s all see a movie together this weekend.', formal: '시간이 있으면 이번 주말에 다 같이 영화를 봅시다.', polite: '시간이 있으면 이번 주말에 다 같이 영화를 봐요.', casual: '시간이 있으면 이번 주말에 다 같이 영화를 보자.',
      words: ['day:weekend', 'day:movie', 'day:together'], scenes: ['friend', 'chat', 'colleague'],
      note: 'Only the end of the sentence changes: 있으면 (“if you have”) stays the same at every level. 봅시다 suits a suggestion to a group (다 같이, “all together”).',
      traps: [
        { to: 'casual', text: '시간이 있으면 이번 주말에 다 같이 영화를 봐자.', why: '-자 goes on the stem 보: 보자.' },
        { to: 'formal', text: '시간이 있으면 이번 주말에 다 같이 영화를 보읍시다.', why: 'After a vowel, “let’s” is -ㅂ시다, joined to the stem: 봅시다.' },
      ] },
    { id: 'live', level: 3, en: 'I live in Seoul.', formal: '저는 서울에 삽니다.', polite: '저는 서울에 살아요.', casual: '나는 서울에 살아.',
      words: ['people:live'], scenes: ['interview', 'stranger', 'child'],
      note: 'ㄹ-dropping: before -ㅂ니다 the ㄹ of 살다 drops (삽니다), like 알다 → 압니다 and 만들다 → 만듭니다. 살아요 and 살아 keep it.',
      traps: [
        { to: 'casual', text: '저는 서울에 살아.', why: '저 goes with polite speech; in 반말 it’s 나는.' },
        { to: 'casual', text: '나는 서울에 살.', why: '살 is just the stem: 살아요 → 살아.' },
        { to: 'formal', text: '저는 서울에 살습니다.', why: 'With a ㄹ verb, the ㄹ drops and -ㅂ니다 goes on: 삽니다.' },
      ] },
    { id: 'make-bread', level: 3, en: 'I make bread at the weekend.', formal: '저는 주말에 빵을 만듭니다.', polite: '저는 주말에 빵을 만들어요.', casual: '나는 주말에 빵을 만들어.',
      words: ['day:weekend', 'cafe:bread', 'past:made'], scenes: ['presentation', 'colleague', 'friend'],
      traps: [
        { to: 'casual', text: '나는 주말에 빵을 만들.', why: '만들 is just the stem: 만들어요 → 만들어.' },
        { to: 'casual', text: '저는 주말에 빵을 만들어.', why: '반말 needs 나, not 저.' },
        { to: 'formal', text: '저는 주말에 빵을 만들습니다.', why: 'The ㄹ drops before -ㅂ니다: 만듭니다.' },
        { to: 'formal', text: '나는 주말에 빵을 만듭니다.', why: '나 is 반말; 합니다체 needs 저.' },
      ] },
    { id: 'far', level: 3, en: 'The station is far from here.', formal: '역은 여기에서 멉니다.', polite: '역은 여기에서 멀어요.', casual: '역은 여기에서 멀어.',
      words: ['directions:station', 'directions:far', 'directions:here'], scenes: ['stranger', 'friend'],
      traps: [
        { to: 'casual', text: '역은 여기에서 멀.', why: '멀 is just the stem: 멀어요 → 멀어.' },
        { to: 'casual', text: '역은 여기에서 멉어.', why: '멉 only comes before -ㅂ니다 (멉니다). 반말 is 멀어요 without 요: 멀어.' },
        { to: 'formal', text: '역은 여기에서 멀습니다.', why: 'The ㄹ drops before -ㅂ니다: 멉니다.' },
      ] },
    { id: 'cold', level: 3, en: 'It’s very cold today.', formal: '오늘은 날씨가 아주 춥습니다.', polite: '오늘은 날씨가 아주 추워요.', casual: '오늘은 날씨가 아주 추워.',
      words: ['weather:cold', 'weather:weather', 'day:today'], scenes: ['news', 'colleague', 'friend'],
      note: 'ㅂ-irregular: 춥다 keeps its ㅂ before -습니다 (춥습니다), but before 어 the ㅂ becomes 우: 추워요, 추워.',
      traps: [
        { to: 'casual', text: '오늘은 날씨가 아주 춥어.', why: '춥다 is ㅂ-irregular: 춥 + 어 becomes 추워.' },
        { to: 'casual', text: '오늘은 날씨가 아주 춥.', why: 'Only 요 comes off: 추워요 → 추워.' },
        { to: 'formal', text: '오늘은 날씨가 아주 추웁니다.', why: 'Before -습니다 the ㅂ stays as it is: 춥습니다.' },
      ] },
    { id: 'nice-to-meet', level: 3, en: 'Nice to meet you.', formal: '만나서 반갑습니다.', polite: '만나서 반가워요.', casual: '만나서 반가워.',
      words: ['people:nicetomeet'], scenes: ['presentation', 'child'],
      note: '반갑다 is ㅂ-irregular, like 춥다: 반갑습니다, but 반가워요 and 반가워.',
      traps: [
        { to: 'casual', text: '만나서 반갑어.', why: 'ㅂ-irregular: 반갑 + 어 becomes 반가워.' },
        { to: 'formal', text: '만나서 반가웁니다.', why: 'The ㅂ stays before -습니다: 반갑습니다.' },
      ] },
    { id: 'thanks-gift', level: 3, en: 'Thanks for the present.', formal: '선물 고맙습니다.', polite: '선물 고마워요.', casual: '선물 고마워.',
      words: ['shopping:gift', 'cafe:thanks'], scenes: ['friend', 'sibling'],
      note: '고맙다 is ㅂ-irregular: 고맙습니다, but 고마워요 and 고마워. With friends, 고마워 is the everyday “thanks”.',
      traps: [
        { to: 'casual', text: '선물 고맙어.', why: 'ㅂ-irregular: 고맙 + 어 becomes 고마워.' },
        { to: 'formal', text: '선물 고마워습니다.', why: '-습니다 goes on the stem 고맙: 고맙습니다.' },
      ] },
    { id: 'dont-know', level: 3, en: 'I don’t really know either.', formal: '저도 잘 모릅니다.', polite: '저도 잘 몰라요.', casual: '나도 잘 몰라.',
      words: ['past:didntknow'], scenes: ['stranger', 'colleague', 'friend'],
      note: '르-irregular: 모르다 → 모릅니다, but 몰라요 and 몰라, with an extra ㄹ. 저도 (“me too”) becomes 나도.',
      traps: [
        { to: 'casual', text: '저도 잘 몰라.', why: '저도 is polite. In 반말, “me too” is 나도.' },
        { to: 'casual', text: '나도 잘 모라.', why: '르-irregular: 모르 + 아 becomes 몰라, with an extra ㄹ.' },
        { to: 'formal', text: '저도 잘 몰릅니다.', why: 'The extra ㄹ only comes before 아 (몰라요). Before -ㅂ니다 it’s 모릅니다.' },
        { to: 'formal', text: '저도 잘 모르습니다.', why: 'After a vowel it’s -ㅂ니다: 모릅니다.' },
      ] },
    { id: 'sing', level: 3, en: 'My little sister sings really well.', formal: '제 동생은 노래를 정말 잘 부릅니다.', polite: '제 동생은 노래를 정말 잘 불러요.', casual: '내 동생은 노래를 정말 잘 불러.',
      words: ['hobbies:sing', 'hobbies:song', 'people:sibling'], scenes: ['presentation', 'colleague', 'friend'],
      note: '르-irregular: 부르다 → 부릅니다, but 불러요 and 불러, with an extra ㄹ.',
      traps: [
        { to: 'casual', text: '내 동생은 노래를 정말 잘 부러.', why: '르-irregular: 부르 + 어 becomes 불러, with an extra ㄹ.' },
        { to: 'casual', text: '제 동생은 노래를 정말 잘 불러.', why: '제 is the polite “my”; in 반말 it’s 내 동생.' },
        { to: 'formal', text: '제 동생은 노래를 정말 잘 불릅니다.', why: 'The extra ㄹ only comes before 어 (불러요). Before -ㅂ니다 it’s 부릅니다.' },
      ] },
    { id: 'get-off', level: 3, en: 'Please get off at the next station.', formal: '다음 역에서 내리십시오.', polite: '다음 역에서 내리세요.', casual: '다음 역에서 내려.',
      words: ['directions:getoff', 'directions:station'], scenes: ['stranger', 'friend'],
      traps: [
        { to: 'casual', text: '다음 역에서 내리세.', why: 'Taking 요 off 내리세요 doesn’t make 반말: it’s 내려.' },
        { to: 'casual', text: '다음 역에서 내리.', why: '내리 is just the stem. 내리 + 어 becomes 내려.' },
        { to: 'formal', text: '다음 역에서 내려십시오.', why: '-(으)십시오 goes on the stem 내리: 내리십시오.' },
      ] },
    { id: 'came-to-learn', level: 3, en: 'I came to Korea because I wanted to learn Korean.', formal: '저는 한국어를 배우고 싶어서 한국에 왔습니다.', polite: '저는 한국어를 배우고 싶어서 한국에 왔어요.', casual: '나는 한국어를 배우고 싶어서 한국에 왔어.',
      words: ['hobbies:wanttolearn', 'day:korean', 'past:came'], scenes: ['interview', 'stranger', 'friend'],
      note: 'Only the end of the sentence changes: 배우고 싶어서 (“because I wanted to learn”) is the same at every level.',
      traps: [
        { to: 'casual', text: '저는 한국어를 배우고 싶어서 한국에 왔어.', why: '저 and a 반말 ending don’t mix: 나는 한국어를…' },
        { to: 'casual', text: '나는 한국어를 배우고 싶어서 한국에 왔.', why: 'Keep the 어: 왔어요 → 왔어.' },
        { to: 'formal', text: '나는 한국어를 배우고 싶어서 한국에 왔습니다.', why: '나 is 반말; with 합니다체, say 저는.' },
      ] },
    { id: 'sorry-busy', level: 3, en: 'Sorry, I was busy yesterday, so I couldn’t call.', formal: '죄송합니다. 어제 바빠서 전화를 못 했습니다.', polite: '미안해요. 어제 바빠서 전화를 못 했어요.', casual: '미안해. 어제 바빠서 전화를 못 했어.',
      words: ['feelings:sorry', 'feelings:busy'], scenes: ['friend', 'sibling'],
      note: '합니다체 usually says sorry with the humbler 죄송합니다; with friends, “sorry” is 미안해. 바빠서 (“because I was busy”) stays the same at every level.',
      traps: [
        { to: 'casual', text: '미안해요. 어제 바빠서 전화를 못 했어.', why: 'Both sentences need 반말: 미안해요 still ends in the polite 요.' },
        { to: 'casual', text: '미안해. 어제 바빠서 전화를 못 했.', why: 'Keep the 어: 했어요 → 했어.' },
        { to: 'formal', text: '죄송합니다. 어제 바빠서 전화를 못 했어습니다.', why: '-습니다 goes on the past stem 했: 했습니다.' },
      ] },
    { id: 'weekend-rest', level: 3, en: 'At the weekend I read a book at home and rested.', formal: '저는 주말에 집에서 책을 읽고 쉬었습니다.', polite: '저는 주말에 집에서 책을 읽고 쉬었어요.', casual: '나는 주말에 집에서 책을 읽고 쉬었어.',
      words: ['day:weekend', 'day:read', 'day:rest'], scenes: ['presentation', 'teacher', 'friend'],
      note: 'Only the last verb takes the level’s ending: 읽고 (“read, and”) stays the same.',
      traps: [
        { to: 'casual', text: '저는 주말에 집에서 책을 읽고 쉬었어.', why: '반말 needs 나, not 저: 나는 주말에…' },
        { to: 'casual', text: '나는 주말에 집에서 책을 읽고 쉬었.', why: 'Keep the 어: 쉬었어요 → 쉬었어.' },
        { to: 'formal', text: '저는 주말에 집에서 책을 읽습니다고 쉬었습니다.', why: 'Only the last verb takes -습니다: 읽고 stays as it is.' },
      ] },
    { id: 'music', level: 3, en: 'I listen to music every day.', formal: '저는 매일 음악을 듣습니다.', polite: '저는 매일 음악을 들어요.', casual: '나는 매일 음악을 들어.',
      words: ['hobbies:listen', 'hobbies:music', 'day:everyday'], scenes: ['interview', 'stranger', 'friend'],
      note: 'ㄷ-irregular: 듣다 keeps its ㄷ before -습니다 (듣습니다), but before 어 the ㄷ becomes ㄹ: 들어요, 들어.',
      traps: [
        { to: 'casual', text: '나는 매일 음악을 듣어.', why: 'ㄷ-irregular: 듣 + 어 becomes 들어.' },
        { to: 'casual', text: '저는 매일 음악을 들어.', why: '저 goes with 해요체 and 합니다체; in 반말 it’s 나.' },
        { to: 'formal', text: '저는 매일 음악을 들습니다.', why: 'The ㄷ only turns into ㄹ before a vowel: 듣습니다.' },
      ] },
  ],
});
