/**
 * Topic: 교통과 여행 · Travel & transport — tickets, the subway, taxis, the airport and the hotel.
 * Verbs are listed in the polite present form (해요체) with the dictionary form
 * alongside; 놓쳤어요 (missed) is taught in the past, the form you really need,
 * with `form: 'past'` as in content/past.js. The subway, bus and taxi words
 * themselves are in directions.js and are used here as 'directions:…'.
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'travel',
  order: 11,
  emoji: '🚄',
  color: 'pink',
  title: { ko: '교통과 여행', en: 'Travel & transport' },
  description: { ko: '표 사기 · 지하철 · 택시', en: 'Tickets, the subway, a taxi' },

  notes: [
    {
      title: { ko: '표 두 장 주세요', en: 'Buying tickets' },
      text: 'Say where you’re going with **까지** (to, as far as), then how many. Tickets are counted with **장** and native numbers: **한 장, 두 장, 세 장**. To choose a **편도** (one-way) or **왕복** (return) ticket, or a **창가** (window) seat, add **(으)로 주세요**.',
      examples: [
        { ko: '부산까지 표 두 장 주세요.', en: 'Two tickets to Busan, please.' },
        { ko: '왕복으로 주세요.', en: 'A return ticket, please.' },
        { ko: '창가 자리로 주세요.', en: 'A window seat, please.' },
      ],
    },
    {
      title: { ko: '이호선으로 갈아타세요', en: 'Taking the subway' },
      text: 'Subway lines are Sino-Korean numbers + **호선**: **일호선** (Line 1), **이호선** (Line 2). What you ride takes 을/를: **이호선을 타세요**. The station where you get off or change takes **에서**, and the line you change to takes **(으)로**. At the gates, you tap your **교통카드**: **찍어요**.',
      examples: [
        { ko: '지하철 이호선을 타세요.', en: 'Take subway Line 2.' },
        { ko: '시청역에서 일호선으로 갈아타세요.', en: 'Change to Line 1 at City Hall Station.' },
        { ko: '교통카드를 찍으세요.', en: 'Tap your transport card.' },
      ],
    },
    {
      title: { ko: '(으)로 가 주세요', en: 'In a taxi' },
      text: 'Tell the driver where to go with **(으)로 가 주세요** or **까지 가 주세요**. To get out, say **여기서 세워 주세요** (please stop here). Call the driver **기사님**: it’s polite, and it works on the bus too.',
      examples: [
        { ko: '서울역으로 가 주세요.', en: 'Seoul Station, please.' },
        { ko: '기사님, 여기서 세워 주세요.', en: 'Could you stop here, please?' },
        { ko: '서울역까지 얼마나 걸려요?', en: 'How long does it take to Seoul Station?' },
      ],
    },
    {
      title: { ko: '벌써 출발했어요', en: 'Times, and running late' },
      text: 'Clock times take **에**: **몇 시에 출발해요?** (What time does it leave?) For what has already happened, Korean uses the past where English often says “has / have”: **벌써 출발했어요** (it has already left), **기차를 놓쳤어요** (I’ve missed the train), **예약했어요** (I have a booking).',
      examples: [
        { ko: '다음 기차는 몇 시에 출발해요?', en: 'What time does the next train leave?' },
        { ko: '어떡해요! 기차가 벌써 출발했어요.', en: 'Oh no! The train has already left.' },
        { ko: '김민수로 예약했어요.', en: 'I have a booking under Kim Minsu.' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'ticket', ko: '표', en: 'ticket', level: 1, pos: 'noun', emoji: '🎟️', rom: 'pyo', accept: ['티켓'], enAlt: ['tickets'],
      note: 'For the train, the bus or a film. Count tickets with 장: 표 두 장 = two tickets. A train ticket is 기차표.',
      example: { ko: '기차표 샀어요?', en: 'Have you bought the train tickets?' } },
    { id: 'train', ko: '기차', en: 'train', level: 1, pos: 'noun', emoji: '🚆', rom: 'gicha', accept: ['열차'],
      note: '“By train” is 기차로. Korea’s fast train, the KTX, gets from Seoul to Busan in under three hours.',
      example: { ko: '기차로 부산에 가요.', en: 'I’m going to Busan by train.' } },
    { id: 'plane', ko: '비행기', en: 'plane', level: 1, pos: 'noun', emoji: '✈️', rom: 'bihaenggi',
      enAlt: ['airplane', 'aeroplane', 'aircraft', 'flight'],
      note: '“Take a plane” is 비행기를 타요, and “by plane” is 비행기로. A plane ticket is 비행기표.',
      example: { ko: '비행기 몇 시예요?', en: 'What time is your flight?' } },
    { id: 'airport', ko: '공항', en: 'airport', level: 1, pos: 'noun', emoji: '🛫', rom: 'gonghang',
      note: '공 (air) + 항 (port). Seoul’s big international airport is 인천공항 (Incheon Airport).',
      example: { ko: '공항에 어떻게 가요?', en: 'How do I get to the airport?' } },
    { id: 'hotel', ko: '호텔', en: 'hotel', level: 1, pos: 'noun', emoji: '🏨', rom: 'hotel',
      note: 'After ㄹ, “to the hotel” takes 로, not 으로: 호텔로 가 주세요.',
      example: { ko: '호텔이 역 앞에 있어요.', en: 'The hotel is in front of the station.' } },
    { id: 'passport', ko: '여권', en: 'passport', level: 1, pos: 'noun', emoji: '🛂', rom: 'yeogwon', pron: '여꿘',
      note: 'It’s said [여꿘], with a tense ㄲ. At the airport you’ll hear 여권 보여 주세요: “Your passport, please.”',
      example: { ko: '여권 있어요?', en: 'Have you got your passport?' } },
    { id: 'luggage', ko: '짐', en: 'luggage', level: 1, pos: 'noun', emoji: '🛄', rom: 'jim', avoid: ['shopping:bag'],
      enAlt: ['baggage', 'bags'],
      note: 'Everything you carry on a trip. Packing is 짐을 싸요: this 싸다 means “wrap”, not “cheap”!',
      example: { ko: '짐이 많아요?', en: 'Do you have a lot of luggage?' } },
    { id: 'map', ko: '지도', en: 'map', level: 1, pos: 'noun', emoji: '🗺️', rom: 'jido',
      note: 'A map app is 지도 앱. To look something up on the map: 지도에서 찾아요.',
      example: { ko: '지도에서 호텔을 찾아요.', en: 'I’m looking for the hotel on the map.' } },
    { id: 'fast', ko: '빨라요', en: "it's fast", level: 1, pos: 'adjective', emoji: '⚡', rom: 'ppallayo', dict: '빠르다',
      enAlt: ['quick'],
      note: '르-irregular, like 몰라요: 르 turns into ㄹ라 → 빨라요. The opposite is 느려요 (it’s slow).',
      example: { ko: '기차가 정말 빨라요!', en: 'The train is really fast!' } },
    { id: 'slow', ko: '느려요', en: "it's slow", level: 1, pos: 'adjective', emoji: '🐢', rom: 'neuryeoyo', dict: '느리다',
      accept: ['느리어요'], avoid: ['slowly'],
      note: '느리 + 어요 → 느려요 (ㅣ + ㅓ merge into ㅕ). “Slowly” is 천천히.',
      example: { ko: '이 버스는 너무 느려요.', en: 'This bus is too slow.' } },
    { id: 'slowly', ko: '천천히', en: 'slowly', level: 1, pos: 'adverb', emoji: '🐌', rom: 'cheoncheonhi', avoid: ['slow'],
      note: 'Very handy when Korean is too fast for you: 천천히 말해 주세요 = please speak slowly.',
      example: { ko: '천천히 말해 주세요.', en: 'Please speak slowly.' } },
    { id: 'takemeto', ko: '가 주세요', en: 'please take me (to …)', level: 1, pos: 'phrase', emoji: '🚕💨', rom: 'ga juseyo',
      dict: '가다', avoid: ['cafe:togo'], enAlt: ['take me to', 'take me', 'please go', 'please take me there'],
      note: 'Say the place first: 서울역으로 가 주세요 or 서울역까지 가 주세요. 가 (go) + 주세요 (please, for me).',
      example: { ko: '서울역으로 가 주세요.', en: 'Seoul Station, please.' } },

    // ---- Level 2 ----
    { id: 'sheet', ko: '장', en: 'sheet (counter)', level: 2, pos: 'counter', emoji: '📄', rom: 'jang', avoid: ['ticket'],
      enAlt: ['sheets', 'flat things'],
      note: 'The counter for flat things like tickets, paper and photos, with native numbers: 한 장, 두 장, 세 장.',
      example: { ko: '사진 한 장 찍어 주세요.', en: 'Could you take a photo of us?' } },
    { id: 'line', ko: '호선', en: 'line (subway)', level: 2, pos: 'counter', emoji: '🟢', rom: 'hoseon',
      enAlt: ['subway line', 'metro line', 'train line'],
      note: 'Subway lines have numbers and colours: 이호선 (Line 2) is green. The numbers are Sino-Korean: 일호선, 이호선, 삼호선…',
      example: { ko: '몇 호선 타요?', en: 'Which line are you taking?' } },
    { id: 'transitcard', ko: '교통카드', en: 'transport card', level: 2, pos: 'noun', emoji: '🪪', rom: 'gyotongkadeu',
      avoid: ['shopping:card'], enAlt: ['transit card', 'travel card', 'metro card', 'bus card', 't-money', 'tmoney'],
      note: '교통 (transport) + 카드. You tap it on the bus and at the subway gates (교통카드를 찍어요), and top it up at a convenience store.',
      example: { ko: '교통카드 있어요?', en: 'Do you have a transport card?' } },
    { id: 'driver', ko: '기사님', en: 'driver (polite)', level: 2, pos: 'noun', emoji: '🚖', rom: 'gisanim',
      enAlt: ['taxi driver', 'bus driver'],
      note: 'The polite way to talk to a taxi or bus driver. 님 makes it respectful, as in 선생님.',
      example: { ko: '기사님, 감사합니다!', en: 'Thank you! (to the driver)' } },
    { id: 'expressbus', ko: '고속버스', en: 'express bus', level: 2, pos: 'noun', emoji: '🚍', rom: 'gosokbeoseu', pron: '고속뻐스',
      enAlt: ['intercity bus', 'coach', 'long-distance bus'],
      note: '고속 means “high-speed”: the fast bus between cities, leaving from a bus terminal. After ㄱ, the ㅂ gets tense: [고속뻐스].',
      example: { ko: '고속버스로 가요.', en: 'I’m taking the express bus.' } },
    { id: 'terminal', ko: '터미널', en: 'bus terminal', level: 2, pos: 'noun', emoji: '🚌🏢', rom: 'teomineol',
      avoid: ['directions:station'], enAlt: ['terminal', 'bus station', 'coach station'],
      note: 'Buses to other cities leave from a bus terminal: 고속버스 터미널. Airports have them too: 제1터미널 = Terminal 1.',
      example: { ko: '터미널에서 만나요.', en: 'Let’s meet at the terminal.' } },
    { id: 'checkin', ko: '체크인', en: 'check-in', level: 2, pos: 'noun', emoji: '🛎️', rom: 'chekeuin', enAlt: ['checkin'],
      note: 'At a hotel or the airport. The opposite is 체크아웃. At the front desk: 체크인해 주세요.',
      example: { ko: '체크인은 몇 시예요?', en: 'What time is check-in?' } },
    { id: 'book', ko: '예약해요', en: 'book / reserve', level: 2, pos: 'verb', emoji: '📲', rom: 'yeyakaeyo', pron: '예야캐요',
      dict: '예약하다', enAlt: ['make a reservation', 'make a booking'],
      note: '예약 (a booking) + 하다. Korean uses the past for a booking you have: 예약했어요. The ㄱ and ㅎ blend into ㅋ: [예야캐요].',
      example: { ko: '호텔을 예약했어요?', en: 'Have you booked the hotel?' } },
    { id: 'depart', ko: '출발해요', en: 'depart / set off', level: 2, pos: 'verb', emoji: '🚀', rom: 'chulbalhaeyo',
      dict: '출발하다', avoid: ['day:goout', 'day:go'], enAlt: ['leave', 'set out', 'start off'],
      note: '출발 (departure) + 하다. The opposite is 도착해요 (arrive). On tickets and boards you’ll see 출발 and 도착.',
      example: { ko: '버스가 곧 출발해요.', en: 'The bus is leaving soon.' } },
    { id: 'stophere', ko: '세워 주세요', en: 'please stop (the car)', level: 2, pos: 'phrase', emoji: '✋', rom: 'sewo juseyo',
      dict: '세우다', enAlt: ['please stop', 'stop here', 'please stop here', 'pull over', 'please pull over', 'stop the car'],
      note: '세우다 means “to stop (a car)”. In a taxi, say where: 여기서 세워 주세요 = please stop here.',
      example: { ko: '저기 편의점 앞에서 세워 주세요.', en: 'Please stop in front of that convenience store.' } },
    { id: 'heavy', ko: '무거워요', en: "it's heavy", level: 2, pos: 'adjective', emoji: '🪨', rom: 'mugeowoyo', dict: '무겁다',
      note: 'ㅂ-irregular, like 추워요: 무겁 + 어요 → 무거워요. The opposite is 가벼워요 (it’s light).',
      example: { ko: '가방이 너무 무거워요.', en: 'My bag is too heavy.' } },
    { id: 'comfortable', ko: '편해요', en: "it's comfortable / convenient", level: 2, pos: 'adjective', emoji: '🛌',
      rom: 'pyeonhaeyo', dict: '편하다', enAlt: ['comfy', "it's comfy"], avoid: ['work:easy'],
      note: 'For comfy seats and shoes, and for an easy, convenient way to get around: 지하철이 편해요. The opposite is 불편해요.',
      example: { ko: '이 신발은 정말 편해요.', en: 'These shoes are really comfortable.' } },
    { id: 'fare', ko: '요금', en: 'fare / charge', level: 2, pos: 'noun', emoji: '💲', rom: 'yogeum', enAlt: ['fee', 'charges'],
      note: 'What you pay for a ride or a service: 택시 요금 (taxi fare), 버스 요금. Late at night, taxi fares go up.',
      example: { ko: '버스 요금이 얼마예요?', en: 'How much is the bus fare?' } },

    // ---- Level 3 ----
    { id: 'seat', ko: '좌석', en: 'seat (on a train, plane…)', level: 3, pos: 'noun', emoji: '🪑', rom: 'jwaseok',
      note: 'The formal word for a seat, on tickets and signs: 좌석 번호 = seat number. In speech, people often just say 자리.',
      example: { ko: '좌석 번호가 몇 번이에요?', en: 'What’s your seat number?' } },
    { id: 'window', ko: '창가', en: 'by the window', level: 3, pos: 'noun', emoji: '🪟', rom: 'changga', pron: '창까',
      accept: ['창가 쪽'], avoid: ['seat'], enAlt: ['window seat', 'window side', 'window'],
      note: '창 (window) + 가 (edge), said [창까]. A window seat is 창가 자리; an aisle seat is 통로 쪽 자리.',
      example: { ko: '창가 자리 있어요?', en: 'Is there a window seat?' } },
    { id: 'oneway', ko: '편도', en: 'one-way', level: 3, pos: 'noun', emoji: '↗️', rom: 'pyeondo',
      enAlt: ['one way', 'single', 'single ticket', 'one-way ticket'],
      note: 'A ticket for one way only. The opposite is 왕복 (return).',
      example: { ko: '편도로 주세요.', en: 'One-way, please.' } },
    { id: 'return', ko: '왕복', en: 'return / round trip', level: 3, pos: 'noun', emoji: '🔃', rom: 'wangbok',
      enAlt: ['return ticket', 'round-trip ticket', 'there and back'],
      note: '왕 (going) + 복 (coming back): a ticket there and back. 왕복 얼마예요? = How much is a return?',
      example: { ko: '왕복으로 두 장 주세요.', en: 'Two return tickets, please.' } },
    { id: 'lasttrain', ko: '막차', en: 'last train (or bus)', level: 3, pos: 'noun', emoji: '🕛', rom: 'makcha',
      enAlt: ['last bus', 'the last train', 'last train of the day', 'last subway'],
      note: '막 (last, as in 막내, the youngest) + 차 (vehicle): the last train, subway or bus of the night. The first one is 첫차.',
      example: { ko: '막차가 몇 시예요?', en: 'What time is the last train?' } },
    { id: 'missed', ko: '놓쳤어요', en: 'missed (a train, bus…)', level: 3, pos: 'verb', emoji: '😰', rom: 'notchyeosseoyo',
      pron: '녿처써요', dict: '놓치다', form: 'past', accept: ['놓치었어요'],
      enAlt: ['missed it', 'missed the train', 'missed the bus'],
      note: '놓치다 → 놓치 + 었어요 → 놓쳤어요 (ㅣ + ㅓ merge into ㅕ). What you miss takes 을/를: 버스를 놓쳤어요.',
      example: { ko: '기차를 놓쳤어요!', en: 'I’ve missed the train!' } },
    { id: 'cancel', ko: '취소해요', en: 'cancel', level: 3, pos: 'verb', emoji: '✖️', rom: 'chwisohaeyo', dict: '취소하다',
      note: '취소 (cancellation) + 하다. What you cancel takes 을/를: 예약을 취소해요.',
      example: { ko: '호텔 예약을 취소했어요.', en: 'I cancelled the hotel booking.' } },
    { id: 'traffic', ko: '길이 막혀요', en: 'the traffic is bad', level: 3, pos: 'phrase', emoji: '🚗', rom: 'giri makyeoyo',
      pron: '기리 마켜요', accept: ['길 막혀요', '차가 막혀요', '차 막혀요'],
      enAlt: ['traffic jam', 'heavy traffic', 'the traffic is heavy', 'the roads are jammed'],
      note: 'Literally “the road is blocked” (막히다). You’ll also hear 차가 막혀요. At rush hour, the subway is often faster.',
      example: { ko: '출근 시간에는 길이 막혀요.', en: 'The roads are jammed in the morning rush hour.' } },
    { id: 'exchange', ko: '환전', en: 'currency exchange', level: 3, pos: 'noun', emoji: '💱', rom: 'hwanjeon',
      avoid: ['shopping:change'], enAlt: ['money exchange', 'changing money', 'foreign exchange'],
      note: 'Changing money into won (or back): 환전해요. Banks and the airport do it, and so do exchange shops in tourist areas.',
      example: { ko: '공항에서 환전했어요.', en: 'I changed money at the airport.' } },
    { id: 'stay', ko: '숙소', en: 'place to stay', level: 3, pos: 'noun', emoji: '🗝️', rom: 'sukso', pron: '숙쏘',
      avoid: ['hotel', 'day:room'], enAlt: ['accommodation', 'lodging', 'somewhere to stay', 'where you stay'],
      note: 'Anywhere you stay on a trip: a hotel, a guesthouse… After ㄱ, the ㅅ gets tense: [숙쏘].',
      example: { ko: '숙소는 어디예요?', en: 'Where are you staying?' } },
    { id: 'crowded', ko: '복잡해요', en: "it's crowded", level: 3, pos: 'adjective', emoji: '🧑‍🤝‍🧑', rom: 'bokjapaeyo',
      pron: '복짜패요', dict: '복잡하다', enAlt: ['busy', 'packed', "it's complicated", 'complicated'],
      note: 'For places full of people or cars: 지하철이 복잡해요. It also means “complicated”: 이 지도는 너무 복잡해요.',
      example: { ko: '주말에는 공항이 정말 복잡해요.', en: 'The airport is really crowded at weekends.' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-airport', en: 'I’m going to the airport by train.', ko: '공항에 기차로 가요.',
      tiles: ['공항에', '기차로', '가요'], gloss: ['to the airport', 'by train', 'go'], words: ['airport', 'train', 'day:go'],
      alts: [['기차로', '공항에', '가요']],
      traps: [
        { tile: '공항에서', why: '에 marks where you are going. 공항에서 would mean “from the airport”.' },
        { tile: '기차를', why: 'To say how you travel, use (으)로: 기차로 가요 = I go by train.' },
      ] },
    { id: 's-passport', en: 'Here’s my passport.', ko: '여권 여기 있어요.',
      tiles: ['여권', '여기', '있어요'], gloss: ['passport', 'here', 'is (there)'], words: ['passport', 'directions:here', 'day:have'],
      alts: [['여기', '여권', '있어요']],
      traps: [{ tile: '저기', why: '저기 means “over there”. When you hand something over, say 여기 있어요 (here it is).' }] },
    { id: 's-fastslow', en: 'The plane is fast. The train is a bit slow.', ko: '비행기는 빨라요. 기차는 좀 느려요.',
      tiles: ['비행기는', '빨라요', '기차는', '좀', '느려요'], gloss: ['plane (topic)', 'is fast', 'train (topic)', 'a bit', 'is slow'],
      words: ['plane', 'fast', 'train', 'slow'],
      traps: [{ tile: '빠라요', why: '빠르다 is 르-irregular: 르 turns into ㄹ라 → 빨라요.' }] },
    { id: 's-slowly', en: 'Please drive slowly.', ko: '천천히 가 주세요.',
      tiles: ['천천히', '가', '주세요'], gloss: ['slowly', 'go', 'please (for me)'], words: ['slowly', 'takemeto'],
      traps: [{ tile: '빨리', why: '빨리 means “quickly”. “Slowly” is 천천히.' }] },
    { id: 's-hotel', en: 'To the hotel, please.', ko: '호텔로 가 주세요.',
      tiles: ['호텔로', '가', '주세요'], gloss: ['to the hotel', 'go', 'please (for me)'], words: ['hotel', 'takemeto'],
      traps: [
        { tile: '호텔으로', why: 'After ㄹ, use 로, not 으로: 호텔로.' },
        { tile: '호텔에서', why: '에서 would mean “from the hotel”. To say where to go, use (으)로: 호텔로 가 주세요.' },
      ] },
    { id: 's-ticket', en: 'Where do I buy a ticket?', ko: '표 어디서 사요?',
      tiles: ['표', '어디서', '사요'], gloss: ['ticket', 'where (at)', 'buy'], words: ['ticket', 'directions:where', 'shopping:buy'],
      alts: [['어디서', '표', '사요']],
      traps: [{ tile: '어디에', why: 'Buying is something you do there, so “where” takes 에서: 어디서 (short for 어디에서). 어디에 is for where you go or where something is.' }] },
    { id: 's-map', en: 'Do you have a map?', ko: '지도 있어요?',
      tiles: ['지도', '있어요'], gloss: ['map', 'is there? / do you have?'], words: ['map', 'day:have'],
      traps: [{ tile: '지도를', why: '있어요 says that something is there, so it never takes 을/를: 지도 있어요? (or 지도가 있어요?)' }] },

    // ---- Level 2 ----
    { id: 's-twotickets', level: 2, en: 'Two tickets, please.', ko: '표 두 장 주세요.',
      tiles: ['표', '두', '장', '주세요'], gloss: ['ticket', 'two', 'sheets (counter)', 'please give'],
      words: ['ticket', 'cafe:two', 'sheet', 'cafe:please'],
      traps: [
        { tile: '둘', why: 'Before a counter like 장, 둘 shortens to 두: 두 장.' },
        { tile: '이', why: 'Tickets are counted with native Korean numbers: 두 장, not 이 장.' },
        { tile: '잔', why: '잔 counts cups and glasses. Tickets and other flat things take 장.' },
      ] },
    { id: 's-depart', level: 2, en: 'What time does the train leave?', ko: '기차가 몇 시에 출발해요?',
      tiles: ['기차가', '몇', '시에', '출발해요'], gloss: ['train (subject)', 'what (number)', 'at … o’clock', 'leave'],
      words: ['train', 'numbers:howmany', 'numbers:oclock', 'depart'], alts: [['몇', '시에', '기차가', '출발해요']],
      traps: [
        { tile: '도착해요', why: '도착해요 means “arrive”. “Leave / depart” is 출발해요.' },
        { tile: '시에서', why: 'Clock times take 에: 몇 시에 (at what time).' },
      ] },
    { id: 's-stop', level: 2, en: 'Driver, please stop here.', ko: '기사님, 여기서 세워 주세요.',
      tiles: ['기사님', '여기서', '세워', '주세요'], gloss: ['driver (polite)', 'here', 'stop (the car)', 'please (for me)'],
      words: ['driver', 'directions:here', 'stophere'],
      traps: [{ tile: '가', why: '가 주세요 means “please go / take me”. To stop the car, say 세워 주세요.' }] },
    { id: 's-fare', level: 2, en: 'How much is the taxi fare?', ko: '택시 요금이 얼마예요?',
      tiles: ['택시', '요금이', '얼마예요'], gloss: ['taxi', 'fare (subject)', 'how much is it?'],
      words: ['directions:taxi', 'fare', 'cafe:howmuch'],
      traps: [{ tile: '요금을', why: '요금 is what you’re asking about (the subject of 얼마예요?), so it takes 이: 요금이 얼마예요?' }] },
    { id: 's-heavy', level: 2, en: 'My luggage is too heavy.', ko: '짐이 너무 무거워요.',
      tiles: ['짐이', '너무', '무거워요'], gloss: ['luggage (subject)', 'too', 'is heavy'], words: ['luggage', 'heavy'],
      traps: [
        { tile: '무겁어요', why: '무겁다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 무거워요.' },
        { tile: '짐을', why: '무거워요 describes the luggage, so 짐 is the subject and takes 이: 짐이 무거워요.' },
      ] },
    { id: 's-checkin', level: 2, en: 'Check-in is from three o’clock.', ko: '체크인은 세 시부터예요.',
      tiles: ['체크인은', '세', '시부터예요'], gloss: ['check-in (topic)', 'three', 'is from … o’clock'],
      words: ['checkin', 'numbers:three', 'numbers:oclock'],
      traps: [
        { tile: '셋', why: 'Before a counter like 시, 셋 shortens to 세: 세 시.' },
        { tile: '삼', why: 'Hours use native Korean numbers: 세 시, not 삼 시.' },
      ] },
    { id: 's-transitcard', level: 2, en: 'I buy a transport card at the convenience store.', ko: '편의점에서 교통카드를 사요.',
      tiles: ['편의점에서', '교통카드를', '사요'], gloss: ['at the convenience store', 'transport card (object)', 'buy'],
      words: ['directions:convenience', 'transitcard', 'shopping:buy'], alts: [['교통카드를', '편의점에서', '사요']],
      traps: [{ tile: '편의점에', why: 'Buying is something you do there, so the place takes 에서: 편의점에서.' }] },
    { id: 's-fastcomfy', level: 2, en: 'The subway is fast and convenient.', ko: '지하철이 빠르고 편해요.',
      tiles: ['지하철이', '빠르고', '편해요'], gloss: ['subway (subject)', 'is fast and', 'is convenient'],
      words: ['directions:subway', 'fast', 'comfortable'],
      traps: [{ tile: '빨라고', why: '-고 goes straight onto the stem: 빠르 + 고 → 빠르고. The change to 빨라 only happens before 아/어.' }] },
    { id: 's-terminal', level: 2, en: 'Where is the express bus terminal?', ko: '고속버스 터미널이 어디예요?',
      tiles: ['고속버스', '터미널이', '어디예요'], gloss: ['express bus', 'terminal (subject)', 'where is it?'],
      words: ['expressbus', 'terminal', 'directions:where'],
      traps: [{ tile: '터미널을', why: '어디예요? asks where something is. That thing is the subject, so it takes 이: 터미널이 어디예요?' }] },

    // ---- Level 3 ----
    { id: 's-transfer', level: 3, en: 'Change to Line 2 at City Hall Station.', ko: '시청역에서 이호선으로 갈아타세요.',
      tiles: ['시청역에서', '이호선으로', '갈아타세요'], gloss: ['at City Hall Station', 'to Line 2', 'please change (trains)'],
      words: ['numbers:i', 'line', 'directions:transfer'],
      traps: [{ tile: '시청역에', why: 'Changing trains is something you do there, so the station takes 에서: 시청역에서.' }] },
    // No particle questions here: (으)로 marks a choice (“make it…”), and 좌석 주세요 / 좌석을 주세요 are fine too.
    { id: 's-window', level: 3, en: 'A window seat, please.', ko: '창가 좌석으로 주세요.', drill: false,
      tiles: ['창가', '좌석으로', '주세요'], gloss: ['by the window', 'seat (as my choice)', 'please give'],
      words: ['window', 'seat', 'cafe:please'],
      traps: [{ tile: '좌석에', why: 'To choose one option, use (으)로: 창가 좌석으로 주세요 (make it a window seat).' }] },
    { id: 's-oneway', level: 3, en: 'Is it one-way or return?', ko: '편도예요, 왕복이에요?',
      tiles: ['편도예요', '왕복이에요'], gloss: ['is it one-way', 'is it a return?'], words: ['oneway', 'return'],
      traps: [
        { tile: '편도이에요', why: '편도 ends in a vowel, so it takes 예요. 이에요 goes after consonants.' },
        { tile: '왕복예요', why: '왕복 ends in a consonant, so it takes 이에요. 예요 goes after vowels.' },
      ] },
    { id: 's-lasttrain', level: 3, en: 'I missed the last train. I took a taxi.', ko: '막차를 놓쳤어요. 택시를 탔어요.',
      tiles: ['막차를', '놓쳤어요', '택시를', '탔어요'], gloss: ['last train (object)', 'missed', 'taxi (object)', 'rode / took'],
      words: ['lasttrain', 'missed', 'directions:taxi', 'directions:ride'],
      traps: [
        { tile: '막차가', why: '막차 is what you missed (the object), so it takes 를: 막차를 놓쳤어요.' },
        { tile: '타요', why: 'This already happened, so use the past: 탔어요.' },
      ] },
    { id: 's-traffic', level: 3, en: 'The traffic is really bad right now.', ko: '지금 길이 많이 막혀요.',
      tiles: ['지금', '길이', '많이', '막혀요'], gloss: ['now', 'road (subject)', 'a lot', 'is blocked'],
      words: ['day:now', 'directions:road', 'traffic'], alts: [['길이', '지금', '많이', '막혀요']],
      traps: [{ tile: '길을', why: 'The road is what’s blocked (the subject), so it takes 이: 길이 막혀요.' }] },
    { id: 's-cancel', level: 3, en: 'I’d like to cancel my booking.', ko: '예약을 취소하고 싶어요.',
      tiles: ['예약을', '취소하고', '싶어요'], gloss: ['booking (object)', 'cancel', 'I want to'], words: ['book', 'cancel'],
      traps: [{ tile: '취소해요', why: '-고 싶어요 goes straight onto the stem: 취소하 + 고 싶어요. Don’t conjugate the verb first.' }] },
    { id: 's-crowded', level: 3, en: 'The subway is crowded in the morning.', ko: '아침에는 지하철이 복잡해요.',
      tiles: ['아침에는', '지하철이', '복잡해요'], gloss: ['in the morning (topic)', 'subway (subject)', 'is crowded'],
      words: ['day:morning', 'directions:subway', 'crowded'], alts: [['지하철이', '아침에는', '복잡해요']],
      traps: [{ tile: '편해요', why: '편해요 means “it’s comfortable / convenient”. “Crowded” is 복잡해요.' }] },
    { id: 's-stay', level: 3, en: 'The place I’m staying is near the station.', ko: '숙소는 역 근처에 있어요.',
      tiles: ['숙소는', '역', '근처에', '있어요'], gloss: ['place to stay (topic)', 'station', 'near (the area)', 'is (there)'],
      words: ['stay', 'directions:station', 'directions:nearby', 'day:have'],
      traps: [{ tile: '근처에서', why: 'To say where something is, use 에 with 있어요: 근처에 있어요. 에서 is for where an action happens.' }] },
    { id: 's-exchange', level: 3, en: 'Where can I change money?', ko: '환전은 어디서 해요?',
      tiles: ['환전은', '어디서', '해요'], gloss: ['currency exchange (topic)', 'where (at)', 'do'],
      words: ['exchange', 'directions:where', 'day:do'],
      traps: [{ tile: '어디에', why: 'Doing something at a place takes 에서: 어디서 (short for 어디에서). 어디에 is for where you go or where something is.' }] },
  ],
});
