/**
 * Topic: 날씨와 계절 · Weather & seasons — talking about the weather.
 * Weather words are adjectives in the polite 해요 form (with the dictionary
 * form alongside) plus set phrases like 비가 와요 (“it’s raining”).
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'weather',
  order: 9,
  emoji: '☔',
  color: 'sky',
  title: { ko: '날씨와 계절', en: 'Weather & seasons' },
  description: { ko: '날씨 이야기', en: 'Talk about the weather' },

  notes: [
    {
      title: { ko: '날씨가 어때요?', en: 'Talking about the weather' },
      text: 'Ask **날씨가 어때요?** (How’s the weather?). The answer needs no “it”: **추워요** = It’s cold. To remark on the weather you notice right now, add **-네요** to the stem: **춥다 → 춥네요!** (Oh, it’s cold!)',
      examples: [
        { ko: '오늘 날씨가 어때요?', en: 'How’s the weather today?' },
        { ko: '맑아요. 날씨가 좋아요.', en: 'It’s clear. The weather is nice.' },
        { ko: '와, 춥네요!', en: 'Wow, it’s cold!' },
      ],
    },
    {
      title: { ko: '비가 와요', en: 'Rain and snow “come”' },
      text: 'Rain and snow **come** in Korean: **비가 와요** (it’s raining), **눈이 와요** (it’s snowing). When the rain stops, say **비가 그쳤어요**. Wind **blows**: **바람이 불어요**.',
      examples: [
        { ko: '지금 비가 와요.', en: 'It’s raining now.' },
        { ko: '어제 눈이 왔어요.', en: 'It snowed yesterday.' },
        { ko: '비가 그쳤어요.', en: 'The rain has stopped.' },
      ],
    },
    {
      title: { ko: '추워요 · 더워요', en: 'Cold and hot' },
      text: '**춥다** and **덥다** are ㅂ-irregular: before a vowel, the ㅂ turns into 우 → **추워요**, **더워요**. Before a noun they become **추운** and **더운**: 추운 겨울 (a cold winter). They’re for the weather and how your body feels. Things that are cold or hot to the touch, like water or coffee, are **차가워요** and **뜨거워요**.',
      examples: [
        { ko: '겨울은 추워요.', en: 'Winter is cold.' },
        { ko: '여름은 더워요.', en: 'Summer is hot.' },
        { ko: '커피가 뜨거워요.', en: 'The coffee is hot.' },
      ],
    },
    {
      title: { ko: '여름에 · 여름에는', en: 'In summer' },
      text: 'Say “in” a season with **에**: **여름에** (in summer), **겨울에** (in winter). To compare seasons, add **는**: **여름에는** 더워요. **겨울에는** 추워요.',
      examples: [
        { ko: '한국은 여름에 더워요.', en: 'Korea is hot in summer.' },
        { ko: '겨울에 눈이 와요.', en: 'It snows in winter.' },
        { ko: '봄에는 따뜻해요. 가을에는 시원해요.', en: 'Spring is warm. Autumn is cool.' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'weather', ko: '날씨', en: 'weather', level: 1, pos: 'noun', emoji: '🌤️', rom: 'nalssi',
      note: 'Ask 날씨가 어때요? (How’s the weather?). Nice weather: 날씨가 좋아요.',
      example: { ko: '내일 날씨가 어때요?', en: 'What’s the weather like tomorrow?' } },
    { id: 'rain', ko: '비', en: 'rain', level: 1, pos: 'noun', emoji: '🌧️', rom: 'bi',
      note: 'Rain “comes” in Korean: 비가 와요 = it’s raining.',
      example: { ko: '밖에 비가 와요?', en: 'Is it raining outside?' } },
    { id: 'snow', ko: '눈', en: 'snow', level: 1, pos: 'noun', emoji: '❄️', rom: 'nun',
      note: '눈 also means “eye”: context tells you which! Snow comes too: 눈이 와요.',
      example: { ko: '어제 눈이 많이 왔어요.', en: 'It snowed a lot yesterday.' } },
    { id: 'cold', ko: '추워요', en: "it's cold (weather)", level: 1, pos: 'adjective', emoji: '🥶', rom: 'chuwoyo', dict: '춥다',
      note: 'For cold weather or feeling cold (ㅂ-irregular: 춥 + 어요 → 추워요). Things that are cold to the touch, like water or ice, are 차가워요.',
      example: { ko: '오늘 너무 추워요!', en: 'It’s so cold today!' } },
    { id: 'hot', ko: '더워요', en: "it's hot (weather)", level: 1, pos: 'adjective', emoji: '🥵', rom: 'deowoyo', dict: '덥다',
      avoid: ['cafe:hot'],
      note: 'For hot weather or feeling hot (ㅂ-irregular: 덥 + 어요 → 더워요). Hot food or water is 뜨거워요.',
      example: { ko: '여름에는 정말 더워요.', en: 'It’s really hot in summer.' } },
    { id: 'summer', ko: '여름', en: 'summer', level: 1, pos: 'noun', emoji: '🏖️', rom: 'yeoreum',
      note: 'Korean summers are hot and humid, with a rainy season (장마).',
      example: { ko: '여름에 바다에 가요.', en: 'I go to the beach in summer.' } },
    { id: 'winter', ko: '겨울', en: 'winter', level: 1, pos: 'noun', emoji: '⛄', rom: 'gyeoul',
      note: 'Korean winters are cold and dry.',
      example: { ko: '겨울에는 스키를 타요.', en: 'I go skiing in winter.' } },
    { id: 'sun', ko: '해', en: 'sun', level: 1, pos: 'noun', emoji: '🌞', rom: 'hae',
      note: '해 also means “year”: 새해 = the New Year. The sun’s heat on your skin is 뜨거워요: 해가 뜨거워요.',
      example: { ko: '해가 나왔어요!', en: 'The sun came out!' } },

    // ---- Level 2 ----
    { id: 'spring', ko: '봄', en: 'spring (season)', level: 2, pos: 'noun', emoji: '🌸', rom: 'bom',
      note: 'In spring, Koreans go out to see the cherry blossoms (벚꽃).',
      example: { ko: '봄에는 날씨가 따뜻해요.', en: 'The weather is warm in spring.' } },
    { id: 'autumn', ko: '가을', en: 'autumn / fall', level: 2, pos: 'noun', emoji: '🍁', rom: 'gaeul',
      note: 'Korean autumn is famous for its high, clear sky (가을 하늘).',
      example: { ko: '가을에는 날씨가 시원해요.', en: 'The weather is cool in autumn.' } },
    { id: 'wind', ko: '바람', en: 'wind', level: 2, pos: 'noun', emoji: '🌬️', rom: 'baram',
      note: 'Wind “blows” in Korean: 바람이 불어요 = it’s windy.',
      example: { ko: '바람이 차가워요.', en: 'The wind is cold.' } },
    { id: 'clear', ko: '맑아요', en: "it's clear / sunny", level: 2, pos: 'adjective', emoji: '☀️', rom: 'malgayo',
      pron: '말가요', dict: '맑다', enAlt: ['fine'],
      note: 'In ㄺ, the ㄹ stays and the ㄱ moves over: [말가요]. 맑다 also means “clear” for water or a voice.',
      example: { ko: '오늘은 하늘이 맑아요.', en: 'The sky is clear today.' } },
    { id: 'cloudy', ko: '흐려요', en: "it's cloudy", level: 2, pos: 'adjective', emoji: '🌥️', rom: 'heuryeoyo', dict: '흐리다',
      enAlt: ['overcast'],
      note: '흐리 + 어요 → 흐려요 (ㅣ + ㅓ merge into ㅕ). The opposite is 맑아요.',
      example: { ko: '날씨가 좀 흐려요.', en: 'It’s a bit cloudy.' } },
    { id: 'raining', ko: '비가 와요', en: "it's raining", level: 2, pos: 'phrase', emoji: '☔', rom: 'biga wayo',
      accept: ['비 와요', '비가 내려요'], enAlt: ['it rains', 'rainy'],
      note: 'Literally “rain comes”. You’ll also hear 비가 내려요 (rain falls). When it stops: 비가 그쳤어요.',
      example: { ko: '지금 비가 와요?', en: 'Is it raining now?' } },
    { id: 'snowing', ko: '눈이 와요', en: "it's snowing", level: 2, pos: 'phrase', emoji: '🌨️', rom: 'nuni wayo',
      pron: '누니 와요', accept: ['눈 와요', '눈이 내려요'], enAlt: ['it snows', 'snowy'],
      note: 'Literally “snow comes”. The ㄴ slides over: [누니 와요]. You’ll also hear 눈이 내려요 (snow falls).',
      example: { ko: '밖에 눈이 와요!', en: 'It’s snowing outside!' } },
    { id: 'warm', ko: '따뜻해요', en: "it's warm", level: 2, pos: 'adjective', emoji: '🌷', rom: 'ttatteutaeyo',
      pron: '따뜨태요', dict: '따뜻하다',
      note: 'The ㅅ sounds like ㄷ and blends with ㅎ into ㅌ: [따뜨태요]. It works for weather, drinks and even kind people.',
      example: { ko: '오늘은 날씨가 따뜻해요.', en: 'It’s warm today.' } },
    { id: 'cool', ko: '시원해요', en: "it's cool (pleasantly)", level: 2, pos: 'adjective', emoji: '🍃', rom: 'siwonhaeyo',
      dict: '시원하다',
      note: 'A pleasant cool: a breeze, or a cold drink on a hot day. Koreans even say a hot soup is 시원해요 (refreshing)!',
      example: { ko: '여기는 정말 시원해요!', en: 'It’s really nice and cool in here!' } },
    { id: 'umbrella', ko: '우산', en: 'umbrella', level: 2, pos: 'noun', emoji: '🌂', rom: 'usan',
      note: 'Umbrellas take 쓰다, the verb for hats: 우산을 써요 = I put up my umbrella.',
      example: { ko: '우산 있어요?', en: 'Do you have an umbrella?' } },
    { id: 'season', ko: '계절', en: 'season', level: 2, pos: 'noun', emoji: '🍂', rom: 'gyejeol',
      note: '봄, 여름, 가을, 겨울: Korea has four clear seasons (사계절).',
      example: { ko: '무슨 계절을 좋아해요?', en: 'Which season do you like?' } },

    // ---- Level 3 ----
    { id: 'chilly', ko: '쌀쌀해요', en: "it's chilly", level: 3, pos: 'adjective', emoji: '🧣', rom: 'ssalssalhaeyo',
      dict: '쌀쌀하다', avoid: ['cold', 'cafe:cold'], enAlt: ['a bit cold'],
      note: 'A little cold, like a spring or autumn morning. It can also describe a cold, unfriendly manner.',
      example: { ko: '아침에는 좀 쌀쌀해요.', en: 'It’s a bit chilly in the mornings.' } },
    { id: 'humid', ko: '습해요', en: "it's humid", level: 3, pos: 'adjective', emoji: '💦', rom: 'seupaeyo', pron: '스패요',
      dict: '습하다', enAlt: ['muggy'],
      note: 'ㅂ and ㅎ blend into ㅍ: [스패요]. The opposite is 건조해요 (it’s dry).',
      example: { ko: '여름에는 너무 습해요.', en: 'It’s so humid in summer.' } },
    { id: 'windy', ko: '바람이 불어요', en: "it's windy", level: 3, pos: 'phrase', emoji: '💨', rom: 'barami bureoyo',
      pron: '바라미 부러요', accept: ['바람 불어요'], enAlt: ['wind is blowing', 'wind blows'],
      note: 'Literally “the wind blows” (불다 → 불어요). A very windy day: 바람이 많이 불어요.',
      example: { ko: '오늘은 바람이 많이 불어요.', en: 'It’s very windy today.' } },
    { id: 'cloud', ko: '구름', en: 'cloud', level: 3, pos: 'noun', emoji: '☁️', rom: 'gureum',
      note: 'Lots of clouds: 구름이 많아요. No clouds at all: 구름이 없어요.',
      example: { ko: '하늘에 구름이 많아요.', en: 'There are lots of clouds in the sky.' } },
    { id: 'sky', ko: '하늘', en: 'sky', level: 3, pos: 'noun', emoji: '🪁', rom: 'haneul',
      note: '하늘색 (sky colour) is the everyday word for light blue.',
      example: { ko: '하늘이 정말 파래요.', en: 'The sky is really blue.' } },
    { id: 'forecast', ko: '일기 예보', en: 'weather forecast', level: 3, pos: 'noun', emoji: '📺', rom: 'ilgi yebo',
      enAlt: ['forecast', 'weather report'],
      note: '일기 here is an old word for “weather”, not the 일기 that means “diary”.',
      example: { ko: '일기 예보 봤어요?', en: 'Did you see the weather forecast?' } },
    { id: 'temperature', ko: '기온', en: 'temperature (air)', level: 3, pos: 'noun', emoji: '🌡️', rom: 'gion',
      note: 'The air temperature in weather reports: 기온이 높아요 / 낮아요 (high / low). Body temperature is 체온.',
      example: { ko: '오늘은 기온이 낮아요.', en: 'The temperature is low today.' } },
    { id: 'rainyseason', ko: '장마', en: 'rainy season', level: 3, pos: 'noun', emoji: '📅☔', rom: 'jangma',
      enAlt: ['monsoon', 'monsoon season'],
      note: 'Korea’s summer rainy season, usually from late June to late July.',
      example: { ko: '장마가 시작됐어요.', en: 'The rainy season has started.' } },
    { id: 'downpour', ko: '소나기', en: 'rain shower', level: 3, pos: 'noun', emoji: '🌦️', rom: 'sonagi',
      enAlt: ['shower', 'downpour', 'sudden shower'],
      note: 'A sudden, heavy summer shower that stops as fast as it starts.',
      example: { ko: '갑자기 소나기가 왔어요.', en: 'There was a sudden shower.' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-cold', en: "It's really cold today!", ko: '오늘 정말 추워요!',
      tiles: ['오늘', '정말', '추워요'], gloss: ['today', 'really', "it's cold"], words: ['day:today', 'cold'],
      traps: [
        { tile: '차가워요', why: '차가워요 is for things that feel cold to the touch, like water or ice. For cold weather, say 추워요.' },
        { tile: '춥어요', why: '춥다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 추워요.' },
        { tile: '더워요', why: '더워요 means “it’s hot”. “Cold” is 추워요.' },
      ] },
    { id: 's-weather', en: "The weather isn't nice today.", ko: '오늘은 날씨가 안 좋아요.',
      tiles: ['오늘은', '날씨가', '안', '좋아요'], gloss: ['today (topic)', 'weather (subject)', 'not', 'is good'],
      words: ['day:today', 'weather', 'feelings:good'], alts: [['날씨가', '오늘은', '안', '좋아요']],
      traps: [{ tile: '날씨를', why: '좋아요 describes the weather, so 날씨 is its subject and takes 가: 날씨가 좋아요.' }] },
    { id: 's-hot', en: "It's so hot in summer.", ko: '여름에는 너무 더워요.',
      tiles: ['여름에는', '너무', '더워요'], gloss: ['in summer (topic)', 'so', "it's hot"], words: ['summer', 'hot'],
      traps: [
        { tile: '뜨거워요', why: '뜨거워요 is for hot things you touch, eat or drink, like water or coffee. For hot weather, say 더워요.' },
        { tile: '덥어요', why: '덥다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 더워요.' },
      ] },
    { id: 's-snow', en: "I like snow. I don't like rain.", ko: '눈이 좋아요. 비는 싫어요.',
      tiles: ['눈이', '좋아요', '비는', '싫어요'], gloss: ['snow (subject)', 'is good (I like it)', 'rain (topic)', "I don't like it"],
      words: ['snow', 'feelings:good', 'rain', 'feelings:dislike'],
      traps: [{ tile: '눈을', why: '좋아요 means “is good”, so the thing you like is its subject and takes 이: 눈이 좋아요.' }] },

    // ---- Level 2 ----
    { id: 's-sun', level: 2, en: 'The sun is really hot.', ko: '해가 정말 뜨거워요.',
      tiles: ['해가', '정말', '뜨거워요'], gloss: ['sun (subject)', 'really', 'is hot (burning)'], words: ['sun', 'cafe:hot'] },
    { id: 's-raining', level: 2, en: "It's raining. I don't have an umbrella!", ko: '비가 와요. 우산이 없어요!',
      tiles: ['비가', '와요', '우산이', '없어요'], gloss: ['rain (subject)', 'comes', 'umbrella (subject)', "there isn't"],
      words: ['raining', 'umbrella', 'day:nothave'],
      traps: [{ tile: '우산을', why: '없어요 says that something isn’t there. That thing is the subject, so it takes 이: 우산이 없어요.' }] },
    { id: 's-snowing', level: 2, en: 'It snows in winter.', ko: '겨울에 눈이 와요.',
      tiles: ['겨울에', '눈이', '와요'], gloss: ['in winter', 'snow (subject)', 'comes'], words: ['winter', 'snowing'],
      alts: [['눈이', '겨울에', '와요']],
      traps: [{ tile: '겨울에서', why: 'To say when something happens, use 에, not 에서: 겨울에 (in winter).' }] },
    { id: 's-seasons', level: 2, en: "It's warm in spring. It's cool in autumn.", ko: '봄에는 따뜻해요. 가을에는 시원해요.',
      tiles: ['봄에는', '따뜻해요', '가을에는', '시원해요'], gloss: ['in spring (topic)', "it's warm", 'in autumn (topic)', "it's cool"],
      words: ['spring', 'warm', 'autumn', 'cool'],
      traps: [{ tile: '더워요', why: '더워요 means “it’s hot”. For “warm”, say 따뜻해요.' }] },
    { id: 's-clear', level: 2, en: "It was cloudy yesterday. Today it's clear.", ko: '어제는 흐렸어요. 오늘은 맑아요.',
      tiles: ['어제는', '흐렸어요', '오늘은', '맑아요'], gloss: ['yesterday (topic)', 'was cloudy', 'today (topic)', "it's clear"],
      words: ['day:yesterday', 'cloudy', 'day:today', 'clear'],
      traps: [{ tile: '흐려요', why: '어제 (yesterday) needs the past tense: 흐렸어요.' }] },
    { id: 's-season', level: 2, en: 'Winter is a cold season.', ko: '겨울은 추운 계절이에요.',
      tiles: ['겨울은', '추운', '계절이에요'], gloss: ['winter (topic)', 'cold', 'is a season'], words: ['winter', 'cold', 'season'],
      traps: [{ tile: '차가운', why: '차가운 is for cold things you touch, like water or ice. A cold season or cold weather is 추운.' }] },
    { id: 's-wind', level: 2, en: 'The breeze is really cool.', ko: '바람이 정말 시원해요.',
      tiles: ['바람이', '정말', '시원해요'], gloss: ['wind (subject)', 'really', 'is cool'], words: ['wind', 'cool'] },

    // ---- Level 3 ----
    { id: 's-windy', level: 3, en: "It's windy. It's a bit chilly.", ko: '바람이 불어요. 좀 쌀쌀해요.',
      tiles: ['바람이', '불어요', '좀', '쌀쌀해요'], gloss: ['wind (subject)', 'blows', 'a little', "it's chilly"],
      words: ['windy', 'wind', 'chilly'],
      traps: [{ tile: '바람을', why: 'The wind is what blows (the subject), so it takes 이: 바람이 불어요.' }] },
    { id: 's-sky', level: 3, en: 'The sky is clear. There are no clouds.', ko: '하늘이 맑아요. 구름이 없어요.',
      tiles: ['하늘이', '맑아요', '구름이', '없어요'], gloss: ['sky (subject)', 'is clear', 'clouds (subject)', "there aren't"],
      words: ['sky', 'clear', 'cloud', 'day:nothave'] },
    { id: 's-forecast', level: 3, en: 'I check the temperature in the weather forecast.', ko: '일기 예보에서 기온을 봐요.',
      tiles: ['일기 예보에서', '기온을', '봐요'], gloss: ['in the weather forecast', 'temperature (object)', 'see / check'],
      words: ['forecast', 'temperature', 'day:watch'], alts: [['기온을', '일기 예보에서', '봐요']],
      traps: [{ tile: '기온이', why: '기온 is what you look at (the object of 봐요), so it takes 을: 기온을 봐요.' }] },
    { id: 's-rainyseason', level: 3, en: "There's a rainy season in summer. It's so humid.", ko: '여름에는 장마가 있어요. 너무 습해요.',
      tiles: ['여름에는', '장마가', '있어요', '너무', '습해요'],
      gloss: ['in summer (topic)', 'rainy season (subject)', 'there is', 'so', "it's humid"],
      words: ['summer', 'rainyseason', 'day:have', 'humid'],
      traps: [{ tile: '장마를', why: '있어요 says that something is there. That thing is the subject, so it takes 가: 장마가 있어요.' }] },
    { id: 's-downpour', level: 3, en: 'There was a rain shower yesterday.', ko: '어제 소나기가 왔어요.',
      tiles: ['어제', '소나기가', '왔어요'], gloss: ['yesterday', 'rain shower (subject)', 'came'],
      words: ['day:yesterday', 'downpour', 'day:come'], alts: [['소나기가', '어제', '왔어요']],
      traps: [{ tile: '와요', why: '어제 (yesterday) needs the past tense: 왔어요.' }] },
  ],
});
