/**
 * Topic: 학교와 직장 · School & work — classes and exams, the office, and the
 * set phrases of Korean school and office life (수고하셨습니다, 먼저 가 보겠습니다…).
 * Verbs are in the polite 해요 form with the dictionary form alongside; 합격했어요
 * is taught in the past (`form: 'past'`), the form you really say. The office
 * phrases keep the formal 합니다 style people use at work, even in 해요 sentences.
 * Field reference: see content/cafe.js.
 */
Mallang.content.registerTopic({
  id: 'work',
  order: 13,
  emoji: '💼',
  color: 'butter',
  title: { ko: '학교와 직장', en: 'School & work' },
  description: { ko: '수업 · 시험 · 회사 생활', en: 'Classes, exams, the office' },

  notes: [
    {
      title: { ko: '질문 있어요!', en: 'In class' },
      text: 'Need to ask something? Say **질문 있어요!** (I have a question). Didn’t catch it? **다시 한번 말해 주세요** (Please say that again). For a new word, ask **무슨 뜻이에요?** (What does it mean?). When you’ve understood, say **알겠습니다** (Got it); when you haven’t, **잘 모르겠어요** (I don’t quite get it).',
      examples: [
        { ko: '다시 한번 말해 주세요.', en: 'Could you say that again, please?' },
        { ko: '이 단어는 무슨 뜻이에요?', en: 'What does this word mean?' },
        { ko: '네, 알겠습니다!', en: 'OK, got it!' },
      ],
    },
    {
      title: { ko: '시험을 봐요', en: 'Which verb goes with it?' },
      text: 'English “takes” exams and classes, but Korean “sees” an exam: **시험을 봐요**, and “listens to” a class: **수업을 들어요**. Meetings and presentations are simply done: **회의를 해요** (have a meeting), **발표를 해요** (give a presentation). And pay is received: **월급을 받아요** (get paid).',
      examples: [
        { ko: '내일 한국어 시험을 봐요.', en: 'I’m taking a Korean exam tomorrow.' },
        { ko: '이번 학기에 수업을 네 개 들어요.', en: 'I’m taking four classes this semester.' },
        { ko: '매달 이십오 일에 월급을 받아요.', en: 'I get paid on the 25th of every month.' },
      ],
    },
    {
      title: { ko: '회사에 다녀요', en: 'Going to school or work' },
      text: '**다니다** is for a place you go to regularly, as a student or an employee: **학교에 다녀요** (I go to school), **회사에 다녀요** (I work for a company). Like 가요, it takes **에** (회사를 다녀요, with 를, is correct too). With **일해요** (work) or **공부해요** (study), the place is where you do something, so it takes **에서**.',
      examples: [
        { ko: '동생은 고등학교에 다녀요.', en: 'My younger sibling goes to high school.' },
        { ko: '제 친구는 은행에 다녀요.', en: 'My friend works at a bank.' },
        { ko: '저는 학교에서 영어를 가르쳐요.', en: 'I teach English at a school.' },
      ],
    },
    {
      title: { ko: '수고하셨습니다', en: 'Office phrases (and when to say them)' },
      text: 'On your first day, say your name, bow and add **잘 부탁드립니다** (I look forward to working with you). When the work is done, at the end of the day or a meeting, people say **수고하셨습니다** (Thanks for your hard work) to everyone, the boss too; to thank a teacher, say **감사합니다**. Leaving before the others? Say **먼저 가 보겠습니다** (I’ll be off now). **수고하세요** is for someone who keeps working as you leave, like a shop assistant or a colleague. Don’t say it to your boss or teacher: it can sound like an order.',
      examples: [
        { ko: '처음 뵙겠습니다. 마크입니다. 잘 부탁드립니다.', en: 'How do you do? I’m Mark. I look forward to working with you.' },
        { ko: '먼저 가 보겠습니다. — 네, 수고하셨습니다!', en: 'I’ll be off now. — OK, thanks for your hard work today!' },
        { ko: '안녕히 계세요. 수고하세요!', en: 'Goodbye! Keep up the good work!' },
      ],
    },
  ],

  words: [
    // ---- Level 1 ----
    { id: 'class', ko: '수업', en: 'class / lesson', level: 1, pos: 'noun', emoji: '📐', rom: 'sueop',
      enAlt: ['lesson', 'lessons', 'classes', 'lecture'],
      note: 'The lesson itself; the group of students is 반. Taking a class is 수업을 들어요, literally “listen to a class”.',
      example: { ko: '오늘 수업 있어요?', en: 'Do you have class today?' } },
    { id: 'exam', ko: '시험', en: 'exam / test', level: 1, pos: 'noun', emoji: '✍️', rom: 'siheom',
      enAlt: ['examination', 'exams', 'tests'],
      note: 'You “see” an exam in Korean: 시험을 봐요 = I take an exam.',
      example: { ko: '내일 시험이 있어요.', en: 'I have an exam tomorrow.' } },
    { id: 'classroom', ko: '교실', en: 'classroom', level: 1, pos: 'noun', emoji: '🪑', rom: 'gyosil',
      note: '교 (teaching) + 실 (room). Other rooms end in 실 too: 화장실 (restroom), 휴게실 (break room).',
      example: { ko: '교실이 어디예요?', en: 'Where’s the classroom?' } },
    { id: 'question', ko: '질문', en: 'question', level: 1, pos: 'noun', emoji: '❔', rom: 'jilmun',
      enAlt: ['questions'],
      note: 'To ask a question is 질문해요. In class, just say 질문 있어요! (I have a question).',
      example: { ko: '질문 있어요?', en: 'Any questions?' } },
    { id: 'university', ko: '대학교', en: 'university', level: 1, pos: 'noun', emoji: '🎓', rom: 'daehakgyo', pron: '대학꾜',
      accept: ['대학'], avoid: ['day:school'], enAlt: ['college', 'uni'],
      note: 'Often shortened to 대학; a university student is a 대학생. After ㄱ, the ㄱ of 교 is tense: [대학꾜].',
      example: { ko: '대학교에서 한국어를 배워요.', en: 'I’m learning Korean at university.' } },
    { id: 'computer', ko: '컴퓨터', en: 'computer', level: 1, pos: 'noun', emoji: '🖥️', rom: 'keompyuteo', enAlt: ['pc'],
      note: 'Doing something on a computer takes (으)로: 컴퓨터로 숙제를 해요 (I do my homework on the computer).',
      example: { ko: '집에 컴퓨터 있어요?', en: 'Do you have a computer at home?' } },
    { id: 'notebook', ko: '공책', en: 'notebook', level: 1, pos: 'noun', emoji: '📓', rom: 'gongchaek', accept: ['노트'],
      enAlt: ['exercise book', 'note book', 'notepad'],
      note: 'A paper notebook, also called 노트. Careful: 노트북 means a laptop!',
      example: { ko: '공책하고 연필 있어요?', en: 'Do you have a notebook and a pencil?' } },
    { id: 'word', ko: '단어', en: 'word (vocabulary)', level: 1, pos: 'noun', emoji: '🔤', rom: 'daneo', pron: '다너',
      enAlt: ['words', 'vocabulary', 'vocab'],
      note: 'The ㄴ slides over: [다너]. To ask what a word means: 이 단어는 무슨 뜻이에요?',
      example: { ko: '한국어 단어가 너무 많아요!', en: 'There are so many Korean words!' } },
    { id: 'teach', ko: '가르쳐요', en: 'teach', level: 1, pos: 'verb', emoji: '👩‍🏫', rom: 'gareuchyeoyo', dict: '가르치다',
      note: '가르치 + 어요 → 가르쳐요 (ㅣ + ㅓ merge into ㅕ). Its partner is 배워요 (learn): the teacher teaches, the students learn.',
      example: { ko: '한국어 좀 가르쳐 주세요!', en: 'Please teach me some Korean!' } },
    { id: 'difficult', ko: '어려워요', en: "it's difficult", level: 1, pos: 'adjective', emoji: '🧗', rom: 'eoryeowoyo', dict: '어렵다',
      avoid: ['feelings:hard', 'hard'], enAlt: ['difficult', 'is difficult', 'hard', "it's hard", 'is hard'],
      note: 'ㅂ-irregular: 어렵 + 어요 → 어려워요. It’s for things that are hard to do or understand; tiring, tough work is 힘들어요.',
      example: { ko: '시험이 너무 어려워요!', en: 'The exam is so hard!' } },
    { id: 'easy', ko: '쉬워요', en: "it's easy", level: 1, pos: 'adjective', emoji: '😎', rom: 'swiwoyo', dict: '쉽다',
      enAlt: ['easy', 'is easy', "it's simple", 'simple'],
      note: 'ㅂ-irregular, like 어려워요: 쉽 + 어요 → 쉬워요. Don’t mix it up with 쉬어요 (rest)!',
      example: { ko: '오늘 숙제는 쉬워요.', en: 'Today’s homework is easy.' } },
    { id: 'hard', ko: '열심히', en: 'hard (with effort)', level: 1, pos: 'adverb', emoji: '🐝', rom: 'yeolsimhi', pron: '열씸히',
      avoid: ['feelings:hard'], enAlt: ['diligently', 'with effort'],
      note: 'It goes before the verb: 열심히 공부해요 (study hard), 열심히 일해요 (work hard). 열심 is said [열씸].',
      example: { ko: '매일 열심히 공부해요.', en: 'I study hard every day.' } },

    // ---- Level 2 ----
    { id: 'meeting', ko: '회의', en: 'meeting', level: 2, pos: 'noun', emoji: '🗨️', rom: 'hoeui',
      avoid: ['hobbies:promise'], enAlt: ['work meeting', 'meetings', 'conference'],
      note: 'A work meeting; plans to meet a friend are 약속. The 의 is often said like 이 ([회이]), and the meeting room is the 회의실.',
      example: { ko: '오늘 회의가 있어요?', en: 'Is there a meeting today?' } },
    { id: 'colleague', ko: '동료', en: 'colleague / co-worker', level: 2, pos: 'noun', emoji: '🧑‍🤝‍🧑', rom: 'dongnyo', pron: '동뇨',
      enAlt: ['coworker', 'colleagues', 'co-workers', 'workmate'],
      note: 'After ㅇ, ㄹ sounds like ㄴ: [동뇨]. At work, people call each other by name + 씨 (민지 씨), or by job title + 님 (팀장님).',
      example: { ko: '동료하고 점심을 먹어요.', en: 'I have lunch with a colleague.' } },
    { id: 'boss', ko: '사장님', en: 'company president / boss', level: 2, pos: 'noun', emoji: '👑', rom: 'sajangnim',
      enAlt: ['boss', 'the boss', 'president', 'ceo', 'owner', 'company boss'],
      note: 'The head of a company, or the owner of a shop or restaurant (customers call them 사장님 too). The 님 shows respect: keep it when you talk to or about the boss.',
      example: { ko: '사장님 사무실이 어디예요?', en: 'Where’s the boss’s office?' } },
    { id: 'salary', ko: '월급', en: 'salary (monthly pay)', level: 2, pos: 'noun', emoji: '🤑', rom: 'wolgeup',
      avoid: ['shopping:money'], enAlt: ['salary', 'pay', 'monthly pay', 'monthly salary', 'wages', 'wage', 'paycheck', 'paycheque'],
      note: '월 (month) + 급 (pay): in Korea you’re usually paid once a month. Payday is 월급날, and “get paid” is 월급을 받아요.',
      example: { ko: '내일은 월급날이에요!', en: 'Tomorrow is payday!' } },
    { id: 'presentation', ko: '발표', en: 'presentation', level: 2, pos: 'noun', emoji: '📊', rom: 'balpyo',
      enAlt: ['talk', 'presentations'],
      note: 'To give one is 발표해요. Group presentations (조별 발표) are a big part of Korean university classes.',
      example: { ko: '내일 발표가 있어요. 떨려요!', en: 'I have a presentation tomorrow. I’m nervous!' } },
    { id: 'break', ko: '쉬는 시간', en: 'break (between classes)', level: 2, pos: 'noun', emoji: '🔔', rom: 'swineun sigan',
      avoid: ['day:rest'], enAlt: ['break', 'break time', 'breaks', 'recess'],
      note: 'Literally “resting time” (쉬다 + 시간). People say it at work too, but the lunch break is 점심시간.',
      example: { ko: '쉬는 시간은 십 분이에요.', en: 'The break is ten minutes long.' } },
    { id: 'firstday', ko: '첫날', en: 'the first day', level: 2, pos: 'noun', emoji: '🌱', rom: 'cheonnal', pron: '천날',
      enAlt: ['first day', 'day one'],
      note: '첫 (first) + 날 (day). ㅅ before ㄴ sounds like ㄴ: [천날]. 첫 also gives 첫 수업 (the first class).',
      example: { ko: '첫날 어땠어요?', en: 'How was your first day?' } },
    { id: 'score', ko: '점수', en: 'score / marks', level: 2, pos: 'noun', emoji: '🅰️', rom: 'jeomsu', pron: '점쑤',
      enAlt: ['score', 'scores', 'marks', 'mark', 'grade', 'grades', 'points'],
      note: 'Points are counted with 점: 구십 점 = 90 points. The ㅅ is tense: [점쑤].',
      example: { ko: '시험 점수가 몇 점이에요?', en: 'What did you get on the exam?' } },
    { id: 'attend', ko: '다녀요', en: 'attend (school, work)', level: 2, pos: 'verb', emoji: '🔄', rom: 'danyeoyo', dict: '다니다',
      avoid: ['day:go', 'day:gotowork'], enAlt: ['go to school', 'go to work', 'go regularly', 'go to', 'work for', 'work at'],
      note: '다니 + 어요 → 다녀요. It’s for a place you go to regularly: 학교에 다녀요 (I go to school), 회사에 다녀요 (I work for a company).',
      example: { ko: '어느 회사에 다녀요?', en: 'Which company do you work for?' } },
    { id: 'answer', ko: '대답해요', en: 'answer', level: 2, pos: 'verb', emoji: '✋', rom: 'daedapaeyo', pron: '대다패요',
      dict: '대답하다', enAlt: ['reply', 'respond', 'give an answer'],
      note: '대답 (a reply) + 해요, and what you answer takes 에: 질문에 대답해요. ㅂ and ㅎ blend into ㅍ: [대다패요].',
      example: { ko: '제 질문에 대답해 주세요.', en: 'Please answer my question.' } },
    { id: 'prepare', ko: '준비해요', en: 'prepare / get ready', level: 2, pos: 'verb', emoji: '🗂️', rom: 'junbihaeyo',
      dict: '준비하다', enAlt: ['prepare for', 'get ready for', 'prep'],
      note: '준비 (preparation) + 해요. In speech the 을/를 is often dropped: 시험 준비해요 (I’m studying for an exam).',
      example: { ko: '지금 회의 준비해요.', en: 'I’m getting ready for the meeting.' } },
    { id: 'lookforward', ko: '잘 부탁드립니다', en: 'I look forward to working with you', level: 2, pos: 'phrase', emoji: '🙇‍♀️',
      rom: 'jal butakdeurimnida', pron: '잘 부탁뜨림니다', avoid: ['people:nicetomeet', 'cafe:thanks'],
      accept: ['잘 부탁합니다', '잘 부탁해요', '잘 부탁드려요'],
      enAlt: ['look forward to working with you', 'please take care of me', 'please treat me well', 'please look after me',
        'nice to work with you', "I'm counting on you"],
      note: 'Said with a bow when you join a new class or team, right after your name. It also asks someone to take care of a job for you: 이거 잘 부탁드립니다.',
      example: { ko: '안녕하세요, 마크입니다. 잘 부탁드립니다!', en: 'Hello, I’m Mark. I look forward to working with you!' } },
    { id: 'thanksforwork', ko: '수고하셨습니다', en: 'thanks for your hard work', level: 2, pos: 'phrase', emoji: '👏',
      rom: 'sugohasyeotseumnida', pron: '수고하셛씀니다', avoid: ['cafe:thanks'], accept: ['수고하셨어요', '수고 많으셨습니다'],
      enAlt: ['thank you for your hard work', 'thanks for your work', 'good work', 'good work today', 'good job', 'well done', 'great work'],
      note: 'Said when the work is done: at the end of the day, a meeting or an exam. At work people say it to everyone, the boss too (though some frown on that). Teachers say it to students; to thank a teacher, 감사합니다 is safer.',
      example: { ko: '오늘도 수고하셨습니다!', en: 'Thanks for all your hard work today!' } },

    // ---- Level 3 ----
    { id: 'businesstrip', ko: '출장', en: 'business trip', level: 3, pos: 'noun', emoji: '👔🧳', rom: 'chuljang', pron: '출짱',
      avoid: ['hobbies:trip'], enAlt: ['work trip', 'business travel', 'business trips'],
      note: 'You “go” on one: 출장을 가요, or just 출장 가요. After ㄹ, the ㅈ is tense: [출짱].',
      example: { ko: '출장 잘 다녀오세요!', en: 'Have a good business trip!' } },
    { id: 'breakroom', ko: '휴게실', en: 'break room / staff lounge', level: 3, pos: 'noun', emoji: '🪴', rom: 'hyugesil',
      enAlt: ['breakroom', 'staff room', 'staffroom', 'lounge'],
      note: '휴게 (rest) + 실 (room), like 교실. A motorway rest stop is a 휴게소, famous for its snacks.',
      example: { ko: '휴게실에 커피가 있어요.', en: 'There’s coffee in the break room.' } },
    { id: 'overtime', ko: '야근', en: 'working late / overtime', level: 3, pos: 'noun', emoji: '🕙', rom: 'yageun',
      enAlt: ['overtime', 'working late', 'work late', 'late work', 'night work'],
      note: '야 (night) + 근 (work): staying late at the office. “I’m working late” is 야근해요.',
      example: { ko: '오늘도 야근해요?', en: 'Are you working late again today?' } },
    { id: 'graduation', ko: '졸업', en: 'graduation', level: 3, pos: 'noun', emoji: '🧑‍🎓', rom: 'joreop', pron: '조럽',
      enAlt: ['graduating', 'graduate'],
      note: 'To graduate is 졸업해요, and the school takes 을/를: 대학교를 졸업했어요. Congratulate someone with 졸업 축하해요!',
      example: { ko: '졸업 축하해요!', en: 'Congratulations on your graduation!' } },
    { id: 'entrance', ko: '입학', en: 'starting school (enrolment)', level: 3, pos: 'noun', emoji: '🎊', rom: 'iphak', pron: '이팍',
      avoid: ['numbers:start'],
      enAlt: ['admission', 'enrolment', 'enrollment', 'entering school', 'starting school', 'school entrance', 'entrance'],
      note: 'Starting at a school or university: the school takes 에 (대학교에 입학해요). The Korean school year starts in March.',
      example: { ko: '동생이 삼월에 입학해요.', en: 'My younger sibling starts school in March.' } },
    { id: 'exercises', ko: '연습 문제', en: 'practice exercises', level: 3, pos: 'noun', emoji: '📄', rom: 'yeonseum munje',
      pron: '연슴 문제', enAlt: ['exercises', 'practice questions', 'practice problems', 'practice exercise'],
      note: '연습 (practice) + 문제 (question, problem). You “solve” them: 연습 문제를 풀어요. ㅂ before ㅁ sounds like ㅁ: [연슴].',
      example: { ko: '연습 문제를 풀어 보세요.', en: 'Try doing the practice exercises.' } },
    { id: 'staffdinner', ko: '회식', en: 'staff dinner (after work)', level: 3, pos: 'noun', emoji: '🍻', rom: 'hoesik',
      avoid: ['day:evening'],
      enAlt: ['staff dinner', 'team dinner', 'company dinner', 'work dinner', 'office party', 'work night out', 'team night out'],
      note: 'Dinner, and often drinks, with your whole team after work, usually paid for by the company.',
      example: { ko: '회식은 어디에서 해요?', en: 'Where’s the team dinner?' } },
    { id: 'passed', ko: '합격했어요', en: 'passed (an exam)', level: 3, pos: 'verb', emoji: '🏅', rom: 'hapgyeokaesseoyo',
      pron: '합껴캐써요', dict: '합격하다', form: 'past',
      enAlt: ['passed', 'I passed', 'passed the exam', 'passed the test', 'got in', 'got accepted'],
      note: '합격 (passing) + 했어요, and the exam takes 에: 시험에 합격했어요! Failing is 떨어졌어요 (literally “fell”).',
      example: { ko: '대학교에 합격했어요!', en: 'I got into university!' } },
    { id: 'keepitup', ko: '수고하세요', en: 'keep up the good work', level: 3, pos: 'phrase', emoji: '🙌', rom: 'sugohaseyo',
      avoid: ['weather:careful'], accept: ['수고하십시오'], enAlt: ['keep up the hard work', 'keep it up'],
      note: 'Said as you leave someone who is still working: a shop assistant, a taxi driver, a colleague at your level. Not to your boss or teacher: it can sound like an order.',
      example: { ko: '기사님, 감사합니다. 수고하세요!', en: 'Thank you, driver. Keep up the good work!' } },
    { id: 'leavingfirst', ko: '먼저 가 보겠습니다', en: "I'll be off now (before you)", level: 3, pos: 'phrase', emoji: '🌆',
      rom: 'meonjeo ga bogetseumnida', pron: '먼저 가 보겓씀니다',
      avoid: ['hobbies:willgo', 'day:go', 'day:goout', 'day:leavework'],
      accept: ['먼저 들어가 보겠습니다', '먼저 가겠습니다', '먼저 가 볼게요'],
      enAlt: ["I'll be off", "I'm off", "I'll be going", "I'll be going now", "I'll go first", "I'm leaving first", 'leaving first'],
      note: '먼저 = first, before the others. Said with a small bow when you leave work while others (especially your boss) are still there; the reply is often 네, 수고하셨습니다!',
      example: { ko: '죄송합니다. 오늘은 먼저 가 보겠습니다.', en: 'Sorry, I’m heading off first today.' } },
    { id: 'memorise', ko: '외워요', en: 'memorise / learn by heart', level: 3, pos: 'verb', emoji: '🧠', rom: 'oewoyo', dict: '외우다',
      enAlt: ['memorize', 'learn by heart'],
      note: '외우 + 어요 → 외워요 (ㅜ + ㅓ merge into ㅝ), just like 배워요. What you memorise takes 을/를: 단어를 외워요.',
      example: { ko: '이 단어 외웠어요?', en: 'Have you memorised this word?' } },

    // ---- More words ----
    { id: 'pencil', ko: '연필', en: 'pencil', level: 1, pos: 'noun', emoji: '✏️', rom: 'yeonpil', enAlt: ['pencils'],
      note: '연 (lead) + 필 (writing brush). A pen is 펜, and a ballpoint pen is 볼펜.',
      example: { ko: '연필 있어요?', en: 'Do you have a pencil?' } },
    { id: 'desk', ko: '책상', en: 'desk', level: 1, pos: 'noun', emoji: '🧑‍💻', rom: 'chaeksang', pron: '책쌍',
      enAlt: ['desks', 'study desk', 'writing desk'],
      note: '책 (book) + 상 (table): a table for books. After ㄱ, the ㅅ is tense: [책쌍].',
      example: { ko: '책상에 컴퓨터가 있어요.', en: 'There’s a computer on the desk.' } },
    { id: 'office', ko: '사무실', en: 'office', level: 1, pos: 'noun', emoji: '🖇️', rom: 'samusil',
      enAlt: ['office room'],
      note: '사무 (office work) + 실 (room), like 교실. 회사 is the company; the 사무실 is the room or floor where you work.',
      example: { ko: '사무실이 어디예요?', en: 'Where’s the office?' } },
    { id: 'gotit', ko: '알겠습니다', en: 'got it / understood', level: 1, pos: 'phrase', emoji: '🫡', rom: 'algetseumnida',
      pron: '알겓씀니다', dict: '알다', accept: ['알겠어요'], avoid: ['cafe:yes', 'cafe:okay'],
      enAlt: ['got it', 'understood', 'i understand', 'i see', 'will do', 'i got it', 'roger'],
      note: 'The formal “Got it / Will do”, for a teacher, a boss or a customer; in everyday polite talk, it’s 알겠어요. Careful: 알아요 means “I know”.',
      example: { ko: '내일까지요? 네, 알겠습니다.', en: 'By tomorrow? OK, will do.' } },
    { id: 'textbook', ko: '교과서', en: 'textbook', level: 2, pos: 'noun', emoji: '📘', rom: 'gyogwaseo',
      avoid: ['day:book'], enAlt: ['textbooks', 'coursebook', 'course book', 'schoolbook'],
      note: '교과 (school subject) + 서 (book). In class you’ll hear 교과서 이십 쪽을 펴세요 (Open your textbooks to page 20): 쪽 counts pages.',
      example: { ko: '교과서를 안 가져왔어요.', en: 'I didn’t bring my textbook.' } },
    { id: 'explain', ko: '설명해요', en: 'explain', level: 2, pos: 'verb', emoji: '💡', rom: 'seolmyeonghaeyo',
      dict: '설명하다', enAlt: ['explains', 'explain it', 'give an explanation'],
      note: '설명 (explanation) + 해요. Ask for help with 설명해 주세요 (Please explain), and what you explain takes 을/를: 이 단어를 설명해 주세요.',
      example: { ko: '친구가 다시 설명해요.', en: 'My friend explains it again.' } },
    { id: 'ask', ko: '물어봐요', en: 'ask', level: 2, pos: 'verb', emoji: '🙋‍♂️', rom: 'mureobwayo', pron: '무러봐요',
      dict: '물어보다', avoid: ['question'], enAlt: ['ask about', 'ask someone', 'inquire', 'enquire'],
      note: '물어보다 = ask (literally “ask and see”). The person you ask takes 한테: 선생님한테 물어봐요. 물어보 + 아요 → 물어봐요 (ㅗ + ㅏ merge into ㅘ).',
      example: { ko: '친구한테 물어봐요.', en: 'I’ll ask a friend.' } },
    { id: 'notsure', ko: '잘 모르겠어요', en: "I'm not sure", level: 2, pos: 'phrase', emoji: '🫤', rom: 'jal moreugesseoyo',
      pron: '잘 모르게써요', dict: '모르다', accept: ['모르겠어요', '잘 모르겠습니다'], avoid: ['past:didntknow'],
      enAlt: ['not sure', "i don't know", "i don't quite get it", "i don't understand", "i don't really know", "i'm not really sure", 'no idea'],
      note: 'A softer way to say “I don’t know” than 몰라요: the -겠- makes it less blunt. In class, it also means “I don’t quite get it”.',
      example: { ko: '미안해요, 잘 모르겠어요.', en: 'Sorry, I’m not sure.' } },
    { id: 'parttime', ko: '아르바이트', en: 'part-time job', level: 2, pos: 'noun', emoji: '🧋', rom: 'areubaiteu',
      accept: ['알바'], avoid: ['people:job', 'day:work'],
      enAlt: ['part time job', 'part-time work', 'part time work', 'part-time', 'side job', 'student job'],
      note: 'From German “Arbeit” (work), and usually shortened to 알바. Having one is 아르바이트를 해요, and the person is an 알바생.',
      example: { ko: '편의점에서 아르바이트를 해요.', en: 'I work part-time at a convenience store.' } },
    { id: 'interview', ko: '면접', en: 'job interview', level: 3, pos: 'noun', emoji: '👩‍💼', rom: 'myeonjeop',
      enAlt: ['interview', 'interviews', 'job interviews'],
      note: 'A job (or school) interview. Like an exam, you “see” it: 면접을 봐요 = I have an interview. An interview on TV is 인터뷰.',
      example: { ko: '면접 잘 봤어요?', en: 'How did your interview go?' } },
    { id: 'gotjob', ko: '취직했어요', en: 'got a job', level: 3, pos: 'verb', emoji: '💼🎉', rom: 'chwijikaesseoyo',
      pron: '취지캐써요', dict: '취직하다', form: 'past',
      enAlt: ['i got a job', 'found a job', 'i found a job', 'got hired', 'was hired', 'landed a job'],
      note: '취직 (getting a job) + 했어요, and the company takes 에: 은행에 취직했어요 (I got a job at a bank). Congratulate with 취직 축하해요!',
      example: { ko: '언니가 은행에 취직했어요!', en: 'My older sister got a job at a bank!' } },
    { id: 'major', ko: '전공', en: 'major (subject)', level: 3, pos: 'noun', emoji: '🔬', rom: 'jeongong',
      enAlt: ['major', 'subject', 'field of study', 'main subject', 'degree subject', 'specialization', 'specialisation'],
      note: 'Your main subject at university: 전공이 뭐예요? (What’s your major?). To major in something is 전공해요: 경영학을 전공해요 (I’m majoring in business).',
      example: { ko: '전공이 뭐예요?', en: 'What’s your major?' } },
    { id: 'businesscard', ko: '명함', en: 'business card', level: 3, pos: 'noun', emoji: '📇', rom: 'myeongham',
      avoid: ['shopping:card'], enAlt: ['business cards', 'name card', 'namecard', 'calling card'],
      note: 'In Korea, give and take it with both hands and a small bow, and read it before you put it away.',
      example: { ko: '명함 한 장 주세요.', en: 'Could I have your business card?' } },
    { id: 'quit', ko: '그만둬요', en: 'quit (a job, school)', level: 3, pos: 'verb', emoji: '🏳️', rom: 'geumandwoyo',
      dict: '그만두다', avoid: ['day:leavework'],
      enAlt: ['quit', 'quits', 'stop', 'give up', 'resign', 'leave a job', 'quit my job', 'drop out'],
      note: '그만 (stop there) + 두다 (leave it): to stop for good, like a job or a class: 회사를 그만둬요. 그만두 + 어요 → 그만둬요 (ㅜ + ㅓ merge into ㅝ).',
      example: { ko: '왜 회사를 그만둬요?', en: 'Why are you quitting your job?' } },
    { id: 'tardy', ko: '지각했어요', en: 'was late (for school, work)', level: 3, pos: 'verb', emoji: '🏃‍♀️', rom: 'jigakaesseoyo',
      pron: '지가캐써요', dict: '지각하다', form: 'past', avoid: ['past:late'],
      enAlt: ['was late', 'i was late', 'late', 'came late', 'arrived late', 'late for school', 'late for work', 'late for class'],
      note: '지각 = being late for school or work, and the place takes 에: 학교에 지각했어요. Late to meet a friend? That’s 늦었어요.',
      example: { ko: '늦잠을 자서 지각했어요.', en: 'I overslept, so I was late.' } },
  ],

  sentences: [
    // ---- Level 1 ----
    { id: 's-question', en: 'Teacher, I have a question.', ko: '선생님, 질문이 있어요.',
      tiles: ['선생님', '질문이', '있어요'], gloss: ['teacher (calling them)', 'question (subject)', 'there is / I have'],
      words: ['people:teacher', 'question', 'day:have'],
      traps: [{ tile: '질문을', why: '있어요 says that something is there (or that you have it). That thing is the subject, so it takes 이: 질문이 있어요.' }] },
    { id: 's-easy', en: 'The classes are easy, but the exams are hard.', ko: '수업은 쉬워요. 그런데 시험은 어려워요.',
      tiles: ['수업은', '쉬워요', '그런데', '시험은', '어려워요'],
      gloss: ['classes (topic)', 'are easy', 'but', 'exams (topic)', 'are difficult'],
      words: ['class', 'easy', 'exam', 'difficult'],
      traps: [
        { tile: '쉽어요', why: '쉽다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 쉬워요.' },
        { tile: '어렵어요', why: '어렵다 is ㅂ-irregular: before a vowel, ㅂ turns into 우 → 어려워요.' },
        { tile: '쉬어요', why: '쉬어요 means “I rest” (쉬다). “It’s easy” is 쉬워요.' },
      ] },
    { id: 's-hard', en: 'I’m working hard to learn Korean.', ko: '저는 한국어를 열심히 배워요.',
      tiles: ['저는', '한국어를', '열심히', '배워요'], gloss: ['I (topic)', 'Korean (object)', 'hard (with effort)', 'learn'],
      words: ['people:me', 'day:korean', 'hard', 'hobbies:learn'], alts: [['저는', '열심히', '한국어를', '배워요']],
      traps: [{ tile: '가르쳐요', why: '가르쳐요 means “teach”. “Learn” is 배워요.' }] },
    { id: 's-teach', en: 'My mum teaches piano.', ko: '엄마가 피아노를 가르쳐요.',
      tiles: ['엄마가', '피아노를', '가르쳐요'], gloss: ['mum (subject)', 'piano (object)', 'teaches'],
      words: ['people:mom', 'hobbies:piano', 'teach'],
      traps: [{ tile: '배워요', why: '배워요 means “learn”. Mum is the teacher here, so she 가르쳐요 (teaches).' }] },
    { id: 's-notebook', en: 'There’s a notebook in my bag.', ko: '가방에 공책이 있어요.',
      tiles: ['가방에', '공책이', '있어요'], gloss: ['in the bag', 'notebook (subject)', 'there is'],
      words: ['shopping:bag', 'notebook', 'day:have'],
      traps: [
        { tile: '가방에서', why: 'To say where something is, use 에 with 있어요: 가방에 있어요. 에서 is for where an action happens.' },
        { tile: '공책을', why: '있어요 says that something is there. That thing is the subject, so it takes 이: 공책이 있어요.' },
      ] },

    // ---- Level 2 ----
    { id: 's-attend', level: 2, en: 'I go to university.', ko: '저는 대학교에 다녀요.',
      tiles: ['저는', '대학교에', '다녀요'], gloss: ['I (topic)', 'to university', 'go (regularly), attend'],
      words: ['people:me', 'university', 'attend'],
      traps: [{ tile: '대학교에서', why: '다녀요 is a verb of going, like 가요, so the place takes 에: 대학교에 다녀요.' }] },
    { id: 's-answer', level: 2, en: 'The teacher asks questions. The students answer.', ko: '선생님이 질문하세요. 학생들이 대답해요.',
      tiles: ['선생님이', '질문하세요', '학생들이', '대답해요'],
      gloss: ['teacher (subject)', 'asks a question (respectful)', 'students (subject)', 'answer'],
      words: ['people:teacher', 'question', 'people:student', 'answer'],
      traps: [
        { tile: '가르치세요', why: '가르치세요 means “(the teacher) teaches”. Asking a question is 질문하세요.' },
        { tile: '학생들을', why: 'The students are the ones who answer (the subject), so they take 이: 학생들이 대답해요.' },
      ] },
    { id: 's-boss', level: 2, en: 'I have a meeting with the boss today.', ko: '오늘 사장님하고 회의가 있어요.',
      tiles: ['오늘', '사장님하고', '회의가', '있어요'], gloss: ['today', 'with the boss', 'meeting (subject)', 'there is'],
      words: ['day:today', 'boss', 'meeting', 'day:have'],
      traps: [
        { tile: '사장하고', why: 'Talking about your boss, always add 님 for respect: 사장님하고.' },
        { tile: '회의를', why: '있어요 says that something is there. That thing is the subject, so it takes 가: 회의가 있어요.' },
      ] },
    { id: 's-salary', level: 2, en: 'I got paid today!', ko: '오늘 월급을 받았어요!',
      tiles: ['오늘', '월급을', '받았어요'], gloss: ['today', 'salary (object)', 'received'],
      words: ['day:today', 'salary', 'past:received'], alts: [['월급을', '오늘', '받았어요']],
      traps: [
        { tile: '받아요', why: 'The English says “got paid” (the past), so use 받았어요.' },
        { tile: '월급이', why: '월급 is what you receive (the object of 받았어요), so it takes 을: 월급을 받았어요.' },
      ] },
    { id: 's-presentation', level: 2, en: 'I’m preparing my presentation now.', ko: '지금 발표를 준비해요.',
      tiles: ['지금', '발표를', '준비해요'], gloss: ['now', 'presentation (object)', 'prepare'],
      words: ['day:now', 'presentation', 'prepare'], alts: [['발표를', '지금', '준비해요']],
      traps: [{ tile: '발표가', why: '발표 is what you prepare (the object), so it takes 를: 발표를 준비해요.' }] },
    { id: 's-firstday', level: 2, en: 'Today is my first day. I look forward to working with you!', ko: '오늘이 첫날이에요. 잘 부탁드립니다!',
      tiles: ['오늘이', '첫날이에요', '잘 부탁드립니다'], gloss: ['today (subject)', 'is the first day', 'I look forward to working with you'],
      words: ['day:today', 'firstday', 'lookforward'],
      traps: [{ tile: '수고하셨습니다', why: '수고하셨습니다 thanks people when the work is done. Meeting new colleagues on your first day, say 잘 부탁드립니다.' }] },
    { id: 's-classroom', level: 2, en: 'The students are studying hard in the classroom.', ko: '학생들이 교실에서 열심히 공부해요.',
      tiles: ['학생들이', '교실에서', '열심히', '공부해요'], gloss: ['students (subject)', 'in the classroom', 'hard (with effort)', 'study'],
      words: ['people:student', 'classroom', 'hard', 'day:study'], alts: [['교실에서', '학생들이', '열심히', '공부해요']],
      traps: [{ tile: '교실에', why: 'Studying is something you do there, so the place takes 에서: 교실에서.' }] },
    { id: 's-computer', level: 2, en: 'I don’t have a computer, so I do my homework at the library.',
      ko: '컴퓨터가 없어요. 그래서 도서관에서 숙제를 해요.',
      tiles: ['컴퓨터가', '없어요', '그래서', '도서관에서', '숙제를', '해요'],
      gloss: ['computer (subject)', "there isn't / I don't have", 'so', 'at the library', 'homework (object)', 'do'],
      words: ['computer', 'day:nothave', 'day:library', 'day:homework', 'day:do'],
      traps: [
        { tile: '컴퓨터를', why: '없어요 says that something isn’t there (or that you don’t have it). That thing is the subject, so it takes 가: 컴퓨터가 없어요.' },
        { tile: '도서관에', why: 'Doing homework is something you do there, so the place takes 에서: 도서관에서.' },
      ] },

    // ---- Level 3 ----
    { id: 's-trip', level: 3, en: 'I’m going on a business trip next week, so I’m working late again today.',
      ko: '다음 주에 출장 가요. 그래서 오늘도 야근해요.',
      tiles: ['다음 주에', '출장', '가요', '그래서', '오늘도', '야근해요'],
      gloss: ['next week', 'business trip', 'go', 'so', 'today too', 'work late'],
      words: ['hobbies:nextweek', 'businesstrip', 'day:go', 'overtime'],
      traps: [
        { tile: '다음 주에서', why: 'To say when something happens, use 에, not 에서: 다음 주에.' },
        { tile: '퇴근해요', why: '퇴근해요 means “leave work”. Working late is 야근해요.' },
      ] },
    { id: 's-graduation', level: 3, en: 'I’ve graduated from school. Now I’m starting university.', ko: '학교를 졸업했어요. 이제 대학교에 입학해요.',
      tiles: ['학교를', '졸업했어요', '이제', '대학교에', '입학해요'],
      gloss: ['school (object)', 'graduated', 'now', 'into university', 'enter (start)'],
      words: ['day:school', 'graduation', 'university', 'entrance'],
      traps: [
        { tile: '학교에서', why: '졸업하다 takes the school as its object: 학교를 졸업했어요. English says “graduate from”, but Korean doesn’t use 에서 here.' },
        { tile: '대학교에서', why: '입학하다 (to start at a school) takes 에 for the school you go into: 대학교에 입학해요.' },
        { tile: '대학교가', why: 'You’re the one starting university (the subject). The university takes 에: 대학교에 입학해요.' },
      ] },
    { id: 's-exercises', level: 3, en: 'I’ve done all the practice exercises.', ko: '연습 문제를 다 풀었어요.',
      tiles: ['연습 문제를', '다', '풀었어요'], gloss: ['practice exercises (object)', 'all', 'solved (did)'],
      words: ['exercises'],
      traps: [{ tile: '풀어요', why: 'The English says “I’ve done” (they’re finished), so use the past: 풀었어요.' }] },
    { id: 's-staffdinner', level: 3, en: 'There’s a team dinner on Friday evening.', ko: '금요일 저녁에 회식이 있어요.',
      tiles: ['금요일', '저녁에', '회식이', '있어요'], gloss: ['Friday', 'in the evening', 'staff dinner (subject)', 'there is'],
      words: ['numbers:friday', 'day:evening', 'staffdinner', 'day:have'], alts: [['회식이', '금요일', '저녁에', '있어요']],
      traps: [
        { tile: '회식을', why: '있어요 says that something is there. That thing is the subject, so it takes 이: 회식이 있어요.' },
        { tile: '저녁에서', why: 'To say when something happens, use 에, not 에서: 저녁에.' },
      ] },
    // No particle questions here: 시험에서 합격했어요 is also heard (에서 = in the exam), so 에서 isn't clearly wrong.
    { id: 's-passed', level: 3, en: 'I passed the exam! My score is really good.', ko: '시험에 합격했어요! 점수가 정말 좋아요.', drill: false,
      tiles: ['시험에', '합격했어요', '점수가', '정말', '좋아요'],
      gloss: ['exam (with 에)', 'passed', 'score (subject)', 'really', 'is good'],
      words: ['exam', 'passed', 'score', 'feelings:good'],
      traps: [
        { tile: '시험이', why: 'You’re the one who passed (the subject). The exam takes 에: 시험에 합격했어요.' },
        { tile: '합격해요', why: 'It already happened: “passed” is the past, 합격했어요.' },
      ] },
    { id: 's-memorise', level: 3, en: 'I memorise ten words every day.', ko: '매일 단어를 열 개 외워요.',
      tiles: ['매일', '단어를', '열', '개', '외워요'], gloss: ['every day', 'words (object)', 'ten (native)', '(counter for things)', 'memorise'],
      words: ['day:everyday', 'word', 'numbers:ten', 'numbers:item', 'memorise'], alts: [['단어를', '매일', '열', '개', '외워요']],
      traps: [
        { tile: '십', why: 'Counting things with 개 uses native Korean numbers: 열 개, not 십 개.' },
        { tile: '단어가', why: '단어 is what you memorise (the object), so it takes 를: 단어를 외워요.' },
      ] },
    { id: 's-keepitup', level: 3, en: 'Thank you! Keep up the good work!', ko: '감사합니다. 수고하세요!',
      tiles: ['감사합니다', '수고하세요'], gloss: ['thank you', 'keep up the good work'],
      words: ['cafe:thanks', 'keepitup'],
      traps: [{ tile: '수고하셨습니다', why: '수고하셨습니다 (thanks for your hard work) is for when the work is done. As you leave someone who is still working, like a shop assistant, say 수고하세요.' }] },
    { id: 's-leavingfirst', level: 3, en: 'I’ll be off now. Thanks for your hard work, everyone!', ko: '저 먼저 가 보겠습니다. 수고하셨습니다!',
      tiles: ['저', '먼저', '가 보겠습니다', '수고하셨습니다'],
      gloss: ['I', 'first (before you)', 'will go (humble)', 'thanks for your hard work'],
      words: ['people:me', 'leavingfirst', 'thanksforwork'],
      traps: [{ tile: '수고하세요', why: '수고하세요 means “keep up the good work”, and it isn’t for your boss. “Thanks for your hard work” is 수고하셨습니다.' }] },
    { id: 's-breakroom', level: 3, en: 'In the breaks, I have coffee with a colleague in the break room.',
      ko: '쉬는 시간에는 동료하고 휴게실에서 커피를 마셔요.',
      tiles: ['쉬는 시간에는', '동료하고', '휴게실에서', '커피를', '마셔요'],
      gloss: ['in the breaks (topic)', 'with a colleague', 'in the break room', 'coffee (object)', 'drink'],
      words: ['break', 'colleague', 'breakroom', 'cafe:coffee', 'day:drink'],
      alts: [['쉬는 시간에는', '휴게실에서', '동료하고', '커피를', '마셔요']],
      traps: [{ tile: '휴게실에', why: 'Having coffee is something you do there, so the place takes 에서: 휴게실에서.' }] },

    // ---- More sentences ----
    { id: 's-desk', en: 'There’s a pencil and a notebook on the desk.', ko: '책상에 연필하고 공책이 있어요.',
      tiles: ['책상에', '연필하고', '공책이', '있어요'], gloss: ['on the desk', 'pencil and', 'notebook (subject)', 'there is'],
      words: ['desk', 'pencil', 'notebook', 'day:have'], alts: [['연필하고', '공책이', '책상에', '있어요']],
      traps: [
        { tile: '책상에서', why: 'To say where something is, use 에 with 있어요: 책상에 있어요. 에서 is for where an action happens.' },
        { tile: '공책을', why: '있어요 says that something is there. That thing is the subject, so it takes 이: 공책이 있어요.' },
      ] },
    { id: 's-office', level: 2, en: 'Please come to the office. — OK, will do.', ko: '사무실로 오세요. 네, 알겠습니다.',
      tiles: ['사무실로', '오세요', '네', '알겠습니다'], gloss: ['to the office', 'please come', 'yes', 'got it (formal)'],
      words: ['office', 'day:come', 'cafe:yes', 'gotit'],
      traps: [
        { tile: '사무실에서', why: '사무실에서 오세요 would mean “come from the office”. To say where to come, use 로 (toward): 사무실로 오세요.' },
        { tile: '가세요', why: '가세요 means “please go (there)”. To ask someone to come here, use 오세요.' },
        { tile: '알아요', why: '알아요 means “I know”. To say “Got it, will do”, use 알겠습니다.' },
      ] },
    { id: 's-explain', level: 2, en: 'I don’t quite get it. Could you explain it again?', ko: '잘 모르겠어요. 다시 설명해 주세요.',
      tiles: ['잘 모르겠어요', '다시', '설명해', '주세요'], gloss: ['I don’t quite get it', 'again', 'explain', 'please (for me)'],
      words: ['notsure', 'explain', 'cafe:please'],
      traps: [
        { tile: '알겠어요', why: '알겠어요 means “Got it”. When you don’t understand, say 잘 모르겠어요.' },
        { tile: '대답해', why: '대답해 주세요 means “please answer”. To ask for an explanation, use 설명해 주세요.' },
        { tile: '설명해요', why: 'Before 주세요, the verb ends in 해, not 해요: 설명해 주세요.' },
      ] },
    { id: 's-interview', level: 3, en: 'In the interview, they asked me what my major was.', ko: '면접에서 전공을 물어봤어요.',
      tiles: ['면접에서', '전공을', '물어봤어요'], gloss: ['in the interview', 'major (object)', 'asked'],
      words: ['interview', 'major', 'ask'],
      traps: [
        { tile: '면접에', why: 'Asking is something they did there, so the interview takes 에서: 면접에서.' },
        { tile: '전공이', why: '전공 is what they asked about (the object), so it takes 을: 전공을 물어봤어요.' },
        { tile: '대답했어요', why: '대답했어요 means “answered”. The English says they asked: 물어봤어요.' },
      ] },
    { id: 's-gotjob', level: 3, en: 'I got a job at a bank. Here’s my business card.', ko: '은행에 취직했어요. 제 명함이에요.',
      tiles: ['은행에', '취직했어요', '제', '명함이에요'], gloss: ['at a bank (into)', 'got a job', 'my', 'is a business card'],
      words: ['directions:bank', 'gotjob', 'businesscard'],
      traps: [
        { tile: '은행에서', why: '취직하다 takes 에 for the place you join, like 입학하다: 은행에 취직했어요.' },
        { tile: '은행이', why: 'You’re the one who got the job (the subject). The bank takes 에: 은행에 취직했어요.' },
        { tile: '저', why: 'Before a noun, “my” is 제 (저 + 의): 제 명함.' },
      ] },
    { id: 's-quit', level: 3, en: 'I quit my part-time job last month.', ko: '지난달에 아르바이트를 그만뒀어요.',
      tiles: ['지난달에', '아르바이트를', '그만뒀어요'], gloss: ['last month', 'part-time job (object)', 'quit'],
      words: ['past:lastmonth', 'parttime', 'quit'], alts: [['아르바이트를', '지난달에', '그만뒀어요']],
      traps: [
        { tile: '지난달에서', why: 'To say when something happens, use 에, not 에서: 지난달에.' },
        { tile: '아르바이트가', why: '아르바이트 is what you quit (the object), so it takes 를: 아르바이트를 그만뒀어요.' },
        { tile: '그만둬요', why: 'It happened last month, so use the past: 그만뒀어요.' },
      ] },
  ],
});
